### PR TITLE
[core][ios] Give precedence to `UIBackgroundFetchResult.newData` over `.failed` in ExpoAppDelegate

### LINKED ISSUE #19310: Incorrect callback passed when `.newData` is available
### Summary

When a callback is invoked the `.newData` the current implementation will favor `.failed` `UIBackgroundFetchResult` over it. We think this is a mistake, and that a `UIBackgroundFetchResult.newData` should be passed if one was provided.

### What platform(s) does this occur on?

iOS

### Environment
```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.4.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.9.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: bare
```
### Minimal reproducible example

impossible to reproduce without a project, but we can provide one if needed.

### PR DESCRIPTION
**Pull request by ferologics**
### Why
due to the else if condition a `.failed` UIBackgroundFetchResult would always be used even though other callbacks would pass `.newData`.

### How
The change assumes that even though `.failed` fetch results are passed we want to be optimistic about the `.newData` rather than the `.failed` callback.

### Test Plan
idk bruv

fixes #19310

### CODE REVIEW

**Comment by ferologics** [comment]
also, you have a related bug in the implementation where the `EXLegacyAppDelegateWrapper` is [registered by default as subscriber](https://github.com/expo/expo/blob/5a467296c9cbe9566e81195ad1ac72835c05af29/packages/expo-modules-core/ios/AppDelegates/EXAppDelegatesLoader.m#L20) but [doesn't call back](https://github.com/expo/expo/blob/5a467296c9cbe9566e81195ad1ac72835c05af29/packages/expo-modules-core/ios/AppDelegates/EXLegacyAppDelegateWrapper.m#L206) to the main one because it itself doesn't have any `subcontractorsLeft`, thus causing [`ExpoAppDelegate` not to callback at all](https://github.com/expo/expo/blob/5a467296c9cbe9566e81195ad1ac72835c05af29/packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift#L132).

but if someone uses `expo-notifications` (which doesn't use the [new `ExpoAppDelegateSubscriber` pattern](https://docs.expo.dev/modules/appdelegate-subscribers/) btw) then the issue goes away, because it magically decreases the `subscribersLeft` count by one.

i'll try to open an issue for this once i have more scope...

File: packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift [hunk 1]
```diff
@@ -115,21 +115,28 @@ open class ExpoAppDelegate: UIResponder, UIApplicationDelegate {
...
 
     let handler = { (result: UIBackgroundFetchResult) in
       dispatchQueue.sync {
         if result == .failed {
-          fetchResult = .failed
-        } else if fetchResult != .failed && result == .newData {
-          fetchResult = .newData
+          failedCount += 1
+        } else if result == .newData {
+          newDataCount += 1
```
Comment (tsapeta) [inline packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift:127]: I would just change existing conditions to give `newData` a higher priority, but that's ok too 😉 

```swift
if result == .newData {
  fetchResult = .newData
} else if fetchResult != .newData && result == .failed {
  fetchResult = .failed
}
```

**Review by tsapeta — CHANGES_REQUESTED** [review]
Thanks for submitting the PR to fix this and congrats on your first contribution!
I agree that it probably makes more sense to favor `newData` over `failed`. I guess we should apply the same change in `application(_:performFetchWithCompletionHandler:)` too 🤔  https://github.com/expo/expo/blob/5a467296c9cbe9566e81195ad1ac72835c05af29/packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift#L215
Could you please do that? And remember to fix bot's suggestion to add a changelog entry to `expo-modules-core` 😉

File: packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift (hunk 1 above)
Comment (ferologics) [reply packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift:127]: this would incorrectly result in `.failed` callbacks if `result` would be `.noData`

**Review by tsapeta — APPROVED** [review]
Great, thanks! We'll release that in SDK 47, which should be out sometime next month 😉

**Comment by tsapeta** [comment]
@ferologics Your change has been released in `expo@46.0.14` 🚀
