### PR TITLE
[ios][camera] Refactor CameraView

### LINKED ISSUE #37328: [iOS][expo-camera] CameraView eventually causes app to crash with KERN_INVALID_ADDRESS from availableLensesChanged
### Minimal reproducible example

https://github.com/adamhari/expo-camera-ios-crash

### Steps to reproduce

1. Mount `CameraView`
2. Unmount `CameraView`

[Sentry issue](https://kashoo.sentry.io/share/issue/1c37a529a6d843d8a75248656981c6a6/)

<details>
  <summary>Stack Trace</summary>
  
  ```js
  _120__shared_ptr_emplaceIN8facebook5react47NativeReactDevToolsRuntimeSettingsModuleSpecJSIENS_9allocatorIS3_EEEE > availableLensesChanged > EventEmitter::dispatchEvent > type >
  KERN_INVALID_ADDRESS at 0x20.
  
  Thread 12 Crashed:
  0   Expenses                        0x20095e4a0         [inlined] std::__1::weak_ptr<T>::lock (shared_ptr.h:1482)
  1   Expenses                        0x20095e4a0         facebook::react::EventEmitter::dispatchEvent (EventEmitter.cpp:94)
  2   Expenses                        0x20095e264         facebook::react::EventEmitter::dispatchEvent (EventEmitter.cpp:82)
  3   Expenses                        0x20041989c         expo::ExpoViewEventEmitter::dispatch (ExpoViewEventEmitter.cpp:10)
  4   Expenses                        0x200414600         -[ExpoFabricViewObjC dispatchEvent:payload:] (ExpoFabricViewObjC.mm:149)
  5   Expenses                        0x200468a74         closure in ExpoSwiftUI.SwiftUIVirtualView.installEventDispatchers (ExpoFabricView.swift:119)
  6   Expenses                        0x200466d04         thunk for closure
  7   Expenses                        0x200461994         EventDispatcher.callAsFunction (EventDispatcher.swift:40)
  8   Expenses                        0x200365e60         [inlined] CameraView.emitAvailableLenses (CameraView.swift:375)
  9   Expenses                        0x200365e60         [inlined] CameraView.addDevice (CameraView.swift:204)
  10  Expenses                        0x200365e60         CameraView.addDevice (CameraView.swift:202)
  11  Expenses                        0x200365a90         CameraView.updateDevice
  12  Expenses                        0x20036f684         [inlined] closure in CameraView.initializeCaptureSessionInput (CameraView.swift:824)
  13  Expenses                        0x20036f684         closure in CameraView.initializeCaptureSessionInput
  14  Expenses                        0x20032e348         thunk for closure
  15  libdispatch.dylib               0x315eebaa8         _dispatch_call_block_and_release
  16  libdispatch.dylib               0x315f05580         _dispatch_client_callout
  17  libdispatch.dylib               0x315ef42cc         _dispatch_lane_serial_drain
  18  libdispatch.dylib               0x315ef4da8         _dispatch_lane_invoke
  19  libdispatch.dylib               0x315eff1d8         _dispatch_root_queue_drain_deferred_wlh
  20  libdispatch.dylib               0x315efea5c         _dispatch_workloop_worker_thread
  21  libsystem_pthread.dylib         0x41ae14a08         _pthread_wqthread
  
  Thread 0
  0   libswiftCore.dylib              0x3030d4a4c         swift_release
  1   libswiftCore.dylib              0x3030b8a94         swift_cvw_destroyImpl
  2   libswiftCore.dylib              0x302d97378         _KeyedDecodingContainerBox.decode<T>
  3   libswiftCore.dylib              0x302d88c60         KeyedDecodingContainer.decode
  4   Expenses                        0x2006d84c4         LottieVector2D.init (VectorsExtensions.swift:95)
  5   Expenses                        0x2006d743c         [inlined] LottieVector2D.init
  6   Expenses                        0x2006d743c         LottieVector2D (<compiler-generated>:81)
  7   libswiftCore.dylib              0x303089bb0         Decodable.init
  8   Foundation                      0x303958444         JSONDecoderImpl.unwrap<T>
  9   Foundation                      0x303959104         JSONDecoderImpl.KeyedContainer.decodeIfPresent<T>
  10  Foundation                      0x3039570a4         JSONDecoderImpl.KeyedContainer<T>
  11  Foundation                      0x303959224         JSONDecoderImpl.KeyedContainer<T>
  12  libswiftCore.dylib              0x302d9c764         _KeyedDecodingContainerBox.decodeIfPresent<T>
  13  libswiftCore.dylib              0x302d896ec         KeyedDecodingContainer.decodeIfPresent<T>
  14  Expenses                        0x20063389c         KeyframeData<T>.init
  15  Expenses                        0x20063356c         KeyframeData<T>.init
  16  Expenses                        0x200633aac         KeyframeData<T>
  17  libswiftCore.dylib              0x303089bb0         Decodable.init
  18  Foundation                      0x3039548f4         JSONDecoderImpl.unwrap<T>
  19  Foundation                      0x303958bf0         JSONDecoderImpl.UnkeyedContainer.decode<T>
  20  Foundation                      0x303958c80         JSONDecoderImpl.UnkeyedContainer
  21  libswiftCore.dylib              0x30308b448         UnkeyedDecodingContainer.decode<T>
  22  Expenses                        0x200634b00         KeyframeGroup<T>.init (KeyframeGroup.swift:82)
  23  Expenses                        0x200634de8         KeyframeGroup<T>
  24  libswiftCore.dylib              0x303089bb0         Decodable.init
  25  Foundation                      0x303958444         JSONDecoderImpl.unwrap<T>
  26  Foundation                      0x303957cac         JSONDecoderImpl.KeyedContainer.decode<T>
  27  Foundation                      0x3039570a4         JSONDecoderImpl.KeyedContainer<T>
  28  Foundation                      0x303957064         JSONDecoderImpl.KeyedContainer<T>
  29  libswiftCore.dylib              0x302d997d0         _KeyedDecodingContainerBox.decode<T>
  30  libswiftCore.dylib              0x302d8908c         KeyedDecodingContainer.decode<T>
  31  Expenses                        0x2006ce614         Transform.init (Transform.swift:29)
  32  Expenses                        0x2006cffd8         [inlined] Transform.__allocating_init
  33  Expenses                        0x2006cffd8         Transform (<compiler-generated>:13)
  34  libswiftCore.dylib              0x303089bb0         Decodable.init
  35  Foundation                      0x303958444         JSONDecoderImpl.unwrap<T>
  36  Foundation                      0x303959104         JSONDecoderImpl.KeyedContainer.decodeIfPresent<T>
  37  Foundation                      0x3039570a4         JSONDecoderImpl.KeyedContainer<T>
  38  Foundation                      0x303959224         JSONDecoderImpl.KeyedContainer<T>
  39  libswiftCore.dylib              0x302d9c764         _KeyedDecodingContainerBox.decodeIfPresent<T>
  40  libswiftCore.dylib              0x302d896ec         KeyedDecodingContainer.decodeIfPresent<T>
  41  Expenses                        0x200645708         LayerModel.init (LayerModel.swift:96)
  42  Expenses                        0x2006b25a4         ShapeLayerModel.init (ShapeLayerModel.swift:16)
  43  Expenses                        0x2006b2434         ShapeLayerModel.__allocating_init
  44  Expenses                        0x2006476a0         LayerModel
  45  libswiftCore.dylib              0x303089bb0         Decodable.init
  46  Foundation                      0x3039548f4         JSONDecoderImpl.unwrap<T>
  47  Foundation                      0x303958bf0         JSONDecoderImpl.UnkeyedContainer.decode<T>
  48  Foundation                      0x303958c80         JSONDecoderImpl.UnkeyedContainer
  49  libswiftCore.dylib              0x30308b448         UnkeyedDecodingContainer.decode<T>
  50  Expenses                        0x20064f658         $ss22KeyedDecodingContainerV6LottieE6decode_8ofFamily6forKeySayqd__GAGm_qd_0_mxtKSeRd__AC05ClassG0Rd_0_r0_lFAC0D9AnimationC10CodingKeysO_AC10LayerModelCAC0N4TypeOTtt0g5 (KeyedDecodingContainerExtensions.swift:40)
  51  Expenses                        0x20064fb80         LottieAnimation.init (LottieAnimation.swift:36)
  52  Expenses                        0x200651510         [inlined] LottieAnimation.__allocating_init
  53  Expenses                        0x200651510         LottieAnimation (<compiler-generated>:27)
  54  libswiftCore.dylib              0x303089bb0         Decodable.init
  55  Foundation                      0x3039548f4         JSONDecoderImpl.unwrap<T>
  56  Foundation                      0x303954a74         closure in JSONDecoder.decode<T>
  57  Foundation                      0x303952f2c         closure in JSONDecoder._decode<T>
  58  Foundation                      0x303953018         closure in JSONDecoder._decode<T>
  59  Foundation                      0x3039521bc         closure in JSONDecoder.withUTF8Representation<T>
  60  Foundation                      0x303952504         closure in JSONDecoder.withUTF8Representation<T>
  61  Foundation                      0x303950434         closure in Data.withBufferView<T>
  62  Foundation                      0x303950500         closure in Data.withBufferView<T>
  63  Foundation                      0x3039504c8         __DataStorage.withUnsafeBytes<T>
  64  Foundation                      0x3039514f8         Data._Representation.withUnsafeBytes<T>
  65  Foundation                      0x30394ffc8         JSONDecoder.decode<T>
  66  Foundation                      0x303950348         JSONDecoder.decode<T>
  67  Expenses                        0x200cbe9e0         ContainerView.setSourceJson (ContainerView.swift:212)
  68  Expenses                        0x200cbeedc         ContainerView.setRenderMode
  69  Expenses                        0x200cb8efc         -[LottieAnimationViewComponentView updateProps:oldProps:] (LottieAnimationViewComponentView.mm:69)
  70  Expenses                        0x200705c60         [inlined] RCTPerformMountInstructions (RCTMountingManager.mm:82)
  71  Expenses                        0x200705c60         [inlined] _ZZ41-[RCTMountingManager performTransaction:]ENK3$_1clERKN8facebook5react19MountingTransactionERKNS1_16SurfaceTelemetryE (RCTMountingManager.mm:264)
  72  Expenses                        0x200705c60         [inlined] _ZNSt3__18__invokeB8ne190102IRZ41-[RCTMountingManager performTransaction:]E3$_1JRKN8facebook5react19MountingTransactionERKNS4_16SurfaceTelemetryEEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOSB_DpOSC_ (invoke.h:149)
  73  Expenses                        0x200705c60         [inlined] _ZNSt3__128__invoke_void_return_wrapperIvLb1EE6__callB8ne190102IJRZ41-[RCTMountingManager performTransaction:]E3$_1RKN8facebook5react19MountingTransactionERKNS6_16SurfaceTelemetryEEEEvDpOT_ (invoke.h:224)
  74  Expenses                        0x200705c60         [inlined] _ZNSt3__110__function12__alloc_funcIZ41-[RCTMountingManager performTransaction:]E3$_1NS_9allocatorIS2_EEFvRKN8facebook5react19MountingTransactionERKNS6_16SurfaceTelemetryEEEclB8ne190102ES9_SC_ (function.h:171)
  75  Expenses                        0x200705c60         _ZNSt3__110__function6__funcIZ41-[RCTMountingManager performTransaction:]E3$_1NS_9allocatorIS2_EEFvRKN8facebook5react19MountingTransactionERKNS6_16SurfaceTelemetryEEEclES9_SC_ (function.h:313)
  76  Expenses                        0x200992128         [inlined] std::__1::__function::__value_func<T>::operator()[abi:ne190102] (function.h:430)
  77  Expenses                        0x200992128         [inlined] std::__1::function<T>::operator() (function.h:989)
  78  Expenses                        0x200992128         facebook::react::TelemetryController::pullTransaction (TelemetryController.cpp:39)
  79  Expenses                        0x200704a84         -[RCTMountingManager performTransaction:] (RCTMountingManager.mm:258)
  80  Expenses                        0x200704984         -[RCTMountingManager initiateTransaction:] (RCTMountingManager.mm:246)
  81  libdispatch.dylib               0x315eebaa8         _dispatch_call_block_and_release
  82  libdispatch.dylib               0x315f05580         _dispatch_client_callout
  83  libdispatch.dylib               0x315f2259c         _dispatch_main_queue_drain.cold.5
  84  libdispatch.dylib               0x315efad2c         _dispatch_main_queue_drain
  85  libdispatch.dylib               0x315efac68         _dispatch_main_queue_callback_4CF
  86  CoreFoundation                  0x306042d8c         __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  87  CoreFoundation                  0x305fe64f0         __CFRunLoopRun
  88  CoreFoundation                  0x305fe7c38         CFRunLoopRunSpecific
  89  GraphicsServices                0x3a03b5450         GSEventRunModal
  90  UIKitCore                       0x30b2e9270         -[UIApplication _run]
  91  UIKitCore                       0x30b2b4a24         UIApplicationMain
  92  Expenses                        0x2002f5774         main (AppDelegate.swift:7)
  93  <unknown>                       0x1aa337f08         <redacted>
  
  Thread 1 name: com.apple.uikit.eventfetch-thread
  0   libsystem_kernel.dylib          0x3a8412ce4         mach_msg2_trap
  1   libsystem_kernel.dylib          0x3a8416398         mach_msg2_internal
  2   libsystem_kernel.dylib          0x3a84162b4         mach_msg_overwrite
  3   libsystem_kernel.dylib          0x3a84160fc         mach_msg
  4   CoreFoundation                  0x305fe78fc         __CFRunLoopServiceMachPort
  5   CoreFoundation                  0x305fe61ec         __CFRunLoopRun
  6   CoreFoundation                  0x305fe7c38         CFRunLoopRunSpecific
  7   Foundation                      0x3038d9798         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
  8   Foundation                      0x3038df01c         -[NSRunLoop(NSRunLoop) runUntilDate:]
  9   UIKitCore                       0x30b2d3568         -[UIEventFetcher threadMain]
  10  Foundation                      0x30393f800         __NSThread__start__
  11  libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 2 name: com.facebook.react.runtime.JavaScript
  0   libsystem_kernel.dylib          0x3a8412ce4         mach_msg2_trap
  1   libsystem_kernel.dylib          0x3a8416398         mach_msg2_internal
  2   libsystem_kernel.dylib          0x3a84162b4         mach_msg_overwrite
  3   libsystem_kernel.dylib          0x3a84160fc         mach_msg
  4   CoreFoundation                  0x305fe78fc         __CFRunLoopServiceMachPort
  5   CoreFoundation                  0x305fe61ec         __CFRunLoopRun
  6   CoreFoundation                  0x305fe7c38         CFRunLoopRunSpecific
  7   Expenses                        0x2009fa534         +[RCTJSThreadManager runRunLoop] (RCTJSThreadManager.mm:102)
  8   Foundation                      0x30393f800         __NSThread__start__
  9   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 3 name: hades
  0   libsystem_kernel.dylib          0x3a8418438         __psynch_cvwait
  1   libsystem_pthread.dylib         0x41ae15e4c         _pthread_cond_wait
  2   libc++.1.dylib                  0x3275bd2c0         std::__1::condition_variable::wait
  3   hermes                          0x1023e8e94         hermes::vm::HadesGC::Executor::worker
  4   hermes                          0x1023e8dfc         std::__1::__thread_proxy[abi:v160006]<T>
  5   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 4 name: hades
  0   libsystem_kernel.dylib          0x3a8418438         __psynch_cvwait
  1   libsystem_pthread.dylib         0x41ae15e4c         _pthread_cond_wait
  2   libc++.1.dylib                  0x3275bd2c0         std::__1::condition_variable::wait
  3   hermes                          0x1023e8e94         hermes::vm::HadesGC::Executor::worker
  4   hermes                          0x1023e8dfc         std::__1::__thread_proxy[abi:v160006]<T>
  5   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 5
  0   libsystem_kernel.dylib          0x3a8418658         __semwait_signal
  1   libsystem_c.dylib               0x315f899a8         nanosleep
  2   libsystem_c.dylib               0x315f9ed0c         sleep
  3   Expenses                        0x200a801ac         monitorCachedData (SentryCrashCachedData.c:146)
  4   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 6 name: SentryCrash Exception Handler (Secondary)
  0   libsystem_kernel.dylib          0x3a8412ce4         mach_msg2_trap
  1   libsystem_kernel.dylib          0x3a8416398         mach_msg2_internal
  2   libsystem_kernel.dylib          0x3a84162b4         mach_msg_overwrite
  3   libsystem_kernel.dylib          0x3a84160fc         mach_msg
  4   Expenses                        0x200a89960         handleExceptions (SentryCrashMonitor_MachException.c:313)
  5   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 8 name: io.sentry.app-hang-tracker
  0   libsystem_kernel.dylib          0x3a8418658         __semwait_signal
  1   libsystem_c.dylib               0x315f899a8         nanosleep
  2   Foundation                      0x303b77c28         +[NSThread sleepForTimeInterval:]
  3   Expenses                        0x200a69e8c         -[SentryANRTrackerV1 detectANRs] (SentryANRTrackerV1.m:106)
  4   Foundation                      0x30393f800         __NSThread__start__
  5   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 9 name: com.apple.NSURLConnectionLoader
  0   libsystem_kernel.dylib          0x3a8412ce4         mach_msg2_trap
  1   libsystem_kernel.dylib          0x3a8416398         mach_msg2_internal
  2   libsystem_kernel.dylib          0x3a84162b4         mach_msg_overwrite
  3   libsystem_kernel.dylib          0x3a84160fc         mach_msg
  4   CoreFoundation                  0x305fe78fc         __CFRunLoopServiceMachPort
  5   CoreFoundation                  0x305fe61ec         __CFRunLoopRun
  6   CoreFoundation                  0x305fe7c38         CFRunLoopRunSpecific
  7   CFNetwork                       0x308b98308         +[__CFN_CoreSchedulingSetRunnable _run:]
  8   Foundation                      0x30393f800         __NSThread__start__
  9   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 10 name: com.apple.CoreMotion.MotionThread
  0   libsystem_kernel.dylib          0x3a8412ce4         mach_msg2_trap
  1   libsystem_kernel.dylib          0x3a8416398         mach_msg2_internal
  2   libsystem_kernel.dylib          0x3a84162b4         mach_msg_overwrite
  3   libsystem_kernel.dylib          0x3a84160fc         mach_msg
  4   CoreFoundation                  0x305fe78fc         __CFRunLoopServiceMachPort
  5   CoreFoundation                  0x305fe61ec         __CFRunLoopRun
  6   CoreFoundation                  0x305fe7c38         CFRunLoopRunSpecific
  7   CoreFoundation                  0x306062670         CFRunLoopRun
  8   CoreMotion                      0x321288e4c         <redacted>
  9   libsystem_pthread.dylib         0x41ae17340         _pthread_start
  
  Thread 11
  0   libsystem_kernel.dylib          0x3a8412a90         __workq_kernreturn
  1   libsystem_pthread.dylib         0x41ae14a54         _pthread_wqthread
  
  Thread 12 Crashed:
  0   Expenses                        0x20095e4a0         [inlined] std::__1::weak_ptr<T>::lock (shared_ptr.h:1482)
  1   Expenses                        0x20095e4a0         facebook::react::EventEmitter::dispatchEvent (EventEmitter.cpp:94)
  2   Expenses                        0x20095e264         facebook::react::EventEmitter::dispatchEvent (EventEmitter.cpp:82)
  3   Expenses                        0x20041989c         expo::ExpoViewEventEmitter::dispatch (ExpoViewEventEmitter.cpp:10)
  4   Expenses                        0x200414600         -[ExpoFabricViewObjC dispatchEvent:payload:] (ExpoFabricViewObjC.mm:149)
  5   Expenses                        0x200468a74         closure in ExpoSwiftUI.SwiftUIVirtualView.installEventDispatchers (ExpoFabricView.swift:119)
  6   Expenses                        0x200466d04         thunk for closure
  7   Expenses                        0x200461994         EventDispatcher.callAsFunction (EventDispatcher.swift:40)
  8   Expenses                        0x200365e60         [inlined] CameraView.emitAvailableLenses (CameraView.swift:375)
  9   Expenses                        0x200365e60         [inlined] CameraView.addDevice (CameraView.swift:204)
  10  Expenses                        0x200365e60         CameraView.addDevice (CameraView.swift:202)
  11  Expenses                        0x200365a90         CameraView.updateDevice
  12  Expenses                        0x20036f684         [inlined] closure in CameraView.initializeCaptureSessionInput (CameraView.swift:824)
  13  Expenses                        0x20036f684         closure in CameraView.initializeCaptureSessionInput
  14  Expenses                        0x20032e348         thunk for closure
  15  libdispatch.dylib               0x315eebaa8         _dispatch_call_block_and_release
  16  libdispatch.dylib               0x315f05580         _dispatch_client_callout
  17  libdispatch.dylib               0x315ef42cc         _dispatch_lane_serial_drain
  18  libdispatch.dylib               0x315ef4da8         _dispatch_lane_invoke
  19  libdispatch.dylib               0x315eff1d8         _dispatch_root_queue_drain_deferred_wlh
  20  libdispatch.dylib               0x315efea5c         _dispatch_workloop_worker_thread
  21  libsystem_pthread.dylib         0x41ae14a08         _pthread_wqthread
  
  Thread 13
  0   libsystem_kernel.dylib          0x3a8412a90         __workq_kernreturn
  1   libsystem_pthread.dylib         0x41ae14a54         _pthread_wqthread
  
  Thread 14
  0   libsystem_kernel.dylib          0x3a8412a90         __workq_kernreturn
  1   libsystem_pthread.dylib         0x41ae14a54         _pthread_wqthread
  
  Thread 15
  0   libsystem_kernel.dylib          0x3a8412a90         __workq_kernreturn
  1   libsystem_pthread.dylib         0x41ae14a54         _pthread_wqthread
  
  Thread 12 crashed with ARM Thread State (64-bit):
      x0: 0x000000016fc223e8   x1: 0x0000000100ed7d4a   x2: 0x0000000100e9dea0   x3: 0x000000016fc22480
      x4: 0x0000000159e5d580   x5: 0x0000000000000000   x6: 0x00000000003b5170   x7: 0x49dd7dce1036f2ad
      x8: 0x2f4c524a224f002e   x9: 0x2f4c524a224f002e  x10: 0x0000000600000003  x11: 0x0000000800000003
     x12: 0x000000000000076b  x13: 0x0000000159e5c000  x14: 0x0000000000000001  x15: 0xffffffffb00007ff
     x16: 0x000000019f34bd90  x17: 0x23eb0001ee194110  x18: 0x0000000000000000  x19: 0x0000000000000002
     x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x000000016fc22470  x23: 0x000000016fc22480
     x24: 0x000000016fc22518  x25: 0x0000000000000310  x26: 0x0000000100d84000  x27: 0x00000001f028bce0
     x28: 0x000000015a9c5cf8   fp: 0x000000016fc22450   lr: 0x000000010095e4a0   sp: 0x000000016fc22340
      pc: 0x000000010095e4a0 cpsr: 0x0000000060001000
  
  
  
  EOF
  ```
</details>

This is difficult to reproduce in the minimum repro app & the app where it originally crashed.

### Environment

```text
System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.8.2 - /usr/local/bin/npm
      Watchman: 2024.09.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/adamhari/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.10 => 53.0.11 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.3 => 0.79.3 
    npmGlobalPackages:
      eas-cli: 16.6.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
adamhari@MacBook-Pro-2 expo-camera-ios-crash % npx expo-doctor@latest --verbose
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions

14/15 checks passed. 1 checks failed. Possible issues detected:

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, splash, ios, android, plugins. 


1 check failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #37328
The crashes in the issue are happening when events are dispatched early in the views lifecycle. The fix was to wrap the early calls in `DispatchQueue.main.async` but this was never required before and we have always emitted events early. I need to debug it further to figure out what has changed. 

There was also another issue, `SharedObjects` will no longer be converted unless the function definition is explicitly annotated with the return type. This causes an issue in camera because previously we would resolve a `PictureRef` or a dictionary depending on if the user passed `pictureRef: true` as an option to the `takePicture` function. This now no longer works. To fix it I've added another function that explicitly returns the `PictureRef` and we decide which function call on the JS side so this is non breaking change. 

While working on these problems, I also realized that the `CameraView` has gotten way to large so I've broken it out into separate components
`CameraPhotoCapture`
`CameraSessionManager`
`CameraVideoRecording`

# How
- Wrap early event emissions in `DispatchQueue.main.async`
- Create a new function to handle returning `PictureRef`
- Break the main camera functions up by feature. Reduced the `CameraView` from 1000+ lines to 350

# Test Plan
Bare-expo. Tested all features on the example screens.

### CODE REVIEW

File: packages/expo-camera/ios/CameraViewModule.swift [hunk 1]
```diff
@@ -249,12 +249,26 @@ public final class CameraViewModule: Module, ScannerResultHandler {
         view.getAvailableLenses()
       }
 
+      AsyncFunction("takePictureRef") { (view, options: TakePictureOptions) -> PictureRef in
+        #if targetEnvironment(simulator)
+        return try takePictureRefForSimulator(self.appContext, view, options)
+        #else // not simulator
```
Comment (lukmccall) [inline packages/expo-camera/ios/CameraViewModule.swift]:
```suggestion
        #else
```
up to you

File: packages/expo-camera/ios/CameraViewModule.swift [hunk 2]
```diff
@@ -249,12 +249,26 @@ public final class CameraViewModule: Module, ScannerResultHandler {
...
+
```
Comment (lukmccall) [inline packages/expo-camera/ios/CameraViewModule.swift]:
```suggestion
```

File: packages/expo-camera/ios/Current/CameraPhotoCapture.swift [hunk 3]
```diff
@@ -0,0 +1,265 @@
...
+
+    guard let imageData, var takenImage = UIImage(data: imageData) else {
+      throw CameraSavingImageException("Failed to process image data")
+    }
+
+    let previewSize: CGSize = {
+      return captureDelegate.deviceOrientation == .portrait ?
+      CGSize(width: captureDelegate.previewLayer.frame.size.height, height: captureDelegate.previewLayer.frame.size.width) :
+      CGSize(width: captureDelegate.previewLayer.frame.size.width, height: captureDelegate.previewLayer.frame.size.height)
+    }()
```
Comment (lukmccall) [inline packages/expo-camera/ios/Current/CameraPhotoCapture.swift]: Is there any reason why this is wrapped inside the lambda?

File: packages/expo-camera/ios/Current/CameraSessionManager.swift [hunk 4]
```diff
@@ -0,0 +1,359 @@
...
+    }
+  }
+
+  func enableTorch() {
+    guard let delegate else {
+      return
+    }
+    guard let device = captureDeviceInput?.device, device.hasTorch else {
+      return
+    }
```
Comment (lukmccall) [inline packages/expo-camera/ios/Current/CameraSessionManager.swift]: Those can be merged

**Review by lukmccall — APPROVED** [review]

File: packages/expo-camera/ios/Current/CameraPhotoCapture.swift (hunk 3 above)
Comment (alanjhughes) [reply packages/expo-camera/ios/Current/CameraPhotoCapture.swift]: `if` wasn't an expression in swift until recently and I forgot 😅

**Comment by LucasBourgeois** [comment]
This MR didnt solve the problem.
Still having a crash report on 16.1.10 on IOS. 

<details>

<summary>stacktrace</summary>

```
Incident Identifier: A5D2BE7A-3962-4540-8E18-E8F7E5BA349C
CrashReporter Key:   c07868a1538c8df9634a0395c1bbd20a0720e038
Hardware Model:      iPhone13,1
Process:             <ANON_APPBUNDLE> [5300]
Path:                /private/var/containers/Bundle/Application/E1DBC20B-CC8A-44C8-9D54-38AAA10F751D/<ANON_APPBUNDLE>.app/<ANON_APPBUNDLE>
Identifier:          <ANON_IDENTIFIER>
Version:             1.1.6 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           <ANON_IDENTIFIER> [701]

Date/Time:           2025-07-02 18:19:50.2695 +0200
Launch Time:         2025-07-02 18:18:40.3158 +0200
OS Version:          iPhone OS 18.5 (22F76)
Release Type:        User
Baseband Version:    5.51.03
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Codes: 0x0000000000000001, 0x0000000000000020
VM Region Info: 0x20 is not in any region.  Bytes before following region: 4340613088
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   102b88000-102b94000 [   48K] r-x/r-x SM=COW  /var/containers/Bundle/Application/E1DBC20B-CC8A-44C8-9D54-38AAA10F751D/<ANON_APPBUNDLE>.app/<ANON_APPBUNDLE>
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [5300]

Triggered by Thread:  15

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0:
0   <ANON_APPBUNDLE>.debug.dylib      	       0x10473913c DYLD-STUB$$facebook::react::RectangleEdges<double>::isUniform() const + 0
1   <ANON_APPBUNDLE>.debug.dylib      	       0x1040a9564 -[RCTViewComponentView styleWouldClipOverflowInk] + 96
2   <ANON_APPBUNDLE>.debug.dylib      	       0x1040a8a20 -[RCTViewComponentView finalizeUpdates:] + 76
3   <ANON_APPBUNDLE>.debug.dylib      	       0x104006640 RCTPerformMountInstructions(std::__1::vector<facebook::react::ShadowViewMutation, std::__1::allocator<facebook::react::ShadowViewMutation>> const&, RCTComponentViewRegistry*, RCTMountingTransactionObserverCoordinator&, int) + 1212
4   <ANON_APPBUNDLE>.debug.dylib      	       0x104006178 -[RCTMountingManager performTransaction:]::$_1::operator()(facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) const + 80
5   <ANON_APPBUNDLE>.debug.dylib      	       0x10400611c decltype(std::declval<-[RCTMountingManager performTransaction:]::$_1&>()(std::declval<facebook::react::MountingTransaction const&>(), std::declval<facebook::react::SurfaceTelemetry const&>())) std::__1::__invoke[abi:de190102]<-[RCTMountingManager performTransaction:]::$_1&, facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&>(-[RCTMountingManager performTransaction:]::$_1&, facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) + 40
6   <ANON_APPBUNDLE>.debug.dylib      	       0x1040060c4 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:de190102]<-[RCTMountingManager performTransaction:]::$_1&, facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&>(-[RCTMountingManager performTransaction:]::$_1&, facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) + 40
7   <ANON_APPBUNDLE>.debug.dylib      	       0x104006090 std::__1::__function::__alloc_func<-[RCTMountingManager performTransaction:]::$_1, std::__1::allocator<-[RCTMountingManager performTransaction:]::$_1>, void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)>::operator()[abi:de190102](facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) + 44
8   <ANON_APPBUNDLE>.debug.dylib      	       0x104004f18 std::__1::__function::__func<-[RCTMountingManager performTransaction:]::$_1, std::__1::allocator<-[RCTMountingManager performTransaction:]::$_1>, void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)>::operator()(facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) + 44
9   <ANON_APPBUNDLE>.debug.dylib      	       0x103d9a100 std::__1::__function::__value_func<void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)>::operator()[abi:de190102](facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) const + 76
10  <ANON_APPBUNDLE>.debug.dylib      	       0x103d99380 std::__1::function<void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)>::operator()(facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&) const + 40
11  <ANON_APPBUNDLE>.debug.dylib      	       0x103d991b4 facebook::react::TelemetryController::pullTransaction(std::__1::function<void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)> const&, std::__1::function<void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)> const&, std::__1::function<void (facebook::react::MountingTransaction const&, facebook::react::SurfaceTelemetry const&)> const&) const + 300
12  <ANON_APPBUNDLE>.debug.dylib      	       0x1040004a8 -[RCTMountingManager performTransaction:] + 588
13  <ANON_APPBUNDLE>.debug.dylib      	       0x1040001d8 -[RCTMountingManager initiateTransaction:] + 496
14  <ANON_APPBUNDLE>.debug.dylib      	       0x103fffb48 __42-[RCTMountingManager scheduleTransaction:]_block_invoke + 348
15  <ANON_APPBUNDLE>.debug.dylib      	       0x103b62e2c __RCTExecuteOnMainQueue_block_invoke + 40
16  libdispatch.dylib             	       0x1a7edcaac _dispatch_call_block_and_release + 31
17  libdispatch.dylib             	       0x1a7ef6584 _dispatch_client_callout + 15
18  libdispatch.dylib             	       0x1a7f135a0 _dispatch_main_queue_drain.cold.5 + 811
19  libdispatch.dylib             	       0x1a7eebd30 _dispatch_main_queue_drain + 179
20  libdispatch.dylib             	       0x1a7eebc6c _dispatch_main_queue_callback_4CF + 43
21  CoreFoundation                	       0x19ffbdd90 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 15
22  CoreFoundation                	       0x19ff614f4 __CFRunLoopRun + 1979
23  CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
24  GraphicsServices              	       0x1ed141454 GSEventRunModal + 167
25  UIKitCore                     	       0x1a2975274 -[UIApplication _run] + 815
26  UIKitCore                     	       0x1a2940a28 UIApplicationMain + 335
27  <ANON_APPBUNDLE>.debug.dylib      	       0x10304e678 __debug_main_executable_dylib_entry_point + 64
28  dyld                          	       0x1c6e37f08 start + 6039

Thread 1:
0   libsystem_pthread.dylib       	       0x22a65caa4 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x22a65caa4 start_wqthread + 0

Thread 3 name:  com.apple.uikit.eventfetch-thread
Thread 3:
0   libsystem_kernel.dylib        	       0x1f116fce4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1f117339c mach_msg2_internal + 75
2   libsystem_kernel.dylib        	       0x1f11732b8 mach_msg_overwrite + 427
3   libsystem_kernel.dylib        	       0x1f1173100 mach_msg + 23
4   CoreFoundation                	       0x19ff62900 __CFRunLoopServiceMachPort + 159
5   CoreFoundation                	       0x19ff611f0 __CFRunLoopRun + 1207
6   CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
7   Foundation                    	       0x19ebda79c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
8   Foundation                    	       0x19ebe0020 -[NSRunLoop(NSRunLoop) runUntilDate:] + 63
9   UIKitCore                     	       0x1a295f56c -[UIEventFetcher threadMain] + 423
10  Foundation                    	       0x19ec40804 __NSThread__start__ + 731
11  libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
12  libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 4 name:  com.facebook.react.runtime.JavaScript
Thread 4:
0   <ANON_APPBUNDLE>.debug.dylib      	       0x103d34bb8 facebook::react::RawPropsParser::at(facebook::react::RawProps const&, facebook::react::RawPropsKey const&) const + 436
1   <ANON_APPBUNDLE>.debug.dylib      	       0x103d2a3a4 facebook::react::RawProps::at(char const*, char const*, char const*) const + 292
2   <ANON_APPBUNDLE>.debug.dylib      	       0x103c161a4 std::__1::optional<facebook::react::SharedColor> facebook::react::convertRawProp<std::__1::optional<facebook::react::SharedColor>, std::__1::optional<facebook::react::SharedColor>>(facebook::react::PropsParserContext const&, facebook::react::RawProps const&, char const*, std::__1::optional<facebook::react::SharedColor> const&, std::__1::optional<facebook::react::SharedColor> const&, char const*, char const*) + 68
3   <ANON_APPBUNDLE>.debug.dylib      	       0x103bfd548 facebook::react::CascadedRectangleEdges<facebook::react::SharedColor> facebook::react::convertRawProp<facebook::react::SharedColor>(facebook::react::PropsParserContext const&, facebook::react::RawProps const&, char const*, char const*, facebook::react::CascadedRectangleEdges<facebook::react::SharedColor> const&, facebook::react::CascadedRectangleEdges<facebook::react::SharedColor> const&) + 512
4   <ANON_APPBUNDLE>.debug.dylib      	       0x103bfb428 facebook::react::BaseViewProps::BaseViewProps(facebook::react::PropsParserContext const&, facebook::react::BaseViewProps const&, facebook::react::RawProps const&, std::__1::function<bool (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)> const&) + 1652
5   <ANON_APPBUNDLE>.debug.dylib      	       0x1043de878 facebook::react::RNSVGGroupProps::RNSVGGroupProps(facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 152
6   <ANON_APPBUNDLE>.debug.dylib      	       0x103909880 facebook::react::RNSVGGroupProps* std::__1::construct_at[abi:de190102]<facebook::react::RNSVGGroupProps, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, facebook::react::RNSVGGroupProps*>(facebook::react::RNSVGGroupProps*, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 72
7   <ANON_APPBUNDLE>.debug.dylib      	       0x10390982c facebook::react::RNSVGGroupProps* std::__1::__construct_at[abi:de190102]<facebook::react::RNSVGGroupProps, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, facebook::react::RNSVGGroupProps*>(facebook::react::RNSVGGroupProps*, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 48
8   <ANON_APPBUNDLE>.debug.dylib      	       0x103909668 void std::__1::allocator_traits<std::__1::allocator<facebook::react::RNSVGGroupProps>>::construct[abi:de190102]<facebook::react::RNSVGGroupProps, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, void, 0>(std::__1::allocator<facebook::react::RNSVGGroupProps>&, facebook::react::RNSVGGroupProps*, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 52
9   <ANON_APPBUNDLE>.debug.dylib      	       0x103909584 std::__1::__shared_ptr_emplace<facebook::react::RNSVGGroupProps, std::__1::allocator<facebook::react::RNSVGGroupProps>>::__shared_ptr_emplace[abi:de190102]<facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, std::__1::allocator<facebook::react::RNSVGGroupProps>, 0>(std::__1::allocator<facebook::react::RNSVGGroupProps>, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 120
10  <ANON_APPBUNDLE>.debug.dylib      	       0x10390926c std::__1::__shared_ptr_emplace<facebook::react::RNSVGGroupProps, std::__1::allocator<facebook::react::RNSVGGroupProps>>::__shared_ptr_emplace[abi:de190102]<facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, std::__1::allocator<facebook::react::RNSVGGroupProps>, 0>(std::__1::allocator<facebook::react::RNSVGGroupProps>, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 52
11  <ANON_APPBUNDLE>.debug.dylib      	       0x10390915c std::__1::shared_ptr<facebook::react::RNSVGGroupProps> std::__1::allocate_shared[abi:de190102]<facebook::react::RNSVGGroupProps, std::__1::allocator<facebook::react::RNSVGGroupProps>, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, 0>(std::__1::allocator<facebook::react::RNSVGGroupProps> const&, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 92
12  <ANON_APPBUNDLE>.debug.dylib      	       0x1039090dc std::__1::shared_ptr<facebook::react::RNSVGGroupProps> std::__1::make_shared[abi:de190102]<facebook::react::RNSVGGroupProps, facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&, 0>(facebook::react::PropsParserContext const&, facebook::react::RNSVGGroupProps const&, facebook::react::RawProps const&) + 68
13  <ANON_APPBUNDLE>.debug.dylib      	       0x103908fac facebook::react::ConcreteShadowNode<&facebook::react::RNSVGGroupComponentName, facebook::react::RNSVGLayoutableShadowNode, facebook::react::RNSVGGroupProps, facebook::react::BaseViewEventEmitter, facebook::react::StateData, false>::Props(facebook::react::PropsParserContext const&, facebook::react::RawProps const&, std::__1::shared_ptr<facebook::react::Props const> const&) + 108
14  <ANON_APPBUNDLE>.debug.dylib      	       0x1039073b8 facebook::react::ConcreteComponentDescriptor<facebook::react::RNSVGConcreteShadowNode<&facebook::react::RNSVGGroupComponentName, facebook::react::RNSVGGroupProps>>::cloneProps(facebook::react::PropsParserContext const&, std::__1::shared_ptr<facebook::react::Props const> const&, facebook::react::RawProps) const + 176
15  <ANON_APPBUNDLE>.debug.dylib      	       0x103daffcc facebook::react::UIManager::createNode(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, facebook::react::RawProps, std::__1::shared_ptr<facebook::react::InstanceHandle const>) const + 400
16  <ANON_APPBUNDLE>.debug.dylib      	       0x103de0e60 facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const + 520
17  <ANON_APPBUNDLE>.debug.dylib      	       0x103de0c4c decltype(std::declval<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0&>()(std::declval<facebook::jsi::Runtime&>(), std::declval<facebook::jsi::Value const&>(), std::declval<facebook::jsi::Value const*>(), std::declval<unsigned long>())) std::__1::__invoke[abi:de190102]<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 72
18  <ANON_APPBUNDLE>.debug.dylib      	       0x103de0bd4 facebook::jsi::Value std::__1::__invoke_void_return_wrapper<facebook::jsi::Value, false>::__call[abi:de190102]<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 64
19  <ANON_APPBUNDLE>.debug.dylib      	       0x103de0b88 std::__1::__function::__alloc_func<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0, std::__1::allocator<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()[abi:de190102](facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 72
20  <ANON_APPBUNDLE>.debug.dylib      	       0x103ddf910 std::__1::__function::__func<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0, std::__1::allocator<facebook::react::UIManagerBinding::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 68
21  hermes                        	       0x10830d930 facebook::hermes::HermesRuntimeImpl::HFContext::func(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) + 536
22  hermes                        	       0x1083c4074 hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) + 144
23  hermes                        	       0x1083ddf98 hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) + 2228
24  hermes                        	       0x1083dd6b0 hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) + 132
25  hermes                        	       0x1083c4348 hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) + 40
26  hermes                        	       0x1083c3b98 hermes::vm::BoundFunction::_boundCall(hermes::vm::BoundFunction*, hermes::inst::Inst const*, hermes::vm::Runtime&) + 568
27  hermes                        	       0x108305ca4 facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 744
28  <ANON_APPBUNDLE>.debug.dylib      	       0x103355e14 facebook::jsi::Function::call(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned long) const + 100
29  <ANON_APPBUNDLE>.debug.dylib      	       0x103355d64 facebook::jsi::Function::call(facebook::jsi::Runtime&, std::initializer_list<facebook::jsi::Value>) const + 112
30  <ANON_APPBUNDLE>.debug.dylib      	       0x10435d12c facebook::react::Task::execute(facebook::jsi::Runtime&, bool) + 276
31  <ANON_APPBUNDLE>.debug.dylib      	       0x104343a80 facebook::react::RuntimeScheduler_Modern::executeTask(facebook::jsi::Runtime&, facebook::react::Task&, bool) const + 148
32  <ANON_APPBUNDLE>.debug.dylib      	       0x104344824 facebook::react::RuntimeScheduler_Modern::runEventLoopTick(facebook::jsi::Runtime&, facebook::react::Task&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>) + 336
33  <ANON_APPBUNDLE>.debug.dylib      	       0x1043443c0 facebook::react::RuntimeScheduler_Modern::runEventLoop(facebook::jsi::Runtime&, bool) + 252
34  <ANON_APPBUNDLE>.debug.dylib      	       0x10434b794 facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0::operator()(facebook::jsi::Runtime&) const + 44
35  <ANON_APPBUNDLE>.debug.dylib      	       0x10434b75c decltype(std::declval<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0&>()(std::declval<facebook::jsi::Runtime&>())) std::__1::__invoke[abi:de190102]<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0&, facebook::jsi::Runtime&>(facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0&, facebook::jsi::Runtime&) + 32
36  <ANON_APPBUNDLE>.debug.dylib      	       0x10434b70c void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:de190102]<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0&, facebook::jsi::Runtime&>(facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0&, facebook::jsi::Runtime&) + 32
37  <ANON_APPBUNDLE>.debug.dylib      	       0x10434b6e0 std::__1::__function::__alloc_func<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0, std::__1::allocator<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0>, void (facebook::jsi::Runtime&)>::operator()[abi:de190102](facebook::jsi::Runtime&) + 36
38  <ANON_APPBUNDLE>.debug.dylib      	       0x10434a578 std::__1::__function::__func<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0, std::__1::allocator<facebook::react::RuntimeScheduler_Modern::scheduleEventLoop()::$_0>, void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) + 36
39  <ANON_APPBUNDLE>.debug.dylib      	       0x10337a158 std::__1::__function::__value_func<void (facebook::jsi::Runtime&)>::operator()[abi:de190102](facebook::jsi::Runtime&) const + 68
40  <ANON_APPBUNDLE>.debug.dylib      	       0x10337a108 std::__1::function<void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) const + 32
41  <ANON_APPBUNDLE>.debug.dylib      	       0x10415d340 _ZZZN8facebook5react13ReactInstanceC1ENSt3__110unique_ptrINS0_9JSRuntimeENS2_14default_deleteIS4_EEEENS2_10shared_ptrINS0_18MessageQueueThreadEEENS8_INS0_12TimerManagerEEENS2_8functionIFvRNS_3jsi7RuntimeERKNS0_14JsErrorHandler14ProcessedErrorEEEEPNS0_18jsinspector_modern10HostTargetEENK3$_0clINSD_IFvSG_EEEEEDaT_ENKUlvE_clEv + 164
42  <ANON_APPBUNDLE>.debug.dylib      	       0x10415d290 _ZNSt3__18__invokeB8de190102IRZZN8facebook5react13ReactInstanceC1ENS_10unique_ptrINS2_9JSRuntimeENS_14default_deleteIS5_EEEENS_10shared_ptrINS2_18MessageQueueThreadEEENS9_INS2_12TimerManagerEEENS_8functionIFvRNS1_3jsi7RuntimeERKNS2_14JsErrorHandler14ProcessedErrorEEEEPNS2_18jsinspector_modern10HostTargetEENK3$_0clINSE_IFvSH_EEEEEDaT_EUlvE_JEEEDTclclsr3stdE7declvalISW_EEspclsr3stdE7declvalIT0_EEEEOSW_DpOSZ_ + 24
43  <ANON_APPBUNDLE>.debug.dylib      	       0x10415d248 _ZNSt3__128__invoke_void_return_wrapperIvLb1EE6__callB8de190102IJRZZN8facebook5react13ReactInstanceC1ENS_10unique_ptrINS4_9JSRuntimeENS_14default_deleteIS7_EEEENS_10shared_ptrINS4_18MessageQueueThreadEEENSB_INS4_12TimerManagerEEENS_8functionIFvRNS3_3jsi7RuntimeERKNS4_14JsErrorHandler14ProcessedErrorEEEEPNS4_18jsinspector_modern10HostTargetEENK3$_0clINSG_IFvSJ_EEEEEDaT_EUlvE_EEEvDpOT_ + 24
44  <ANON_APPBUNDLE>.debug.dylib      	       0x10415d224 _ZNSt3__110__function12__alloc_funcIZZN8facebook5react13ReactInstanceC1ENS_10unique_ptrINS3_9JSRuntimeENS_14default_deleteIS6_EEEENS_10shared_ptrINS3_18MessageQueueThreadEEENSA_INS3_12TimerManagerEEENS_8functionIFvRNS2_3jsi7RuntimeERKNS3_14JsErrorHandler14ProcessedErrorEEEEPNS3_18jsinspector_modern10HostTargetEENK3$_0clINSF_IFvSI_EEEEEDaT_EUlvE_NS_9allocatorISY_EEFvvEEclB8de190102Ev + 28
45  <ANON_APPBUNDLE>.debug.dylib      	       0x10415bf64 _ZNSt3__110__function6__funcIZZN8facebook5react13ReactInstanceC1ENS_10unique_ptrINS3_9JSRuntimeENS_14default_deleteIS6_EEEENS_10shared_ptrINS3_18MessageQueueThreadEEENSA_INS3_12TimerManagerEEENS_8functionIFvRNS2_3jsi7RuntimeERKNS3_14JsErrorHandler14ProcessedErrorEEEEPNS3_18jsinspector_modern10HostTargetEENK3$_0clINSF_IFvSI_EEEEEDaT_EUlvE_NS_9allocatorISY_EEFvvEEclEv + 28
46  <ANON_APPBUNDLE>.debug.dylib      	       0x10337c34c std::__1::__function::__value_func<void ()>::operator()[abi:de190102]() const + 60
47  <ANON_APPBUNDLE>.debug.dylib      	       0x10337c304 std::__1::function<void ()>::operator()() const + 24
48  <ANON_APPBUNDLE>.debug.dylib      	       0x103abdbe8 facebook::react::tryAndReturnError(std::__1::function<void ()> const&) + 24
49  <ANON_APPBUNDLE>.debug.dylib      	       0x103aea194 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 36
50  <ANON_APPBUNDLE>.debug.dylib      	       0x103aeec44 facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0::operator()() const + 80
51  <ANON_APPBUNDLE>.debug.dylib      	       0x103aeebe8 decltype(std::declval<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0&>()()) std::__1::__invoke[abi:de190102]<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0&) + 24
52  <ANON_APPBUNDLE>.debug.dylib      	       0x103aeeba0 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:de190102]<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0&) + 24
53  <ANON_APPBUNDLE>.debug.dylib      	       0x103aeeb7c std::__1::__function::__alloc_func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0>, void ()>::operator()[abi:de190102]() + 28
54  <ANON_APPBUNDLE>.debug.dylib      	       0x103aed8ac std::__1::__function::__func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_0>, void ()>::operator()() + 28
55  <ANON_APPBUNDLE>.debug.dylib      	       0x10337c34c std::__1::__function::__value_func<void ()>::operator()[abi:de190102]() const + 60
56  <ANON_APPBUNDLE>.debug.dylib      	       0x10337c304 std::__1::function<void ()>::operator()() const + 24
57  <ANON_APPBUNDLE>.debug.dylib      	       0x103ae9f34 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 48
58  CoreFoundation                	       0x19ffbd9b0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 27
59  CoreFoundation                	       0x19ff60188 __CFRunLoopDoBlocks + 351
60  CoreFoundation                	       0x19ff61688 __CFRunLoopRun + 2383
61  CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
62  <ANON_APPBUNDLE>.debug.dylib      	       0x104148514 +[RCTJSThreadManager runRunLoop] + 312
63  Foundation                    	       0x19ec40804 __NSThread__start__ + 731
64  libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
65  libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 5 name:  hades
Thread 5:
0   libsystem_kernel.dylib        	       0x1f1175438 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x22a65de50 _pthread_cond_wait + 983
2   libc++.1.dylib                	       0x1b0a552c4 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 31
3   hermes                        	       0x1084a75c8 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x1084a752c void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
6   libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 6 name:  com.apple.CFStream.LegacyThread
Thread 6:
0   libsystem_kernel.dylib        	       0x1f116fce4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1f117339c mach_msg2_internal + 75
2   libsystem_kernel.dylib        	       0x1f11732b8 mach_msg_overwrite + 427
3   libsystem_kernel.dylib        	       0x1f1173100 mach_msg + 23
4   CoreFoundation                	       0x19ff62900 __CFRunLoopServiceMachPort + 159
5   CoreFoundation                	       0x19ff611f0 __CFRunLoopRun + 1207
6   CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
7   CoreFoundation                	       0x1a003cf70 _legacyStreamRunLoop_workThread + 299
8   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
9   libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 7 name:  com.facebook.SocketRocket.NetworkThread
Thread 7:
0   libsystem_kernel.dylib        	       0x1f116fce4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1f117339c mach_msg2_internal + 75
2   libsystem_kernel.dylib        	       0x1f11732b8 mach_msg_overwrite + 427
3   libsystem_kernel.dylib        	       0x1f1173100 mach_msg + 23
4   CoreFoundation                	       0x19ff62900 __CFRunLoopServiceMachPort + 159
5   CoreFoundation                	       0x19ff611f0 __CFRunLoopRun + 1207
6   CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
7   Foundation                    	       0x19ebda79c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
8   <ANON_APPBUNDLE>.debug.dylib      	       0x1044b5ea4 -[SRRunLoopThread main] + 268
9   Foundation                    	       0x19ec40804 __NSThread__start__ + 731
10  libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
11  libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 8 name:  com.apple.NSURLConnectionLoader
Thread 8:
0   libsystem_kernel.dylib        	       0x1f116fce4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1f117339c mach_msg2_internal + 75
2   libsystem_kernel.dylib        	       0x1f11732b8 mach_msg_overwrite + 427
3   libsystem_kernel.dylib        	       0x1f1173100 mach_msg + 23
4   CoreFoundation                	       0x19ff62900 __CFRunLoopServiceMachPort + 159
5   CoreFoundation                	       0x19ff611f0 __CFRunLoopRun + 1207
6   CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
7   CFNetwork                     	       0x1a158230c +[__CFN_CoreSchedulingSetRunnable _run:] + 415
8   Foundation                    	       0x19ec40804 __NSThread__start__ + 731
9   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
10  libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 9 name:  com.apple.CFSocket.private
Thread 9:
0   libsystem_kernel.dylib        	       0x1f117732c __select + 8
1   CoreFoundation                	       0x19ffe8a44 __CFSocketManager + 703
2   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
3   libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 10 name:  hades
Thread 10:
0   libsystem_kernel.dylib        	       0x1f1175438 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x22a65de50 _pthread_cond_wait + 983
2   libc++.1.dylib                	       0x1b0a552c4 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 31
3   hermes                        	       0x1084a75c8 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x1084a752c void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
6   libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 11 name:  JavaScriptCore libpas scavenger
Thread 11:
0   libsystem_kernel.dylib        	       0x1f1175438 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x22a65de50 _pthread_cond_wait + 983
2   JavaScriptCore                	       0x1b7871864 scavenger_thread_main + 1583
3   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
4   libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 12 name:  com.apple.CoreMotion.MotionThread
Thread 12:
0   libsystem_kernel.dylib        	       0x1f116fce4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1f117339c mach_msg2_internal + 75
2   libsystem_kernel.dylib        	       0x1f11732b8 mach_msg_overwrite + 427
3   libsystem_kernel.dylib        	       0x1f1173100 mach_msg + 23
4   CoreFoundation                	       0x19ff62900 __CFRunLoopServiceMachPort + 159
5   CoreFoundation                	       0x19ff611f0 __CFRunLoopRun + 1207
6   CoreFoundation                	       0x19ff62c3c CFRunLoopRunSpecific + 571
7   CoreFoundation                	       0x19ffdd674 CFRunLoopRun + 63
8   CoreMotion                    	       0x1ad8ade4c 0x1ad8ad939 + 1299
9   libsystem_pthread.dylib       	       0x22a65f344 _pthread_start + 135
10  libsystem_pthread.dylib       	       0x22a65cab8 thread_start + 7

Thread 13:
0   libsystem_pthread.dylib       	       0x22a65caa4 start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	       0x22a65caa4 start_wqthread + 0

Thread 15 name:   Dispatch queue: captureSessionQueue
Thread 15 Crashed:
0   <ANON_APPBUNDLE>.debug.dylib      	       0x103cac538 std::__1::weak_ptr<facebook::react::EventDispatcher const>::lock() const + 68
1   <ANON_APPBUNDLE>.debug.dylib      	       0x103cac27c facebook::react::EventEmitter::dispatchEvent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<facebook::react::EventPayload const>, facebook::react::RawEvent::Category) const + 124
2   <ANON_APPBUNDLE>.debug.dylib      	       0x103cabf00 facebook::react::EventEmitter::dispatchEvent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&)> const&, facebook::react::RawEvent::Category) const + 100
3   <ANON_APPBUNDLE>.debug.dylib      	       0x1033cfd94 expo::ExpoViewEventEmitter::dispatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&)>) const + 72
4   <ANON_APPBUNDLE>.debug.dylib      	       0x1033a6f58 -[ExpoFabricViewObjC dispatchEvent:payload:] + 252
5   <ANON_APPBUNDLE>.debug.dylib      	       0x10346f1f8 closure #1 in closure #1 in ExpoFabricView.installEventDispatchers() + 444
6   <ANON_APPBUNDLE>.debug.dylib      	       0x1034c132c thunk for @escaping @callee_guaranteed (@guaranteed [String : Any]) -> () + 108
7   <ANON_APPBUNDLE>.debug.dylib      	       0x103464a28 EventDispatcher.callAsFunction(_:) + 180
8   <ANON_APPBUNDLE>.debug.dylib      	       0x103224c4c CameraView.emitAvailableLenses() + 248
9   <ANON_APPBUNDLE>.debug.dylib      	       0x103221504 $defer #1 () in CameraView.addDevice(_:) + 128
10  <ANON_APPBUNDLE>.debug.dylib      	       0x103221270 CameraView.addDevice(_:) + 564
11  <ANON_APPBUNDLE>.debug.dylib      	       0x103220d64 CameraView.updateDevice() + 808
12  <ANON_APPBUNDLE>.debug.dylib      	       0x10322d554 closure #1 in CameraView.initializeCaptureSessionInput() + 40
13  <ANON_APPBUNDLE>.debug.dylib      	       0x1030d3ec8 thunk for @escaping @callee_guaranteed @Sendable () -> () + 48
14  libdispatch.dylib             	       0x1a7edcaac _dispatch_call_block_and_release + 31
15  libdispatch.dylib             	       0x1a7ef6584 _dispatch_client_callout + 15
16  libdispatch.dylib             	       0x1a7ee52d0 _dispatch_lane_serial_drain + 739
17  libdispatch.dylib             	       0x1a7ee5dac _dispatch_lane_invoke + 387
18  libdispatch.dylib             	       0x1a7ef01dc _dispatch_root_queue_drain_deferred_wlh + 291
19  libdispatch.dylib             	       0x1a7eefa60 _dispatch_workloop_worker_thread + 539
20  libsystem_pthread.dylib       	       0x22a65ca0c _pthread_wqthread + 291
21  libsystem_pthread.dylib       	       0x22a65caac start_wqthread + 7

Thread 16:
0   libsystem_pthread.dylib       	       0x22a65caa4 start_wqthread + 0


Thread 15 crashed with ARM Thread State (64-bit):
    x0: 0x000000016d6460b8   x1: 0x000000016d645d7f   x2: 0x0000000104895270   x3: 0x000000016d646178
    x4: 0x000000011ff61840   x5: 0x0000000000000000   x6: 0x000000000040d960   x7: 0xec0df026feee03a7
    x8: 0x0000000000000018   x9: 0x000000016d6460b8  x10: 0x000000011ff61858  x11: 0x0000000800000003
   x12: 0x000000000000081c  x13: 0x000000011ff60000  x14: 0x0000000000000001  x15: 0xffffffffb00007ff
   x16: 0x00000001bbe4bd90  x17: 0x23eb00020ac93d50  x18: 0x0000000000000000  x19: 0x000000013d651a70
   x20: 0x000000013d653ab0  x21: 0x0000000000000000  x22: 0x000000020ac98bc0  x23: 0x000000016d6470e0
   x24: 0x0000000000000000  x25: 0x00000001370cb700  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000114   fp: 0x000000016d645fb0   lr: 0x0000000103cac534
    sp: 0x000000016d645f80   pc: 0x0000000103cac538 cpsr: 0x60001000
   far: 0x0000000000000020  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x102b88000 -        0x102b93fff <ANON_APPBUNDLE> arm64  <98ac7a1b30a33b29aeb3c4467c35ff1c> /var/containers/Bundle/Application/E1DBC20B-CC8A-44C8-9D54-38AAA10F751D/<ANON_APPBUNDLE>.app/<ANON_APPBUNDLE>
       0x103048000 -        0x104a87fff <ANON_APPBUNDLE>.debug.dylib arm64  <bd7c4f6f7699312eb9ddc52d2da4206d> /private/var/containers/Bundle/Application/E1DBC20B-CC8A-44C8-9D54-38AAA10F751D/<ANON_APPBUNDLE>.app/<ANON_APPBUNDLE>.debug.dylib
       0x1082f8000 -        0x108677fff hermes arm64  <7fd659d8a1f83dffb8a58dd1e40f6eca> /private/var/containers/Bundle/Application/E1DBC20B-CC8A-44C8-9D54-38AAA10F751D/<ANON_APPBUNDLE>.app/Frameworks/hermes.framework/hermes
       0x102d60000 -        0x102d6bfff libobjc-trampolines.dylib arm64e  <9136d8ba22ff3f129caddfc4c6dc51de> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
       0x1a7edb000 -        0x1a7f20b1f libdispatch.dylib arm64e  <395da84f715d334e8d41a16cd93fc83c> /usr/lib/system/libdispatch.dylib
       0x19ff51000 -        0x1a04cdfff CoreFoundation arm64e  <7821f73c378b3a10be90ef526b7dba93> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1ed140000 -        0x1ed148c7f GraphicsServices arm64e  <5ba62c226d3731999dfd0e0f7abebfa9> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x1a2840000 -        0x1a4781b5f UIKitCore arm64e  <96636f64106f30c8a78082dcebb0f443> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x1c6df9000 -        0x1c6e93857 dyld arm64e  <86d5253d4fd136f3b4ab25982c90cbf4> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? unknown-arch  <00000000000000000000000000000000> ???
       0x22a65c000 -        0x22a6683f3 libsystem_pthread.dylib arm64e  <b37430d8e3af33e481e1faed9ee26e8a> /usr/lib/system/libsystem_pthread.dylib
       0x1f116f000 -        0x1f11a8ebf libsystem_kernel.dylib arm64e  <9e195be11733345ea9bf50d0d7059647> /usr/lib/system/libsystem_kernel.dylib
       0x19ebcb000 -        0x19f83eddf Foundation arm64e  <34de055d8683380a9198c3347211d13d> /System/Library/Frameworks/Foundation.framework/Foundation
       0x1b0a34000 -        0x1b0ac3ff7 libc++.1.dylib arm64e  <d67033dd24503cd8b76caac221a7fb80> /usr/lib/libc++.1.dylib
       0x1a14e2000 -        0x1a18a7b9f CFNetwork arm64e  <a35a109c49d23986965d4ed7e0b6681e> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
       0x1b7826000 -        0x1b926175f JavaScriptCore arm64e  <e32426af64113260be0bbe0ad12e23c8> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
       0x1ad8a7000 -        0x1adcc4a9f CoreMotion arm64e  <cec80db7b3f23b179d4ebcfeb020ca2d> /System/Library/Frameworks/CoreMotion.framework/CoreMotion
       0x1bbe44000 -        0x1bbe5f15f libsystem_trace.dylib arm64e  <a800c18d6de43e089ae2280796d10789> /usr/lib/system/libsystem_trace.dylib

EOF
```
</details>
