### PR TITLE
fix(cli): add iPad as usbmux platform to os type

### LINKED ISSUE #29165: Unable to run on iPad and iPod after updating to Expo 51
### Summary

The same thing as [this](https://github.com/expo/expo/issues/28838) still happens on Expo@51.0.8 for iPad and iPod running iOS 15.8.2.
The output to `DEBUG=expo:apple-device npx expo run:ios --device` is
expo:apple-device Unknown usbmuxd platform (needs to be added to Expo CLI): iPad
and
expo:apple-device Unknown usbmuxd platform (needs to be added to Expo CLI): iPod

I thought 15.8 is not supported anymore but [this](https://docs.expo.dev/versions/latest/#support-for-android-and-ios-versions) said minimum OS is 13.4+.

### What platform(s) does this occur on?

iOS

### SDK Version

51.0.8

### Environment

System:
      OS: macOS 14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.14.1 - ~/.nodebrew/current/bin/node
      Yarn: 1.22.21 - ~/.nodebrew/current/bin/yarn
      npm: 9.3.1 - ~/.nodebrew/current/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/ichijo/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 29, 30, 31, 32, 33, 34
        Build Tools: 26.0.2, 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: managed

### Minimal reproducible example

Connect iPad or iPod device, create minimal Expo 51 app and show iOS device list as
```
npx create-expo-app --template blank
npx expo run:ios --device
```
then the output is
```
? Select a device ›  
❯   iPhone 15 (17.0)
    iPhone 15 Plus (17.0)
    iPhone 15 Pro (17.0) 
    iPhone 15 Pro Max (17.0)
    iPad Air (5th generation) (17.0)
    iPad (10th generation) (17.0)
    iPad mini (6th generation) (17.0)
    iPad Pro (11-inch) (4th generation) (17.0)
    iPad Pro (12.9-inch) (6th generation) (17.0)
    iPhone SE (3rd generation) (17.5)
  ↓ iPhone 15 (17.5)
```
On the contrary, if do the same thing for minimal Expo 50 app as
```
npx create-expo-app --template blank@50
npx expo run:ios --device
```
then the output is
```
? Select a device ›  
❯   🔌 ichijoのiPod7 (15.8.2)  
    🔌 iPadAir2 (15.8.2)  
    🌐 ichijoのiPod7 (15.8.2)  
    iPhone 15 (17.0)  
    iPhone 15 Plus (17.0)  
    iPhone 15 Pro (17.0)  
    iPhone 15 Pro Max (17.0)  
    iPad Air (5th generation) (17.0)  
    iPad (10th generation) (17.0)  
    iPad mini (6th generation) (17.0)  
  ↓ iPad Pro (11-inch) (4th generation) (17.0) 
```

### PR DESCRIPTION
**Pull request by moduval**
# Why
Fixes https://github.com/expo/expo/issues/29165

# How

Running the command: `EXPO_DEBUG=1 DEBUG=1 npx expo run:ios --device` we can see that this is missing iPad

```
  expo:apple-device:client:usbmuxd connectUsbmuxdSocket +18ms
  expo:apple-device:client:usbmuxd connect: 6 on port 62078 +1ms
  expo:apple-device:client:usbmuxd connect:device: {
  expo:apple-device:client:usbmuxd   DeviceID: 6,
  expo:apple-device:client:usbmuxd   MessageType: 'Attached',
  expo:apple-device:client:usbmuxd   Properties: {
  expo:apple-device:client:usbmuxd     ConnectionSpeed: 480000000,
  expo:apple-device:client:usbmuxd     ConnectionType: 'USB',
  expo:apple-device:client:usbmuxd     DeviceID: 6,
  expo:apple-device:client:usbmuxd     LocationID:****** ,
  expo:apple-device:client:usbmuxd     ProductID: 4779,
  expo:apple-device:client:usbmuxd     SerialNumber: '************************',
  expo:apple-device:client:usbmuxd     UDID: '*********************',
  expo:apple-device:client:usbmuxd     USBSerialNumber: '*********************'
  expo:apple-device:client:usbmuxd   }
  expo:apple-device:client:usbmuxd } +0ms
  expo:apple-device:protocol:usbmux socket write: {"messageType":"Connect","extraFields":{"DeviceID":6,"PortNumber":32498}} +1ms
  expo:apple-device:protocol:usbmux Response: {"MessageType":"Result","Number":0} +2ms
  expo:apple-device:client:usbmuxd connect:device:response: { MessageType: 'Result', Number: 0 } +2ms
  expo:apple-device:client:lockdownd getAllValues +0ms
  expo:apple-device:protocol:lockdown socket write: {"Request":"GetValue"} +0ms
  expo:devicectl No devices found.
  expo:devicectl  +0ms
  expo:apple-device:protocol:lockdown Response: {"Request":"GetValue","Value":{"BoardId":60,"BuildVersion":"20D67","CPUArchitecture":"arm64e","ChipID":32807,"DeviceClass":"iPad","DeviceColor":"1","DeviceName":"Marc-Olivier’s iPad","DieID":5164304050962478,"HardwareModel":"J417AP","HasSiDP":true,"PartitionType":"GUID_partition_scheme","ProductName":"iPhone OS","ProductType":"iPad8,9","ProductVersion":"16.3.1","ProductionSOC":true,"ProtocolVersion":"2","SupportedDeviceFamilies":[1,2],"TelephonyCapability":false,"UniqueChipID":*****************,"UniqueDeviceID":"****************","WiFiAddress":"**************"}} +31ms
  expo:apple-device Unknown usbmuxd platform (needs to be added to Expo CLI): iPad +0ms

```

I added the iPad in the list

# Test Plan

I connected my Ipad and the run the cli with the changed. I am now able to see my iPad in the device list.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/run/ios/appleDevice/AppleDevice.ts [hunk 1]
```diff
@@ -79,6 +79,7 @@ function coerceUsbmuxdPlatformToOsType(platform: string): OSType {
   // The only connectable device I have to test against...
   switch (platform) {
     case 'iPhone':
+    case 'iPad':
```
Comment (gabrieldonadel) [inline packages/@expo/cli/src/run/ios/appleDevice/AppleDevice.ts:82]: This should probably return `iPadOS`

Comment (EvanBacon) [reply packages/@expo/cli/src/run/ios/appleDevice/AppleDevice.ts:82]: Not according to the logs (note the `DeviceClass` type sent by Apple):
```
  expo:apple-device:protocol:lockdown Response: {"Request":"GetValue","Value":{"BoardId":60,"BuildVersion":"20D67","CPUArchitecture":"arm64e","ChipID":32807,"DeviceClass":"iPad","DeviceColor":"1","DeviceName":"Marc-Olivier’s iPad","DieID":5164304050962478,"HardwareModel":"J417AP","HasSiDP":true,"PartitionType":"GUID_partition_scheme","ProductName":"iPhone OS","ProductType":"iPad8,9","ProductVersion":"16.3.1","ProductionSOC":true,"ProtocolVersion":"2","SupportedDeviceFamilies":[1,2],"TelephonyCapability":false,"UniqueChipID":5164304050962478,"UniqueDeviceID":"00008027-001258E83C78402E","WiFiAddress":"64:0b:d7:b1:4b:2d"}} +31ms
```

**Review by EvanBacon — APPROVED** [review]

File: packages/@expo/cli/src/run/ios/appleDevice/AppleDevice.ts (hunk 1 above)
Comment (moduval) [reply packages/@expo/cli/src/run/ios/appleDevice/AppleDevice.ts:82]: I think he was talking about the return statement that state ios instead of ipad os. I will need to take a look further in the implementation to see if this change something. 

Ps: @EvanBacon can you remove my ipad serial number from your copied log, i edited my PR description to remove it on my side.

Comment (moduval) [reply packages/@expo/cli/src/run/ios/appleDevice/AppleDevice.ts:82]: Ok, i have taken a look at it and ios seems to be the good parameter. It is also listed in Xcode as ios: 
image

**Review by gabrieldonadel — APPROVED** [review]
