### PR TITLE
[expo-notifications][Android] Eliminate unsupported types when processing notification intents from onCreate/onNewIntent

### LINKED ISSUE #30738: [expo-notifications] Crash immediately after second app start
### Minimal reproducible example

https://github.com/wonderlul/expo-notifications-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Hello Everyone,

Minimal reproducible example was delivered.

In summary, after installation of expo-notifications the app is crashing after second attempt to open it. I didn't check it on iOS yet. 

Below the example from Logcat, but there's a lot more than that.

```
024-07-31 12:21:22.698  8946-9004  tificationstes          com.exponotificationstest            A  java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.IllegalArgumentException: Could not put 'class android.os.UserHandle' to WritableMap
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.types.JSTypeConverterHelperKt.putGeneric(com.facebook.react.bridge.WritableMap, java.lang.String, java.lang.Object) (JSTypeConverterHelper.kt:171)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.bridge.WritableMap expo.modules.kotlin.types.JSTypeConverterHelperKt.toJSValue(android.os.Bundle, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverterHelper.kt:46)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Object expo.modules.kotlin.types.JSTypeConverter.convertToJSValue(java.lang.Object, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverter.kt:29)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.bridge.WritableMap expo.modules.kotlin.types.JSTypeConverterHelperKt.toJSValue(android.os.Bundle, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverterHelper.kt:45)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Object expo.modules.kotlin.types.JSTypeConverter.convertToJSValue(java.lang.Object, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverter.kt:29)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.bridge.WritableMap expo.modules.kotlin.types.JSTypeConverterHelperKt.toJSValue(android.os.Bundle, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverterHelper.kt:45)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Object expo.modules.kotlin.types.JSTypeConverter.convertToJSValue(java.lang.Object, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverter.kt:29)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.bridge.WritableMap expo.modules.kotlin.types.JSTypeConverterHelperKt.toJSValue(android.os.Bundle, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverterHelper.kt:45)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Object expo.modules.kotlin.types.JSTypeConverter.convertToJSValue(java.lang.Object, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverter.kt:29)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.bridge.WritableMap expo.modules.kotlin.types.JSTypeConverterHelperKt.toJSValue(android.os.Bundle, expo.modules.kotlin.types.JSTypeConverter$ContainerProvider) (JSTypeConverterHelper.kt:45)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.events.KModuleEventEmitterWrapper.emit(java.lang.String, android.os.Bundle) (KModuleEventEmitterWrapper.kt:28)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.modules.Module.sendEvent(java.lang.String, android.os.Bundle) (Module.kt:31)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.notifications.notifications.emitting.NotificationsEmitter.onNotificationResponseIntentReceived(android.os.Bundle) (NotificationsEmitter.kt:77)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.notifications.notifications.NotificationManager.addListener(expo.modules.notifications.notifications.interfaces.NotificationListener) (NotificationManager.java:62)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.notifications.notifications.emitting.NotificationsEmitter$definition$lambda$3$$inlined$OnCreate$1.invoke() (ModuleDefinitionBuilder.kt:145)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Object expo.modules.notifications.notifications.emitting.NotificationsEmitter$definition$lambda$3$$inlined$OnCreate$1.invoke() (ModuleDefinitionBuilder.kt:75)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.events.BasicEventListener.call() (EventListener.kt:13)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.ModuleHolder.post(expo.modules.kotlin.events.EventName) (ModuleHolder.kt:98)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.ModuleRegistry.postOnCreate() (ModuleRegistry.kt:79)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.AppContext.onCreate() (AppContext.kt:142)
                                                                                                    java_vm_ext.cc:591]   at void expo.modules.kotlin.KotlinInteropModuleRegistry.emitOnCreate() (KotlinInteropModuleRegistry.kt:100)
```

Yesterday everything was working great. I saw that new version of expo-notifications was released several hours ago and since then the problem occurs.

I deliberately set the New Architecture since we're using it in our project.  

If anything more is needed please let me know.

Best regards

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/wonderlul/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.24 => 51.0.24 
      expo-router: ~3.5.20 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.3
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.

### PR DESCRIPTION
**Pull request by douglowder**
# Why

On Android, when a notification is tapped to open the app, the intent passed into the Android lifecycle listeners may have properties in the `extras` bundle that are not supported in converting to `WritableMap` for sending events to JS. This potentially leads to a crash.

This PR fixes #30738.

# How

- New methods in `Utils` to filter out bundle properties that are not convertible.
- `NotificationSerializer` is modified to use the above new methods to filter out unconvertible values when processing the intent extras in `onCreate()` and `onNewIntent()` from `ExpoNotificationLifecycleListener`.

# Test Plan

- CI should pass
- The test app should not crash when this condition is encountered

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by douglowder** [comment]
* **#30750** <a href="https://app.graphite.dev/github/pr/expo/expo/30750?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @douglowder and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by wschurman** [comment]
Is it possible to use `Arguments.fromBundle`? See https://github.com/expo/expo/pull/23428/files#r1260246415 for similar discussion (I think?)

**Comment by wschurman** [comment]
Or, I guess the question is more just curious why this exception didn't get hit pre-blame-rev (https://github.com/expo/expo/pull/30615). I.e. why `serializedRequest.putBundle("content", toBundle(request.getContent()));` didn't cause it.

**Comment by wschurman** [comment]
Jumping in to review as requested. Trying to gain context necessary from reading code but could use help with answering the following: 
- Blame rev: https://github.com/expo/expo/pull/30615
- That PR was necessary due to some (implicit) breaking change somewhere? (could use a pointer to the breaking change that required that PR to be added). What caused the remapping? 
- Does this mean that clients on the old version of the library (pre that PR) just aren't receiving notifications correctly?
- I assume the reason this needed to be fixed on the client is that the expo-notifications library can be used without using the Expo notifications service (i.e. just plain firebase) and we needed to translate that response to our agreed-upon JS event data format? If that's the case, was the implicit breaking change in firebase?

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt [hunk 1]
```diff
@@ -17,3 +26,77 @@ internal fun createDefaultResultReceiver(
     }
   }
 }
+
+/**
+ * Returns true if object is convertible to a WritableMap element
+ */
+internal fun isWritableMapConvertible(value: Any?): Boolean {
```
Comment (wschurman) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt:33]: This seems a bit fragile and likely to cause issues if new types are added that we forgot to handle here, or if support for a new type is added to WritableMap. Is it possible to use something like recursive calls to `Arguments.fromBundle` wrapped with try/catches to know what can be serialized?

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt [hunk 2]
```diff
@@ -17,3 +26,77 @@ internal fun createDefaultResultReceiver(
...
+  return when (value) {
+    null, is Unit -> true
+    is Bundle -> true
```
Comment (wschurman) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt:36]: what happens if this bundle has a nested element that can't be serialized? (I think anything here needs to be recursive)

**Review by wschurman — CHANGES_REQUESTED** [review]

**Review by christopherwalter — APPROVED** [review]

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt (hunk 1 above)
Comment (douglowder) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt:33]: We could do exactly that, but it would be much less performant. This method is actually more or less copied from our own code in `expo-modules-core`, specifically `JSTypeConverter`. So I can add a note here that any changes in `JSTypeConverter` may require changes here.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt (hunk 2 above)
Comment (douglowder) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt:36]: The recursiveness is handled in `filteredBundleForWritableMap` below.

**Comment by douglowder** [comment]
> Or, I guess the question is more just curious why this exception didn't get hit pre-blame-rev (https://github.com/expo/expo/pull/30615). I.e. why `serializedRequest.putBundle("content", toBundle(request.getContent()));` didn't cause it.

This exception only gets hit when

- the user is using Firebase or other non-Expo service to send a notification
- the app is opened in response to a notification, so our lifecycle listeners get called and the notification response structure is created from the intent extras, where pretty much any type object might be inserted

The bizarre thing is that only some customers seem to be hitting this. I have not yet seen it in my testing, but there are so many ways to send notifications and different properties that can be added to them, that it is almost impossible to check all the different breakage possibilities.

**Comment by douglowder** [comment]
> - I assume the reason this needed to be fixed on the client is that the expo-notifications library can be used without using the Expo notifications service (i.e. just plain firebase) and we needed to translate that response to our agreed-upon JS event data format? If that's the case, was the implicit breaking change in firebase?

This is the exact reason why the breaking change had to be made. The new Firebase v1 protocol seems to be more strict about the shape of the payload, and customers were seeing issues where we were taking that payload and remapping on the Android clients as if they were coming from Expo service.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt [hunk 3]
```diff
@@ -17,3 +26,77 @@ internal fun createDefaultResultReceiver(
...
+fun filteredBundleForWritableMap(bundle: Bundle): Bundle? {
+  val result = Bundle()
+  result.putAll(bundle)
+  bundle.keySet().forEach { key: String ->
+    val value = bundle[key]
+    if (!isWritableMapConvertible(value)) {
+      result.remove(key)
+    } else if (value is Bundle) {
+      result.putBundle(key, filteredBundleForWritableMap(value))
+    }
```
Comment (wschurman) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt:75]: flip order of these if and else if

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt (hunk 1 above)
Comment (douglowder) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt]: I've moved the test for convertibility of an object to `JSTypeConverter`, since `expo-notifications` has no visibility into internal RN classes like `WritableMap`. The new method is no longer checking through a list of hardcoded types -- it is calling the same method that causes the crash we are seeing, and catching the exception.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt (hunk 3 above)
Comment (douglowder) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt]: Done

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt [hunk 4]
```diff
@@ -17,3 +26,77 @@ internal fun createDefaultResultReceiver(
...
+    is RawTypedArrayHolder -> true
+    is Iterable<*> -> true
+    else -> false
+  }
+}
+
+/**
+ * Given an input bundle, creates a new bundle with non-WritableMap-convertible objects removed
+ */
+fun filteredBundleForWritableMap(bundle: Bundle): Bundle? {
```
[the remark this answers is not in the document]
Comment (douglowder) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/Utils.kt]: Fixed in a later commit

**Comment by ekremgunes** [comment]
We are waiting to approve . Thanks mr @douglowder

**Comment by yellow-umbrella-studio** [comment]
> We are waiting to approve . Thanks mr @douglowder.
> 
> update: I added new lines from pr and fixed my crash.

Hi, which lines should i add to fix the issue?

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt [hunk 5]
```diff
@@ -54,6 +54,23 @@ object JSTypeConverter {
...
+  fun valueIsConvertibleToJSValue(value: Any?, containerProvider: ContainerProvider = DefaultContainerProvider): Boolean {
+    val testMap = containerProvider.createMap()
+    try {
+      val convertedValue = JSTypeConverter.convertToJSValue(value, containerProvider)
+      testMap.putGeneric("testKey", convertedValue)
+    } catch (e: Throwable) {
+      return false
+    }
+    return true
+  }
```
Comment (lukmccall) [inline packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt:71]: I don't like this approach, but I understand the current limitation. We can't fix all the problems correctly because we would have to stop using `folly::dynamic` entirely. We can temporarily add such a function, but let's move it to the `expo-notifications` package.

Comment (douglowder) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt:71]: Sadly, `expo-notifications` can't access the `WritableMap` class, since it doesn't have a direct dependency on RN. Also, keeping this method here might help to keep it in sync if `JSTypeConverter` changes in future.

Comment (lukmccall) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt:71]: This version no longer uses `WritableMap`, and I don't see how keeping it in `expo-modules-core` would help in syncing it with `JSTypeConverter`. You're using `JSTypeConverter.convertToJSValue` directly, which should be enough.

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt [hunk 6]
```diff
@@ -54,6 +54,23 @@ object JSTypeConverter {
     }
   }
 
+  /**
+   * Tests that a converted value can be added to a map for inclusion in the payload of a JS event
+   * without throwing
+   */
+  @JvmStatic
+  fun valueIsConvertibleToJSValue(value: Any?, containerProvider: ContainerProvider = DefaultContainerProvider): Boolean {
```
Comment (wschurman) [inline packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt:62]:
```suggestion
  fun isValueConvertibleToJSValue(value: Any?, containerProvider: ContainerProvider = DefaultContainerProvider): Boolean {
```

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt (hunk 5 above)
Comment (wschurman) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt:71]: I don't have a strong opinion of where this should live. If moving it to `expo-notifications` is easy then I guess that's fine.

If it is in `expo-modules-core` though, we should probably add a test for it. In `expo-notifications` it'd still be good to add a test but not as strictly necessary.

**Review by wschurman — APPROVED** [review]
A few inline comments.

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt (hunk 5 above)
Comment (douglowder) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt:71]: @lukmccall the `convertToJSValue` does not throw for generic values. Placing that value inside a bundle and calling `convertToJSValue` is what causes the `WritableMap` exception.

Comment (douglowder) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt]: @wschurman @lukmccall I've changed the `filteredBundleForJSTypeConverter` implementation so that no `expo-modules-core` change is needed. The code is a little more complex, but works correctly in local testing. Also structured the implementation so that the check for what values may be converted is a replaceable function --  the idea is to make unit testing easier.

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt (hunk 6 above)
Comment (douglowder) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverter.kt]: Done

**Comment by douglowder** [comment]
Published in `expo-notifications@0.28.15`
