### PR TITLE
[expo-image-picker][android] Clean `onActivityResult`

### LINKED ISSUE #7946: ImagePicker Crashing with Expo 37.0.0 Android 8.1
### Environment

Client version `2.15.4`

SDK `37`

Android `8.1.0`

Platform.OS `android`
Platform.Version `27`

### Steps to Reproduce

From the official docs https://docs.expo.io/versions/latest/sdk/imagepicker/
Run the app https://snack.expo.io/oFN6U26kW

Tap `Pick an image from camera roll`
Wait for image gallery to load
Tap on a picture
Tap `Crop`

### Expected Behavior

A picture is picked from `ImageLibrary` and loaded into the View

### Actual Behavior

Expo crashes (client reloads)

### Reproducible Demo

https://snack.expo.io/oFN6U26kW

### Related issues

#2925

### Device logs

```shell
adb devices

List of devices attached
0260eeef30673805	device

adb -s 0260eeef30673805 logcat --pid=$(adb shell pidof -s host.exp.exponent)
```

<details>
  <summary>Output</summary>

```shell
04-21 14:29:14.730 26089 26089 I TextToSpeech: Sucessfully bound to com.google.android.tts
04-21 14:29:14.735 26089 26089 D ReactNative: CatalystInstanceImpl.destroy() start
04-21 14:29:14.740 26089 26089 W unknown:Fresco: Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!
04-21 14:29:14.740 26089 26089 D SoLoader: init exiting
04-21 14:29:14.741 26089 26089 W unknown:ImagePipelineFactory: ImagePipelineFactory has already been initialized! `ImagePipelineFactory.initialize(...)` should only be called once to avoid unexpected behavior.
04-21 14:29:14.744 26089 26507 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:15.316 26089 26572 D ReactNative: CatalystInstanceImpl.destroy() end
04-21 14:29:19.859 26089 26089 W c       : Could not find listener for key: experienceActivityKernelDidLoad
04-21 14:29:19.868 26089 26089 W c       : Could not find listener for key: openOptimisticExperienceActivity
04-21 14:29:19.868 26089 26089 W c       : Could not find listener for key: openExperienceActivity
04-21 14:29:19.928 26089 26094 I zygote64: Do partial code cache collection, code=243KB, data=169KB
04-21 14:29:19.933 26089 26094 I zygote64: After code cache collection, code=242KB, data=169KB
04-21 14:29:19.933 26089 26094 I zygote64: Increasing code cache capacity to 1024KB
04-21 14:29:19.936 26089 26099 I zygote64: CollectorTransition concurrent copying GC freed 31213(1379KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 11MB/23MB, paused 265us total 250.549ms
04-21 14:29:20.439 26089 26089 W unknown:Fresco: Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!
04-21 14:29:20.440 26089 26089 D SoLoader: init exiting
04-21 14:29:20.440 26089 26089 W unknown:ImagePipelineFactory: ImagePipelineFactory has already been initialized! `ImagePipelineFactory.initialize(...)` should only be called once to avoid unexpected behavior.
04-21 14:29:21.225 26089 26089 E e       : java.lang.RuntimeException: A TaskDescription's primary color should be opaque
04-21 14:29:21.260 26089 26592 D b       : Using cached or embedded response.
04-21 14:29:21.260 26089 26592 D b       : Got cached OkHttp response for https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fsnack%2F1.0.0%2Fef6915b1309493f18dc5fd7e65fba036-37.0.0-android.js
04-21 14:29:21.260 26089 26592 D b       : Have cached source file for https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fsnack%2F1.0.0%2Fef6915b1309493f18dc5fd7e65fba036-37.0.0-android.js
04-21 14:29:21.263 26089 26089 D SoLoader: init exiting
04-21 14:29:21.281 26089 26089 W c       : Could not find listener for key: readyForBundle
04-21 14:29:21.281 26089 26089 E e       : java.lang.RuntimeException: A TaskDescription's primary color should be opaque
04-21 14:29:21.283 26089 26089 E k       : java.lang.NoSuchMethodException
04-21 14:29:21.283 26089 26089 W System.err: java.lang.NoSuchMethodException
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.k.a(RNObject.java:33)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.k.a(RNObject.java:17)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.k.a(RNObject.java:12)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.l.a(ReactNativeActivity.java:37)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$d.onSuccess(ExperienceActivity.java:1)
04-21 14:29:21.284 26089 26089 W System.err: 	at g.a.a.b.a(Exponent.java:75)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity.l(ExperienceActivity.java:1)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.l.a(ReactNativeActivity.java:19)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$c.execute(ExperienceActivity.java:3)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.v.c.a(AsyncCondition.java:2)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity.b(ExperienceActivity.java:6)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$b.a(ExperienceActivity.java:1)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.d.b(AppLoader.java:17)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.d.d(AppLoader.java:2)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.d.a(AppLoader.java:1)
04-21 14:29:21.284 26089 26089 W System.err: 	at host.exp.exponent.d$e.onBundleLoaded(AppLoader.java:11)
04-21 14:29:21.284 26089 26089 W System.err: 	at g.a.a.b$b$a.run(Exponent.java:1)
04-21 14:29:21.284 26089 26089 W System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
04-21 14:29:21.284 26089 26089 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-21 14:29:21.284 26089 26089 W System.err: 	at android.os.Looper.loop(Looper.java:164)
04-21 14:29:21.284 26089 26089 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-21 14:29:21.284 26089 26089 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 14:29:21.284 26089 26089 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-21 14:29:21.284 26089 26089 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-21 14:29:21.300 26089 26089 D ReactNative: ReactInstanceManager.ctor()
04-21 14:29:21.300 26089 26089 D SoLoader: init exiting
04-21 14:29:21.313 26089 26089 D ReactNative: ReactInstanceManager.createReactContextInBackground()
04-21 14:29:21.314 26089 26089 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
04-21 14:29:21.314 26089 26089 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
04-21 14:29:21.314 26089 26089 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-21 14:29:21.314 26089 26089 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
04-21 14:29:21.316 26089 26597 D ReactNative: ReactInstanceManager.createReactContext()
04-21 14:29:21.349 26089 26597 D ReactNative: Initializing React Xplat Bridge.
04-21 14:29:21.351 26089 26597 D ReactNative: Initializing React Xplat Bridge before initializeBridge
04-21 14:29:21.359 26089 26597 D ReactNative: Initializing React Xplat Bridge after initializeBridge
04-21 14:29:21.359 26089 26597 D ReactNative: CatalystInstanceImpl.runJSBundle()
04-21 14:29:21.360 26089 26597 D CatalystInstanceImpl: Loading script from file
04-21 14:29:21.360 26089 26599 D ReactNative: ReactInstanceManager.setupReactContext()
04-21 14:29:21.360 26089 26599 D ReactNative: CatalystInstanceImpl.initialize()
04-21 14:29:21.362 26089 26599 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-21 14:29:21.376 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTGroupViewManager
04-21 14:29:21.377 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTGroupShadowNode
04-21 14:29:21.378 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTShapeViewManager
04-21 14:29:21.379 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTShapeShadowNode
04-21 14:29:21.380 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTTextViewManager
04-21 14:29:21.380 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTTextShadowNode
04-21 14:29:21.381 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.checkbox.ReactCheckBoxManager
04-21 14:29:21.383 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.uimanager.LayoutShadowNode
04-21 14:29:21.387 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.picker.ReactDialogPickerManager
04-21 14:29:21.389 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.drawer.ReactDrawerLayoutManager
04-21 14:29:21.390 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.picker.ReactDropdownPickerManager
04-21 14:29:21.390 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
04-21 14:29:21.392 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
04-21 14:29:21.393 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.progressbar.ReactProgressBarViewManager
04-21 14:29:21.393 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.progressbar.ProgressBarShadowNode
04-21 14:29:21.394 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.scroll.ReactScrollViewManager
04-21 14:29:21.396 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.slider.ReactSliderManager
04-21 14:29:21.397 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
04-21 14:29:21.397 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.switchview.ReactSwitchManager
04-21 14:29:21.398 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
04-21 14:29:21.399 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
04-21 14:29:21.399 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTSurfaceViewManager
04-21 14:29:21.400 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.art.ARTSurfaceViewShadowNode
04-21 14:29:21.400 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
04-21 14:29:21.400 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
04-21 14:29:21.401 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.image.ReactImageManager
04-21 14:29:21.402 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.modal.ReactModalHostManager
04-21 14:29:21.403 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.modal.ModalHostShadowNode
04-21 14:29:21.403 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.ReactRawTextManager
04-21 14:29:21.404 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.ReactRawTextShadowNode
04-21 14:29:21.404 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.textinput.ReactTextInputManager
04-21 14:29:21.407 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.textinput.ReactTextInputShadowNode
04-21 14:29:21.408 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.ReactTextViewManager
04-21 14:29:21.409 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.ReactTextShadowNode
04-21 14:29:21.410 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.view.ReactViewManager
04-21 14:29:21.412 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.viewpager.ReactViewPagerManager
04-21 14:29:21.412 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.ReactVirtualTextViewManager
04-21 14:29:21.413 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.com.facebook.react.views.text.ReactVirtualTextShadowNode
04-21 14:29:21.413 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$GroupViewManager
04-21 14:29:21.415 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$RenderableShadowNode
04-21 14:29:21.416 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$PathViewManager
04-21 14:29:21.416 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$CircleViewManager
04-21 14:29:21.417 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$EllipseViewManager
04-21 14:29:21.418 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$LineViewManager
04-21 14:29:21.418 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$RectViewManager
04-21 14:29:21.419 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$TextViewManager
04-21 14:29:21.420 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$TSpanViewManager
04-21 14:29:21.420 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$TextPathViewManager
04-21 14:29:21.421 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$ImageViewManager
04-21 14:29:21.422 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$ClipPathViewManager
04-21 14:29:21.423 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$DefsViewManager
04-21 14:29:21.423 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$UseViewManager
04-21 14:29:21.423 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$SymbolManager
04-21 14:29:21.424 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$LinearGradientManager
04-21 14:29:21.425 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$RadialGradientManager
04-21 14:29:21.426 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$PatternManager
04-21 14:29:21.427 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$MaskManager
04-21 14:29:21.427 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$ForeignObjectManager
04-21 14:29:21.428 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager$MarkerManager
04-21 14:29:21.429 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.svg.SvgViewManager
04-21 14:29:21.429 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapCalloutManager
04-21 14:29:21.431 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager
04-21 14:29:21.433 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapPolylineManager
04-21 14:29:21.433 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapGradientPolylineManager
04-21 14:29:21.434 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapPolygonManager
04-21 14:29:21.434 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapCircleManager
04-21 14:29:21.435 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapManager
04-21 14:29:21.437 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapLiteManager
04-21 14:29:21.437 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapUrlTileManager
04-21 14:29:21.438 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapWMSTileManager
04-21 14:29:21.438 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapLocalTileManager
04-21 14:29:21.439 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapOverlayManager
04-21 14:29:21.439 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maps.AirMapHeatmapManager
04-21 14:29:21.440 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.lottie.LottieAnimationViewManager
04-21 14:29:21.440 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerRootViewManager
04-21 14:29:21.441 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerButtonViewManager
04-21 14:29:21.441 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.screens.ScreenContainerViewManager
04-21 14:29:21.442 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.screens.ScreenViewManager
04-21 14:29:21.442 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.screens.ScreenStackViewManager
04-21 14:29:21.442 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.screens.ScreenStackHeaderConfigViewManager
04-21 14:29:21.443 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.screens.ScreenStackHeaderSubviewManager
04-21 14:29:21.444 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.webview.RNCWebViewManager
04-21 14:29:21.445 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.safeareacontext.SafeAreaViewManager
04-21 14:29:21.445 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.sharedelement.RNSharedElementTransitionManager
04-21 14:29:21.446 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.maskedview.RNCMaskedViewManager
04-21 14:29:21.446 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.host.exp.exponent.modules.api.components.viewpager.ReactViewPagerManager
04-21 14:29:21.447 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.org.unimodules.adapters.react.views.ViewGroupManagerAdapter
04-21 14:29:21.447 26089 26599 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi37_0_0.org.unimodules.adapters.react.views.SimpleViewManagerAdapter
04-21 14:29:21.454 26089 26599 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:21.456 26089 26599 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:21.763 26089 26598 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:21.766 26089 26598 I chatty  : uid=10265(host.exp.exponent) mqt_js identical 1 line
04-21 14:29:21.770 26089 26598 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:22.940 26089 26598 I ReactNativeJS: Running "main" with {"initialProps":{"exp":{"initialUri":"exp://expo.io/@snack/sdk.37.0.0-x_LtBQuZG","manifest":{"id":"@snack/sdk.37.0.0-x_LtBQuZG","primaryColor":"#000","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fsnack%2F1.0.0%2Fef6915b1309493f18dc5fd7e65fba036-37.0.0-android.js","revisionId":"1.0.0-r.Nzv0OAZlS","releaseChannel":"default","notification":{"iconUrl":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png","color":"#000000","icon":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png"},"locales":{},"releaseId":"99ec5f05-110e-4072-b13f-022ac6f9c9ee","slug":"snack","name":"Snack","icon":"https://s3.amazonaws.com/exp-brand-assets/SnackIcon_200.png","loadedFromCache":false,"splash":{"image":"./splash.png","imageUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/19cbaa9ed24b8c3c3fdd031eeb73c1af"},"description":"Write code in Expo's online editor and instantly use it on your phone","publishedTime":"2020-04-01T00:54:47.040Z","iconUrl":"https://s3.amazonaws.com/exp-brand-assets/SnackIcon_200.png","isVerified":true,"version":"1.0.0","owner":"exponent","packagerOpts":{"assetExts":["ttf","otf","mp4"]},"sdkVersion":"37.0.0","platforms":["android","ios","web"],"hostUri":"exp.host/@snack/sdk.37.0.0-x_LtBQuZG","commitTime":"2020-04-01T00:54:47.140Z","dependencies":["@babel/polyfill","@expo/vector-icons","@unimodules/core","@unimodules/react-native-adapter","babel-plugin-transform-decorators-legacy","babel-preset-expo","diff","escape-string-regexp","expo","expo-analytics-amplitude","expo-asset","expo-barcode-scanner","expo-camera","expo-constants","expo-file-system","expo-gl","expo-image-picker","expo-linear-gradient","path","prop-types","pubnub","react","react-dom","react-hot-loader","react-native","react-native-gesture-handler","react-native-web","source-map","unimodules-permissions-interface"]},"shell":false}},"rootTag":31}
04-21 14:29:22.945 26089 26606 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:22.975 26089 26606 I chatty  : uid=10265(host.exp.exponent) logThread identical 2 lines
04-21 14:29:22.981 26089 26606 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:26.392 26089 26599 D Event   : No subscribers registered for event class host.exp.exponent.experience.g$c
04-21 14:29:26.393 26089 26599 D Event   : No subscribers registered for event class f.a.a.g

































------ at this point I hit "Crop" ------ 

04-21 14:29:38.381 26089 26089 W c       : Could not find listener for key: experienceActivityKernelDidLoad
04-21 14:29:38.387 26089 26089 W c       : Could not find listener for key: openOptimisticExperienceActivity
04-21 14:29:38.387 26089 26089 W c       : Could not find listener for key: openExperienceActivity
04-21 14:29:38.461 26089 26154 D OpenGLRenderer: endAllActiveAnimators on 0x70ce21cc00 (RippleDrawable) with handle 0x70db1a1da0
04-21 14:29:40.060 26089 26089 E e       : java.lang.RuntimeException: A TaskDescription's primary color should be opaque
04-21 14:29:40.082 26089 26817 D b       : Using cached or embedded response.
04-21 14:29:40.082 26089 26817 D b       : Got cached OkHttp response for https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fsnack%2F1.0.0%2Fef6915b1309493f18dc5fd7e65fba036-37.0.0-android.js
04-21 14:29:40.082 26089 26817 D b       : Have cached source file for https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fsnack%2F1.0.0%2Fef6915b1309493f18dc5fd7e65fba036-37.0.0-android.js
04-21 14:29:40.095 26089 26089 D SoLoader: init exiting
04-21 14:29:40.107 26089 26089 W c       : Could not find listener for key: readyForBundle
04-21 14:29:40.108 26089 26089 E e       : java.lang.RuntimeException: A TaskDescription's primary color should be opaque
04-21 14:29:40.113 26089 26089 E k       : java.lang.NoSuchMethodException
04-21 14:29:40.113 26089 26089 W System.err: java.lang.NoSuchMethodException
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.k.a(RNObject.java:33)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.k.a(RNObject.java:17)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.k.a(RNObject.java:12)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.l.a(ReactNativeActivity.java:37)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$d.onSuccess(ExperienceActivity.java:1)
04-21 14:29:40.113 26089 26089 W System.err: 	at g.a.a.b.a(Exponent.java:75)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity.l(ExperienceActivity.java:1)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.l.a(ReactNativeActivity.java:19)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$c.execute(ExperienceActivity.java:3)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.v.c.a(AsyncCondition.java:2)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity.b(ExperienceActivity.java:6)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$b.a(ExperienceActivity.java:1)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.d.b(AppLoader.java:17)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.d.d(AppLoader.java:2)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.d.a(AppLoader.java:1)
04-21 14:29:40.113 26089 26089 W System.err: 	at host.exp.exponent.d$e.onBundleLoaded(AppLoader.java:11)
04-21 14:29:40.113 26089 26089 W System.err: 	at g.a.a.b$b$a.run(Exponent.java:1)
04-21 14:29:40.113 26089 26089 W System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
04-21 14:29:40.113 26089 26089 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-21 14:29:40.113 26089 26089 W System.err: 	at android.os.Looper.loop(Looper.java:164)
04-21 14:29:40.113 26089 26089 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-21 14:29:40.113 26089 26089 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 14:29:40.113 26089 26089 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-21 14:29:40.113 26089 26089 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-21 14:29:40.122 26089 26089 D ReactNative: ReactInstanceManager.ctor()
04-21 14:29:40.122 26089 26089 D SoLoader: init exiting
04-21 14:29:40.130 26089 26089 D ReactNative: ReactInstanceManager.createReactContextInBackground()
04-21 14:29:40.130 26089 26089 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
04-21 14:29:40.130 26089 26089 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
04-21 14:29:40.130 26089 26089 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-21 14:29:40.130 26089 26089 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
04-21 14:29:40.131 26089 26818 D ReactNative: ReactInstanceManager.createReactContext()
04-21 14:29:40.151 26089 26818 D ReactNative: Initializing React Xplat Bridge.
04-21 14:29:40.156 26089 26818 D ReactNative: Initializing React Xplat Bridge before initializeBridge
04-21 14:29:40.165 26089 26818 D ReactNative: Initializing React Xplat Bridge after initializeBridge
04-21 14:29:40.165 26089 26818 D ReactNative: CatalystInstanceImpl.runJSBundle()
04-21 14:29:40.165 26089 26818 D CatalystInstanceImpl: Loading script from file
04-21 14:29:40.166 26089 26822 D ReactNative: ReactInstanceManager.setupReactContext()
04-21 14:29:40.166 26089 26822 D ReactNative: CatalystInstanceImpl.initialize()
04-21 14:29:40.167 26089 26822 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-21 14:29:40.203 26089 26822 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:40.205 26089 26822 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:40.494 26089 26821 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:40.505 26089 26821 I chatty  : uid=10265(host.exp.exponent) mqt_js identical 1 line
04-21 14:29:40.509 26089 26821 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:41.589 26089 26821 I ReactNativeJS: Running "main" with {"initialProps":{"exp":{"initialUri":"exp://expo.io/@snack/sdk.37.0.0-x_LtBQuZG","manifest":{"id":"@snack/sdk.37.0.0-x_LtBQuZG","primaryColor":"#000","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fsnack%2F1.0.0%2Fef6915b1309493f18dc5fd7e65fba036-37.0.0-android.js","revisionId":"1.0.0-r.Nzv0OAZlS","releaseChannel":"default","notification":{"iconUrl":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png","color":"#000000","icon":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png"},"locales":{},"releaseId":"99ec5f05-110e-4072-b13f-022ac6f9c9ee","slug":"snack","name":"Snack","icon":"https://s3.amazonaws.com/exp-brand-assets/SnackIcon_200.png","loadedFromCache":false,"splash":{"image":"./splash.png","imageUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/19cbaa9ed24b8c3c3fdd031eeb73c1af"},"description":"Write code in Expo's online editor and instantly use it on your phone","publishedTime":"2020-04-01T00:54:47.040Z","iconUrl":"https://s3.amazonaws.com/exp-brand-assets/SnackIcon_200.png","isVerified":true,"version":"1.0.0","owner":"exponent","packagerOpts":{"assetExts":["ttf","otf","mp4"]},"sdkVersion":"37.0.0","platforms":["android","ios","web"],"hostUri":"exp.host/@snack/sdk.37.0.0-x_LtBQuZG","commitTime":"2020-04-01T00:54:47.140Z","dependencies":["@babel/polyfill","@expo/vector-icons","@unimodules/core","@unimodules/react-native-adapter","babel-plugin-transform-decorators-legacy","babel-preset-expo","diff","escape-string-regexp","expo","expo-analytics-amplitude","expo-asset","expo-barcode-scanner","expo-camera","expo-constants","expo-file-system","expo-gl","expo-image-picker","expo-linear-gradient","path","prop-types","pubnub","react","react-dom","react-hot-loader","react-native","react-native-gesture-handler","react-native-web","source-map","unimodules-permissions-interface"]},"shell":false}},"rootTag":41}
04-21 14:29:41.591 26089 26832 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:41.605 26089 26832 I chatty  : uid=10265(host.exp.exponent) logThread identical 2 lines
04-21 14:29:41.611 26089 26832 D k       : WARNING: getPackageName called on ScopedContext
04-21 14:29:53.790 26089 26606 W com.amplitude.api.AmplitudeClient: mergeEventsAndIdentifys: number of events and identifys less than expected by 1
```

</details>

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

To fix https://github.com/expo/expo/issues/7946 we need to clean the Android code.

# How

- created separate async tasks for different result flow.
- unregistered from the activity lifecycle method.

# Test Plan

- NCL ✅
- test-suite ✅

### CODE REVIEW

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java [hunk 1]
```diff
@@ -322,440 +154,198 @@ private void launchCameraWithPermissionsGranted(Promise promise, Intent cameraIn
...
-          response.putBoolean("cancelled", true);
-          promise.resolve(response);
-          return;
-        }
-
-        handleCropperResult(intent, promise, exifData);
-      }
-      return;
+  public void startCropIntent(Uri uri, String type, int requestCode) throws IOException {
+    String extension = ".jpg";
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java:213]: Is type expected to be of format `image/(png|gif|jpg)`?

Could we verify it is of given format? And check against endsWith? I am afraid those checks are vulnerable to future errors.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java [hunk 2]
```diff
@@ -322,440 +154,198 @@ private void launchCameraWithPermissionsGranted(Promise promise, Intent cameraIn
...
-          Bundle response = new Bundle();
-          response.putBoolean("cancelled", true);
-          promise.resolve(response);
-          return;
-        }
-
-        handleCropperResult(intent, promise, exifData);
-      }
-      return;
+  public void startCropIntent(Uri uri, String type, int requestCode) throws IOException {
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java:212]: I'd love to have some comment here documenting arguments.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java [hunk 3]
```diff
@@ -322,440 +154,198 @@ private void launchCameraWithPermissionsGranted(Promise promise, Intent cameraIn
...
+    } else {
+      File file = new File(ImagePickerFileUtils.generateOutputPath(mContext.getCacheDir(), "ImagePicker", extension));
+      fileUri = Uri.fromFile(file);
     }
 
-    if (mPromise == null || (mCameraCaptureURI == null && requestCode == REQUEST_LAUNCH_CAMERA)
-        || (requestCode != REQUEST_LAUNCH_CAMERA && requestCode != REQUEST_LAUNCH_IMAGE_LIBRARY)) {
-      return;
+    CropImage.ActivityBuilder cropImage = CropImage.activity(uri);
+    if (mPickerOptions.getForceAspect() != null) {
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java:245]: `mPickerOptions` seems to be good candidate for method argument instead of field, ain't it?

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/PickerOptions.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+
+import org.unimodules.core.Promise;
+
+import java.util.ArrayList;
+import java.util.Map;
+
+import androidx.annotation.NonNull;
+import androidx.annotation.Nullable;
+
+public class PickerOptions {
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/PickerOptions.java:13]: How about kotlin `data class`?

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java [hunk 5]
```diff
@@ -31,221 +28,53 @@
...
-  static final int REQUEST_LAUNCH_CAMERA = 1;
-  static final int REQUEST_LAUNCH_IMAGE_LIBRARY = 2;
-  private static final int DEFAULT_QUALITY = 100;
-  final String OPTION_QUALITY = "quality";
-  final String OPTION_ALLOWS_EDITING = "allowsEditing";
-  final String OPTION_MEDIA_TYPES = "mediaTypes";
-  final String OPTION_ASPECT = "aspect";
-  final String OPTION_BASE64 = "base64";
-  final String OPTION_EXIF = "exif";
+public class ImagePickerModule extends ExportedModule implements ActivityEventListener {
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java:49]: I think your changes makes it easier to unit tests this module. Would you mind trying to write some basic native unit tests for it?

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.java [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+
+import java.io.ByteArrayOutputStream;
+import java.io.File;
+import java.io.FileOutputStream;
+import java.io.IOException;
+
+import androidx.annotation.NonNull;
+import androidx.annotation.Nullable;
+
+public class CompressionImageExporter implements ImageExporter {
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.java:18]: This class should also be easily testable, though I am not sure whether `android.graphics.Bitmap` manipulation won't make it painful.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.java [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+import java.io.FileOutputStream;
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.OutputStream;
+
+import androidx.annotation.NonNull;
+import expo.modules.imagepicker.ImagePickerConstance;
+import expo.modules.imagepicker.ImagePickerFileUtils;
+
+public class VideoResultTask extends ImagePickerResultTask {
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.java:21]: I see why you decided to go with inheritance here. It is good enough for me, but we might spend some time to try and refactor it if you wish.

**Review by mczernek — APPROVED** [review]
LGTM!

Those changes heads in very good direction! I would love you to test and showcase the benefits of your approach by adding some native tests.

That is not a must, however. We're good to go :)

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.java (hunk 7 above)
Comment (lukmccall) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.java:21]: So you want to change it to a composition? or you suggest a different approach here?

**Comment by lukmccall** [comment]
I will add unit tests in the different PR ;)

**Review by bbarthec — CHANGES_REQUESTED** [review]
Wow 👏 I like it sooo much! 💯 I almost detested the previous version of this module code as it was one 750-lines long file containing everything 🤮 and now it's super clear for me what's happening at every point of execution (even though I don't remember touching this modules at all 😉)
Very solid work! 🎉 💪 Keep it up! 😃 

And now some things to apply:
- Please, convert all new classes into kotlin files (just as @mczernek suggested in one place).
- Use `data classes` from `kotlin` if applicable 😉 
- Additionally, as you've already touched the whole `ImagePickerModule.java` file, would you mind converting it to `kotlin` as well? 😅
- Use this proposal of mine addressing these well-defined error messages 😉 

Regarding `kotlin` conversion I would accept doing it in separate PR, but it might be here as well (as it might introduce some new refactoring anyway).

File: apps/native-component-list/src/screens/ImagePickerScreen.tsx [hunk 8]
```diff
@@ -55,6 +63,48 @@ export default class ImagePickerScreen extends React.Component<object, State> {
...
       <ScrollView style={{ padding: 10 }}>
+        <View
+          style={{
+            flexDirection: 'row',
+            height: 30,
+            alignItems: 'center',
+            justifyContent: 'center',
+            marginVertical: 10,
+            paddingRight: 30,
+          }}>
```
[the remark this answers is not in the document]
Comment (barthap) [reply apps/native-component-list/src/screens/ImagePickerScreen.tsx:74]: @bbarthec I suppose you mean `StyleSheet.create` :wink:

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java [hunk 9]
```diff
@@ -271,19 +100,22 @@ public void getCameraPermissionsAsync(final Promise promise) {
...
+    mPickerOptions = PickerOptions.fromMap(options, promise);
+    if (mPickerOptions == null) {
       return;
     }
 
-    if (getExperienceActivity() == null) {
-      promise.reject(ERR_MISSING_ACTIVITY, MISSING_ACTIVITY_MESSAGE);
+    Activity activity = getExperienceActivity();
+    if (activity == null) {
+      promise.reject(ImagePickerConstance.ERR_MISSING_ACTIVITY, ImagePickerConstance.MISSING_ACTIVITY_MESSAGE);
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java:110]: I think it's a very good idea. I can add it ;) but in a different PR 😅

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java (hunk 1 above)
Comment (lukmccall) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java:213]: No, the format could be different. However, then we will try to convert it to a `jpg`. So, we can't check it using `endsWith`.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt [hunk 10]
```diff
@@ -0,0 +1,305 @@
...
+    WeakReference(activityProvider.currentActivity)
+  }
+  private val mImageLoader: ImageLoader by moduleRegistry()
+  private val mUIManager: UIManager by moduleRegistry()
+
+  override fun onCreate(moduleRegistry: ModuleRegistry) {
+    moduleRegistryPropertyDelegate.onCreate(moduleRegistry)
+  }
+
+  private fun getModuleRegistry() = moduleRegistryPropertyDelegate.moduleRegistry!!
```
Comment (bbarthec) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt:57]: I assume that this `propertyDelegation` couldn't help us with this one?
It would be wonderful if we could go with sth like this 😅 
```kotlin
private val mModuleRegistry: ModuleRegistry by moduleRegistry
```

**Review by bbarthec — APPROVED** [review]
I'm thrilled by the changes you've made 🎉 
Thanks to the work like **THIS ONE**, expo is truly heading toward the better world! 🥳

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImagePickerResultTask.kt [hunk 11]
```diff
@@ -0,0 +1,16 @@
...
+import android.net.Uri
+import android.os.AsyncTask
+import expo.modules.imagepicker.fileproviders.FileProvider
+import org.unimodules.core.Promise
+import java.io.File
+
+/**
+ * Base class for tasks which will process result of other activities like system camera or crop tool.
+ */
+abstract class ImagePickerResultTask(protected val promise: Promise,
```
Comment (mczernek) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImagePickerResultTask.kt:13]: Do we need this class? If it does not have any methods, what's the point? We have to repeat all constructor entries in every subclass anyway.

**Review by mczernek — APPROVED** [review]
It is great to have yet another module in Kotlin!

Please take my suggestions as advices, I am okay with discussing them and hopefully incorporating kotlin into `unimodules-core` after this PR gets merged.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt [hunk 12]
```diff
@@ -0,0 +1,305 @@
...
+  private var mPickerOptions: ImagePickerOptions? = null
+
+  private val mExperienceActivity: WeakReference<Activity> by moduleRegistry { activityProvider: ActivityProvider ->
+    WeakReference(activityProvider.currentActivity)
+  }
+  private val mImageLoader: ImageLoader by moduleRegistry()
+  private val mUIManager: UIManager by moduleRegistry()
+
+  override fun onCreate(moduleRegistry: ModuleRegistry) {
+    moduleRegistryPropertyDelegate.onCreate(moduleRegistry)
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt:55]: I will try to add this to `unimodules-core` but in a separate PR.
