### PR TITLE
[ios][camera] Fix initial rotation

### LINKED ISSUE #34592: [expo-camera] Orientation of camera preview wrong on iOS (iPad)
### Minimal reproducible example

https://github.com/chriscoomber/expo-52-expo-camera-repro/tree/0b77b20afb9487df37823300cd3bcd265804e4ca

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

I've done a reasonable effort to make a minimal reproduction. It seems to have something to do with **landscape mode on iPad** and **react-navigation** (v6).

From the minimal reproduction example I linked above, create a development build (or a standalone build) and get it running on an iPad. I'm using an iPad mini (6th generation) on iPadOS: 17.5.1

1. Hold the device in landscape (landscapeRight or landscapeLeft) - the app is locked to landscape too, but it's important that you're also holding it in landscape
2. Click the "Go to react-navigation" button and then "ScanQRScreen", which has the camera preview.
3. Observe that the camera preview is orientated incorrectly. I'm holding the camera at my lovely tapestry which is hung correctly, but the tapestry appears to be on its side.
    a. If it appears orientated correctly, try navigating out and back in.
4. Observe that if you manually tilt the device 90 degrees (either way) and then tilt it back to where you started, it has corrected itself - the camera preview is now aligned with the direction that the device is facing.

https://github.com/user-attachments/assets/95906efe-0476-4fe2-8fd2-01e31c9a3657

This seems to be related to https://github.com/expo/expo/issues/27218 but I'm at the latest version of expo-camera and I'm still seeing issues.

Note that the issue doesn't seem to occur outside of react-navigation - in my repro app there is a button to go to a camera preview screen which doesn't use react-navigation and I cannot reproduce the issue there. So it must have something to do with how @react-navigation/native-stack hosts its screens. I know that's a third party repro, but react-navigation doesn't violate anything in the docs for expo-camera, so it still feels like expo-camera's issue.

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.27 => 52.0.27 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.6 => 0.76.6 
    npmGlobalPackages:
      eas-cli: 14.3.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

(node:66853) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  expo@52.0.27 - expected version: ~52.0.28
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**I'm one patch version behind on expo, but that shouldn't affect anything - it doesn't include expo-camera. I don't want to kick off another eas build to prove that this isn't related.**
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #34592
When using the camera inside a screen from `react-native-screens`, the rotation is always set to portrait on the initial render. This is because we used an older API to determine the screen rotation which would always return `unknown` on the initial render and then default to portrait. Without screens it corrects itself but when screens locks the orientation, the camera never updates after the initial render and renders incorrectly until you manually rotate the device.

# How
Use `UIApplication.shared.connectedScenes` to correctly determine the device orientation.

# Test Plan
Tested in the provided repro and bare-expo.

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

File: packages/expo-camera/ios/Current/CameraView.swift [hunk 1]
```diff
@@ -134,7 +134,9 @@ public class CameraView: ExpoView, EXAppLifecycleListener,
   let onResponsiveOrientationChanged = EventDispatcher()
 
   private var deviceOrientation: UIInterfaceOrientation {
-    window?.windowScene?.interfaceOrientation ?? .unknown
+    UIApplication.shared.connectedScenes.compactMap { $0 as?
+      UIWindowScene
+    }.first?.interfaceOrientation ?? .unknown
```
Comment (lukmccall) [inline packages/expo-camera/ios/Current/CameraView.swift:139]:
```suggestion
    UIApplication.shared.connectedScenes.compactMap { 
      $0 as? UIWindowScene
    }.first?.interfaceOrientation ?? .unknown
```
