### PR TITLE
[image][Android] Fix the image components rendering incorrect assets when the Proguard is enabled

### LINKED ISSUE #22515: [expo-image] [android] Image components render wrong image
### Minimal reproducible example

https://gist.github.com/buraks/ed0e69c0267d1c92c9bdb0b61d4e21e7

### Summary

On iOS, the exact same code works perfectly fine. However, on Android, we are experiencing the problems of image components getting rendered incorrectly. The blurry image comes from the placeholder, which is 50x50 scaled up to the full space. We have noticed that the placeholders themselves get mixed up as well, not just the full-size image.

We suspect that the Image components get recycled incorrectly on Android.

We have tried updating the `expo-image` to the latest version: `1.2.2` and the issue remains.

https://github.com/expo/expo/assets/2693237/ec5b05b1-05b0-4084-8459-b233616617bd

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.9.0 - ~/.nodenv/versions/18.9.0/bin/node
      Yarn: 1.22.19 - ~/.nodenv/versions/18.9.0/bin/yarn
      npm: 8.19.1 - ~/.nodenv/versions/18.9.0/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
        System Images: android-32 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.12.1
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/22515.

# How

It turns out our proguard file is omitted and also not all rules are correct. I've managed to fix that, but invoking `consumerProguardFiles` function in `build.gradle` and checking all the rules manually. 

# Test Plan

- bare-expo ✅
- https://gist.github.com/buraks/ed0e69c0267d1c92c9bdb0b61d4e21e7 ✅

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

File: packages/expo-image/android/src/main/java/expo/modules/image/ThumbnailRequestCoordinatorExtension.kt [hunk 1]
```diff
@@ -1,18 +1,21 @@
 package expo.modules.image
 
+import android.util.Log
 import com.bumptech.glide.request.Request
 import com.bumptech.glide.request.ThumbnailRequestCoordinator
 
 fun ThumbnailRequestCoordinator.getPrivateFullRequest(): Request? {
-  return getPrivateRequest("full")
+  return getPrivateFiled("full")
```
Comment (buraks) [inline packages/expo-image/android/src/main/java/expo/modules/image/ThumbnailRequestCoordinatorExtension.kt:8]: is this a small typo or "filed" is intentional?

Comment (lukmccall) [reply packages/expo-image/android/src/main/java/expo/modules/image/ThumbnailRequestCoordinatorExtension.kt:8]: No, thanks for pointing that out. I'll fix that on the main ;)
