### PR TITLE
[expo-go] Fix reading `userInterfaceStyle` on Android if it's in root options

### LINKED ISSUE #13488: Root userInterfaceStyle does not apply on Android in Expo Go
### Summary

```
{
  "expo": {
    "userInterfaceStyle": "automatic",
  }
}
```

this will not change the user interface style behavior to allow for both light and dark themes, instead you need to set it on the Android key

```
{
  "expo": {
    "userInterfaceStyle": "automatic",
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}
```

The root key does work as expected on iOS

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.15.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 21.0.6113669
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/brentvatne/schemes

Run the project on Android and toggle between light/dark themes, notice the text doesn't update. Now add `"userInterfaceStyle": "automatic"` under the `"android"` key and reload the app (not just fast refresh, full reload) and notice it works as expected.

### PR DESCRIPTION
**Pull request by mrousavy**
# Why

```
{
  "expo": {
    "userInterfaceStyle": "dark",
    "android": {
      "userInterfaceStyle": "dark"
    }
  }
}
```

this chose `dark`

```
{
  "expo": {
    "userInterfaceStyle": "dark"
  }
}
```

this did not choose `dark`.

This PR attempts to fix this so that the root options (`expo`) are used as fallback.

# How

* Fixes #13488 

# Test Plan

1. Run expo-go with `android.userInterfaceStyle` set to `dark`
2. Remove `android.userInterfaceStyle` and only set root `userInterfaceStyle`
3. Do a full-reload
4. See that it's still dark.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by esamelson — CHANGES_REQUESTED** [review]
ignore me :)

**Review by esamelson — APPROVED** [review]
~ignore me too~

File: packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/raw/RawManifest.kt [hunk 1]
```diff
@@ -149,7 +149,7 @@ abstract class RawManifest(protected val json: JSONObject) {
   fun getAndroidUserInterfaceStyle(): String? {
     val expoClientConfig = getExpoClientConfigRootObject() ?: return null
     val android = expoClientConfig.optJSONObject("android") ?: return null
```
Comment (esamelson) [inline packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/raw/RawManifest.kt:151]: could we fall back to `expoClientConfig.optString("userInterfaceStyle")` here as well?

**Review by esamelson — CHANGES_REQUESTED** [review]
Sorry for the mess with all the review comments 🤪 This looks good, just one comment

**Review by brentvatne — APPROVED** [review]

File: packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/raw/RawManifest.kt (hunk 1 above)
Comment (mrousavy) [reply packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/raw/RawManifest.kt]: Right, Thanks! Pushed a new commit, this uses the same approach as in other similar functions (eg with `backgroundColor`)

**Review by esamelson — APPROVED** [review]
LGTM, for real this time 👌
