### PR TITLE
Fix expo form data missing value

### LINKED ISSUE #40059: ReferenceError when appending a File to FormData on native
### Minimal reproducible example

https://github.com/Hamusutaa/expo-blob-mre

### Steps to reproduce

Within the MRE, start the server with `npx expo start` and attach an iOS device.  Upload load, the code will attempt to attach a File to a FormData object, and the following error should be visible:

```
 LOG  error: ReferenceError: Property 'blob' doesn't exist
```

The error is [on this line](https://github.com/expo/expo/blob/main/packages/expo/src/winter/FormData.ts#L77) and appears to have been caused in #38160.  Because of the `@ts-expect-error` annotation on the previous line, the undefined variable `blob` error was not caught.

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 15.6.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.8.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.10 => 54.0.10 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
      react-native-web: ^0.21.0 => 0.21.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Closes https://github.com/expo/expo/issues/40059

# How

Only setting the property if it's writable, also fixed accessing blob that doesn't exist.

# Test Plan

Tested using the reproduction in bare-expo.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Review by jakex7 — APPROVED** [review]

File: packages/expo/src/winter/FormData.ts [hunk 1]
```diff
@@ -73,8 +73,15 @@ function normalizeArgs(
   blobFilename: string | undefined
 ): [string, File | string] {
   if (value instanceof Blob) {
```
Comment (barthap) [inline packages/expo/src/winter/FormData.ts:75]: Side note: this works for RN built-in `Blob`, but this condition resolves to `false` for `expo-blob` objects, which have the same issue (`blobFilename` is ignored for them)

**Review by barthap — APPROVED** [review]
