### PR TITLE
[UM][iOS] Fix bool variable representation

### LINKED ISSUE #4656: [sqlite] iOS fails to execute "create table" with "could not prepare..."
## 🐛 Bug Report

I'm trying to create a table in SQLite. 

The SQLite library fails to create a table using the sql statement `create table if not exists taskssss (id INTEGER primary key not null)` on iOS. 

It fails **only** on an iOS device (with the Expo client app). It works on Android (device and simulator) and iOS simulator (using Expo client).

I tried to debug `SQLIte.js` in:

```
function _deserializeResultSet(nativeResult) {
    let [errorMessage, insertId, rowsAffected, columns, rows] = nativeResult;
```

And the `nativeResult` variable is:

```
["could not prepare create table if not exists taskssss (id INTEGER primary key not null)"]
```

I also tried to find where that error is created:

```
$ grep -r "could not prepare" node_modules/*
node_modules/@expo/websql/lib/sqlite/SQLiteDatabase.js:  'could not prepare statement (23 not authorized)');
node_modules/expo-sqlite/ios/EXSQLite/EXSQLite.m:    error = [NSString stringWithFormat:@"could not prepare %@", sql];
node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.java:      super("could not prepare statement (23 not authorized)");
```

...and this to me looks like it's something in `EXSQLite.m`. Unfortunately, my knowledge of Objective-C fails short here.

### Environment

```
  Expo CLI 2.20.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.13 => 16.8.13 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.1
```

The iOS device I'm using is an iPhone 5 with iOS 10.3.3. But, I suspect it's a similar behaviour on my colleague's device (except I haven't had the opportunity to debug it directly).

### Steps to Reproduce

See the minimal demo below.

### Expected Behavior

Should create a table (like it does on Android and the iOS simulator)

### Actual Behavior

Fails to create a table on iOS (but only on actual devices, using Expo client).

### Reproducible Demo

This is the minimal (typescript) application that reproduces the bug:

```
import { SQLite } from "expo-sqlite";
import React from "react";
import { Text, View } from "react-native";

// --------------------------------------------------------

export interface Query {
  sql: string;
  args: unknown[];
}
export interface ResultSetError {
  error: Error;
}
export interface ResultSet {
  insertId?: number;
  rowsAffected: number;
  rows: Array<{
    [column: string]: any;
  }>;
}

declare type SQLiteCallback = (error?: Error | null, resultSet?: (ResultSet | ResultSetError)[]) => void;
interface WebSQLDatabase {
  exec(queries: Query[], readOnly: boolean, callback: SQLiteCallback): void;
}

// --------------------------------------------------------

class AppState {
  error?: Error | null;
  resultSet?: (ResultSet | ResultSetError)[];
}

class App extends React.Component<any, AppState> {
  constructor(props: any) {
    super(props);
    this.state = new AppState();
  }

  async componentDidMount() {
    const db = SQLite.openDatabase("dbdb.db") as WebSQLDatabase;
    db.exec([{ sql: "create table if not exists tasks_sss (id INTEGER)", args: [] }], false, (error?, resultSets?) => {
      this.setState({
        resultSet: resultSets,
        error: error
      });
    });
  }

  componentWillUnmount() {}

  render() {
    return (
      <View style={{ flex: 1, alignContent: "center", justifyContent: "center" }}>
        <Text style={{ alignSelf: "center" }}>
          err={JSON.stringify(this.state.error)}
          rs={JSON.stringify(this.state.resultSet)}
        </Text>
      </View>
    );
  }
}

export default App;

```

Note that the interfaces and types at the beginning are here only because not all parts of the SQLite API is properly exposed for Typescript (https://github.com/expo/expo/pull/4446). They can be removed when trying this with plain Javascript.

The result (on an iOS device):

IMG_0642

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #4656

# How

BOOL type in objective-c can be represented by `bool` or `signed char` (according to [objc.h](https://opensource.apple.com/source/objc4/objc4-706/runtime/objc.h.auto.html)). 
We only check if BOOL variables are represented as a `bool`.  

# Test Plan

Test-suits passed on iPhone 5 and 8 simulator.
Also, you can check https://snack.expo.io/@lukaszkosmaty/[sqlite]-ios-fails-to-execute-%22create-table%22 (in particular, it works on iPhone 5).

### CODE REVIEW

File: packages/@unimodules/core/ios/UMCore/UMExportedModule.m [hunk 1]
```diff
@@ -149,12 +149,22 @@ - (void)callExportedMethod:(NSString *)methodName withArguments:(NSArray *)argum
...
+#if OBJC_BOOL_IS_BOOL
     if ([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_BOOL) {
       // We need this intermediary variable, see
       // https://stackoverflow.com/questions/11061166/pointer-to-bool-in-objective-c
       BOOL value = [obj boolValue];
       [invocation setArgument:&value atIndex:(2 + idx)];
     }
+#else // BOOL is represented by `signed char`
+    if([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_CHR){
+      char value = [obj charValue];
```
Comment (ide) [inline packages/@unimodules/core/ios/UMCore/UMExportedModule.m]:
```suggestion
      BOOL value = [obj charValue];
```

**Review by ide — CHANGES_REQUESTED** [review]
Can you please provide a more robust test plan that shows the code working?

File: packages/@unimodules/core/ios/UMCore/UMExportedModule.m [hunk 2]
```diff
@@ -149,12 +149,22 @@ - (void)callExportedMethod:(NSString *)methodName withArguments:(NSArray *)argum
...
+    // getArgumentTypeAtIndex can return _C_BOOL (when `bool`) or _C_CHR (when `signed char`)
+#if OBJC_BOOL_IS_BOOL
     if ([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_BOOL) {
       // We need this intermediary variable, see
       // https://stackoverflow.com/questions/11061166/pointer-to-bool-in-objective-c
       BOOL value = [obj boolValue];
       [invocation setArgument:&value atIndex:(2 + idx)];
     }
+#else // BOOL is represented by `signed char`
+    if([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_CHR){
```
Comment (tsapeta) [inline packages/@unimodules/core/ios/UMCore/UMExportedModule.m]:
```suggestion
    if ([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_CHR) {
```

**Review by tsapeta — APPROVED** [review]
Looks good to me 👍

**Comment by lukmccall** [comment]
On older devices (with 32 bit iOS) BOOL type is represented by `signed char` so I tested SQL module on iPhone 5 (simulator and physical device)

**Comment by tsapeta** [comment]
@lukmccall Could you also add changelog entry for that? Maybe not specifically for SQLite as I can imagine there are some more issues that might have been solved by this.

**Comment by giautm** [comment]
Hi @tsapeta , Is it released in SDK-33 as a fix? I facing with this issues on production right now.

**Comment by ide** [comment]
This will go out with SDK 34.
