### PR TITLE
[android] Remove universal image loader dependency

### LINKED ISSUE #2657: ImagePicker quality option not working and storage alway increase 4Mb -> 7Mb (version 31.0.0, 30.0.0)
Hi there,

In version 31, I tried to use `ImagePicker` (`Android`) to let user capture the image. As I read the document, it have support an option called `quality`. This option value is from 0 to 1. I understand that 1 is maximum quality. But when I set the value from 0 to 1, I always received an image that had size from 4mb to 7mb. The size and quality of image did not reduce.

Is there anyone have the issue like me? Or I did it incorrectly?

BTW, I found another issue. When the user use camera to capture image (ImagePicker) the storage(app, cache) of the app alway increase 4Mb -> 7Mb

I have tried `FileSystem` to delete the file of the ImagePicker result. I can delete the file but the size of the storage alway increase

Snack url: https://snack.expo.io/ByI5m3mi7

*Storage before use ImagePicker*
Storage before use ImagePicker

*Storage after use ImagePicker and capture an image*
Storage after use ImagePicker and capture an image

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

With https://github.com/expo/expo/pull/2746 should fix https://github.com/expo/expo/issues/2657.

# How

It seems in `ImagePickerModule` and `ImageManipulatorModule` we're using a separate library to load images into the memory. This [Android Universal Image Loader](https://github.com/nostra13/Android-Universal-Image-Loader) keeps its own in-app cache, which makes installed app size blow up.

I've removed this loader in favor of using (already used throughout React Native) Fresco.

# Test Plan

The following scenarios seem to work properly on a Nokia with Android 8 and a Samsung Galaxy Tab with Android 7:

- [x] Pick a camera image
- [x] Pick a camera image with `quality`
- [x] Pick a camera image with `allowsEditing`
- [x] Pick a camera image with `allowsEditing` and `quality`
- [x] Pick a gallery image
- [x] Pick a gallery image with `quality`
- [x] Pick a gallery image with `allowsEditing`
- [x] Pick a gallery image with `allowsEditing` and `quality`
- [x] All the buttons in `ImageManipulator` screen in NCL work ok on both predefined image and on some MediaLibrary photo
- [x] Running the Snack provided in the issue showed a 300 KB increase in app size rather than 3 MB
- [x] [An image with EXIF rotation=8](https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_8.jpg) has correct width/height when picked with `ImagePicker`
- [x] Rotating [an image with EXIF rotation=8](https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_8.jpg) 90 degrees right with `ImageManipulator` acts as expected

### CODE REVIEW

File: android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ImageManipulatorModule.java [hunk 1]
```diff
@@ -42,32 +47,37 @@ public String getName() {
...
-                .considerExifParams(true)
-                .build());
-      } catch (Throwable e) {}
-    }
-    if (bmp == null) {
-      promise.reject(new IllegalStateException("Opening the image failed."));
-      return;
-    }
+  public void manipulate(final String uri, final ReadableArray actions, final ReadableMap saveOptions, final Promise promise) {
+    ImageRequest imageRequest = ImageRequest.fromUri(uri);
```
Comment (Szymon20000) [inline android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ImageManipulatorModule.java]: Probably we want to use `.setRotationOptions(RotationOptions.autoRotate())` option here.
[link](https://frescolib.org/docs/rotation.html)

File: android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ImagePickerModule.java [hunk 2]
```diff
@@ -290,50 +297,42 @@ public void run() {
...
-                          .considerExifParams(true)
-                          .imageScaleType(ImageScaleType.NONE)
-                          .build());
-                } catch (Throwable e) {}
-              }
-              if (bmp == null) {
-                promise.reject(new IllegalStateException("Image decoding failed."));
-                if (requestCode == REQUEST_LAUNCH_CAMERA) {
-                  revokeUriPermissionForCamera();
+              ImageRequest imageRequest = ImageRequest.fromUri(uri);
```
Comment (Szymon20000) [inline android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ImagePickerModule.java]: The same here.
[link](https://frescolib.org/docs/rotation.html)

**Review by Szymon20000 — APPROVED** [review]
