### PR TITLE
[cli] Update ngrok instance to use https

### LINKED ISSUE #26573: App Transport Security policy error on iOS with Expo dev client in tunnel mode
### Minimal reproducible example

https://github.com/tomrom-pomelo/expo-50-test

### Summary

After upgrading to SDK 50 and the latest expo-dev-client, we can no longer connect to our dev client with the `--tunnel` option set. 

To reproduce, first we can build a dev client for the simulator

```
eas build --profile development-simulator --platform ios
```

then install the app and run

```
npx expo start --tunnel
```

If we try to open it on the dev client, we get the error:

> Failed to load app from http://ehudf9i.tromano.8081.exp.direct with error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection

I am installing the app on a simulator running iOS 17.2. The dev client succeeds in connecting if I do not use the `--tunnel` mode. I provided a _very_ minimal reproducible example, essentially just using the bear `npx create-expo-app` result with a dev client profile set up.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.volta/tools/image/node/18.17.0/bin/node
      npm: 9.6.7 - ~/.volta/tools/image/npm/9.6.7/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 29, 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-29 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Closes https://github.com/expo/expo/issues/26573
Closes ENG-11158

# How

- Change ngrok URL format to separate values with dashes instead of dots. e.g. `${projectRandomValue}-${username}-${port}.exp.direct`. We need this because the TLS certificate uses wildcard and does not support multiple subdomain levels.
- Update UrlCreator to use https when tunneling  
-  Remove custom ATS configuration for exp.direct in the template
- Add protocol to ManifestRequestInfo

# Test Plan

run `yarn start --tunnel` in projects using expo go and dev-client and ensure the bundle is correctly loaded 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

File: packages/@expo/cli/src/start/server/UrlCreator.ts [hunk 1]
```diff
@@ -60,7 +60,10 @@ export class UrlCreator {
       return null;
     }
 
-    const manifestUrl = this.constructUrl({ ...options, scheme: 'http' });
+    const manifestUrl = this.constructUrl({
+      ...options,
+      scheme: this.defaults?.hostType === 'tunnel' ? 'https' : 'http',
```
Comment (EvanBacon) [inline packages/@expo/cli/src/start/server/UrlCreator.ts:65]: Likely want to toggle this to be https by default https://github.com/expo/expo/blob/b5d471d6d5b117a58ff129a3752e5bec2af08c7b/packages/%40expo/cli/src/start/server/UrlCreator.ts#L95 if all tunnel URLs should be https. Don't rely on defaults, use `options.hostType`

Comment (gabrieldonadel) [reply packages/@expo/cli/src/start/server/UrlCreator.ts:65]: The problem is that most of the time `options` is an empty object

**Comment by wodin** [comment]
There are some people here who say that `--tunnel` no longer works for them unless they change the URL to `http`:
#27027

**Comment by akravecas8** [comment]
Hi we are having the http/https --tunnl issue on Android as well.
