### PR TITLE
[video][android] Fix duration property resetting to 0 on video repeat

### LINKED ISSUE #34700: [expo-video]: On Android, the `duration` property is reset to 0 after the first video loop
### Minimal reproducible example

https://github.com/dr-crsa/EVAndroidDurationBug

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### How to reproduce:
Test a video that loops, with a `timeUpdate` listener, **on Android**.

**Example (can be tested in the linked repository as well):**
```
const videoPlayer = useVideoPlayer(
    "http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8",
    (player) => {
      player.muted = true;
      player.loop = true;
      player.timeUpdateEventInterval = 1;
      player.play();
    }
  );

  const { currentTime } = useEvent(videoPlayer, "timeUpdate", {
    currentTime: videoPlayer.currentTime,
    currentLiveTimestamp: null,
    currentOffsetFromLive: null,
    bufferedPosition: 0,
  });

  console.log("DURATION:", videoPlayer.duration, "CURRENT TIME:", currentTime);

  return (
    <View>
      <VideoView
        style={{ width: "100%", height: "100%" }}
        player={videoPlayer}
      />
    </View>
  );
```

### Expected behaviour:
On every loop, `videoPlayer.duration` should remain the same value.

### Current behaviour:
`videoPlayer.duration` becomes 0 after the first loop.

Image

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.30 => 52.0.30 
      expo-router: ~4.0.17 => 4.0.17 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.6 => 0.76.6 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 6.0.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by Wenszel**
# Why

Fixes [#34700](https://github.com/expo/expo/issues/34700)

# How
This situation occurs because on repeat the player remains in `STATE_READY`, and the duration is not refreshed after being set to 0 in onMediaTransition.  
Removed resetting the duration on `MEDIA_ITEM_TRANSITION_REASON_REPEAT` because the duration does not change on video repeat.

# Test Plan

Tested on bare-expo using the code from the issue.

### CODE REVIEW

File: packages/expo-video/android/src/main/java/expo/modules/video/player/VideoPlayer.kt [hunk 1]
```diff
@@ -383,6 +384,16 @@ class VideoPlayer(val context: Context, appContext: AppContext, source: VideoSou
     }
   }
 
+  private fun refreshPlaybackInfo() {
+    this@VideoPlayer.duration = this@VideoPlayer.player.duration / 1000f
+    this@VideoPlayer.isLive = this@VideoPlayer.player.isCurrentMediaItemLive
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/player/VideoPlayer.kt]:
```suggestion
		duration = player.duration / 1000f
    isLive = player.isCurrentMediaItemLive
```

File: packages/expo-video/android/src/main/java/expo/modules/video/player/VideoPlayer.kt [hunk 2]
```diff
@@ -383,6 +384,16 @@ class VideoPlayer(val context: Context, appContext: AppContext, source: VideoSou
...
+  }
+
+  private fun resetPlaybackInfo() {
+    this@VideoPlayer.duration = 0f
+    this@VideoPlayer.isLive = false
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/player/VideoPlayer.kt]:
```suggestion
    duration = 0f
    isLive = false
```

**Review by lukmccall — APPROVED** [review]

**Review by behenate — APPROVED** [review]
