### PR TITLE
[notifications] remove token listener on module destroy

### LINKED ISSUE #41040: [expo-notifications] IllegalArgumentException at expo.modules.kotlin.AppContext.eventEmitter
### Minimal reproducible example

The app crashes with `IllegalArgumentException: Cannot create an event emitter for the module that isn't present in the module registry` when Firebase Messaging attempts to dispatch a new token event before the Expo module registry is fully initialized. This occurs primarily on Android devices, especially during cold starts/first app launches.

### Stack Trace (from Sentry)
```
IllegalArgumentException: Cannot create an event emitter for the module that isn't present in the module registry.

at expo.modules.kotlin.AppContext.eventEmitter (AppContext.kt:228)
at expo.modules.kotlin.modules.Module.moduleEventEmitter_delegate$lambda$2 (Module.kt:30)
at expo.modules.kotlin.modules.Module.getModuleEventEmitter (Module.kt:30)
at expo.modules.kotlin.modules.Module.sendEvent (Module.kt:43)
at expo.modules.notifications.tokens.PushTokenModule.onNewToken (PushTokenModule.kt:23)
at expo.modules.notifications.service.delegates.FirebaseMessagingDelegate.onNewToken (FirebaseMessagingDelegate.kt:98)
at expo.modules.notifications.service.ExpoFirebaseMessagingService.onNewToken (ExpoFirebaseMessagingService.kt:13)
at com.google.firebase.messaging.FirebaseMessagingService.handleIntent (FirebaseMessagingService.java:170)
```

### Stack Trace (from Google Play Console)
```
Exception java.lang.IllegalArgumentException: Cannot create an event emitter for the module that isn't present in the module registry.

  at expo.modules.kotlin.AppContext.eventEmitter (AppContext.kt:237)
  at expo.modules.kotlin.modules.Module.moduleEventEmitter_delegate$lambda$2 (Module.kt:31)
  at expo.modules.kotlin.modules.Module.getModuleEventEmitter (Module.kt:31)
  at expo.modules.kotlin.modules.Module.sendEvent (Module.kt:44)
  at expo.modules.notifications.tokens.PushTokenModule.onNewToken (PushTokenModule.kt:23)
  at expo.modules.notifications.service.delegates.FirebaseMessagingDelegate.onNewToken (FirebaseMessagingDelegate.kt:98)
  at expo.modules.notifications.service.ExpoFirebaseMessagingService.onNewToken (ExpoFirebaseMessagingService.kt:13)
  at com.google.firebase.messaging.FirebaseMessagingService.handleIntent (FirebaseMessagingService.java:170)
```

### 1. Upgraded Expo SDK and Packages
- Upgraded to Expo SDK 54
- Upgraded `expo-notifications` to latest version (0.32.12.)
- **Result:** Issue persisted

### 2. JavaScript-Level Workarounds
Attempted to prevent registration on first launch:

```javascript
// NotificationService.js - ATTEMPTED (didn't work)
const hasLaunchedBefore = await AsyncStorage.getItem('hasLaunchedBefore');
if (!hasLaunchedBefore) {
  // Skip registration on first launch
  await AsyncStorage.setItem('hasLaunchedBefore', 'true');
  return null;
}
```

**Result:** Didn't prevent the crash because Firebase can trigger `onNewToken()` independently of our JS code, especially during cold starts.

### 3. Global Error Handler
Attempted to catch and suppress the error:

```javascript
// App.js - ATTEMPTED (didn't work)
if (Platform.OS === 'android') {
  global.ErrorUtils?.setGlobalHandler?.((error, isFatal) => {
    if (error?.message?.includes('Cannot create an event emitter')) {
      console.warn('Caught module registry error');
      return; // Prevent crash
    }
    // Handle other errors normally
  });
}
```

**Result:** The error occurs in native code before it reaches JavaScript, so this approach doesn't work.

### 4. Patch-Package Workaround
Created a patch to check if React context is available before sending events:

```kotlin
// Patch: expo-notifications+0.32.12.patch
override fun onNewToken(token: String) {
    // Check if React context is available
    if (appContext.reactContextHolder.reactContext == null) {
        Log.w(TAG, "React Context is NULL. Skipping onNewToken dispatch to prevent crash.")
        return // Exit early, preventing the crash
    }
    
    // Original logic proceeds ONLY if the context is ready
    sendEvent(NEW_TOKEN_EVENT_NAME, mapOf("token" to token))
}
```

**Result:** This patch didnt prevents the crash.

## Related Issues

This issue has been reported by other developers in the community:

- [Reddit: Fatal Exception in Expo Android Build - Cannot create an event emitter](https://www.reddit.com/r/reactnative/comments/1ox7i56/fatal_exception_in_expo_android_build_cannot/)
- [Reddit: Expo Notification Crash on Android Devices](https://www.reddit.com/r/reactnative/comments/1of89xi/expo_notification_crash_on_android_devices/)

## Screenshots

Image

Image

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: Windows 11 10.0.26100
    Binaries:
      Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12700392
    npmPackages:
      expo: ^54.0.23 => 54.0.23
      expo-updates: ~29.0.12 => 29.0.12
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
      react-native-web: ^0.21.0 => 0.21.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by vonovak**
# Why

This PR attempts to fix invalid push token event emissions by calling `removeTokenListener` in `OnDestroy`.

Originally opened to try fix #41040, it doesn't seem to help, but I'd still like to get it in.

# How

- Changed the token listeners collection from a `WeakHashMap<FirebaseTokenListener, WeakReference<FirebaseTokenListener?>?>` to a `HashSet<FirebaseTokenListener>` which was somewhat odd
- Implemented `OnDestroy` in the `PushTokenModule` to properly unregister the token listener when the module is destroyed

# Test Plan

tested locally

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by vonovak** [comment]
* **#41275** <a href="https://app.graphite.com/github/pr/expo/expo/41275?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/41275?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/FirebaseMessagingDelegate.kt [hunk 1]
```diff
@@ -47,16 +47,22 @@ open class FirebaseMessagingDelegate(protected val context: Context) : FirebaseM
     @JvmStatic
     fun addTokenListener(listener: FirebaseTokenListener) {
```
Comment (lukmccall) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/FirebaseMessagingDelegate.kt]:
```suggestion
    fun addTokenListener(listener: FirebaseTokenListener) = synchronized(sTokenListenersReferences) {
```

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/FirebaseMessagingDelegate.kt [hunk 2]
```diff
@@ -47,16 +47,22 @@ open class FirebaseMessagingDelegate(protected val context: Context) : FirebaseM
...
+        sTokenListenersReferences.add(listener)
         // Since it's a new listener and we know of a last valid token, let's let them know.
         sLastToken?.let {
           listener.onNewToken(it)
         }
       }
     }
 
+    @JvmStatic
+    fun removeTokenListener(listener: FirebaseTokenListener) {
```
Comment (lukmccall) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/FirebaseMessagingDelegate.kt]:
```suggestion
    fun removeTokenListener(listener: FirebaseTokenListener) = synchronized(sTokenListenersReferences) {
```

**Review by lukmccall — APPROVED** [review]
