### PR TITLE
fix(expo/fetch): Align w/ method normalization, `Request`-like input, and `URL` input

### LINKED ISSUE #43192: `expo/fetch` errors with `400` error when using lowercase method names
### Minimal reproducible example

https://github.com/gmaclennan/expo-fetch-test/blob/main/App.js

### Steps to reproduce

Use `fetch` from `expo/fetch` and pass a lowercase method name (e.g. `get`) to the `init.method` option. It will return a response with status 400 on Android, which seems to come from the okhttp library. The `globalThis.fetch` in React Native works fine with lowercase method names, and the [fetch spec says they should be normalized to uppercase](https://fetch.spec.whatwg.org/#methods). The error gives no indication that the method name casing is the issue, and I'm not sure where the 400 response is coming from.

### Environment

```text
Running expo-env-info@2.0.8

  expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 26.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.4 - ~/.local/state/fnm_multishells/35993_1771280307090/bin/node
      Yarn: 3.8.7 - ~/.local/state/fnm_multishells/35993_1771280307090/bin/yarn
      npm: 10.8.2 - ~/.local/state/fnm_multishells/35993_1771280307090/bin/npm
      Watchman: 2026.01.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /var/folders/0x/w55m5zvx1lv6lhc_96k0wb440000gn/T/frum_36077_1771280307385/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 33, 34, 35, 36
        Build Tools: 30.0.2, 33.0.1, 33.0.2, 34.0.0, 35.0.0, 36.0.0
        System Images: android-29 | ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 26.2/17C52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.33 => 54.0.33
      react: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
    npmGlobalPackages:
      eas-cli: 16.26.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Running expo-doctor@1.17.14
17/17 checks passed. No issues detected!
```

### LINKED ISSUE #43193: `expo/fetch` does not accept a URL as input
### Minimal reproducible example

https://github.com/gmaclennan/expo-fetch-test/blob/main/App.js

### Steps to reproduce

```
import { fetch } from 'expo/fetch'

fetch(new URL('http://www.example.com/'))
```

This throws an error `fetch failed: [start] Cannot convert 'http://www.example.com/' to a Kotlin type.`

I know this isn't a full implementation of the `fetch` spec, but thought it's worth having an issue to track this, especially as the types currently allow a URL, and the error is non-intuitive.

### Environment

```text
Running expo-env-info@2.0.8

  expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 26.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.4 - ~/.local/state/fnm_multishells/35993_1771280307090/bin/node
      Yarn: 3.8.7 - ~/.local/state/fnm_multishells/35993_1771280307090/bin/yarn
      npm: 10.8.2 - ~/.local/state/fnm_multishells/35993_1771280307090/bin/npm
      Watchman: 2026.01.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /var/folders/0x/w55m5zvx1lv6lhc_96k0wb440000gn/T/frum_36077_1771280307385/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 33, 34, 35, 36
        Build Tools: 30.0.2, 33.0.1, 33.0.2, 34.0.0, 35.0.0, 36.0.0
        System Images: android-29 | ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 26.2/17C52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.33 => 54.0.33
      react: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
    npmGlobalPackages:
      eas-cli: 16.26.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Running expo-doctor@1.17.14
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by kitten**
# Why

Resolves #43193 
Resolves #43192

This fixes a few discrepancies in the `expo/fetch` implementation that were reported in the linked issues and further that I noticed when double-checking the against [`fetch-nodeshim`](https://github.com/kitten/fetch-nodeshim) (which I previously checked against the Fetch standard)

# How

- `method` needs to be normalised to uppercase (this isn't obvious in the standard; commit links to section)
- input needs to accept `URL` and stringify it
- input needs to accept `Request` and replace `init` with it
  - **NOTE:** Typically, only one argument is used in that case, but it's more convenient to express it as a "replacement." I've added a custom `FetchRequestLike` type to mirror `RequestInit`
- `body` and `signal` need to accept `null` as valid input values in `FetchRequestInit`

# Test Plan

- Unclear how we typically test this, but could manually verify this; changes are pretty straightforward though
- For type compatibility, `fetch(new URL('...'))` and `fetch(new Request('...'))` shouldn't raise type errors

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo/src/winter/fetch/fetch.ts [hunk 1]
```diff
@@ -3,39 +3,55 @@ import { FetchError } from './FetchErrors';
 import { FetchResponse, type AbortSubscriptionCleanupFunction } from './FetchResponse';
 import { NativeRequest, NativeRequestInit } from './NativeRequest';
 import { normalizeBodyInitAsync, normalizeHeadersInit, overrideHeaders } from './RequestUtils';
-import type { FetchRequestInit } from './fetch.types';
+import type { FetchRequestInit, FetchRequestLike } from './fetch.types';
+
+/** Returns if `input` is a Request object */
+const isRequest = (input: any): input is Request =>
+  input != null && typeof input === 'object' && 'body' in input;
```
Comment (Kudo) [inline packages/expo/src/winter/fetch/fetch.ts:15]: [🏗️ **design**] This check is too loose — any object with a `body` property will match (e.g., a plain `{ body: 'data', url: '...' }` config object). The Fetch spec identifies `Request` by the presence of `url`, `method`, and `body` together. A more robust check:

```ts
const isRequest = (input: any): input is FetchRequestLike =>
  input != null && typeof input === 'object' && 'url' in input && 'method' in input && 'body' in input;
```

Also note the type predicate says `input is Request` (the global `Request`), but `FetchRequestLike` is the type that actually represents what the function accepts. Consider using `input is FetchRequestLike` instead.

File: packages/expo/src/winter/fetch/fetch.ts [hunk 2]
```diff
@@ -3,39 +3,55 @@ import { FetchError } from './FetchErrors';
...
 
 // TODO(@kitten): Do we really want to use our own types for web standards?
-export async function fetch(url: string, init?: FetchRequestInit): Promise<FetchResponse> {
+export async function fetch(
+  input: string | URL | FetchRequestLike,
+  init?: FetchRequestInit
+): Promise<FetchResponse> {
+  const initFromRequest = isRequest(input);
```
Comment (Kudo) [inline packages/expo/src/winter/fetch/fetch.ts:22]: [🚨 **critical**] Per the [Fetch spec §5.6](https://fetch.spec.whatwg.org/#dom-global-fetch), when both a `Request` input and an `init` dict are provided, the `init` values should take precedence over the Request properties. Currently, `init` is completely ignored when `initFromRequest` is true.

For example, `fetch(request, { method: 'POST' })` would use the request's method instead of `'POST'`.

Consider merging them with `init` taking priority:
```ts
const method = init?.method ?? (initFromRequest ? input.method : undefined);
const body = init?.body !== undefined ? init.body : (initFromRequest ? input.body : null);
// ...etc for signal, redirect, credentials, headers
```

File: packages/expo/src/winter/fetch/fetch.ts [hunk 3]
```diff
@@ -3,39 +3,55 @@ import { FetchError } from './FetchErrors';
...
+  const url = initFromRequest ? input.url : input;
+  const body = initFromRequest ? input.body : init?.body || null;
```
Comment (Kudo) [inline packages/expo/src/winter/fetch/fetch.ts]: [💡 suggestion] `init?.body || null` uses `||` which coerces falsy values. While `body: ''` is unlikely in practice, `??` is semantically correct here and consistent with how `signal` should be handled:
```ts
const body = initFromRequest ? input.body : init?.body ?? null;
```

File: packages/expo/src/winter/fetch/fetch.ts [hunk 4]
```diff
@@ -3,39 +3,55 @@ import { FetchError } from './FetchErrors';
...
+  const signal = initFromRequest ? input.signal : init?.signal || undefined;
+  const redirect = initFromRequest ? input.redirect : init?.redirect;
+  const method = initFromRequest ? input.method : init?.method;
+  const credentials = initFromRequest ? input.credentials : init?.credentials;
+
+  let headers = normalizeHeadersInit(initFromRequest ? input.headers : init?.headers);
```
Comment (Kudo) [inline packages/expo/src/winter/fetch/fetch.ts]: [🏗️ **design**] The code accesses `input.headers` here, but `FetchRequestLike` doesn't declare a `headers` property. This works at runtime (because the type guard says `input is Request` — the global type which has `headers`), but it creates an inconsistency between the type the function signature advertises (`FetchRequestLike`) and what it actually requires.

Either add `readonly headers?: HeadersInit` to `FetchRequestLike`, or extract headers differently.

File: packages/expo/src/winter/fetch/fetch.types.ts [hunk 5]
```diff
@@ -16,3 +16,17 @@ export interface FetchRequestInit {
   referrer?: string;
   window?: any;
 }
+
+/**
+ * A fetch Request compatible structure.
+ */
+export interface FetchRequestLike {
```
Comment (Kudo) [inline packages/expo/src/winter/fetch/fetch.types.ts:23]: [🏗️ **design**] This interface is missing `headers` — but the fetch implementation accesses `input.headers` when the input is detected as Request-like. Add:
```ts
readonly headers?: HeadersInit;
```
to keep the type and the runtime behavior aligned.

File: packages/expo/src/winter/fetch/fetch.ts [hunk 6]
```diff
@@ -3,39 +3,55 @@ import { FetchError } from './FetchErrors';
...
     headers = overrideHeaders(headers, overriddenHeaders);
   }
 
   const nativeRequestInit: NativeRequestInit = {
-    credentials: init?.credentials ?? 'include',
+    credentials: credentials ?? 'include',
     headers,
-    method: init?.method ?? 'GET',
-    redirect: init?.redirect ?? 'follow',
+    method: method?.toUpperCase() ?? 'GET',
```
Comment (Kudo) [inline packages/expo/src/winter/fetch/fetch.ts]: [🐧 nit] Strictly speaking, the Fetch spec only normalizes a specific set of methods to uppercase (DELETE, GET, HEAD, OPTIONS, POST, PUT). Custom or non-standard methods should be passed as-is. This is a minor point since most servers are case-insensitive, but worth noting for spec conformance.

See [Fetch spec §5.1 normalize method](https://fetch.spec.whatwg.org/#concept-method-normalize).

**Review by Kudo — CHANGES_REQUESTED** [review]

File: packages/expo/src/winter/fetch/fetch.ts (hunk 2 above)
Comment (kitten) [reply packages/expo/src/winter/fetch/fetch.ts:22]: That seems correct. The reason I didn't catch this is that I accounted for `fetch(new Request(...))` but not for `fetch(new Request(...), init)`. The linked section is wrong and instead 5.6 redirects to `Request`: https://fetch.spec.whatwg.org/#request-class

That section doesn't explicitly state what happens when `fetch(new Request(...))` is passed and only points out a few properties, but I've tested it in Firefox and it seems that in practice, they're indeed combined, and `init` takes precedence in this case.

File: packages/expo/src/winter/fetch/fetch.ts (hunk 1 above)
Comment (kitten) [reply packages/expo/src/winter/fetch/fetch.ts:15]: This is intentional and on purpose. `input is FetchRequestList` isn't and fixed. `'body' in x` is a sufficient check given we don't quite know what `Request` will look like without the presence of a global. We could check for our object here, but it's unlikely we want `instanceof`. We could check for all properties here, but in practice, we mostly care about `body` which is the differentiating property. The types further constrain this either way

File: packages/expo/src/winter/fetch/fetch.ts (hunk 4 above)
Comment (kitten) [reply packages/expo/src/winter/fetch/fetch.ts]: typo, due to `is Request`

**Comment by kitten** [comment]
For clarity, the discrepancy that was left over was `fetch(new Request(...), init)`, where `init`'s properties take precedence, and the method normalisation. The corresponding PR for `fetch-nodeshim` is: https://github.com/kitten/fetch-nodeshim/pull/37

**Review by Kudo — APPROVED** [review]
thanks for the pr update and the fix
