### PR TITLE
[expo-camera] Save metadata

### LINKED ISSUE #6399: [expo-camera] Does not save the Exif data
### Environment

```
Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.9.1
```

**app target is iOS and Android**

### Steps to Reproduce

take a photo using expo Camera: 
```js
takePicture() {
        const options = {
            quality: 1,
            base64: false,
            exif: true,
            skipProcessing: false,
            onPictureSaved: this.saveImage.bind(this),
        };
        this.camera.takePictureAsync(options).then().catch(
            error => this.props.setError(error.toString())
        )
    }
```
Use the `onPictureSaved` callback to save the photo to the camera roll:
```js
saveImage(photo) {
        if (this.props.save === false) {
            // Switch component sets true/false flag
            // true => Save to camera roll
            // false => Save to collection
            let filename = photo.uri.substring(photo.uri.lastIndexOf('/') + 1);
            let image = {
                [filename]: {
                    uri: photo.uri,
                    width: photo.width,
                    height: photo.height,
                    filename: filename,
                }
            };
            this.props.addMedia(image);
            this.props.navigation.navigate('MediaPicker');
        } else {
            console.log(photo);
            this.saveToCameraRoll(photo.uri);
        }
    }
```
**The photo taken with the camera's phone contains the following metadata:**
```json
Object {
  "exif": Object {
    "ApertureValue": 2.52,
    "ColorSpace": 1,
    "ComponentsConfiguration": "???",
    "Compression": 6,
    "DateTime": "2019:11:28 14:08:55",
    "DateTimeDigitized": "2019:11:28 14:08:55",
    "DateTimeOriginal": "2019:11:28 14:08:55",
    "ExifVersion": "0220",
    "ExposureTime": 0.05,
    "FNumber": 2.4,
    "Flash": 0,
    "FlashpixVersion": "0100",
    "FocalLength": 3.97,
    "ISOSpeedRatings": 1377,
    "ImageLength": 3200,
    "ImageWidth": 2400,
    "InteroperabilityIndex": "R98",
    "JPEGInterchangeFormat": 646,
    "JPEGInterchangeFormatLength": 24615,
    "LightSource": 0,
    "Make": "LGE",
    "Model": "Nexus 5",
    "Orientation": 0,
    "PixelXDimension": 2400,
    "PixelYDimension": 3200,
    "ResolutionUnit": 2,
    "ShutterSpeedValue": 4.33,
    "SubSecTime": "483367",
    "SubSecTimeDigitized": "483367",
    "SubSecTimeOriginal": "483367",
    "WhiteBalance": 0,
    "XResolution": 72,
    "YCbCrPositioning": 1,
    "YResolution": 72,
  },
  "height": 3200,
  "uri": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540hayate%252Fbivio-mob/Camera/84212baf-8280-4cc8-9da8-49977855a5d1.jpg",
  "width": 2400,
}
```
**The following method is used to save the photo**
```js
saveToCameraRoll(uri) {
        MediaLibrary.getPermissionsAsync().then(permission => {
            if (permission.granted) {
                MediaLibrary.createAssetAsync(uri).then(asset => {
                    // do nothing with asset
                    // console.log(asset);
                    MediaLibrary.getAssetInfoAsync(asset.id).then(info => {
                        console.log(info);
                    })

                }).catch(error => {
                    this.props.setError(error.toString());
                });
            }
        });
    }
```
**When retrieving the info from the saved asset using MediaLibrary.getAssetInfoAsync is missing the majority of the Exif content**
```json
Object {
  "albumId": "-2075821635",
  "creationTime": 1574917737000,
  "duration": 0,
  "exif": Object {
    "ImageLength": 3200,
    "ImageWidth": 2400,
    "LightSource": 0,
    "Orientation": 0,
  },
  "filename": "84212baf-8280-4cc8-9da8-49977855a5d1.jpg",
  "height": 3200,
  "id": "15332",
  "localUri": "file:///storage/emulated/0/DCIM/84212baf-8280-4cc8-9da8-49977855a5d1.jpg",
  "location": null,
  "mediaType": "photo",
  "modificationTime": 1574917737000,
  "uri": "file:///storage/emulated/0/DCIM/84212baf-8280-4cc8-9da8-49977855a5d1.jpg",
  "width": 2400,
}
```
The same is happening on both iPhone Xs and Android Nexus 5. 
The Exif data is actually not present on the saved file as I cannot read it even when opening the photo with a photo editor tool such as Lightroom. 

### Expected Behavior
I would expect that `MediaLibrary.createAssetAsync` saves the Exif data contained in the original file into the newly created asset.

### Actual Behavior
Exif data is not saved.

### Reproducible Demo

# To reproduce the issue please copy the whole code below over the App.js file generated by `expo init`

```js
import React from 'react';
import { StyleSheet, SafeAreaView, Button } from 'react-native';
import * as Permissions from 'expo-permissions';
import * as MediaLibrary from 'expo-media-library';
import { Camera } from 'expo-camera';


export default class App extends React.Component {
    constructor(props) {
        super(props);

        this.camera = null;

        this.state = {
            permissions: false,
            ready: false,
        }
    }

    componentDidMount() {
        Permissions.askAsync(Permissions.CAMERA, Permissions.CAMERA_ROLL).then(permission => {
            if (permission.status === 'granted') {
                this.setState({permissions: true});
            } else {
                alert('Permission is required to take photos and access media library.');
            }
        });
    }

    onCameraReady() {
        if (this.state.permissions && this.camera) {
            this.setState({ready: true});
        }
    }

    onTakePhoto() {
        const options = {
            quality: 1,
            base64: false,
            exif: true,
            skipProcessing: false,
            onPictureSaved: this.saveImage.bind(this),
        };
        this.camera.takePictureAsync(options).then().catch(
            error => alert(error)
        )
    }

    saveImage(photo) {
        // photo contains all the Exif data, for example:

        // "ApertureValue": 1.6959938131099002,
        // "BrightnessValue": -0.5381590558481736,
        // "ColorSpace": 65535,
        // "DateTimeDigitized": "2019:11:28 15:36:46",
        // "DateTimeOriginal": "2019:11:28 15:36:46",
        // "ExifVersion": "0231",
        // "ExposureBiasValue": 0,
        // "ExposureMode": 0,
        // "ExposureProgram": 2,
        // "ExposureTime": 0.02,
        // "FNumber": 1.8,
        // "Flash": 16,
        // "FocalLenIn35mmFilm": 27,
        // "FocalLength": 4.25,
        // "ISOSpeedRatings": Array [
        //       1000,
        //     ],
        //
        // ...and more...

        console.log(photo);

        MediaLibrary.createAssetAsync(photo.uri).then(asset => {
            // The return of createAssetAsync does not contain Exif data, this is expected
            // however the saved file should contain the original Exif data, but it does not
            console.log(asset);

            MediaLibrary.getAssetInfoAsync(asset.id).then(info => {
                // here Exif field is present but only with very few attributes,
                // I think it is added by getAssetInfoAsync method and is not actually in the file
                // all of the original Exif is lost
                console.log(info);
            });

        }).catch(error => {
            alert(error);
        });
    }

    render() {
        return (
            <SafeAreaView style={styles.container}>
                <Camera style={styles.camera}
                        ref={cam => {
                            this.camera = cam
                        }}
                        type={Camera.Constants.Type.back}
                        flashMode={'off'}
                        onCameraReady={() => this.onCameraReady()}
                />
                <Button disabled={!this.state.ready} title={'take photo'} onPress={() => this.onTakePhoto()} />
            </SafeAreaView>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    camera: {
        flex: 1,
   }
});
```

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolves https://github.com/expo/expo/issues/6399.

# How

UIImage strips metadata (https://stackoverflow.com/a/25595495). So I've added it manually using `Image IO API`. Moreover, I've also deleted `updateImageSampleMetadata` function - it was unuse.

Android bitmap also strips metadata.
# TODO

- [x] iOS
- [x] Android

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/github---camera---fix-metadata ✅(returns correct metadata)
- NCL ✅

### CODE REVIEW

File: packages/expo-camera/ios/EXCamera/EXCamera.m [hunk 1]
```diff
@@ -413,60 +413,58 @@ - (void)captureOutput:(AVCapturePhotoOutput *)output didFinishProcessingPhoto:(A
...
 
   NSMutableDictionary *response = [[NSMutableDictionary alloc] init];
-  response[@"uri"] = [EXCameraUtils writeImage:takenImageData toPath:path];
-  response[@"width"] = @(takenImage.size.width);
-  response[@"height"] = @(takenImage.size.height);
-
-  if ([options[@"base64"] boolValue]) {
-    response[@"base64"] = [takenImageData base64EncodedStringWithOptions:0];
+  if ([options[@"exif"] boolValue]) {
+    NSMutableDictionary *updatedExif = [EXCameraUtils updateExifMetadata:exifMetadata withAdditionalData:@{ @"Orientation": @([EXCameraUtils exportImageOrientation:takenImage.imageOrientation]) }]; // TODO
```
Comment (bbarthec) [inline packages/expo-camera/ios/EXCamera/EXCamera.m]: `// TODO` 🤔

File: packages/expo-camera/ios/EXCamera/EXCamera.m [hunk 2]
```diff
@@ -413,60 +413,58 @@ - (void)captureOutput:(AVCapturePhotoOutput *)output didFinishProcessingPhoto:(A
...
+    updatedExif[(NSString *)kCGImagePropertyExifPixelYDimension] = @(width);
+    updatedExif[(NSString *)kCGImagePropertyExifPixelXDimension] = @(height);
+    response[@"exif"] = updatedExif;
+    
+    // UIImage does not contain metadata information. We need to add them to CGImage manually.
+    processedImageData = [EXCameraUtils writeImageToData:takenImage withExifData:updatedExif imageQuality:quality];
```
Comment (bbarthec) [inline packages/expo-camera/ios/EXCamera/EXCamera.m]:
```suggestion
    processedImageData = [EXCameraUtils dataFromImage:takenImage withExifData:updatedExif imageQuality:quality];
```
Method name suggests other process IMO (taking image and writing it to some data container).

File: packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m [hunk 3]
```diff
@@ -121,19 +135,41 @@ + (NSString *)writeImage:(NSData *)image toPath:(NSString *)path
   return [fileURL absoluteString];
 }
 
-+ (void)updateImageSampleMetadata:(CMSampleBufferRef)imageSampleBuffer withAdditionalData:(NSDictionary *)additionalData inResponse:(NSMutableDictionary *)response
++ (NSData *)writeImageToData:(UIImage *)image withExifData:(NSDictionary *)exif imageQuality:(float)quality
```
Comment (bbarthec) [inline packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m]: Change this name to express accurately what this method is actually doing, please see my suggestion in other comment.

File: packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m [hunk 4]
```diff
@@ -121,19 +135,41 @@ + (NSString *)writeImage:(NSData *)image toPath:(NSString *)path
...
+  // Set compression quality
+  [updatedMetadata setObject:@(quality) forKey:(__bridge NSString *)kCGImageDestinationLossyCompressionQuality];
+
+  // Create an image destination
+  NSMutableData *processedImageData = [NSMutableData data];
+  CGImageDestinationRef destinationCGImageRef = CGImageDestinationCreateWithData((__bridge CFMutableDataRef)processedImageData, CGImageSourceGetType(sourceCGIImageRef), 1, NULL);
+
+  // Add image to the destination
+  // Note: it'll save only these value which are under the kCGImagePropertyExif* key.
+  CGImageDestinationAddImage(destinationCGImageRef, image.CGImage, (__bridge CFDictionaryRef) updatedMetadata);
```
Comment (bbarthec) [inline packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m]: ANd what about `kCGImagePropertyGPSDictionary`?

**Review by bbarthec — CHANGES_REQUESTED** [review]
LGTM 👌 Just a little method renaming and confusion about `kCGImagePropertyGPSDictionary` 😉

File: packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m (hunk 4 above)
Comment (bbarthec) [reply packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m]: @lukmccall, well you've resolved this thread, but I still don't know what about `kCGImagePropertyGPSDictionary`?

Comment (lukmccall) [reply packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m]: `kCGImagePropertyGPSDictionary` will be saved too. I've changed logic a little bit. Now we save into image file every piece of information which are under kCGImageProperty* key.

**Review by bbarthec — APPROVED** [review]

File: packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/ResolveTakenPictureAsyncTask.java [hunk 5]
```diff
@@ -5,7 +5,9 @@
 import android.graphics.BitmapFactory;
 import android.graphics.Matrix;
 import android.os.Bundle;
+
 import androidx.exifinterface.media.ExifInterface;
+
```
Comment (bbarthec) [inline packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/ResolveTakenPictureAsyncTask.java]: Maybe just move `import androidx.exifinterface.media.ExifInterface;` below `import android.*` section 🤔

**Review by tsapeta — APPROVED** [review]
