### PR TITLE
[media-library] Add missing image loader for MediaLibrary in bare workflow

### LINKED ISSUE #7826: Cannot resolve assets-library:// or ph:// schemes on iOS in bare config
To resolve these schemes a custom `RCTURLRequestHandler` is necessary. Up until RN0.61, it was possible to get this by linking `RCTCameraRoll`, which includes `RCTAssetsLibraryRequestHandler`. However in RN0.61 this was deprecated. 

The Expo managed workflow relies on a custom patch to `react-native` to continue using the old `RCTAssetsLibraryRequestHandler`: https://github.com/expo/react-native/commit/7a357f9748624ca7c9223648a76b6dca68a66623

This is not possible to reproduce in the bare workflow, which makes it difficult to use `expo-media-library`. A workaround is to install `@react-native-community/cameraroll`, which provides similar functionality via [RNCAssetsLibraryRequestHandler](https://github.com/react-native-community/react-native-cameraroll/blob/master/ios/RNCAssetsLibraryRequestHandler.m).

However, relying on custom patches to `react-native` isn't a good solution for bare workflows. We should see if it's possible to move this functionality elsewhere. Would `expo-media-library` be a good candidate?

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Fixes #7826

# How

- Added `EXMediaLibraryImageLoader` module that implements `RCTImageURLLoader` so it will be used to load images with `assets-library://` and `ph://` schemes.

# Test Plan

Tested MediaLibrary examples in both bare and manage workflows. Photos are rendering correctly now.

### CODE REVIEW

**Comment by lukmccall** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  
📋 **Missing Changelog**
------
🛠 Add missing entires to:
- <code><a href="https://github.com/expo/expo/blob/@tsapeta/fix-missing-medialibrary-loader/packages/expo-media-library/CHANGELOG.md">packages/expo-media-library/CHANGELOG.md</a></code>
  </td>
    </tr>
  </tbody>
</table>




### 🛠 Suggested fixes:

<details>
  <summary>📋 Missing changelog</summary>

  #### Apply suggested changes:
```diff
diff --git a/packages/expo-media-library/CHANGELOG.md b/packages/expo-media-library/CHANGELOG.md
index bc2ee3c3c9..9f363b2998 100644
--- a/packages/expo-media-library/CHANGELOG.md
+++ b/packages/expo-media-library/CHANGELOG.md
@@ -8,5 +8,6 @@
 
 ### 🐛 Bug fixes
 
+- Add missing image loader for MediaLibrary in bare workflow. ([#8304](https://github.com/expo/expo/pull/8304) by [@tsapeta](https://github.com/tsapeta))
 - Fixed `MediaLibrary` not compiling with the `use_frameworks!` option in the bare React Native application. ([#7861](https://github.com/expo/expo/pull/7861) by [@Ashoat](https://github.com/Ashoat))
 - Flip dimensions based on media rotation data on Android to match `<Image>` and `<Video>` as well as iOS behavior. ([#7980](https://github.com/expo/expo/pull/7980) by [@Ashoat](https://github.com/Ashoat))
```

#### or merge this pull request: https://github.com/expo/expo/pull/8306 
</details>
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 499041b579b73c982e590619329bcb8d9344fe9e
</p>

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.h [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// Copyright 2015-present 650 Industries. All rights reserved.
+
+#if __has_include(<React/RCTBridge.h>)
```
Comment (sjchmiela) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.h:3]: Why use `RCTBridge.h` in the clause? (Why not `RCTImageURLLoader.h`?)

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m [hunk 2]
```diff
@@ -0,0 +1,106 @@
+// Copyright 2015-present 650 Industries. All rights reserved.
+
+#if __has_include(<React/RCTBridge.h>)
+
+#import <Photos/Photos.h>
+#import <React/RCTUtils.h>
+#import <EXMediaLibrary/EXMediaLibraryImageLoader.h>
+
+@implementation EXMediaLibraryImageLoader
```
Comment (sjchmiela) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m:9]: How about some information about why this is needed in a comment above the class definition?

File: packages/expo-media-library/CHANGELOG.md [hunk 3]
```diff
@@ -8,5 +8,6 @@
 
 ### 🐛 Bug fixes
 
+- Added missing image loader for MediaLibrary in bare workflow. ([#8304](https://github.com/expo/expo/pull/8304) by [@tsapeta](https://github.com/tsapeta))
```
Comment (sjchmiela) [inline packages/expo-media-library/CHANGELOG.md:11]:
```suggestion
- Added missing image loader for `MediaLibrary` in bare workflow. ([#8304](https://github.com/expo/expo/pull/8304) by [@tsapeta](https://github.com/tsapeta))
```
It looks like `MediaLibrary` was coded-d in the entry below.

File: packages/expo-media-library/ios/EXMediaLibrary.podspec [hunk 4]
```diff
@@ -19,4 +19,5 @@ Pod::Spec.new do |s|
   s.dependency 'UMCore'
   s.dependency 'UMPermissionsInterface'
   s.dependency 'UMFileSystemInterface'
+  s.dependency 'React'
```
Comment (sjchmiela) [inline packages/expo-media-library/ios/EXMediaLibrary.podspec:22]: Pity that we need to add this line, but this shouldn't break anything!

**Review by sjchmiela — APPROVED** [review]
Thank you for taking care of this! 😍

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+  if (progressHandler) {
+    imageOptions.progressHandler = ^(double progress, NSError *error, BOOL *stop, NSDictionary<NSString *, id> *info) {
+      static const double multiplier = 1e6;
+      progressHandler(progress * multiplier, multiplier);
+    };
+  }
+
+  // Note: PhotoKit defaults to a deliveryMode of PHImageRequestOptionsDeliveryModeOpportunistic
+  // which means it may call back multiple times - we probably don't want that
+  imageOptions.deliveryMode = PHImageRequestOptionsDeliveryModeHighQualityFormat;
```
Comment (Ashoat) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m:73]: Does this mean that if a user attempts to upload a `ph://` URI directly using `fetch`, the image might get upscaled (increase in size)? In stock React Native there’s the `ph-upload://` to be used in uploads to avoid the upscaling issue

Comment (tsapeta) [reply packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m:73]: Yeah, I think you may be right 🤔 My goal was to make it possible to render images with such urls and generally this is the same as photo library image loader from RN: [RCTPhotoLibraryImageLoader.mm](https://github.com/facebook/react-native/blob/master/Libraries/CameraRoll/RCTPhotoLibraryImageLoader.mm).
However, looks like it doesn't handle `ph-upload://` urls and for that case we would need to copy [RCTAssetsLibraryRequestHandler.mm](https://github.com/facebook/react-native/blob/master/Libraries/CameraRoll/RCTAssetsLibraryRequestHandler.mm) as well. They both provide similar functionality and they both fix an issue with rendering, so I thought we don't need both of them at once. Also looks like stock React Native doesn't include them by default since this is the old code of CameraRoll from before it's been moved to separate repo.

Is this thing important to you? Would you be able to open similar PR but copying request handler functionality?

Comment (Ashoat) [reply packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m:73]: It’s not important to me personally, I just figured I’d mention it :)

Comment (tsapeta) [reply packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibraryImageLoader.m:73]: Ok, cool, I'll try to fix this anyway before the release 😉 Thanks for pointing this out! 🙇‍♂️
