### PR TITLE
[iOS] Fix sending multiple SMSes one after another

### LINKED ISSUE #2936: Cannot send more than one SMS
### Environment
```
  Expo CLI 2.6.0 environment info:
    System:
      OS: Linux 4.11 Ubuntu 17.10 (Artful Aardvark)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.9.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
    npmPackages:
      expo: ^30.0.1 => 30.0.1 
      react: 16.4 => 16.4.2 
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4 
      react-navigation: ^3.0.2 => 3.0.2 
    npmGlobalPackages:
      expo-cli: 2.6.0
```

### Steps to Reproduce

(Write your steps here:)

1. Run the snack https://snack.expo.io/HkJJuQDJE on your iphone
2. Press the button
3. Send a text, or hit cancel

### Expected Behavior

One SMS modal should open, then close, and another should open 

### Actual Behavior

Only one SMS modal opens. 

### Reproducible Demo

https://snack.expo.io/HkJJuQDJE

You'll need to run this on your phone to have the SMS modal

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Problem was occurring only on iOS
Resolves #2936 
Resolves https://github.com/expo/universe/issues/3220

# How

iOS wasn't waiting for viewController completion callback and thus was failing to show another one.
Problem is solved by postponing resolution/rejection until completion callback is called.

# Test Plan

Use this snack: https://snack.expo.io/HkJJuQDJE
Or just this piece of code:
```javascript
 await SMS.sendSMSAsync('', 'hi 1');
 await SMS.sendSMSAsync('', 'hi 2');
```

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
👍

File: packages/expo-sms/ios/EXSMS/EXSMSModule.m [hunk 1]
```diff
@@ -52,44 +52,52 @@ - (void)setModuleRegistry:(EXModuleRegistry *)moduleRegistry
...
+      rejectMessage = @"SMS message sending failed with unknown error";
       break;
   }
-  _reject = nil;
-  _resolve = nil;
-  [controller dismissViewControllerAnimated:YES completion:nil];
+  EX_WEAKIFY(self);
+  [controller dismissViewControllerAnimated:YES completion:^{
+    EX_ENSURE_STRONGIFY(self);
+    if (rejectMessage != nil) {
```
Comment (sjchmiela) [inline packages/expo-sms/ios/EXSMS/EXSMSModule.m]:
```suggestion
    if (rejectMessage) {
```

**Review by tsapeta — APPROVED** [review]
