### PR TITLE
[location] Add method to get last known position

### LINKED ISSUE #3433: Location.getCurrentPositionAsync() Takes 10+ seconds after upgrading to SDK 31
### Environment

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v8.10.0/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^31.0.1 => 31.0.7 
      @types/react: ^16.7.13 => 16.7.18 
      @types/react-native: ^0.57.18 => 0.57.27 
      expo: ^31.0.0 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

This bug is happening on iOS in **standalone app only**

### Steps to Reproduce

I upgraded my app to SDK V31.  After noticing severly degraded performance related to location based services, I started profiling to see what was going on. The following consistently takes 10,100 ms to complete:

```js
import { Location } from 'expo';

async function getLocation() {
  const start = Date.now();
  await Location.getCurrentLocationAsync();
  console.log(Date.now() - start); // consistently around 10,100ms
}
```
This issue **only** happens in the standalone production version of my app. In development, there are no issues. I'd be happy to provide more information, but not sure what more to include given that this singular invocation is what's causing problems.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolves #3433.

# How

According to Apple documentation `Location.getCurrentPositionAsync()` will take several seconds to complete, because CLLocationManager needs to calibrate the device. To minimize the impact of this, I've created a new function which is responsible for getting the last known position.
I've also updated the documentation to warn the user about the long execution time of `getCurrentPositionAsync` and added new tests cases to `test-suits`.

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/github---location---getlastknownpositionasync <- you can check there the new functionality.
- test-suits passed

### CODE REVIEW

File: apps/test-suite/tests/Location.js [hunk 1]
```diff
@@ -95,6 +124,37 @@ export async function test(t) {
       );
     });
 
+    describeWithPermissions('Location.getLastKnowPositionAsync()', () => {
```
Comment (tsapeta) [inline apps/test-suite/tests/Location.js]:
```suggestion
    describeWithPermissions('Location.getLastKnownPositionAsync()', () => {
```

File: docs/pages/versions/unversioned/sdk/location.md [hunk 2]
```diff
@@ -48,10 +48,20 @@ Checks user's permissions for accessing location. Alias for `Permissions.getAsyn
...
+
+#### Returns
+
+Returns a promise resolving to an object representing [Location](#type-location) type.
+
 ### `Location.getCurrentPositionAsync(options)`
 
 Get the current position of the device.
 
+> **Note:** calling it on iOS causes the location manager to obtain a location fix which may take several seconds.
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/location.md]:
```suggestion
> **Note:** calling it on iOS causes the location manager to obtain a location fix which may take several seconds. Consider using [Location.getLastKnownPositionAsync](#locationgetlastknownpositionasync) if you expect to get a quick response and high accuracy is not required.
```

File: packages/expo-location/ios/EXLocation/EXLocation.m [hunk 3]
```diff
@@ -172,6 +172,54 @@ - (void)stopObserving {}
...
+    if (lockMgr) {
+      [lockMgr stopUpdatingLocation];
+      lockMgr = nil;
+    }
+    
+    if (delegate) {
+      if (locations.lastObject) {
+        resolve([EXLocation exportLocation:locations.lastObject]);
+      } else {
+        reject(@"E_LAST_KNOW_LOCATION_NOT_FOUND", @"Last known location not found.", nil);
```
Comment (tsapeta) [inline packages/expo-location/ios/EXLocation/EXLocation.m]:
```suggestion
        reject(@"E_LAST_KNOWN_LOCATION_NOT_FOUND", @"Last known location not found.", nil);
```

File: packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java [hunk 4]
```diff
@@ -172,6 +172,23 @@ public void getPermissionsAsync(final Promise promise) {
...
+  public void getLastKnownPositionAsync(final Promise promise) {
+    // Check for permissions
+    if (isMissingPermissions()) {
+      promise.reject(new LocationUnauthorizedException());
+      return;
+    }
+
+    getLastKnownLocation(null, location -> {
+      if (location == null) {
+        promise.reject("E_LAST_KNOW_LOCATION_NOT_FOUND", "Last known location not found.", null);
```
Comment (tsapeta) [inline packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java]:
```suggestion
        promise.reject("E_LAST_KNOWN_LOCATION_NOT_FOUND", "Last known location not found.", null);
```

File: apps/test-suite/tests/Location.js [hunk 5]
```diff
@@ -17,6 +17,35 @@ export async function test(t) {
   const shouldSkipTestsRequiringPermissions = await TestUtils.shouldSkipTestsRequiringPermissionsAsync();
   const describeWithPermissions = shouldSkipTestsRequiringPermissions ? t.xdescribe : t.describe;
 
+  const testShapeOrUnauthorized = (testFunction, options) => async () => {
```
Comment (tsapeta) [inline apps/test-suite/tests/Location.js]: I think we shouldn't pass `testFunction` and `options` separately, that way we're losing invocation context. It might be better to have just one argument here that is an arrow function that calls appropriate method with appropriate arguments.

**Review by tsapeta — CHANGES_REQUESTED** [review]

**Review by tsapeta — APPROVED** [review]
