### PR TITLE
[notifications] add FCM intent origin validation

### LINKED ISSUE #34523: `getLastNotificationResponseAsync` returns a half-empty object when the app is launched on Android
### Minimal reproducible example

https://github.com/TuurDutoit/expo-notifications-example

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

## Summary
When launching the app on Android, `getLastNotificationResponseAsync` returns a half-empty object like this:

```json
{
  "actionIdentifier": "expo.modules.notifications.actions.DEFAULT",
  "notification": {
    "date": 0,
    "request": {
      "identifier": null,
      "content": {
        "data": {
          "anim_not_finish": false
        },
        "title": null
      },
      "trigger": {
        "type": "push",
        "channelId": null
      }
    }
  }
}
```

## How to reproduce
I attached a repo you can use to reproduce the issue. It's essentially the `bare-minimum` template with `expo-notifications` installed. I added some logs so we can see the received data in the console.

To run it:
1. Build and run the app: `npm run android`
2. Close and reopen the app

Expected behavior: the last notification response logged to the console is `null`

Actual behavior: the data is an object that *looks* like a notification response, but misses most of the keys.

## Logs
All the relevant logs, both from `expo-notifications`, as well the ones I added.

JS:
```
 LOG  LAST NOTIFICATION RESPONSE {
  "actionIdentifier": "expo.modules.notifications.actions.DEFAULT",
  "notification": {
    "date": 0,
    "request": {
      "identifier": null,
      "content": {
        "data": {
          "anim_not_finish": false
        },
        "title": null
      },
      "trigger": {
        "type": "push",
        "channelId": null
      }
    }
  }
}
```

Native logs (logcat):
```
01-28 13:36:19.229 10349 10349 I expo-notifications: ExpoNotificationLifeCycleListener.onCreate::
01-28 13:36:19.229 10349 10349 I expo-notifications: anim_not_finish: false
01-28 13:36:19.229 10349 10349 I TESTING : MainActivity.onCreate | intent.extras:
01-28 13:36:19.229 10349 10349 I TESTING : MainActivity.onCreate | - anim_not_finish
01-28 13:36:19.229 10349 10349 I TESTING : MainActivity.onCreate | /intent.extras
01-28 13:36:20.643 10349 10436 I expo-notifications: NotificationsEmitter.onNotificationResponseIntentReceived:
01-28 13:36:20.643 10349 10436 I expo-notifications: actionIdentifier: expo.modules.notifications.actions.DEFAULT
01-28 13:36:20.643 10349 10436 I expo-notifications: notification
01-28 13:36:20.643 10349 10436 I expo-notifications:   date: 0
01-28 13:36:20.643 10349 10436 I expo-notifications:   request
01-28 13:36:20.643 10349 10436 I expo-notifications:     identifier: (null)
01-28 13:36:20.643 10349 10436 I expo-notifications:     trigger
01-28 13:36:20.643 10349 10436 I expo-notifications:       type: push
01-28 13:36:20.643 10349 10436 I expo-notifications:       channelId: (null)
01-28 13:36:20.643 10349 10436 I expo-notifications:     content
01-28 13:36:20.643 10349 10436 I expo-notifications:       data
01-28 13:36:20.643 10349 10436 I expo-notifications:         anim_not_finish: false
01-28 13:36:20.643 10349 10436 I expo-notifications:       title: (null)
```

Note that, when the app is launched, there is 1 "extra" attached to the intent: `anim_not_finish`. I'm not sure where this comes from, I assume it's from my OS (I use a OnePlus Nord 2T 5G).

## What I've been able to find so far
- `MainActivity.onCreate` calls `ReactActivityDelegateWrapper.onCreate`
- `ReactActivityDelegateWrapper.onCreate` calls all `reactActivityLifecycleListeners` [here](https://github.com/expo/expo/blob/6ada9f5a9559fd75aeeaffdfdff5dc4e1b3180bf/packages/expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt#L183)
- That includes `expo-notifications`' `ExpoNotificationLifecycleListener.onCreate` [here](https://github.com/expo/expo/blob/6ada9f5a9559fd75aeeaffdfdff5dc4e1b3180bf/packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoNotificationLifecycleListener.java#L31)
- If there are *any* extras attached to the intent, they are passed to `mNotificationManager.onNotificationResponseFromExtras`

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.local/state/fnm_multishells/38834_1738067722227/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.2 - ~/.local/state/fnm_multishells/38834_1738067722227/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.28 => 52.0.28 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.6 => 0.76.6 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check native tooling versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by vonovak**
# Why

closes https://github.com/expo/expo/issues/34523

This PR fixes an issue with notification handling on Android by properly filtering out OEM-injected extras that aren't actual FCM notifications. Some device manufacturers (like Samsung) inject extras into intents that can be mistakenly processed as notifications.

# How

- Added a constant `GOOGLE_MESSAGE_ID_KEY` to reference the FCM message ID key consistently
- Added validation in `ExpoNotificationLifecycleListener` to check if intents contain the FCM message ID before processing them as notifications

# Test Plan

- notification tester app on device - send push notification to a killed app, tap it, observe `isFCMIntent` returning `true` in `ExpoNotificationLifecycleListener`

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by vonovak** [comment]
* **#43206** <a href="https://app.graphite.com/github/pr/expo/expo/43206?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/43206?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: apps/native-component-list/src/api/sendPushNotificationsAsync.ts [hunk 1]
```diff
@@ -43,17 +43,49 @@ export async function sendPushNotificationsAsync({
...
       }
-      if (receipt.__debug) {
-        console.warn(receipt.__debug);
+      if (ticket.__debug) {
+        console.warn(ticket.__debug);
+      }
+    }
+  }
+
+  // Check push receipts after a delay to confirm delivery
```
Comment (douglowder) [inline apps/native-component-list/src/api/sendPushNotificationsAsync.ts:61]: This section seems related to a different PR?

Comment (vonovak) [reply apps/native-component-list/src/api/sendPushNotificationsAsync.ts:61]: It's not directly related, but it's an improvement of the existing code which is there and sends push notifications to the device which runs the code.

**Review by douglowder — APPROVED** [review]
