### PR TITLE
[expo-screen-orientation] Fix getting initial orientation.

### LINKED ISSUE #8210: locking screen orientation buggy in SDK37
### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Justyna\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ^37.0.8 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

Target: iOS

### Steps to Reproduce

On the splash screen I am fetching the current orientation of the phone and then I am locking the app to this orientation
```		
await ScreenOrientation.getOrientationAsync().then((orientationId) => {
    orientation = ScreenOrientation.Orientation[orientationId];
    ScreenOrientation.lockAsync(
    ScreenOrientation.OrientationLock[orientation]
    );
});
```
In SDK36, everything was working as expected:
1. On initial: when phone was in landscape position the app was loaded and locked in landscape for the whole time of app working, therefore:
2. When coming back from the background, doesn't matter if the phone was in landscape or portrait position, app was loaded as locked.
https://streamable.com/jhmee9

In SDK37:
1. On initial, when phone is in the horizontal position, it is rotating by itself to the portrait
https://streamable.com/0a5qw5

2. However when I rotate the phone form portrait to landscape orientation on initial, it's 'catching' horizontal position and the app is loaded in landscape.  But when coming back from background, when phone is in portrait position, it is first loaded to the phone position, and then rotating by itself to locked position.
https://streamable.com/3obzqo

I know that there is an option to set orientation in the app.json, however my app should work in both landscape/horizontal position, as locked on initial. Setting 'orientation' to 'default' does not change anything. 

Specially the issue with not fetching properly orientation on initial is problematic, as clients using this app on the tablets build in the wall

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/8210.

# How

- Initializes current screen orientation in the constructor of the `EXScreenOrientationRegisty`.
- Saves the last known orientation mask when the app is moved to the background and restores it when the app is moved to the foreground.

# Test Plan

- bare-expo ✅
- client ✅

# Changelog

- Fix `ScreenOrientation. getOrientationAsync` returning a wrong value when the application is starting.

### CODE REVIEW

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m [hunk 1]
```diff
@@ -79,6 +90,11 @@ - (void)setMask:(UIInterfaceOrientationMask)mask forModule:(id)module {
 
 - (UIInterfaceOrientationMask)requiredOrientationMask
 {
+  // The app is moved to the foreground.
+  if (!_foregroundedModule && _lastOrientationMask) {
```
Comment (sjchmiela) [inline packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:94]: If there is no `_foregroundedModule`, but `_lastOrientationMask` is falsy, we will skip this clause, move over to `[_moduleInterfaceMasks objectForKey:_foregroundedModule]` which will result in `nil`, since `_foregorundedModule` is `nil` and return `0`.

Was this `&& _lastOrientationMask` intentional?

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m [hunk 2]
```diff
@@ -214,6 +230,10 @@ - (void)moduleDidForeground:(id)module
 
 - (void)moduleDidBackground:(id)module
 {
+  // We save the mask to restore it when the app moves to the foreground.
+  // We don't want to wait for the module to call moduleDidForeground, cause it will add unnecessary rotation.
+  _lastOrientationMask = [self requiredOrientationMask];
```
Comment (sjchmiela) [inline packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:235]: Should we call this only if `_foregroundedModule == module`?

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m [hunk 3]
```diff
@@ -25,14 +26,24 @@ - (instancetype)init
...
     dispatch_async(dispatch_get_main_queue(), ^{
       [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
+      
+      UM_ENSURE_STRONGIFY(self)
+      if (@available(iOS 13, *)) {
+        self.currentScreenOrientation = UIApplication.sharedApplication.windows[0].windowScene.interfaceOrientation;
+      } else {
+        // statusBarOrientation was deprecated in iOS 13
+        self.currentScreenOrientation = UIApplication.sharedApplication.statusBarOrientation;
+      }
```
Comment (sjchmiela) [inline packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:46]: Shouldn't we call it on the main queue **synchronously**? `dispatch_async` means that this may be executed some time from now, maybe it would be wrong to other methods be executed before assigning the `currentScreenOrientation` initial value?

**Review by sjchmiela — COMMENTED** [review]
Correct me if I'm wrong — this sounds like a good fix to the "initial orientation" problem, but I'm a little bit afraid that setting the mask to more rigid only **after** the app is foregrounded… could it mean that when a user taps on an icon they can see the rotation being executed (if the device would have been rotated while the app was in background).

Leaving this behavior of disabling lock when the app backgrounds may be useful for brownfield apps (eg. RN app lock shouldn't automatically impact app after being hidden — or maybe it should?), but if this feature would cause the app to rotate in background or something maybe we should rethink this. Does it rotate in background?

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m (hunk 1 above)
Comment (lukmccall) [reply packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:94]: So, I wanted to make it less confusing by adding this check. When `_lastOrientationMast` is `0` and the `_foregroundedModule` is `nil` we still returns `0` as a default value. But not as a saved `_lastOrientationMask`. I'm not sure if you will understand what I mean by this. However, you pointed out this so it is still confusing 😅

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m (hunk 2 above)
Comment (lukmccall) [reply packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:235]: Nope, cause module can change mask when the app is running. So, the best place for this code is here in my option :D

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m (hunk 1 above)
Comment (sjchmiela) [reply packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:94]: No, actually I understood the code as you wanted to write it, just wanted to make sure. Good job! (The `if` handles only one, particular situation, all the other situations are handled below.)

**Comment by lukmccall** [comment]
> could it mean that when a user taps on an icon they can see the rotation being executed (if the device would have been rotated while the app was in background).

Without this fix, the user could see the rotation in the background. Now, it'll freeze in the last set orientation. So, when you click on the home button, your app will be displayed in the correct orientation.

> Leaving this behavior of disabling lock when the app backgrounds may be useful for brownfield apps (eg. RN app lock shouldn't automatically impact app after being hidden — or maybe it should?), but if this feature would cause the app to rotate in background or something maybe we should rethink this. Does it rotate in background?

No, it doesn't rotate in the background. It will work like other native apps.

File: packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m (hunk 2 above)
Comment (sjchmiela) [reply packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:236]: > module can change mask when the app is running

Sure, but we will only ever fetch a value from this variable if `_foregroundedModule` is `nil`, which only happens if:
- no module has been foregrounded yet (from the start), we return `0` in that case, `_lastOrientationMask` isn't taken into account,
- a module has been backgrounded, which can only happen if 
https://github.com/expo/expo/blob/ee29508092dd1e94e343cbe5ecdd1d45c6fcc1ac/packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m#L217-L218, so what I mean is that we also could just set the value once we go into the state in which we will read it.

**Comment by sjchmiela** [comment]
Don't forget to add a note about this change in behavior (breaking, imho) that now the module will keep the lock active when the app backgrounds!

**Review by sjchmiela — APPROVED** [review]
+ changelog! 👏 👏 👏
