### PR TITLE
[web][location] Fix event emitter crash on web

### LINKED ISSUE #41677: expo-location LocationEventEmitter type diverged between web and native (removeSubscription is not a function)
### Minimal reproducible example

https://snack.expo.dev/@edkimmel/expo-location-web-crash

### Steps to reproduce

Register and unregister a single location subscription on web via expo-location.  When LocationSubscriptions hits 0 remaining callbacks, you will get `removeSubscription is not a function` or a related error.

expo-location's LocationEventEmitter is using different types between Web and Native

[Web](https://github.com/expo/expo/blob/main/packages/expo-location/src/LocationEventEmitter.web.ts) is using the modern interface -  EventEmitter

[Native](https://github.com/expo/expo/blob/main/packages/expo-location/src/LocationEventEmitter.ts) is using the legacy interface - LegacyEventEmitter

If we look at those interfaces in expo-modules-core...

[LegacyEventEmitter](https://github.com/expo/expo/blob/main/packages/expo-modules-core/src/LegacyEventEmitter.ts#L84) - This has removeSubscription

[EventEmitter](https://github.com/expo/expo/blob/main/packages/expo-modules-core/src/ts-declarations/EventEmitter.ts) - This does NOT have removeSubscription.

[This line](https://github.com/expo/expo/blob/main/packages/expo-location/src/LocationSubscribers.ts#L72) in expo-location crashes on web, because removeSubscription is not defined in the modern interface.

This was discovered on SDK 53, but the main branch appears unchanged and still has this issue.

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 15.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      Yarn: 4.3.0 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/edward.kimmel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
      Android SDK:
        API Levels: 28, 30, 31, 32, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.2, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.27812.49.2514.14217341
      Xcode: 26.2/17C52 - /usr/bin/xcodebuild
    npmPackages:
      expo: 53.0.23 => 53.0.23 
      expo-updates: 0.28.17 => 0.28.17 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.5 => 0.79.5 
      react-native-web: 0.21.1 => 0.21.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
N/A
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #41677

# How
Stop using the legacy event emitter and replace `removeSubscription` with `remove`

# Test Plan
Bare-expo. web does not cause errors on web

### CODE REVIEW

File: packages/expo-location/src/LocationEventEmitter.ts [hunk 1]
```diff
@@ -1,5 +1,3 @@
-import { LegacyEventEmitter } from 'expo-modules-core';
-
 import ExpoLocation from './ExpoLocation';
 
-export const LocationEventEmitter = new LegacyEventEmitter(ExpoLocation);
+export const LocationEventEmitter = ExpoLocation;
```
Comment (edkimmel) [inline packages/expo-location/src/LocationEventEmitter.ts:3]: Not EventEmitter from expo-modules-core?

Comment (alanjhughes) [reply packages/expo-location/src/LocationEventEmitter.ts:3]: No, all native modules extend EventEmitter. https://github.com/expo/expo/blob/d5700e15ebc78b95b973aa6cb4fe02da8a33f810/packages/expo-modules-core/src/ts-declarations/NativeModule.ts#L8

**Review by vonovak — APPROVED** [review]
