### PR TITLE
[file-system][Android] Fix deleteAsync in older Android SDKs

### LINKED ISSUE #5170: [Android][FileSystem] Unable to delete any directory via FileSystem.deleteAsync(Uri) on Older Android Versions
### Environment

  System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.0/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v10.15.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.5
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce
````
  myCreateDirectoryMethod = async () => {
    try {
       await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'myDirectory');
    } catch (error) {
      }
  }
  myDeleteDirectoryMethod = async () => {
    try {
       await FileSystem.deleteAsync(FileSystem.documentDirectory + 'myDirectory');
    } catch (error) {
      }
  }

   this.myCreateDirectoryMethod()
   this.myDeleteDirectoryMethod()
````
### Expected Behavior

Delete successfully

### Actual Behavior

[Error: Encountered an exception while calling native method: Exception occurred while executing exported method deleteAsync on module ExponentFileSystem: null]

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves #5170

# How

Prior Android SDK 26 `File#toPath` is not implemented and 3rd party lib handling file deletion was using it under the hood. Copied and adapted deleting code from previously used lib version.

# Test Plan

[snack](https://snack.expo.io/@bbarthec/github---filesystem---android---deleteasync)

### CODE REVIEW

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 1]
```diff
@@ -883,4 +891,37 @@ private void ensureDirExists(File dir) throws IOException {
...
+      IOException exception = null;
+      for (File f : files) {
+        try {
+          forceDelete(f);
+        } catch (IOException ioe) {
+          exception = ioe;
+        }
+      }
+
+      if (null != exception) {
```
Comment (sjchmiela) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]:
```suggestion
      if (exception != null) {
```
isn't this how usually one would write `if`s? 🤔

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 2]
```diff
@@ -883,4 +891,37 @@ private void ensureDirExists(File dir) throws IOException {
...
+      if (files == null) {
+        throw new IOException("Failed to list contents of " + file);
+      }
+
+      IOException exception = null;
+      for (File f : files) {
+        try {
+          forceDelete(f);
+        } catch (IOException ioe) {
+          exception = ioe;
```
Comment (sjchmiela) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]: Do we want to continue `forceDelete`ing files, or would we want to early throw here? Why one and not the other?

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 3]
```diff
@@ -304,7 +307,12 @@ public void deleteAsync(String uriStr, Map<String, Object> options, Promise prom
       if ("file".equals(uri.getScheme())) {
         File file = uriToFile(uri);
         if (file.exists()) {
-          FileUtils.forceDelete(file);
+          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+            FileUtils.forceDelete(file);
+          } else {
+            // to be removed once Android SDK 25 support is dropped
```
Comment (sjchmiela) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]:
```suggestion
            // TODO: remove once Android SDK 25 support is dropped
```

`TODO` will show up when looking for TODOs 🙂

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 4]
```diff
@@ -36,6 +37,8 @@
 import java.io.OutputStreamWriter;
 import java.math.BigInteger;
 import java.net.CookieHandler;
+import java.nio.file.LinkOption;
+import java.nio.file.attribute.BasicFileAttributes;
```
Comment (sjchmiela) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]: Unused, do you still want to import them?

**Review by sjchmiela — COMMENTED** [review]
Thanks for investigating this! 💪

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 5]
```diff
@@ -883,4 +891,37 @@ private void ensureDirExists(File dir) throws IOException {
       throw new IOException("Couldn't create directory '" + dir + "'");
     }
   }
+
+  /**
+   * Concatenated copy of org.apache.commons.io@1.4.0#FileUtils#forceDelete
+   * Newer version of commons-io uses File#toPath() under the hood that unsupported below Android SDK 26
```
Comment (ide) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]:
```suggestion
   * Newer version of commons-io uses File#toPath() under the hood that is unsupported below Android SDK 26
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 6]
```diff
@@ -883,4 +891,37 @@ private void ensureDirExists(File dir) throws IOException {
...
+
+      if (null != exception) {
+        throw exception;
+      }
+
+      if (!file.delete()) {
+        throw new IOException("Unable to delete directory " + file + ".");
+      }
+    } else if (!file.delete()) {
+      throw new IOException( "Unable to delete file: " + file);
```
Comment (ide) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]:
```suggestion
      throw new IOException("Unable to delete file: " + file);
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java (hunk 4 above)
Comment (bbarthec) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]:
```suggestion
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java [hunk 7]
```diff
@@ -36,6 +37,8 @@
 import java.io.OutputStreamWriter;
 import java.math.BigInteger;
 import java.net.CookieHandler;
+import java.nio.file.LinkOption;
```
Comment (bbarthec) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]:
```suggestion
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java (hunk 1 above)
Comment (bbarthec) [reply packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]: Well yeah 😉

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java (hunk 2 above)
Comment (bbarthec) [reply packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java]: The behaviour is copied from `commons-io` that we were using previously, so I don't want to change any logic introduced there.

**Review by ide — APPROVED** [review]

**Comment by jsamr** [comment]
@bbarthec Will we have access to this patch in unimodules soon? Or do we have to wait for SDK36?

**Comment by bbarthec** [comment]
@jsamr, I can release this for bare workflow as release candidate (`-rc`) version. Other workflows will contain this fix since SDK36. Will that satisfy your needs?

**Comment by jsamr** [comment]
@bbarthec That would be perfect. I'm already plugged on `^0.7.0-rc.1`. Thank you so much!

**Comment by jsamr** [comment]
@bbarthec Wait, I didn't realized rc4 was out; thought I would be notified for having subscribed to releases! Guess the fix is already there.
