### PR TITLE
[expo-intent-launcher][android] Fixed Double to Long conversion for calendar timestamps.

### LINKED ISSUE #16958: [expo-intent-launcher][android] Calendar Event intent - ClassCastException: Double cannot be cast to Long
### Summary

When you supply the IntentLauncher with extra for the Event insert intent, the beginTime/endTime parameters are ignored because they are not considered a long. JavaScript always sending a double.

I'm not sure in all cases that we would want to just convert double to long, however is it possible to support this in some way for this particular intent? I would be happy to work on a PR if some direction on how it should be solved was provided.

From logcat:
```
04-07 11:12:04.941 27464 27464 W Bundle  : Key beginTime expected Long but value was a java.lang.Double.  The default value -1 was returned.
04-07 11:12:04.944 27464 27464 W Bundle  : Attempt to cast generated internal exception:
04-07 11:12:04.944 27464 27464 W Bundle  : java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo

Here is a reproducible demo:
https://snack.expo.dev/@frankcalise/intentlauncher-events

### PR DESCRIPTION
**Pull request by brianomchugh**
# Why

Fixes #16958 - Calendar event intents fail with ClassCastException when passing `beginTime`/`endTime` parameters because JavaScript numbers (doubles) were being converted to ints, but calendar timestamps exceed `Int.MAX_VALUE` and require `Long` type.

From the issue:
```
Key beginTime expected Long but value was a java.lang.Double. The default value -1 was returned.
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
```

# How

Modified `IntentLauncherModule.kt` to use magnitude-based type conversion:
- Values exceeding `Int.MAX_VALUE` or below `Int.MIN_VALUE` are converted to `Long`
- Smaller values remain as `Int` for backward compatibility
- This handles calendar timestamps (milliseconds since epoch) which are typically 13 digits and exceed the int range

# Test Plan

Tested with calendar intent using current timestamps:

```javascript
import * as IntentLauncher from 'expo-intent-launcher';

const now = Date.now(); // e.g., 1737463200000 (exceeds Int.MAX_VALUE: 2147483647)
const oneHourLater = now + (60 * 60 * 1000);

await IntentLauncher.startActivityAsync('android.intent.action.INSERT', {
  data: 'content://com.android.calendar/events',
  extra: {
    title: 'Test Event',
    beginTime: now,
    endTime: oneHourLater,
    allDay: false
  }
});
```

**Before fix:**
- ❌ ClassCastException in logcat
- ❌ Calendar opens but date/time fields are empty

**After fix:**
- ✅ No exceptions
- ✅ Calendar opens with date and time pre-filled correctly
- ✅ Backward compatibility maintained for smaller numeric values

---

**Checklist:**

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by brianomchugh** [comment]
This is not an ideal fix-- but the current behavior is worse. I think this fix is preferable to:
1. having to add specific cases for beginTime and endTime (and possibly others)
2. converting everything to double/long
3. leaving it broken for calendar intents (and possibly others)

The fix is backwards compatible, and only affects values larger than Int (which are currently broken anyway).

File: packages/expo-intent-launcher/android/src/main/java/expo/modules/intentlauncher/IntentLauncherModule.kt [hunk 1]
```diff
@@ -63,7 +63,20 @@ class IntentLauncherModule : Module() {
 
       params.extra?.let {
         val valuesList = it.mapValues { (_, value) ->
-          if (value is Double) value.toInt() else value
+          when {
+            value is Double -> {
+              // JavaScript sends all numbers as doubles. We need to convert them appropriately:
+              // - Large values (like calendar timestamps) need to be Long
+              // - Smaller values should remain Int for backward compatibility
+              // Calendar timestamps in milliseconds exceed Int.MAX_VALUE (2,147,483,647)
```
Comment (vonovak) [inline packages/expo-intent-launcher/android/src/main/java/expo/modules/intentlauncher/IntentLauncherModule.kt]:
```suggestion
```

**Review by vonovak — APPROVED** [review]
