### PR TITLE
[expotools] [circle] add flag to skip template in macro generation

### LINKED ISSUE #5537: [ad hoc] Expo custom iOS client crash
The created ios custom client app does crash while starting.
The app was deinstalled and re-installed. Did restart the iPhone, too.
When opening the App the white Expo splash screen with the “A”-icon is visible for a second and then back to the home screen.
```
Device: iPhone XS with iOS 12.4.1
```
Then I suspect the problem is on the Profile file.So I cleared Certificates & Identifiers & Profiles on the apple developer account and use expo client:ios rebuild it for many many time. Undoubtedly failed. Just crash and crash
**When the Profile been installed, it just open a web page, but it didn't show up at configuration profile like other Profile file**
And I tried it with Apple configurator 2. the same
I very much hope that someone can come out and help us solve this problem.
Thank you very much

### PR DESCRIPTION
**Pull request by quinlanj**
# Why
fixes https://github.com/expo/expo/issues/5537

- client builds are uploaded with a `GoogleService-Info.plist` file. Normally when we build the Expo Client App we release in the App Store, we put all our relevant secret keys in there. However, in our adhoc builds service, we strip out our secret keys, and `GoogleService-Info.plist` doesn't contain anything useful.
- This causes problems because packages like `FaceDetector` will look for the presence of a `GoogleService-Info.plist` and will attempt to configure a Firebase App if it exists. If the user did not provide the relevant keys in their manifest file (`ios.googleServicesFile`), this configuration call will fail because a.) `GoogleService-Info.plist` exists and b.) it doesn't contain the required firebase keys. 
- This is causing the adhoc client app to crash at start up because `FaceDetector` is trying to configure a Firebase App and erroring out [here](https://github.com/expo/expo/blob/master/packages/expo-face-detector/ios/EXFaceDetector/EXFaceDetectorAppDelegate.m#L15)

# How
- try to get client builds in a similar state as standalone builds. Standalone shell apps are uploaded to s3 without a `GoogleService-Info.plist`.
- In circle ci, both standalone and client builds have template files generated `expotools ios-generate-dynamic-macros`, but it looks like standalone builds call an extra step to use the supporting files in `exponent-view-template` instead.
- to fix this, we add a flag in `ios-generate-dynamic-macros` to skip the `GoogleService-Info.plist` template

# Test Plan
- [x] expect `et ios-generate-dynamic-macros --skip-template=GoogleService-Info.plist` to skip GoogleService-Info.plist
- [x] expect `et ios-generate-dynamic-macros --skip-template=GoogleService-Info.plist  --skip-template=Foo` to skip GoogleService-Info.plist
- [x] expect `et ios-generate-dynamic-macros` to generate GoogleService-Info.plist
- [ ] double check to make sure this plan wont break anything in prod :/ 
- [ ] make new branch that contains keyword `all-ci`
- [ ] approve job, ensure that the artifact uploaded to s3 has no `GoogleService-Info.plist`

### CODE REVIEW

**Review by wkozyra95 — APPROVED** [review]

**Review by dsokal — APPROVED** [review]

**Comment by quinlanj** [comment]
i've updated the pr to add supporting for skipping the template file in the macro gen script instead, as per our discussion on slack

File: tools/expotools/src/dynamic-macros/generateDynamicMacros.ts [hunk 1]
```diff
@@ -142,8 +142,19 @@ async function copyTemplateFilesAsync(platform, args, templateSubstitutions) {
     path.join(templateFilesPath, `${platform}-paths.json`)
   ).readAsync();
   const promises: Promise<any>[] = [];
+  const skipTemplates: Array<string> = args.skipTemplates || [];
 
   for (const [source, dest] of Object.entries(templatePaths)) {
+    if (skipTemplates.includes(source)){
```
Comment (dsokal) [inline tools/expotools/src/dynamic-macros/generateDynamicMacros.ts]: Maybe it would be useful to log something here.

**Review by dsokal — APPROVED** [review]
💯

**Review by wkozyra95 — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]
