### PR TITLE
[router] fix passing style array to <Link /> when using asChild

### LINKED ISSUE #31352: `asChild` throws error on child component with array style for React Native Web
### Minimal reproducible example

https://snack.expo.dev/@bryanmylee/link-aschild-breaks-on-array-styles

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

In React Native Web, `<Link asChild />` over a child component with array styles throws an error.

```tsx
<Link href="/details" asChild>
  <Pressable style={[styles.button, dynamic.button]} />
</Link>

/// Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported.
```

This is likely due to the use of `@radix-ui/react-slot` which does not support array styles.

I've submitted a related issue on `react-slot` regarding support for array styles.

https://github.com/radix-ui/primitives/issues/3107

However, it might be worthwhile to patch the behaviour using a fork of `react-slot` to handle `style` differently, since we have array style syntax available.

```tsx
<Link href="/details" asChild style={{ color: 'white' }}>
  <Pressable style={{ backgroundColor: 'red' }} />
</Link>
/// becomes
<Pressable style={[{ color: 'white' }, { backgroundColor: 'red' }]} />

<Link href="/details" asChild style={{ color: 'white' }}>
  <Pressable style={[style1, style2]} />
</Link>
/// becomes
<Pressable style={[{ color: 'white' }, style1, style2]} />
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.31 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.0.0
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by marklawlor**
# Why

Fix: #31352

RadixUI has special logic to handle the merging of `style` and `className` props. On the web styles are not allowed so Radix does not handle this scenario/ This could be fixed upstream (PR open), but it may not as RN is not their target platform.

# How

This shim calls `StyleSheet.flatten` on the styles before we render the <Slot />

We will need to do the same for the Headless components which use `<Slot />` as well.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by dlindenkreuz** [comment]
Why not fix it upstream in Radix UI?

**Comment by marklawlor** [comment]
@dlindenkreuz If I was the maintainer of Radix UI I would not merge the PR, so I'm just covering my bases. Radix UI is a web library. Asking them to add special logic in a single component for a not supported platform isn't likely to get merged.

If they merge this, then they probably also need to support style functions, etc. A better solution would be a new forked version that is RN focused.

File: packages/expo-router/src/link/LinkSlot.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+ * This shim calls `StyleSheet.flatten` on the styles before we render the <Slot />
+ *
+ * @see https://github.com/expo/expo/issues/31352
+ * @see https://github.com/radix-ui/primitives/issues/3107
+ * @param Component
+ * @returns
+ */
+function ShimSlotForReactNative(Component: typeof RUISlot): typeof RUISlot {
+  return forwardRef(function RNSlotHOC({ style, ...props }, ref) {
+    style = useMemo(() => StyleSheet.flatten(style), [style]);
```
Comment (EvanBacon) [inline packages/expo-router/src/link/LinkSlot.tsx:20]: Try running this on web

**Review by EvanBacon — APPROVED** [review]
