### PR TITLE
[android][media-library] Fix passing sortBy argument to native

### LINKED ISSUE #21338: MediaLibrary.getAssetsAsync() with sortBy crashes on Android, Expo SDK 48
### Minimal reproducible example

MediaLibrary.getAssetsAsync(anything)

### Summary

Hello,
I tried using expo-media-library in Expo SDK version 47, but the permissions kept failing because [expo-media-library was not using the granular permissions required by Android API 33](https://github.com/expo/expo/issues/20496).

I ended up upgrading to expo@next (SDK version 48) but now any calls to `getAssetsAsync` with the `sortBy` option throw an error.

The function all:

```
   return MediaLibrary.getAssetsAsync({
              album,
              first: 1,
              sortBy: [["creationTime", false]],
            })
```

```
Possible Unhandled Promise Rejection (id: 0):
Error: Call to function 'ExpoMediaLibrary.getAssetsAsync' has been rejected.
→ Caused by: The 1st argument cannot be cast to type expo.modules.medialibrary.AssetsOptions (received String)
→ Caused by: Cannot cast 'Array' for field 'sortBy' ('kotlin.collections.List<kotlin.String>').
→ Caused by: Cannot cast 'Array' to 'kotlin.String' required by the collection of type: 'kotlin.collections.List<kotlin.String>'.
→ Caused by: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String
```

The function works correctly when _not_ passing an array to `sortBy`.

Reproduction steps:
1. Create an expo app and install `expo-media-library`
2. Ask for permissions
3. Try to call `MediaLibrary.getAssetsAsync()` while passing an array of SortByKeys and booleans to `sortBy`

Note: I am using a development client.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.3 => 48.0.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.2 => 0.71.2
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 5.4.4
    Expo Workflow: bare

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Passing the `sortBy` argument as a tuple was throwing an error on the native side because the expected type is `List<String>`.
Fixes #21338

# How
Wrote a function on the JS side that maps the argument to the expected type.

# Test Plan
Added a new test that passes the argument as a tuple and gets the expected result. All other tests are still passing as before

### CODE REVIEW

File: packages/expo-media-library/src/MediaLibrary.ts [hunk 1]
```diff
@@ -370,6 +370,13 @@ function checkSortByKey(sortBy: any): void {
   }
 }
 
+function sortByOptionToString(sortBy: any) {
+  if (Array.isArray(sortBy)) {
+    return `${sortBy[0]} ${sortBy[1] ? 'ASC' : 'DESC'}`;
+  }
+  return `${sortBy} DESC`;
+}
```
Comment (lukmccall) [inline packages/expo-media-library/src/MediaLibrary.ts:378]: That function won't work well with the current iOS implementation. It won't be understood by https://github.com/expo/expo/blob/9df607dd0286e61f7606253b2941924db4cbae9a/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L1111-L1130

**Review by lukmccall — CHANGES_REQUESTED** [review]

File: apps/test-suite/tests/MediaLibrary.js [hunk 2]
```diff
@@ -353,10 +350,12 @@ export async function test(t) {
 
           // Repeat assets request but reverse the order.
           const { assets: ascendingAssets } = await MediaLibrary.getAssetsAsync({
-            first: assetsToCheck,
             sortBy: [[MediaLibrary.SortBy.height, true]],
           });
 
+          console.log(JSON.stringify(ascendingAssets, null, 2));
+          console.log(JSON.stringify(assets, null, 2));
```
Comment (lukmccall) [inline apps/test-suite/tests/MediaLibrary.js:357]:
```suggestion
```

**Review by lukmccall — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]
