### PR TITLE
[expo-blur][ios] Fix Detox tests hanging when BlurView is present

### LINKED ISSUE #21640: [expo-blur] Detox tests hang indefinitely on screen with BlurView on iOS
### Minimal reproducible example

https://github.com/philiplindberg/expo-blur-detox-repro

### Summary

I'm using both `BlurView` and Detox (for e2e testing) in my project, but I've noticed that whenever I try to run detox tests on a screen that has a `BlurView`, the detox test hangs indefinitely on iOS with the following error:

```
14:15:58.767 detox[13592] i The app is busy with the following tasks:
• Run loop "Main Run Loop" is awake.
• UI elements are busy:
  - Layer animations pending: 5.
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
```

To reproduce the issue, clone my [repro](https://github.com/philiplindberg/expo-blur-detox-repro) and run the following commands:
```
yarn install
yarn expo prebuild
yarn detox build -c ios.release
yarn detox test -c ios.release
```

Here's a screen recording of the detox tests being run on an iOS simulator:

https://user-images.githubusercontent.com/1865904/224052571-97c40fc8-0fd5-4ef8-bb69-bff618ab1ac3.mov

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.asdf/installs/nodejs/lts/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.6 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/21640

# How

Added check in `BlurEffectView.swift` , which detects if detox tests are running. In that case animation-based blur intensity is replaced with simple on/off behaviour.

# Test Plan

Tested on iOS 16 simulator in BareExpo and the example provided in the issue.

### CODE REVIEW

File: packages/expo-blur/ios/BlurEffectView.swift [hunk 1]
```diff
@@ -39,6 +39,17 @@ final class BlurEffectView: UIVisualEffectView {
 
   override func draw(_ rect: CGRect) {
     super.draw(rect)
+
+    // BlurView intensity relies on running an animation and making it partially complete. This means that there
+    // is a continually running animation, which makes detox hang (it waits for the animation to finish indefinitely).
+    // We can detect if detoxServer is running and in that case replace smooth intensity value with an on/off behaviour.
+    let args = ProcessInfo.processInfo.arguments
+
+    if args.contains("-detoxServer") && args.contains("-detoxSessionId") {
```
Comment (tsapeta) [inline packages/expo-blur/ios/BlurEffectView.swift:48]: Can you move these checks to a separate function?

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]
