### PR TITLE
[video][ios]Add `keepFullscreenOnPiPStop` property

### LINKED ISSUE #44757: expo-video on iOS: fullscreen mode not reinstated when returning from PiP
### Minimal reproducible example

https://github.com/JoshWhiteTTD/expo-video-pip-return-ios-repro

### Steps to reproduce

- Tap play button - enters fullscreen mode
- Background the app - PiP starts
- Tap restore in PiP

Expected:
Video to continue playing in fullscreen mode

Actual:
Video moves to inline mode.
This is exacerbated in this repro, as the inline video is hidden and therefor the video stops playing

If the video is not hidden, it continues to play, but I would expect it to return to fullscreen mode and continue playing if that's the mode in which it left. 

### Environment

```text
expo-env-info 2.0.12 environment info:
    System:
      OS: Windows 11 10.0.26200
    Binaries:
      Node: 24.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 11.6.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ~55.0.15 => 55.0.15
      react: 19.2.0 => 19.2.0
      react-native: 0.83.4 => 0.83.4
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/44757

After entering PiP from a fullscreen video, on iOS, the player will return to the non-fullscreen video view after exiting PiP.

# How

Add three options of methods of returning to fullscreen from pip - depending on usage you may want something else - on Android we don't need this since PiP can't be used within the app there. 

 - `'always'`: Always re-enter fullscreen when PiP stops.
 - `'autoEnter'`: Re-enter fullscreen only when PiP was started automatically by the app going to the background. (default)
 - `'never'`: Do not re-enter fullscreen when PiP stops.
 

Adding this required a bit of work - when entering PiP `AVPlayer` will always exit fullscreen - but we can use `restoreUserInterfaceForPictureInPictureStopWithCompletionHandler` to re-enter Fullscreen before exiting PiP. 

# Test Plan

Tested on iPhone 13 running iOS 18

### CODE REVIEW

File: packages/expo-video/ios/OrientationAVPlayerViewController.swift [hunk 1]
```diff
@@ -185,14 +198,43 @@ internal class OrientationAVPlayerViewController: AVPlayerViewController, AVPlay
...
+  ) {
+    let shouldRestore: Bool
+    switch keepFullscreenOnPiPStop {
+    case .always:
+      shouldRestore = true
+    case .autoEnter:
+      shouldRestore = pipWasAutoEntered
+    case .never:
+      shouldRestore = false
+    }
```
Comment (tsapeta) [inline packages/expo-video/ios/OrientationAVPlayerViewController.swift]: Consider moving this to a separate function, maybe in the `KeepFullscreenOnPiPStopBehavior` enum

**Review by tsapeta — APPROVED** [review]
