### PR TITLE
[Android][sdk39] Make SplashScreen methods work in SDK39

### LINKED ISSUE #10263: [ios][android] Warning about native splash screen in latest Expo development clients
## 🐛 Bug Report

In the iOS Expo development client 2.17.1, currently available for download from the App Store, and Android Expo development client 2.17.2, currently available from Google Play, occasionally the following warning is logged when running a project in development:

```
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
```

This is a known issue with these versions and will be fixed in a future update. This warning can be ignored and you do not need to do anything to resolve it.

### PR DESCRIPTION
**Pull request by bbarthec**
Redirect native code flow from verisioned splash screen module realm storing no information to unversioned splash screen module realm that stores all information about current activity's splash.

# Why

Resolves https://github.com/expo/expo/issues/10263

# How

- in SDK 39 codebase whenever you make a call into native methods you end up in versioned native codebase
- each ExperienceActivity is being registered in unversioned `expo-splash-screen`
- unfortunately versioned `expo-splash-screen` is not using `SingletonModules` (yet?) and therefore it tries to operate on unregistered activity (because the activity is registered in unversioned module)
- I've redirected the flow from versioned to unversioned realm by simply importing in the versioned module the kotlin object from unversioned module that handles the whole splash screen logic

### Other solution would be:
- create package with the SplashScreenSingletonModule interface and publish as a separate package (that would add complexity into `expo-splash-screen` package itself)
- register unversioned SplashScreen object as a singleton module in ModuleRegistry
- use ModuleRegistry.getSingletonModule("SplashScreenSingletonModuleName", SplashScreenInterface.class); (that would add complexity into `expo-splash-screen` package itself)

# Test Plan

- open Expo Client
- `expo init` & select `tabs managed template`
- see that no warning is thrown and everything works (both `SplashScreen.preventAutoHideAsync` and `SplashScreen.hideAsync`)

### CODE REVIEW

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt [hunk 1]
```diff
@@ -9,6 +9,15 @@ import abi39_0_0.org.unimodules.core.errors.CurrentActivityNotFoundException
...
 import abi39_0_0.org.unimodules.core.interfaces.ExpoMethod
 
+// Below import is added explicitly to provide a redirection from versioned code realm to unversioned code realm.
+// Without this import any `SplashScreen.methodName(...)` invocation on JS side ends up in versioned SplashScreen kotlin object that stores no state about the ExperienceActivity.
+// Other solution would be:
+// - create package with the SplashScreeSingletonModule interface and publish as a separate package (that would add complexity into `expo-splash-screen` package itself)
+// - register unversioned SplashScreen object as a singleton module in ModuleRegistry
+// - use ModuleRegistry.getSingletonModule("SplashScreenSingletonModuleName", SplashScreenInterface.class); (that would add complexity into `expo-splash-screen` package itself)
+// TODO (@bbarthec): add this import while performing Android versioning
+import expo.modules.splashscreen.SplashScreen
```
Comment (sjchmiela) [inline android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:19]: For this to be working in future SDK versioning phases you'll need to add this class to [`android-packages-to-keep.txt`](https://github.com/expo/expo/blob/227455e3d6f4bc9d05ca84109db5cbc03a56e342/tools/expotools/src/versioning/android/android-packages-to-keep.txt) and add this import to unversioned `SplashScreenModule` itself.

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt [hunk 2]
```diff
@@ -9,6 +9,15 @@ import abi39_0_0.org.unimodules.core.errors.CurrentActivityNotFoundException
 import abi39_0_0.org.unimodules.core.interfaces.ActivityProvider
 import abi39_0_0.org.unimodules.core.interfaces.ExpoMethod
 
+// Below import is added explicitly to provide a redirection from versioned code realm to unversioned code realm.
+// Without this import any `SplashScreen.methodName(...)` invocation on JS side ends up in versioned SplashScreen kotlin object that stores no state about the ExperienceActivity.
+// Other solution would be:
+// - create package with the SplashScreeSingletonModule interface and publish as a separate package (that would add complexity into `expo-splash-screen` package itself)
```
Comment (sjchmiela) [inline android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:15]:
```suggestion
// - create package with the SplashScreenSingletonModule interface and publish as a separate package (that would add complexity into `expo-splash-screen` package itself)
```

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt [hunk 3]
```diff
@@ -9,6 +9,15 @@ import abi39_0_0.org.unimodules.core.errors.CurrentActivityNotFoundException
 import abi39_0_0.org.unimodules.core.interfaces.ActivityProvider
 import abi39_0_0.org.unimodules.core.interfaces.ExpoMethod
 
+// Below import is added explicitly to provide a redirection from versioned code realm to unversioned code realm.
```
Comment (sjchmiela) [inline android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:12]: Personally I think the long version of this explanation (current one) belongs to this pull request's description while in the code we could put like a one-two lines summary pointing out that it's intentional (if anything, this pattern isn't uncommon in the codebase). _Other solutions_ section contains information that can become outdated easily.

**Review by sjchmiela — COMMENTED** [review]
LGTM, but I'd advocate for making these other changes in this PR. 👍

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt (hunk 1 above)
Comment (bbarthec) [reply android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:19]: I'm not this happy to trash the module codebase with unnecessary code (import in this case), but rather provide some code injection in versioning process 😉
My argument is: let's keep in mind the module-centric approach and treat Expo Client as a special case that needs more adjustments.

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt [hunk 4]
```diff
@@ -9,6 +9,15 @@ import abi39_0_0.org.unimodules.core.errors.CurrentActivityNotFoundException
...
+// Without this import any `SplashScreen.methodName(...)` invocation on JS side ends up in versioned SplashScreen kotlin object that stores no state about the ExperienceActivity.
+// Other solution would be:
+// - create package with the SplashScreenSingletonModule interface and publish as a separate package (that would add complexity into `expo-splash-screen` package itself)
+// - register unversioned SplashScreen object as a singleton module in ModuleRegistry
+// - use ModuleRegistry.getSingletonModule("SplashScreenSingletonModuleName", SplashScreenInterface.class); (that would add complexity into `expo-splash-screen` package itself)
```
Comment (bbarthec) [inline android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:17]:
```suggestion
```

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt [hunk 5]
```diff
@@ -9,6 +9,11 @@ import abi39_0_0.org.unimodules.core.errors.CurrentActivityNotFoundException
 import abi39_0_0.org.unimodules.core.interfaces.ActivityProvider
 import abi39_0_0.org.unimodules.core.interfaces.ExpoMethod
 
+// Below import is added explicitly to provide a redirection from versioned code realm to unversioned code realm.
+// Without this import any `SplashScreen.methodName(...)` invocation on JS side ends up in versioned SplashScreen kotlin object that stores no state about the ExperienceActivity.
```
Comment (bbarthec) [inline android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:13]:
```suggestion
// Without this import any `SplashScreen.methodName(...)` invocation on JS side ends up in versioned SplashScreen kotlin object that stores no information about the ExperienceActivity.
```

File: android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt (hunk 1 above)
Comment (sjchmiela) [reply android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:15]: If you want the import to be necessary you can always move `SplashScreen` to a separate `.singletons` package. 😛 

You could also add a regexp that replaces
```kt
class SplashScreenModule(context: Context) : ExportedModule(context) {
```
with the same + the import, but you know what they say about problems and regexps. 😃 

Yet another solution is to reference `SplashScreen` everywhere by fully qualified name, i.e. `expo.modules.splashscreen.SplashScreen` — iirc versioning script should catch that (I think this solution is already used somewhere).

--- 

What I mean is — let's solve this problem now. (I also wouldn't say that adding an import is _trashing the module with unnecessary code_, but that's an opinion.)

Comment (esamelson) [reply android/versioned-abis/expoview-abi39_0_0/src/main/java/abi39_0_0/expo/modules/splashscreen/SplashScreenModule.kt:15]: > What I mean is — let's solve this problem now. 

I agree with this and would also add that we should go with whatever solution is **most likely to keep working in the future**. The cleanliness of the codebase is subjective and is less important than the direct maintenance cost to us to keep the module working in future SDK versions.

**Review by sjchmiela — APPROVED** [review]
Superb! Thanks for taking care of everything! 👍
