### PR TITLE
[linear-gradient] fix crash when r8 enabled

### LINKED ISSUE #21562: [expo-linear-gradient] android - crash when enable Proguard
### Minimal reproducible example

https://github.com/GaelCO/repro_linearGradient

### Summary

Hi,

When I update the libraries of my project, my app crash on release if proguard is enabled.
Main libraries for this issue
- expo 46.0.20 to 48.0.5
- expo-linear-gradient 11.4.0 to 12.1.1
- react-native 0.70.7 to 0.71.3

The app crashs on LinearGradient component. If I remove it, my app doesn't crash.
likewise, if I disable proguard, the app doesn't crash too.

By crashlytics, I obtain this log : 
```
Fatal Exception: java.lang.IllegalArgumentException: class gf.b doesn't have a primary constructor
       at expo.modules.kotlin.views.d$a.a(:196)
       at expo.modules.kotlin.views.d$a.w(:4)
       at expo.modules.kotlin.views.f.a(:12)
       at expo.modules.kotlin.views.g.b(:19)
       at expo.modules.kotlin.views.SimpleViewManagerWrapper.createViewInstance(:9)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(:27)
       at com.facebook.react.uimanager.ViewManager.createView()
       at com.facebook.react.uimanager.t.j(:40)
       at com.facebook.react.uimanager.c1$e.a(:23)
       at com.facebook.react.uimanager.c1$j.d(:58)
       at com.facebook.react.uimanager.c1$j.c(:23)
       at com.facebook.react.uimanager.k.a()
       at com.facebook.react.modules.core.g$d.a(:46)
       at com.facebook.react.modules.core.a$a$a.doFrame(:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:775)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

To reproduce this issue, I created a new project (repro_linearGradient) and added last version of expo and expo-linear-gradient.
You can launch the release version with yarn android-release. 

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.0 - /usr/local/bin/npm
      Watchman: 20221126.133621.0 - /usr/local/bin/watchman
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #21562

# How

the code here will be stripped by R8: https://github.com/expo/expo/blob/4d234bbfb32b66b3944a0e652eda1e6c67287059/packages/expo-linear-gradient/android/src/main/java/expo/modules/lineargradient/LinearGradientView.java#L25-L27 and then our `ViewDefinitionBuilder` cannot find the primary constructor. this pr adds the keep annotation.

i didn't find a way to fix it systematically from expo-modules-core. let's address case by case and expo-linear-gradient first.

# Test Plan

https://github.com/GaelCO/repro_linearGradient with patch-package for the fix

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-linear-gradient/android/src/main/java/expo/modules/lineargradient/LinearGradientView.java [hunk 1]
```diff
@@ -22,6 +24,8 @@ public class LinearGradientView extends View {
   private int[] mSize = {0, 0};
   private float[] mBorderRadii = {0, 0, 0, 0, 0, 0, 0, 0};
 
+  // Keeps this primary constructor from Proguard/R8 for ViewDefinitionBuilder
+  @Keep
```
Comment (lukmccall) [inline packages/expo-linear-gradient/android/src/main/java/expo/modules/lineargradient/LinearGradientView.java:28]: Is there any difference between @Keep and @DoNotStrip?

**Review by lukmccall — APPROVED** [review]
