### PR TITLE
[permissions] guard mounted state

### LINKED ISSUE #12441: usePermissions triggers the Warning: Can't perform a React state update on an unmounted component
### Summary

usePermissions triggers the Warning: Can't perform a React state update on an unmounted component when I leave the view.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

_No response_

### Environment

  Expo CLI 4.1.6 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.asdf/installs/nodejs/14.15.4/bin/node
      Yarn: 1.22.10 - ~/.asdf/installs/nodejs/14.15.4/.npm/bin/yarn
      npm: 6.14.10 - ~/.asdf/installs/nodejs/14.15.4/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@triptec/createstacknavigator-%7C-react-navigation

Click "Go to Profile" and then click "Go back" and you should see the error with the warning in your console.

Problem with snack is that it does not show any warnings but running the same code locally I get the " Warning: Can't perform a React state update on an unmounted component" warning

I think the problem is in https://github.com/expo/expo/blob/master/packages/expo-permissions/src/PermissionsHooks.ts

and specifically on line 34 and 36.

A possible solution might be something like this?

```
export function usePermissions(
  type: PermissionType | PermissionType[],
  options: PermissionsOptions = {}
): [PermissionResponse | undefined, () => Promise<void>, () => Promise<void>] {
  let isSubscribed = true;
  const [data, setData] = useState<PermissionResponse>();
  const { ask = false, get = true } = options;
  const types = Array.isArray(type) ? type : [type];

  // note: its intentional to listen to `type`, not `types`.
  // when `type` is casted to an array, it possible creates a new one on every render.
  // to prevent unnecessary function instances we need to listen to the "raw" value.

  const askPermissions = useCallback(() => askAsync(...types).then((d) => {if(isSubscribed) setData(d)}), [type]);

  const getPermissions = useCallback(() => getAsync(...types).then((d) => {if(isSubscribed) setData(d)}), [type]);

  useEffect(() => {
    if (ask) {
      askPermissions();
    }

    if (!ask && get) {
      getPermissions();
    }
    return () => {
      isSubscribed = false;
    };
  }, [ask, askPermissions, get, getPermissions]);

  return [data, askPermissions, getPermissions];
}
```

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- resolve https://github.com/expo/expo/issues/12441

# Test Plan

- ran it in some code and unmounted the component after a settimeout

### CODE REVIEW

File: packages/expo-permissions/src/PermissionsHooks.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ export function usePermissions(
   type: PermissionType | PermissionType[],
   options: PermissionsOptions = {}
 ): [PermissionResponse | undefined, () => Promise<void>, () => Promise<void>] {
+  const isMounted = useRef(true);
```
Comment (bbarthec) [inline packages/expo-permissions/src/PermissionsHooks.ts:26]:
```suggestion
  const isMounted = useRef(true);
```
Why not to go with plain `useState<boolean>(false)` here? 🤔

Comment (EvanBacon) [reply packages/expo-permissions/src/PermissionsHooks.ts:26]: cuz that will cause the state to update, a ref doesn't.

**Review by bbarthec — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]

**Comment by brentvatne** [comment]
lgtm, although we're deprecating expo-permissions in favor of individual permissions requesters 😅
