### PR TITLE
[glass-effect] - Fix crash on UIGlassEffect init call on iOS 26 beta

### LINKED ISSUE #40911: Crash on iOS 26 when using new GlassEffect view (UIGlassEffect selector not found)
### Minimal reproducible example

soon

### Steps to reproduce

The app crashes natively before any JS runs.

NSInvalidArgumentException
+[UIGlassEffect effectWithStyle:]: unrecognized selector sent to class 0x1fdc02178

Top frames:

UIGlassEffect.__allocating_init
GlassView.setGlassStyle (GlassView.swift:49)
ExpoFabricView.updateProps (ExpoFabricView.swift:86)
-[ExpoFabricViewObjC finalizeUpdates:] (ExpoFabricViewObjC.mm:136)

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.21.1 - ~/.volta/tools/image/node/22.21.1/bin/node
      Yarn: 4.9.0 - ~/.volta/tools/image/yarn/4.9.0/bin/yarn
      npm: 10.9.4 - ~/.volta/tools/image/node/22.21.1/bin/npm
      Watchman: 2025.08.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/leonardocavalcante/.rvm/rubies/ruby-3.2.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^54.0.6 => 54.0.6 
      expo: ^54.0.22 => 54.0.22 
      expo-router: ^6.0.14 => 6.0.14 
      expo-updates: ^29.0.12 => 29.0.12 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: ^0.81.5 => 0.81.5 
      react-native-web: ^0.21.2 => 0.21.2 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.21.1 - ~/.volta/tools/image/node/22.21.1/bin/node
      Yarn: 4.9.0 - ~/.volta/tools/image/yarn/4.9.0/bin/yarn
      npm: 10.9.4 - ~/.volta/tools/image/node/22.21.1/bin/npm
      Watchman: 2025.08.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/leonardocavalcante/.rvm/rubies/ruby-3.2.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^54.0.6 => 54.0.6 
      expo: ^54.0.22 => 54.0.22 
      expo-router: ^6.0.14 => 6.0.14 
      expo-updates: ^29.0.12 => 29.0.12 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: ^0.81.5 => 0.81.5 
      react-native-web: ^0.21.2 => 0.21.2 
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Why
Closes #40911

We do not have a repro but someone reported that the crash is happening in beta iOS 26 versions.
https://www.reddit.com/r/SwiftUI/comments/1oqui1x/glasseffect_in_crushing_on_ios_26_public_beta

So this PR adds a runtime check if the class is available. This seems like iOS beta bug, but we should handle it. 

# How

Add runtime UIGlassEffect class check

# Test Plan

Test glass effect examples work in iOS 26 and renders regular view in iOS 18

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-glass-effect/ios/GlassContainer.swift [hunk 1]
```diff
@@ -16,9 +16,23 @@ public final class GlassContainer: ExpoView {
     addSubview(containerEffectView)
   }
 
+  // UIGlassEffect initialiser is failing for iOS 26 beta versions for some reason, so we need to check if it's available at runtime
+  // https://github.com/expo/expo/issues/40911
+  private func isGlassContainerEffectAvailable() -> Bool {
+    #if compiler(>=6.2)
```
Comment (alanjhughes) [inline packages/expo-glass-effect/ios/GlassContainer.swift:22]: Do we need both checks? 🤔

**Review by alanjhughes — APPROVED** [review]

File: packages/expo-glass-effect/ios/GlassContainer.swift (hunk 1 above)
Comment (intergalacticspacehighway) [reply packages/expo-glass-effect/ios/GlassContainer.swift:22]: not really, class string check is fine, just kept it thinking it'd be faster for unsupported os than string check 😅

**Comment by CavalcanteLeo** [comment]
thanks, that was me reporting it, several users crashing in production

**Comment by CavalcanteLeo** [comment]
I think the bug I reported here https://github.com/expo/expo/issues/40911 is related to iOS 26 beta 1. I’m not sure if that version includes the effectWithStyle method or not. A lot of people using my app are still on beta 1, though I’m not sure why.

we should not disable the feature at all, but disable this method if not available only, something like `respondsToSelector:@selector(effectWithStyle:)` may handle


Operating System
Build: `23A5260n`
Kernel `Version: Darwin Kernel Version 25.0.0: Fri May 30 19:47:39 PDT 2025; root:xnu-12377.0.81.0.3~311/RELEASE_ARM64_T8140`
Rooted: `no`

ipsw to download in case want to test: https://ipsw.dev/download/iPhone17,2/23A5260n

**Comment by intergalacticspacehighway** [comment]
@CavalcanteLeo good idea with the selector check. Can you try the latest changes in this PR as a patch with the user? This is surely some iOS beta bug.

**Comment by CavalcanteLeo** [comment]
I can, but it's not that fast, need to deploy a version to apple store, get approved, then email him
