### PR TITLE
fix(expo-network): emit correct state on Android disconnect

### LINKED ISSUE #37972: expo-network: Network state does not update correctly when device disconnects from the internet
### Minimal reproducible example

https://github.com/Zeptosec/expo-network-test

### Steps to reproduce

To reproduce the issue:
* Use expo-network hook **useNetworkState()** and log the output.
* Disconnect the device from the network by turning off mobile data and Wi-Fi.
* Look in the console for changes.

It seems that when you start the application with your device connected to the internet and then while being in the application turn it off the state updates, I do receive the event, but the event shows that I am still connected and the internet is reachable.

Also, if you open the application while the device is not connected to the internet then it prints showing that `isConnected = false` and `isInternetReachable = false`
```json
{"isConnected": false, "isInternetReachable": false, "type": "NONE"}
```
then when I turn on the Wi-Fi and the device connects to the internet I do receive another event which shows that the device is now connected to the internet
```json
{"isConnected": true, "isInternetReachable": true, "type": "WIFI"}
```
and after that if I again turn off the Wi-Fi I receive the same event as above. So the library detects that network status has changed but it emits the wrong status when disconnecting from the network. When connecting to the network it updates correctly.

I have though maybe it's the timing issue I've tried waiting for a few minutes, but I did not receive any further updates about the network status.

I don't have a physical iOS device, so I have tried in iOS simulator, but I don't know how accurate are the results from the simulator because I had to turn off mac Wi-Fi in order for the simulator network state to change, but the results I got were opposite to what I've experienced on android device. When I opened the simulator the network state was connected, but when I disconnected the status changed to disconnected and when I connected back to Wi-Fi I received another event with status disconnected. There was one event showing that I did connect to the internet as shown in video example, but it's too inconsistent.

I've also tried the same example with [@react-native-community/netinfo](https://www.npmjs.com/package/@react-native-community/netinfo) on android only and I didn't have any problems that I wrote above. For now I'll be using [@react-native-community/netinfo](https://www.npmjs.com/package/@react-native-community/netinfo) instead of expo-network I just wanted to report an issue that I had.

Thank you for your time.

| Property               | Value                                        |
|--------------------|----------------------------------|
| Device Model       | Samsung Galaxy S21 Ultra 5G |
| Android Version   | 15                                             |
| One UI Version     | 7.0                                            |

https://github.com/user-attachments/assets/624bcbd3-84e9-4a9e-86df-d1ddc2a31909

| Property              | Value                                         |
|-------------------|-----------------------------------|
| Device                | IPhone 16 Pro                            |
| iOS                     | 18.3                                            |

https://github.com/user-attachments/assets/26dbddf3-4cac-44c1-a422-4c4477141036

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.7.0 - /opt/homebrew/bin/node
      npm: 11.4.2 - /opt/homebrew/bin/npm
      Watchman: 2025.03.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/user/.rvm/gems/ruby-3.2.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 33.0.1, 34.0.0, 35.0.0, 35.0.1, 36.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
        Android NDK: 29.0.13599879-beta2
    IDEs:
      Android Studio: 2025.1 AI-251.25410.109.2511.13665796
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.17 => 53.0.19 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.5 => 0.79.5 
    npmGlobalPackages:
      eas-cli: 16.14.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
npx expo-doctor@latest
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by gueroverdenwshq**
## Summary

Fixes #37972

When a device disconnects from the network on Android 13+, `expo-network`'s `addNetworkStateListener` emits a stale event reporting `isConnected: true` and `isInternetReachable: true` instead of the correct disconnected state. The issue has been open since July 2025, acknowledged by Expo maintainers, and has affected users on Samsung Galaxy S21 Ultra, Pixel 8, Galaxy A34, and Galaxy Tab S7+. The bug does not occur on iOS. Multiple users have switched to `@react-native-community/netinfo` as a workaround.

## Root cause

The original `onLost` callback called `asyncEmitNetworkState(DELAY_MS)`, which posts a 250ms-delayed runnable that re-queries `connectivityManager.activeNetwork`. On Android 13+, `activeNetwork` continues to return the just-lost `Network` object even **after** the 250ms delay, so `fetchNetworkState()` reads `network != null` → `isInternetReachable = true` → emits a stale "connected" event right after a disconnection.

## Fix

In `onLost`, compare the lost network against the current active network instead of blindly re-querying:

- If `activeNetwork == null` OR `activeNetwork == lostNetwork` → emit a disconnected state directly (no delay).
- If a different network is active (e.g. cellular fallback after a WiFi drop) → call `emitNetworkState()` to query its state.

`android.net.Network.equals()` compares by `netId`, so the identity check is reliable.

### Why the asymmetry vs `onAvailable`

A reviewer might reasonably ask: "Why doesn't `onLost` use the same `asyncEmitNetworkState(DELAY_MS)` pattern as `onAvailable`?"

The answer is that **the delay is exactly what causes the bug**. `onAvailable` works fine with a delay because by the time the delay fires, the new network is fully registered and `activeNetwork` returns it correctly. `onLost` cannot use the same pattern because `activeNetwork` returns the stale lost network even after the delay — re-querying simply re-reads stale data. The asymmetry is intentional and is documented inline in the code.

### Known minor trade-off

During a fast WiFi → cellular handover where `activeNetwork` is briefly stale, listeners may see a transient `{ isConnected: false, type: "NONE" }` event before the cellular `onAvailable` callback fires ~250ms later. This matches `@react-native-community/netinfo`'s behavior and is strictly better than the current bug (permanently stale `isConnected: true` on disconnection).

## Other changes

- Replaced empty `catch (e: SecurityException) {}` blocks with `Log.w(TAG, …, e)` so failures surface in `adb logcat` instead of being silently swallowed. Applied to both the new `onLost` handler and the existing `asyncEmitNetworkState` for consistency within the same file.

## Test plan

The fix is in native Kotlin code; `expo-network` has no existing Android test infrastructure (no `android/src/test/`, no gradle test deps), so standing up Robolectric for a single test was judged out of scope for a targeted bugfix. Verification is manual:

### Repro steps (from #37972)

1. In an Expo app, call `useNetworkState()` or `addNetworkStateListener(...)` and log the received state.
2. Open the app with the device connected to WiFi.
3. Disable WiFi (and mobile data) on the device.
4. **Before this fix:** listener fires with `{ type: "WIFI", isConnected: true, isInternetReachable: true }` — wrong.
5. **After this fix:** listener fires with `{ type: "NONE", isConnected: false, isInternetReachable: false }` — correct.
6. Re-enable WiFi. Listener fires with `{ type: "WIFI", isConnected: true, isInternetReachable: true }` — unchanged by this PR.

### Checklist

- [ ] Manually verified on a physical Android 13+ device (reviewers: please confirm on your test fleet, as I do not have access to the exact repro hardware listed in the issue)
- [ ] Manually verified WiFi → cellular handover emits a correct sequence of events (acknowledging the ~250ms transient blip documented above)
- [x] iOS code path unchanged (no iOS files touched)
- [x] API < 29 code path (`< Build.VERSION_CODES.Q`) in `fetchNetworkState()` unchanged
- [x] `onAvailable` behavior unchanged
- [x] `getNetworkStateAsync()`, `getIpAddressAsync()`, `isAirplaneModeEnabledAsync()` unchanged
- [x] CHANGELOG updated in `packages/expo-network/CHANGELOG.md` under `Unpublished › Bug fixes`

### CODE REVIEW

File: packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt [hunk 1]
```diff
@@ -31,15 +31,65 @@ class NetworkModule : Module() {
...
+      // Instead, compare the lost network against the active network. If they
+      // match (or activeNetwork is null), there is no replacement network and
+      // we emit a disconnected state directly. If a different network is
+      // active (e.g. cellular fallback after WiFi drop), emit its state.
+      //
+      // Note: android.net.Network.equals() compares by netId, so the identity
+      // check below is a reliable "same network" comparison.
+      //
+      // We still post to the main looper because sendEvent expects the main
+      // thread; we just skip the delay.
```
Comment (lukmccall) [inline packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt]:
```suggestion
      // We intentionally do NOT reuse asyncEmitNetworkState(DELAY_MS) here.
      //
      // The 250ms delay used by onAvailable cannot be applied to onLost. On
      // Android 13+, connectivityManager.activeNetwork continues to return the
      // just-lost Network object even after the delay. Re-querying it would
      // emit a stale "isConnected = true" event — the exact bug reported in
      // https://github.com/expo/expo/issues/37972. This behavior isn't
      // documented by AOSP as version-specific, so we apply this check
      // defensively on all API 29+ devices.
      //
      // Instead, we compare the lost network against the current active network.
      // If they match (or activeNetwork is null), there is no replacement 
      // network and we emit a disconnected state directly. If a different 
      // network is active (e.g. cellular), we emit 
      // its state instead.
      //
      // Note: android.net.Network.equals() compares by netId, so the check 
      // below is a reliable "same network" comparison.
      //
      // We still post to the main looper because sendEvent must run on the 
      // main thread; we just skip the artificial delay.
```

File: packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt [hunk 2]
```diff
@@ -31,15 +31,65 @@ class NetworkModule : Module() {
...
+          Log.w(TAG, "expo-network could not read network state in onLost: missing ACCESS_NETWORK_STATE permission", e)
+        } catch (e: Exception) {
+          // The runnable may outlive the module if the React context is torn
+          // down between ConnectivityManager.NetworkCallback firing and the
+          // posted runnable draining. In that case, the `connectivityManager`
+          // getter throws `ReactContextLost` (a RuntimeException) when it
+          // resolves `appContext.reactContext`. unregisterNetworkCallback only
+          // stops future callbacks — it cannot cancel an already-posted
+          // runnable — so we must catch teardown-time exceptions here to
+          // avoid crashing the host app's main thread.
```
Comment (lukmccall) [inline packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt]:
```suggestion
          // The runnable may outlive the module if the React context is torn
          // down between the ConnectivityManager.NetworkCallback firing and 
          // the posted runnable executing. In that case, the `connectivityManager`
          // getter throws `ReactContextLost` when it
          // attempts to resolve `appContext.reactContext`. Since 
          // unregisterNetworkCallback only prevents future callbacks and 
          // cannot cancel a runnable that is already in the queue, we must 
          // catch teardown-time exceptions here to avoid crashing the 
          // host app's main thread.
```

**Review by lukmccall — APPROVED** [review]
Looks good! Thanks for your contribution.
