### PR TITLE
[ios][expo-mail-composer] Prevent duplicate values in LSApplicationQueriesSchemes

### LINKED ISSUE #37695: expo-mail-composer duplicates LSApplicationQueriesSchemes entries on prebuild
### Minimal reproducible example

Upgrading from Expo SDK 52 to 53 automatically adds `expo-mail-composer` to the plugins array in `app.json`.

After running `npx expo prebuild`, the plugin correctly adds values to `Info.plist` under `LSApplicationQueriesSchemes`.

The problem is that each time I run `npx expo prebuild`, the same values are added again, resulting in duplicates in `Info.plist`.

I believe this may be related to this script, which adds the keys without checking for existing values:
https://github.com/expo/expo/blob/main/packages/expo-mail-composer/plugin/src/withMailComposer.ts

```json 
{
  "expo": "^53.0.0",
  "expo-mail-composer": "~14.1.5",
  "@expo/config-plugins": "~10.0.0"
}
```

### Steps to reproduce

Run `npx expo prebuild`

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.16.0 - ~/.nvm/versions/node/v22.16.0/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.16.0/bin/npm
    Managers:
      CocoaPods: 1.14.2 - /Users/---/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2024.3 AI-243.26053.27.2432.13536105
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^53.0.0 => 53.0.13 
      expo-updates: ~0.28.15 => 0.28.15 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.4 => 0.79.4 
    npmGlobalPackages:
      eas-cli: 16.9.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
13/15 checks passed. 2 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: icon, orientation, splash, ios, android, plugins. 

Advice:
Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  Untested on New Architecture: ---
  Unmaintained: ---
  No metadata available: ---
Advice:
Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

2 checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by huextrat**
# Why

fixes: https://github.com/expo/expo/issues/37695

The expo-mail-composer plugin was unconditionally appending all mail client URL schemes to the `LSApplicationQueriesSchemes` array in the iOS Info.plist, which could result in duplicate values when other plugins also add schemes. This could lead to unnecessary bloat in the Info.plist and potential conflicts.

# How

- Extract existing schemes with fallback to empty array
- Create a Set for efficient duplicate checking
- Filter mailClientURLs to only include schemes not already present
- Preserve existing array order while appending new values

# Test Plan

# Checklist

- [X] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-mail-composer/plugin/src/withMailComposer.ts [hunk 1]
```diff
@@ -32,11 +32,13 @@ const mailClientURLs: string[] = [
...
   return withInfoPlist(config, (config) => {
-    config.modResults.LSApplicationQueriesSchemes = [
-      ...(config.modResults.LSApplicationQueriesSchemes ?? []),
-      ...mailClientURLs,
+    const existingSchemes = config.modResults.LSApplicationQueriesSchemes ?? [];
+    const existingSet = new Set(existingSchemes);
+    const newSchemes = [
+      ...existingSchemes,
+      ...mailClientURLs.filter((scheme) => !existingSet.has(scheme)),
     ];
```
Comment (vonovak) [inline packages/expo-mail-composer/plugin/src/withMailComposer.ts]:
```suggestion
    const newSchemes = [...new Set([...existingSchemes, ...mailClientURLs])]
```

thank you for the PR, this feels a little more straightforward

**Review by vonovak — CHANGES_REQUESTED** [review]

File: packages/expo-mail-composer/plugin/src/withMailComposer.ts (hunk 1 above)
Comment (huextrat) [reply packages/expo-mail-composer/plugin/src/withMailComposer.ts]: Absolutely, I have updated the code

**Review by vonovak — CHANGES_REQUESTED** [review]
Please rebuild the files as you did before, thank you

**Review by vonovak — APPROVED** [review]

**Comment by vonovak** [comment]
Thank you!
