### PR TITLE
[core][ios] Fix random conversion errors when converting JavaScript floating-point numbers to `Swift.Float`

### LINKED ISSUE #29036: [expo-video] Unable to set playbackRate on iOS
### Minimal reproducible example

https://github.com/tslater/reproduce-expo-video-playbackrate-error

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Anytime I set the playbackRate like this: `player.playbackRate = 0.7;` I get the following error:
```
ERROR  Error: FunctionCallException: Calling the 'set' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:87)
→ Caused by: ArgumentCastException: The 2nd argument cannot be cast to type Float (at ExpoModulesCore/JavaScriptUtils.swift:40)
→ Caused by: CastingException<Float>: Cannot cast 'Optional(0.9)' to Float (at ExpoModulesCore/DynamicRawType.swift:27)
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
      npm: 10.8.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/sl8r/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.3, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-22 | Intel x86_64 Atom, android-32 | Google APIs ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.8
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/29036

Fixes a conversion error, which would be thrown when setting some specific numbers (eq. 0.7 which is actually something like 0.6999999993) as `playbackRate` or `volume`. Conversion fails because JS sends the value as a Double, and for some precisions the conversion using `floatValue as? Double` returns null

# How

Made all of the Property Float types Double.

# Test Plan

Tested in BareExpo on iOS 17.5

### CODE REVIEW

**Comment by tslater** [comment]
@behenate Is there an easy way to test this? or not until then next release?

**Comment by behenate** [comment]
@tslater This should be includes as a part of SDK-51, but we have to merge it first. If you want to test it now, you can `patch-package` expo-video with changes from this PR

**Review by tsapeta — COMMENTED** [review]
I'm fine with this change, although it might be a good idea to just add support for auto-conversion between Float and Double here https://github.com/expo/expo/blob/0cb8c0a10d5f9bb4446fe701673a25ce7b62b9f6/packages/expo-modules-core/ios/Core/DynamicTypes/DynamicRawType.swift#L19-L21

**Review by lukmccall — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by hirbod** [comment]
@behenate @tsapeta we're still seeing this crash on iOS 17.5.1 and iPhone 12 Pro
Seems like to happen when we set `currentTime`. But I need to verify where it happens exactly.

Screenshot 2024-09-04 at 10 58 28


```
└─ expo-app@workspace:apps/expo
   └─ expo@npm:51.0.32 (via npm:~51.0.32)
➜  drakula git:(refactor/ios-expo-video) yarn why expo-modules-core
└─ expo@npm:51.0.32
   └─ expo-modules-core@npm:1.12.24 (via npm:1.12.24)
```

File: packages/expo-modules-core/ios/Core/DynamicTypes/DynamicRawType.swift [hunk 1]
```diff
@@ -19,6 +19,10 @@ internal struct DynamicRawType<InnerType>: AnyDynamicType {
     if let value = value as? InnerType {
       return value
     }
+    // Sometimes conversion from Double to Float will fail due to precision losses. We can accept them though.
+    if let value = value as? Double, wraps(Float.self) {
+      return Float(value)
+    }
```
Comment (tsapeta) [inline packages/expo-modules-core/ios/Core/DynamicTypes/DynamicRawType.swift:25]: Actually I think this is no longer necessary – I recently introduced a separate dynamic type for numbers, see https://github.com/expo/expo/blob/main/packages/expo-modules-core/ios/Core/DynamicTypes/DynamicNumberType.swift
