### PR TITLE
[doctor] Don't match on stderr prefix on deep dep check

### LINKED ISSUE #28545: expo-doctor has a non fatal error in 51.*.*
### Summary

npx
> expo-doctor

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
...
✖ Check that native modules do not use incompatible support packages
Unexpected error while running 'Check that native modules do not use incompatible support packages' check:
Error: Failed to find dependency tree for @unimodules/core: npm explain @unimodules/core --json exited with non-zero code: 1
✖ Check for legacy global CLI installed locally
Unexpected error while running 'Check for legacy global CLI installed locally' check:
Error: Failed to find dependency tree for expo-cli: npm explain expo-cli --json exited with non-zero code: 1
✔ Check that native modules use compatible support package versions for installed Expo SDK

running those individual commands gives the following:
npm error No dependencies found matching @unimodules/core
{
  "error": {
    "code": null,
    "summary": "No dependencies found matching @unimodules/core",
    "detail": ""
  }
}

npm error No dependencies found matching expo-cli
{
  "error": {
    "code": null,
    "summary": "No dependencies found matching expo-cli",
    "detail": ""
  }
}

### What platform(s) does this occur on?

Web

### SDK Version

51.0.0-preview.8

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 4.1.1 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.6.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
    npmGlobalPackages:
      eas-cli: 7.8.5
    Expo Workflow: managed

### Minimal reproducible example

running npx expo-doctor. i don't have a minimal reproducable project as this happens for any project regardless .

### PR DESCRIPTION
**Pull request by keith-kurak**
# Why

Fixes https://github.com/expo/expo/issues/28545, which presents itself on the most recent NPM versions. Somewhere between 10.2 and 10.6, the stderr prefix changed from `npm ERR!` to `npm error`. The deep dependency check code was matching on `/npm ERR! No dependencies found matching/` to detect that there's no matching dependencies, so it broke all deep dep checks on these later versions.

# How
Changed the match to `/No dependencies found matching/`. Since we request the JSON output from `npm explain`, which also identifies that no results, thought about going after that, but it's really just matching against the same string, so 

Example:
```
npm explain expo-cli --json
npm error No dependencies found matching expo-cli
{
  "error": {
    "code": null,
    "summary": "No dependencies found matching expo-cli",
    "detail": ""
  }
}
```

Also added some debug logging to the `explainDependencies` code so we can get a little more info if these commands fail in the future (there's been other hard-to-detect issues before due to node setup weirdness).

# Test Plan
No more errors on those checks with npm 10.7:
image

No errors on those checks still with npm 10.7
image

Also, still picks up issues if I install one of the dependencies those checks detects.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-doctor/src/utils/explainDependencies.ts [hunk 1]
```diff
@@ -31,7 +32,7 @@ async function explainAsync(
     return JSON.parse(stdout);
   } catch (error: any) {
     if (isSpawnResult(error)) {
-      if (error.stderr.match(/npm ERR! No dependencies found matching/)) {
+      if (error.stderr.match(/No dependencies found matching/)) {
```
Comment (byCedric) [inline packages/expo-doctor/src/utils/explainDependencies.ts:35]: Maybe nice to add a (e2e) test to support this, and warn us if this breaks in the future again 😄

**Review by byCedric — APPROVED** [review]
Left 1 comment, but looks good to me!

**Comment by saviocmc** [comment]
Hi! I was working on a pull request for this yesterday and saw yours just now.
I think this change should also cover the npm error handling in here:

https://github.com/expo/expo/blob/0a7f234009205ec0e55276a30ad5373555c2b15b/packages/create-expo/src/utils/npm.ts#L163

as the `npm ERR!` string is also hardcoded there

**Comment by saviocmc** [comment]
> Hi! I was working on a pull request for this yesterday and saw yours just now.
> I think this change should also cover the npm error handling in here:
> 
> https://github.com/expo/expo/blob/0a7f234009205ec0e55276a30ad5373555c2b15b/packages/create-expo/src/utils/npm.ts#L163
> 
> as the `npm ERR!` string is also hardcoded there

As this PR was merged now, should I submit a new PR for this?

**Comment by keith-kurak** [comment]
@saviocmc sorry, I was confused if your PR was for `expo-doctor` or `create-expo`. If you're working on a PR to fix this in `create-expo`, it'd be good to have a separate PR for that. Link to it here when ready and I'll take a look. As far as I know, `create-expo` is the only other package that has a check matching on `npm ERR!`, that that PR might cover everything else.
