### PR TITLE
[file-system] Fix OOM when calculating md5

### LINKED ISSUE #43962: File.md5 causes OOM with large files and no way to download a file with support to abort/cancel the request with new expo-file-system without blocking the JS thread
### Minimal reproducible example

https://github.com/vr7bd/expo-file-system-oom-repro

### Steps to reproduce

1. Clone the repo
2. `npm install`
3. `npx expo run:android`
4. Test each of the 4 buttons

Additional info can be found in the repo. The repo was created using AI and verified by me.

### Environment

```text
expo-env-info 2.0.11 environment info:
  System:
    OS: macOS 15.7.3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.15.0 - ~/Library/pnpm/node
    npm: 10.9.2 - ~/Library/pnpm/npm
  Managers:
    CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2025.3 AI-253.30387.90.2532.14935130
  npmPackages:
    expo: ~55.0.6 => 55.0.6
    react: 19.2.0 => 19.2.0
    react-native: 0.83.2 => 0.83.2
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
npx expo-doctor@latest
Running 17 checks on your project...
16/17 checks passed. 1 checks failed. Possible issues detected:

✖ Check native tooling versions
Your Expo SDK version 55 is not compatible with Xcode 16.4.0. Required Xcode version: >=26.0.0.

1 check failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by barthap**
## Why

Fixes #43962 (issue 1)

The `md5` property on `FileSystemFile` reads the entire file into memory before hashing, which causes out-of-memory crashes for large files on both iOS and Android.

## How

Changed both iOS and Android implementations to use streaming/chunked reading (8KB buffer) instead of loading the full file contents into memory at once:

- **Android**: Replaced `it.readBytes()` with a loop using `stream.read(buffer)` and `md.update()`
- **iOS**: Replaced `Data(contentsOf:)` with `FileHandle` chunked reads

> Aside, another problem is that `md5` is a property with synchronous getter, and hashing is blocking the JS thread

## Test Plan

- Test suite on both platforms (md5 correctness)
- No OOM on large files (>1GB)

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-file-system/ios/FileSystemFile.swift [hunk 1]
```diff
@@ -53,8 +53,17 @@ internal final class FileSystemFile: FileSystemPath {
   var md5: String {
     get throws {
       return try withCorrectTypeAndScopedAccess(permission: .read) {
-        let fileData = try Data(contentsOf: url)
-        let hash = Insecure.MD5.hash(data: fileData)
+        let bufferSize = 65536
+
+        let handle = try FileHandle(forReadingFrom: url)
+        defer { try? handle.close() } // Modern close throws
```
Comment (barthap) [inline packages/expo-file-system/ios/FileSystemFile.swift]:
```suggestion
        defer { try? handle.close() }
```

**Review by lukmccall — APPROVED** [review]
