### PR TITLE
[ios][camera] Fix dead or dark frames when video starts

### LINKED ISSUE #23130: [iOS] Preview flickering and darkened videos on iOS when recording video
### Minimal reproducible example

https://snack.expo.dev/@blimpapp/black-frames-example

### Summary

When starting a video recording the preview flickers black and sometimes the first frames of the result video are darkened or even black. I've found the similar issue here: https://github.com/expo/expo/issues/1057 but none of the workarounds work for me. I also tried patching with this PR: https://github.com/expo/expo/pull/16290/files but this didn't work too. 

I've tried debugging it a bit and it is possible that the flickering happens here:
```
- (void)setupMovieFileCapture
{
  AVCaptureMovieFileOutput *movieFileOutput = [[AVCaptureMovieFileOutput alloc] init];

  if ([_session canAddOutput:movieFileOutput]) {
    [_session addOutput:movieFileOutput];
    _movieFileOutput = movieFileOutput;
  }
}
```
Maybe this function should be called earlier, not just before starting the recording? `react-native-visual-camera` calls this when setting props, not starting the recording.

Expected behaviour:
- the preview doesn't flicker black
- the first frames of the resulting video are not darkened

Actual behaviour: 
- the preview flickers black when starting the video
- the first frames of the resulting video are sometimes darkened or even black

I'm also attaching a result video. You can see that the first frames are darkened.

https://github.com/expo/expo/assets/6280457/f7e5f39f-6ae2-4e4b-b2aa-488dd252c145

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/Projects/blimp-reactnative/node_modules/.bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/angelikaserwa/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.11 => 0.71.11
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.0
    Expo Workflow: bare

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #23130

# How
Some session configuration was happening off the `sessionQueue`. This causes the preview to be blocked. The same issue occurs when starting bar code scanner but will need to be fixed there. 

# Test Plan
Tested in bare expo.

### CODE REVIEW

File: packages/expo-camera/ios/EXCamera/EXCamera.m [hunk 1]
```diff
@@ -715,13 +716,11 @@ - (void)startSession
     [self onMountingError:@{@"message": @"Camera permissions not granted - component could not be rendered."}];
     return;
   }
-  EX_WEAKIFY(self);
-  dispatch_async(_sessionQueue, ^{
-    EX_ENSURE_STRONGIFY(self);
-
+  dispatch_async(self.sessionQueue, ^{
```
Comment (tsapeta) [inline packages/expo-camera/ios/EXCamera/EXCamera.m:719]: I'm afraid that we can't just avoid weakifying – this may lead to some other issues that may come up at some later point (including memory leaks).

Comment (alanjhughes) [reply packages/expo-camera/ios/EXCamera/EXCamera.m:719]: Not sure why we need it here. The only thing that can happen is we extend the life of self. The queue will not retain the blocks. Just run through them until it's empty.

Comment (alanjhughes) [reply packages/expo-camera/ios/EXCamera/EXCamera.m:719]: Maybe objc works differently. I can put them back

**Review by tsapeta — APPROVED** [review]

**Comment by jacobjonsson** [comment]
Appreciate you all fixing this issue!

Do you have updates for when you think an update could be published?

**Comment by tsapeta** [comment]
@jacobjonsson Sorry to keep you waiting, I've just published `expo-camera@13.4.3`, please let us know if it solves the issue for you. Note that this is not included in Expo Go, we will probably do the release soon but I can't promise anything.

**Comment by jacobjonsson** [comment]
@tsapeta appreciate you publishing it so quickly.

The issue got slightly better but unfortunately, there is still a noticeable dark flicker when calling `recordAsync`.

**Comment by Kieraano** [comment]
As per the comment above: this release is an improvement but the issue isn't quite gone yet.

It's still not at the point where Expo Camera could be used for video recording in a production iOS app.
This issue does need a little more attention to get it across the line.

Tested on a fresh dev build using iPhone 12 Pro and Expo Camera 13.4.4

The black flash persists when calling recordAsync() for both the front and back camera.

**Comment by ChristopherGabba** [comment]
I am also still experiencing this issue consistently in v13.4.4. 

How is this not a total deal killer for this camera package? The camera flickers black on every resolution still for a second or two. Apart from that massive issue, the package seems to work great.

**Comment by flyingL123** [comment]
@ChristopherGabba @DomGarza do you know if this is fixed? Seems there are a lot of separate issues for the same issue in this repo, lots of which are closed and marked as resolved, but I am confused because I still see this issue occurring consistently for every video I record on iOS. The screen flashes to black very quickly right after calling `recordAsync`, and then the first few frames of the recorded video are very dark.

**Comment by ChristopherGabba** [comment]
@flyingL123 Not sure, I removed the package and went with React-native-vision-camera

**Comment by flyingL123** [comment]
@ChristopherGabba have you run into any issues with that?

**Comment by ChristopherGabba** [comment]
No, works well for my use case
