### PR TITLE
[expo-document-picker] Prevent crashing when picking folder

### LINKED ISSUE #8837: [expo-document-picker] iOS app crashes on GarageBand project (.band) files
## 🐛 Bug Report

DocumentPicker.getDocumentAsync crashes on picking GarageBand project (.band) file types

### Environment
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.5

npm package versions:
"expo-document-picker": "8.1.0",
"expo": "37.0.12",

The app is targeted for iOS

### Reproducible Demo

https://snack.expo.io/@illesg/document-picker-demo

### Steps to Reproduce

Press Select document, then try to select the document (empty.band) attached to this issue

### Expected Behavior vs Actual Behavior

The app crashes, crashlog attached (crashlog.crash)

[expo-document-picker-crash.zip](https://github.com/expo/expo/files/4787045/expo-document-picker-crash.zip)

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/8837.

# How

Some files can be interpreted as a folder. For example the `.band` file is a good example of this. For those files, we should get file size differently, cause otherwise, it will crash the application.

# Test Plan

- NCL ✅ (tested with `.pdf`, `.band`, `.txt`)

# Changelog

- Fixed `getDocumentAsync` crashing when picking a folder on iOS.

### CODE REVIEW

File: packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m [hunk 1]
```diff
@@ -164,4 +162,34 @@ - (void)documentPickerWasCancelled:(UIDocumentPickerViewController *)controller
   _reject = nil;
 }
 
++ (unsigned long long int)getFileSize:(NSString *)path error:(NSError **)error
```
Comment (tsapeta) [inline packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m:165]: `long long int` is the same as `long long`
And why not `NSNumber`?

```suggestion
+ (unsigned long long)getFileSize:(NSString *)path error:(NSError **)error
```

File: packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m [hunk 2]
```diff
@@ -164,4 +162,34 @@ - (void)documentPickerWasCancelled:(UIDocumentPickerViewController *)controller
...
+  
+  // The path is pointing to the folder
+  NSArray *contents = [[NSFileManager defaultManager] contentsOfDirectoryAtPath:path error:error];
+  if (*error) {
+    return 0;
+  }
+  
+  NSEnumerator *contentsEnumurator = [contents objectEnumerator];
+  NSString *file;
+  unsigned long long int folderSize = 0;
```
Comment (tsapeta) [inline packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m:184]:
```suggestion
  unsigned long long folderSize = 0;
```

**Review by tsapeta — APPROVED** [review]

File: packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m (hunk 1 above)
Comment (lukmccall) [reply packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m]: > Why not `NSNumber`?

cause `fileAttributes.fileSize` is `unsigned long long` and I don't want to box it in  the `getFileSize` function.
