### PR TITLE
[video][ios] Fix safe area insets not updating for native controls

### LINKED ISSUE #30722: [expo-video] Native controls insets don't update when view moves
### Minimal reproducible example

https://github.com/joeporpeglia/expo-video-controls-inset-repro

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Insets are automatically applied to the native controls when `VideoView` overlaps with safe areas on initial render. If the view moves after this initial render, the insets don't update (e.g. if rendered inside a bottom sheet that slides vertically). Ideally there would be some way to trigger re-calculation for these insets, or disable them completely.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/joeporpeglia/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 23, 24, 26, 29, 31, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.23 => 51.0.23
      expo-router: ~3.5.19 => 3.5.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by behenate**
# Why

Safe area insets for the native controls are not updating when view moves from underneath the notch.
Fixes https://github.com/expo/expo/issues/30722

# How

Forces re-update of the native controls when the insets for a view change. The solution is kinda ugly, but nothing else I've tried has worked.

# Test Plan

Tested in BareExpo and the repro app from the issue.

### CODE REVIEW

File: packages/expo-video/ios/VideoView.swift [hunk 1]
```diff
@@ -197,4 +197,11 @@ public final class VideoView: ExpoView, AVPlayerViewControllerDelegate {
     playerViewController.beginAppearanceTransition(self.window != nil, animated: true)
     #endif
   }
+
+  public override func safeAreaInsetsDidChange() {
+    super.safeAreaInsetsDidChange()
+    // This is the only way that I (@behenate) to force re-calculation of the safe-area insets for native controls
```
Comment (lukmccall) [inline packages/expo-video/ios/VideoView.swift:203]:
```suggestion
    // This is the only way that I (@behenate) found to force re-calculation of the safe-area insets for native controls
```

**Review by lukmccall — APPROVED** [review]
