### PR TITLE
[IAP][ios] no more extra request on purchaseItemAsync

### LINKED ISSUE #10654: [expo-in-app-purchases] [ios] Products are not properly cached for purchase flow
### Summary of Issue 
On iOS, `purchaseItemAsync` checks if a cached product has been already fetched [here](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L86). However, the method then continues to re-fetch the product [here](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L95) - rendering the caching process useless, submitting an extra network call (thus incurring additional delay until the purchase flow appears to the end-user) and creating an inconsistency with the android implementation which does [pull the product from the cache](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java#L140).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
react-native-unimodules@0.11.0
expo-in-app-purchases@9.1.0
```
 
### Steps to Reproduce
on iOS:
```js
await InAppPurchases.getProductsAsync("your.sku");
await InAppPurchases.purchaseItemAsync("your.sku"); // Causes a re-fetch, although the product should be in the cache.
```

#### Expected:
After fetching a product, it should be cached and reused during purchase.
#### Actual:
[The product is verified to be cached](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L86) but [is still re-fetched](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L92).

### Suggested Solution
1. Instead of caching the fetched product IDs (`_retrievedItems`), cache the actual product object like the current Android implementation.
1. Inside `purchaseItemAsync`, pull the product from the cache instead of refetching it and directly start the purchase flow.

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/10654

# How

- Instead of only caching product IDs, cache the entire `SKProduct`
- If object in cache- send straight to `purchase` method
- Otherwise, reject promise (same behavior as before, no breaking change)

Some nice side effects:
- `handlePurchase` and `handleQuery` methods are no longer necessary
- no longer need to keep track of whether we are querying products or not
- fewer divergent code paths
- faster purchase flow

One change to note is that we no longer inform the user that a product is not available if they attempt to purchase one that doesn't exist ([this deleted code](https://github.com/expo/expo/compare/@cruzach/iap-fixes/10654?expand=1#diff-65514672f55b6d866d36a8831be6887d2d8ef96ad56a258a8ed39796e54f36ddL163-L166)). But users should be first querying products with `getProductsAsync`, and using those resulting IDs for purchase. If a product identifier wasn't valid, it isn't returned from that method (and isn't cached in `cachedProducts `, so `purchaseItemAsync` would reject). This matches the Android implementation, and also fails _earlier_ than it would have before (previously, users could attempt to purchase "bad" IDs because we added all requested IDs to `retrievedItems`, _now_ we only add valid IDs to our cache, so we're keeping users from making that mistake).

# Test Plan

Tested on NCL, purchasing products work like it did before

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m [hunk 1]
```diff
@@ -5,11 +5,10 @@
 @interface EXInAppPurchasesModule ()
 
 @property (weak, nonatomic) UMModuleRegistry *moduleRegistry;
-@property (nonatomic, assign) BOOL queryingItems;
 @property (nonatomic, weak) id <UMEventEmitterService> eventEmitter;
 @property (strong, nonatomic) NSMutableDictionary *promises;
 @property (strong, nonatomic) NSMutableDictionary *pendingTransactions;
-@property (strong, nonatomic) NSMutableSet *retrievedItems;
+@property (strong, nonatomic) NSMutableSet *cachedProducts;
```
Comment (ide) [inline packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:11]:
```suggestion
@property (strong, nonatomic) NSMutableSet<SKProduct *> *cachedProducts;
```

**Review by ide — APPROVED** [review]
Yeah, this looks clearer. 

I would list this under Breaking Changes since it's an API change and see if the docs need to be updated as well.

**Comment by cruzach** [comment]
No docs update needed bc they actually already state this is req'd:

> Remember, you have to query an item's details via `getProductsAsync` and set the purchase listener before you attempt to buy an item.
