### PR TITLE
[router]: Fix creating/parsing URLs with array search params

### LINKED ISSUE #29457: paramsSerializer not support multiple same key
### Minimal reproducible example

https://github.com/hasanaktas/expo-router-search-params-bug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I have a project where I am trying to reflect the url structure on my site.

Unfortunately, the expo router does not support the following example structures.

```
?color=red&color=yellow&color=blue

//useLocalSearchParams result
//color='blue'

```

Expected Behavior

```
?color=red&color=yellow&color=blue

//useLocalSearchParams result
//color=['blue','red','yellow']
```

When working with URLs, there is the same problem on both web and mobile.

We also need to be able to set multiple values ​​to the same key. It currently only accepts string.string array should also accept

```
const router = useRouter()
router.setParams({
  color:'red'
})
    
//useLocalSearchParams result
color='red'

//newUrlSearch
?color=red
```

```
const router = useRouter()
router.setParams({
  color:['red','green','blue']
})
    
//useLocalSearchParams result
color=['red','green','blue']

//newUrlSearch
?color=red&color=green&color=blue
```

### Environment

  System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.10 => 51.0.10 
      expo-router: ~3.5.15 => 3.5.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by marklawlor**
# Why

Fix #29457

# How

Expo Router doesn't correctly handle array search params. Params could only be an array if set by `setParams`, but reloading the router would cause the param to revert back to a string version of the array.

For the web, there is no standard to array search params. W3 has a recommendation, but its upto the framework to choose their implementation. I've chosen to implement the most common JavaScript framework method, plus an additional TypeSafe feature.

## New Implementation

If a search param is present multiple times in the queryString, they will be grouped together as an Array.

```
/?test=1&test=2  -->  { test: ["1", "2"] }
/?test=1,2  -->  { test: "1,2" }
```

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-router/src/hooks.ts [hunk 1]
```diff
@@ -149,3 +149,28 @@ export function useLocalSearchParams<
...
+  const entries = Object.entries(params).flatMap(([key, value]) => {
+    if (global) {
+      if (key === 'params') return [];
+      if (key === 'screen') return [];
+    }
+
+    return Array.isArray(value) ? value.map((v) => [key, v]) : [[key, value]];
+  });
+
+  return Object.assign(new URLSearchParams(entries), {
```
Comment (EvanBacon) [inline packages/expo-router/src/hooks.ts:165]: Make readonly URLSearchParams its own class

File: packages/expo-router/src/hooks.ts [hunk 2]
```diff
@@ -149,3 +149,28 @@ export function useLocalSearchParams<
     })
   ) as RouteParams<TParams1, TParams2>;
 }
+
+export function useSearchParams({ global = false } = {}): URLSearchParams {
```
Comment (EvanBacon) [inline packages/expo-router/src/hooks.ts:153]: global needs to be immutable since changing it will break the rules of hooks

File: packages/expo-router/src/hooks.ts [hunk 3]
```diff
@@ -149,3 +149,28 @@ export function useLocalSearchParams<
...
+  // eslint-disable-next-line react-hooks/rules-of-hooks
+  const params = global ? useGlobalSearchParams() : useLocalSearchParams();
```
Comment (marklawlor) [inline packages/expo-router/src/hooks.ts:155]: Add `process.env.NODE_ENV === 'dev'` warning if `global` changes

File: docs/pages/router/reference/url-parameters.mdx [hunk 4]
```diff
@@ -316,6 +316,26 @@ export default function User() {
 }
 ```
 
+{/* prettier-ignore */}
+{/*
+REMOVE COMMENT WHEN https://github.com/expo/expo/pull/30268 IS PUBLISHED
```
Comment (amandeepmittal) [inline docs/pages/router/reference/url-parameters.mdx:321]:
```suggestion
TODO: REMOVE COMMENT WHEN https://github.com/expo/expo/pull/30268 IS PUBLISHED
```
Just a small suggestion. Let's add a Todo reference here if we're planning to keep this reference for some time.
