### PR TITLE
[expo-blur][android]: fix transition issues with RNScreens

### LINKED ISSUE #23239: [SDK 49 beta] [Android] expo-blur causes decreased performance and looks weird
### Minimal reproducible example

https://github.com/RRaideRR/expo-blur-sdk-49

### Summary

I noticed in my Android app some performance degradation when I tried out the new SDK 49. I tracked it down to expo-blur view. As hyped as I am for the new blurred view on the Android side, I cannot use it in my app because it causes the application to become significantly slower on low end and medium Android devices.  Plus: you will see that if I'm navigating away from a view, the blur view changes its colours in a strange way.

In my repro, I added also a 49SDK build APK and a 48SDK build APK so you can try it out faster by yourself :-). 

PS - on a side node: I noticed that the build size between these two builds differs (48 SDK build: 24.98 MB ; 49 SDK build: 28.22 MB --> so its gotten nearly 13% worse 😢)

SDK 49 build:
https://github.com/expo/expo/assets/3411292/31cab6ff-00f3-42a5-99aa-99b906f6b15c

SDK 48 build:
https://github.com/expo/expo/assets/3411292/ffaa8c1b-31c2-4c7f-bb19-56b528579e60

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0-beta.1 => 49.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.9
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by hannojg**
# Why

There is a bug when using expo-blur with the custom native component and using react-native-screens / native-stack. You can see the previous content while navigating / when navigating back there can be a flicker of the previous screen (not visible here but happens in a production app):

https://github.com/user-attachments/assets/f47610ed-eac7-4213-a636-a83ff575e1fe

You can try reproducing by just checking out this commit: https://github.com/expo/expo/pull/37904/commits/716a01740dc94315e5eb5f451a6cac63dd034b80

Fixes https://github.com/expo/expo/issues/23239

# How

The problem is that we need to configure a "root" for where the blur view should start _capturing the view hierarchy for its blur_. Now, currently, we just pick the app's absolute root.
However, when we are using react-native-screens, the root should much rather be the screen itself. **Otherwise we are capturing the whole app including the screen transitions.** This also slows down screen transitions as we have to re-run the blur calculation for each frame of the transition.

The code I added will try to find a screen in the view hierarchy, if it doesn't it will fallback to using the app root as it was before. 
The important part here is that we can only traverse the view hierarchy if the view got attached, so we have to wait for that event.
Here you can see the fixed version, which also feels much faster to navigate:

https://github.com/user-attachments/assets/6d4b4eda-3f5a-4d10-95d7-fa9c30ec15f6

> Note: BlurView just released a V3 where you explicitly need to configure a `<BlurTarget>` which would also be a solution to this problem - I opened a discussion [here](https://github.com/expo/expo/discussions/37905)

# Test Plan

I added an example case to the bare app. Is there anything else needed?

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by hannojg** [comment]
Opened up a follow up discussion here:

- https://github.com/expo/expo/discussions/37905

File: packages/expo-blur/android/src/main/java/expo/modules/blur/ExpoBlurView.kt [hunk 1]
```diff
@@ -19,27 +19,21 @@ class ExpoBlurView(context: Context, appContext: AppContext) : ExpoView(context,
...
   fun setBlurRadius(radius: Float) {
+    blurRadius = radius
+
+    if (!isBlurViewConfigured) return;
+
     when (blurMethod) {
       BlurMethod.NONE -> {
-        this.setBackgroundColor(tint.toBlurEffect(blurRadius))
+        this.setBackgroundColor(tint.toBlurEffect(radius))
       }
```
Comment (hannojg) [inline packages/expo-blur/android/src/main/java/expo/modules/blur/ExpoBlurView.kt]: Not sure about that change here. When its `BlurMethod.none` we were setting the _previous_ value as blur radius? that seems like a bug and I changed it but I might be wrong!

**Review by behenate — APPROVED** [review]
This was a long standing issue with `expo-blur` thanks for the fix! The code looks good to me.

File: packages/expo-blur/android/src/main/java/expo/modules/blur/ExpoBlurView.kt (hunk 1 above)
Comment (behenate) [reply packages/expo-blur/android/src/main/java/expo/modules/blur/ExpoBlurView.kt]: Yep, this looks like a bug to me as well

**Review by amandeepmittal — APPROVED** [review]
Docs change looks good, thanks!

File: apps/native-component-list/package.json [hunk 2]
```diff
@@ -47,6 +47,7 @@
     "@react-navigation/drawer": "^7.3.9",
     "@react-navigation/elements": "^2.3.8",
     "@react-navigation/native": "^7.1.6",
+    "@react-navigation/native-stack": "^7.3.21",
```
Comment (jakex7) [inline apps/native-component-list/package.json]: Testing in bare-expo was enough but we'd like to avoid adding native-stack to `native-component-list` as it's used in many places within different apps. Could you revert the changes made to NCL (package and native navigator) before merging this PR?

**Review by jakex7 — CHANGES_REQUESTED** [review]
Thank you for fixing it!

File: apps/native-component-list/package.json (hunk 2 above)
Comment (hannojg) [reply apps/native-component-list/package.json]: you mean for me to remove the commit that adds the example to the bare-app, or instead add native-stack to some other package.json? Or keep the change but just remove the package dep?

Comment (hannojg) [reply apps/native-component-list/package.json]: (happy to do either, just confused right now haha)

Comment (jakex7) [reply apps/native-component-list/package.json]: Sorry for the confusion 😄  I meant to remove the changes made in `apps/native-component-list`

Comment (hannojg) [reply apps/native-component-list/package.json]: Done!

Comment (jakex7) [reply apps/native-component-list/package.json]: Thank you!

**Review by jakex7 — APPROVED** [review]

**Review by jakex7 — CHANGES_REQUESTED** [review]
I've notice this PR made a regression where `blurMethod: "none"` is does not take effect  on initial render.

https://github.com/user-attachments/assets/ed6c432c-6fbe-4b2c-b277-26563e80e218

File: packages/expo-blur/android/src/main/java/expo/modules/blur/ExpoBlurView.kt [hunk 3]
```diff
@@ -88,4 +86,75 @@ class ExpoBlurView(context: Context, appContext: AppContext) : ExpoView(context,
...
     blurView.invalidate()
   }
+
+  override fun onAttachedToWindow() {
+    super.onAttachedToWindow()
+
+    // Now we can safely walk the parent hierarchy
+    if (!isBlurViewConfigured) {
+      configureBlurView()
+      isBlurViewConfigured = true
```
Comment (jakex7) [inline packages/expo-blur/android/src/main/java/expo/modules/blur/ExpoBlurView.kt]: Most likely it should be in reverse order. Otherwise `setBlurRadius, setBlurMethod and applyTint` will early-return and would not set it's values on `blurView`.
```suggestion
      isBlurViewConfigured = true
      configureBlurView()
```

**Comment by hirbod** [comment]
Thanks for fixing this. I still remember the impact it had on our app. On modals, it would even show a snapshot of the splash screen. Performance looks really good too!

**Comment by hannojg** [comment]
Ah good catch, does it look correct now?


https://github.com/user-attachments/assets/1eb8762d-74a8-48e1-8b7a-d9eedcb1d04b

**Review by jakex7 — APPROVED** [review]
Perfect, thank you!

**Comment by joaqo** [comment]
Thank you so much for this fix @hannojg! Do you know when it will be released? We just added a bunch of blur views to our next release which were hit by this issue, and are waiting on your release to do ours.

Or maybe some guidance on how to build this myself?

Thank you again!

**Comment by DanielAraldi** [comment]
Hey everyone, I was looking for this PR, haha. I notice that the community Blur continues to have this issue. I'll be fixing this issue in my library in the future. Thank you for the excellent description of the issue throughout the PR conversations.
