### PR TITLE
[package-manager][install-expo-modules] fix yarn v3 support

### LINKED ISSUE #26117: `npx install-expo-modules` fails with Yarn v3
### Summary

`npx install-expo-modules` fails when running in a project with Yarn v3.

Maybe related to https://github.com/expo/expo-cli/issues/4125

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.5.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/douglas.junior/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 30, 31, 33, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.12 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
› Updating your project...
› Installing expo packages...
> yarn add expo@^48.0.0 --non-interactive
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

While running add expo@^48.0.0 --non-interactive
> yarn add expo@>=48.0.0-0 <49.0.0 --non-interactive
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

While running add "expo@>=48.0.0-0 <49.0.0" --non-interactive
Uncaught Error Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:396526)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:396036)
    at YarnPackageManager._runAsync (/Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:348469)
    at YarnPackageManager.addWithParametersAsync (/Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:347397)
    at async installExpoPackageAsync (/Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:34:446727)
    at async runAsync (/Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:34:422819)
    at async /Users/douglas.junior/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:34:423030 {
  pid: 29039,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}
```

### Reproducible demo or steps to reproduce from a blank project

1. npx react-native init SampleProject
2. yarn set version stable
3. yarn install
4. npx install-expo-modules

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #26117

# How

- [install-expo-modules] yarn v3 does not enable interactive mode by default, we don't need the `--non-interactive` flag
- [package-manager] fix `versionAsync` returns empty string when silent=false and stdio=inherit

# Test Plan

- ci passed
- test install-expo-modules on yarn v1 and yarn v3 package managers

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by byCedric — APPROVED** [review]

File: packages/@expo/package-manager/src/node/BasePackageManager.ts [hunk 1]
```diff
@@ -67,17 +67,19 @@ export abstract class BasePackageManager implements PackageManager {
     return cwd;
   }
 
-  runAsync(command: string[]) {
+  runAsync(command: string[], options?: SpawnOptions) {
```
Comment (byCedric) [inline packages/@expo/package-manager/src/node/BasePackageManager.ts:70]: We might need to default to `options: SpawnOptions = {}`, since it's being spread regardless if it's `undefined` or not 😄 

```suggestion
  runAsync(command: string[], options: SpawnOptions = {}) {
```

Comment (Kudo) [reply packages/@expo/package-manager/src/node/BasePackageManager.ts:70]: the fun fact is that `{ ...undefined }` returns `{}`. but i think your even better and clear. will update accordingly. thanks!
