### PR TITLE
[ios] Don't call RCTPackagerConnection when it isn't available

### LINKED ISSUE #6487: ExpoKit ios Use of undeclared identifier 'RCTPackagerConnection'
### Environment

 Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.2.0 => 3.2.0 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

ExpoKit
### Steps to Reproduce
xcode archive ExpoKit Project

### Expected Behavior
build success

### Actual Behavior
Use of undeclared identifier 'RCTPackagerConnection'

--
If my comment out will work.
Maybe there is a problem with my _isDevModeEnabledForBridge?

/*
  if ([self _isDevModeEnabledForBridge:bridge]) {
    // Set the bundle url for the packager connection manually
    [[RCTPackagerConnection sharedPackagerConnection] setBundleURL:[bridge bundleURL]];
  }
*/

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Fixes #6487 

# How

So `RCTPackagerConnection` is available only when `RCT_DEV` constant is set to true - this is not a problem in Expo client because this flag is enabled on both Debug and Release modes in the entire workspace, but it isn't the case when using ExpoKit or building a shell app. Instead of changing the project settings (it requires users to make a change) we can use `DEBUG` constant here so that in ExpoKit projects `RCTPackagerConnection` will be called only when building in Debug mode.

# Test Plan

`shell_app_ios_build` passed on CI, I was able to archive ExpoKit project with this change applied locally.

### CODE REVIEW

File: ios/Exponent/Versioned/Core/EXVersionManager.m [hunk 1]
```diff
@@ -112,10 +112,12 @@ - (void)bridgeWillStartLoading:(id)bridge
      postNotificationName:EX_UNVERSIONED(@"EXReloadActiveAppRequest") object:nil];
   }];
 
+#if DEBUG || RCT_DEV
```
Comment (brentvatne) [inline ios/Exponent/Versioned/Core/EXVersionManager.m]: should we use this same macro for the header import?

Comment (tsapeta) [reply ios/Exponent/Versioned/Core/EXVersionManager.m]: No, we don't need to do that because this header is empty when `RCT_DEV` is defined, see https://github.com/facebook/react-native/blob/9b81232ed2cc2beaf06a34ffe2279612f435f931/React/DevSupport/RCTPackagerConnection.h#L12

**Review by sjchmiela — APPROVED** [review]
Thanks for adding the explanation! 👍
