### PR TITLE
[audio] Prevent unnecessary re-renders from `useAudioRecorderState`

### LINKED ISSUE #38253: [expo-audio] Performance issue - useAudioRecorderState causes the component to re-render infinitely
### Minimal reproducible example

Not require to have example. Issue becomes obvious if you see code bellow.

### Steps to reproduce

Just call `useAudioRecorderState` from react component add add a console log:
```
const data = useAudioRecorderState(recorder, 100)
console.log('render', data)
```
you will see that render never stops.

The problem with a hook.
It runs inteval and set a new object to state, that triggers react updates ([this line](https://github.com/expo/expo/blob/b3d8e736ccc7d73fa3457b098a42a432a408d0fa/packages/expo-audio/src/ExpoAudio.ts#L236)):

```
export function useAudioRecorderState(recorder: AudioRecorder, interval: number = 500) {
  const [state, setState] = useState<RecorderState>(recorder.getStatus());

  useEffect(() => {
    const int = setInterval(() => {
      setState(recorder.getStatus());
    }, interval);

    return () => clearInterval(int);
  }, [recorder.id]);

  return state;
}
```

The simplest fix is `setState(prev => isEqual(prev, next) ? prev: next)`
Better if we can prevent setState calling at all. Would be nice if we can avoid using isEqual and compare each prop.
The best if recorder has a subscription to state updates, and subscription can trigger setState. 
Any solution is good option, cause it makes real issues

Sorry, not a mobile developer and don't know this library.

Hope you will help fix it! Thank you.

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #38253

# How
Currently the `useAudioRecorderState` hook triggers a re-render on every update interval. This is unnecessary when the recorder is at rest and the values are not changing. The ideal solution is in native but the recording apis there don't provide the necessary hooks to do this the same way we do with the audio players. For now, a shallow state comparison works. I will follow up with a better solution. There was also a second issue where the state events were not emitting the url as a string so  it remained undefined.

# Test Plan
Bare-expo. State updates only when changed.

### CODE REVIEW

File: packages/expo-audio/src/ExpoAudio.ts [hunk 1]
```diff
@@ -233,7 +233,27 @@ export function useAudioRecorderState(recorder: AudioRecorder, interval: number
 
   useEffect(() => {
     const int = setInterval(() => {
-      setState(recorder.getStatus());
+      const newState = recorder.getStatus();
+
+      setState((prevState) => {
```
Comment (ycharniauski) [inline packages/expo-audio/src/ExpoAudio.ts:238]: I think it can be simplified:
```
setState((prev) => {
    const changed = prev.canRecord !== next.canRecord ||
      prev.isRecording !== next.isRecording ||
      prev.mediaServicesDidReset !== next.mediaServicesDidReset ||
      prev.url !== next.url ||
      prev.durationMillis !== next.durationMillis || // strict equal probably better
      Math.abs((prev.metering || 0) - (next.metering || 0)) > 0.1

    return changed ? next : prev
  })
```
And make sense compare durationMilis with === operator. Cause this value depends on interval and it will be always different if recording works I guess. I would say we should use === to compare metering also, to receive more smooth values, to avoid regression. The idea is to prevent rendering when recording not works

Comment (alanjhughes) [reply packages/expo-audio/src/ExpoAudio.ts:238]: It doesn't make sense to use strict equal here because there will always be a slight difference between the two values. The check sets a low threshold for what is considered a significant change.

**Review by chrfalch — APPROVED** [review]
LGTM!
