### PR TITLE
[document-picker] Handle nil MIME type

### LINKED ISSUE #16096: Choosing the same file in expo-document-picker crashes iOS simulator
### Summary

I'm facing an issue with `expo-document-picker` which is affecting only iOS simulator, on real device, there is no issue. When I select a file and then select the same file one more time, the app immediately crashes.

I have tried:
- to use a different iOS version (15.2, 15.0, 14.5) => no change
- to use the latest `expo-document-picker@10.1.1` from yesterday but it seems to be present in all `10.x.x` versions
- to use `expo prebuild` and debug the issue in Xcode, I saw `EXC_BAD_ACCESS` in the native `EXDocumentPickerModule.m` once it crashed but I don't have enough knowledge to fix it

Thank you for any help, I'm trying to solve it for a few days with no luck.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK 44

### Environment

```
Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

```javascript
export default function App() {
  let selectDocument = async () => {
    let file = await DocumentPicker.getDocumentAsync({});
    console.log(file.name);
  };

  return (
    <View style={styles.container}>
      <StatusBar style="auto" />
      <Button title="Upload file" onPress={selectDocument} />
    </View>
  );
}
```

Snack: https://snack.expo.dev/@jiri.orsag/document-picker-issue

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

I believe this fixes #16096

# How

This appears to have been caused by adding the MIME type field for iOS in #13702. `UTTypeCopyPreferredTagWithClass ` can return null, and we don't handle that in our MIME type conversion code.

There are two commits here with possible solutions:
1. Fall back to application/octet-stream if we can't figure out the MIME type.
2. Leave the `mimeType` field out entirely in the response if nil. Types already indicate that this field is optional.

I prefer the second approach but I'm open to either.

# Test Plan

Run the test app from #16096, reproduce by picking a keynote file (for example), then apply this fix manually to node_modules, rebuild, try again. 

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m [hunk 1]
```diff
@@ -186,14 +186,26 @@ - (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocum
     
   NSString *extension = [url pathExtension];
   NSString *mimeType = [EXDocumentPickerModule getMimeType:extension];
+  NSString *name = [url lastPathComponent];
+  NSString *uri = [newUrl absoluteString];
```
Comment (bbarthec) [inline packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m:190]:
```suggestion
```

File: packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m [hunk 2]
```diff
@@ -186,14 +186,26 @@ - (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocum
...
+               });
+  } else {
+    _resolve(@{
+               @"type": @"success",
+               @"uri": uri,
+               @"name": name,
+               @"size": @(fileSize)
+               });
+  }
+
```
Comment (bbarthec) [inline packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m:208]: Too much code repetition 👀 
```suggestion
  NSMutableDictionary *response = [@{
    @"type": @"success",
    @"uri": [newUrl absoluteString],
    @"name": [url lastPathComponent],
    @"size": @(fileSize)
  } mutableCopy];

  if (mimeType != nil) {
    response[@"mimeType"] = mimeType;
  }

   _resolve(response);

```

**Review by bbarthec — DISMISSED** [review]
Your preferred solution is a good one! 👍 
Approach of adding or not a property to the response is an solution we use in many other places 😁 

Add missing changelog too 😉
