### PR TITLE
[contacts] fix CNContactViewController presentation

### LINKED ISSUE #38775: Expo contacts presentFormAsync doesn't utilise formOptions
### Minimal reproducible example

https://snack.expo.dev/@tapajyoti/expo-contact-formoptions-not-working

### Steps to reproduce

```ts
import { presentFormAsync } from 'expo-contacts';

const editContact = () => {
  presentFormAsync(CONTACT_ID, undefined, {
    allowsActions: false,
    allowsEditing: false,
    cancelButtonTitle: 'Exit',
    isNew: false,
    message: 'Edit',
  });
```

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.3 - /opt/homebrew/bin/node
      Yarn: 4.4.1 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2025.06.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Android Studio: 2024.3 AI-243.22562.218.2431.13114758
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 15.0.14
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by vonovak**
# Why

This PR enhances the Contacts module functionality by fixing the contact form presentation.

closes #38775

# How

- fixed `ContactsViewController` initialization which was previously incorrect for existing contacts
- Updated documentation for `FormOptions` to be more accurate and added iOS platform tag
- Added error handling for missing view controllers in the iOS implementation

# Test Plan

- bare expo

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by vonovak** [comment]
* **#39004** <a href="https://app.graphite.dev/github/pr/expo/expo/39004?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/expo/expo/39004?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/expo-contacts/ios/ContactsModule.swift [hunk 1]
```diff
@@ -84,7 +84,7 @@ public class ContactsModule: Module, OnContactPickingResultHandler {
 
       if let identifier {
         if let foundContact = try? getContact(withId: identifier) {
-          controller = ContactsViewController.init(forNewContact: foundContact)
+          controller = ContactsViewController.init(for: foundContact)
```
Comment (alanjhughes) [inline packages/expo-contacts/ios/ContactsModule.swift]:
```suggestion
          controller = ContactsViewController(for: foundContact)
```
No idea why I used explicit the initializer here 😅 Let's remove it

**Review by alanjhughes — APPROVED** [review]
