### PR TITLE
[android][Linking] allow Linking.openUrl while app is foregrounded

### LINKED ISSUE #6058: [Linking][Android] Standalone app Deep Linking opened from app itself not working
### Environment

Expo CLI 3.3.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.12.0 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.3.0

Android Standalone App
(Expo Client works fine on both, iOS standalone works fine)

### Steps to Reproduce

[repo repro](https://github.com/cruzach/deep-links-issue)
Optionally, start a brand new tabs template project, configure [linking for standalone](https://docs.expo.io/versions/latest/workflow/linking/#in-a-standalone-app), implement necessary `react-navigation` paths, and try to navigate to a specific screen in the app, from the app itself. For example, creating an `onPress` in `HomeScreen` that navigates to the `Settings` screen with:
```
Expo.Linking.openURL(Expo.Linking.makeUrl("/settings/3"));
```

### Expected Behavior

Should be the same as the behavior in the Expo Client, namely, navigate to that specific screen/path

### Actual Behavior

Nothing happens. However, typing out the result of `Linking.makeUrl("/settings/3")` into the FireFox browser on an Android device *does* open the correct screen

Edit: on further inspection, it looks like the `Linking.addListener` isn't working on a standalone Android app. 

### Reproducible Demo

[repo repro](https://github.com/cruzach/deep-links-issue)

### PR DESCRIPTION
**Pull request by cruzach**
# Why

Closes #6058 
When a standalone app was already foregrounded, the incorrect key (the `scheme` rather than the published url) was being searched for in the `mManifestUrlToOptions` hashmap.
# How

Search for the appropriate URL in the hashmap

# Test Plan

Tested locally on `sdk-35` branch

### CODE REVIEW

**Comment by esamelson** [comment]
@cruzach thanks so much for digging into this 🙏  Have you verified that this doesn't break anything in the Expo client case? IIRC `Constants.INITIAL_URL` is null or `""` in the Expo client so I think this might break `openURI` in the client. We may need to check `Constants.isStandaloneApp()` here.

I would recommend testing a few common linking cases in both the client and a standalone app before landing this -- probably some list like
- Expo client: test `exp://<your app manifest url>` with app in foreground, in background, and closed
- Expo client: test `exp://<some other app manifest url>` with your app open in the foreground
- Standalone app: test `<scheme>://deep/link` with app in foreground, in background, and closed
- Both: test opening some other url (`tel://` maybe?) from your app

and make sure the initial URL is set correctly and the listener fires when expected in all cases. This code is pretty tough to modify without accidentally breaking something else so it's good to err on the side of testing more things.

**Comment by cruzach** [comment]
Good point, I had tested standalone but not in the Expo Client. Turns out this completely broke behavior in the client 😬 

- standalone app: test `<scheme>://deep/link` with app in foreground, in background, and closed, and multiple different links to different screens in the same app. The `Linking.addEventListener` listener doesn't fire in the case of a closed app, but that's due to the listener not being added yet, so that's expected
- Expo client: test exp://<some other app manifest url> with your app open in the foreground
- Both: test opening some other url (tel:// ) from app
- opening exp://exp.host/<your app manifest url> from another published experience opens the expo experience, not the standalone app
- Opening exp://exp.host/<your app manifest url> via Firefox with Expo Client closed opens up the expo experience
-

**Comment by cruzach** [comment]
Good point, I had tested standalone but not in the Expo Client. Turns out this completely broke behavior in the client 😬 With the new changes, you observe the following:

- standalone app: test `<scheme>://deep/link` with app in foreground, in background, and closed, and multiple different links to different screens in the same app. The `Linking.addEventListener` listener doesn't fire in the case of a closed app, but that's due to the listener not being added yet, so that's expected ✅
- Expo client: test `exp://<some other app manifest url>` with your app open in the foreground ✅
- Both: test opening some other url (`tel://` ) from app ✅
- opening `exp://exp.host/<your app manifest url>` from another published experience opens the expo experience, not the standalone app ✅
- Opening `exp://exp.host/<your app manifest url>` via Firefox with Expo Client closed opens up the expo experience ✅

The only iffy behavior is:
- if standalone app is in foreground and you open `exp://exp.host/<your app manifest url>`, the expo experience doesn't open and the standalone app will stay in the foreground
Although, how often is someone going to want to open their Expo experience from the standalone version of that same experience?

File: android/expoview/src/main/java/host/exp/exponent/kernel/services/linking/LinkingKernelService.java [hunk 1]
```diff
@@ -14,9 +14,11 @@ public LinkingKernelService() {
   }
 
   public void openURI(Uri uri) {
-    KernelProvider.getInstance().openExperience(
-        new KernelConstants.ExperienceOptions(uri.toString(), uri.toString(), null)
-    );
+    String manifestUrl = (Constants.INITIAL_URL != null && !Constants.INITIAL_URL.isEmpty()
```
Comment (esamelson) [inline android/expoview/src/main/java/host/exp/exponent/kernel/services/linking/LinkingKernelService.java]:
```suggestion
    String manifestUrl = (Constants.isStandaloneApp()
```
Both options would achieve the same thing but I think this is more meaningfully correct, & would not break in the future if for example we start including an `INITIAL_URL` in the client 🤷‍♂

**Review by esamelson — CHANGES_REQUESTED** [review]
Thanks for testing this so thoroughly! In a PR like this testing is definitely more than half the work. I agree that one iffy case is not a big deal because the use case is so weird. That said, just looking at this file I bet the problem is coming from `canOpenURI` and is probably a simple fix 😄 just need to check `Constants.isStandaloneApp()` before returning `true` with exp/exps scheme. Up to you if you want to do that in this PR or not.

I have one small code suggestion, but otherwise looks good to me 👍

**Review by esamelson — APPROVED** [review]

**Comment by cruzach** [comment]
So now just merge and cherry-pick to the `sdk-35` branch?

**Comment by esamelson** [comment]
yep!
