### PR TITLE
[Haptic] Fixed Haptic errors

### LINKED ISSUE #3224: Bug on Haptic.notification(Haptic.NotificationFeedbackType.Error)
### Environment

Iphone X
SDK 32

### Steps to Reproduce

Write the following code for example in an onPress button props:
```
Platform.OS === "ios" &&
        Haptic.notification(Haptic.NotificationFeedbackType.Error);
```
### Expected Behavior

Haptic notification happens

### Actual Behavior

This error happens:
`Error: The method or property Haptic.notification is not available on this platform, are you sure you ve linked all the native dependencies properly?
`

### PR DESCRIPTION
**Pull request by EvanBacon**
* Added Haptic unit tests
* Ensure the native module is defined.
* Fixed logic for notification method

*Edited by @tsapeta*:
Fixes #3224

### CODE REVIEW

**Comment by EvanBacon** [comment]
#3224

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+          try {
+            await Haptic.notification(type);
+          } catch (error) {
+            resultingError = error;
+          }
+          expect(resultingError).toBeUndefined();
+        }
+      });
+    });
+  } else {
```
Comment (tsapeta) [inline packages/expo/src/__tests__/Haptic-test.ts]: I think we run these tests with `Platform.OS = 'ios'` by default so we will never hit the else block. To properly test JS stuff with `Platform.OS = 'Android'` you should call `mockPlatformAndroid()` method.

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+  if (Platform.OS === 'ios') {
+    describe('selection()', () => {
+      it("Doesn't throw an error", async () => {
+        let resultingError;
+        try {
+          await Haptic.selection();
+        } catch (error) {
+          resultingError = error;
+        }
+        expect(resultingError).toBeUndefined();
```
Comment (tsapeta) [inline packages/expo/src/__tests__/Haptic-test.ts]: If you want to test whether `await Haptic.selection()` doesn't fail, there is simpler solution 🙂 
```javascript
it("Doesn't throw an error", async () => {
  await Haptic.selection();
});
```
There is actually no need to use `expect`s here.

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+    });
+    describe('impact()', () => {
+      it("Doesn't throw an error", async () => {
+        let resultingError;
+        try {
+          await Haptic.impact();
+        } catch (error) {
+          resultingError = error;
+        }
+        expect(resultingError).toBeUndefined();
```
Comment (tsapeta) [inline packages/expo/src/__tests__/Haptic-test.ts]: same comment as for Haptic.selection test

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+    });
+    describe('notification()', () => {
+      it("Doesn't throw an error", async () => {
+        let resultingError;
+        try {
+          await Haptic.notification();
+        } catch (error) {
+          resultingError = error;
+        }
+        expect(resultingError).toBeUndefined();
```
Comment (tsapeta) [inline packages/expo/src/__tests__/Haptic-test.ts]: same comment as for Haptic.selection test

**Review by tsapeta — APPROVED** [review]
Looks good to me! 💯 Just a few nitpicking comments 😅 Thanks for fixing that 😉

**Review by ide — CHANGES_REQUESTED** [review]

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+  try {
+    await method();
+    expect(name).toBe('a failing method');
+  } catch (error) {
+    expect(error instanceof UnavailabilityError).toBeTruthy();
+  }
+}
+
+function applyMocks() {
+  mockPlatformWeb();
```
Comment (sjchmiela) [inline packages/expo/src/__tests__/Haptic-test.ts]:
```suggestion
```

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+async function executeUnavailableMethod(method, name) {
+  try {
+    await method();
+    expect(name).toBe('a failing method');
+  } catch (error) {
+    expect(error instanceof UnavailabilityError).toBeTruthy();
+  }
+}
+
+function applyMocks() {
```
Comment (sjchmiela) [inline packages/expo/src/__tests__/Haptic-test.ts]: Maybe move this method down to where it's used? 🤔

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+
+import {
+  mockPlatformAndroid,
+  mockPlatformWeb,
+  mockProperty,
+  unmockAllProperties,
+} from '../../test/mocking';
+import * as Haptic from '../Haptic/Haptic';
+
+async function executeUnavailableMethod(method, name) {
```
Comment (sjchmiela) [inline packages/expo/src/__tests__/Haptic-test.ts]: This function is used only once in the entire file, maybe inlining it would improve readability? 🙂 (Looking at the file in the code editor prolly worked ok, but with some comments in GitHub PR page declaration and its use float apart 😅)

**Review by sjchmiela — APPROVED** [review]
💯

File: packages/expo/src/Haptic/Haptic.ts [hunk 8]
```diff
@@ -45,7 +45,9 @@ export enum ImpactFeedbackStyle {
 /**
  * Triggers notification feedback.
  */
-export function notification(type: NotificationFeedbackType = NotificationFeedbackType.Success) {
+export async function notification(
```
Comment (ide) [inline packages/expo/src/Haptic/Haptic.ts]: btw (not for this PR) - might be good to change the native side of the haptic functions to be async as well (the promise resolves when we successfully make a call to the haptic library) because even with turbomodules, we'll need to `dispatch_async` from the JS queue to the main queue since UIFeedbackGenerator is a main-threaded UI* class

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 9]
```diff
@@ -0,0 +1,92 @@
...
+import {
+  mockPlatformAndroid,
+  mockPlatformWeb,
+  mockProperty,
+  unmockAllProperties,
+} from '../../test/mocking';
+import * as Haptic from '../Haptic/Haptic';
+
+describe('Haptic', () => {
+  describe('iOS', () => {
```
Comment (ide) [inline packages/expo/src/__tests__/Haptic-test.ts]:
```
beforeEach(() => {
  mockPlatformIOS();  // be explicit
});

afterEach(() => {
  unmockAllProperties();
});
```

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+    describe('selection()', () => {
+      it("Doesn't throw an error", async () => {
```
Comment (ide) [inline packages/expo/src/__tests__/Haptic-test.ts]: - Read this as "it doesn't throw an error"
- The first word should be lowercase
- Prefer to use backticks for all the `it` descriptions since they are prose and we don't need to switch between single and double quotes then and it's pretty straightforward once you get used to it

```suggestion
      it(`doesn't throw an error`, async () => {
```

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 11]
```diff
@@ -0,0 +1,92 @@
...
+        await Haptic.selection();
+      });
+    });
+    describe('impact()', () => {
+      it("Doesn't throw an error", async () => {
+        await Haptic.impact();
+      });
+      it('Throws an error when an unexpected type is provided', async () => {
```
Comment (ide) [inline packages/expo/src/__tests__/Haptic-test.ts]: Add a newline between the `it` blocks to space them out a bit

File: packages/expo/src/__tests__/Haptic-test.ts [hunk 12]
```diff
@@ -0,0 +1,92 @@
...
+function applyMocks() {
+  mockPlatformWeb();
+  ['selection', 'impact', 'notification'].forEach(methodName => {
+    mockProperty(NativeModules.ExponentHaptic, methodName, null);
+  });
+}
+
+export function describeUnsupportedPlatforms(message, tests) {
+  describe(`🕸  ${message}`, () => {
+    beforeEach(applyMocks);
```
Comment (ide) [inline packages/expo/src/__tests__/Haptic-test.ts]: This is a bit more robust:

```suggestion
    beforeEach(() => {
      applyMocks();
      mockPlatformWeb();
    });
```

**Review by ide — APPROVED** [review]
Stylistic feedback mostly

File: packages/expo/src/__tests__/Haptic-test.ts (hunk 12 above)
Comment (EvanBacon) [reply packages/expo/src/__tests__/Haptic-test.ts]: This doesn't do anything. The platform remains `ios`
