### PR TITLE
[ios][facebook] add schemes for facebook login & always handle openURL in EXFacebookAppDelegate

### LINKED ISSUE #6112: [iOS][Facebook] Not redirecting back to app after Facebook.logInWithReadPermissionsAsync through facebook app
### Environment

```
Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 - ~/.nodebrew/current/bin/node
      Yarn: 1.16.0 - ~/.nodebrew/current/bin/yarn
      npm: 6.4.1 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.2.3
```

**iOS Standalone AND iOS Expo Client**

### Steps to Reproduce

Must be logged out of Facebook in the browser, but logged in in the Facebook app
Facebook.logInWithReadPermissionsAsync, doesn’t come back to our app after flying to Facebook app.
This may or may not occur.

For now it only occurs on iOS standalone.
It’s pretty strange because it’s quite strange behavior and it hurts user acquisition opportunities.
This is fatal for our app.

### Expected Behavior

After logging in with Facebook, you are redirected to our app and the login process is executed
### Actual Behavior

Even after logging in on the Facebook app, it behaves like staying in the Facebook app.
The only way to get back to our app is to cancel, and of course the login process will fail.

### Sample code
``` javascript
import * as firebase from 'firebase';
import * as Facebook from 'expo-facebook';

const signinFacebook = async () => {
  try {
    const {
      type,
      token,
    } = await Facebook.logInWithReadPermissionsAsync(
      ENV.FACEBOOK_APP_ID,
      {
        permissions: ['public_profile', 'email'],
      },
    );

    if (type === 'success') {
      const credential = firebase.auth.FacebookAuthProvider.credential(token);
      return firebase.auth().signInWithCredential(credential).catch((error) => {
        throw error;
      });
    }
  } catch (error) {
    // ERROR
  }
};
```

### LINKED ISSUE #6459: Expo-Facebook login won't redirect back to Expo Client app when using login with Facebook app
### Environment

Expo CLI 3.9.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.19.2 - ~/.yarn/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    IDEs:
      Xcode: 11.0/11M337n - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.9.0

Expo Client on iOS device

### Steps to Reproduce

I recently tried to add login with Facebook to my application. I just copied the logIn function from here
`https://docs.expo.io/versions/v35.0.0/sdk/facebook/`

When I run my app via Expo Client, and execute the logIn function it

1) Redirects me to a page asking if I want to use the Facebook app for login or use phone or email
2) If I use phone or email login works perfectly fine
3) If I select `Use Facebook App` it takes me to the Facebook app, it says `You have previously logged into [MY_APP] and then I press `Continue` a white screen shows up with the `Cancel` button on the top left. It never goes back to my app and never resolves this function `logInWithReadPermissionsAsync`.

### Expected Behavior

It should have gone back to the Expo Client app where my app was running and it should have resolved the promise and returned `(type === 'success') {` so I could use the token and called GraphQL Apis

### Actual Behavior

A white screen shows up with the `Cancel` button on the top left. It never goes back to my app and never resolves this function `logInWithReadPermissionsAsync`.

### Reproducible Demo

```
 async logIn() {
        try {
            const {
                type,
                token,
            } = await Facebook.logInWithReadPermissionsAsync(`MY_APP_ID`, {
                permissions: ['public_profile', 'email'],
            });
            if (type === 'success') {
                // Get the user's name using Facebook's Graph API
                const response = await fetch(`https://graph.facebook.com/me?access_token=${token}`);
                Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
            } else {
                // type === 'cancel'
                alert(`Facebook Login Cancel`);
            }
        } catch ({ message }) {
            alert(`Facebook Login Error: ${message}`);
        }
    }

    render() {
        return (
            <Button onPress={this.logIn}><Text>Login</Text></Button>
        )
    }```

<!--
  Please share a project that reproduces the issue.
  There are two ways to do it:

    * Create a new app using https://snack.expo.io/ and try to reproduce the issue in it.
      This is useful if you roughly know where the problem is, or can’t share the real code.

    * Or, copy your app and remove things until you’re left with the minimal reproducible demo.
      This is useful for finding the root cause. You may then optionally create a Snack.

  This is a good guide to creating bug demos: https://stackoverflow.com/help/mcve
  Once you’re done, copy and paste the link to the Snack or a public GitHub repository below.

  (Even if your issue can only be reproduced in a standalone app, please include a Snack
  or GitHub repo we can use to build a standalone app!)
-->

<!--
  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->

### PR DESCRIPTION
**Pull request by cruzach**
# Why

(1) Closes https://github.com/expo/expo/issues/6459
and (2) closes https://github.com/expo/expo/issues/6112

(1) Currently, Facebook Login in the Expo Client on iOS does not redirect back to the experience after selecting to "Login via the Facebook app." Instead, the user is left with a blank white screen with `Cancel` at the top left.

(2) In standalone apps (and the Expo Client once (1) is addressed), after calling `Facebook.loginWithReadPermissionsAsync` & signing in with the facebook app, the webbrowser window _occasionally_ remains open after the native facebook app redirects back to the standalone app after the user has logged in, thus users can never log in. This is because `UMAppDelegateWrapper` is [iterating over the subcontractors](https://github.com/expo/expo/blob/master/packages/@unimodules/core/ios/UMCore/UMAppDelegateWrapper.m#L209) looking for a viable openURL method. Sometimes `ExpoKitAppDelegate`  is first in the set, other times `EXFacebookAppDelegate` is first. Since `ExpoKitAppDelegate` always returns YES for openURL, if it’s first in that list, it attempts to (and says it has successfully) open the FB url, but it should not

# How

(1) By adding the fbid url scheme, the FacebookAppId, and the required `LSApplicationQueriesSchemes` from Facebook's documentation, the redirect is now successful. The scoped facebook module now also automatically uses the Expo Client's facebook app id, even if the user provides one. This way, developers don't have to remember to change their app id in place of a "development" app id (Expo's) when they build or publish for release, they can write the method once and forget about it.

(2) By adding a `priority` property to singleton modules, which defaults to `0`, we can re-order the subcontractors to match this priority. So UMAppDelegateWrapper would order unimodules:
n , … , 1, [all the 0s in whatever order], -1, -2, ..., -n

# Test Plan

Tested in a local client build with app.json facebook configuration, and without (but providing in the `Facebook.initializeAsync` call)

Confirmed that `ExpoKitAppDelegate` is always last in [the array of subcontractors](https://github.com/expo/expo/blob/master/packages/@unimodules/core/ios/UMCore/UMAppDelegateWrapper.m#L209)

### CODE REVIEW

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m [hunk 1]
```diff
@@ -74,7 +69,8 @@ - (void)initializeWithAppId:(NSString *)appId
                    rejecter:(UMPromiseRejectBlock)reject
 {
   _isInitialized = YES;
-  [super initializeWithAppId:appId appName:appName resolver:resolve rejecter:reject];
+  NSString *scopedFacebookAppId = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"FacebookAppID"];
```
Comment (sjchmiela) [inline ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:72]: Do you think it makes sense to log an information or a warning (`UMLogWarn`, `UMLogInfo`) that we're overriding the app ID with our own?

File: ios/Exponent/Supporting/Info.plist [hunk 2]
```diff
@@ -70,6 +71,8 @@
 	</dict>
 	<key>FacebookAdvertiserIDCollectionEnabled</key>
 	<false/>
+	<key>FacebookAppID</key>
+	<string>1696089354000816</string>
```
Comment (sjchmiela) [inline ios/Exponent/Supporting/Info.plist:75]: Is it a problem that we don't provide a `FacebookAppName`?

File: ios/Exponent/Supporting/Info.plist [hunk 3]
```diff
@@ -82,7 +85,18 @@
...
+		<string>fbapi20130702</string>
+		<string>fbapi20131010</string>
+		<string>fbapi20131219</string>
+		<string>fbapi20140410</string>
+		<string>fbapi20140116</string>
+		<string>fbapi20150313</string>
+		<string>fbapi20150629</string>
+		<string>fbapi20160328</string>
+		<string>fbauth</string>
+		<string>fb-messenger-share-api</string>
```
Comment (sjchmiela) [inline ios/Exponent/Supporting/Info.plist:99]: Do we still need https://github.com/expo/expo-cli/blob/6bacea668e954c24eb8d9ed6d46a5c46bc3e4a2f/packages/xdl/src/detach/IosNSBundle.ts#L317-L322? Should we `.uniq()` the array before building the app, add/remove some entries?

File: ios/Exponent/Supporting/Info.plist [hunk 4]
```diff
@@ -31,6 +31,7 @@
 			<array>
 				<string>exp</string>
 				<string>exps</string>
+				<string>fb1696089354000816</string>
```
Comment (sjchmiela) [inline ios/Exponent/Supporting/Info.plist:34]: If so, could we remove https://github.com/expo/expo/blob/0ff9a3f7d08a177fe51e822425ddff1af485372c/packages/expo-facebook/ios/EXFacebook/EXFacebookAppDelegate.m#L29-L32?

Comment (sjchmiela) [reply ios/Exponent/Supporting/Info.plist:34]: Maybe the method swizzling is the cause of all these problems in the first place? 🤔

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m [hunk 5]
```diff
@@ -48,21 +48,16 @@ - (instancetype)initWithExperienceId:(NSString *)experienceId andParams:(NSDicti
...
 
-    NSString *facebookAppId = params[@"manifest"][@"facebookAppId"];
+    NSString *scopedFacebookAppId = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"FacebookAppID"];
     NSString *facebookDisplayName = params[@"manifest"][@"facebookDisplayName"];
 
     if (hasPreviouslySetAutoInitEnabled || manifestDefinesAutoInitEnabled) {
-      // FacebookAppId is a prerequisite for initialization.
       // This happens even before the app foregrounds, which mimics
       // the mechanism behind EXFacebookAppDelegate.
-      if (facebookAppId) {
```
Comment (sjchmiela) [inline ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:58]: Could someone build an ad-hoc Expo Client without providing a `FacebookAppID`? If so, is it safe to remove the `if (facebookAppId)`?

**Review by sjchmiela — COMMENTED** [review]
Thanks for taking care of this issue, it giving us and the developers a hard time for so long… 😃 

What are the consequences of using Expo's Facebook app for all API calls in Expo Client? Should we list them in the documentation? We should probably also put that information somewhere around a list of breaking changes introduced in SDK37.

Could you also please add some people from the SWM team to the Expo Client Facebook app, so in case something goes wrong we can at least look into the settings and see if everything is configured as it should?

File: docs/pages/versions/unversioned/sdk/facebook.md [hunk 6]
```diff
@@ -28,14 +28,15 @@ Then follow these steps based on the platforms you're targetting. This will need
 
 - **The Expo client app**
 
-  - Add `host.exp.Exponent` as an iOS _Bundle ID_. Add `rRW++LUjmZZ+58EbN5DVhGAnkX4=` as an Android _key hash_. Your app's settings should end up including the following under "Settings > Basic":
+  - In the Expo Client, all of your Facebook API calls will be made with Expo's Facebook App ID. To use your app's own Facebook App ID (and thus send related app events to your Facebook developer console), you'll need to [build a standalone app](../../distribution/building-standalone-apps/).
+  - Add `host.exp.exponent` as an iOS _Bundle ID_. Add `rRW++LUjmZZ+58EbN5DVhGAnkX4=` as an Android _key hash_. Your app's settings should end up including the following under "Settings > Basic":
```
[the remark this answers is not in the document]
Comment (cruzach) [reply docs/pages/versions/unversioned/sdk/facebook.md:32]: That's correct! Even better 😏 

Removed this from the docs

File: ios/Exponent/Supporting/Info.plist (hunk 2 above)
Comment (cruzach) [reply ios/Exponent/Supporting/Info.plist:75]: It doesn't look like `FacebookDisplayName` is used much, if it all. our current value for it is `exp-test-1`, so I believe we should change this to `Expo Client` if we do want to include it

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m (hunk 1 above)
Comment (cruzach) [reply ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:72]: Good idea, adding that in here and in `initWithExperienceId`

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m (hunk 5 above)
Comment (cruzach) [reply ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:58]: added this back, although i need to double-check the ad-hoc client generation code to see if we assign the given facebookAppId (from app.json) to the info.plist

File: ios/Exponent/Supporting/Info.plist (hunk 3 above)
Comment (cruzach) [reply ios/Exponent/Supporting/Info.plist:99]: hm so it seems the facebook docs are conflicting a little bit:
- when setting up the app it at the facebook developer console it says to include all of these (it know's we use FB SDK v5)
- but [here](https://developers.facebook.com/docs/ios/ios9/) it says that the `fbapi.*` schemes are only if you are on FB SDK v4.5 or older

I haven't noticed any issues when excluding the schemes, so probably safe to remove them

File: ios/Exponent/Supporting/Info.plist (hunk 4 above)
Comment (cruzach) [reply ios/Exponent/Supporting/Info.plist:34]: ^ removed the swizzling code in the most recent commits

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m (hunk 5 above)
Comment (sjchmiela) [reply ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:58]: Don't forget to add this back to the versioned `EXScopedFacebook` too! 😉

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m [hunk 7]
```diff
@@ -48,15 +48,16 @@ - (instancetype)initWithExperienceId:(NSString *)experienceId andParams:(NSDicti
     BOOL hasPreviouslySetAutoInitEnabled = [_settings boolForKey:AUTO_INIT_KEY];
     BOOL manifestDefinesAutoInitEnabled = [params[@"manifest"][@"facebookAutoInitEnabled"] boolValue];
 
-    NSString *facebookAppId = params[@"manifest"][@"facebookAppId"];
+    NSString *scopedFacebookAppId = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"FacebookAppID"];
+    UMLogInfo(@"Overriding Facebook App ID with the Expo Client's. To test your own Facebook App ID, you'll need to build a standalone app. Refer to our documentation for more info- https://docs.expo.io/versions/latest/sdk/facebook/");
```
Comment (sjchmiela) [inline ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:52]: Do you think it makes sense to **always** log that information when the experience is starting? Maybe only if user defines his/her own `FacebookAppID` (if so, they may expect Expo Client to use it) would suffice?

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m [hunk 8]
```diff
@@ -48,15 +48,16 @@ - (instancetype)initWithExperienceId:(NSString *)experienceId andParams:(NSDicti
...
 
     if (hasPreviouslySetAutoInitEnabled || manifestDefinesAutoInitEnabled) {
-      // FacebookAppId is a prerequisite for initialization.
       // This happens even before the app foregrounds, which mimics
       // the mechanism behind EXFacebookAppDelegate.
-      if (facebookAppId) {
-        [FBSDKSettings setAppID:facebookAppId];
+      // Check for FacebookAppId in case this is a custom client build
+      if (scopedFacebookAppId) {
+        [FBSDKSettings setAppID:scopedFacebookAppId];
```
Comment (sjchmiela) [inline ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:60]: Looking from a wider perspective: doesn't Facebook SDK use `Info.plist` as the default source of `FacebookAppID`? If so, do we need to `setAppId:` and `setDisplayName:` manually (just trying to make the code clearer for future maintainers, so they don't scratch their heads why do we set already set value)?

File: docs/pages/versions/unversioned/sdk/facebook.md [hunk 9]
```diff
@@ -28,14 +28,14 @@ Then follow these steps based on the platforms you're targetting. This will need
 
 - **The Expo client app**
 
-  - Add `host.exp.Exponent` as an iOS _Bundle ID_. Add `rRW++LUjmZZ+58EbN5DVhGAnkX4=` as an Android _key hash_. Your app's settings should end up including the following under "Settings > Basic":
+  - In the Expo Client, all of your Facebook API calls will be made with Expo's Facebook App ID. To use your app's own Facebook App ID (and thus send related app events to your Facebook developer console), you'll need to [build a standalone app](../../distribution/building-standalone-apps/).
```
Comment (sjchmiela) [inline docs/pages/versions/unversioned/sdk/facebook.md:31]: Do you think the ramifications you mentioned in

> > What are the consequences of using Expo's Facebook app for all API calls in Expo Client?
> 
> The main drawback is that they won't see app events logged, since their app isn't being initialized. Possibly also ramifications for facebook ads, since that relies on facebook app id as well

are worth listing here?

**Review by sjchmiela — COMMENTED** [review]
These changes look great, great job! 👍

File: ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m (hunk 8 above)
Comment (cruzach) [reply ios/Exponent/Versioned/Core/UniversalModules/EXFacebook/EXScopedFacebook.m:60]: I suppose we don't, my thinking is this might make it more obvious to future maintainers that the provided appId is overridden. But with the addition of the `UMLogInfo`, it's already clear what's happening, so good idea to remove setAppId and setDisplayName

File: docs/pages/versions/unversioned/sdk/facebook.md (hunk 9 above)
Comment (cruzach) [reply docs/pages/versions/unversioned/sdk/facebook.md:31]: added here and to facebook-ads documentation

**Review by sjchmiela — APPROVED** [review]
🎉 Looks super great to me! 🎉

**Comment by appseugene** [comment]
does anyone know how we can get this fix into our existing projects? or what the current status is for this fix to get released?

**Comment by jeanlucnguyen** [comment]
Since the Facebook APP ID used now is always the one from Expo when using Expo Client, it seems that we can't have access to **user_friends**, **user_birthday** or **user_gender** permissions anymore. This used to work well when we could use our own APP ID. Also, being forced to use Expo App Id prevents us from using Facebook Test Users feature as well. Isn't it possible to leave an option to be able to use our own Facebook App Id in development when using Expo Client? We never had the problem referenced in this issue before so this seems like a step back for us.

**Comment by atyrian** [comment]
Hi. I am quite new to developmen, so forgive me if this is not the right forum.

Today I noticed that the permissions that I had previously granted to my application via Facebook's developer portal were no longer effective (**user_gender**, **user_birthday**,**user_photos**). The User ID of my user also changed (I presume this is scoped to the app). After reading the changelog for SDK 37 I now understand that the reason being the user token is issued in the scope of Expo Client instead of the app that I have registered with Facebook.

Is this with the understanding that I may now only use the default public profile permissions, or is there some other way of getting more granular permissions? My application relies very heavily on being able to fetch user images. My understanding is that this means that I should now build my app as a Standalone application (something that I would have to do to distribute the app on the app store anyways?) as per the SDK 37 documentation.

Thank you for any help in this matter.

**Comment by cruzach** [comment]
@atyrian that's correct, you should build your app as a standalone IPA (you can also test using simulator builds) if you want to use your own Facebook app ID

@jeanlucnguyen it seems like those particular permissions, along with a couple other features, require app review, I'll look into that. As for Test Users, it seems like that may be a feature not available in the Expo Client app. But I think having a functioning Facebook Login is more critical than access to the test users feature in the expo client app
