### PR TITLE
[dev-launcher] Fix intent that started activity isn't passed further

### LINKED ISSUE #13992: [🤖] Intent that started activity isn't passed further
### Summary

When the activity has been started with an intent containing extras, those extras aren't passed to the activity.
We use for example Firebase Cloud Messaging. When the application is killed and the user presses on a notification, we fail to get the notification payload, as the intent isn't passed to the activity.

## Steps used to solve the issue

The issue seems to me that in `onCreate` the intent isn't forwarded to the dev clients intent registry.

* In `DevLauncherController` I made `handleExternalIntent` public.
* In `DevLauncherController` I added a public method, called `addPendingIntent`, that just calls `handleExternalIntent`
* In app's `MainActivity` the onCreate now looks like this:
```java
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    if (getIntent().getExtras() != null && savedInstanceState == null) {
      DevLauncherController.addPendingIntent(getIntent());
    }
    // Set the theme to AppTheme BEFORE onCreate to support
    // coloring the background, status bar, and navigation bar.
    // This is required for expo-splash-screen.
    setTheme(R.style.AppTheme);
    super.onCreate(savedInstanceState);
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "^0.4.7",
"expo-updates": "~0.8.4",

### Environment
<details>
  <summary>EnvironmentClick to expand!</summary>

```
  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.1, 30.0.2, 30.0.3
        System Images: android-23 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.64.2 => 0.64.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare
```
</details>

### Reproducible demo or steps to reproduce from a blank project

I reproduced this with using firebase cloud messaging, sending a push notification and starting the app, checking with
```
messaging().getInitialNotification();
```

in JS for the notification.

There are probably easier ways to test this, e.g. by starting the app with an intent with extras using `adb`.

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/13992.

# How

Saves intent without data as a pending intent too.

# Test Plan

- bare-expo ✅

### CODE REVIEW

File: packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt [hunk 1]
```diff
@@ -100,7 +100,11 @@ class DevLauncherInternalModule(reactContext: ReactApplicationContext?)
 
   @ReactMethod
   fun getPendingDeepLink(promise: Promise) {
-    promise.resolve(intentRegistry.intent?.data?.toString())
+    intentRegistry.intent?.data?.let {
+      promise.resolve(it.toString())
+    }
+
+    promise.resolve(intentRegistry.intent?.action)
```
Comment (esamelson) [inline packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt:107]: I don't think we should call `resolve` twice on the same Promise, even if it happens to be a no-op the second time. It would be more future-proof to be explicit about what we do and don't want to happen in each case.

Comment (lukmccall) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt:108]: Good find 💪

**Review by esamelson — APPROVED** [review]
