### PR TITLE
[expo-image-picker][ios] set video quality to high, to prevent low quality recording

### LINKED ISSUE #6224: ImagePicker.launchCameraAsync only records videos at 480x360
### Environment
```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1
```

### Target
iPhone X iOS 13.1.3

### Steps to Reproduce

Using the the `ImagePicker.launchCameraAsync` method results in only low quality (480x360) videos regardless of the `quality` and `aspect` options passed.

### Expected Behavior

Passing a `quality` option of `1` should result in a video with the highest possible quality 

### Actual Behavior

Using the the `ImagePicker.launchCameraAsync` method results in only low quality (480x360) videos regardless of the `quality` and `aspect` options passed.

### Reproducible Demo

`VideoLauncher.js`

```
import React from "react";
import { View, TouchableHighlight, Text, StyleSheet } from "react-native";
import { EvilIcons } from "@expo/vector-icons";
// import Colors from "../constants/Colors";
let Colors = {
  tintColor: "#FFF" 
}

export default function VideoLauncher({
  icon,
  label,
  onPress,
  iconColor = Colors.tintColor,
}) {
  return (
    <View style={styles.container}>
      <TouchableHighlight
        style={styles.select}
        underlayColor="#1a1a1a"
        onPress={onPress}>
        <View style={styles.button}>
          <EvilIcons name={icon} size={64} color={iconColor}></EvilIcons>
          <Text style={{ color: "lightgrey" }}>{label}</Text>
        </View>
      </TouchableHighlight>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    height: 160,
    width: 160,
  },
  select: {
    flex: 1,
  },
  button: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "grey",
    borderRadius: 20,
    borderStyle: "dashed",
  },
});
```

`VideoUploadScreen.js`

```
import * as React from "react";
import { View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import Constants from "expo-constants";
import * as Permissions from "expo-permissions";
import VideoLauncher from "../components/VideoLauncher";
// import Colors from "../constants/Colors";
let Colors = {
  tintColor: "#FFFFFF",
  successColor: "#FFFFFF" 
}

let launchTypes = {
  gallery: "launchImageLibraryAsync",
  camera: "launchCameraAsync",
};

export default class VideoUploadScreen extends React.Component {
  static navigationOptions = {
    title: "Upload Video",
  };

  state = {
    image: null,
  };

  render() {
    let { image } = this.state;

    return (
      <View
        style={{
          flex: 1,
          alignItems: "center",
          justifyContent: "space-around",
        }}>
        <VideoLauncher
          icon="image"
          label="Choose"
          onPress={() => this.pickImage(launchTypes.gallery)}
        />
        <VideoLauncher
          icon="camera"
          iconColor={Colors.successColor}
          label="Capture"
          onPress={() => this.pickImage(launchTypes.camera)}
        />
      </View>
    );
  }

  sendVideo = async ({ type, uri }) => {
    let name = "video";
    let method = "POST";
    let body = new FormData();
    body.append(name, { name, type, uri });
    let res = await fetch("http://10.0.0.11:3000/video", {
      body,
      method,
    });
    return res.json();
  };

  componentDidMount() {
    this.getPermissionAsync();
  }

  getPermissionAsync = async () => {
    if (Constants.platform.ios) {
      const camera = await Permissions.askAsync(Permissions.CAMERA);
      const roll = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (roll.status !== "granted" && camera.status === "granted") {
        alert("Sorry, we need camera roll permissions to make this work!");
      }
    }
  };

  pickImage = async (type = launchTypes.camera) => {
    try {
      let result = await ImagePicker[type]({
        mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        allowsEditing: true,
        quality: 1,
        aspect: [16, 9],
      });

      // result shows small 
      console.log("result", result);

      if (!result.cancelled) {
        await this.sendVideo(result);
        this.setState({ image: uri });
      }
    } catch (err) {
      console.error(err);
    }
  };
}
```

Any help would be much appreciated, maybe this is expected given something I don't yet understand about Expo.

### PR DESCRIPTION
**Pull request by vmaark**
# Why
Resolves #6224 
On iOS, opening the camera via the image picker api results in a low quality video recording, regardless of the options provided.

# How
The suggested fix in the issue is setting the native `videoQuality` property, because the lack of it defaults to low resolution.

# Test Plan

I've verified both the issue and the fix with the help of this repo created by @lukmccall https://github.com/lukmccall/launchCameraAsyncIssue. I'd also like to test it in my application, but not sure how to set up to use an unreleased expo sdk.

### CODE REVIEW

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 1]
```diff
@@ -173,7 +173,8 @@ - (void)launchImagePicker:(EXImagePickerTarget)target
     if (@available(iOS 11.0, *)) {
       self.picker.videoExportPreset = [self importVideoExportPreset:self.options[@"videoExportPreset"]];
     }
-    
+    self.picker.videoQuality = UIImagePickerControllerQualityTypeHigh;
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:176]: There might be some cases where people don't want to use the highest quality — it would be better to provide a new option to control this behavior.
cc @lukmccall

**Review by tsapeta — CHANGES_REQUESTED** [review]

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 1 above)
Comment (vujevits) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:176]: In my understanding this should still be effected by the `VideoExportPreset` option, so the saved video does not have to be high quality. Although `VideoExportPreset` is being deprecated in iOS 14, so maybe it should be replaced with [UIImagePickerControllerQualityType](https://developer.apple.com/documentation/uikit/uiimagepickercontrollerqualitytype), which is used here.

Comment (lukmccall) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:176]: Maybe we could deprecate `videoExportPreset` and switch to `UIImagePickerControllerQualityType`? Or maybe it will be better if we change `picker.videoQuality` according to the `options[@"videoExportPreset"]`. I'm not sure which solution is better in this case.

Comment (vujevits) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:176]: I was considering the latter, but I often end up looking at Apple documentation, so using the `VideoExportPreset` value for another valid iOS option seems confusing. I prefer going with the first option if that's fine.

Comment (lukmccall) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:176]: Ok, it sounds great 🎉 Thanks for taking care of it ;)

File: packages/expo-image-picker/src/ImagePicker.types.ts [hunk 2]
```diff
@@ -56,6 +65,7 @@ export type ImagePickerOptions = {
   exif?: boolean;
   base64?: boolean;
   videoExportPreset?: VideoExportPreset;
```
Comment (lukmccall) [inline packages/expo-image-picker/src/ImagePicker.types.ts:67]:
```suggestion
	/**
    * @deprecated use `videoQuality` instead.
    */
  videoExportPreset?: VideoExportPreset;
```

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 3]
```diff
@@ -239,6 +240,17 @@ Android system sometimes kills the `MainActivity` after the `ImagePicker` finish
...
+### `ImagePicker.UIImagePickerControllerType`
+
+| Preset                                       | Value | Resolution            | Video compression algorithm | Audio compression algorithm |
+| -------------------------------------------- | ----- | --------------------- | --------------------------- | --------------------------- |
+| `UIImagePickerControllerType.High`           | 0     | Highest available     | None                        | None                        |
+| `UIImagePickerControllerType.Medium`         | 1     | Depends on the device | None                        | None                        |
+| `UIImagePickerControllerType.Low`            | 2     | Depends on the device | None                        | None                        |
+| `UIImagePickerControllerType.VGA640x480`     | 3     | 640 x 480             | None                        | None                        |
+| `UIImagePickerControllerType.IFrame1280x720` | 4     | 1280 x 720            | None                        | None                        |
+| `UIImagePickerControllerType.IFrame960x540`  | 5     | 960 x 540             | None                        | None                        |
```
Comment (lukmccall) [inline docs/pages/versions/unversioned/sdk/imagepicker.md:252]: I believe we can remove algorithm's columns ;)

**Review by lukmccall — COMMENTED** [review]
LGTM 🎉
Please add an entry to the `CHANGELOG` ([here](https://github.com/expo/expo/blob/master/packages/expo-image-picker/CHANGELOG.md)) and run `yarn build` in the `expo-image-picker` package directory.

File: packages/expo-image-picker/src/ImagePicker.types.ts (hunk 2 above)
Comment (vujevits) [reply packages/expo-image-picker/src/ImagePicker.types.ts:67]: I might be wrong but based on the documentation it seems videoQuality is only effecting **recording**, meanwhile `videoExportPreset` is also doing a conversion when picking a video from the gallery, so it's not a 1 to 1 mapping.

Comment (lukmccall) [reply packages/expo-image-picker/src/ImagePicker.types.ts:67]: So it will be a better idea to leave these two options 😅
Please remove `deprecated` word from the documentation too ;)

Comment (vujevits) [reply packages/expo-image-picker/src/ImagePicker.types.ts:67]: it does not change the fact that it's deprecated :) 
https://developer.apple.com/documentation/uikit/uiimagepickercontroller/2890964-videoexportpreset?language=objc

Comment (lukmccall) [reply packages/expo-image-picker/src/ImagePicker.types.ts:67]: Sorry, I forgot about it 😅  My bad.

Comment (lukmccall) [reply packages/expo-image-picker/src/ImagePicker.types.ts:67]: So add a comment that `videoExportPreset` is deprecated, but don't redirect a user to use `videoQuality` 😉
You can link the apple documentation int this comment.

**Comment by lukmccall** [comment]
Please fix:
```
❌  /Users/runner/work/expo/expo/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:44:46: collection element of type 'NSInteger' (aka 'long') is not an Objective-C object

                        @"videoQuality": UIImagePickerControllerQualityTypeHigh
      
⚠️  /Users/runner/work/expo/expo/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:177:30: incompatible pointer to integer conversion assigning to 'UIImagePickerControllerQualityType' (aka 'enum UIImagePickerControllerQualityType') from 'id _Nullable' [-Wint-conversion]

    					self.picker.videoQuality = self.options[@"videoQuality"];
```

**Review by lukmccall — APPROVED** [review]
LGTM 🎉🎉🎉

**Review by bbarthec — APPROVED** [review]

**Comment by vujevits** [comment]
@lukmccall @tsapeta is there a way to test the HEAD / 39 RC SDK with my project somehow? I'd like to see my changes in real action, before the sdk gets released, so if there's anything unexpected, it can be fixed before the release.

**Comment by bbarthec** [comment]
@vujevits, I'm afraid there's no way to do so 😞 I advise you to wait for the release and test it once the SDK 39 is out. You don't need to upgrade right away from your actual SDK 😉
