### PR TITLE
[expo-calendar] Fix Calendars.getCalendarsAsync rejecting when calendar name is nil

### LINKED ISSUE #5809: [iOS 13] Fetching calendars not working
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.8 => 16.8.22
      @types/react-native: ^0.57.41 => 0.57.65
      @types/react-navigation: ^3.0.6 => 3.0.7
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.1.2

This issue only happens whenever you are testing on an iOS 13 device (I could not test the bug on the simulator, because this gave me another bug with Localization that has already been reported)

### Steps to Reproduce

* Create a new project with SDK 35 and test on an iPhone with > iOS 13.
* Add `expo-calendar` to your `package.json` with version `~7.0.0`.
* Write code to ask for permissions
* After permission has been given, write code to fetch all calendars.

import * as ExpoCalendar from 'expo-calendar';

```
await ExpoCalendar.requestPermissionsAsync();
const localCalendars = await ExpoCalendar.getCalendarsAsync();
console.log(localCalendars);
```

* Notice how this either sometimes gives you an empty array, but most of the time results into the following error. 

```
An exception was thrown while calling `ExpoCalendar.getCalendarsAsync` with arguments `(
    "<null>"
)`: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104:55 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```

### Expected Behavior

A list of all the calendars that are there

### Actual Behavior

The error as shown above

### Reproducible Demo

https://snack.expo.io/@jordywijman/calendars-issue

Litterarly just run it on the snack itself, and you'll see it works, then try to run it on your device with > iOS 13 and you get nothing back.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #5809.

# How

On iOS 13, sometimes when you sync your phone with google account, `source.title` is nil.
I think it's system bug. Unfortunately, I'm not sure. 

# Test Plan

It's very hard to reproduce. You need to add google account and sync calendar. Then use `Calendar.getCalendarsAsync` to get all calendars. With this fix, it'll work every time.

### CODE REVIEW

File: ios/versioned-react-native/ABI35_0_0/EXCalendar/ABI35_0_0EXCalendar/ABI35_0_0EXCalendarConverter.m [hunk 1]
```diff
@@ -124,7 +124,7 @@ + (NSDictionary *)serializeSource:(EKSource *)source
   return @{
        @"id": source.sourceIdentifier,
        @"type": [ABI35_0_0EXCalendarConverter _sourceType:source.sourceType],
-       @"name": source.title
+       @"name": ABI35_0_0UMNullIfNil(source.title)
```
Comment (tsapeta) [inline ios/versioned-react-native/ABI35_0_0/EXCalendar/ABI35_0_0EXCalendar/ABI35_0_0EXCalendarConverter.m]: We don't want to change versioned code in the client if you aren't going to update shell apps for standalone builds, it's better to still have that bug unfixed in older SDKs rather than have two different behaviors between the client and standalone. I'm fine if you will update shell apps for all these SDKs as well :D

**Review by tsapeta — COMMENTED** [review]
One comment below + please don't forget about changelog :P

**Review by tsapeta — APPROVED** [review]
