### PR TITLE
[video-thumbnails] Fix URI parsing

### LINKED ISSUE #5657: VideoThumbnails: Error: Can't read file
I'm unable to generate thumbnails for the uri which I took using `ImagePicker`. I'm using same code as documented in expo docs.

P.S. it works on iOS.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #5657.

# How

Add URI parsing, when provided URI to a local file.

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/32b3b2 <- now returns valid thumbnail uri.

### CODE REVIEW

File: packages/expo-video-thumbnails/android/src/main/java/expo/modules/videothumbnails/VideoThumbnailsModule.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ protected void onPostExecute(Bitmap thumbnail) {
                     outputStream.flush();
                     outputStream.close();
                     Bundle response = new Bundle();
-                    response.putString("uri", Uri.fromFile(new File(path)).toString());
+                    response.putString("uri", Uri.fromFile(new File(path)) .toString());
```
Comment (tsapeta) [inline packages/expo-video-thumbnails/android/src/main/java/expo/modules/videothumbnails/VideoThumbnailsModule.java]:
```suggestion
                    response.putString("uri", Uri.fromFile(new File(path)).toString());
```
😜

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FilePermissionModule.java [hunk 2]
```diff
@@ -1,6 +1,7 @@
 package expo.modules.filesystem;
 
 import android.content.Context;
+import android.net.Uri;
```
Comment (tsapeta) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FilePermissionModule.java]: Are you sure this needs to be added to this file? This is the only change in this file 😅

**Review by tsapeta — APPROVED** [review]
