### PR TITLE
[hermes][dev-server] Fix incorrect hermesc path on SDK 46

### LINKED ISSUE #18542: [dev-server][hermes] Incorrect hermesc path on react-native>=0.69
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@expo/dev-server@0.1.110` for the project I'm working on.

There was an oversight in this line of code where the path should point to hermes executable bundled with `react-native@0.69` and above. Not sure what's the best solution to support backwards compatibility but this is what works on >=0.69.

This was breaking `expo-updates` for me with `hermes` enabled as the bytecode generated currently will not match and I get `Wrong bytecode version. Expected 85 but got 84` error.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@expo/dev-server/build/metro/importMetroFromProject.js b/node_modules/@expo/dev-server/build/metro/importMetroFromProject.js
index d1cbb72..6b1a1da 100644
--- a/node_modules/@expo/dev-server/build/metro/importMetroFromProject.js
+++ b/node_modules/@expo/dev-server/build/metro/importMetroFromProject.js
@@ -54,7 +54,7 @@ function importExpoMetroConfigFromProject(projectRoot) {
 exports.importExpoMetroConfigFromProject = importExpoMetroConfigFromProject;
 function importHermesCommandFromProject(projectRoot) {
     const platformExecutable = getHermesCommandPlatform();
-    return resolveFromProject(projectRoot, `hermes-engine/${platformExecutable}`);
+    return resolveFromProject(projectRoot, `react-native/sdks/hermesc/${platformExecutable}`);
 }
 exports.importHermesCommandFromProject = importHermesCommandFromProject;
 function getHermesCommandPlatform() {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by thespacemanatee**
# Why

Fixes #18542 

# How

Added a function to check if `hermes` is bundled based on SDK version, where `>= 46.0.0` runs `react-native>=0.69`, and provide the appropriate path to the `hermes` executable.

# Test Plan

- Ran the changes by my personal project, but please let me know how I can test this PR properly

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
hey @thespacemanatee! thanks for the fix. it was our fault when moving the `@expo/dev-server` code from expo/expo-cli repo to expo/expo repo for the versioned cli. actually i had a fix at https://github.com/expo/expo-cli/pull/4462. could you help to align the change to this pr?

**Comment by thespacemanatee** [comment]
@Kudo done!

File: packages/@expo/dev-server/src/metro/importMetroFromProject.ts [hunk 1]
```diff
@@ -65,7 +65,28 @@ export function importExpoMetroConfigFromProject(
...
+    `react-native/sdks/hermesc/${platformExecutable}`,
+
+    // Legacy hermes-engine package
+    `hermes-engine/${platformExecutable}`,
+  ];
+
+  for (const location of hermescLocations) {
+    try {
+      return resolveFromProject(projectRoot, location);
+    } catch (e: any) {}
```
Comment (Kudo) [inline packages/@expo/dev-server/src/metro/importMetroFromProject.ts:87]:
```suggestion
    } catch {}
```

```
stdout > /home/runner/work/expo/expo/packages/@expo/dev-server/src/metro/importMetroFromProject.ts
stdout >   87:14  warning  'e' is defined but never used  @typescript-eslint/no-unused-vars
```

there's a lint error originally passed in expo-cli repo. please help to fix it for me. thanks!

**Review by Kudo — APPROVED** [review]
