### PR TITLE
[expo-barcode-scanner] Fix attempt to send events with nil as value

### LINKED ISSUE #5160: expo-camera work well on Expo Client, but it make crash app when I build ios standalone app
## 🐛 Bug Report
expo-camera work well on Expo Client, but it make crash app when I build ios standalone app
### Environment
IOS Standalone App build
Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6
### Steps to Reproduce
Ask permission camera on app -> camera permission approved -> Camera tag is render and app crashed on IOS 
### Expected Behavior
Camera show preview
### Actual Behavior
App crashed

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Should fix https://github.com/expo/expo/issues/5160.

# How

I inspected crash log (https://github.com/expo/expo/issues/5160#issuecomment-517831917) and found that it points to this line to this error. Now the code will ensure that the value it wants to send to JS is not nil.

# Test Plan

I haven't executed any tests, Expo client compiled.

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]

File: ios/versioned-react-native/ABI34_0_0/EXBarCodeScanner/ABI34_0_0EXBarCodeScanner/ABI34_0_0EXBarCodeScanner.m [hunk 1]
```diff
@@ -164,7 +164,7 @@ - (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputMetadataObjects:
     if([metadata isKindOfClass:[AVMetadataMachineReadableCodeObject class]]) {
       AVMetadataMachineReadableCodeObject *codeMetadata = (AVMetadataMachineReadableCodeObject *) metadata;
       for (id barcodeType in _settings[ABI34_0_0EX_BARCODE_TYPES_KEY]) {
-        if ([metadata.type isEqualToString:barcodeType]) {
+        if (codeMetadata.stringValue && [metadata.type isEqualToString:barcodeType]) {
```
Comment (bbarthec) [inline ios/versioned-react-native/ABI34_0_0/EXBarCodeScanner/ABI34_0_0EXBarCodeScanner/ABI34_0_0EXBarCodeScanner.m]:
```suggestion
        if (codeMetadata.stringValue && [codeMetadata.type isEqualToString:barcodeType]) {
```
or 
```suggestion
        if (metadata.stringValue && [metadata.type isEqualToString:barcodeType]) {
```

It's not consistent with what's being changed in `unversioned` package

Comment (sjchmiela) [reply ios/versioned-react-native/ABI34_0_0/EXBarCodeScanner/ABI34_0_0EXBarCodeScanner/ABI34_0_0EXBarCodeScanner.m]: I know
