### PR TITLE
[template] fix IconSymbol and ExternalLink types

### LINKED ISSUE #35777: Type 'StyleProp<ViewStyle>' is not assignable to type 'StyleProp<TextStyle>'.
### Summary

When generating the template code, I have the following error in components/ui/IconSymbol.tsx on line:
```ts
return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
```
> Type 'StyleProp<ViewStyle>' is not assignable to type 'StyleProp<TextStyle>'.
Type 'ViewStyle' is not assignable to type 'StyleProp<TextStyle>'.
 Type 'ViewStyle' is not assignable to type 'TextStyle'.

Only happens when `expo-env.d.ts` file was generated.

### What platform(s) does this occur on?

_No response_

### SDK Version

_No response_

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.4/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
      Watchman: 2025.03.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 28, 33, 34, 35, 36
        Build Tools: 30.0.3, 33.0.0, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.40 => 52.0.40 
      expo-router: ~4.0.19 => 4.0.19 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.7 => 0.76.7 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

### Minimal reproducible example

Create a project and start it (make sure `expo-env.d.ts` gets generated), then look into `IconSymbol.tsx` TS errors.

I also found an issue in `ExternalLink.tsx`:

> Type 'string' is not assignable to type 'RelativePathString | ExternalPathString | "/_sitemap" | `/_sitemap?${string}` | `/_sitemap#${string}` | "/(tabs)" | "/(tabs)/explore" | `/(tabs)/explore?${string}` | `/(tabs)/explore#${string}` | ... 14 more ... | { ...; }'.

### PR DESCRIPTION
**Pull request by kadikraman**
# Why

Resolves https://github.com/expo/expo/issues/35777

# How

1. For the IconButton, we're allowed to use TextStyles or ViewStyles, so we were just typing the props incorrectly
2. For the external link, we're looking for Href that is a string (which is more correct than stringifying the href)

# Test Plan

```sh
bun install
npx expo start
bunx tsc
```
& ensure there are no ts errors

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: templates/expo-template-default/components/ui/IconSymbol.tsx [hunk 1]
```diff
@@ -3,7 +3,7 @@
 import MaterialIcons from '@expo/vector-icons/MaterialIcons';
 import { SymbolWeight, SymbolViewProps } from 'expo-symbols';
 import { ComponentProps } from 'react';
-import { OpaqueColorValue, StyleProp, ViewStyle } from 'react-native';
+import { OpaqueColorValue, StyleProp, TextStyle } from 'react-native';
```
Comment (byCedric) [inline templates/expo-template-default/components/ui/IconSymbol.tsx:6]:
```suggestion
import { OpaqueColorValue, type StyleProp, TextStyle } from 'react-native';
```

**Review by byCedric — APPROVED** [review]
