### PR TITLE
[android] Migrate installation identifier to non-backed-up storage

### LINKED ISSUE #11008: [expo-notifications] Device identifier used by expo-notifications is scoped per experience
## 🐛 Bug Report

While testing https://github.com/expo/expo/pull/11005 I have found a bug — `InstallationIdProvider` exposed to JS, used to get/create `deviceId`, was not being subclassed in `expoview` and while at first it looked like it would grab the same UUID that:
- `Constants.installationId` exposed to JS, used in `expo-firebase-analytics`, `home`
- `ExponentFcmIntentService` used when automatically updating device push token on Expo servers in standalone apps
- old `Notifications` API uses when fetching an Expo push token

used thanks to the same `SharedPreferences` name and key, it actually created a UUID of its own (the module received a `ScopedContext` which automatically scopes `SharedPreferences` and while it looked like it would operate on `host.exp.exponent.SharedPreferences`, it actually used `@username/id-host.exp.exponent.SharedPreferences`.

On one hand this creates a dichotomy in installation identifiers used throughout the codebase, on the other hand it actually may make it easier for us to deprecate and eventually remove the "common" installation ID.

The one problem it raises is the fact that apps for projects that were initially built as standalone apps and then were ejected will rotate their `installationId` on this change (since in bare the `InstallationIdProvider` will no longer receive a `ScopedContext`, it will start to use the "common" installation ID) and as a result of this — Expo push token.

Essentially this boils down to whether we'd accept Expo push token change:
- as a result of upgrading (`InstallationIdProvider` could start using "common" installation ID in SDK 40)
- as a result of ejecting to bare workflow (once ejected, `InstallationIdProvider` receives unscoped `Context` and uses a different UUID than the one that it used previously).

I'm curious to hear your opinion, @ide, I thought postponing the issue to "ejecting" may look like less inconvenience for all parties (why anyone would expect tokens to change after upgrading) and "ejecting" is also a more "serious" process (during which token rotation may even look like something expected). On the other hand subclassing `InstallationIdProvider` and rotating the tokens on this upgrade fixes the issue completely and immediately (also fixing device push token being outdated in standalone apps without need to implement autoreregistration).

### Environment

This happens on Android.
 
### Steps to Reproduce

I've inspected `shared_prefs` stored in the data directory of a sample standalone app on an Android emulator and noticed two `uuid` values:
1. `/data/user/0/com.sjchmiela.myapp/shared_prefs/%40sjchmiela%2Fmy-app-host.exp.exponent.SharedPreferences.xml`
2. `/data/user/0/com.sjchmiela.myapp/shared_prefs/host.exp.exponent.SharedPreferences.xml`

Another way to see this is to run the app

<details><summary>Code</summary>

```tsx
import { StatusBar } from "expo-status-bar";
import Constants from "expo-constants";
import InstallationIdProvider from "expo-notifications/build/InstallationIdProvider";
import React from "react";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
  const [notificationsId, setNotificationsId] = React.useState<
    string | undefined
  >(undefined);
  React.useEffect(() => {
    try {
      InstallationIdProvider.getInstallationIdAsync!().then(setNotificationsId);
    } catch (e) {
      alert(e);
    }
  }, []);

  return (
    <View style={styles.container}>
      <Text>Constants.installationId</Text>
      <Text>{Constants.installationId}</Text>
      <Text>expo-notifications.installationId</Text>
      <Text>{notificationsId}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

</details>

for apps of two different `experienceId`s:

Zrzut ekranu 2020-11-12 o 22 16 23

### Expected Behavior vs Actual Behavior (or is it?)

I imagine one could expect `InstallationIdProvider` to always return the same identifier as `Constants.installationId`.

Currently it returns the same identifier only on apps in bare workflow.

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

https://github.com/expo/expo/pull/10261#issuecomment-725396140. Also fixes https://github.com/expo/expo/issues/11008 by making `expo-notifications` use the same installation ID as `expo-constants` and `expoview` (https://github.com/expo/expo/pull/11005/commits/f1ecd07d586094fb9494a5e6584e7d01e419aa48).

# How

Found a (in my opinion) nicer way to store a string in a non-backed-up storage (than defining a `<full-backup-content>` XML file and requiring developers to implement their own `BackupAgent` in some circumstances, etc.) — using [`getNoBackupFilesDir`](https://developer.android.com/reference/android/content/Context#getNoBackupFilesDir()) to get a directory where we create a simple `.txt` file. The advantage it provides is not requiring developers to [modify any native files](https://github.com/expo/expo/pull/10261/files#diff-d8d19d8e0ef909f84b94eb86534e4dde2f0659b56c72ce5bcde12c5815e8b2fd) to incorporate this feature.

I wrote a class that tries to migrate the UUID from `SharedPreferences` to `noBackupFilesDir` on `getUUID` call. It should handle invalid UUIDs well (by ignoring it). Then I copied it from `expoview` to `expo-constants` and `expo-notifications` in case there are bare projects that use one and not the other (we don't want to depend on migration in `-constants` in `-notifications` and vice versa). It follows the implementation outline of https://github.com/expo/expo/pull/10261#issuecomment-725396140 with the following modifications:
- instead of removing the `SharedPreferences/keychain` entry "so we recover from corrupt data" I decided to ignore it
- if we didn't read a valid ID and we wouldn't intend to create one if it wasn't present we don't immediately generate a new one. There are still parts of code that do not "get-or-create" the UUID, just "get". For them we need a sensible "just-get" implementation.
- instead of computing the v5 UUID from the Firebase Instance ID (as proposed by the main overview) I've decided to stick with a random v4 UUID since fetching the Firebase Instance ID [starts some kind of connection with Firebase servers](https://github.com/TheWizard91/Album_base_source_from_JADX/blob/e1d228fc2ee550ac19eeac700254af8b0f96080a/sources/com/google/firebase/iid/FirebaseInstanceId.java#L227-L231) — it may also require Firebase app configured (but I haven't verified that) and even though `installationId` is mostly used in `expo-notifications`, we don't say anywhere that accessing `expo-constants.installationId` requires Firebase configured.
- instead of using `SharedPreferences` I decided to save the file in `noBackupFilesDir` which seems less breakable than using `SharedPreferences` and configuring `full-backup-content`.

Another option I was thinking of was to create a new unimodule `expo-installations` (`expo-installation-id`) just for this class and depend on the new unimodule in `expoview`, `expo-constants` and `expo-notifications`. Since we intend to deprecate and eventually remove `.installationId` creating a unimodule just for half a year and deprecating it immediately doesn't seem like the best idea.

# Test Plan

I have verified that:
- `Constants.installationId` from running Expo client on `master` is the same as `.installationId` returned when running Expo client on this branch
- `expo-notifications`'s installation ID from running Expo client on `master` is the same as `installationId` returned when running Expo client on this branch
- removing and reinstalling Expo client sets a different `installationId`
- modifying the file so that is does not contain a valid UUID discards its contents and persists a new UUID

# Test approach #2

Test scenarios for installation identifiers:
- **on an experience running on SDK39 when Expo client upgrades**
  - SDK39 `ConstantsBinding` keeps using `mExponentSharedPreferences.getOrCreateUUID`. Unversioned `ExponentSharedPreferences` migrates UUID from unscoped `SharedPreferences` to unscoped non-backed-up storage. No change. ✅ 
  - SDK39 `InstallationIdProvider` keeps using scoped `SharedPreferences`. Migration isn't being added to versioned `InstallationIdProvider`s, **identifier keeps being backed-up** but it doesn't change. ⚠️ 
- **when an experience using SDK39 upgrades to SDK40 in Expo client**
  - Both SDK39 and SDK40 `ConstantsBinding`s use `mExponentSharedPreferences.getOrCreateUUID` which uses migrated non-backed-up storage. No change ✅ 
  - SDK39 `InstallationIdProvider` used scoped `SharedPreferences`, SDK40 `ScopedInstallationIdProvider` uses `mExponentSharedPreferences.getOrCreateUUID` if there is no existing ID (new project) or migrates legacy UUID from scoped `SharedPreferences` to scoped no-backup-dir if it exists and keeps using it in the future. All in all there's no change. ✅ 
- when standalone app using SDK39 upgrades to SDK40
  - Both SDK39 and SDK40 `ConstantsBinding`s use `mExponentSharedPreferences.getOrCreateUUID` which uses migrated non-backed-up storage. No change ✅ 
  - SDK39 `InstallationIdProvider` had ID saved in scoped `SharedPreferences`, SDK40 `InstallationIdProvider` migrates that ID to scoped `noBackupDir`. No change ✅ 
- when an SDK39 project ejects to bare
  - SDK39 `ConstantsBinding` was using `mExponentSharedPreferences.getOrCreateUUID` which persisted ID in unscoped `SharedPreferences`. Upon ejection we start using `ConstantsService` with unscoped `Context` which results in using the same `SharedPreferences`. No change ✅ 
  - SDK39 `InstallationIdProvider` uses scoped `SharedPreferences` to persist installation ID. Upon ejection we start using unscoped `SharedPreferences`, ID changes to one equal to `Constants.installationId`. ⚠️ [We can live with that.](https://github.com/expo/expo/issues/11008#issuecomment-728769487)
- when an SDK40 project ejects to bare
  - SDK40 `ConstantsBinding` was using `mExponentSharedPreferences` which persisted ID in unscoped non-backed-up storage. `ConstantsService` uses the same storage location, ID doesn't change. ✅ 
  - SDK40 `ScopedInstallationProvider` was using either `mExponentSharedPreferences` which persisted ID in unscoped non-backed-up storage (in this case bare `InstallationIdProvider` uses unscoped common installation ID and there are no changes. ✅) or used ID migrated from scoped `SharedPreferences` to scoped `noBackupDir` in which case the ID changes, but [we can live with that](https://github.com/expo/expo/issues/11008#issuecomment-728769487)). ⚠️
- when a bare project upgrades `expo-notifications` or `expo-constants`
  - Previous installation ID providers used unscoped `SharedPreferences`. Upon upgrade, the ID gets migrated to the same location by either `expo-notifications` or `expo-constants`. ID stays the same. ✅

### CODE REVIEW

File: packages/expo-constants/android/src/main/java/expo/modules/constants/ExponentInstallationId.java [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+         BufferedReader bufferedReader = new BufferedReader(fileReader)) {
+      // Cache for future calls
+      mUuid = UUID.fromString(bufferedReader.readLine()).toString();
+    } catch (IOException | IllegalArgumentException e) {
+      // do nothing, try other sources
+    }
+
+    // We could have returned inside try clause,
+    // but putting it like this here makes it immediately
+    // visible.
```
Comment (ide) [inline packages/expo-constants/android/src/main/java/expo/modules/constants/ExponentInstallationId.java:57]: it's also better to put only the code that could throw inside of a try-clause so that errors from code like this don't accidentally get caught

File: packages/expo-constants/android/src/main/java/expo/modules/constants/ExponentInstallationId.java [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+    if (mUuid != null) {
+      return mUuid;
+    }
+
+    // In November 2020 we decided to move installationID (backed by LEGACY_UUID_KEY value) from backed-up SharedPreferences
+    // to non-backed text file to fix issues where devices restored from backups have the same installation IDs
```
Comment (ide) [inline packages/expo-constants/android/src/main/java/expo/modules/constants/ExponentInstallationId.java:63]:
```suggestion
    // to non-backed-up text file to fix issues where devices restored from backups have the same installation IDs
```

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/installationid/InstallationId.java [hunk 3]
```diff
@@ -2,30 +2,109 @@
...
+
+    // We could have returned inside try clause,
+    // but putting it like this here makes it immediately
+    // visible.
+    if (mUuid != null) {
+      return mUuid;
+    }
+
+    // In November 2020 we decided to move installationID (backed by LEGACY_UUID_KEY value) from backed-up SharedPreferences
+    // to non-backed text file to fix issues where devices restored from backups have the same installation IDs
```
Comment (ide) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/installationid/InstallationId.java:63]:
```suggestion
    // to a non-backed-up text file to fix issues where devices restored from backups have the same installation IDs
```

**Review by ide — APPROVED** [review]
Could you help comment / describe what code can be deleted when:

- we remove legacy Notifications?
- we remove Constants.installationId?

**Comment by sjchmiela** [comment]
What can we remove when:

- once we remove legacy Notifications — we will be able to remove `ExponentNotificationIntentService` (not mentioned in this PR), but I think we would still keep `ExponentSharedPreferences` and its migrator as it provides installation ID for scoped `expo-constants` and `expo-notifications`
- once we remove legacy Notifications **and** `Constants.installationId` — we would be able to remove `ExponentSharedPreferences`'  `getOrCreateUUID` in favor of moving the unscoped UUID code "closer" to `expo-notifications` (as this would be the only remaining piece of code using it). `ScopedInstallationIdProvider` could be initialized with `ScopedContext` (it already is) and it could try to fetch installation ID from either scoped storage or from unscoped storage (as it already does https://github.com/expo/expo/blob/319d8f1ba5afce810a0d0fa9021c6d8535ef4527/android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/notifications/ScopedInstallationIdProvider.java#L22-L45), but it wouldn't need `ExponentSharedPreferences` to do so.

**Comment by brentvatne** [comment]
@sjchmiela - i cherry-picked the ios companion to this into sdk-40, shall we land this and cherry-pick it there as well? cc @byCedric to time versioning android around this

**Comment by sjchmiela** [comment]
Thanks, sorry for not letting you know — I planned to cherry-pick both of the "companion pull request" at once once this got 100% approved as well. Thank you for taking care of that!

As one can see, I merged this and cherry-picked the commit to `sdk-40`. 🙂
