### PR TITLE
[dev-launcher][ios] Fix handling deep links 

### LINKED ISSUE #32496: [SKD 52] deep link is not work
### Minimal reproducible example

https://github.com/AruSeito/expo-test

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

- Run `bunx uri-scheme open myapp:///auth/index --ios`
- Open the Auth page

I can see this, but when I press my-app, not open auth page.
iShot_2024-10-31_17 17 38

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.09.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.13 => 52.0.0-preview.13 
      expo-router: ~4.0.0-preview.8 => 4.0.0-preview.8 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Closes ENG-14002
Closes #32496

# How

With bridgeless mode on by default we can no longer rely on `[_appBridge isValid]` to verify the state of the app, this PR updates the dev-launcher logic to check for the `reactHost` instance in order to determine if the app is running and then process the deep link. We we're also not proving the correct `launchOptions` when recreating the rootView

# Test Plan

FabricTester on iOS

https://github.com/user-attachments/assets/3efe3642-c2ae-46ed-8f86-573129cec199

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by douglowder — APPROVED** [review]

File: packages/expo-dev-launcher/ios/ReactDelegateHandler/ExpoDevLauncherReactDelegateHandler.swift [hunk 1]
```diff
@@ -5,6 +5,7 @@ import EXUpdatesInterface
 
 @objc
 public class ExpoDevLauncherReactDelegateHandler: ExpoReactDelegateHandler, EXDevLauncherControllerDelegate {
+  public weak var rctAppDelegate: RCTAppDelegate?
```
Comment (Kudo) [inline packages/expo-dev-launcher/ios/ReactDelegateHandler/ExpoDevLauncherReactDelegateHandler.swift:8]: nit: maybe add some helper functions than accessing the member directly. e.g. `isReactInstanceValid` or `destroyReactInstance` or even `getRootViewFactory`

File: packages/expo-dev-launcher/ios/EXDevLauncherController.h [hunk 2]
```diff
@@ -27,6 +28,8 @@ NS_ASSUME_NONNULL_BEGIN
 
 @protocol EXDevLauncherControllerDelegate <NSObject>
 
+@property (nonatomic, weak) RCTAppDelegate *rctAppDelegate;
```
Comment (Kudo) [inline packages/expo-dev-launcher/ios/EXDevLauncherController.h:31]: that seems not being used?
looks like we only use `[self.delegate rctAppDelegate]` which stands for `ExpoDevLauncherReactDelegateHandler`

File: packages/expo-dev-launcher/ios/EXDevLauncherController.m [hunk 3]
```diff
@@ -605,6 +607,11 @@ - (void)_initAppWithUrl:(NSURL *)appUrl bundleUrl:(NSURL *)bundleUrl manifest:(E
 
 - (BOOL)isAppRunning
 {
+  if([_appBridge isProxy]){
+    RCTHost *reactHost =  [self.delegate rctAppDelegate].rootViewFactory.reactHost;
```
Comment (Kudo) [inline packages/expo-dev-launcher/ios/EXDevLauncherController.m:611]: the `[self.delegate rctAppDelegate]` is weak reference so it could be nil, we should handle this case

File: packages/expo-dev-launcher/ios/EXDevLauncherController.m [hunk 4]
```diff
@@ -327,6 +327,8 @@ - (void)navigateToLauncher
   [self _applyUserInterfaceStyle:UIUserInterfaceStyleUnspecified];
 
   [self _removeInitModuleObserver];
+  // Reset app react host
+  [[self.delegate rctAppDelegate].rootViewFactory setReactHost:nil];
```
Comment (Kudo) [inline packages/expo-dev-launcher/ios/EXDevLauncherController.m:331]: the `[self.delegate rctAppDelegate]` is weak reference so it could be nil, we should handle this case

**Review by lukmccall — APPROVED** [review]

File: packages/expo-dev-launcher/ios/ReactDelegateHandler/ExpoDevLauncherReactDelegateHandler.swift (hunk 1 above)
Comment (gabrieldonadel) [reply packages/expo-dev-launcher/ios/ReactDelegateHandler/ExpoDevLauncherReactDelegateHandler.swift]: makes sense, I added `isReactInstanceValid ` and `destroyReactInstance `

File: packages/expo-dev-launcher/ios/EXDevLauncherController.h (hunk 2 above)
Comment (gabrieldonadel) [reply packages/expo-dev-launcher/ios/EXDevLauncherController.h]: actually, `self.delegate` was an `EXDevLauncherControllerDelegate`, so that's why it was declared like this but I've just updated it to be `ExpoDevLauncherReactDelegateHandler `

**Review by Kudo — APPROVED** [review]
