### PR TITLE
[core] Catch errors thrown in event listeners

### LINKED ISSUE #29999: [expo-video] Crash when error thrown in listener callback
### Minimal reproducible example

https://github.com/expo/expo/tree/main/apps/bare-expo

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When an error is thrown in JS inside of a VideoPlayer callback it causes the app to crash instead of showing a redbox with the JS error.

This seems to be because the code that calls into JS in EventEmitter.cpp doesn't catch errors thrown by jsi.

To repro:

- Add `throw new Error()` in [the `player.addListener` callback](https://github.com/expo/expo/blob/41c96200719e27cdcd7393503c0a3d70db0aae27/apps/native-component-list/src/screens/Video/VideoScreen.tsx#L146)
- Open Components -> Video
- Toggle "Log events" on
- Click "Toggle" to trigger a pause event

Crash log:

```
Thread 28 Crashed:: com.facebook.react.JavaScript
0   libsystem_kernel.dylib        	       0x1074353b0 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x10749b124 pthread_kill + 256
2   libsystem_c.dylib             	       0x1801655c0 abort + 104
3   libc++abi.dylib               	       0x1802a7778 abort_message + 128
4   libc++abi.dylib               	       0x180298eb0 demangling_terminate_handler() + 272
5   libobjc.A.dylib               	       0x1800634a8 _objc_terminate() + 140
6   libc++abi.dylib               	       0x1802a6c50 std::__terminate(void (*)()) + 12
7   libc++abi.dylib               	       0x1802a6c00 std::terminate() + 52
8   BareExpo                      	       0x10108447c expo::EventEmitter::emitEvent(facebook::jsi::Runtime&, facebook::jsi::Object const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, facebook::jsi::Value const*, unsigned long) + 148 (EventEmitter.cpp:152)
9   BareExpo                      	       0x101084a5c expo::EventEmitter::emitEvent(facebook::jsi::Runtime&, facebook::jsi::Object&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<facebook::jsi::Value, std::__1::allocator<facebook::jsi::Value>> const&) + 96 (EventEmitter.cpp:185)
10  BareExpo                      	       0x1010c3474 +[EXJSIUtils emitEvent:toObject:withArguments:inRuntime:] + 240 (EXJSIUtils.mm:154)
11  BareExpo                      	       0x101199ee8 specialized closure #1 in SharedObject.emit<each A>(event:arguments:) + 1304 (SharedObject.swift:71)
12  BareExpo                      	       0x100bbc590 thunk for @escaping @callee_guaranteed () -> () + 48
13  BareExpo                      	       0x10109daa4 decltype(std::declval<void () block_pointer __strong&>()()) std::__1::__invoke[abi:ue170006]<void () block_pointer __strong&>(&&, decltype(std::declval<void () block_pointer __strong&>()())&&...) + 32 (invoke.h:340)
14  BareExpo                      	       0x10109d934 std::__1::__function::__func<void () block_pointer __strong, std::__1::allocator<std::__1::allocator>, void ()>::operator()() + 28 (function.h:954)
15  BareExpo                      	       0x100d7c348 std::__1::__function::__value_func<void ()>::operator()[abi:ue170006]() const + 68 (function.h:518)
16  BareExpo                      	       0x100d754cc std::__1::function<void ()>::operator()() const + 24 (function.h:1169)
17  BareExpo                      	       0x101b11644 facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3::operator()(facebook::react::JSExecutor*) const + 28 (Instance.cpp:319)
18  BareExpo                      	       0x101b1161c decltype(std::declval<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3&>()(std::declval<facebook::react::JSExecutor*>())) std::__1::__invoke[abi:ue170006]<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3&, facebook::react::JSExecutor*>(facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3&, facebook::react::JSExecutor*&&) + 36 (invoke.h:340)
19  BareExpo                      	       0x101b115c8 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ue170006]<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3&, facebook::react::JSExecutor*>(facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3&, facebook::react::JSExecutor*&&) + 32 (invoke.h:415)
20  BareExpo                      	       0x101b1159c std::__1::__function::__alloc_func<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3, std::__1::allocator<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3>, void (facebook::react::JSExecutor*)>::operator()[abi:ue170006](facebook::react::JSExecutor*&&) + 36 (function.h:193)
21  BareExpo                      	       0x101b10370 std::__1::__function::__func<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3, std::__1::allocator<facebook::react::Instance::JSCallInvoker::scheduleAsync(std::__1::function<void ()>&&)::$_3>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&) + 36 (function.h:364)
22  BareExpo                      	       0x101b37304 std::__1::__function::__value_func<void (facebook::react::JSExecutor*)>::operator()[abi:ue170006](facebook::react::JSExecutor*&&) const + 76 (function.h:518)
23  BareExpo                      	       0x101b37284 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const + 36 (function.h:1169)
24  BareExpo                      	       0x101b37250 facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8::operator()() const + 92 (NativeToJsBridge.cpp:308)
25  BareExpo                      	       0x101b371e8 decltype(std::declval<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8&>()()) std::__1::__invoke[abi:ue170006]<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8&>(facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8&) + 24 (invoke.h:340)
26  BareExpo                      	       0x101b371a0 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ue170006]<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8&>(facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8&) + 24 (invoke.h:415)
27  BareExpo                      	       0x101b3717c std::__1::__function::__alloc_func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>&&)::$_8, 
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/janicduplessis/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check for common project setup issues
✖ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.80.3
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.3
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.3
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

Error: Problems validating fields in /Users/janicduplessis/Developer/expo/apps/bare-expo/app.json. Learn more.
 • should NOT have additional property 'facebookScheme'.
 • should NOT have additional property 'facebookAppId'.
 • should NOT have additional property 'facebookDisplayName'.
 • Field: notification - should NOT have additional property 'serviceWorkerPath'.
 • Field: notification - should NOT have additional property 'vapidPublicKey'.
 • Field: ios - should NOT have additional property 'scheme'.
 • Field: android - should NOT have additional property 'scheme'.

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@8.0.0 - expected version: 8.0.1
  expo@51.0.8 - expected version: ~51.0.14
  expo-camera@15.0.9 - expected version: ~15.0.11
  expo-dev-client@4.0.14 - expected version: ~4.0.18
  expo-image@1.12.9 - expected version: ~1.12.12
  expo-notifications@0.28.3 - expected version: ~0.28.9
  expo-splash-screen@0.27.4 - expected version: ~0.27.5
  @types/react@18.0.14 - expected version: ~18.2.79
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Fixes #29999 

# How

Added a try/catch around the listeners calls and used RN's `handleJSError` function to show the error in the RedBox.
Updated web implementation accordingly.

# Test Plan

- Followed repro steps from #29999, it works as expected now - the app doesn't crash and the error is shown in RedBox
- Added tests to test-suite

Screenshot 2024-06-28 at 12 50 03

### CODE REVIEW

File: packages/expo-modules-core/common/cpp/EventEmitter.cpp [hunk 1]
```diff
@@ -2,6 +2,8 @@
 #include "EventEmitter.h"
 #include "LazyObject.h"
 
+#include <cxxreact/ErrorUtils.h>
```
Comment (Kudo) [inline packages/expo-modules-core/common/cpp/EventEmitter.cpp:5]: nit: little afraid if this import will break use_frameworks. could you help to check it?

**Review by Kudo — APPROVED** [review]

File: packages/expo-modules-core/common/cpp/EventEmitter.cpp (hunk 1 above)
Comment (Kudo) [reply packages/expo-modules-core/common/cpp/EventEmitter.cpp:5]: checking on sdk 51 blank project and it should be fine.
