### PR TITLE
fix(expo,expo-modules-core): Fix forced type-chain on `@types/node` and `metro-require.d.ts`

### LINKED ISSUE #40765: Typed routes brings in @types/node locally resulting in CI inconsistency
### Minimal reproducible example

https://github.com/kieran-osgood/expo-router-ci-types-reproduction/blob/main/constants/reproduction.ts

### Steps to reproduce

Now I'm certain I must be missing something in the documentation or issues but I can't seem to find it

I was experiencing a CI `@typescript-eslint` rule fail for `unsafe assignment of any`, which only happened on CI not locally.

Turned out to be due to the `expo-env.d.ts` that is not committed - including the "expo/types" brings in `@types/node` which types the `process.env` values as `string | undefined`, whilst on CI they would be `any`.

Everything seems to suggest this file shouldn't be included, but I'm not sure if `@types/node` being a side effect only locally is intentional.
 
Reproduction:
- blank expo router project
- *prior* to running `expo start` the types of `process.env.*` are not available

Image

- Running `expo start` the types are available

Image
- These types are stored in expo-env.d.ts but not committed
- CI will not have these types during typechecking

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 24.9.0 - /opt/homebrew/bin/node
      npm: 11.4.1 - ~/.bun/bin/npm
      Watchman: 2025.09.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/lib/ruby/gems/3.4.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2025.1 AI-251.27812.49.2514.14171003
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.20 => 54.0.21
      expo-router: ~6.0.13 => 6.0.14
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
      react-native-web: ~0.21.0 => 0.21.2
    npmGlobalPackages:
      eas-cli: 16.24.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by kitten**
# Why

Resolves #40765
Resolves DVT-53

~~**Note: This is a breaking change and shouldn't be backported.**~~

**Edit: This is potentially not a breaking change, due to globals referencing `NodeJS` namespace in current `@types/node`. Maybe a candidate for backporting to SDK 54**

---

The `expo/types` pull in `@types/node` via a type reference. However, it's not desirable for `@types/*` references to be pulled in explicitly and this can lead to type pollution, unless the requesting typings declaration actually must rely on these types. This is not the case for Expo as a whole.

`expo-modules-core` already defines a subset of `process.env.*` it needs and doesn't cause `@types/node` to be explicitly requested. It's better for us to be explicit about the `expo/types -> expo-modules-core/types -> expo-modules-core/build/ts-declarations/global` relationship instead.

`metro-require.d.ts` doesn't sufficiently define the NodeJS and environment types it's trying to enhance. Notably `NodeModule` it references doesn't exist in its scope (or at all, really). It also is a better place for the `process.env.NODE_ENV` enhancement that's currently in `global.d.ts`.

# How

- Remove `types="node"` reference from `expo/types`
- Add explicit import for `global` types in `expo-modules-core/types`
- Move `process.env` type declaration to `metro-require.d.ts` and leave comment
- Fix up `metro-require.d.ts` structure to fix deprecations
- Add missing `Process` and `ProcessEnv` enhancements to mirror `expo-modules-core`'s types and correctly extend `env`

# Test Plan

There's two problems that make this hard to test and guarantee to be working:
- we're shipping `.ts` for now, which causes many problems, including that it makes typings behave more like if the user declared them and can bypass some isolation in TypeScript
- Metro via `jest-worker` and `jest-validate`, and `react-native` via Jest itself depend on `@types/node` so it's often picked up already and not optional / hard to exclude
- This behaves differently in isolated and non-isolated dependencies (expected)

Tested in both isolated pnpm and hoisted installations. The `process.env.NODE_ENV` types are correct once `expo-env.d.ts` is generated. Otherwise, they point primarily to `expo-modules-core`'s `ts` files. (Not intended but acceptable given that they're raw TS files)

Easiest way to test this:
- `pnpx create-expo-app --no-install`
- delete `pnpm-workspace.yaml` and use isolated install
- apply modifications
- check `process.env.NODE_ENV`, `require`, `require.context`, and `module.exports` types

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

File: packages/expo/types/metro-require.d.ts [hunk 1]
```diff
@@ -1,11 +1,20 @@
...
-declare var module: NodeModule;
+// NOTE: This module is named `metro-require.d.ts` for backwards compatibility, since it's accessible to users
+// However, it's supposed to be understood more as a "Metro environment" typings file that provides types for `require` and `module`,
+// regardless of if `@types/node` is present, and/or, to enhance `@types/node` if it's present
 
 declare namespace __MetroModuleApi {
-  interface RequireContext {
+  export interface ProcessEnv {
+    readonly NODE_ENV: 'development' | 'production' | 'test';
+    [key: string]: string | undefined;
```
Comment (hassankhan) [inline packages/expo/types/metro-require.d.ts:10]: The index signature in `ExpoProcessEnv` (in `packages/expo-modules-core/src/ts-declarations/global.ts`) is `[key: string]: any`, should they be aligned?

**Review by hassankhan — APPROVED** [review]

File: packages/expo/types/metro-require.d.ts (hunk 1 above)
Comment (kitten) [reply packages/expo/types/metro-require.d.ts:10]: I believe the one in Node is `Dict<string>`. I generally think we should narrow the other one but don't know whether that's safe to do at the moment. In theory, the Node one (and this one) should be narrowing the values again though, unless I'm mistaken
