### PR TITLE
[unimodules] Fix problems for when use_frameworks! is enabled

### LINKED ISSUE #29: Is this working with podfile "use_frameworks!" ?
I can't build this with "react-native-charts-wrapper".
Because I need use "use_frameworks!" in the podfile.
Any solutions for this?

RN 0.59.1

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/unimodules/react-native-unimodules/issues/29.

# How

Externing functions from one framework so that another framework actually implements them either isn't possible or isn't obvious how to do.

Instead of fighting C linking, let's use unimodules architecture to not only fix the issue, but also enable some third-party logs listeners:
- `UMLogManager` is a singleton module
- `UMLog{Warn,Info,Error}` functions grab the instance of `UMLogManager` and call appropriate methods
- `UMLogManager` selects `UMLogHandler`s from among singleton modules
- `UMReactLogHandler` is a singleton module in `UMReactNativeAdapter` which is detected by `UMLogManager`. `UMLogManager` forwards logging calls to `UMReactLogHandler` which calls appropriate `RCT…` methods.

To fix usage within frameworks I also had to remove declarations of implementation of a protocol — interfaces-only pods aren't packaged as frameworks so we can't import them in frameworks. https://github.com/expo/expo/commit/e40683da55a3cea8a34d28b5b569b2dcdcf27367 We will need to propagate this change to other unimodules too.

# Test Plan

`UMLogWarn` and `console.warn` called in different places show RN warnings.

### CODE REVIEW

File: packages/@unimodules/core/ios/UMCore/Services/UMLogManager.h [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// Copyright 2019-present 650 Industries. All rights reserved.
```
Comment (tsapeta) [inline packages/@unimodules/core/ios/UMCore/Services/UMLogManager.h]: Inconsistency alert here, please decide whether the copyright is since 2015 or 2019 😅

**Review by tsapeta — APPROVED** [review]
Looks great! 💪💯
