### PR TITLE
[expo-notifications] Add support for custom icons and colors

### LINKED ISSUE #7961: [Bare] expo-notifications does not handle notification payload on Android
### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.62.2 => 0.62.2 

- Standalone (bare workflow)
- Android

### Steps to Reproduce

Send a FCM message with both `notification` and `data` payload:

```js
    {
      notification: {
        title: "Test",
        body: "Hello world!",
        badge: "1",
        sound: "default",
      },
      data: {
        key: value,
      },
	}
```

When app is in the background, FCM itself handles the `notification` payload and shows the notification.

When app is in the foreground, FCM will not do anything, but expo-notifications does not handle the `notification` payload either. So an empty notification is shown.

### Expected Behavior

According to Firebase [doc](https://firebase.google.com/docs/cloud-messaging/android/receive#override-onmessagereceived), we should check the payload if the app's in the foreground.

```java
    // Check if message contains a data payload.
    if (remoteMessage.getData().size() > 0) {
        Log.d(TAG, "Message data payload: " + remoteMessage.getData());

        if (/* Check if data needs to be processed by long running job */ true) {
            // For long-running tasks (10 seconds or more) use WorkManager.
            scheduleJob();
        } else {
            // Handle message within 10 seconds
            handleNow();
        }

    }

    // Check if message contains a notification payload.
    if (remoteMessage.getNotification() != null) {
        Log.d(TAG, "Message Notification Body: " + remoteMessage.getNotification().getBody());
    }

```

### Actual Behavior

expo-notifications, however, only extract `data` from the message, so `notification` is not handled: 

https://github.com/expo/expo/blob/c37c9afa3674c6dd49f251f21b0532a69545f9e4/packages/expo-notifications/android/src/main/java/expo/modules/notifications/FirebaseListenerService.java#L88-L97

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/expo/expo/issues/7961#issuecomment-618868603.

# How

- added a way to set a custom icon for Android notifications
- added a way to set a custom default color for Android notifications as well as in runtime on per-notification basis 

# Test Plan

Added a test case for custom-set color.

### CODE REVIEW

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.java [hunk 1]
```diff
@@ -205,4 +216,53 @@ private int getPriority() {
...
+   *
+   * @return Resource ID for icon that should be used as a notification icon.
+   */
+  protected int getIcon() {
+    try {
+      ApplicationInfo ai = getContext().getPackageManager().getApplicationInfo(getContext().getPackageName(), PackageManager.GET_META_DATA);
+      if (ai.metaData.containsKey(META_DATA_DEFAULT_ICON_KEY)) {
+        return ai.metaData.getInt(META_DATA_DEFAULT_ICON_KEY);
+      }
+    } catch (Exception e) {
```
Comment (mczernek) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.java:232]: I know it is common pattern across expo codebase, but I dislike catching such general error.

I assume this is to catch `PackageManager.NameNotFoundException`? Maybe we should consider catching it explicitly and rethrowing? It should never ever happen and only scenario I can think of it occurring  is when someone makes some unintentional change in here.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.java [hunk 2]
```diff
@@ -205,4 +216,53 @@ private int getPriority() {
...
+      ApplicationInfo ai = getContext().getPackageManager().getApplicationInfo(getContext().getPackageName(), PackageManager.GET_META_DATA);
+      if (ai.metaData.containsKey(META_DATA_DEFAULT_COLOR_KEY)) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
+          return getContext().getResources().getColor(ai.metaData.getInt(META_DATA_DEFAULT_COLOR_KEY), null);
+        } else {
+          return getContext().getResources().getColor(ai.metaData.getInt(META_DATA_DEFAULT_COLOR_KEY));
+        }
+      }
+    } catch (Exception e) {
+      Log.e("expo-notifications", "Could not have fetched default notification color.");
```
Comment (mczernek) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.java:262]: Same as above ^

**Review by mczernek — APPROVED** [review]
I generally approve, but please consider suggested changes to catching exceptions.

**Review by mczernek — APPROVED** [review]
:100:
