### PR TITLE
Fix expo-file-system@next types

### LINKED ISSUE #33731: Type error in expo-file-system/next: getPathFromURLPosix
### Minimal reproducible example

https://github.com/expo/expo

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

This line in `getPathFromURLPosix` is tripping up TypeScript:

```
const third = pathname.charAt(pathname, n + 2) | 0x20;
```

https://github.com/expo/expo/blob/40bf344a56128cabc41ea88c06184adea4c84422/packages/expo-file-system/src/next/pathUtilities/url.ts#L73

I think `charAt` only takes a single arg (`pos`) and returns a string, so it's not clear what the intent of this line is.

### Environment

```text
N/a
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Validate packages against React Native Directory package metadata
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: lucide-react-native
Unmaintained: @gorhom/portal
No metadata available: @babel/plugin-proposal-export-namespace-from, @breezystack/lamejs, @datadog/browser-logs, @datadog/browser-rum, @siteed/expo-audio-stream, @supabase/postgrest-js, crypto-es, date-fns, dedent, editor, eventemitter3, expo-standard-web-crypto, jsqr, jszip, lodash, mobx, mobx-react-lite, parchment, postgres, quill, quill-delta, remark-frontmatter, remark-gfm, remark-parse, resolve-from, ulid, unified, unist-util-visit, uqr, yjs
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Closes https://github.com/expo/expo/issues/33731

# How

I went through the tsc errors and fixed all of them. 
IMO it's still not a full fix, since we should have no tsc errors that occur in a default template but not when running tsc inside a module while developing.

Our tsconfig for template and for modules is not in sync and/or tsc should not typecheck node_modules even when importing from it.

# Test Plan

Tested this fixes the community repro.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-file-system/src/next/pathUtilities/url.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ function getPathFromURLPosix(url) {
   const pathname = url.pathname;
   for (let n = 0; n < pathname.length; n++) {
     if (pathname[n] === '%') {
-      const third = pathname.charAt(pathname, n + 2) | 0x20;
+      const third = pathname.charAt(n + 2) as any | 0x20;
```
Comment (lukmccall) [inline packages/expo-file-system/src/next/pathUtilities/url.ts:73]:
```suggestion
      const third = +pathname.charAt(n + 2) | 0x20;
```
it should produce the same result, but as least we don't need to cast to `any`

File: packages/expo-file-system/src/next/streams.ts [hunk 2]
```diff
@@ -36,7 +36,7 @@ export class FileSystemReadableStreamSource implements UnderlyingByteSource {
       theView.set(bytes, theView.byteOffset);
     } else {
       for (let i = 0; i < bytes.length; i++) {
-        theView[i + theView.byteOffset] = bytes[i];
+        (theView as any)[i + theView.byteOffset] = bytes[i];
```
Comment (lukmccall) [inline packages/expo-file-system/src/next/streams.ts:39]: Do we have to cast it to any?

**Review by lukmccall — APPROVED** [review]
