### PR TITLE
[android][media-library] update check for album corruption

### LINKED ISSUE #30869: [android][media-library] With media management permission, addAssetsToAlbumAsync fails on albums containing folders
### Minimal reproducible example

https://github.com/Nafeij/my-app

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

https://github.com/expo/expo/blob/138283bf6b277d209638f37f4ff3c6b691c26e84/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/albums/AddAssetsToAlbum.kt#L48

When adding assets to an album, the above check is performed with the assumption that this is a [migrated](https://github.com/expo/fyi/blob/main/android-r.md#album-migration) or app-created album. However, it is still possible for apps to obtain `MANAGE_MEDIA` permissions and operate on external albums, which may themselves contain nested albums or folders. In this case, an unexpected error is thrown stating that the Media Library is corrupted.

# To reproduce:
Prepare an album containing an image and a folder and run the reproducible example to add another image to said album.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ~51.0.24 => 51.0.24 
      expo-router: ~3.5.20 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by Nafeij**
# Why

We can't assume an album is corrupted because it contains non-files. In an app with file manager perms, it's possible for expo to access external albums which may be nested or otherwise contain directories.

Closes #30869

~~Also feel free to suggest alternative checks.~~ We should also check if the non-file is a non-directory (https://github.com/expo/expo/pull/31027#discussion_r1732969029)

# How

Add an additional check to prevent the exception being thrown for nested but otherwise valid albums.

# Test Plan

See the `Minimal reproducible example` in #30869 to reproduce original behavior.

Before:

https://github.com/user-attachments/assets/f6edbc3f-2850-4ae6-97fd-12caa8ce4ae9

After:

https://github.com/user-attachments/assets/8527535f-5926-488f-82fd-bd6ee82956aa

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/albums/AddAssetsToAlbum.kt [hunk 1]
```diff
@@ -43,11 +43,6 @@ internal class AddAssetsToAlbum(
         albumCursor.moveToNext()
         val filePathColumnIndex = albumCursor.getColumnIndex(MediaStore.Images.Media.DATA)
         val fileInAlbum = File(albumCursor.getString(filePathColumnIndex))
-
-        // Media store table can be corrupted. Extra check won't harm anyone.
-        if (!fileInAlbum.isFile) {
-          throw MediaLibraryException()
-        }
```
Comment (behenate) [inline packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/albums/AddAssetsToAlbum.kt:50]: Maybe we can keep a check like this:
```        
// Media store table can be corrupted. Extra check won't harm anyone.
if (!fileInAlbum.isFile && !fileInAlbum.isDirectory) {
  throw MediaLibraryException()
}
 ```
 This should be safer around symbolic links, files with no read permission etc and should still work with subdirectories.

Comment (Nafeij) [reply packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/albums/AddAssetsToAlbum.kt]: Good idea, thanks.

**Review by behenate — APPROVED** [review]

**Comment by behenate** [comment]
@Nafeij Thank you for the contribution!
