### PR TITLE
[android] Fix versioned permissions checks

### LINKED ISSUE #6339: [android] Scoped permissions are always denied on SDK 36
Follow up to #5061 

During QA, it looks like scoped permissions are not working properly on Android in the versioned SDK 36 code. In `native-component-list,` if the sdkVersion is set to 36.0.0, opening any of the screens that request permission (e.g. Calendar, Location, Recording) and interacting to initiate the permissions request does not produce the expected popup window. On the Permissions screen, all of the permissions return with `denied`.

If the sdkVersion is set to UNVERSIONED, everything works properly. Also, running an older SDK version project works fine. It appears to make no difference whether or not some other experience has been granted the permission, or if it's the first time the client has requested the permission at all -- all requests just fail for SDK 36. @lukmccall could you look into this and figure out what's going wrong here?

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolves https://github.com/expo/expo/issues/6339

# How

`ReactNativeActivity` now implements versioned `PermissionAwareActivity` interface.
Also, I've move permissions related method form `BaseExperienceActivity` to `ReactNativeActivity`.

# Test plan

Unfortunately, `et add-sdk-version --platform android` failed on a different task. However, I've copied my changes into a separate script:

```
MAJOR_ABI_VERSION='37'
ABI_VERSION='abi37_0_0'
NEWLINE='\
'
# Update classes that implement DefaultHardwareBackBtnHandler or PermissionAwareActivity
BACK_BUTTON_HANDLER_CLASS='com.facebook.react.modules.core.DefaultHardwareBackBtnHandler'
PERMISSION_AWARE_ACTIVITY_CLASS='com.facebook.react.modules.core.PermissionAwareActivity'
PERMISSION_LISTENER_CLASS='com.facebook.react.modules.core.PermissionListener'
find expoview/src/main/java/host/exp/exponent -iname '*.java' -type f -print0 | xargs -0 sed -i '' -e "s/ADD_NEW_SDKS_HERE/BEGIN_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ $ABI_VERSION\.$BACK_BUTTON_HANDLER_CLASS,$NEWLINE\ \ \ \ $ABI_VERSION\.$PERMISSION_AWARE_ACTIVITY_CLASS,$NEWLINE\ \ \ \ \/\/ END_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ \/\/ ADD_NEW_SDKS_HERE/" \
# Add implementation of PermissionAwareActivity.requestPermissions
find expoview/src/main/java/host/exp/exponent -iname '*.java' -type f -print0 | xargs -0 sed -i '' "s/ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_HERE/BEGIN_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ @Override$NEWLINE\ \ \ \ public\ void\ requestPermissions(String\[\]\ strings\,\ int\ i\,\ $ABI_VERSION\.$PERMISSION_LISTENER_CLASS\ permissionListener)\ {$NEWLINE\ \ \ \ \ \ super\.requestPermissions(strings\,\ i\,\ permissionListener::onRequestPermissionsResult);$NEWLINE\ \ \ \ }$NEWLINE\ \ \ \ \/\/ END_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ \/\/ ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_HERE/"
```
And run it in android folder. This script generated correct file: 
```
// Copyright 2015-present 650 Industries. All rights reserved.

package host.exp.exponent.experience;

// Implement for each version.
public class MultipleVersionReactNativeActivity extends ReactNativeActivity implements
    // The 4-space indentation is used by android-build-aar.sh.
    // WHEN_DISTRIBUTING_REMOVE_FROM_HERE
    // WHEN_PREPARING_SHELL_REMOVE_FROM_HERE
    // BEGIN_SDK_33
    abi33_0_0.com.facebook.react.modules.core.DefaultHardwareBackBtnHandler,
    // END_SDK_33
    // BEGIN_SDK_34
    abi34_0_0.com.facebook.react.modules.core.DefaultHardwareBackBtnHandler,
    // END_SDK_34
    // BEGIN_SDK_35
    abi35_0_0.com.facebook.react.modules.core.DefaultHardwareBackBtnHandler,
    // END_SDK_35
    // BEGIN_SDK_36
    abi36_0_0.com.facebook.react.modules.core.DefaultHardwareBackBtnHandler,
    abi36_0_0.com.facebook.react.modules.core.PermissionAwareActivity,
    // END_SDK_36
    // BEGIN_SDK_37
    abi37_0_0.com.facebook.react.modules.core.DefaultHardwareBackBtnHandler,
    abi37_0_0.com.facebook.react.modules.core.PermissionAwareActivity,
    // END_SDK_37
    // ADD_NEW_SDKS_HERE
    // WHEN_PREPARING_SHELL_REMOVE_TO_HERE
    // WHEN_DISTRIBUTING_REMOVE_TO_HERE
    com.facebook.react.modules.core.DefaultHardwareBackBtnHandler {

    // BEGIN_SDK_36
    @Override
    public void requestPermissions(String[] strings, int i, abi36_0_0.com.facebook.react.modules.core.PermissionListener permissionListener) {
      super.requestPermissions(strings, i, permissionListener::onRequestPermissionsResult);
    }
    // END_SDK_36
    // BEGIN_SDK_37
    @Override
    public void requestPermissions(String[] strings, int i, abi37_0_0.com.facebook.react.modules.core.PermissionListener permissionListener) {
      super.requestPermissions(strings, i, permissionListener::onRequestPermissionsResult);
    }
    // END_SDK_37
    // ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_HERE

}
```

### CODE REVIEW

File: android/expoview/src/main/java/host/exp/exponent/experience/MultipleVersionReactNativeActivity.java [hunk 1]
```diff
@@ -18,10 +18,19 @@
...
     // BEGIN_SDK_36
     abi36_0_0.com.facebook.react.modules.core.DefaultHardwareBackBtnHandler,
+    abi36_0_0.com.facebook.react.modules.core.PermissionAwareActivity,
     // END_SDK_36
     // ADD_NEW_SDKS_HERE
     // WHEN_PREPARING_SHELL_REMOVE_TO_HERE
     // WHEN_DISTRIBUTING_REMOVE_TO_HERE
     com.facebook.react.modules.core.DefaultHardwareBackBtnHandler {
 
+    // PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_SDK_36
```
Comment (sjchmiela) [inline android/expoview/src/main/java/host/exp/exponent/experience/MultipleVersionReactNativeActivity.java]:
```suggestion
    // BEGIN_SDK_36
```

File: android/expoview/src/main/java/host/exp/exponent/experience/MultipleVersionReactNativeActivity.java [hunk 2]
```diff
@@ -18,10 +18,19 @@
...
+    @Override
+    public void requestPermissions(String[] strings, int i, abi36_0_0.com.facebook.react.modules.core.PermissionListener permissionListener) {
+      super.requestPermissions(strings, i, permissionListener::onRequestPermissionsResult);
+    }
+    // END_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_SDK_36
```
Comment (sjchmiela) [inline android/expoview/src/main/java/host/exp/exponent/experience/MultipleVersionReactNativeActivity.java]:
```suggestion
    // END_SDK_36
```

File: android/expoview/src/main/java/host/exp/exponent/experience/MultipleVersionReactNativeActivity.java [hunk 3]
```diff
@@ -18,10 +18,19 @@
...
+    // ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION
```
Comment (sjchmiela) [inline android/expoview/src/main/java/host/exp/exponent/experience/MultipleVersionReactNativeActivity.java]:
```suggestion
    
    // ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_HERE
```

File: tools/expotools/src/versioning/android/android-build-aar.sh [hunk 4]
```diff
@@ -117,4 +117,10 @@ sed -i '' "/$REPLACE_TEXT/$SED_APPEND_COMMAND\ \ \ \ \/\/ BEGIN_SDK_$MAJOR_ABI_V
 BACK_BUTTON_HANDLER_CLASS='com.facebook.react.modules.core.DefaultHardwareBackBtnHandler'
 find expoview/src/main/java/host/exp/exponent -iname '*.java' -type f -print0 | xargs -0 sed -i '' "s/ADD_NEW_SDKS_HERE/BEGIN_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ $ABI_VERSION\.$BACK_BUTTON_HANDLER_CLASS,$NEWLINE\ \ \ \ \/\/ END_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ \/\/ ADD_NEW_SDKS_HERE/"
 
+# Update classes that implement PermissionAwareActivity
+PERMISSION_AWARE_ACTIVITY_CLASS='com.facebook.react.modules.core.PermissionAwareActivity'
+PERMISSION_LISTENER_CLASS='com.facebook.react.modules.core.PermissionListener'
+find expoview/src/main/java/host/exp/exponent -iname '*.java' -type f -print0 | xargs -0 sed -i '' "s/ADD_NEW_SDKS_HERE/BEGIN_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ $ABI_VERSION\.$PERMISSION_AWARE_ACTIVITY_CLASS,$NEWLINE\ \ \ \ \/\/ END_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ \/\/ ADD_NEW_SDKS_HERE/"
```
Comment (sjchmiela) [inline tools/expotools/src/versioning/android/android-build-aar.sh]: Couldn't we merge this and `find` at line 118 into one, so that both `$BACK_BUTTON_HANDLER_CLASS` and `$PERMISSION_AWARE_ACTIVITY_CLASS` get added in one `find`?

File: tools/expotools/src/versioning/android/android-build-aar.sh [hunk 5]
```diff
@@ -117,4 +117,10 @@ sed -i '' "/$REPLACE_TEXT/$SED_APPEND_COMMAND\ \ \ \ \/\/ BEGIN_SDK_$MAJOR_ABI_V
...
+find expoview/src/main/java/host/exp/exponent -iname '*.java' -type f -print0 | xargs -0 sed -i '' "s/ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION/PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ @Override$NEWLINE\ \ \ \ public\ void\ requestPermissions(String\[\]\ strings\,\ int\ i\,\ $ABI_VERSION\.$PERMISSION_LISTENER_CLASS\ permissionListener)\ {$NEWLINE\ \ \ \ \ \ super\.requestPermissions(strings\,\ i\,\ permissionListener::onRequestPermissionsResult);$NEWLINE\ \ \ \ }$NEWLINE\ \ \ \ \/\/ END_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ \/\/ ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION/"
```
Comment (sjchmiela) [inline tools/expotools/src/versioning/android/android-build-aar.sh]:
```suggestion
find expoview/src/main/java/host/exp/exponent -iname '*.java' -type f -print0 | xargs -0 sed -i '' "s/ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION_HERE/BEGIN_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ @Override$NEWLINE\ \ \ \ public\ void\ requestPermissions(String\[\]\ strings\,\ int\ i\,\ $ABI_VERSION\.$PERMISSION_LISTENER_CLASS\ permissionListener)\ {$NEWLINE\ \ \ \ \ \ super\.requestPermissions(strings\,\ i\,\ permissionListener::onRequestPermissionsResult);$NEWLINE\ \ \ \ }$NEWLINE\ \ \ \ \/\/ END_SDK_$MAJOR_ABI_VERSION$NEWLINE\ \ \ \ \/\/ ADD_NEW_PERMISSION_AWARE_ACTIVITY_IMPLEMENTATION/"
```

File: tools/expotools/src/versioning/android/index.ts [hunk 6]
```diff
@@ -52,6 +52,17 @@ async function removeVersionReferencesFromFileAsync(sdkMajorVersion: string, fil
   );
 }
 
+async function removeVersionedPermissionAwareActivityImplementationFromFileAsync(sdkMajorVersion: string, filePath: string) {
```
Comment (sjchmiela) [inline tools/expotools/src/versioning/android/index.ts]: Good job on adding this function, but I think reusing existing `BEGIN/END_SDK_XX` infrastructure will be clearer and more easily maintainable (and also it has been implemented to be reused). 🌷

**Review by sjchmiela — CHANGES_REQUESTED** [review]
Could you also try adding a new SDK37 version to see if the code works as expected? The command would be `et add-sdk-version --platform android`. Then fill in the **Test plan** section of the PR description. 🙂

**Review by sjchmiela — APPROVED** [review]
Thank you! 🚀
