### PR TITLE
fix: provide more image metadata in image-picker

### LINKED ISSUE #29442: expo-image-picker and expo-media-library provide incomplete EXIF information
### Minimal reproducible example

https://github.com/Hooper93/expo-bug-report

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When I use the two tool libraries `expo-image-picker` and `expo-media-library` 
to obtain the photos I took with a Sony camera, the exif information they provide is incomplete. 

```js
{"BrightnessValue": 8.0171875, "ColorSpace": 1, "ComponentsConfiguration": [1, 2, 3, 0], "CompressedBitsPerPixel": 3, "Contrast": 0, "CustomRendered": 0, "DateTimeDigitized": "2024:04:06 09:15:26", "DateTimeOriginal": "2024:04:06 09:15:26", "DigitalZoomRatio": 1, "ExifVersion": [2, 3, 1], "ExposureBiasValue": 0, "ExposureMode": 1, "ExposureProgram": 1, "ExposureTime": 0.004, "FNumber": 4, "FileSource": 3, "Flash": 16, "FlashPixVersion": [1, 0], "FocalLenIn35mmFilm": 87, "FocalLength": 87, "ISOSpeedRatings": [200], "LensModel": "FE 24-105mm F4 G OSS", "LensSpecification": [24, 105, 4, 4], "LightSource": 10, "MaxApertureValue": 4, "MeteringMode": 2, "OffsetTime": "+08:00", "OffsetTimeDigitized": "+08:00", "OffsetTimeOriginal": "+08:00", "Orientation": 1, "PixelXDimension": 6240, "PixelYDimension": 4160, "RecommendedExposureIndex": 200, "Saturation": 0, "SceneCaptureType": 0, "SceneType": 1, "SensitivityType": 2, "Sharpness": 0, "WhiteBalance": 1}
```
↑ this is the exif of picture by Sony a7r4, Model tag is missing, but LensModel can read out, GPS information is lost too.

When I use lightroom or other software to view the exif information of these photos, it is completable. 
image
↑ the same photo can read the Make or Model exif on https://exifmeta.com

this is the photo:
DSC02727

The lost information is very random, such as the camera's device model, geographic location, lens information, etc. 

The loss of this information also shows a correlation with the shooting device. 
For example, the photos taken by my SONY camera can read the lens information, but the camera model cannot be obtained; For another example, I can only read out IOS, shutter and other information from the photos taken by the DJI drone, and the device model and lens information cannot be read, but this information exists in EXIF, and I can use other software to read it out.

```js
{"ApertureValue": 2.97, "BodySerialNumber": "6GVFL6C11109T3", "ColorSpace": 1, "ComponentsConfiguration": [1, 2, 3, 0], "Contrast": 0, "CustomRendered": 0, "DateTimeDigitized": "2023:10:04 11:34:02", "DateTimeOriginal": "2023:10:04 11:34:02", "DigitalZoomRatio": 1, "ExifVersion": [2, 3], "ExposureBiasValue": 0, "ExposureMode": 0, "ExposureProgram": 2, "ExposureTime": 0.004166666666666667, "FNumber": 2.8, "FileSource": 3, "Flash": 0, "FlashPixVersion": [1, 0], "FocalLenIn35mmFilm": 70, "FocalLength": 19.35, "GPSAltitude": 737.037, "GPSAltitudeRef": 0, "GPSGPSVersion": [2, 3, 0, 0], "GPSLatitude": 51.33297, "GPSLatitudeRef": "N", "GPSLongitude": 120.67776666666667, "GPSLongitudeRef": "E", "GPSMapDatum": "WGS-84", "GPSStatus": "A", "GainControl": 0, "ISOSpeedRatings": [100], "LensSpecification": [70, 70, 2.799999952316284, 2.799999952316284], "LightSource": 2, "MaxApertureValue": 2.97, "MeteringMode": 2, "Orientation": 1, "PixelXDimension": 4032, "PixelYDimension": 2268, "Saturation": 0, "SceneCaptureType": 0, "SceneType": 1, "SensitivityType": 2, "Sharpness": 0, "ShutterSpeedValue": 7.9069, "SubjectDistance": 0, "WhiteBalance": 0}
```
↑ photo by DJI, can only read GPS information, Model / Make / LensModel are all lost

image
↑ the same photo can read the exif on https://exifmeta.com

Is this a system limitation of IOS? Or do I need to enable some advanced permissions to see these additional exif information?

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.1.0 - /usr/local/bin/node
      Yarn: 3.6.1 - /usr/local/bin/yarn
      npm: 8.19.3 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.9 => 51.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by vonovak**
# Why

closes #29442 by adding extra metadata to the result of `ImagePicker.launchImageLibraryAsync`.

Generally speaking, with these apis, it's easy to miss this or that piece of information because the information is scattered across various places, and there are even manufacturer-specific ones, such as for [Minolta](https://developer.apple.com/documentation/imageio/kcgimagepropertymakerminoltadictionary), Canon and others.

However, I believe the TIFF information should be commonly present and also brings the result closer to Android.

# How

I'm taking metadata from [`kCGImagePropertyTIFFDictionary`](https://developer.apple.com/documentation/imageio/kcgimagepropertytiffdictionary) and merging it with the existing `exif` dictionary. In case of duplicate keys, the exif value is preserved.

I removed usage of `kCGImagePropertyOrientation` because the value, if present, is the same as the value in TIFF metadata [source](https://github.com/xybp888/iOS-SDKs/blob/d7f1be9f5b79cffcfb547bbd930f92ec0fc35038/iPhoneOS13.0.sdk/System/Library/Frameworks/ImageIO.framework/Headers/CGImageProperties.h#L75). The key is the same as well, though this is not confirmed by any docs.

# Test Plan

Tested on simulator and device

# Checklist

No need to update docs, and the rest doesn't apply imo

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-image-picker/ios/ImagePickerModule.swift [hunk 1]
```diff
@@ -143,9 +143,7 @@ public class ImagePickerModule: Module, OnMediaPickingResultHandler {
     // selection limit = 1 --> single selection, reflects the old picker behavior
     configuration.selectionLimit = options.allowsMultipleSelection ? options.selectionLimit : SINGLE_SELECTION
     configuration.filter = options.mediaTypes.toPickerFilter()
-    if #available(iOS 14, *) {
```
Comment (vonovak) [inline packages/expo-image-picker/ios/ImagePickerModule.swift:146]: the whole fn is wrapped in @available(iOS 14, *) (line 138)

**Comment by hirbod** [comment]
It would be lovely if the same functionality could be added for the Expo documents picker. They have overlapping functionality, just different picker locations.

**Review by alanjhughes — APPROVED** [review]
