### PR TITLE
[android][expo-dev-launcher] fix missing intent extras external intent

### LINKED ISSUE #31830: Launch arguments not available for E2E testing when using expo-dev-client
### Summary

**Context**
I am at the start of setting up E2E testing for our app. We have a managed Expo app using `expo-dev-client`. We want to use [maestro](https://github.com/mobile-dev-inc/maestro) as our Testing Framework. In order to inject some values when launching the app during e2e test, I am trying to use [launch arguments](https://maestro.mobile.dev/api-reference/commands/launchapp#launch-arguments) according to the Maestro documentation. Which recommends using [react-native-launch-arguments](https://www.npmjs.com/package/react-native-launch-arguments).

**Problem**
This works **when not using a development build**, but when using a development build the Launch Arguments seem to get lost. I don't think it's a Maestro specific problem. My guess is that `expo-dev-client` launches the app / bundle / metro server without the initial launch arguments when the metro server is loaded.

I couldn't find any solution or discussion about this so that's why I created this issue. Hope someone can help me solve this!
Thanks in advance! 🫶 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

expo: 51.0.28
expo-dev-client: 4.0.27
react-native-launch-arguments: 4.0.2

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.36 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.1
    Expo Workflow: managed
```

### Reproducible demo

1. Clone minimum reproducable example repo [https://github.com/BrandonYuen/expo-launch-args-issue](https://github.com/BrandonYuen/expo-launch-args-issue)
2. `npm install`
3. Create build `eas build --profile development --platform android` (did not test on iOS)
3. Launch the Android app with Launch Arguments
a. Install [Maestro](https://maestro.mobile.dev/getting-started/installing-maestro) and run `maestro test -e APP_ID=com.brandonshiftbase.expolaunchargsissue .maestro`
b. Any other method of launching the app with launch arguments
4. App will show Alert with Launch Arguments (empty with development build) on startup 

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by coolsoftwaretyler**
# Why

This is a follow up to https://github.com/expo/expo/pull/37172, which closed #31830. The [original reproducing repository](https://github.com/BrandonYuen/expo-launch-args-issue) didn't have the `clearState: true` scenario in the Maestro tests. So while #37172 fixed the issue for cases where `lastOpenedApp` is *not* `null`, the error continued to happen in clear states.

If `lastOpenedApp` was `null`, we'd end up in `handleExternalIntent`, which also wasn't passing along intent extras. We need to hang on to those for any eventual call of `createAppIntent`.

# How

I don't have as much experience with Kotlin as I do with TypeScript and Swift, so I'm not sure if this is ready to ship yet. I suspect Expo will want to do more work to maybe provide an interface for the pending extras to be stored in. I'd be happy to do that with some guidance, but I can experimentally verify that this patch fixes the issue. [See my comment on a PR with a patch into the reproducer](https://github.com/BrandonYuen/expo-launch-args-issue/pull/1#issuecomment-2954479300).

# Test Plan

1. [Here is a screen recording of the reproducer app with `clearState: true` in a Maestro test in the failure case](https://www.dropbox.com/scl/fi/aksj0oc6jqlvo4n7ivs43/bugged-behavior-clear-state.mov?rlkey=xo5xb6z8zljl7d4ggm2c6u84t&st=7i0n0jc0&dl=0).
2. I then used patch-package to test out these changes, and you can see [in this video, the behavior is correct](https://www.dropbox.com/scl/fi/iw3pxr2br20hz2962ppvm/correct-behavior-clear-state.mov?rlkey=3rmbygfpjs4be2vmlarvpuv8j&st=ei50ine3&dl=0)

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt [hunk 1]
```diff
@@ -108,6 +109,7 @@ class DevLauncherController private constructor() :
   private var appIsLoading = false
 
   private var networkInterceptor: DevLauncherNetworkInterceptor? = null
+  private var pendingIntentExtras: Bundle? = null
```
Comment (coolsoftwaretyler) [inline packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:112]: **note:** I am not so much a Kotlin dev, so GenAI helped me with this one and suggested a `Bundle` would be the appropriate data structure for this. I suspect it isn't. Happy to take a little guidance on this and adjust the approach.

File: packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt [hunk 2]
```diff
@@ -282,6 +284,8 @@ class DevLauncherController private constructor() :
   }
 
   private fun handleExternalIntent(intent: Intent): Boolean {
+    // Always store the intent extras even if we don't set the pending intent.
+    pendingIntentExtras = intent.extras
```
Comment (coolsoftwaretyler) [inline packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: **note:** this feels kinda weird, we throw away the pending intent extras if we end up using the `pendingIntentRegistry`. Maybe we should only do this if we're not setting `pendingIntentRegistry.intent`.

Comment (lukmccall) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: I have some concerns about this approach. What do you think about finding a more suitable check when we save the pending intent? Perhaps we should always set the intent as 'pending' here. Just a thought! Since you're working with code that was written 3-4 years ago, I can't quite recall why it was done this way 😅

Comment (coolsoftwaretyler) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: Yeah I agree. I tried setting the intent as pending each time, but there is a problem. If you do that, the deep link modal shows up, which I don't think we want.

Comment (coolsoftwaretyler) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: So if we changed `handleExternalIntent` to be:

```kt
  private fun handleExternalIntent(intent: Intent): Boolean {
    pendingIntentRegistry.intent = intent

    return false
  }
```

And ran a Maestro test like this:

```yaml
- launchApp:
    clearState: true
    arguments:
      EXAMPLE_ARG: "test"
```

We'd get this pop up:



This would also happen on every fresh install of the app when using dev launcher.

**Comment by 616151371** [comment]
Hello, why is there an error here，"expo-intent-launcher": "~12.1.5"
info:at expo.modules.intentlauncher.IntentLauncherModule.definition(IntentLauncherModule.kt:149)

File: packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt (hunk 2 above)
Comment (lukmccall) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: Okay, we can merge it as it is. We're planning to rewire some parts of the dev-launcher soon. I'll take a closer look at this deep linking situation then.

Could you resolve merge conflicts?

Comment (coolsoftwaretyler) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: Will do! Thanks!

Comment (coolsoftwaretyler) [reply packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:288]: Hey @lukmccall - I pulled `main` into this branch, then fixed up the merge conflicts. When I ran `yarn bundle` - the diffs in the Android and iOS bundles went away. I tried a couple more times with no effect, and it seems there are a few tests failing in CI.

Any other steps I can run to fix those up?

**Comment by lukmccall** [comment]
I'm sorry for not getting back to you sooner.

Some tests in the dev-launcher test suite don't pass. It doesn't seem to be connected to your changes, so can you rebase your PR against the current main again?

**Comment by coolsoftwaretyler** [comment]
Thanks @lukmccall. Done!

**Review by lukmccall — APPROVED** [review]
The CI is failing, but it doesn't appear to be related to this change, so I'm going to merge it.
