### PR TITLE
[android][expo/fetch] allow sending POST requests without body

### LINKED ISSUE #35950: Expo fetch post request requires a body on Android, not iOS
### Minimal reproducible example

https://github.com/ink404/fetch-repro

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

*   **Expected Behavior:** According to the [Fetch Standard](https://fetch.spec.whatwg.org/#requestinit), sending a `POST` request using `fetch` (imported from `expo/fetch`) without specifying a `body` in the `RequestInit` options should succeed without error, potentially sending a `Content-Length: 0` header. This behavior is observed correctly on iOS and Web platforms.
*   **Actual Behavior:** On **Android**, making a `POST` request using `fetch` from `expo/fetch` *without* providing a `body` consistently throws a native Java exception, causing the fetch operation to fail. This deviates from the Fetch Standard and introduces a platform-specific inconsistency.
*   **Affected Platforms:** Android

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.10.0 - /opt/homebrew/bin/node
      npm: 10.9.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.3 AI-243.22562.218.2431.13114758
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.43 => 52.0.44 
      expo-router: ~4.0.20 => 4.0.20 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.9 => 0.76.9 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by julian-dueck**
# Why

Android implementation doesn't allow sending no body if the request method is POST, PATCH or PUT. This is a limitation of the underlying okhttp library, so this is a workaround
Closes #35950

# How

If the method of the request is POST, PATCH or PUT and the body is null, set the body to a byte array of 0.

# Test Plan

Didn't test, can't get gradle to build in android studio following the instructions for contributions...

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
Thanks for the contribution! Looks good, but I would like to wait for @Kudo's review to merge it.

File: packages/expo/android/src/main/java/expo/modules/fetch/NativeRequest.kt [hunk 1]
```diff
@@ -14,6 +14,8 @@ import java.net.URL
 
 private data class RequestHolder(var request: Request?)
 
+internal val ALLOWED_METHODS_FOR_BODY = arrayOf("POST", "PUT", "PATCH")
```
Comment (Kudo) [inline packages/expo/android/src/main/java/expo/modules/fetch/NativeRequest.kt]:
```suggestion
internal val METHODS_REQUIRING_BODY = arrayOf("POST", "PUT", "PATCH")
```

File: packages/expo/android/src/main/java/expo/modules/fetch/NativeRequest.kt [hunk 2]
```diff
@@ -34,9 +36,15 @@ internal class NativeRequest(appContext: AppContext, internal val response: Nati
 
     val headers = requestInit.headers.toHeaders()
     val mediaType = headers["Content-Type"]?.toMediaTypeOrNull()
+    var reqBody = requestBody?.toRequestBody(mediaType)
+    // OkHttp requires a non-null body for POST, PATCH and PUT requests. (also for PROPPATCH and REPORT)
+    // https://github.com/expo/expo/issues/35950#issuecomment-3245173248
+    if (reqBody == null && requestInit.method in ALLOWED_METHODS_FOR_BODY) {
+      reqBody = byteArrayOf(0).toRequestBody(mediaType)
+    }
```
Comment (Kudo) [inline packages/expo/android/src/main/java/expo/modules/fetch/NativeRequest.kt]:
```suggestion
    val reqBody = requestBody?.toRequestBody(mediaType) ?: run {
      // OkHttp requires a non-null body for POST, PATCH, and PUT requests.
      // WinterTC fetch, however, does not have this limitation.
      // Provide an empty body to make OkHttp behave like WinterTC fetch.
      // Ref: https://github.com/expo/expo/issues/35950#issuecomment-3245173248
      if (requestInit.method in METHODS_REQUIRING_BODY) {
        byteArrayOf(0).toRequestBody(mediaType)
      } else {
        null
      }
    }
```

- use elvis operator
- though okhttp also enforces body for PROPPATCH and REPORT, i would not like to mention these in the comment. we did not add these method to METHODS_REQUIRING_BODY and it's not clear whether we support these methods

**Review by Kudo — COMMENTED** [review]
that's a great fix. thanks for the help. i'm leaving some nit comment and we are good to merge this fix

**Comment by julian-dueck** [comment]
changes applied :)

File: packages/expo/CHANGELOG.md [hunk 3]
```diff
@@ -8,6 +8,8 @@
 
 ### 🐛 Bug fixes
 
+- [android] allow sending a POST, PATCH or PUT request without a body ([#39363](https://github.com/expo/expo/pull/39363))
```
Comment (Kudo) [inline packages/expo/CHANGELOG.md]:
```suggestion
- [Android] allow `expo/fetch` sending a `POST`, `PATCH` or `PUT` request without a body. ([#39363](https://github.com/expo/expo/pull/39363) by [@julian-dueck](https://github.com/julian-dueck))
```

makes the changelog clear and add pr author

**Review by Kudo — APPROVED** [review]
thanks again for having the nice fix ❤️
