### PR TITLE
fix: more strict config plugin resolution

### LINKED ISSUE #31568: config plugin resolution fails in libraries using react-native-builder-bob
### Minimal reproducible example

https://github.com/vonovak/react-native-theme-control/releases/tag/v6.0.1

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

when compiling a RN lib with react-native-builder-bob (popular community tool for shipping RN libraries), the build output has multiple package.json files in it (intentionally, though it seems a bit hacky). 

This breaks config plugins’ mechanism of resolving the plugin file (`app.plugin.js`) .

This is caused by https://github.com/callstack/react-native-builder-bob/commit/0c5582bb66f5581693e8e9913f80d2fd40d4d7c5 and https://github.com/callstack/react-native-builder-bob/commit/5b455542fec82fa9edfb41c0da0ddceb4e72c485.

As a result of those commits there’s `<root>/package.json`, `<root>/lib/commonjs/package.json` and `<root>/lib/module/package.json`.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 5.2.15 - /opt/homebrew/bin/bash
    Binaries:
      Node: 20.17.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 26, 33, 34
        Build Tools: 26.0.3, 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-23 | Google APIs ARM 64 v8a, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.4.0

### Expo Doctor Diagnostics

all good

### PR DESCRIPTION
**Pull request by vonovak**
# Why

closes #31568

# How

libraries compiled with builder-bob now contain several package.json files: `<root>/package.json`, `<root>/lib/commonjs/package.json` and `<root>/lib/module/package.json`.

We would previously assume there's only one (the root one) and try to resolve the `app.plugin.js` file from its location.
But with multiple package.json files we attempted to resolve `app.plugin.js` relative to the nested `package.json` and that would fail.
This makes the resolution more strict by attempting to always resolve the root `package.json`

# Test Plan

added unit tests, tested in an app locally

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/config-plugins/src/utils/__tests__/plugin-resolver-test.ts [hunk 1]
```diff
@@ -1,22 +1,71 @@
...
+          isPluginFile: false,
+        },
+      },
+      {
+        pluginReference: 'test-plugin',
+        expected: {
+          filePath: 'node_modules/test-plugin/lib/commonjs/index.js',
+          isPluginFile: false,
+        },
+      },
```
Comment (byCedric) [inline packages/@expo/config-plugins/src/utils/__tests__/plugin-resolver-test.ts:59]: This test case should throw not found I think. It's mentioned here: https://docs.expo.dev/config-plugins/development-and-debugging/#expo-install

image

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts [hunk 2]
```diff
@@ -10,26 +9,41 @@ import { ConfigPlugin, StaticPlugin } from '../Plugin.types';
...
+    throwPluginNotFound();
+  }
+  const maybePluginFilePath = findUpPlugin(resolvedPackageJson);
+  if (maybePluginFilePath) {
+    return { isPluginFile: true, filePath: maybePluginFilePath };
+  } else {
+    if (!resolvedPluginScriptFile) {
+      throwPluginNotFound();
+    }
+    return { isPluginFile: false, filePath: resolvedPluginScriptFile };
```
Comment (byCedric) [inline packages/@expo/config-plugins/src/utils/plugin-resolver.ts:45]: I'd love to refactor this a bit. The way I like to think of "returning functions", where some data in should return some other data out, is that we can structure it like this:

```
function <name>(a, b) {
  // Handle most common case
  // Handle alternative cases
  // return fallback, or throw
}
```

It would make the function way easier to read and optimize, for example:

```ts
// pluginReference is a node module or a file path, as user entered it in app.config.js
export function resolvePluginForModule(
  projectRoot: string,
  pluginReference: string
): { filePath: string; isPluginFile: boolean } {
  // If the plugin was referenced by direct file reference, or package + file specifier, skip resolving app.plugin.js
  if (moduleNameIsDirectFileReference(pluginReference)) {
    const pluginScriptFile = resolveFrom.silent(projectRoot, pluginReference);
    if (pluginScriptFile) {
      return { isPluginFile: false, filePath: pluginScriptFile };
    }
  }

  // If the plugin was referenced by node module name, resolve the root of the package and look for app.plugin.js
  const pluginPackageDir = resolveFrom.silent(projectRoot, `${pluginReference}/package.json`);
  const pluginPackageFile = pluginPackageDir ? findUpPlugin(pluginPackageDir) : null;
  if (pluginPackageFile) {
    return { isPluginFile: true, filePath: pluginPackageFile };
  }

  throw new PluginError(
    `Failed to resolve plugin for module "${pluginReference}" relative to "${projectRoot}"`,
    'PLUGIN_NOT_FOUND'
  );
}
```

Comment (byCedric) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts:45]: It also shows further optimization we could do:

```ts
  // If the plugin was referenced by node module name, resolve the root of the package and look for app.plugin.js
  const pluginPackageFile = resolveFrom.silent(projectRoot, `${pluginReference}/${pluginFileName}`);
  if (pluginPackageFile && fileExists(pluginPackageFile)) {
    return { isPluginFile: true, filePath: pluginPackageFile };
  }
```

Instead of resolving this order:
  - `root = resolve(<pkg>/package.json)`
  - `plugin = resolve(path.dirname(root), './app.plugin.js')`
  - `return fileExists(plugin)`

**Review by byCedric — APPROVED** [review]
⚠️ There is one test case that seems incorrectly handled in the code right now, other than that, it looks good.

Left a few other nits, and a potential nice refactor, but we can skip that.

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts (hunk 2 above)
Comment (byCedric) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts:45]: Oh, another optimization to really get the most out of it would be:

```
function resolvePluginForModule(
  projectRoot: string,
  pluginReference: string
): { filePath: string; isPluginFile: boolean } {
  if (moduleNameIsDirectFileReference(pluginReference)) {
    // Only resolve `./file.js`, `package/file.js`, `@org/package/file.js`
  } else if (moduleNameIsPackageReference(pluginReference)) {
    // Only resolve `package -> package/app.plugin.js`, `@org/package -> 
  @org/package/app.plugin.js` 
  }

  throw new PluginError(
    `Failed to resolve plugin for module "${pluginReference}" relative to "${projectRoot}"`,
    'PLUGIN_NOT_FOUND'
  );
}
```

**Review by byCedric — APPROVED** [review]
Awesome, thanks!
