### PR TITLE
[fingerprint] transform paths in expo config as relative paths

### LINKED ISSUE #33852: EAS fingerprint fails when using file-based secrets
### Summary

EAS fingerprint validation fails when using file-based secrets due to path differences between GitHub CI environment and EAS build environment.
Related issued on Expo Github Actions https://github.com/expo/expo-github-action/issues/315 

I found a workaround for my builds to pass, which is to ignore fingerprint check on the whole expo config. 
https://github.com/expo/expo/blob/main/packages/%40expo/fingerprint/src/sourcer/SourceSkips.ts#L40
As mentioned in the readme https://www.npmjs.com/package/@expo/fingerprint 
But it's not the solution because it can lead to issues
```
  /**
   * Skip the whole ExpoConfig.
   * Prefer the other ExpoConfig source skips when possible and use this flag with caution.
   * This will potentially ignore some native changes that should be part of most fingerprints.
   * E.g., adding a new config plugin, changing the app icon, or changing the app name.
   */
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 34, 35
        Build Tools: 33.0.1, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.23 => 52.0.23 
      expo-router: ~4.0.15 => 4.0.15 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/mrkpatchaa/fingerprint-file-based-secrets

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #33852

# How

- transform paths in expo config as relative paths
- also removed `googleServicesFile` because it would be an absolute path when using file-based secret on EAS

# Test Plan

add unit tests and ci passed

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by Kudo** [comment]
* **#33926** <a href="https://app.graphite.dev/github/pr/expo/expo/33926?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/expo/expo/33926?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/@expo/fingerprint/src/sourcer/Expo.ts [hunk 1]
```diff
@@ -145,13 +145,22 @@ export async function getExpoConfigSourcesAsync(
...
   // Deep clone by JSON.parse/stringify that assumes the config is serializable.
   const normalizedConfig: ExpoConfig = JSON.parse(JSON.stringify(config));
 
   const { sourceSkips } = options;
   delete normalizedConfig._internal;
 
+  // googleServicesFile may contain absolute paths on EAS with file-based secrets.
+  // Given we include googleServicesFile as external files already, we can remove it from the config.
+  delete normalizedConfig.android?.googleServicesFile;
+  delete normalizedConfig.ios?.googleServicesFile;
```
Comment (tharakadesilva) [inline packages/@expo/fingerprint/src/sourcer/Expo.ts:162]: Hey Kudo, if we delete the keys here, then we will lose access to it [here](https://sourcegraph.com/github.com/expo/expo/-/blob/packages/%40expo/fingerprint/src/sourcer/Expo.ts?L116-119), no?

I think we will have to make a copy of the config and delete it before adding it [here](https://sourcegraph.com/github.com/expo/expo/-/blob/packages/%40expo/fingerprint/src/sourcer/Expo.ts?L48).

Comment (Kudo) [reply packages/@expo/fingerprint/src/sourcer/Expo.ts:162]: amazing you are so right! thanks for catching the problem.

File: packages/@expo/fingerprint/src/sourcer/Expo.ts [hunk 2]
```diff
@@ -212,7 +218,22 @@ function normalizeExpoConfig(config: ExpoConfig, options: NormalizedOptions): Ex
...
+
+/**
+ * Gives the last chance to modify the ExpoConfig.
+ * For example, we can remove some fields that are already included in the fingerprint.
+ */
+function postUpdateExpoConfig(config: ExpoConfig, projectRoot: string): ExpoConfig {
+  // The config is already a clone, so we can modify it in place for performance.
+
+  // googleServicesFile may contain absolute paths on EAS with file-based secrets.
+  // Given we include googleServicesFile as external files already, we can remove it from the config.
```
[the remark this answers is not in the document]
Comment (Kudo) [reply packages/@expo/fingerprint/src/sourcer/Expo.ts:232]: skips/exclude run [beforehand](https://github.com/expo/expo/blob/70b1ae4a0f2aa4b380d24cca321ac776d1eca34a/packages/%40expo/fingerprint/src/sourcer/Expo.ts#L46). if googleServicesFile is excluded in sourceSkips. it won't have the external file and no googleServicesFile key in the config object. literally like
```js
let config = { android: {} };
delete config.android?.googleServicesFile;
```
should be fine?

**Comment by Kudo** [comment]
going to merge this to resolve unstable fingerprint issue using google service files on eas.

**Review by wschurman — APPROVED** [review]

**Comment by Kudo** [comment]
### Merge activity

* **Jan 30, 10:15 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/33926).
