### PR TITLE
fix: Incorrect usage of reanimated shared value in expo-template-default app

### LINKED ISSUE #33197: Reading shared value during render
### Summary

In templates/expo-template-default/components/HelloWave.tsx is the following code: 
```
rotationAnimation.value = withRepeat(
    withSequence(withTiming(25, { duration: 150 }), withTiming(0, { duration: 150 })),
    4 // Run the animation 4 times
  );
```
it reads to value on render triggering the following warning: 
```
[Reanimated] Writing to `value` during component render. Please ensure that you do not access the `value` property or use `set` method of a shared value while React is rendering a component.

If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
```

### What platform(s) does this occur on?

iOS

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.3/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
      Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/filip/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 31, 33, 34, 35
        Build Tools: 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.10 => 52.0.0-preview.10 
      expo-router: ~4.0.0-preview.6 => 4.0.0-preview.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.0 => 0.76.0 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: managed
```

### Minimal reproducible example

default expo template

### PR DESCRIPTION
**Pull request by MatiPl01**
# Why

This PR fixes incorrect usage of the Reanimated `SharedValue` in the `HelloWave` component. In Reanimated `3.16.0` we introduced a warning displayed when the `SharedValue` is read/written when the component renders (see [this](https://github.com/software-mansion/react-native-reanimated/pull/6310) PR for more details).

Basically, we should read from/read to the shared value only in hooks or callback functions, not in the top level scope of the function component.

closes #33197

# How

Just wrapped the assignment to the shared value with the `useEffect` hook.

# Test Plan

Build the example app and either add an interval updating state in the `HelloWave` component or just trigger hot reload (by adding/removing some code from the component) to see that the warning is no longer visible.

This warning was visible before:

image

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: templates/expo-template-default/components/HelloWave.tsx [hunk 1]
```diff
@@ -12,10 +13,12 @@ import { ThemedText } from '@/components/ThemedText';
 export function HelloWave() {
   const rotationAnimation = useSharedValue(0);
 
-  rotationAnimation.value = withRepeat(
-    withSequence(withTiming(25, { duration: 150 }), withTiming(0, { duration: 150 })),
-    4 // Run the animation 4 times
-  );
+  useEffect(() => {
```
Comment (MatiPl01) [inline templates/expo-template-default/components/HelloWave.tsx:16]: Just added this `useEffect` hook.

**Review by aleqsio — APPROVED** [review]

**Review by chrfalch — APPROVED** [review]
