### PR TITLE
[expo-updates][Android] fix possible NPE in launch asset DB query

### LINKED ISSUE #28168: [expo-updates] Attempt to invoke virtual method 'void expo.modules.updates.db.entity.AssetEntity.setLaunchAsset(boolean)' on a null object reference
### Minimal reproducible example

Difficult to reproduce this with a fresh project since it needs to be installed by a large user base

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

Ever since we migrated to `expo-updates` a small number of our users are experiencing the following error:

image

These are the devices that it affects:

image

We don't see any Google devices affected by this bug so perhaps its vendor-specific.

The bug occurs here in `expo/modules/updates/db/dao/UpdateDao.kt:67`:

Screenshot 2024-04-12 at 11 35 00 AM

`assetEntity` should not be `null` but for some reason the Room query here returns `null`.

### Environment

```sh
expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 14.4
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.asdf/installs/nodejs/18.18.0/bin/node
    Yarn: 1.22.21 - ~/.asdf/installs/nodejs/18.18.0/bin/yarn
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/honeycomb/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
  IDEs:
    Xcode: 15.3/15E204a - /usr/bin/xcodebuild
  npmGlobalPackages:
    eas-cli: 7.8.0
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```sh
Detailed check results:

Expected package @expo/config-plugins@~7.8.0
Found invalid:
  @expo/config-plugins@6.0.2
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

The package "expo-dev-menu" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@7.6.2 - expected version: 7.6.1
  @sentry/react-native@5.19.3 - expected version: 5.19.1
  @shopify/flash-list@1.6.4 - expected version: 1.6.3
  expo@50.0.12 - expected version: ~50.0.15
  expo-camera@14.0.6 - expected version: ~14.1.2
  expo-dev-client@3.3.9 - expected version: ~3.3.11
  expo-updates@0.24.11 - expected version: ~0.24.12
  lottie-react-native@6.6.0 - expected version: 6.5.1
  react-native-gesture-handler@2.15.0 - expected version: ~2.14.0
  react-native-get-random-values@1.10.0 - expected version: ~1.8.0
  react-native-reanimated@3.8.1 - expected version: ~3.6.2
  jest-expo@50.0.3 - expected version: ~50.0.4
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by douglowder**
# Why

A customer with a large user base is seeing occasional errors happening when the query to return the launch asset from the DB returns null.

This fix will not prevent the errors from happening, but will gracefully produce a callback failure if it does occur. It also applies possible band-aids to places where this could be caused.

Fixes #28168.

Closes ENG-12190.

# How

- Make the result of the DB query nullable, and add code to check for this and call `callback.onFailure()` if it occurs.
- Don't reap embedded updates
- Don't delete assets that are referenced by direct foreign key

# Test Plan

We don't have a repro for this so we're taking guesses mostly. What we do know is that when this happens the emergency launch mechanism will kick in and the embedded update will be launched. Whether this is better than crashing is up for debate.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-updates/android/src/main/java/expo/modules/updates/launcher/DatabaseLauncher.kt [hunk 1]
```diff
@@ -84,7 +84,11 @@ class DatabaseLauncher(
     // verify that we have all assets on disk
     // according to the database, we should, but something could have gone wrong on disk
     val launchAsset = database.updateDao().loadLaunchAsset(launchedUpdate!!.id)
-    if (launchAsset.relativePath == null) {
+    if (launchAsset == null) {
+      // Issue #28168, handle case where launch asset is not found in DB
+      this.callback!!.onFailure(Exception("launchAsset was not found in DB; this should never happen"))
```
Comment (wschurman) [inline packages/expo-updates/android/src/main/java/expo/modules/updates/launcher/DatabaseLauncher.kt:89]:
```suggestion
      this.callback!!.onFailure(Exception("Launch asset for launched update not found in database. This should never happen."))
```

**Review by wschurman — APPROVED** [review]
I wonder what is causing this foreign key relationship to be broken. Do you think it's just never established during update finished downloading due to some transaction issue? Or maybe it's something with the embedded loader not establishing it? Or do you think something is severing it like the reaper?

If this is happening for the embedded update and we call `onFailure` here, there won't be a update to fall back to and the launch will still fail.

As a general principle, I agree that if something isn't right in the db or on disk for an update, it shouldn't crash, it just shouldn't launch it. But that has the downside of us probably not finding out about bugs in the library if this or something like it starts happening more frequently.

This solution looks correct assuming we're okay with not getting more info on the cause of the error from our users. It looks like if this occurs during startup, it'll fail the load and will fall back to `NoDatabaseLauncher` with an emergency launch, so we won't get crash reports. It does expose the underlying error to the server though, so maybe we could start reading those. 

It'd still be good to try to figure out how this could happen. Otherwise this could start happening more frequently and we'll be blind to it.
