### PR TITLE
[dev-client][expo-updates] Use expo-updates as source of truth for runtime version

### LINKED ISSUE #2511: Development Build does not work with fingerprint as Runtime Version
### Build/Submit details page URL

https://expo.dev/accounts/jinbu/projects/my-demo-expo-app/builds/25a7434a-4535-464e-b079-4863268b939b

### Summary

When creating development build using fingerprint as runtime version, the branches with the same runtime versions arent recognized as compatible update. Happens for iOS and Android apps.

### Managed or bare?

managed

### Environment

`npx expo-env-info`

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.20.4 - ~/hostedtoolcache/node/18.20.4/arm64/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.7.0 - ~/hostedtoolcache/node/18.20.4/arm64/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS [17](https://github.com/ash-blossom/masquerena/actions/runs/10479750265/job/29026011412#step:7:18).5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 33, 33, 33, 34, 34, 34, 34, 34, 35
        Build Tools: 33.0.2, 33.0.3, 34.0.0, 35.0.0
        Android NDK: 26.3.11579264
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.28 
      react: [18](https://github.com/ash-blossom/masquerena/actions/runs/10479750265/job/29026011412#step:7:19).2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.[19](https://github.com/ash-blossom/masquerena/actions/runs/10479750265/job/29026011412#step:7:20).11 => 0.19.12 
    Expo Workflow: managed
```

`npx expo-doctor`

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### Error output

No error.

Branches that dont have any updates yet will be listed here with `no updates available`. As soon as you push an update to the branch, it disappears.

In the first screenshot, you will see that the development branch is not showing. The second and third pictures shows that both the build and update runtime versions are the same.

1st picture
WhatsApp Image 2024-08-20 at 23 55 47_fa304bd7

2nd picture
image

3rd picture
image

### Reproducible demo or steps to reproduce from a blank project

create `app.config.js` with the fingerprint runtime version
```
runtimeVersion: {
  policy: 'fingerprint'
},
```

run `eas build` command
run `eas update` command

ensure that same platform, channel, branch etc are used.

### PR DESCRIPTION
**Pull request by wschurman**
# Why

This adds support for fingerprint runtime versions to dev client.

Closes ENG-12323.
Closes ENG-13390.
Closes https://github.com/expo/eas-cli/issues/2511.

# How

Fingerprint uses a special runtime version (`file:fingeprint`) to direct the code to read the fingerprint from a file. This is so that the fingerprint itself isn't part of the fingeprint.

Dev client was still reading this value from the manifest directly.

# Test Plan

On android, build app with fingeprint and dev client, load on emulator, see correct runtime version. Same with iOS.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by wschurman** [comment]
* **#31453** <a href="https://app.graphite.dev/github/pr/expo/expo/31453?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wschurman and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by wschurman — COMMENTED** [review]
Test failures are unrelated (one is a cancel, the other is an error in test setup).

**Review by douglowder — APPROVED** [review]

File: packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt [hunk 1]
```diff
@@ -60,10 +60,10 @@ class DevLauncherInternalModule(reactContext: ReactApplicationContext?) :
   private fun getUpdatesConfig(): WritableMap {
     val map = Arguments.createMap()
 
-    val runtimeVersion = DevLauncherController.getMetadataValue(reactApplicationContext, "expo.modules.updates.EXPO_RUNTIME_VERSION")
-    var projectUrl = DevLauncherController.getMetadataValue(reactApplicationContext, "expo.modules.updates.EXPO_UPDATE_URL")
+    val runtimeVersion = controller.updatesInterface?.getRuntimeVersion(reactApplicationContext)
+    val projectUrl = controller.updatesInterface?.getUpdateUrl(reactApplicationContext)
 
-    val appId = if (projectUrl.isNotEmpty()) {
+    val appId = if (projectUrl !== null && projectUrl.isNotEmpty()) {
```
Comment (Kudo) [inline packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt:66]:
```suggestion
    val appId = if (!projectUrl.isNullOrEmpty()) {
```

File: packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt [hunk 2]
```diff
@@ -231,15 +231,14 @@ class DevLauncherInternalModule(reactContext: ReactApplicationContext?) :
...
+    val appIcon = getApplicationIconUri()
 
-    var updatesUrl = DevLauncherController.getMetadataValue(reactApplicationContext, "expo.modules.updates.EXPO_UPDATE_URL")
-    var appId = ""
-
-    if (updatesUrl.isNotEmpty()) {
-      var uri = Uri.parse(updatesUrl)
-      appId = uri.lastPathSegment ?: ""
+    val updatesUrl = controller.updatesInterface?.getUpdateUrl(reactApplicationContext)
+    val appId = if (updatesUrl !== null && updatesUrl.isNotEmpty()) {
```
Comment (Kudo) [inline packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/modules/DevLauncherInternalModule.kt:238]:
```suggestion
    val appId = if (!updatesUrl.isNullOrEmpty()) {
```

File: packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt [hunk 3]
```diff
@@ -108,6 +108,14 @@ class UpdatesDevLauncherController(
     launcher = null
   }
 
+  override fun getRuntimeVersion(context: Context): String? {
+    return updatesConfiguration?.getRuntimeVersion()
+  }
+
+  override fun getUpdateUrl(context: Context): String? {
+    return updatesConfiguration?.updateUrl?.toString()
```
Comment (Kudo) [inline packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt:116]:
```suggestion
  override fun getUpdateUrl(context: Context): Uri? {
    return updatesConfiguration?.updateUrl
```

nit: maybe return Uri as aligned with ios implementation?

**Review by Kudo — APPROVED** [review]
great change. just leaving some nit comments. thanks for fixing the problem
