### PR TITLE
fix(router): fix nested generateStaticParams

### LINKED ISSUE #25394: generateStaticParams() doesn't work properly on cascade
### Minimal reproducible example

https://github.com/giofilo/expo-generateStaticParams-cascade

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Hi!

The problem is: `generateStaticParams()` function have a `params` parameter that doesn't work as the Expo docs is saying.

To reproduce, I started from `npx create-expo-app --template` and chose `Navigation (TypeScript)` template.

I then added `blog/[id]/_layout.tsx` and `blog/[id]/[comment].tsx`.

The code inside those files is [the same of the docs](https://docs.expo.dev/router/reference/static-rendering/#generatestaticparams). I just commented `await getComments(params.id);` and replaced it with a `console.log(params)`.

How to reproduce:

- run `npm install`
- run `npx expo export -p web`

In the terminal, you'll see the console.log result, it will print 3 times the same log:

```
{ params: { '0': { id: 'one' }, '1': { id: 'two' } } }
{ params: { '0': { id: 'one' }, '1': { id: 'two' } } }
{ params: { '0': { id: 'one' }, '1': { id: 'two' } } }
```

I would expect, instead:

```
{ id: 'one' }
{ id: 'two' }
```

I would appreciate your help and/or suggestions.
Thank you!

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2023.11.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.8.0
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- fix https://github.com/expo/expo/issues/25394

# How

- Clean up traversal logic.
- Minimize the amount of data fetching invocations to make.
- Fix the shape of the params being sent to nested `generateStaticParams` functions.

# Test Plan

- Improved the tests to also track the incoming parameters.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-router/src/loadStaticParamsAsync.ts [hunk 1]
```diff
@@ -1,92 +1,14 @@
...
-  TProps,
-  TProcess extends (node: T, props: any) => Promise<T[]>,
->(nodes: T[], props: TProps, func: TProcess): Promise<T[]> {
-  const tarr = await Promise.all(nodes.map((node) => func(node, props)).flat());
-  return tarr.filter(Boolean) as T[];
-}
-
 export async function loadStaticParamsAsync(route: RouteNode): Promise<RouteNode> {
-  const processed = (
+  route.children = (
```
Comment (marklawlor) [inline packages/expo-router/src/loadStaticParamsAsync.ts:4]: Nitpick: I'd break this into multiple lines

```tsx
const childStaticParams = await Promise.all(
  route.children.map((route) => loadStaticParamsRecursive(route, { parentParams: {} }))
)
route.children = childStaticParams.flat()
```

File: packages/expo-router/src/loadStaticParamsAsync.ts [hunk 2]
```diff
@@ -157,25 +87,83 @@ async function loadStaticParamsRecursive(
...
+      // TODO: We could split strings by `/` and use that too.
+      if (!Array.isArray(value)) {
+        validateSingleParam(dynamic, value, true);
+      } else {
+        validateSingleParam(dynamic, value.filter(Boolean).join('/'), true);
+      }
+    } else {
+      validateSingleParam(dynamic, value);
+    }
+    return value !== undefined && value !== null;
```
Comment (marklawlor) [inline packages/expo-router/src/loadStaticParamsAsync.ts:167]: I'm confused by this last line, its not doing anything

Comment (EvanBacon) [reply packages/expo-router/src/loadStaticParamsAsync.ts:167]: good catch
