### PR TITLE
[doctor] Fix - fails unexpectedly when setting EXPO_DEBUG=1

### LINKED ISSUE #39843: `expo-doctor` fails unexpectedly when setting `EXPO_DEBUG=1`
### Minimal reproducible example

https://github.com/conner1reimers/expo-doctor-bug-demonstration

### Steps to reproduce

To reproduce this bug, simply run `EXPO_DEBUG=1 npx expo-doctor@latest`. 

The last bit of output should look something like:
```
2025-09-19T21:42:20.995Z expo:doctor:dependencies:validate Checking dependencies for 54.0.0: {
  expo: '~54.0.9',
  'expo-status-bar': '~3.0.8',
  react: '19.1.0',
  'react-native': '0.81.4'
}
2025-09-19T21:42:20.995Z expo:doctor:dependencies:validate Comparing known versions: [ 'expo', 'expo-status-bar', 'react', 'react-native' ]
2025-09-19T21:42:20.995Z expo:doctor:dependencies:validate Skipping packages that cannot be versioned automatically: []
2025-09-19T21:42:20.996Z expo:doctor:dependencies:validate Package versions: {
  expo: '54.0.9',
  'expo-status-bar': '3.0.8',
  react: '19.1.0',
  'react-native': '0.81.4'
}
2025-09-19T21:42:20.998Z expo:doctor:dependencies:validate Incorrect dependencies: []
2025-09-19T21:42:21.028Z expo:telemetry:client:detached Detached flush started
Advice:
Use 'npx expo install --check' to review and upgrade your dependencies.
To ignore specific packages, add them to "expo.install.exclude" in package.json. Learn more: https://expo.fyi/dependency-validation

1 check failed, indicating possible issues with the project.
```
...while running `npx expo-doctor@latest` produces:
```
17/17 checks passed. No issues detected!
```
...as expected.

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 15.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.18.0 - ~/.nvm/versions/node/v22.18.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.9.3 - ~/.nvm/versions/node/v22.18.0/bin/npm
      Watchman: 2025.08.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/connerreimers/.rubies/ruby-3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2025.1 AI-251.25410.109.2511.13752376
      Xcode: 26.0/17A324 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.9 => 54.0.9 
      react: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
    npmGlobalPackages:
      eas-cli: 16.19.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by betomoedano**
# Why

Fixes: #39843

# How

We set `EXPO_DEBUG=0` when running the install check, so the CLI only emits the JSON we parse. Because of that:

# Test Plan

Before:
image

After:
image

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-doctor/src/checks/InstalledDependencyVersionCheck.ts [hunk 1]
```diff
@@ -55,9 +55,37 @@ export class InstalledDependencyVersionCheck implements DoctorCheck {
...
       parseInstallCheckOutput(commandResult.stdout, issues, projectMajorSdkVersion);
 
-      // If no issues were added from stdout, fall back to stderr
+      // Only fall back to stderr if stdout didn't contain valid JSON indicating up-to-date status
       if (issues.length === initialIssuesCount && commandResult.stderr.trim()) {
-        issues.push(commandResult.stderr.trim());
+        // Check if stdout indicates dependencies are up to date
+        let isUpToDate = false;
+        try {
+          const jsonMatch = commandResult.stdout.match(/\{[\s\S]*\}/);
```
Comment (kitten) [inline packages/expo-doctor/src/checks/InstalledDependencyVersionCheck.ts]: not sure if @byCedric has a different opinion on this, but I think we may just want to set `EXPO_DEBUG=0` for now, or make a private API available. This seems brittle, and I'm not sure if we want to even process `stderr`? Seems overly elaborate for what's an RPC API call, and maintaining this seems tough if mismatches occur 🤔

Comment (kitten) [reply packages/expo-doctor/src/checks/InstalledDependencyVersionCheck.ts]: ^Bump; cc @betomoedano

**Review by kitten — APPROVED** [review]
