### PR TITLE
[Android] Fix GLView initialization with 0 size texture

### LINKED ISSUE #2671: [Expo 31][expo-gl][Android] Expo.GLView doesn't work on Android in SDK 31
### Environment

| software         | version
| ---------------- | -------
| expo | 31.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz
| device    | Pixel 2 XL, Nexus 5X

`exp diagnostics` output

screen shot 2018-11-09 at 3 01 52 pm

App's target is Android Standalone

### Steps to Reproduce

To test Expo 31
```
git clone https://github.com/serhiipalash/test-glview-expo-31
cd test-glview-expo-31
yarn
expo start --android
```
You'll see this
screen shot 2018-11-09 at 2 51 59 pm

To test Expo 30
```
git checkout -b sdk-30 origin/sdk-30
rm -rf node_modules
yarn
expo start --android -c
```
You'll see this
screen shot 2018-11-09 at 2 48 52 pm

### Expected Behavior

`Expo.GLView` should work both Android and iOS in SDK 31

### Actual Behavior

On Android `Expo.GLView` doesn't work for any shader both in Simulator and .apk. I tested it for more complex cases in our real app.

### Reproducible Demo

https://github.com/serhiipalash/test-glview-expo-31

ping @tsapeta

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves #2671

# How

Android while creating `surfaceTexture` sometimes returns texture that has 0 size.
Immediately ofter such incident correct sized texture is provided via different callback. 

# Test Plan

https://snack.expo.io/@barthec/glview-sdk31

### CODE REVIEW

File: packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java [hunk 1]
```diff
@@ -10,6 +10,7 @@
 
 public class GLView extends TextureView implements TextureView.SurfaceTextureListener {
   private boolean mOnSurfaceCreateCalled = false;
+  private boolean mOnSurfaceTextureCreatedWith0Size = false;
```
Comment (tsapeta) [inline packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java]:
```suggestion
  private boolean mOnSurfaceTextureCreatedWithZeroSize = false;
```

File: packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java [hunk 2]
```diff
@@ -43,29 +44,18 @@ public GLContext getGLContext() {
...
-            public Bundle getEventBody() {
-              return event;
-            }
-          });
-        }
-      });
+      // onSurfaceTextureAvailable is sometimes called with 0 size texture
+      // and immediately followed by onSurfaceTextureSizeChanged with actual size
+      if (width == 0 || height == 0) {
+        mOnSurfaceTextureCreatedWith0Size = true;
```
Comment (tsapeta) [inline packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java]:
```suggestion
        mOnSurfaceTextureCreatedWithZeroSize = true;
```

File: packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java [hunk 3]
```diff
@@ -43,29 +44,18 @@ public GLContext getGLContext() {
...
+      }
+
+      if (!mOnSurfaceTextureCreatedWith0Size) {
```
Comment (tsapeta) [inline packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java]:
```suggestion
      if (!mOnSurfaceTextureCreatedWithZeroSize) {
```

File: packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java [hunk 4]
```diff
@@ -81,7 +71,11 @@ public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
   }
 
   @Override
-  public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
+  synchronized public void onSurfaceTextureSizeChanged(SurfaceTexture surfaceTexture, int width, int height) {
+    if (mOnSurfaceTextureCreatedWith0Size && width != 0 && height != 0) {
```
Comment (tsapeta) [inline packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java]:
```suggestion
    if (mOnSurfaceTextureCreatedWithZeroSize && width != 0 && height != 0) {
```

File: packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java [hunk 5]
```diff
@@ -81,7 +71,11 @@ public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
...
+      initializeSurfaceInGLContext(surfaceTexture);
+      mOnSurfaceTextureCreatedWith0Size = false;
```
Comment (tsapeta) [inline packages/expo-gl/android/src/main/java/expo/modules/gl/GLView.java]:
```suggestion
      mOnSurfaceTextureCreatedWithZeroSize = false;
```

**Review by tsapeta — CHANGES_REQUESTED** [review]
Good work Bartek! Thanks for fixing this 😄

**Review by tsapeta — APPROVED** [review]
