### PR TITLE
[expo-font][iOS] Fix font registration failing when font was in use.

### LINKED ISSUE #28948: [expo-font] Could not unregister the CGFont
### Minimal reproducible example

https://github.com/leonhh/expo-font-reproducer

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm in the process of updating my app to SDK 51 when I encountered an issue with font registration/unregistration on iOS in combination with hot-reload. 

SDK 50 works fine:

npm install expo@50
npx expo install --fix
npx expo prebuild --clean

```bash
iOS Bundled 1641ms (node_modules/expo/AppEntry.js)
 LOG  {"fontError": null}
 LOG  {"fontError": null}
› Reloading apps
iOS Bundled 32ms (node_modules/expo/AppEntry.js)
 LOG  {"fontError": null}
 LOG  {"fontError": null}
```

Update epxo to SDK 51:

npm install expo@51
npx expo install --fix
npx expo prebuild --clean

With expo-font 12.0.0 an error is thrown when the app is started:

```bash
iOS Bundled 1533ms node_modules/expo/AppEntry.js (638 modules)
 LOG  {"fontError": null}
 LOG  {"fontError": [Error: Calling the 'loadAsync' function has failed
→ Caused by: Registering 'Error Domain=com.apple.CoreText.CTFontManagerErrorDomain Code=305 "Could not register the CGFont '<CGFont (0x600003a5ea80): Danfo-Regular>'" UserInfo={NSDescription=Could not register the CGFont '<CGFont (0x600003a5ea80): Danfo-Regular>', CTFailedCGFont=<CGFont (0x600003a5ea80): Danfo-Regular>}' font failed with message: 'The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 305 - Could not register the CGFont '<CGFont (0x600003a5ea80): Danfo-Regular>')']}
```

With expo-font 12.0.5 an error is thrown only when reloading the app (pressing `r` in the terminal):

```bash
iOS Bundled 1598ms node_modules/expo/AppEntry.js (608 modules)
 LOG  {"fontError": null}
 LOG  {"fontError": null}
› Reloading apps
iOS Bundled 40ms node_modules/expo/AppEntry.js (1 module)
 LOG  {"fontError": null}
 LOG  {"fontError": [Error: Calling the 'loadAsync' function has failed
→ Caused by: Registering 'Error Domain=com.apple.CoreText.CTFontManagerErrorDomain Code=203 "Could not unregister the CGFont '<CGFont (0x6000011f5c00): Danfo-Regular>'" UserInfo={NSDescription=Could not unregister the CGFont '<CGFont (0x6000011f5c00): Danfo-Regular>', CTFailedCGFont=<CGFont (0x6000011f5c00): Danfo-Regular>}' font failed with message: 'The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 203 - Could not unregister the CGFont '<CGFont (0x6000011f5c00): Danfo-Regular>')']}
```

### Environment

  ```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check native tooling versions
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Fixes https://github.com/expo/expo/issues/28948

# How

When unregistering a font, we sometimes bump into a failure.

Now, if the failure code indicates that the font will still be available afterwards, we let the registerFont function complete instead of rethrowing this error.

# Test Plan

Tested that this works in standalone app.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by anstap** [comment]
hey @aleqsio how long does it usually takes after the PR is merged for this to get into a release?

**Comment by aleqsio** [comment]
For a CNG flow (not expo-go), usually a week or so :)

**Comment by anstap** [comment]
@aleqsio roger that. Thank you for the fix!

File: packages/expo-font/ios/FontLoaderModule.swift [hunk 1]
```diff
@@ -12,7 +12,9 @@ public final class FontLoaderModule: Module {
       // If the font was already registered, unregister it first. Otherwise CTFontManagerRegisterGraphicsFont
       // would fail because of a duplicated font name when the app reloads or someone wants to override a font.
       if let familyName = FontFamilyAliasManager.familyName(forAlias: fontFamilyAlias) {
-        try unregisterFont(named: familyName)
+        guard try unregisterFont(named: familyName) == true else {
```
Comment (tsapeta) [inline packages/expo-font/ios/FontLoaderModule.swift:15]: Isn't `== true` redundant?

**Review by tsapeta — APPROVED** [review]

File: packages/expo-font/ios/FontLoaderModule.swift (hunk 1 above)
Comment (aleqsio) [reply packages/expo-font/ios/FontLoaderModule.swift:15]: Fair point!
```suggestion
        guard try unregisterFont(named: familyName) else {
```

**Comment by pera14** [comment]
PR is blocked... can anyone do something about it?

**Comment by pera14** [comment]
when will this update be live in **npm**?

**Comment by hyochan** [comment]
Also waiting for this!

**Comment by Lurtroxx** [comment]
Waiting this as well. Fonts do not work in my app from latest expo upgrade. Any Expo team member able to comment on when this will be released to the live version? What is the last stable version of Expo that we can use.

**Comment by Lurtroxx** [comment]
@aleqsio What can be done to test the pull request or integrate into the package. I can install the standalone build from the pull request (or current main branch, since the PR is merged, but not published to NPM), but I do not see how to use it with EAS build. Any advice?

**Comment by hyochan** [comment]
Here is a patch package for `expo-font`. This works great!
```
diff --git a/node_modules/expo-font/ios/FontLoaderModule.swift b/node_modules/expo-font/ios/FontLoaderModule.swift
index 0cce788..f03aa4f 100644
--- a/node_modules/expo-font/ios/FontLoaderModule.swift
+++ b/node_modules/expo-font/ios/FontLoaderModule.swift
@@ -12,7 +12,9 @@ public final class FontLoaderModule: Module {
       // If the font was already registered, unregister it first. Otherwise CTFontManagerRegisterGraphicsFont
       // would fail because of a duplicated font name when the app reloads or someone wants to override a font.
       if let familyName = FontFamilyAliasManager.familyName(forAlias: fontFamilyAlias) {
-        try unregisterFont(named: familyName)
+        guard try unregisterFont(named: familyName) else {
+          return
+        }
       }
 
       // Create a font object from the given file
diff --git a/node_modules/expo-font/ios/FontUtils.swift b/node_modules/expo-font/ios/FontUtils.swift
index 48968db..2e179f4 100644
--- a/node_modules/expo-font/ios/FontUtils.swift
+++ b/node_modules/expo-font/ios/FontUtils.swift
@@ -67,19 +67,30 @@ internal func registerFont(_ font: CGFont) throws {
 /**
  Unregisters the given font, so the app will no longer be able to render it.
  */
-internal func unregisterFont(_ font: CGFont) throws {
+internal func unregisterFont(_ font: CGFont) throws -> Bool {
   var error: Unmanaged<CFError>?
 
   if !CTFontManagerUnregisterGraphicsFont(font, &error), let error = error?.takeRetainedValue() {
-    throw FontRegistrationFailedException(error)
+    if let ctFontManagerError = CTFontManagerError(rawValue: CFErrorGetCode(error as CFError)) {
+      switch ctFontManagerError {
+      case .systemRequired, .inUse:
+        return false
+      case .notRegistered:
+        return true
+      default:
+        throw FontRegistrationFailedException(error)
+      }
+    }
   }
+  return true
 }
 
 /**
  Unregisters a font with the given name, so the app will no longer be able to render it.
  */
-internal func unregisterFont(named fontName: String) throws {
+internal func unregisterFont(named fontName: String) throws -> Bool {
   if let font = CGFont(fontName as CFString) {
-    try unregisterFont(font)
+    return try unregisterFont(font)
   }
+  return true
 }
\ No newline at end of file
```

**Comment by Lurtroxx** [comment]
@hyochan Unfortunately, this did not work.

**Comment by diceros-soojungkim** [comment]
also waiting for this!

**Comment by pera14** [comment]
@aleqsio what's going on with this? Is there any solution for the ongoing issue or it's sorted? If that's the case, can you please tell us how to apply that

**Comment by aleqsio** [comment]
@pera14 Make sure to update to the latest `expo-font` package version - it should be fixed there.

**Comment by pera14** [comment]
@aleqsio I installed the latest `expo-font@12.0.6` and `expo@51.0.9` and I still have an issue when I build the app, and reopen it, after pressing any button, the app will crash.

**Comment by aleqsio** [comment]
This sounds like an unrelated issue - this one was happening on an app reload. 

You can try to open an issue with a fresh reproduction - I'm pretty sure the issue in the repro linked here was fixed already.

**Comment by hyochan** [comment]
I've just realized that this patch doesn't work in release mode while it is fine in development.
When I remove the `newArch`, it works again.

Let me investigate further and come back.

**Comment by Lurtroxx** [comment]
@hyochan no need to use patch package anymore, new version of Expo fixes this.

**Comment by hyochan** [comment]
Disabling `newArch` works fine with this updates. With `newArch`, it only works in dev client and not production mode (tested in android device).

**Comment by Karthik-B-06** [comment]
Is there any fix or workaround for this?

**Comment by diceros-soojungkim** [comment]
The only workaround I found working was to downgrade expo font to  "expo-font": "~11.10.3".  It just kept on giving errors on expo 50.0.19 for me especially for production build.
