### PR TITLE
Change `registerWebModule` to work with minified classes

### LINKED ISSUE #33628: Expo modules on web don't work when classes are changed to be anonymous
### Minimal reproducible example

https://github.com/Expensify/App/pull/51475/commits/0538c0ea9f8a64dc3e5775b3e098fa39fbc110bf

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

`registerWebModule` function requires the class it receives to have a name: https://github.com/expo/expo/blob/c10b58ea1ad8da11f0a6f28e2362736c80ec376b/packages/expo-modules-core/src/registerWebModule.ts#L16-L19

This may not be the case after minifying the code where the class may be changed to be an anonymous class.

Sorry for the repro being the Expensify App 😞. The linked commit contains the workaround for the problem. To reproduce it, see the previous commit and run the app in production mode (the offending module is ImageManipulator):

```
npm run build-adhoc
serve -s dist
```

It may be worth noting that adding

```js
static name = "ImageManipulator"
```

to the module class "solves" the problem as it conflicts with the class name which doesn't exist in this case.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.7.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      Yarn: 3.6.4 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
      Watchman: 2024.09.09.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 24, 26, 28, 29, 30, 31, 32, 33, 34, 35
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 35.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: 52.0.14 => 52.0.14
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
      react-native-web: 0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✖ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check native tooling versions
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following scripts in package.json conflict with the contents of node_modules/.bin: prettier, react-compiler-healthcheck, shellcheck, storybook.

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: react-native-android-location-enabler, react-native-fs, react-native-launch-arguments, react-native-onyx, react-native-release-profiler, react-native-sound, react-native-vision-camera
Unmaintained: @gorhom/portal, react-native-fs, react-native-modal, react-native-quick-sqlite
No metadata available: @dotlottie/react-player, @expo/metro-runtime, @firebase/app, @firebase/performance, @formatjs/intl-datetimeformat, @formatjs/intl-listformat, @formatjs/intl-locale, @formatjs/intl-numberformat, @formatjs/intl-pluralrules, @fullstory/browser, @fullstory/react-native, @onfido/react-native-sdk, @react-ng/bounds-observer, @ua/react-native-airship, awesome-phonenumber, canvas-size, core-js, date-fns, date-fns-tz, dom-serializer, domhandler, expensify-common, fast-equals, focus-trap-react, howler, htmlparser2, idb-keyval, lodash-es, mapbox-gl, onfido-sdk-ui, process, pusher-js, react-beautiful-dnd, react-collapse, react-error-boundary, react-fast-pdf, react-map-gl, react-native-app-logs, react-native-image-size, react-native-key-command, react-plaid-link, react-web-config, react-webcam, react-window
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.2.1 - expected version: 11.4.1
  expo@52.0.14 - expected version: ~52.0.18
  lottie-react-native@6.5.1 - expected version: 7.1.0
  react-native@0.76.3 - expected version: 0.76.5
  react-native-gesture-handler@2.20.1 - expected version: ~2.20.2
  react-native-screens@3.35.0 - expected version: ~4.1.0
  react-native-svg@15.9.0 - expected version: 15.8.0
  react-native-view-shot@3.8.0 - expected version: ~4.0.3
  react-native-webview@13.8.6 - expected version: 13.12.5
  @types/react@18.2.45 - expected version: ~18.3.12
  @types/react-dom@18.2.4 - expected version: ~18.3.1
  jest@29.4.1 - expected version: ~29.7.0
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Closes https://github.com/expo/expo/issues/33628
Found a PR i made and forgot about a few months ago that fixes this issue 🥹 

# How

Added a name argument to `registerWebModule`. We need it since classname can be minified which breaks web modules.

# Test Plan

Tested bare-expo still works well. Tested a few of those modules. 
Also works in after bundling.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

File: packages/expo-modules-core/src/registerWebModule.ts [hunk 1]
```diff
@@ -4,18 +4,21 @@ import type { NativeModule } from './ts-declarations/NativeModule';
 /**
  * Registers a web module.
  * @param moduleImplementation A class that extends `NativeModule`. The class is registered under `globalThis.expo.modules[className]`.
+ * @param moduleName – a name to register the module under.
```
Comment (Kudo) [inline packages/expo-modules-core/src/registerWebModule.ts:7]:
```suggestion
 * @param moduleName – a name to register the module under `globalThis.expo.modules[className]`.
```

nit: unfinished sentence?

**Review by Kudo — APPROVED** [review]
