### PR TITLE
[android][audio] Remove unused parameters to `setAudioModeAsync`

### LINKED ISSUE #34025: [expo-audio][android] Unable to use interruptionMode option
### Minimal reproducible example

https://github.com/JorrinKievit/expo-audio-interruptionmode-repro

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I am not able to use the interruptionMode string options when setting them with setAudioModeAsync. I am getting the following errors:

```
→ Caused by: The 1st argument cannot be cast to type expo.modules.audio.AudioMode (received class com.facebook.react.bridge.ReadableNativeMap)
→ Caused by: Cannot cast 'String' for field 'interruptionMode' ('expo.modules.audio.InterruptionMode').
→ Caused by: java.lang.IllegalArgumentException: Couldn't convert 'com.facebook.react.bridge.DynamicFromMap@add2734' to InterruptionMode where value is the enum parameter]
```

Simply using this code:

```
setAudioModeAsync({
  allowsRecording: false,
  playsInSilentMode: true,
  shouldPlayInBackground: true,
  shouldRouteThroughEarpiece: false,
  interruptionMode: "mixWithOthers",
}).catch(console.error);
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.26100
    Binaries:
      Node: 21.6.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20231008.002904.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ~52.0.23 => 52.0.23 
      expo-router: ~4.0.15 => 4.0.15 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
	  // expo-audio doesn't seem to appear but its
      expo-audio: ~0.3.1
    Expo Workflow: bare
```
```


### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar.



The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-audio
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #34025.
There were parameters passed to `setAudioModeAsync ` that were unused on android. Android recommends not managing audio focus yourself and letting ExoPlayer do it so we're going to see how that works initially. 
See https://developer.android.com/media/optimize/audio-focus

# How
Only pass supported arguments to android in `setAudioModeAsync `.

# Test Plan
Bare-expo. Working as before

### CODE REVIEW

File: packages/expo-audio/src/ExpoAudio.ts [hunk 1]
```diff
@@ -115,7 +116,14 @@ export async function setIsAudioActiveAsync(active: boolean): Promise<void> {
 
 // @docsMissing
 export async function setAudioModeAsync(mode: Partial<AudioMode>): Promise<void> {
-  return await AudioModule.setAudioModeAsync(mode);
+  const audioMode: Partial<AudioMode> =
+    Platform.OS === 'ios'
```
Comment (chrfalch) [inline packages/expo-audio/src/ExpoAudio.ts:120]: Do we need anything here for `web` platform, or does it support the same as iOS?

**Review by chrfalch — APPROVED** [review]
LGTM 👌

File: packages/expo-audio/src/ExpoAudio.ts (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-audio/src/ExpoAudio.ts:120]: It supports the same as iOS 👍
