### PR TITLE
[expo-media-library][android] Add support for granular permissions

### LINKED ISSUE #24122: [media-library] Android 13 Permissions
### Summary

When invoking [`await MediaLibrary.requestPermissionsAsync()`](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibraryrequestpermissionsasyncwriteonly) on Android 13, two permission prompts appear asking for music/audio followed by photos/videos. According to the android developer docs in Android 13 or higher they have introduced more [granular permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions). I'm interested in only presenting the user with a single prompt (as I don't need to ask for music/audio) which appears would be [`READ_MEDIA_IMAGES`](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES), but adding that permission doesn't seem to do the trick. I also don't see that permission in the list of [available permissions](https://docs.expo.dev/versions/latest/config/app/#permissions). Lastly it looks like this was [addressed](https://github.com/expo/expo/pull/20907) in the past, but perhaps I'm missing something. 

**Screenshots**

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```json
"expo": "~49.0.8",
"expo-dev-client": "~2.4.8",
"expo-media-library": "~15.4.1",
"expo-status-bar": "~1.6.0",
"expo-updates": "~0.18.12",
"react": "18.2.0",
"react-native": "0.72.4"
```

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 13.5
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  npmPackages:
    expo: ~49.0.8 => 49.0.8 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.4 => 0.72.4 
  npmGlobalPackages:
    eas-cli: 4.1.2
    expo-cli: 6.3.10
  Expo Workflow: managed
```

### Reproducible demo

https://github.com/iM-GeeKy/media-permissions

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by behenate**
# Why

On Android 13+ when calling `MediaLibrary.requestPermissionsAsync`, due to native API changes, the module asks the user for audio permissions, which doesn't make sense for apps that only want access to images or videos. This PR allows the users to specify what kinds of media they want to get access to.

Fixes https://github.com/expo/expo/issues/24122

This functionality only applies to devices running Android 13+, afaik there is no way to get similar functionality on iOS and web.

# How

Added `granularPermissions` parameter to `requestPermissionsAsync` and `getPermissionsAsync` as well as `usePermissionsHook` which defaults to `["audio", "video", "photo"]` when not provided to keep backwards compatibility.

# Test Plan

Tested in BareExpo on Android 14 Pixel 8

### CODE REVIEW

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryEnums.kt [hunk 1]
```diff
@@ -1,7 +1,22 @@
 package expo.modules.medialibrary
 
+import android.Manifest
 import android.provider.MediaStore
 
+enum class GranularPermission(val value: String) {
```
Comment (alanjhughes) [inline packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryEnums.kt:6]:
```suggestion
enum class GranularPermission(val value: String) : Enumerable {
```

**Review by alanjhughes — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]

**Review by amandeepmittal — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by Joshandrews43** [comment]
Is it possible this broke something? I just upgraded from `15.4.1` and I get this on all devices below Android API 33: 

```
 [Error: Call to function 'ExpoMediaLibrary.getAssetsAsync' has been rejected.
→ Caused by: Missing MEDIA_LIBRARY permissions.]
```

I am certain nothing has changed about my code, and that we request permissions correctly. We had ~100k users with correct permissions before this upgrade.  MEDIA_LIBRARY is never being added, but also doesnt exist on Android 10 for example.

Thanks!

**Comment by zgordon02** [comment]
> Is it possible this broke something? I just upgraded from `15.4.1` and I get this on all devices below Android API 33:
> 
> ```
>  [Error: Call to function 'ExpoMediaLibrary.getAssetsAsync' has been rejected.
> → Caused by: Missing MEDIA_LIBRARY permissions.]
> ```
> 
> I am certain nothing has changed about my code, and that we request permissions correctly. We had ~100k users with correct permissions before this upgrade. MEDIA_LIBRARY is never being added, but also doesnt exist on Android 10 for example.
> 
> Thanks!

@Joshandrews43 

Did you ever get a resolution to this? I am getting the same issue. Upgrading from expo 51 to 54 and this suddenly started happening on older Android devices
