### PR TITLE
fix(cli): disable API interaction when running in offline mode

### LINKED ISSUE #18918: Network timeout error occured even if executing "expo start --offline" with expo "46.0.*"
### Summary

When I started my expo project with the latest version 46.0.0, I got a network error. I thought my proxy settings caused it, so I tried to use offline mode by the command `expo start --offline`, however there still a network error happened.

image

And then I tried to fall back to the 45.0.0 version, it worked as I expected.

### What platform(s) does this occur on?

Web

### SDK Version

46.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.19.1 - D:\ly\softwares\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 6.14.16 - D:\ly\softwares\nodejs\npm.CMD
    npmPackages:
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Minimal reproducible example

Just any project created by "expo init"

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes ENG-6550
Fixes #18918

# How

- Disabled dependency validation when running in offline mode
- Disabled Expo Go version validation when running in offline mode
  > **Note** it still checks if Expo Go is installed. When it's not installed, it throws instead.
- Disabled fetching user when running in offline mode
  > **Note** this would fall back to an anonymous user and (auto)disables analytics and (possible) manifest signing. 
- Updated tests to validate dependency validation is skipped in offline mode

Optionally, we could add a global catch for errors listed below, to mention the `--offline` option.
 - `error instanceof CommandError && error.code === 'API'`
 - `error.code === 'FetchError'`

# Test Plan

To test this, update your **/etc/hosts** and add `127.0.0.1 api.expo.dev`. Then run the CLI:
- `npx expo start` → this fails with a fetch error
- `npx expo start --offline` → this should succeed without issues
- `npx expo start --offline --android|ios` 
  → when Expo Go is NOT installed, it should throw
  → when Expo Go is installed, it should warn and continue to the bundle

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/start/doctor/dependencies/validateDependenciesVersions.ts [hunk 1]
```diff
@@ -32,7 +34,12 @@ export async function validateDependenciesVersionsAsync(
   exp: Pick<ExpoConfig, 'sdkVersion'>,
   pkg: PackageJSONConfig,
   packagesToCheck?: string[]
-): Promise<boolean> {
+): Promise<boolean | null> {
+  if (APISettings.isOffline) {
```
Comment (byCedric) [inline packages/@expo/cli/src/start/doctor/dependencies/validateDependenciesVersions.ts:38]: I added the offline check here, but since `expo start` is the only one supporting the `--offline` flag, we could also not-run this function if running in offline mode.

No strong opinions on either one, but with this, we know that this won't pop up again if used in other commands.

File: packages/@expo/cli/src/start/doctor/dependencies/validateDependenciesVersions.ts [hunk 2]
```diff
@@ -32,7 +34,12 @@ export async function validateDependenciesVersionsAsync(
...
+    debug('Skipping dependency validation in offline mode');
```
Comment (EvanBacon) [inline packages/@expo/cli/src/start/doctor/dependencies/validateDependenciesVersions.ts:39]:
```suggestion
    Log.warn('Skipping dependency validation in offline mode');
```

**Review by EvanBacon — APPROVED** [review]

File: packages/@expo/cli/src/start/platforms/ExpoGoInstaller.ts [hunk 3]
```diff
@@ -74,6 +76,16 @@ export class ExpoGoInstaller<IDevice> {
...
     let shouldInstall = !(await deviceManager.isAppInstalledAsync(this.appId));
 
+    if (APISettings.isOffline && !shouldInstall) {
+      Log.warn(`Skipping Expo Go version validation in offline mode`);
+      return false;
+    } else if (APISettings.isOffline && shouldInstall) {
+      throw new CommandError(
+        'NO_EXPO_GO',
+        `Expo Go is not installed on device "${deviceManager.name}", while running in offline mode. Manually install Expo Go or run without --offline flag.`
+      );
```
Comment (byCedric) [inline packages/@expo/cli/src/start/platforms/ExpoGoInstaller.ts:86]: I think this is the best context we can give them. Pointing to an `expo.fyi` seems pointless in offline mode's case 🤷

**Review by EvanBacon — APPROVED** [review]

**Comment by Stevemoretz** [comment]
Is this published yet? I updated but didn't get it yet.

**Comment by brentvatne** [comment]
@Stevemoretz - published in expo@46.0.16
