### PR TITLE
[file-system][ios] Add utf-8 uri support

### LINKED ISSUE #10476: [expo-file-system][iOS] lack of utf-8 uri support on iOS
### Summary of Issue 

on iOS, `expo-file-system` cannot properly handle uri that contains utf-8 strings.

It seems these lines of code that create URL from strings are responsible. They all return `nil` for any utf-8 file uri.

```objc
NSURL *uri = [NSURL URLWithString:uriString];
```

I believe we should use `NSURL fileURLWithPath` or `stringByAddingPercentEncodingWithAllowedCharacters` to properly handle this.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    Expo Workflow: bare
```

### Steps to Reproduce

```js
import * as fs from 'expo-file-system';
await fs.makeDirectoryAsync(fs.documentDirectory + "中文");
```

throws an error: `[Error: Directory '(null)' could not be created because the location isn't writable.]`.

### Expected Behavior vs Actual Behavior

Uri should work with utf-8 strings.

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Closes https://github.com/expo/expo/issues/10476

# How

This PR updates all iOS local uri instances (NSURL) to parse them using percent-encoded characters when necessary, that way we're able to support paths like `fs.documentDirectory + "中文"`. This also updates 

# Test Plan

Added a new `Create UTF-8 uri` button to NCL so we can test this 

https://user-images.githubusercontent.com/11707729/217058407-3ff04176-2b72-43f9-803c-6a097f0a79ee.mov

 

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good to me 👍 

Since the versioned code for iOS already landed, could you please backport this change to SDK 48? Once you rebase it, running `et add-sdk -p ios -s 48.0.0 -x expo-file-system` should do the trick 😉 

Perhaps we should change it in the Convertible implementation for URL in Expo Modules API as well (but this is a separate task): https://github.com/expo/expo/blob/fe5cfb17dd928f54dda705d6eb5a5630547e4274/packages/expo-modules-core/ios/Swift/Arguments/Convertibles.swift#L16

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 1]
```diff
@@ -208,7 +208,7 @@ - (NSDictionary *)encodingMap
                     resolver:(EXPromiseResolveBlock)resolve
                     rejecter:(EXPromiseRejectBlock)reject)
 {
-  NSURL *uri = [NSURL URLWithString:uriString];
+  NSURL *uri = [NSURL URLWithString:[uriString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]]];
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:211]: At a glance, we should not be double-encoding URIs. Something seems off here. Maybe the parameter needs to be renamed to something other than uriString because if it were a valid URI, it should have been encoded in the first place.

Comment (gabrieldonadel) [reply packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:211]: I believe we're not double-encoding URIs here as `uriString` is a `NSString *`, but I agree that `uriString`  may be misleading

**Review by brentvatne — APPROVED** [review]

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m (hunk 1 above)
Comment (gabrieldonadel) [reply packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: I've renamed this to `pathString` instead.

File: ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m [hunk 2]
```diff
@@ -269,13 +269,13 @@ - (NSDictionary *)encodingMap
...
 ABI48_0_0EX_EXPORT_METHOD_AS(writeAsStringAsync,
-                    writeAsStringAsyncWithURI:(NSString *)uriString
+                    writeAsStringAsyncWithURI:(NSString *)pathString
                     withString:(NSString *)string
                     withOptions:(NSDictionary *)options
                     resolver:(ABI48_0_0EXPromiseResolveBlock)resolve
                     rejecter:(ABI48_0_0EXPromiseRejectBlock)reject)
 {
-  NSURL *uri = [NSURL URLWithString:uriString];
+  NSURL *uri = [NSURL URLWithString:[pathString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]]];
```
Comment (ide) [inline ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m:278]: Should this use `URLPathAllowedCharacterSet` since the intent is to encode a path rather than a query string?

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 3]
```diff
@@ -174,15 +174,15 @@ - (NSDictionary *)encodingMap
 }
 
 EX_EXPORT_METHOD_AS(getInfoAsync,
-                    getInfoAsyncWithURI:(NSString *)uriString
+                    getInfoAsyncWithURI:(NSString *)pathString
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:177]:
```suggestion
                    getInfoAsyncWithPath:(NSString *)pathString
```

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 4]
```diff
@@ -203,15 +203,15 @@ - (NSDictionary *)encodingMap
 }
 
 EX_EXPORT_METHOD_AS(readAsStringAsync,
-                    readAsStringAsyncWithURI:(NSString *)uriString
+                    readAsStringAsyncWithURI:(NSString *)pathString
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:206]:
```suggestion
                    readAsStringAsyncWithPath:(NSString *)pathString
```

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 5]
```diff
@@ -269,13 +269,13 @@ - (NSDictionary *)encodingMap
 }
 
 EX_EXPORT_METHOD_AS(writeAsStringAsync,
-                    writeAsStringAsyncWithURI:(NSString *)uriString
+                    writeAsStringAsyncWithURI:(NSString *)pathString
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:272]:
```suggestion
                    writeAsStringAsyncWithPath:(NSString *)pathString
```

etc... (I did not make a suggestion for everywhere)

**Review by ide — COMMENTED** [review]
I'm confused by the current state of things. The original methods seem like they were written to accept URIs such as `file:///folder/example.txt`. A valid URI already needs to be properly encoded.

On the other hand, as I understand this issue, unencoded values are getting passed in. Are these values intended to be file paths or URIs? If they are file paths, then we need to URI-encode them when converting them to URIs. If they are URIs... they're already URIs and it's correct to leave them as-is.

If the values actually are file paths and every reference in this file was wrong and should not have been named `localURI: fileUriString` or similar, then renaming the parameters looks right. But I'm hesitant to do that because the original authors might have used "URI" in the names they chose because they expected URIs to be passed in.

File: ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m (hunk 2 above)
Comment (douglowder) [reply ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m:278]: I agree, and would also think we should be using `[NSURL fileURLWithString]` maybe

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 6]
```diff
@@ -174,15 +174,15 @@ - (NSDictionary *)encodingMap
...
 
 EX_EXPORT_METHOD_AS(getInfoAsync,
-                    getInfoAsyncWithURI:(NSString *)uriString
+                    getInfoAsyncWithURI:(NSString *)pathString
                     withOptions:(NSDictionary *)options
                     resolver:(EXPromiseResolveBlock)resolve
                     rejecter:(EXPromiseRejectBlock)reject)
 {
-  NSURL *uri = [NSURL URLWithString:uriString];
+  NSURL *uri = [NSURL URLWithString:[pathString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]]];
```
Comment (douglowder) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:182]: Since we are using `[pathString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]]` all over the place, maybe it would be good to refactor this out to an internal method

File: ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m (hunk 2 above)
Comment (gabrieldonadel) [reply ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m:278]: Unfortunately using `[NSURL fileURLWithPath]` directly does not work, it produces the same `Error: File 'file:/Users/.../%E4%B8%AD%E6%96%87 -- file:///' isn't readable.` error.

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m (hunk 6 above)
Comment (tsapeta) [reply packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:182]: As I proposed at the end of this comment https://github.com/expo/expo/pull/21098#pullrequestreview-1285860715, probably the best way would be to change this convertible type and migrate other packages using this to the new API 😄 The internal code of packages can stay in Objective-C if migrating it to Swift would be too much time consuming. I'm encouraging everyone to help in migrating them because only then we could drop a lot of legacy code from expo-modules-core.

File: ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m (hunk 2 above)
Comment (gabrieldonadel) [reply ios/versioned/sdk48/EXFileSystem/EXFileSystem/ABI48_0_0EXFileSystem.m:278]: I did some more investigation on this and it seems that the problem is related to the way that the NSURL path is returned.

Given the following path, `FileSystem.documentDirectory + 'ÅÄÖ'` (`file:///var/mobile/Containers/Data/Application/6FAE142B-76F6-4FDD-AE26-A70292E956B9/Documents/ÅÄÖ`) which does not exist in the device:

- Using `NSURL URLWithString:[pathString stringByAddingPercentEncodingWithAllowedCharacters`:
    - `NSCharacterSet URLQueryAllowedCharacterSet` produces `/var/mobile/Containers/Data/Application/6FAE142B-76F6-4FDD-AE26-A70292E956B9/Documents/ÅÄÖ` (does not include `file` in the path) and scheme is `file`
   - Using `NSCharacterSet URLPathAllowedCharacterSet` produces `file:///var/mobile/Containers/Data/Application/6FAE142B-76F6-4FDD-AE26-A70292E956B9/Documents/ÅÄÖ` (same as input) and scheme is `(null)`
- Using `[NSURL fileURLWithPath:pathString]` produces `/file:/var/mobile/Containers/Data/Application/6FAE142B-76F6-4FDD-AE26-A70292E956B9/Documents/ÅÄÖ` (removes ///) and scheme is `file`

Whenever the returned scheme is `(null)` we already fallback to `[NSURL fileURLWithPath:pathString isDirectory:false]` producing `/file:/var/mobile/Containers/Data/Application/D886A047-E4B6-4365-A5FF-04372FF22182/Documents/ÅÄÖ`
https://github.com/expo/expo/blob/fa1f8b5219dea4ae2c243c4bbff4577443a0952b/packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m#L184-L186

After that, we check for permissions on the given URI
https://github.com/expo/expo/blob/fa1f8b5219dea4ae2c243c4bbff4577443a0952b/packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m#L1003-L1005

And here is the problem, inside the `getInternalPathPermissions` function https://github.com/expo/expo/blob/fa1f8b5219dea4ae2c243c4bbff4577443a0952b/packages/expo-file-system/ios/EXFileSystem/EXFilePermissionModule.m#L30-L48


we check specifically for `standardizedPath hasPrefix:[scopedDirectory stringByAppendingString:@"/"]` which is not true because our `standardizedPath` starts with `/file:`. To solve that we could add a check for `[standardizedPath hasPrefix:[NSString stringWithFormat:@"/file:%@/", scopedDirectory]] ||`. What do you guys think about this?

**Comment by gabrieldonadel** [comment]
@douglowder, @ide, and @tsapeta I've simplified things a bit by using `[NSURL fileURLWithPath]`, the only caveat is that in order to use `fileURLWithPath` we need to remove `file:///` from the provided string, but I created a helper function for that.

Regarding the renaming of the `uri` variables to `path`, I believe we should not do that, after further reviewing this file my understanding is that we always expect the user to provide URIs, e.g. `FileSystem.documentDirectory` returns a URI and not a path

**Review by douglowder — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Review by brentvatne — APPROVED** [review]

**Comment by ide** [comment]
After the release or maybe during the beta period, look out for whether people use `assets-library://` URLs with FileSystem. I'm not sure all URLs were `file:` URLs.
