### PR TITLE
[cli] Fix error after consecutive `run:ios` commands

### LINKED ISSUE #33227: [SDK52 expo-splash-screen] iOS dev build crashes due to missing storyboard
### Minimal reproducible example

https://github.com/philip-zhan/expo-splash-mre

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Expected: development build launches in iOS simulator after `npx expo run:ios`

Actual: development build failed to **re-launch** in iOS simulator
You may not be able to reproduce it in the first cold start. However, if you restart the expo dev session without closing the app in the simulator, you'll see something like this:
```
[CoreFoundation] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'There doesn't seem to be a valid compiled
storyboard at path
'/Users/philipzhan/Library/Developer/CoreSimulator/Devices/D4E8C9E5-8AC5-4FD2-800B-417620963F16/data/Containers/Bundle/Application/743F00DB-F193-43CB-A230-038B94ED0932/exposplashmre.app/SplashScreen.storyboardc''
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804b757c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x000000018008eda8 objc_exception_throw + 72
2   UIKitCore                           0x0000000185c823dc -[UIStoryboard name] + 0
3   exposplashmre.debug.dylib           0x0000000104645798 $sSo12UIStoryboardC4name6bundleABSS_So8NSBundleCSgtcfCTO + 64
4   exposplashmre.debug.dylib           0x0000000104644d44 $s16ExpoSplashScreen0bC7ManagerC8initWithyySo6UIViewCF + 172
5   exposplashmre.debug.dylib           0x0000000104644248 $s16ExpoSplashScreen0bC21AppDelegateSubscriberC17customizeRootVi<…>
```

Related: https://github.com/expo/expo/issues/32605

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.0 - ~/.nvm/versions/node/v18.20.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v18.20.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #33227
When `expo run:ios` is run consecutively on a simulator without closing the app, the app will crash because of missing resources such as the storyboard. 

# How
If we are running on a simulator, we will attempt to close the app if it is currently running. If it's not, we will proceed as normal. This also seems to align with the behaviour you would see when running the app from Xcode. The app is always shut down and then launched. Currently, we don't do that, leading to an error. 

# Test Plan
Running `expo run:ios` locally. The app launches successively regardless of whether it is running or not.

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

File: packages/@expo/cli/src/run/ios/runIosAsync.ts [hunk 1]
```diff
@@ -69,6 +70,16 @@ export async function runIosAsync(projectRoot: string, options: Options) {
   const launchInfo = await getLaunchInfoForBinaryAsync(binaryPath);
   const isCustomBinary = !!options.binary;
 
+  // Always close the app before launching on a simulator. Otherwise certain cached resources like the splashscreen will not be available.
+  if (props.isSimulator) {
+    try {
+      await simctlAsync(['terminate', props.device.udid, launchInfo.bundleId]);
+    } catch (error) {
+      // If we failed the app was not running to begin with and we will get an `invalid device` error
```
Comment (brentvatne) [inline packages/@expo/cli/src/run/ios/runIosAsync.ts:78]:
```suggestion
      // If we failed the app, it's likely that the app was not running to begin with and we will get an `invalid device` error
```

File: packages/@expo/cli/src/run/ios/runIosAsync.ts [hunk 2]
```diff
@@ -69,6 +70,16 @@ export async function runIosAsync(projectRoot: string, options: Options) {
...
+      debug('Failed to terminate app:', error);
```
Comment (brentvatne) [inline packages/@expo/cli/src/run/ios/runIosAsync.ts:79]:
```suggestion
      debug('Failed to terminate app (possibly because it was not running):', error);
```
