### PR TITLE
[notifications]: Fix didNotificationResponseReceived being duplicating fired for pending notification responses

### LINKED ISSUE #34850: [iOS][expo-notification] `didNotificationResponseReceived` being duplicating fired for pending notification responses
### Minimal reproducible example

https://github.com/xc2/expo-repro-notification

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

On iOS, if a notification response (pending notification response) received when there's no listener attached to the notification emitter, **every time** a new listener is added to the notification emitter, it will be fired immediately with this notification response.

See https://github.com/xc2/expo-repro-notification/blob/main/README.md for reproducing steps.

#### Exepcted

Once a pending notification response is consumed, it should not emit the didNotificationResponseReceived event anymore.

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.18.2 - ~/.managed/n/bin/node
      npm: 10.8.2 - ~/.managed/n/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/kfll/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23726.103.2422.12816248
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.32 => 52.0.32
      react: 18.3.1 => 18.3.1
      react-native: 0.76.7 => 0.76.7
    npmGlobalPackages:
      eas-cli: 15.0.9
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by xc2**
# Why

Fixes #34850

# How

Remove response from pending notification responses list after it is consumed.

# Test Plan

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m [hunk 1]
```diff
@@ -163,7 +163,7 @@ - (void)addDelegate:(id<EXNotificationsDelegate>)delegate
     UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
     for (UNNotificationResponse *response in _pendingNotificationResponses) {
       [delegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:^{
-        // completion handler doesn't need to do anything
+        [self->_pendingNotificationResponses removeObject:response];
```
Comment (douglowder) [inline packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m:166]: I think this is probably ok, will test this out. @vonovak are we already doing this in Android?

We are in the process of converting this code to Swift. I'll make sure the behavior is correct there as well.

Comment (vonovak) [reply packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m:166]: @douglowder this looks good to me too, but I'm not a fan of removing entries from a collection (`_pendingNotificationResponses`) while enumerating it (inside a for loop).

Comment (xc2) [reply packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m]: Thanks @vonovak. Updated.

BTW, in our android app, we did not receive events for pending responses. I haven't had a chance to determine whether this is an issue with expo or with our internal system.

File: packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m [hunk 2]
```diff
@@ -161,9 +161,13 @@ - (void)addDelegate:(id<EXNotificationsDelegate>)delegate
   [_delegates addPointer:(__bridge void * _Nullable)(delegate)];
   if ([delegate respondsToSelector:@selector(userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:)]) {
     UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
-    for (UNNotificationResponse *response in _pendingNotificationResponses) {
+    NSArray *responsesToProcess = [_pendingNotificationResponses copy];
+
+    for (UNNotificationResponse *response in responsesToProcess) {
       [delegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:^{
-        // completion handler doesn't need to do anything
+        @synchronized (self) {
```
Comment (vonovak) [inline packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m:168]: this is too complicated. If we're making a copy of `_pendingNotificationResponses`, why can't we make the copy, then clear the `_pendingNotificationResponses`, and then iterate over the copy?

**Review by vonovak — CHANGES_REQUESTED** [review]

File: packages/expo-notifications/CHANGELOG.md [hunk 3]
```diff
@@ -10,6 +10,7 @@
 
 - fix ios textInput action missing title ([#34866](https://github.com/expo/expo/pull/34866) by [@vonovak](https://github.com/vonovak))
 - [ios] Fixed incorrect `EXNotifications-Swift.h` import. ([#34987](https://github.com/expo/expo/pull/34987) by [@lukmccall](https://github.com/lukmccall))
+- [iOS] Fix `didNotificationResponseReceived` being duplicating fired for pending notification responses. ([#34849](https://github.com/expo/expo/pull/34849) by [@xc2](https://github.com/xc2))
```
Comment (vonovak) [inline packages/expo-notifications/CHANGELOG.md:13]:
```suggestion
- [iOS] fix notification response listener emitting duplicate response events ([#34849](https://github.com/expo/expo/pull/34849) by [@xc2](https://github.com/xc2))
```

**Review by vonovak — APPROVED** [review]
thank you for the fix and for the detailed reproducer! :100:
