### PR TITLE
[notifications] remove .native hardcoded platform imports

### LINKED ISSUE #26248: [SDK 50] Error on web when assigning Notifications
### Minimal reproducible example

https://github.com/jparkrr/repro-web-notifications-crash

### Summary

The following code causes an error on web in SDK 50, where it worked before.

```js
import * as Notifications from 'expo-notifications';

// This is the line that causes the error.
const ExpoLibrary = Notifications
// Interestingly, calling methods on Notifications works.

// The reason I want to do it is because I want to use the following line
// ExpoLibrary.requestPermissionsAsync()
// where ExpoLibrary can also be something like expo-contacts
```

The error is:

```
bundle.js:1529 Uncaught Error: Cannot find native module 'ExpoNotificationCategoriesModule'
```

I can probably refactor to avoid assigning `Notifications`, but I just thought you should know, and it might be causing other issues.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - ~/.asdf/installs/nodejs/20.7.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.7.0/bin/yarn
      npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.02.13.00 - /Users/justin/code/custom-watchman/Cellar/watchman/2023.02.13.00/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by marklawlor**
# Why

Fix: #26248

# How

Multiple imports have been hardcoded to import the `.native` file, circumventing platform extensions. This causes the Web to try and use native APIs. 

To appease TypeScript, I renamed the `.web.ts` files to simply `.ts`. I also adjusted the web types to match the `.native` modules, as they were using `null` instead of `boolean`. The only exception to this is commented below

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-notifications/src/setNotificationCategoryAsync.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export default async function setNotificationCategoryAsync(
   identifier: string,
   actions: NotificationAction[],
   options?: NotificationCategoryOptions
-): Promise<NotificationCategory> {
+): Promise<NotificationCategory | null> {
```
Comment (marklawlor) [inline packages/expo-notifications/src/setNotificationCategoryAsync.ts:26]: This is a public facing type change. I'm unsure of the consequences of it.

File: packages/expo-notifications/src/NotificationCategoriesModule.ts [hunk 2]
```diff
@@ -1,8 +1,8 @@
 import { NotificationAction } from './Notifications.types';
 
 export default {
-  async getNotificationCategoriesAsync(): Promise<null> {
-    return null;
+  async getNotificationCategoriesAsync(): Promise<never[]> {
```
Comment (wschurman) [inline packages/expo-notifications/src/NotificationCategoriesModule.ts:4]:
```suggestion
  async getNotificationCategoriesAsync(): Promise<NotificationCategory[]> {
```

(so that the types of the default import/export are correct in apps)

File: packages/expo-notifications/src/NotificationCategoriesModule.ts [hunk 3]
```diff
@@ -11,7 +11,7 @@ export default {
   ): Promise<null> {
```
Comment (wschurman) [inline packages/expo-notifications/src/NotificationCategoriesModule.ts:11]:
```suggestion
  ): Promise<NotificationCategory | null> {
```

(also make change to `NotificationCategoriesModule.types.ts`)

Comment (wschurman) [inline packages/expo-notifications/src/NotificationCategoriesModule.ts:11]: Also add the correct types to `options` arg for this since this is now the file used to dictate the types of the methods. Can also use `NotificationCategoryOptions` in `NotificationCategoriesModule.types.ts`
```typescript
options?: NotificationCategoryOptions
```

File: packages/expo-notifications/src/setNotificationCategoryAsync.ts (hunk 1 above)
Comment (wschurman) [reply packages/expo-notifications/src/setNotificationCategoryAsync.ts:26]: Interesting. I think it's probably fine but it could definitely cause a `tsc` error in people's apps (which is okay, we'll just want to make sure it's in the changelog).

**Review by wschurman — CHANGES_REQUESTED** [review]

**Comment by marklawlor** [comment]
Changes after review:

- rewrote `NotificationCategoriesModule` on web use the types from the `.type` file.
- reverted the changes to the public API in favor of throwing an `UnavailabilityError` on web

File: packages/expo-notifications/src/setNotificationCategoryAsync.ts (hunk 1 above)
Comment (tsapeta) [reply packages/expo-notifications/src/setNotificationCategoryAsync.ts]: Yeah, it seems fine for this simple change, I wouldn't consider it as breaking 👍

**Review by tsapeta — APPROVED** [review]

File: packages/expo-notifications/src/NotificationCategoriesModule.ts [hunk 4]
```diff
@@ -0,0 +1,19 @@
+import { UnavailabilityError } from 'expo-modules-core';
+
+import { NotificationCategoriesModule } from './NotificationCategoriesModule.types';
+
+const notificationCategoriesModule: NotificationCategoriesModule = {
+  async getNotificationCategoriesAsync() {
+    return [];
+  },
+  async setNotificationCategoryAsync() {
+    throw new UnavailabilityError('Notifications', 'setNotificationCategoryAsync');
```
Comment (wschurman) [inline packages/expo-notifications/src/NotificationCategoriesModule.ts:10]: I think this is okay, but it is technically a somewhat change for web (throws vs returns null). I think it's the correct choice though versus changing the return type to be nullable.

**Review by wschurman — APPROVED** [review]
