### PR TITLE
[speech][Android] Fix calling getVoices before TTS initialization

### LINKED ISSUE #36555: expo-speech getAvailableVoicesAsync returns nothing on Android
### Minimal reproducible example

https://gist.github.com/oovz/71b07d4beb6a85e7e3f86e65052f65fc

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go, in a development build

### Summary

Same issue as https://github.com/expo/expo/issues/11502
The ```getAvailableVoicesAsync()``` function on android returns empty array on first call.

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.15.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
      Yarn: 1.22.22 - ~\scoop\apps\yarn\current\bin\yarn.CMD
      npm: 10.9.2 - ~\scoop\apps\nodejs-lts\current\npm.CMD
    IDEs:
      Android Studio: AI-243.24978.46.2431.13363775
    npmPackages:
      expo: ~52.0.46 => 52.0.46
      expo-router: ~4.0.20 => 4.0.20
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.9 => 0.76.9
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
14/15 checks passed. 1 checks failed. Possible issues detected
Use the --verbose flag to see more details about passed checks.

✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  No metadata available: locale-codes
```

### PR DESCRIPTION
**Pull request by jakex7**
# Why

Calling the `getVoices` function before the TTS is initialized causes `textToSpeech.voices` to throw an error. As a result, the function returns an empty array instead of the list of available voices.

Resolves #36555.

# How

Although it's not the prettiest solution, we need to do a similar thing to what we do in the `speak` function. We're adding promises to a queue, and once TTS is initialized, all promises in the queue will be resolved.

# Test Plan

NCL -> TextToSpeech screen. The list of available voices should load correctly.

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-speech/android/src/main/java/expo/modules/speech/SpeechExceptions.kt [hunk 1]
```diff
@@ -6,3 +6,8 @@ import expo.modules.kotlin.exception.CodedException
 class SpeechInputIsToLongException : CodedException(
   message = "Speech input text is too long! Limit of input length is: ${TextToSpeech.getMaxSpeechInputLength()}"
 )
+
+class SpeechUnableToGetVoicesException(cause: Throwable? = null) : CodedException(
+  message = "Unable to get voices. Please check if TTS is initialized correctly.",
+  cause
+)
```
Comment (lukmccall) [inline packages/expo-speech/android/src/main/java/expo/modules/speech/SpeechExceptions.kt:13]:
```suggestion
)

```

**Review by lukmccall — APPROVED** [review]

**Review by aleqsio — APPROVED** [review]
