### PR TITLE
[jest-expo] Generate `moduleNameMapper` from `tsconfig.json` if possible

### LINKED ISSUE #23400: Jest broken in tabs@49 template
### Summary

The jest test built into the create-expo-app tabs@49 template fails, seemingly due to a lack of configured support for tsconfig path aliases:

```
npx create-expo-app@latest --template tabs@49 jest-broken
cd jest-broken
npm run test

 FAIL  components/__tests__/StyledText-test.js
  ● Test suite failed to run

    Cannot find module '@/constants/Colors' from 'components/Themed.tsx'

    Require stack:
      components/Themed.tsx
      components/StyledText.tsx
      components/__tests__/StyledText-test.js

       6 | import { Text as DefaultText, useColorScheme, View as DefaultView } from 'react-native';
       7 |
    >  8 | import Colors from '@/constants/Colors';
         | ^
       9 |
      10 | type ThemeProps = {
      11 |   lightColor?: string;

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (components/Themed.tsx:8:1)
      at Object.require (components/StyledText.tsx:1:1)
      at Object.require (components/__tests__/StyledText-test.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.017 s
Ran all test suites.
```

### What platform(s) does this occur on?

_No response_

### SDK Version

49.0.1

### Environment

  ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.8
      Shell: 5.0.7 - /usr/local/bin/bash
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/<user>/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.1 => 49.0.1
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed
```

### Minimal reproducible example

```
npx create-expo-app@latest --template tabs@49 jest-broken
cd jest-broken
npm run test
```

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #23400

# How

- Added defensive autoconversion from **tsconfig.json** `compilerOptions.paths` → Jest's **moduleNameMapper** (similarly to [`ts-jest`'s module name mapper](https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping))

# Test Plan

- `$ yarn create expo ./test-jest -t tabs@49`
- `$ cd ./test-jest`
- Link `jest-expo` with the version from this PR, e.g. through `"jest-expo": "file:../expo/expo/packages/jest-expo"`
- `$ rm -rf node_modules && yarn install`
- `$ yarn test` should NOT fail

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

File: packages/jest-expo/src/preset/withTypescriptMapping.js [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+}
+
+/** Try to add the `moduleNameMapper` configuration from the typescript `paths` configuration. */
+function withTypescriptMapping(jestConfig) {
+  const readJsonFile = JsonFile.default?.read || JsonFile.read;
+
+  try {
+    // The path to tsconfig.json is resolved relative to cwd
+    // See: _createTypeScriptConfiguration() in `createJestPreset`
+    const tsConfigPath = path.resolve('tsconfig.json');
```
Comment (EvanBacon) [inline packages/jest-expo/src/preset/withTypescriptMapping.js:53]: Also pull in `jsconfig.json` since we check both in Metro

File: packages/jest-expo/src/preset/withTypescriptMapping.js [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+    const tsConfig = readJsonFile(tsConfigPath, { json5: true });
+
+    if (tsConfig?.compilerOptions?.paths) {
+      jestConfig.moduleNameMapper = {
+        ...jestMappingFromTypescriptPaths(tsConfig.compilerOptions.paths || {}),
```
Comment (EvanBacon) [inline packages/jest-expo/src/preset/withTypescriptMapping.js:58]: Also need to support `baseUrl` which is always enabled when the file is defined.

**Review by EvanBacon — APPROVED** [review]
