### PR TITLE
[expo-notifications] Get `channelId` from remote message

### LINKED ISSUE #8990: [expo-notifications] Android push notifications doesn't respect channel's id
### Summary of Issue (just a few sentences)
When you send a push notification, it doesn't appear in the expected channel. Always goes to **Miscellaneous** channel.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.21.12 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.3
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.12
```

### Steps to Reproduce

1. Create a new project (`expo init`)
2. Setup FCM (https://docs.expo.io/guides/using-fcm/#uploading-server-credentials)
3. Update App.js to create a channel and get Expo token.
```
// create channel
Notifications.setNotificationChannelAsync('test-channel', {
  name: 'test-channel',
  importance: Notifications.AndroidImportance.MAX,
  vibrationPattern: [0, 250, 250, 250],
  lightColor: '#FF231F7C',
});

// get expo token
const { data: token } = await Notifications.getExpoPushTokenAsync();
```
4. Send a notification from the Expo push notifications console: https://expo.io/notifications
5. Add your Expo token, title body and set Channel ID to `test-channel`
6. Send a push notification.
7. Long press in the notification
8. Tap on "ALL CATEGORIES"
9. And the category **Miscellaneous** will make two blinks, saying that the notification is in that category.

### Expected Behavior vs Actual Behavior

Expected Behavior: The notification is added in the `test-channel`
Actual Behavior: A **Miscellaneous** channel is created and the notification is added to this channel.

ezgif com-video-to-gif

---
This is the channel that is created automatically and where the all notifications are added.
```
{
  "enableVibrate": true,
  "lockscreenVisibility": 0,
  "groupId": null,
  "sound": "default",
  "id": "expo_notifications_fallback_notification_channel",
  "lightColor": "#00000000",
  "audioAttributes": {
    "usage": 5,
    "flags": {
      "enforceAudibility": false,
      "requestHardwareAudioVideoSynchronization": false
    },
    "contentType": 4
  },
  "bypassDnd": false,
  "enableLights": false,
  "importance": 6,
  "vibrationPattern": null,
  "name": "Miscellaneous",
  "description": null,
  "showBadge": true
}
```

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/8990.

# How

- Get `channelId` from the remote message.

# Test Plan

- send notification via expo.io/notifications and check the channel ✅

# Changelog 

- Fixed remote notifications ignoring the `channelId` parameter.

### CODE REVIEW

**Comment by lukmccall** [comment]
I think we should scope channels to 
cc @sjchmiela

**Review by RodolfoGS — APPROVED** [review]
I tested and works perfect now 👍

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ChannelAwareNotificationBuilder.java [hunk 1]
```diff
@@ -39,6 +43,16 @@ protected String getChannelId() {
...
     }
 
+    NotificationTrigger trigger = getTrigger();
+    if (!(trigger instanceof FirebaseNotificationTrigger)) {
+      return getFallbackNotificationChannel().getId();
+    }
+
+    FirebaseNotificationTrigger firebaseNotificationTrigger = (FirebaseNotificationTrigger) trigger;
+    if (firebaseNotificationTrigger.getRemoteMessage().getData().containsKey("channelId")) {
+      return firebaseNotificationTrigger.getRemoteMessage().getData().get("channelId");
```
Comment (mczernek) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ChannelAwareNotificationBuilder.java:53]: I think this logic should in fact belong to NotificationTrigger.

I would see it like that: every notification in fact needs channel (for Android Oreo+). we might hence add `getChannelId` to NotificationTrigger and provide default which returns null. Here in the Builder, we would only check it for nullability and provide fallback channel if needed.

**Review by mczernek — CHANGES_REQUESTED** [review]

**Review by mczernek — APPROVED** [review]
Good work! 💯 🥇
