### PR TITLE
[expo-notifications][android] Fix local notifications in standalone apps

### LINKED ISSUE #10105: [expo-notifications][android] scheduled notifications do not work in standalone apps
In standalone Android apps, the "Schedule a notification in 10 seconds" test in NCL does not work. When the notification should show, nothing happens and the following is logged in the logcat:

```
09-08 12:35:16.606 19110 19110 E expo-notifications: Action expo.modules.notifications.TRIGGER_EVENT failed: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference.
09-08 12:35:16.607 19110 19110 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
09-08 12:35:16.608 19110 19110 W System.err: 	at android.util.Base64.decode(Base64.java:120)
09-08 12:35:16.608 19110 19110 W System.err: 	at expo.modules.notifications.notifications.service.SharedPreferencesNotificationsStore.deserializeNotificationRequest(SharedPreferencesNotificationsStore.java:152)
09-08 12:35:16.608 19110 19110 W System.err: 	at expo.modules.notifications.notifications.service.SharedPreferencesNotificationsStore.getNotificationRequest(SharedPreferencesNotificationsStore.java:49)
09-08 12:35:16.608 19110 19110 W System.err: 	at expo.modules.notifications.notifications.service.NotificationSchedulingHelper.onNotificationTriggered(NotificationSchedulingHelper.java:329)
09-08 12:35:16.609 19110 19110 W System.err: 	at expo.modules.notifications.notifications.service.NotificationSchedulingHelper.onHandleWork(NotificationSchedulingHelper.java:204)
09-08 12:35:16.609 19110 19110 W System.err: 	at expo.modules.notifications.notifications.service.NotificationSchedulingHelper.enqueueWork(NotificationSchedulingHelper.java:174)
09-08 12:35:16.609 19110 19110 W System.err: 	at expo.modules.notifications.notifications.service.ScheduledAlarmReceiver.onReceive(ScheduledAlarmReceiver.java:20)
...
```

Digging in a little, it looks like the string pulled from shared preferences is null, but I verified it does seem to be saved correctly. I noticed that the `SharedPreferences` object used in `getNotificationRequest` is a different instance from the one used in `saveNotificationRequest`, so I wonder if perhaps a different context object is passed in which causes a different `SharedPreferences` object to be returned? But that may easily be a red herring.

This can be reproduced by checking out the `@eric/android-standalone-sdk-39` branch and then running `et android-shell-app --sdkVersion 39.0.0 --url https://staging.exp.host/@esamelson/native-component-list`. (Note that any local changes to expo-notifications must be rebuilt into expokit by running `et abp -s 39.0.0 -p expo-notifications` before they will show up in the standalone app.)

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/10105.

# How

The SharedPreferences object used in getNotificationRequest is a different instance from the one used in saveNotificationRequest (one is created from a scoped context).

So I've changed it. Now we pass to the `NotificationsScheduler` base context - not scoped one.

# Test Plan

- `et android-shell-app --sdkVersion 39.0.0 --url https://staging.exp.host/@esamelson/native-component-list` ✅

### CODE REVIEW

File: android/expoview/src/main/java/host/exp/exponent/experience/DetachedModuleRegistryAdapter.java [hunk 1]
```diff
@@ -49,6 +50,9 @@ public DetachedModuleRegistryAdapter(ReactModuleRegistryProvider moduleRegistryP
     // Overriding expo-file-system FileSystemModule
     moduleRegistry.registerExportedModule(new ScopedFileSystemModule(scopedContext));
 
+    // `NotificationScheduler` needs to share `SharePreferences` object with a service. So we don't want to use scoped context.
```
Comment (sjchmiela) [inline android/expoview/src/main/java/host/exp/exponent/experience/DetachedModuleRegistryAdapter.java:53]:
```suggestion
    // `NotificationScheduler` needs to share `SharedPreferences` object with the notifications services, we don't want to use scoped context.
```

**Review by sjchmiela — APPROVED** [review]
Superb! Thanks for fixing this! 👍
