### PR TITLE
[expo-dev-launcher][iOS] fix dev-client compatibility with Reanimated 3.4.0

### LINKED ISSUE #23719: [expo-dev-launcher][iOS] Dev launcher breaks with reanimated 3.4.0
### Minimal reproducible example

https://snack.expo.dev/@hirbod/laughing-stroopwafels

### Summary

expo-dev-client / expo-dev-launcher is not compatible with the new react-native-reanimated version 3.4.0

Failing here:
https://github.com/expo/expo/blob/342980234003cca50904000834af098be907407d/packages/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm#L60-L64

It's trying to use a class, REAInitializer, which doesn't exist in the reanimated namespace (anymore)

9fEcleXO

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.5.0 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.2
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by piaskowyk**
# Why

Fixes https://github.com/expo/expo/issues/23719

Dev client with Reanimated 3.4.0 fails on compilation error.
```
❌  (node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:64:15)

  62 | #if __has_include(<RNReanimated/REAInitializer.h>) \
  63 |   && !RCT_NEW_ARCH_ENABLED
> 64 |   reanimated::REAInitializer(bridge);
     |               ^ no type named 'REAInitializer' in namespace 'reanimated'
  65 | #endif // __has_inclide(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
  66 | 
  67 |   return [super jsExecutorFactoryForBridge:bridge];
```

# How

In Reanimated 3.4.0 we simplified the initialization process, so the method `reanimated::REAInitializer(bridge)` is no longer required. I added check to determine if the Reanimated version is lower than 3.4.0.

# Test Plan
Run:
```bash
npx create-expo-app dev-client
cd dev-client
npx expo install expo-dev-client
npm install react-native-reanimated@3.4.0
npx expo run:ios
```
And application should lunch without any problems.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm [hunk 1]
```diff
@@ -59,7 +59,10 @@ - (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 
 - (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
 {
-#if __has_include(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
+#if __has_include(<RNReanimated/REAInitializer.h>) \
+  && __has_include(<RNReanimated/UIResponder+Reanimated.h>) /* removed in react-native-reanimated@3.4.0 */ \
+  && !RCT_NEW_ARCH_ENABLED
+  // required and available only for react-native-reanimated < 3.4.0
   reanimated::REAInitializer(bridge);
 #endif // __has_inclide(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
```
Comment (tomekzaw) [inline packages/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:67]: Let's either update the comment (including typo in `inclide`) or remove it completely due to its length.
```suggestion
#endif
```

**Comment by hirbod** [comment]
Fixes #23719

**Review by lukmccall — APPROVED** [review]
LGTM ✅

**Review by lukmccall — APPROVED** [review]
I'll merge it as soon as the CI checks passes

**Comment by hirbod** [comment]
Not sure if still related or a react-native-reanimated issue, but after installing the new version of dev-client/launcher, the App crashes with following error.

LMK if I shall report this in the reanimated repo

simulator_screenshot_77F1F1B3-039E-46B2-A6F7-C91B12C4D0F9
