### PR TITLE
[expo-gl-cpp] disable VAO extension

### LINKED ISSUE #13672: App crash with Expo Client 2.21.5 and 2.21.4 for android with expo-pixi.
### Summary

- For Android, **Issue in expo client - 2.21.4 and 2.21.5**. So, Workaround is downgrade expo client 2.19.6 - https://d1ahtucjixef4r.cloudfront.net/Exponent-2.19.6.apk
- For iOS, working fine with the latest version - https://dpq5q02fu5f55.cloudfront.net/Exponent-2.21.3.tar.gz
- - Standalone apk is working fine with expo-pixi
- linked issue - https://github.com/expo/expo-pixi/issues/187

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40, 41, 42

### Environment

expo-gl: ~9.2.0 and  expo-pixi: ^1.2.0 (checked with expo  40, 41, 42)

### Reproducible demo or steps to reproduce from a blank project

reproducable snack at https://snack.expo.io/@viveksc1994/signature-pad-crash
reproducible gitcode at https://github.com/viveksc1994/sinaturepad-crash

try to write/signature in screen with expo client 2.21.5 android app and it will give an error.
try with expo client 2.19.6 and it is working. 
 
Warning: 
```
[Unhandled promise rejection: TypeError: this.nativeVaoExtension.createVertexArrayOES is not a function. (In 'this.nativeVaoExtension.createVertexArrayOES()', 'this.nativeVaoExtension.createVertexArrayOES' is undefined)]

Stack trace:
  node_modules\pixi-gl-core\src\VertexArrayObject.js:27:4 in VertexArrayObject
  node_modules\pixi.js\lib\core\renderers\webgl\utils\Quad.js:80:53 in Quad
  node_modules\pixi.js\lib\core\renderers\webgl\managers\FilterManager.js:96:8 in FilterManager
  node_modules\pixi.js\lib\core\renderers\webgl\WebGLRenderer.js:306:51 in _initContext
  http://192.168.1.3:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:316181:24 in WebGLRenderer
  node_modules\pixi.js\lib\core\autoDetectRenderer.js:62:30 in autoDetectRenderer
  http://192.168.1.3:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:334761:65 in _callee$
```

Error:
```
TypeError: undefined is not an object (evaluating '_this.renderer._update')

Stack trace:
  node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
```

### PR DESCRIPTION
**Pull request by wkozyra95**
# Why

closes #13672

# How

Remove `OES_vertex_array_object` from list of supported extensions
- on webgl2 vao implementation is part of the standard so extension is not necessary
- implementation of that extension is not worth it just for webgl 1

# Test Plan

android - run ncl in expo go, (one of the examples was working failing before)
ios - compiles

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-gl-cpp/cpp/EXGLContext.cpp [hunk 1]
```diff
@@ -154,7 +154,9 @@ void EXGLContext::maybeReadAndCacheSupportedExtensions() {
         if (extensionName.substr(0, 3) == "GL_") {
           extensionName.erase(0, 3);
         }
-        supportedExtensions.insert(extensionName);
+        if (extensionName != "OES_vertex_array_object") {
+          supportedExtensions.insert(extensionName);
```
Comment (wkozyra95) [inline packages/expo-gl-cpp/cpp/EXGLContext.cpp:158]: Implementation is intentionally minimal to avoid conflicts with in progress refactor that will land after the next sdk release

**Review by tsapeta — APPROVED** [review]
