### PR TITLE
[babel-preset-expo] Replace `?.` with something that works in node12

### LINKED ISSUE #15544: [babel-preset-expo] Unexpected token '.'  in babel-preset-expo
### Summary

The changes in #15275 introduced newer syntax that isn't transpiled so as a result metro fails and its not possible to start up expo it fails with the following:
```
node_modules/expo/AppEntry.js: [BABEL]: Unexpected token '.' (While processing: /Users/Projects/Javascript/app/node_modules/babel-preset-expo/index.js)
/Users/lenardpratt/Projects/Javascript/optionary/node_modules/babel-preset-expo/index.js:48
        ...(options?.jsxRuntime !== 'classic' && {
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.7 - ~/.volta/tools/image/node/12.22.7/bin/node
      Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
      npm: 6.14.15 - ~/.volta/tools/image/node/12.22.7/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0-beta.1 => 44.0.0-beta.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo

Upgrade to beta 44 and run expo start, it should fail within seconds.

### PR DESCRIPTION
**Pull request by Lapz**
# Why

Fixes #15544
# How

Optional chainning is not supported in node12 and can be easily replaced with extra checks

# Test Plan

Ran `expo start`

### CODE REVIEW

**Comment by kbrandwijk** [comment]
Node 12 is in 'Maintenance LTS' mode since November 2020, Node 14 is Active LTS since October 2020. It's questionable if the 'Node LTS' requirement for Expo should mean 'Active LTS'. I personally think it should.

**Comment by Lapz** [comment]
The [docs](https://docs.expo.dev/get-started/installation/) state 
```
Only Node.js LTS releases (even-numbered) are recommended. As Node.js officially states, "Production applications should only use Active LTS or Maintenance LTS releases."

```
Node 12 is a maintenance release so imo according to the docs it should still be supported. This patch is also only a minor change so it should still be included and if we decide to not support node 12 it should be put in documentation and actively stated.

**Review by brentvatne — APPROVED** [review]

File: packages/babel-preset-expo/index.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ module.exports = function (api, options = {}) {
       {
         // Defaults to `automatic`, pass in `classic` to disable auto JSX transformations.
         runtime: (options && options.jsxRuntime) || 'automatic',
-        ...(options?.jsxRuntime !== 'classic' && {
+        ...(options && options.jsxRuntime && options.jsxRuntime !== 'classic' && {
```
Comment (EvanBacon) [inline packages/babel-preset-expo/index.js:48]: I think this is the correct translation, no?
```suggestion
        ...(options && options.jsxRuntime !== 'classic' && {
```

Comment (Lapz) [reply packages/babel-preset-expo/index.js]: Yep you're right

**Comment by kbrandwijk** [comment]
> The [docs](https://docs.expo.dev/get-started/installation/) state
> 
> ```
> Only Node.js LTS releases (even-numbered) are recommended. As Node.js officially states, "Production applications should only use Active LTS or Maintenance LTS releases."
> ```
> 
> Node 12 is a maintenance release so imo according to the docs it should still be supported. This patch is also only a minor change so it should still be included and if we decide to not support node 12 it should be put in documentation and actively stated.

Yes, you are right, I missed that last sentence. I'll be back in 4.5 months ;)

**Comment by brentvatne** [comment]
i agree that it may not be worth us supporting such a wide range of node versions, but since we do technically support node 12 for now i will merge this

**Comment by ceafive** [comment]
This change has not bubbled up yet. I upgrade to SDK 44 this morning and still got the error, I checked the code and it has the optional chaining syntax instead of the fix. 

Also I am using node 14 through nvm on my laptop, why can't I still get this to work. Any help?

**Comment by Joshandrews43** [comment]
I am using node 16 and am still unable to get this to work as well.

**Comment by j0k3r** [comment]
Any chance to release `9.0.2` with that fix?
