### PR TITLE
[ios] Migrate installation identifier to non-backed-up storage

### LINKED ISSUE #11008: [expo-notifications] Device identifier used by expo-notifications is scoped per experience
## 🐛 Bug Report

While testing https://github.com/expo/expo/pull/11005 I have found a bug — `InstallationIdProvider` exposed to JS, used to get/create `deviceId`, was not being subclassed in `expoview` and while at first it looked like it would grab the same UUID that:
- `Constants.installationId` exposed to JS, used in `expo-firebase-analytics`, `home`
- `ExponentFcmIntentService` used when automatically updating device push token on Expo servers in standalone apps
- old `Notifications` API uses when fetching an Expo push token

used thanks to the same `SharedPreferences` name and key, it actually created a UUID of its own (the module received a `ScopedContext` which automatically scopes `SharedPreferences` and while it looked like it would operate on `host.exp.exponent.SharedPreferences`, it actually used `@username/id-host.exp.exponent.SharedPreferences`.

On one hand this creates a dichotomy in installation identifiers used throughout the codebase, on the other hand it actually may make it easier for us to deprecate and eventually remove the "common" installation ID.

The one problem it raises is the fact that apps for projects that were initially built as standalone apps and then were ejected will rotate their `installationId` on this change (since in bare the `InstallationIdProvider` will no longer receive a `ScopedContext`, it will start to use the "common" installation ID) and as a result of this — Expo push token.

Essentially this boils down to whether we'd accept Expo push token change:
- as a result of upgrading (`InstallationIdProvider` could start using "common" installation ID in SDK 40)
- as a result of ejecting to bare workflow (once ejected, `InstallationIdProvider` receives unscoped `Context` and uses a different UUID than the one that it used previously).

I'm curious to hear your opinion, @ide, I thought postponing the issue to "ejecting" may look like less inconvenience for all parties (why anyone would expect tokens to change after upgrading) and "ejecting" is also a more "serious" process (during which token rotation may even look like something expected). On the other hand subclassing `InstallationIdProvider` and rotating the tokens on this upgrade fixes the issue completely and immediately (also fixing device push token being outdated in standalone apps without need to implement autoreregistration).

### Environment

This happens on Android.
 
### Steps to Reproduce

I've inspected `shared_prefs` stored in the data directory of a sample standalone app on an Android emulator and noticed two `uuid` values:
1. `/data/user/0/com.sjchmiela.myapp/shared_prefs/%40sjchmiela%2Fmy-app-host.exp.exponent.SharedPreferences.xml`
2. `/data/user/0/com.sjchmiela.myapp/shared_prefs/host.exp.exponent.SharedPreferences.xml`

Another way to see this is to run the app

<details><summary>Code</summary>

```tsx
import { StatusBar } from "expo-status-bar";
import Constants from "expo-constants";
import InstallationIdProvider from "expo-notifications/build/InstallationIdProvider";
import React from "react";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
  const [notificationsId, setNotificationsId] = React.useState<
    string | undefined
  >(undefined);
  React.useEffect(() => {
    try {
      InstallationIdProvider.getInstallationIdAsync!().then(setNotificationsId);
    } catch (e) {
      alert(e);
    }
  }, []);

  return (
    <View style={styles.container}>
      <Text>Constants.installationId</Text>
      <Text>{Constants.installationId}</Text>
      <Text>expo-notifications.installationId</Text>
      <Text>{notificationsId}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

</details>

for apps of two different `experienceId`s:

Zrzut ekranu 2020-11-12 o 22 16 23

### Expected Behavior vs Actual Behavior (or is it?)

I imagine one could expect `InstallationIdProvider` to always return the same identifier as `Constants.installationId`.

Currently it returns the same identifier only on apps in bare workflow.

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

- iOS companion for https://github.com/expo/expo/pull/11005.
- https://github.com/expo/expo/pull/11019/commits/1e22e08195b1b4c49650f8243eeb89b5f938b9a5 fixes https://github.com/expo/expo/issues/11008#issuecomment-726370187 ensuring future versioned `EXInstallationIdProvider`s use the common installation ID

# How

Implemented https://github.com/expo/expo/pull/10261#issuecomment-725396140.

- As in https://github.com/expo/expo/pull/11005, the migration code is present in ~3~2 places:
  - ~in `ExpoKit` for managed apps relying on legacy notifications~
  - in `expo-constants` for bare workflow apps and for managed workflow apps (`EXKernel` now uses `expo-constants` directly to fetch installation ID)
  - in `expo-notifications` for bare workflow apps that for some reason do not get UUID migrated by `expo-constants` (eg. because they do not have `expo-constants` installed or have installed in older version).
- To expose common, migrated `deviceInstallUUID` to versioned `expo-constants` code I've added a simple kernel service plugged into already versioned `EXConstantsBinding`s.

# Test Plan

I have verified (previously) that:
- `Constants.installationId` from running Expo client on `master` is the same as `.installationId` returned when running Expo client on this branch
- `expo-notifications`'s installation ID from running Expo client on `master` is the same as `installationId` returned when running Expo client on this branch
- removing and reinstalling Expo client **does not** generate a different installationId (as we know keychain isn't removed!)
- if we fetch an invalid UUID from the Keychain, new UUID is generated
- I experienced an app freeze once on `__ulock_wait`, when waiting for return from `SecItemCopyMatching` which isn't a common issue and were only a few reports online of

# Test approach #2

Test scenarios for installation identifiers:
- **on an experience running on SDK39 when Expo client upgrades**
  - SDK39 `EXConstantsService` used `NSUserDefaults.EXDeviceInstallUUIDKey` which is now cleared by migration. Patched `EXConstantsService` uses `EXDeviceInstallUUIDManager` kernel service which provides it with the "common" ID, migrated from the `NSUserDefaults.EXDeviceInstallUUIDKey`, so the value doesn't change. ✅ 
  - SDK39 `EXInstallationIdProvider` used `NSUserDefaults.ABI39_0_0EXDeviceInstallUUIDKey` which is not cleared by any migration. **Identifier keeps being backed-up** but it doesn't change. ⚠️ 
- **when an experience using SDK39 upgrades to SDK40 in Expo client**
  - SDK39 `EXConstantsService` used `NSUserDefaults.EXDeviceInstallUUIDKey` which got migrated to keychain. SDK40 `EXConstantsService` uses the same keychain entry as the migrator, so they're using the same value. ✅ 
  - SDK39 `EXInstallationIdProvider` used `NSUserDefaults.ABI39_0_0EXDeviceInstallUUIDKey` while SDK40 uses common device UUID the sources are obviously different. Token changes. ❌  This is a bug introduced with `expo-notifications` Expo client integration, we can't do anything about it apart from fixing it in SDK40, IDs for old SDKs are already created and will be used in corresponding SDKs and if we didn't do anything about it in SDK40, the ID per experience would change nonetheless, so let's change it this time for the last time.
- when standalone app using SDK39 upgrades to SDK40
  - Unversioned SDK39 `EXConstantsService` used `NSUserDefaults.EXDeviceInstallUUIDKey` which gets migrated to keychain, unversioned SDK40 `EXConstantsService` uses the same keychain entry as common UUID, no changes. ✅ 
  - Unversioned SDK39 `EXInstallationIdProvider` used `NSUserDefaults.EXDeviceInstallUUIDKey` which gets migrated to keychain, unversioned SDK40 `EXInstallationIdProvider` uses the same keychain entry as common UUID, no changes. ✅ 
- when an SDK39 project ejects to bare
  - SDK39 `EXConstantsService` used `NSUserDefaults.EXDeviceInstallUUIDKey`, the same which is used in bare, ✅ 
  - SDK39 `EXInstallationIdProvider` used `NSUserDefaults.EXDeviceInstallUUIDKey` in standalone apps, but `NSUserDefaults.ABI39_0_0EXDeviceInstallUUIDKey` in Expo client. Token changes on developers' devices. ⚠️ 
- when an SDK40 project ejects to bare
  - SDK40 `EXConstantsService` used `EXDeviceInstallUUIDKey` keychain entry, the same which is used in bare, ✅ 
  - SDK40 `EXInstallationIdProvider` used `EXDeviceInstallUUIDKey` keychain entry, the same which is used in bare (`EXDeviceInstallUUIDKey`), ✅ 
- when a bare project upgrades `expo-notifications` or `expo-constants`
  - both projects have migrators that move `EXDeviceInstallUUIDKey` value from `NSUserDefaults` to keychain, token doesn't change. ✅

### CODE REVIEW

File: packages/expo-constants/ios/EXConstants/EXConstantsService+InstallationId.m [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+    } else {
+      // We only remove the value from old storage once it's set and saved in the new storage.
+      [[NSUserDefaults standardUserDefaults] removeObjectForKey:kEXDeviceInstallUUIDKey];
+    }
+  }
+  
+  return installationId;
+}
+
+- (nullable NSError *)setInstallationId:(NSString *)installationId
```
Comment (ide) [inline packages/expo-constants/ios/EXConstants/EXConstantsService+InstallationId.m:56]: cocoa convention is to return a `BOOL` and accept `NSError **` (this also helps when translating to Swift)

File: packages/expo-constants/ios/EXConstants/EXConstantsService+InstallationId.m [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+    return installationId;
+  }
+  
+  NSString *legacyUUID = [[NSUserDefaults standardUserDefaults] stringForKey:kEXDeviceInstallUUIDKey];
+  if (legacyUUID) {
+    installationId = legacyUUID;
+    
+    NSError *error = [self setInstallationId:installationId];
+    if (error) {
+      NSLog(@"Could not migrate device install UUID from legacy storage: %@", error.description);
```
Comment (ide) [inline packages/expo-constants/ios/EXConstants/EXConstantsService+InstallationId.m:46]:
```suggestion
      NSLog(@"Could not migrate device installation UUID from legacy storage: %@", error.description);
```

File: packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m [hunk 3]
```diff
@@ -15,12 +15,98 @@ @implementation EXInstallationIdProvider
...
+    return installationId;
+  }
+  
+  NSString *legacyUUID = [[NSUserDefaults standardUserDefaults] stringForKey:kEXDeviceInstallUUIDKey];
+  if (legacyUUID) {
+    installationId = legacyUUID;
+    
+    NSError *error = [self setInstallationId:installationId];
+    if (error) {
+      NSLog(@"Could not migrate device install UUID from legacy storage: %@", error.description);
```
Comment (ide) [inline packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m:53]:
```suggestion
      NSLog(@"Could not migrate device installation UUID from legacy storage: %@", error.description);
```

File: packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m [hunk 4]
```diff
@@ -15,12 +15,98 @@ @implementation EXInstallationIdProvider
...
+  
+  installationId = [[NSUUID UUID] UUIDString];
+  [self setInstallationId:installationId];
+  return installationId;
+}
+
+- (nullable NSString *)fetchInstallationId
+{
+  NSString *installationId;
+  CFTypeRef foundDict = NULL;
```
Comment (ide) [inline packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m:31]: this isn't a dict
```suggestion
  CFTypeRef keychainResult = NULL;
```

File: ios/Exponent/Versioned/Core/UniversalModules/EXNotifications/EXScopedInstallationIdProvider.h [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+- (NSString *)deviceInstallUUID;
+
+@end
+
+NS_ASSUME_NONNULL_END
+
+// We only define EXScopedInstallationIdProvider if EXInstallationIdProvider
+// is available, otherwise in installations that don't have expo-notifications
+// it wouldn't compile (while technically as of December 2020 it shouldn't
+// happen, it eventually main, so let's stay on the safe side).
```
[the remark this answers is not in the document]
Comment (ide) [reply ios/Exponent/Versioned/Core/UniversalModules/EXNotifications/EXScopedInstallationIdProvider.h:18]: This said, I'm not sure we need this guard even in the future -- wouldn't we want to group EXInstallationIdProvider and EXScopedInstallationIdProvider together?

File: ios/Exponent/Kernel/Core/EXKernel+DeviceInstallUUID.h [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+#import "EXKernel.h"
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface EXKernel (DeviceInstallUUID)
+
+/**
+ *  An id that uniquely identifies this installation of Exponent.
+ */
++ (NSString *)deviceInstallUUID;
```
Comment (ide) [inline ios/Exponent/Kernel/Core/EXKernel+DeviceInstallUUID.h:12]: This is used only for legacy Notifications, right? If so, let's mention that so we don't use it anymore.

```suggestion
+ (NSString *)deviceInstallUUID __attribute((deprecated("The installation ID API is deprecated and will be removed with legacy Notifications")));
;
```

File: ios/Exponent/Kernel/Core/EXKernel+DeviceInstallUUID.h [hunk 7]
```diff
@@ -0,0 +1,16 @@
+// Copyright 2015-present 650 Industries. All rights reserved.
+
+#import "EXKernel.h"
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface EXKernel (DeviceInstallUUID)
+
+/**
+ *  An id that uniquely identifies this installation of Exponent.
```
Comment (ide) [inline ios/Exponent/Kernel/Core/EXKernel+DeviceInstallUUID.h:10]:
```suggestion
 *  An ID that uniquely identifies this installation of Expo Go
```

**Review by ide — COMMENTED** [review]
The three copies of the keychain code seem like a lot. I don't have an answer but ideally we'd have just one or two copies -- one if we decide that the installation ID and push notification device ID should be the same, and two if we decide to split the installation ID from the push notification device ID.

File: ios/Exponent/Kernel/Core/EXKernel+DeviceInstallUUID.h (hunk 6 above)
Comment (sjchmiela) [reply ios/Exponent/Kernel/Core/EXKernel+DeviceInstallUUID.h:12]: I made it so that `[EXKernel deviceInstallUUID]` is used by `EXDeviceInstallUUIDManager` kernel service which is provided to bindings (subclasses of unimodules used only in ExpoKit):
- `expo-constants`, so that `installationId` in ExpoKit always returns the "common" ExpoKit ID
- `expo-notifications` so that `installationId` in ExpoKit from now on always returns the "common" ExpoKit ID
- versioned constants so that they don't try to create a UUID in `NSUserDefaults` (as was the implementation for SDKs < 40) which would result in ID change for versioned constants (migration removes ID from `NSUserDefaults` to Keychain).

The benefit of overriding unimodules to ensure they're using "common" ExpoKit ID was supposed to be that we would ensure on an "architecture" level that the ID doesn't ever change in managed workflow for any of the modules no matter their bare implementation. I tended to favor this over "loose integration" with which the modules would use the same storage the same way as ExpoKit, but having a copy of the implementation (this is how `EXConstantsService` was ensuring it uses the `deviceInstallUUID` from ExpoKit, it used `NSUserDefaults` with `EXDeviceInstallUUIDKey`; this is also how `EXInstallationIdProvider` was supposed to use the same UUID had it been added to `expotools` list of extra transform rules at https://github.com/expo/expo/blob/95dffabd0058cea1f8d18175aeb5aadef7d1a95b/tools%2Fexpotools%2Fsrc%2Fversioning%2Fios%2Findex.ts#L1149-L1153).

This, however, is unnecessary if we write bare code well carefully (versioning-compatible), so I will change the implementation so that:
- `expo-constants` uses Keychain and includes migration
- `expo-notifications` uses Keychain and includes migration
- legacy notifications use kernel which does not include migration, instead it uses `expo-constants` to fetch the installation ID
- versioned constants use kernel service which uses `expo-constants` to fetch the installation ID.

This way deprecating `installationId` of `expo-constants` is directly related to deprecating versioned constants and legacy notifications which both are/eventually will be deprecated too. `expo-notifications` have their own implementation which won't be deprecated.

I initially didn't want to connect kernel this directly to `expo-constants`, but you're right to say that it won't do any harm. 👍 Thanks!

File: ios/Exponent/Versioned/Core/UniversalModules/EXNotifications/EXScopedInstallationIdProvider.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (sjchmiela) [reply ios/Exponent/Versioned/Core/UniversalModules/EXNotifications/EXScopedInstallationIdProvider.h:18]: As per explanation in https://github.com/expo/expo/pull/11019#discussion_r526346736, I will remove `EXScopedInstallationIdProvider` in favor of using the keychain manually in `expo-notifications` (and fixing `expotools` as in https://github.com/expo/expo/pull/11019/commits/ecf7f307a0ff4a364820b37258115e024c4dba21).

**Review by ide — APPROVED** [review]

File: packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m [hunk 8]
```diff
@@ -15,12 +16,97 @@ @implementation EXInstallationIdProvider
...
+  
+  if (installationId) {
+    return installationId;
+  }
+  
+  NSString *legacyUUID = [[NSUserDefaults standardUserDefaults] stringForKey:kEXDeviceInstallationUUIDLegacyKey];
+  if (legacyUUID) {
+    installationId = legacyUUID;
+
+    NSError *error = nil;
```
Comment (ide) [inline packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m:52]: BTW this is fine (and is how I've written this kind of code) but it's also correct to write `NSError *error;`. Unlike C, ARC will initialize object pointers to `nil` even on the stack.

Comment (sjchmiela) [reply packages/expo-notifications/ios/EXNotifications/EXInstallationIdProvider.m:52]: Initially I've written it like `NSError *error;` knowing it will get initialized to `nil`, but then I decided to see how this structure has been used in the codebase in other places to follow existing conventions and I saw https://github.com/expo/expo/blob/57a8ea27d2e83dc4d749c79fdf5419849e33db7f/ios/Exponent/Kernel/Api/EXApiV2Client.m#L98 and decided to follow its example. Thanks for the note and confirming my expectations!

File: ios/Exponent/Kernel/Services/EXDeviceInstallationUUIDService.h [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+
+#import <Foundation/Foundation.h>
+#import <ABI39_0_0ExpoKit/ABI39_0_0EXConstantsBinding.h>
+#import <ABI38_0_0ExpoKit/ABI38_0_0EXConstantsBinding.h>
+#import <ABI37_0_0ExpoKit/ABI37_0_0EXConstantsBinding.h>
+
+NS_ASSUME_NONNULL_BEGIN
+
+// A kernel service allowing versioned expo-constants to access device installation UUID
+__deprecated_msg("The installation ID API is deprecated and will be removed with SDK39")
```
[the remark this answers is not in the document]
Comment (sjchmiela) [reply ios/Exponent/Kernel/Services/EXDeviceInstallationUUIDService.h:11]: This kernel service will stop being used once we remove SDK 39 (I hope these changes make it before SDK 40 versioning and SDK 39 will be the last SDK where the kernel service will be used). However, your comment made me rethink when will we be able to remove `[EXKernel deviceInstallationUUID]` which we'll be able to remove once:
- SDK 39 is removed (since kernel service used by versioned `EXConstantsBinding` uses `EXKernel` under the hood) **and**
- legacy Notifications API is removed,

which will be further in the future than just SDK 39 removal. I'll fix the comment there to mention legacy Notifications too.

[the remark this answers is not in the document]
Comment (sjchmiela) [reply ios/Exponent/Kernel/Services/EXDeviceInstallationUUIDService.h]: Actually updated both `deprecated` messages with:
> The installation ID API is deprecated and will be removed once both SDK 39 and legacy Notifications API are removed

and added
```
// TODO: Remove this after SDK 39 is phased out
```
over `EXDeviceInstallationUUIDService`.
