### PR TITLE
[file-system][android] Fix copy/move support for SAF/content URIs

### LINKED ISSUE #42343: [expo-file-system] error on android files with uri with `content://` scheme
### Minimal reproducible example

https://github.com/romain-sen/issue-contact-new-expo-file-system

### Reproduction Code

```typescript
import { File, Paths } from 'expo-file-system';

const copyContactImage = async (uri: string) => {
  const src = new File(uri); // uri = "content://com.android.contacts/contacts/1/photo"
  const dest = new File(Paths.document, "photo.png");

  src.copy(dest); // ❌ Throws: Invalid URI
}
```

### Steps to reproduce

These are the steps I detailed in the `Readme.md`

### Prerequisites

- Node.js installed
- Android Studio with an emulator configured (or a physical Android device)
  - In my case, I reproduced the issue on a physical Android device (Xiaomi Redmi Note 13)
- At least one contact with a photo saved on the device/emulator

### 1. Install dependencies

```bash
npm install
```

### 2. Prebuild the Android project

```bash
npx expo prebuild --platform android
```

### 3. Run on Android

```bash
npx expo run:android
```

Or use the shortcut:

```bash
npm run android
```

### 4. Grant permissions

When the app launches, grant the contacts permission when prompted.

### 5. Observe the error

Check the Metro bundler console. You should see the error message about the invalid `content://` URI.

## Expected Behavior

The `File.copy()` method should handle `content://` URIs the same way the legacy `copyAsync()` function did.

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 15.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.21.0 - ~/.nvm/versions/node/v22.21.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.4 - ~/.nvm/versions/node/v22.21.0/bin/npm
      Watchman: 2025.05.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.3 AI-243.25659.59.2432.13423653
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.31 => 54.0.31
      expo-router: ~6.0.21 => 6.0.21
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
      react-native-web: ~0.21.0 => 0.21.2
    npmGlobalPackages:
      eas-cli: 16.28.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by barthap**
# Why

Legacy FileSystem supported copying from SAF and other `content://` URIs. This is very limited or missing in the new file system - it relies heavily on `javaFile` which is usually not available for content URIs.

# How

- Added non-SAF `ContentProviderFile` implementation of `UnifiedFileInterface` to let FileSystem support some subset of common operations
- Created a delegate to the unified interface that handles copying and moving between JavaFile, SAF, Asset and ContentProviderFile
  - handled edge cases and optimizations (assets stay read-only; JavaFiles are atomically copied using native Java File APIs)
  - to avoid spaghetti of nested if-else, came up with kinda over-engineered solution with two sealed classes:
    -  `CopyMoveStrategy` to handle each file type that can be copied and prepare destination config
    -  `DestinationSink` to handle creating the destination file and writing to it
- Introduced a `overwrite` boolean that can be easily exposed to the JS API in a later PR (legacy filesystem was always overwriting, new does not do it).

# Test Plan

- New Test Suite tests
- Added instrumentation tests

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/JavaFile.kt [hunk 1]
```diff
@@ -22,13 +23,13 @@ class JavaFile(override val uri: Uri) : UnifiedFileInterface, File(URI.create(ur
...
     childFile.createNewFile()
     return JavaFile(childFile.toUri())
   }
 
   override fun createDirectory(displayName: String): UnifiedFileInterface? {
-    val childFile = File(super<File>.parentFile, displayName)
+    val childFile = File(this, displayName)
     childFile.mkdir()
     return JavaFile(childFile.toUri())
   }
```
Comment (barthap) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/JavaFile.kt:35]: This change is to make `JavaFile.createFile()` consistent with what `SAFDocumentFile` does: it creates a **child** file/directory, not a neighboring one.
It is now tested in the `copies SAF directory -> local directory (existing)` test _(Line 874 in test suite)_

This is theoretically breaking, but:
- these methods have no JS docs
- they are mainly intended to be used for SAF

Also, on iOS they already do child creation as expected

**Comment by barthap** [comment]
* **#43083** <a href="https://app.graphite.com/github/pr/expo/expo/43083?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#42983** <a href="https://app.graphite.com/github/pr/expo/expo/42983?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#42979** <a href="https://app.graphite.com/github/pr/expo/expo/42979?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#42887** <a href="https://app.graphite.com/github/pr/expo/expo/42887?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/42887?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+
+      val extension = MimeTypeMap.getFileExtensionFromUrl(uri.toString())
+      return extension.takeUnless { it.isNullOrEmpty() }?.let { ext ->
+        MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext.lowercase())
+      }
+    }
+
+  override fun lastModified(): Long? {
+    return queryColumn(OpenableColumns.SIZE)?.toLongOrNull()
+  }
```
Comment (Wenszel) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt]:
```suggestion
  override fun lastModified(): Long? = null
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+
+  override fun isFile(): Boolean = exists()
+
+  override fun isDirectory(): Boolean = false
+
+  override val parentFile: UnifiedFileInterface? = null
+
+  override fun createFile(mimeType: String, displayName: String): UnifiedFileInterface? {
+    throw UnsupportedOperationException("Cannot create files in generic content provider: $uri")
+  }
```
Comment (Wenszel) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt]:
```suggestion
  override fun createFile(mimeType: String, displayName: String) =
    throw UnsupportedOperationException("Cannot create files in generic content provider: $uri")
```

Image

**Review by Wenszel — COMMENTED** [review]
I love that abstraction. Looks solid and definitely not over-engineered!

File: packages/expo-file-system/android/src/androidTest/java/expo/modules/filesystem/CopyMoveOperationsTest.kt [hunk 4]
```diff
@@ -0,0 +1,532 @@
...
+ * - Unix cp/mv behavior semantics
+ */
+class CopyMoveOperationsTest {
+
+  private val context = InstrumentationRegistry.getInstrumentation().targetContext
+  private val resolver = context.contentResolver
+
+  // ============================================================================
+  // TEST HELPERS
+  // ============================================================================
```
Comment (lukmccall) [inline packages/expo-file-system/android/src/androidTest/java/expo/modules/filesystem/CopyMoveOperationsTest.kt]: I'm not a huge fan of these custom section headers. However, if you want to add them, use `region` declaration - it has a better IDE support. See: https://stackoverflow.com/a/67969752

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemPath.kt [hunk 5]
```diff
@@ -25,6 +29,11 @@ val Uri.isAssetUri
     return scheme == "asset"
   }
 
+fun Uri.isSAFUri(context: Context): Boolean =
+  isContentUri && (
+    DocumentsContract.isDocumentUri(context, this) || DocumentsContract.isTreeUri(this)
+    )
```
Comment (lukmccall) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemPath.kt:35]:
```suggestion
  )
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/fsops/Utilities.kt [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+ */
+internal fun copyFileViaStream(
+  source: UnifiedFileInterface,
+  dest: UnifiedFileInterface
+) {
+  require(source.isFile()) { "Source must be a file" }
+
+  source.inputStream().use { input ->
+    dest.outputStream().use { output ->
+      input.copyTo(output)
```
Comment (lukmccall) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/fsops/Utilities.kt:21]: Hmm, this is fine, however, we could use `FileChannel.transferTo`. It would be much faster - `java.nio > java.io`, but it's worth considering as it's much harder to use.

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt [hunk 7]
```diff
@@ -0,0 +1,127 @@
...
+  override fun walkTopDown(): Sequence<UnifiedFileInterface> = sequenceOf(this)
+
+  override val copyMoveStrategy: CopyMoveStrategy = CopyMoveStrategy.ContentProvider(this)
+
+  /**
+   * Helper to query a column from the ContentResolver.
+   */
+  private fun queryColumn(column: String): String? {
+    return runCatching {
+      context.contentResolver.query(uri, arrayOf(column), null, null, null)?.use { cursor ->
```
Comment (lukmccall) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt]:
```suggestion
      context
        .contentResolver
        .query(
          uri, 
          arrayOf(column), 
          null, 
          null, 
          null
        )?.use { cursor ->
```

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt [hunk 8]
```diff
@@ -0,0 +1,127 @@
...
+      inputStream().use { stream ->
+        var total = 0L
+        val buffer = ByteArray(8192)
+        var read: Int
+        while (stream.read(buffer).also { read = it } != -1) {
+          total += read
+        }
+        total
+      }
+    }.getOrNull() ?: 0L
```
Comment (lukmccall) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt:100]: It will be really, really slow.
Also, I would return -1 if we can't determine the size.

**Review by lukmccall — APPROVED** [review]

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt (hunk 8 above)
Comment (barthap) [reply packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/ContentProviderFile.kt:100]: This is the same approach [we already use for `AssetFile`](https://github.com/expo/expo/blob/f7e1446643ecb852f89491f71a331dec4be7022a/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/unifiedfile/AssetFile.kt#L118-L129). I know it's slow, but it's a fallback approach.
Returning 0 is consistent with other file types here, including JavaFile [`length()`](https://developer.android.com/reference/java/io/File#length())

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/fsops/Utilities.kt (hunk 6 above)
Comment (barthap) [reply packages/expo-file-system/android/src/main/java/expo/modules/filesystem/fsops/Utilities.kt:21]: FileChannel would be great, but we don't have a guarantee it's available. I'll see if this can be easily improved -  perhaps we can get a `File{Input,Output}Stream` (instead of generic `Input/OutputStream`) to get a `FileChannel`

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemPath.kt (hunk 5 above)
Comment (barthap) [reply packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemPath.kt:35]: This dissatisfies spotless 😒

**Comment by barthap** [comment]
### Merge activity

* **Mar 4, 12:15 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/expo/expo/42887).
* **Mar 4, 12:16 PM UTC**: @barthap merged this pull request with [Graphite](https://app.graphite.com/github/pr/expo/expo/42887).
