### PR TITLE
[docs] fix broken links on get started and guides

### LINKED ISSUE #7985: [docs] [expo-notifications]
The link "[this guide](https://docs.expo.io/versions/latest/guides/native-firebase/#bare-workflow-setup)" under **Configure for Android** section is broken

### PR DESCRIPTION
**Pull request by byCedric**
# Why

I ran a full check of all links, there is still a lot left in the API reference. But this fixes the "Get Started" and "Guides" sections. (Fixes #7985)

# How

Ran export locally and double-checked the links.

# Test Plan

Could be great if we can detect internal links and/or headers by ESLint or something related 😄

### CODE REVIEW

File: docs/components/DocumentationFooter.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ function githubUrl(path) {
     } else {
       path = path.replace('/versions/latest/', '/versions/unversioned/');
     }
-  } else if (path.match(/v\d+\.\d+\.\d+\/?$/)) {
+  } else if (path.match(/v\d+\.\d+\.\d+\/?$/) || path === '/') {
```
Comment (byCedric) [inline docs/components/DocumentationFooter.js:28]: Fixes the `Edit on GitHub` from the [intro page](https://docs.expo.io).

File: docs/pages/guides/using-graphql.md [hunk 2]
```diff
@@ -157,8 +157,6 @@ There are four major GraphQL clients available at the moment:
 
 Apollo, Relay and Urql implement further features like caching, realtime support with GraphQL subscriptions or optimistic UI updates.
 
-Learn how to integrate with Auth0 social providers in the [expo-auth0-example](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-expo-and-auth0) repository.
```
Comment (byCedric) [inline docs/pages/guides/using-graphql.md:160]: This is now outdated and not supported, graphcool also doesn't exist anymore (now prisma). 😅 This page could use a refresh

**Review by brentvatne — APPROVED** [review]
