### PR TITLE
[expo-image-picker] Fixed downsizing cropped image on iOS

### LINKED ISSUE #8079: [expo-image-picker] [iOS] Image quality degraded after crop with `allowsEditing: true`
## 🐛 Bug Report

If the user selects a high resolution image, say 3000x2000px, and then crops it to square using the built-in editor (invoked with `allowsEditing` option), then the resulting image is dramatically reduced in quality (usually around 820x820px) instead of the expected 2000x2000px.

This appears to be a consequence of using iOS's built-in `UIImagePickerController`, or specifically using the `UIImagePickerControllerEditedImage` from `UIImagePickerController.InfoKey` which appears to return a lower-resolution version of the cropped image.

See [relevant Expo code here](https://github.com/expo/expo/blob/master/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L224-L228).

Suggested fix:
Instead of getting the `UIImagePickerControllerEditedImage` we should get `UIImagePickerControllerOriginalImage` and `UIImagePickerControllerCropRect` and perform a resolution-preserving crop operation.

The other quirk I noticed is that the `1:1` aspect ratio is not always preserved. It's often off by a few pixels. If we are handling the CropRect ourself, we can control for this. Thoughts?

### Environment

  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - node_modules/.bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.19.2

Target: iOS

### Steps to Reproduce

1. Using `allowsEditing: false`, open the Simulator, pick one of the sample images, log its dimensions.
2. Using `allowsEditing: true`, do the same, but this time crop to square and log it's dimensions.
3. Notice that the image has been downscaled.

### Expected Behavior

The cropping should not downsample the image, if just cropping.

### Actual Behavior

The image has been downsampled.

### Reproducible Demo

https://snack.expo.io/@sstur/image-picker-demo

### PR DESCRIPTION
**Pull request by barthap**
# Why
Fixes #8079

# How
Instead of getting [`UIImagePickerControllerEditedImage`](https://developer.apple.com/documentation/uikit/uiimagepickercontrollereditedimage?language=objc) which is cropped and downsized, I take the original image and cropping rect, then crop it manually.
Based on [this thread](https://stackoverflow.com/questions/11233277/how-to-perform-square-cut-to-the-photos-in-camera-roll), however instead of rotating the cropping rect, I took advantage of already implemented `fixOrientation` and it seems to work.
Images are cropped correctly and aren't downsized anymore.

> Note: Cropped images still aren't perfect squares (dimensions often differ by a few pixels). This isn't reason for this PR

# Test Plan
Test using demo from issue. Tested portrait and landscape images, as well as rotated images.
- [x] Test on iOS Simulator
- [x] Test on real device.

### CODE REVIEW

**Comment by barthap** [comment]
Maybe a better way would be to make this change optional? (additional parameter)

**Review by tsapeta — APPROVED** [review]

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 1]
```diff
@@ -220,13 +220,18 @@ - (void)handleImageWithInfo:(NSDictionary * _Nonnull)info
...
   NSDictionary *metadata = [info objectForKey:UIImagePickerControllerMediaMetadata];
-  UIImage *image;
+  UIImage *image = [info objectForKey:UIImagePickerControllerOriginalImage];
+  image = [self fixOrientation:image];
   if ([[self.options objectForKey:@"allowsEditing"] boolValue]) {
-    image = [info objectForKey:UIImagePickerControllerEditedImage];
-  } else {
-    image = [info objectForKey:UIImagePickerControllerOriginalImage];
+    NSValue* rectVal = [info objectForKey:UIImagePickerControllerCropRect];
+    CGRect rect = rectVal.CGRectValue;
```
Comment (bbarthec) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:227]: Is it possible? 🤔 
```suggestion
    CGRect rect = [info objectForKey:UIImagePickerControllerCropRect].CGRectValue;
```
And if it's not:
```suggestion
	CGRect rect = ((NSValue *) [info objectForKey:UIImagePickerControllerCropRect]).CGRectValue;
```

**Review by bbarthec — APPROVED** [review]
LGTM 👍

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 1 above)
Comment (barthap) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m:227]: First one isn't possible ;P You need to cast explicitly.

**Review by lukmccall — APPROVED** [review]
LGTM 🎉🎉🎉
