### PR TITLE
[android] Fix another background task exception

### LINKED ISSUE #15515: [SDK44] startLocationUpdatesAsync doesn't work when app is killed + Crashes App
### Summary

i'm upgrading from SDK 42 to test the Background location which is already working fine but sometimes crashes with null pointer which is supposed to be fixed here https://github.com/expo/expo/pull/15023 , in changelogs i saw that's been fixed so i tried it on SDK44 . i'm building with the classic build system : expo build

Main Problem Description :  **startLocationUpdatesAsync doesn't work on killed state**

I start the bakground location , it works without a problem on foreground and background .
When i kill the app i'd like to have the location updates for my users who always kill their app .
Anyway : If i kill the App , i wait for while (10 - 20 min ) before the background location updates start , when it does , i see the foreground service but there are no location updates , values are not changing on my server . The same code on SDK42 Works with no problems . I don't know if it's an issue with location module or task-manager.

i attached a mini project to reproduce the Bug .

I hope you can fix this issue ASAP, it was already working fine with SDK42 except for this  issue #15023 
i have a big project based on background locations and i'm having a hard time with this .

Second problem : 

If i kill my app while the background location is on : i get this exception the next time i launch my app , it stucks on splash screen. (to catch this bug the location update must be started , so wait for the updates to start after you kill the app before you launch it again )

`java.lang.RuntimeException: Cannot get ReactInstanceManager from kernel
        at versioned.host.exp.exponent.ExpoTurboPackage.getDefaultUIManager(ExpoTurboPackage.kt:9)
        at versioned.host.exp.exponent.ExpoTurboPackage.getModule(ExpoTurboPackage.kt:3)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:2)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:1)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:8)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:7)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:11)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:6)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:1)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:3)
        at versioned.host.exp.exponent.modules.api.reanimated.NodesManager.<init>(NodesManager.java:13)
        at versioned.host.exp.exponent.modules.api.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:2)
        at versioned.host.exp.exponent.modules.api.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:2)
        at versioned.host.exp.exponent.VersionedUtils$getReactInstanceManagerBuilder$builder$1.getJSIModules(VersionedUtils.kt:6)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:21)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:1)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:12)
        at java.lang.Thread.run(Thread.java:923)`

[backgroundLocationDemo.zip](https://github.com/expo/expo/files/7697687/backgroundLocationDemo.zip)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^44.0.0-beta.1 => 44.0.0-beta.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

[backgroundLocationDemo.zip](https://github.com/expo/expo/files/7697687/backgroundLocationDemo.zip)

### PR DESCRIPTION
**Pull request by Kudo**
# Why

yet another exception specific happen to background task manager, especially switching from background to foreground. the `JSIModulePackage` is called before the `ReactInstanceManager` attached to `ReactNativeActivity`. in this case,  we will get a NPE like this:

```
wn:ReactInstanceManager  W  Instance detached from instance manager
     ExperienceActivity  E  java.lang.NullPointerException
                      j  E  Runtime exception in RNObject when calling method getDevSupportManager: java.lang.NullPointerException: null receiver
             System.err  W  java.lang.reflect.InvocationTargetException
                         W      at java.lang.reflect.Method.invoke(Native Method)
                         W      at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:4)
                         W      at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:1)
                         W      at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:19)
                         W      at java.lang.Thread.run(Thread.java:920)
                         W  Caused by: com.facebook.react.common.JavascriptException
                         W      at host.exp.exponent.ReactNativeStaticHelpers.handleReactNativeError(ReactNativeStaticHelpers.kt:8)
                         W      ... 5 more
```

fixes #15515

# How

- leverage kotlin nullable for `ReactNativeActivity.devSupportManager`
- backport VersionedUtils changes to versioned code

# Test Plan

- [standalone app] follow #15515 steps
- [versioned expo go] test changed functions from sdk41-44 & unversioned apps
  - reload
  - toggleElementInspector
  - togglePerformanceMonitor
  - toggleRemoteJSDebugging

# Checklist

- n/a Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: android/expoview/src/main/java/versioned/host/exp/exponent/VersionedUtils.kt [hunk 1]
```diff
@@ -56,27 +56,37 @@ object VersionedUtils {
...
         ReactConstants.TAG,
         "Unable to reload the app because the current activity could not be found."
       )
     }
+    val devSupportManager = currentActivity.devSupportManager ?: return let {
+      FLog.e(
+        ReactConstants.TAG,
+        "Unable to get the DevSupportManager from current activity."
+      )
+    }
```
Comment (lukmccall) [inline android/expoview/src/main/java/versioned/host/exp/exponent/VersionedUtils.kt:70]:
```suggestion
    val devSupportManager = currentActivity.devSupportManager ?: return run {
      FLog.e(
        ReactConstants.TAG,
        "Unable to get the DevSupportManager from current activity."
      )
    }
```
You don't have to change it to `run`, but for future uses, I think `let` isn't the best choice when we're talking about semantic.

File: android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt [hunk 2]
```diff
@@ -610,8 +611,8 @@ abstract class ReactNativeActivity :
     )
   }
 
-  val devSupportManager: RNObject
-    get() = reactInstanceManager.callRecursive("getDevSupportManager")!!
+  val devSupportManager: RNObject?
+    get() = if (reactInstanceManager.isNotNull) reactInstanceManager.callRecursive("getDevSupportManager") else null
```
Comment (lukmccall) [inline android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt:615]:
```suggestion
    get() = reactInstanceManager?.callRecursive("getDevSupportManager")
```

File: android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt [hunk 3]
```diff
@@ -259,8 +259,8 @@ abstract class ReactNativeActivity :
 
   // endregion
   override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
-    if (reactInstanceManager.isNotNull && !isCrashed) {
-      if (devSupportManager.call("getDevSupportEnabled") as Boolean) {
+    this.devSupportManager?.let { devSupportManager ->
```
Comment (lukmccall) [inline android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt:262]:
```suggestion
   devSupportManager?.let { devSupportManager ->
```

**Review by lukmccall — APPROVED** [review]
🚀

File: android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt (hunk 2 above)
Comment (Kudo) [reply android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt:615]: was curious about how `RNObject.isNotNull` interop with kotlin nullable?
https://github.com/expo/expo/blob/83f8eb56baf0a28a66611f6795187e05cd09d27f/android/expoview/src/main/java/host/exp/exponent/RNObject.kt#L33-L34

`RNObject.isNotNull` indicates its internal instance to be null. however, `RNObject?` is the RNObject to be null.

Comment (barthap) [reply android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt:615]:
```suggestion
    get() = reactInstanceManager.takeIf { it.isNotNull }?.callRecursive("getDevSupportManager")
```
This should work too 😁

File: android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt [hunk 4]
```diff
@@ -259,8 +259,8 @@ abstract class ReactNativeActivity :
 
   // endregion
   override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
-    if (reactInstanceManager.isNotNull && !isCrashed) {
-      if (devSupportManager.call("getDevSupportEnabled") as Boolean) {
+   devSupportManager?.let { devSupportManager ->
```
Comment (lukmccall) [inline android/expoview/src/main/java/host/exp/exponent/experience/ReactNativeActivity.kt:262]:
```suggestion
    devSupportManager?.let { devSupportManager ->
```
sorry for that 🤦

**Comment by Kudo** [comment]
`takeIf` works like a charm! thanks @lukmccall and @barthap, you folks from swm are really my kotlin mentor (as always) 💛
