### PR TITLE
[ios] Update Podfile generation and Pods for CocoaPods 1.6

### LINKED ISSUE #4220: Cocoapods 1.6.1 throws compilation error with FBAudienceNetwork.h not found
### Environment

  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.9.1
    npmGlobalPackages:
      expo-cli: 2.17.1

Building for iOS

### Steps to Reproduce

1. Create an expo app
2. Eject
3. Use the following podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'application' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.10.6",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true
  pod 'EXAdsAdMob',
    :path => "../node_modules/expo-ads-admob/ios"
  pod 'EXSegment',
    :path => "../node_modules/expo-analytics-segment/ios"
  pod 'EXAppAuth',
    :path => "../node_modules/expo-app-auth/ios"
  pod 'EXAppLoaderProvider',
    :path => "../node_modules/expo-app-loader-provider/ios"
  pod 'EXBackgroundFetch',
    :path => "../node_modules/expo-background-fetch/ios"
  pod 'EXBarCodeScanner',
    :path => "../node_modules/expo-barcode-scanner/ios"
  pod 'EXBarCodeScannerInterface',
    :path => "../node_modules/expo-barcode-scanner-interface/ios"
  pod 'EXCamera',
    :path => "../node_modules/expo-camera/ios"
  pod 'EXCameraInterface',
    :path => "../node_modules/expo-camera-interface/ios"
  pod 'EXConstants',
    :path => "../node_modules/expo-constants/ios"
  pod 'EXConstantsInterface',
    :path => "../node_modules/expo-constants-interface/ios"
  pod 'EXContacts',
    :path => "../node_modules/expo-contacts/ios"
  pod 'EXCore',
    :path => "../node_modules/expo-core/ios"
  pod 'EXErrors',
    :path => "../node_modules/expo-errors/ios"
  pod 'EXFaceDetectorInterface',
    :path => "../node_modules/expo-face-detector-interface/ios"
  pod 'EXFileSystem',
    :path => "../node_modules/expo-file-system/ios"
  pod 'EXFileSystemInterface',
    :path => "../node_modules/expo-file-system-interface/ios"
  pod 'EXFont',
    :path => "../node_modules/expo-font/ios"
  pod 'EXFontInterface',
    :path => "../node_modules/expo-font-interface/ios"
  pod 'EXGL',
    :path => "../node_modules/expo-gl/ios"
  pod 'EXGL-CPP',
    :path => "../node_modules/expo-gl-cpp/cpp"
  pod 'EXGoogleSignIn',
    :path => "../node_modules/expo-google-sign-in/ios"
  pod 'EXImageLoaderInterface',
    :path => "../node_modules/expo-image-loader-interface/ios"
  pod 'EXLocalAuthentication',
    :path => "../node_modules/expo-local-authentication/ios"
  pod 'EXLocalization',
    :path => "../node_modules/expo-localization/ios"
  pod 'EXLocation',
    :path => "../node_modules/expo-location/ios"
  pod 'EXMediaLibrary',
    :path => "../node_modules/expo-media-library/ios"
  pod 'EXPermissions',
    :path => "../node_modules/expo-permissions/ios"
  pod 'EXPermissionsInterface',
    :path => "../node_modules/expo-permissions-interface/ios"
  pod 'EXPrint',
    :path => "../node_modules/expo-print/ios"
  pod 'EXReactNativeAdapter',
    :path => "../node_modules/expo-react-native-adapter/ios"
  pod 'EXSensors',
    :path => "../node_modules/expo-sensors/ios"
  pod 'EXSensorsInterface',
    :path => "../node_modules/expo-sensors-interface/ios"
  pod 'EXSMS',
    :path => "../node_modules/expo-sms/ios"
  pod 'EXTaskManager',
    :path => "../node_modules/expo-task-manager/ios"
  pod 'EXTaskManagerInterface',
    :path => "../node_modules/expo-task-manager-interface/ios"

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes/ios'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results[0].each do |installationResultArray|
        targetName = installationResultArray[0];
        target = installationResultArray[1]

        if targetName == 'ExpoKit'
          target.native_target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'

            # needed for GoogleMaps 2.x
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
          end
        end

        if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? targetName
          target.native_target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          end
        end
        # Can't specify this in the React podspec because we need
        # to use those podspecs for detached projects which don't reference ExponentCPP.
        if targetName.start_with?('React')
          target.native_target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          end
        end
        # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
        # RCT_ENABLE_PACKAGER_CONNECTION disabled
        next unless targetName == 'React'
        target.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
        end
    end
  end
end

```

### Expected Behavior

Compile with no errors

### Actual Behavior

XCode complains that FBAudienceNetwork.h is not found

### Reproducible Demo

Will see if I can get a reproducible demo out

### PR DESCRIPTION
**Pull request by ide**
# Why

CocoaPods 1.6 changed its Ruby API so the way we access each Pod's `native_target` data structure has changed a little; the template files are now updated to use this new way. This PR still needs to update the xdl dependency in tools-public, which is necessary to get the latest Podfile generator code in XDL.

Closes #4220 (for SDK 33)

# How

Additionally, the way header files are installed has changed and we need to use `@import` syntax for FBAudienceNetwork and GoogleSignIn. To get these to work, the compiler needs to find the frameworks in the framework search paths. We were clobbering the framework search paths with just GoogleMaps paths; this commit just lets us fall back on the default (`$(inherited)`), which includes all the CocoaPods' frameworks.

I also adjusted the indentation a little so the style of the generated Podfile has better indentation.

This PR also updates the version of CocoaPods installed by Nix to 1.6.2 and updates the iOS code to use `@import` where necessary.

# Test Plan

Tested by generating a Podfile, installing the pods successfully, updating the iOS code (coming in another commit) and verifying the app compiles and runs.

### CODE REVIEW

**Comment by ide** [comment]
@tsapeta - Could you review this please? It will be easier to review the individual commits (instead of the entire PR), since this PR contains the new Pods from `pod install` as well, which don't need to be review.

I also need to update the version of xdl we use in tools-public, but I can't because npm won't let me publish xdl for permissions reasons (npm looks broken since `npm owner ls` shows me...).

File: tools/ios-tasks.js [hunk 1]
```diff
@@ -489,19 +489,17 @@ async function generatePodfileDepsAsync(
...
-    if target.pod_name == '${versionedPodNames.React}'
-      target.native_target.build_configurations.each do |config|
+    if pod_name == '${versionedPodNames.React}'
+    target_installation_result.native_target.build_configurations.each do |config|
         config.build_settings['OTHER_CFLAGS'] = [${configValues}]
         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '${versionName}RCT_DEV=1'
-        # needed for GoogleMaps 2.x
+        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '${versionName}RCT_ENABLE_INSPECTOR=0'
+        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '${versionName}ENABLE_PACKAGER_CONNECTION=0'
```
Comment (tsapeta) [inline tools/ios-tasks.js]: What `ENABLE_PACKAGER_CONNECTION` does? Are you sure it will be versioned? It doesn't start with `RCT` 😉

**Review by tsapeta — APPROVED** [review]
Looks good to me! Thanks for doing it and also for adding `:inhibit_warnings => true` 🙂 - I was going to do that as well 😄 
Just one comment below 👇

File: tools/ios-tasks.js (hunk 1 above)
Comment (ide) [reply tools/ios-tasks.js]: `ENABLE_PACKAGER_CONNECTION` causes RN to open a web socket connection that causes lots of noisy log messages (https://github.com/expo/expo-cli/commit/24bb708bc51b555ef415a30f2baad16c9e8648e2). I seem to remember that it was for special editor integration that might not be useful in open source.

You're right that it is not versioned -- perhaps we should add it to the versioning script and update the ABI31+32 code in `ios/versioned-react-native`.

Comment (ide) [reply tools/ios-tasks.js]: I modified the versioning script so that it namespaces `ENABLE_PACKAGER_CONNECTION` (https://github.com/expo/expo/pull/4258) and also edited the old ABI 31 + 32 code to use the namespaces macros.
