### PR TITLE
[Notification] Fix `scheduleLocalNotification` in android

### LINKED ISSUE #4356: Can't schedule local notification on Android on latest expo client
## 🐛 Bug Report

Every time a try to schedule a local notification on Android using the latest version of Expo Client (the one ready for SDK 33) it throws an error `Invalid time provided`. It worked fine before updating the Expo Client.

### Environment

- Android 7.0
- Expo Client 2.11.0

### Steps to Reproduce

```js
try {
  await Notifications.scheduleLocalNotificationAsync(
    {
      title: 'Title',
      body: 'body',
    },
    {
      time: new Date(Date.now() + 10000),
    }
  );
} catch (e) {
  alert(e);
}
```

### Expected Behavior

It should schedule a location notification without throwing an error.

### Actual Behavior

It always fails regardless of the date.

### Reproducible Demo

https://snack.expo.io/@desenvolvimento.secullum/0ace06

Open this Snack via Expo Client on an Android device and it should alert the error message.

### PR DESCRIPTION
**Pull request by ninjaachibi**
# Why

Fix https://github.com/expo/expo/issues/4356 

# How

It seems that after the expo client upgrade `scheduleLocalNotifications` no longer works correctly on Android in sdk-32 since it throws an unnecessary error. Since the typing of dates changed between sdk-32 and sdk-33. In sdk-32, `suppliedTime` is of type `String`, while in sdk-33, `suppliedtime` is of type `Number`.

I updated the android source code to accommodate the `String` as well as the  `Number` types.

# Test Plan

I created a two test expo projects: one in sdk-32 and another in sdk-33 using `expo-templates`. I then tested the two using the snack code from #4356.

### CODE REVIEW

File: android/expoview/src/main/java/host/exp/exponent/notifications/NotificationHelper.java [hunk 1]
```diff
@@ -13,15 +13,19 @@
 import android.support.annotation.Nullable;
 import android.support.v4.app.NotificationCompat;
 import android.text.format.DateUtils;
+import android.util.Log;
```
Comment (esamelson) [inline android/expoview/src/main/java/host/exp/exponent/notifications/NotificationHelper.java]: remove this

**Review by esamelson — COMMENTED** [review]
thanks, this looks good! your medialibrary changes are included in this PR, so could you rebase this branch on top of master?
