### PR TITLE
[image][Android] Fix `You can't start or clear loads in RequestListener or Target callbacks`

### LINKED ISSUE #21073: [expo-image] Android: Crash on release when set placeholder props with blurhash ( works fine in dev-client))
### Summary

expo-image version: 1.0.0-beta.4

--------- beginning of crash
02-03 15:28:54.337 29094 29094 E AndroidRuntime: FATAL EXCEPTION: main
02-03 15:28:54.337 29094 29094 E AndroidRuntime: Process: com.lyrid.semcloud, PID: 29094
02-03 15:28:54.337 29094 29094 E AndroidRuntime: e1.b: Unexpected exception thrown by non-Glide code
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at e1.l.f(Unknown Source:13)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at e1.l$b.run(Unknown Source:33)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:211)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:300)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8301)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you're trying to start a fallback request when a load fails, use RequestBuilder#error(RequestBuilder). Otherwise consider posting your into() or clear() calls to the main thread using a Handler instead.
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at u1.k.h(Unknown Source:9)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at u1.k.clear(Unknown Source:3)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at u1.l.clear(Unknown Source:19)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at r1.r.a(Unknown Source:24)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at com.bumptech.glide.l.B(Unknown Source:12)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at com.bumptech.glide.l.C(Unknown Source:0)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at com.bumptech.glide.l.o(Unknown Source:3)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at m8.n.c(Unknown Source:5)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at m8.d.k(Unknown Source:71)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at m8.n.o(Unknown Source:72)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at m8.n.h(Unknown Source:2)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at u1.k.B(Unknown Source:175)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at u1.k.c(Unknown Source:92)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	at e1.l.f(Unknown Source:6)
02-03 15:28:54.337 29094 29094 E AndroidRuntime: 	... 9 more

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
      Shell: 3.5.1 - /usr/bin/fish
    Binaries:
      Node: 18.13.0 - ~/.local/share/nvm/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.local/share/nvm/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.local/share/nvm/v18.13.0/bin/npm
      Watchman: 20221225.010033.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.5.1
      expo-cli: 6.2.1
    Expo Workflow: bare

### Minimal reproducible example

>  Integrate expo image component, set placeholder holder value with blurhash
> build release.

note:  if i remove placeholder property, and rebuild. release app does not crash.

Screenshot from 2023-02-03 15-50-31

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/21073.

# How

Added a short delay between calling the `onResourceReady` and the modification of the underlying view content. More information in the code. 

# Test Plan

- bare-expo 
  - debug ✅
  - release ✅

### CODE REVIEW

File: packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt [hunk 1]
```diff
@@ -233,74 +236,82 @@ class ExpoImageViewWrapper(context: Context, appContext: AppContext) : ExpoView(
...
+  ) =
+    // The "onResourceReady" function will be triggered when the new resource is available by the Glide.
+    // According to the Glide documentation (https://bumptech.github.io/glide/doc/debugging.html#you-cant-start-or-clear-loads-in-requestlistener-or-target-callbacks),
+    // it's not advisable to clear the Glide target within the stack frame.
+    // To avoid this, a new runnable is posted to the front of the main queue, which can then clean or create targets.
+    // This ensures that the "onResourceReady" frame of the Glide code will be discarded, and the internal state can be altered once again.
+    // Normally, using "postAtFrontOfQueue" can lead to issues such as message queue starvation, ordering problems, and other unexpected consequences.
+    // However, in this case, it is safe to use as long as nothing else is added to the queue.
+    // The intention is simply to wait for the Glide code to finish before the content of the underlying views is changed during the same rendering tick.
+    mainHandler.postAtFrontOfQueue {
```
Comment (lukmccall) [inline packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt:248]: Only this was changed. The rest is here because of the different formatting which has to be applied.

**Review by tsapeta — APPROVED** [review]

**Comment by aleclarson** [comment]
I saw this same issue in Expo 54, `expo-image@3.0.7`

**Comment by Brma1048** [comment]
@aleclarson https://github.com/expo/expo/pull/39091 hopefully this will fix it
