### PR TITLE
[clipboard] fix ClipboardPasteButton asking for permission unexpectedly

### LINKED ISSUE #30617: ClipboardPasteButton is inactive on inital app start
### Minimal reproducible example

https://github.com/alehano/expo_paste_btn_bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

On the first app start, the ClipboardPasteButton is grayed out (inactive) even if the clipboard contains text. When you click on the button, it asks for permission before pasting the text.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 16, 21, 25, 26, 27, 28, 31, 32, 33, 34, 35
        Build Tools: 28.0.3, 29.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-16 | ARM EABI v7a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.22 => 51.0.22 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

### PR DESCRIPTION
**Pull request by vonovak**
# Why

closes #30617

# How

implemented [canPaste](https://developer.apple.com/documentation/uikit/uipasteconfigurationsupporting/2887578-canpaste)

# Test Plan

bare expo app

Tested on real device both with and without interplay with my mbp. There is still some asynchronicity with how the button is greyed out or not but the dialog asking for permissions is no longer shown.

Perhaps it'd make sense to support the [`target`](https://developer.apple.com/documentation/uikit/uipastecontrol/3975881-target) property to point directly to a TextInput.

# Checklist

doesn't apply here

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-clipboard/ios/ClipboardPasteButton.swift [hunk 1]
```diff
@@ -47,6 +47,24 @@ class ClipboardPasteButton: ExpoView {
...
+      provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) ||
+      provider.hasItemConformingToTypeIdentifier(UTType.url.identifier) ||
+      provider.hasItemConformingToTypeIdentifier(UTType.html.identifier) && acceptedContentTypes.contains(.html) ||
+      provider.hasItemConformingToTypeIdentifier(UTType.utf8PlainText.identifier) && !acceptedContentTypes.contains(.html)
+    }
+    if hasConformantItem {
+      return true
+    }
+    // intra-device, when copying simple stuff like images and plain text, `itemProviders` are empty
+    return itemProviders.isEmpty
```
Comment (behenate) [inline packages/expo-clipboard/ios/ClipboardPasteButton.swift:65]:
```suggestion

    // intra-device, when copying simple stuff like images and plain text, `itemProviders` are empty
    return hasConformantItem || itemProviders.isEmpty
```

**Review by behenate — APPROVED** [review]
