### PR TITLE
fix(expo-contacts): #29198 store full url & remove useless restrictio…

### LINKED ISSUE #29198: [expo-contacts] [iOS] addContactAsync - issue on urlAddresses and socialProfiles
### Minimal reproducible example

todo

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

using addContactAsync method with 

```
urlAddresses : [ 
   {
      label: '',
      url: 'https://test.com'
   }
]


and 

socialProfiles : [
   {
        label: 'social',
        url: 'social.example/profile'
   }
]

```

the result is an empty url address because only `path` of the url is stored
and no social profile because implicitly `service`, `userId` and `userName` are required
  

I will make a PR soon

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.1 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/50284_1716992916402/bin/node
      Yarn: 3.6.4 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/50284_1716992916402/bin/yarn
      npm: 9.8.1 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/50284_1716992916402/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Expected package metro@~0.80.8
Found invalid:
  metro@0.80.5
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.5
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.5
```

### PR DESCRIPTION
**Pull request by mlecoq**
…n on social profiles

# Why

to fix #29198 

# How

I am using expo-contacts to store contacts and I have remarked that urls and social profiles are partially stored or missing

# Test Plan

storing a contact with urls and social profiles

before modifications
Simulator Screenshot - iPhone 15 Pro - 2024-05-29 at 21 26 18

after modifications

Simulator Screenshot - iPhone 15 Pro - 2024-05-29 at 21 25 10

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by alanjhughes — APPROVED** [review]
Looks good @mlecoq! Thank you

File: packages/expo-contacts/ios/Decoding.swift [hunk 1]
```diff
@@ -69,7 +68,7 @@ func decodeUrlAddresses(_ input: [UrlAddress]?) -> [CNLabeledValue<NSString>]? {
   var output = [CNLabeledValue<NSString>]()
   for item in input {
     let label = decodeUrlAddressLabel(item.label)
-    if let urlString = item.url?.path {
+    if let urlString = item.url?.formatted() {
```
Comment (alanjhughes) [inline packages/expo-contacts/ios/Decoding.swift:71]: CI is failing because `formatted` is only available on iOS 16 and above. Can you add an availability check?

Comment (mlecoq) [reply packages/expo-contacts/ios/Decoding.swift:71]: I'll make it soon

Comment (mlecoq) [reply packages/expo-contacts/ios/Decoding.swift]: Finally I use `absoluteString`

File: packages/expo-contacts/ios/Decoding.swift [hunk 2]
```diff
@@ -34,13 +34,12 @@ func decodeSocialProfiles(_ input: [SocialProfile]?) -> [CNLabeledValue<CNSocial
...
-    let userId = item.userId,
-    let service = item.service {
-      let profile = CNSocialProfile(urlString: urlString.path, username: username, userIdentifier: userId, service: service)
-      output.append(CNLabeledValue(label: label, value: profile))
-    }
+    let urlString = item.url
+    let username = item.username
+    let userId = item.userId
+    let service = item.service
+    let profile = CNSocialProfile(urlString: urlString?.path(), username: username, userIdentifier: userId, service: service)
```
[the remark this answers is not in the document]
Comment (mlecoq) [reply packages/expo-contacts/ios/Decoding.swift]: changed !
