### PR TITLE
[notifications] fix  not forwarding new options to the OS when permissions were already granted

### LINKED ISSUE #20072: Repeated requests for iOS Notifications with other options are not possible
### Summary

On iOS, the permissions for Notification can be requested with a set of [options](https://developer.apple.com/documentation/usernotifications/unauthorizationoptions). The most common ones are to display alerts or play sounds, but they can also enable notifications on CarPlay displays, or enable critical alerts. Over the course of its lifetime, an app may introduce aditional capabilities, such as critical alerts or other, newly introduced iOS features and thus, must call `requestAuthorization(options:completionHandler:)` again with a new set of options. Expo Notifications supports all these [options](https://docs.expo.dev/versions/latest/sdk/notifications/#requestpermissionsasyncrequest-notificationpermissionsrequest-promisenotificationpermissionsstatus) for  `requestPermissionsAsync`.

The issue is, that after an app is newly installed on a device, the first call to `Notification.requestPermissionsAsync` will prompt the user, and set the given options. **However, subsequent calls will have no effect.**
This means, for the user to take advantage of new features, they will have to de-install and re-install the app, which is completely unacceptable.

### The Root of the Problem

The root of the problem can be found in [EXPermissionsService.m:111](https://github.com/expo/expo/blob/168ee43f71f005baa11edf98e518593443e1807a/packages/expo-modules-core/ios/Services/Permissions/EXPermissionsService.m#L111):

```objc
  BOOL isGranted = [EXPermissionsService statusForPermission:permission] == EXPermissionStatusGranted;
  permission[@"granted"] = @(isGranted);
  
  if (isGranted) {
    return onResult(permission);
  }
  
  [self askForGlobalPermissionUsingRequesterClass:requesterClass 
                                     withResolver:onResult 
                                     withRejecter:reject];
```

This means that permissions are only ever requested again, if permission has not previously been granted. This however **does not consider different options**, but only if any sort of notification permissions have been granted. This means that if previously only Alerts have been requested, a new request for Alerts and Sounds will be ignored.

### The Solution

On iOS, it is perfectly acceptable to call `requestAuthorization(options:completionHandler:)` repeatedly: 
> subsequent calls to this method (even with different options do not prompt the user again. It is best practice on iOS to call this method liberally (e.g. at every startup), and the performance hit should not be different from getting the permission status.

Also not that several tutorials suggest to check the permission status first, and then requesting it. This is — at least for iOS — not advisable.

My proposal therefore is to remove the method `askForPermissionUsingRequesterClass` entirely, and instead rename `askForGlobalPermissionUsingRequesterClass` appropriately.

I will gladly file an appropriate pull request

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Minimal reproducible example

A minimal reproducible example can be found [here](https://github.com/below/ExpoNotificationIssue)

### PR DESCRIPTION
**Pull request by vonovak**
# Why

Fixes an issue on iOS where `requestPermissionsAsync` would not forward new authorization options to the operating system when notification permissions were previously granted. This prevented users from requesting additional notification permissions (like alerts, badges, or sounds) after the initial permission grant.

closes #20086, closes #20072

# How

Changed the implementation to call `requestAuthorizationOptions` directly instead of going through the general permissions system.

A previous attempt (#20086) was rejected because expo go's permission scoping. However, I noticed that notification permissions on expo go are not scoped because some 7 years ago they were "temporarily" excluded from scoping.
So question is, do we want to handle this in a smarter way or have the exclusion be permanent?

# Test Plan

- notification tester app

<details>
<summary>Details</summary>

```
/**
 * Manual test for https://github.com/expo/expo/issues/20072
 * Verifies that requestPermissionsAsync forwards new options to the OS
 * even when notifications are already granted.
 *
 * Steps to verify the fix:
 * 1. Press "Request: alert only" → grants notifications with alert
 * 2. Press "Get permissions" → note allowsSound is false
 * 3. Press "Request: alert + sound" → should update options
 * 4. Press "Get permissions" → allowsSound should now be true
 *
 * Before the fix, step 3 would short-circuit and step 4 would still show allowsSound: false.
 */
function PermissionOptionsTest() {
  const [result, setResult] = useState<string>('');

  if (Platform.OS !== 'ios') {
    return null;
  }

  return (
    <>
      <HeadingText>Permission options test (#20072)</HeadingText>
      <Button
        title="1. Request: alert only"
        onPress={async () => {
          const res = await ExpoNotifications.requestPermissionsAsync({
            ios: { allowAlert: true, allowSound: false, allowBadge: false },
          });
          setResult(JSON.stringify(res, null, 2));
        }}
      />
      <Button
        title="2. Request: alert + sound"
        onPress={async () => {
          const res = await ExpoNotifications.requestPermissionsAsync({
            ios: { allowAlert: true, allowSound: true, allowBadge: true },
          });
          setResult(JSON.stringify(res, null, 2));
        }}
      />
      <Button
        title="Get permissions"
        onPress={async () => {
          const res = await ExpoNotifications.getPermissionsAsync();
          setResult(JSON.stringify(res, null, 2));
        }}
      />
      <Text
        selectable
        style={{
          fontFamily: Platform.select({ ios: 'Menlo', default: 'monospace' }),
          fontSize: 11,
        }}>
        {result}
      </Text>
    </>
  );
}
```

</details>

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by vonovak** [comment]
* **#43378** <a href="https://app.graphite.com/github/pr/expo/expo/43378?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/43378?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#43377** <a href="https://app.graphite.com/github/pr/expo/expo/43377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by douglowder — APPROVED** [review]
Looks fine to me. Would like to know why iOS client check is failing here when it passed the previous PR in the stack...

**Review by lukmccall — APPROVED** [review]

File: packages/expo-notifications/ios/ExpoNotifications/Permissions/PermissionsModule.swift [hunk 1]
```diff
@@ -34,13 +33,11 @@ public class PermissionsModule: Module {
...
-        .permissions?
-        .askForPermission(
-          usingRequesterClass: ExpoNotificationsPermissionsRequester.self,
-          resolve: promise.resolver,
-          reject: promise.legacyRejecter
-        )
+      // Call requestAuthorization directly to ensure new options are always
+      // forwarded to the OS, even if notifications were previously granted.
+      // iOS safely handles repeated calls to requestAuthorization(options:).
+      // expo go notifications permissions are not scoped
```
Comment (tsapeta) [inline packages/expo-notifications/ios/ExpoNotifications/Permissions/PermissionsModule.swift]:
```suggestion
      // Call `requestAuthorization` directly to ensure new options are always
      // forwarded to the OS, even if notifications were previously granted.
      // iOS safely handles repeated calls to `requestAuthorization(options:)`.
      // Expo Go notifications permissions are not scoped
```

**Review by tsapeta — APPROVED** [review]
Honestly I would remove scoping entirely, but there are of course some concerns that apps are not being sandboxed properly and that you cannot test permissions flow in multiple apps without reinstalling Expo Go. Since permissions for notifications can have options, I think we don't really have a choice here.
Not sure if we have scoping and permissions in Expo Go documented, but it might be worth adding a note how users can test granting/rejecting specific permissions.

**Comment by tsapeta** [comment]
Expo Go workflow fail is unrelated, we need to cherry-pick this https://github.com/expo/expo/commit/9d71f9c715256e5ccdc73b1c845e651d0398d0aa from `sdk-55` branch

EDIT: I opened a PR that cherrypicks that commit: https://github.com/expo/expo/pull/43390
