### PR TITLE
[iOS][permissions][notifications] Fix notifications permissions to be correctly re-initialized after app reload

### LINKED ISSUE #7222: [permissions][notifications][iOS] Default permissions aren't re-initialized after `reload`
### Environment

- iOS

### Steps to Reproduce

- Launch `ncl`
- Reload app (here we start what's going to happen)
- Navigate to `Expo APIs` ➡️ `Permissions` ➡️ click `Permissions.{USER_FACING_NOTIFICATIONS, NOTIFICATIONS}`
- Observe Promise rejection

### Expected Behavior

- No rejection after app reload

### Reason behind this rejection

https://github.com/expo/expo/blob/5cd749105dbdf4290dca18c447b059e75bf8ebf6/packages/expo-permissions/ios/EXPermissions/EXPermissions.m#L209-L216

Code presented above is executer only `once` per app lifecycle, but here we need sth that is executer every time `EXPermissions` are created.

### PR DESCRIPTION
**Pull request by bbarthec**
# TO BE MERGED AFTER #7219

# Why

Resolves #7222

# How

Re-initialize notifications permissions every time `ModuleRegistry` is set.

# Test Plan

See #7222

### CODE REVIEW

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 1]
```diff
@@ -208,10 +208,7 @@ + (UMPermissionStatus)statusForPermission:(NSDictionary *)permission
 
 - (id<UMPermissionsRequester>)getPermissionRequesterForType:(NSString *)type
 {
-  static dispatch_once_t once;
-  dispatch_once(&once, ^{
-    [self ensureRequestersFallbacksAreRegistered];
-  });
+  [self ensureRequestersFallbacksAreRegistered];
```
Comment (sjchmiela) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]: Good catch! If we change the code like you propose we will call `ensureRequestersFallbacksAreRegistered` every time a requester is… requested, which may slightly impact performance and is unneeded.

Why don't we just move the `dispatch_once_t` to an instance variable, so that the `ensure` is called once for every instance of `EXPermissions` (that's what I wanted to achieve from the beginning 😞)?

**Review by sjchmiela — APPROVED** [review]
I have only reviewed the last commit, it looks great to me! 💯 Thanks for looking into this.
