### PR TITLE
[expo-image-picker][iOS] Fix cropping rectangle displacement during cropping phase

### LINKED ISSUE #3459: [iOS] ImagePicker allowsEditing moving focus a bit on select
Starting note: I also posted this on the [forums](https://forums.expo.io/t/ios-imagepicker-allowsediting-moving-focus-a-bit-on-select/7220)
### Environment

iOS, Expo SDK 30, Client

### Steps to Reproduce
Ive noticed that the images picked using the [ImagePicker](https://docs.expo.io/versions/latest/sdk/imagepicker.html) using the allowsEditing option is actually a bit off.

If I pick the portraitmode waterfall stock image, and resize it so the top is just above the topmost rocks on the right side, and seperate the cut-in in the middle in the bottom, I notice that the resulting image actually includes some space above the top and cuts off similar space from the bottom.

Images with some annotations for illustration, I hope it makes sense:
[image 1](https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/f/f43d55151678a5045c4f8a22547eefae0210fe7e.jpg)
[image 2](https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/f/fae35d86c45ae772725befcb096d63a986e5106e.png)
### Expected Behavior
The chosen image focus on iOS is not cut off.

I think it works fine on Android, but the example is fidgy on the Android for some reason - the image disappears almost instantly after having been added.

### Reproducible Demo
https://snack.expo.io/S14MFwgDf

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves #3459

# How

I'm hiding StatusBar while ImagePickingController is visible and I'm restoring it's visibility if necessary.

# Test Plan

I've tested that the problem was present both on `in-Expo-apps` and on standalone builds on iOS11+.

`ncl` ImagePicking Screen with `enableEditing` option.

### CODE REVIEW

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 1]
```diff
@@ -27,7 +27,7 @@ @interface EXImagePicker ()
 @property (nonatomic, strong) NSDictionary *customButtons;
 @property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
 @property (nonatomic, weak) id<EXPermissionsInterface> permissionsModule;
-
+@property (nonatomic) Boolean restoreStatusBarVisibility;
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
@property (nonatomic) BOOL restoreStatusBarVisibility;
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 2]
```diff
@@ -340,11 +343,32 @@ - (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
...
     [picker dismissViewControllerAnimated:YES completion:^{
+      [self possiblyRestoreStatusBarVisibility];
       self.resolve(@{@"cancelled": @YES});
     }];
   });
 }
 
+- (void)possiblyPreserveVisibilityAndHideStatusBar:(BOOL)allowsEditingEnabled
+{
+  // launching ImagePicker with allowsEdit option enabled on iOS11+ makes cropping rectangle
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
  // As of iOS 11, launching ImagePicker with `allowsEditing` option makes cropping rectangle
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 3]
```diff
@@ -340,11 +343,32 @@ - (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
...
+  // displacement/slightly moved upwards, because of StatusBar visibility
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
  // slightly moved upwards, because of StatusBar visibility.
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 4]
```diff
@@ -340,11 +343,32 @@ - (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
...
+  // hiding StatusBar during picking process solves the displacement issue
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
  // Hiding StatusBar during picking process solves the displacement issue.
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 5]
```diff
@@ -340,11 +343,32 @@ - (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
...
+  // see https://forums.developer.apple.com/thread/98274
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
  // See https://forums.developer.apple.com/thread/98274
```

**Review by tsapeta — CHANGES_REQUESTED** [review]

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 6]
```diff
@@ -27,7 +27,7 @@ @interface EXImagePicker ()
 @property (nonatomic, strong) NSDictionary *customButtons;
 @property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
 @property (nonatomic, weak) id<EXPermissionsInterface> permissionsModule;
-
+@property (nonatomic) BOOL restoreStatusBarVisibility;
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
@property (nonatomic, assign) BOOL shouldRestoreStatusBarVisibility;
```

I know it's the default, but everywhere else we explicitly define `assign`, so let's define it here too

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 7]
```diff
@@ -340,11 +343,32 @@ - (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
 {
   dispatch_async(dispatch_get_main_queue(), ^{
     [picker dismissViewControllerAnimated:YES completion:^{
+      [self possiblyRestoreStatusBarVisibility];
       self.resolve(@{@"cancelled": @YES});
     }];
   });
 }
 
+- (void)possiblyPreserveVisibilityAndHideStatusBar:(BOOL)allowsEditingEnabled
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
- (void)maybePreserveVisibilityAndHideStatusBar:(BOOL)editingEnabled
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 8]
```diff
@@ -340,11 +343,32 @@ - (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
...
+  // slightly moved upwards, because of StatusBar visibility.
+  // Hiding StatusBar during picking process solves the displacement issue.
+  // See https://forums.developer.apple.com/thread/98274
+  if (allowsEditingEnabled && ![[UIApplication sharedApplication] isStatusBarHidden]) {
+    [[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:NO];
+    _restoreStatusBarVisibility = YES;
+  }
+}
+
+- (void)possiblyRestoreStatusBarVisibility
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
- (void)maybeRestoreStatusBarVisibility
```

File: ios/Pods/Pods.xcodeproj/project.pbxproj [hunk 9]
```diff
@@ -301,6 +301,7 @@
 		08254A00FF69652F518AA543B353DB9F /* FBSDKCoreKit-dummy.m in Sources */ = {isa = PBXBuildFile; fileRef = 73737E9D4825299E9B037F464542A9F0 /* FBSDKCoreKit-dummy.m */; };
 		0827375D7BECA24A4A5908E71DCBC5A5 /* ABI32_0_0RCTSwitch.h in Headers */ = {isa = PBXBuildFile; fileRef = 4480D605308191B1DA881CA79C1B9E98 /* ABI32_0_0RCTSwitch.h */; settings = {ATTRIBUTES = (Project, ); }; };
 		082BC407EDDB96A8F3CFEF324EED6AF9 /* ABI30_0_0RCTExceptionsManager.m in Sources */ = {isa = PBXBuildFile; fileRef = 55DF722285C7B0C6B22427F2319B3BBA /* ABI30_0_0RCTExceptionsManager.m */; settings = {COMPILER_FLAGS = "-w -Xanalyzer -analyzer-disable-all-checks"; }; };
+		08334A0B5755A4FD45B8DD27BDCE1932 /* UIKit.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 5B8D178A8B6B35C8DD54C9C6403F0968 /* UIKit.framework */; };
```
Comment (sjchmiela) [inline ios/Pods/Pods.xcodeproj/project.pbxproj]: Interesting you've got changes in `Pods.xcodeproj` 🤔

**Review by sjchmiela — APPROVED** [review]
Just some nitpicking, thanks! 💅

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 6 above)
Comment (bbarthec) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I will change it, but it's make no sense IMHO 😅

**Comment by daniel** [comment]
I can still reproduce #3459 on my iPhone X. See my snack here:
https://snack.expo.io/@daniel-overstellar/image-picker-cropping-bug

The offset seems to be getting even bigger if I zoom in on the image after selecting it.

The status bar doesn't seem to make a difference to me. I get the same problem if I hide it by adding this inside the View.

`<StatusBar hidden={true} />`

Should I create a new issue or can #3459 be reopened?

**Comment by daniel** [comment]
I noticed this problem after upgrading my app from SDK 37 to SDK 39.0.3. The problem seems to have appeared again after SDK 37.

**Comment by daniel** [comment]
Update: I tested it on an iPhone XR and there was no problem there. Maybe it's related to screen size.

**Comment by bbarthec** [comment]
@daniel, please create a new issue and describe the problem there.
Additionally, refer to this PR, to the #3459 and add in the issue description this observation about the devices that are suffering from the misbehaviour 🙂

**Comment by daniel** [comment]
The problem seems to have been related to iOS 14, but seems to have been fixed with iOS 14.2, I can't reproduce it there.
