### PR TITLE
Fix ios crop box not dragging issue

### LINKED ISSUE #10820: [expo-image-picker][ios] Can't drag the picture around the crop area (bare react-native app)
### Summary of Issue 

1. Call `launchCameraAsync` with `allowsEditing: true`.
2. Take a picture.
3. Try to drag the picture on the crop area.
4. It doesn't change

Works well on Android.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 79.11 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.8.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.14.0 => 16.14.0
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Reproducible Demo

https://github.com/aprilmintacpineda/repro-expo-image-picker-10820

This only happens for `launchCameraAsync` but not for `launchImageLibraryAsync`.

Sorry, can't upload GIF, file size way too big for github
https://streamable.com/4yfkf6

### PR DESCRIPTION
**Pull request by ebrahimhassan121**
# Why
Should fix https://github.com/expo/expo/issues/10820

# How
The solution has been mentioned here https://stackoverflow.com/a/53440254/10811237

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-image-picker/ios/UIImagePickerControllerExtentsion.swift [hunk 1]
```diff
@@ -0,0 +1,63 @@
+//
+//  UIImagePickerControllerExtentsion.swift
+//  ExpoImagePicker
+//
+//  Created by ibrahim.hassan on 5/16/23.
+//
```
Comment (lukmccall) [inline packages/expo-image-picker/ios/UIImagePickerControllerExtentsion.swift:6]:
```suggestion
// Copyright 2016-present 650 Industries. All rights reserved.
```

**Review by lukmccall — CHANGES_REQUESTED** [review]
Thanks for your contribution 🏅
Please, fix problems connected with swift lint and I will merge your pr.

**Review by lukmccall — APPROVED** [review]

File: packages/expo-image-picker/ios/UIImagePickerControllerExtentsion.swift [hunk 2]
```diff
@@ -0,0 +1,58 @@
+// Copyright 2016-present 650 Industries. All rights reserved.
+
+extension UIImagePickerController {
+  func fixCannotMoveEditingBox() {
+    if let cropView = cropView,
+      let scrollView = scrollView,
+      scrollView.contentOffset.y == 0
+    {
+      let top = cropView.frame.minY + self.view.safeAreaInsets.top
```
Comment (TheNerdGuyLulu) [inline packages/expo-image-picker/ios/UIImagePickerControllerExtentsion.swift:9]: Hi @ebrahimhassan121
adding the safeAreaInsets.top prevents from reaching the bottom, and overflows the top
79758501-49ED-4661-A575-EBF0DC0A29AD_1_101_o
18FCFD88-330C-4006-BEB6-36A287F2A96E_1_101_o
