### PR TITLE
[templates] workaround expo-notifications broken when there's firebase sdk

### LINKED ISSUE #15990: [notifications][iOS] getExpoPushTokenAsync doesn't resolve nor reject
### Summary

After upgrade from Expo@43 to Expo@44 `getExpoPushTokenAsync` doesn't resolve nor reject on iOS.
After long debugging it is due to `@react-native-firebase/auth` package - uninstalling this package makes `getExpoPushTokenAsync` to return ExpoPushToken

I'm not sure if it should be reported to `@react-native-firebase/auth` issues or here - but I think it is regression around Expo44 upgrade, because on Expo43 before going thru' upgrade process everything was working okay (followed upgrade steps from https://blog.expo.dev/expo-sdk-44-4c4b8306584a under Bare workflow section)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

_No response_

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v14.17.3/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      expo-notifications: ~0.14.0
      expo-device: ~4.1.0
      expo-firebase-analytics: ~6.0.0
      @react-native-firebase/app: 14.2.1
      @react-native-firebase/auth: 14.2.1
    npmGlobalPackages:
      eas-cli: 0.41.0
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

1. Create bare Expo project
2. Install `expo-notifications` (and go thru' its configuration steps like generating Push Notification Key credential etc - https://github.com/expo/expo/tree/master/packages/expo-notifications#installation-in-bare-react-native-projects)
3. Install `@react-native-firebase/app` (and go thru' its configuration steps - https://rnfirebase.io/)
4. Install `@react-native-firebase/auth` (and go thru' its configuration steps - https://rnfirebase.io/auth/usage)
5. Install `expo-device`
6. Update main App.jsx (or App.tsx) file with code from https://docs.expo.dev/push-notifications/overview/#usage BUT pass `experienceId` to `getExpoPushTokenAsync` method and replace `Constants.isDevice` with `Device.isDevice` (from `expo-device`)
7. `cd ios && pod install`
8. Run `expo run:ios --device --no-build-cache`
9. `getExpoPushTokenAsync` doesn't resolve nor reject
10. Uninstall `@react-native-firebase/auth`
11. `cd ios && rm -rf Pods && pod install`
12. Run `expo run:ios --device --no-build-cache`
13. `getExpoPushTokenAsync` resolves with ExpoPushToken

### PR DESCRIPTION
**Pull request by Kudo**
# Why

from ios firebase sdk `[FIRApp configure];`, this call will do the swizzling internally. they use it to intercept `application:didRegisterForRemoteNotificationsWithDeviceToken:` . even though their implementation will [proxy the handler back to original AppDelegate](https://github.com/google/GoogleUtilities/blob/f4abe56ce62a779e64b525eb133c8fc2a84bbc1f/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m#L289-L311). unfortunately, our AppDelegate doesn't have `application:didRegisterForRemoteNotificationsWithDeviceToken:` , so the swizzling lib will not proxy the handler back. however, we did handle the callback in the AppDelegate base class - the [`ExpoAppDelegate`](https://github.com/expo/expo/blob/13a016812ca0569feb2ec805663d4b8a047402ec/packages/expo-modules-core/ios/AppDelegates/ExpoAppDelegate.swift#L102-L140). the problem is basically from firebase where their swizzling lib doesn't lookup AppDelegate's base class.

fix #15990
close ENG-4757

# How

workaround to add explicit remote notification delegates to AppDelegate

# Test Plan

1. expo init project # select blank
2. expo install expo-notifications @react-native-firebase/app
3. add `expo-notifications` and `@react-native-firebase/app` to the plugins in app.json
4. expo run:ios
5. check whether `token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log("token", token);` returns

# Checklist

- n/a Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.mm [hunk 1]
```diff
@@ -83,6 +83,24 @@ - (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull N
   return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler] || result;
 }
 
+// Leaves remote notification delegates for firebase ios sdk swizzling
```
Comment (tsapeta) [inline templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.mm:86]: We need to think more about the comment here — for sure it's the case not only for Firebase, so more generic comment would fit better imho
cc @brentvatne

Comment (brentvatne) [inline templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.mm:86]:
```suggestion
// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
```

maybe this?

Comment (Kudo) [reply templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.mm]: makes sense to me. i've updated the comments accordingly.

**Review by tsapeta — APPROVED** [review]

File: templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.mm [hunk 2]
```diff
@@ -83,6 +83,24 @@ - (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull N
...
+// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
+- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
+{
+  return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
+}
+
+// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
+- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
+{
+  return [super application:application didFailToRegisterForRemoteNotificationsWithError:error];
```
Comment (zakharchenkoAndrii) [inline templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.mm:95]: Why do we `return`  here? The function is `void`... it is confusing a bit
