### PR TITLE
[device][Android] Fix Device.getDeviceTypeAsync() returns TABLET on certain Android devices

### LINKED ISSUE #18127: Device.getDeviceTypeAsync() returns TABLET on certain Android devices
### Summary

During my tests (using SDK45 and EAS) I detected that certain Android devices return that they are tablets when they are not, here are some of the devices:

- T-Mobile REVVLRY+
- Moto G7 Plus

Using `react-native-device-info` directly works correctly, so I compared the codes between both implementations, and they look quite similar, except for the handling it does with the `DisplayMetrics` (I don't know if that is the reason for the different behavior),

I leave both codes to see if it is useful:

https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceTypeResolver.java#L71

https://github.com/expo/expo/blob/sdk-45/packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt#L174

and I also leave a reference to a previously reported incident:

https://github.com/expo/expo/issues/11409

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.4 environment info:
  System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /private/var/folders/qv/x2xgwlnj1qb2wjnthh5bp_600000gn/T/xfs-9977dec8/node
    Yarn: 3.2.0 - /private/var/folders/qv/x2xgwlnj1qb2wjnthh5bp_600000gn/T/xfs-9977dec8/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  npmGlobalPackages:
    eas-cli: 0.54.1
    expo-cli: 5.4.12
  Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/18127.
On some devices type of the device was incorrectly shown as tablet on Android.

# How

Added checking the type of the device based on the smallest screen width quantifier ([docs](https://developer.android.com/guide/topics/resources/providing-resources#SmallestScreenWidthQualifier)). If this fails the old method is used, but it now uses getRealMetrics instead of getMetrics in order to get the correct screen proportions and size. Also updated the deprecated functions.

# Test Plan

Tested in different android API versions and virtual devices (tablet/phone) to check if the type of the device returned is correct.

### CODE REVIEW

File: packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt [hunk 1]
```diff
@@ -146,18 +142,51 @@ class DeviceModule : Module() {
...
+        deviceTypeFromResourceConfiguration
+      } else {
+        getDeviceTypeFromPhysicalSize(context)
+      }
+    }
+
+    // Device type based on the smallest screen width quantifier
+    // https://developer.android.com/guide/topics/resources/providing-resources#SmallestScreenWidthQualifier
+    private fun getDeviceTypeFromResourceConfiguration(context: Context): DeviceType {
+      val smallestScreenWidthDp: Int = context.resources.configuration.smallestScreenWidthDp
```
Comment (lukmccall) [inline packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt:156]:
```suggestion
      val smallestScreenWidthDp = context.resources.configuration.smallestScreenWidthDp
```

File: packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt [hunk 2]
```diff
@@ -146,18 +142,51 @@ class DeviceModule : Module() {
...
+
+      if (smallestScreenWidthDp == Configuration.SMALLEST_SCREEN_WIDTH_DP_UNDEFINED) {
+        return DeviceType.UNKNOWN
+      }
+      return if (smallestScreenWidthDp >= 600) DeviceType.TABLET else DeviceType.PHONE
```
Comment (lukmccall) [inline packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt:161]:
```suggestion
      return if (smallestScreenWidthDp >= 600) {
        DeviceType.TABLET 
      } else {
        DeviceType.PHONE
      }
```

File: packages/expo-device/CHANGELOG.md [hunk 3]
```diff
@@ -7,7 +7,7 @@
 ### 🎉 New features
 
 ### 🐛 Bug fixes
-
+- Fixed Device.getDeviceTypeAsync() returning TABLET on some devices. ([#21325](https://github.com/expo/expo/pull/21325) by [@behenate](https://github.com/behenate))
```
Comment (lukmccall) [inline packages/expo-device/CHANGELOG.md:10]:
```suggestion

- Fixed Device.getDeviceTypeAsync() returning TABLET on some devices. ([#21325](https://github.com/expo/expo/pull/21325) by [@behenate](https://github.com/behenate))

```

**Review by lukmccall — APPROVED** [review]

File: packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt [hunk 4]
```diff
@@ -146,18 +142,55 @@ class DeviceModule : Module() {
...
+      val smallestScreenWidthDp = context.resources.configuration.smallestScreenWidthDp
+
+      if (smallestScreenWidthDp == Configuration.SMALLEST_SCREEN_WIDTH_DP_UNDEFINED) {
+        return DeviceType.UNKNOWN
+      }
+      return if (smallestScreenWidthDp >= 600) {
+        DeviceType.TABLET 
+      } else {
+        DeviceType.PHONE
+      }
```
Comment (lukmccall) [inline packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt:165]:
```suggestion
      return if (smallestScreenWidthDp == Configuration.SMALLEST_SCREEN_WIDTH_DP_UNDEFINED) {
        DeviceType.UNKNOWN
      } else if (smallestScreenWidthDp >= 600) {
        DeviceType.TABLET 
      } else {
        DeviceType.PHONE
      }
```
