### PR TITLE
[widgets][plugin] Make incremental prebuilds work

### LINKED ISSUE #45090: [expo-widgets] Each time the prebuild command is executed, a target and its references are generated, which must be manually deleted.
### Current Behavior
Each time `npx expo prebuild -p ios` is executed, it generates an ExpoWidgetsTarget file reference, and a new Target file will appear in the Xcode project directory.

Image

Image

### Except Behavior
Before creating a new file or reference, it is necessary to check whether the file or reference already exists.

### Minimal reproducible example

https://github.com/likeSo/expo-widgets-bug-repro

### Steps to reproduce

- Create an new Expo project, setup `expo-widgets` things
- Run `npx expo prebuild -p ios`

Alternatively, you can clone my repository and then run `npx expo prebuild -p ios` multiple times.
Each time you run this command, it generates a target and additional file references.

### Environment

```text
expo-env-info 2.0.12 environment info:
    System:
      OS: macOS 26.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.20.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 11.6.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.4, iOS 26.4, macOS 26.4, tvOS 26.4, visionOS 26.4, watchOS 26.4
    IDEs:
      Android Studio: 2025.3 AI-253.31033.145.2533.15113396
      Xcode: 26.4/17E192 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^55.0 => 55.0.15 
      expo-router: ~55.0.12 => 55.0.12 
      react: 19.2.0 => 19.2.0 
      react-dom: 19.2.0 => 19.2.0 
      react-native: 0.83.4 => 0.83.4 
      react-native-web: ~0.21.0 => 0.21.2 
    npmGlobalPackages:
      eas-cli: 16.20.4
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✖ Check Expo config (app.json/ app.config.js) schema
Errors validating fields in /Users/aron/Desktop/live-activities/app.json:
 should NOT have additional property 'newArchEnabled'.
 Field: android - should NOT have additional property 'edgeToEdgeEnabled'.
Advice:
Resolve schema errors in your app config. Learn more: https://docs.expo.dev/workflow/configuration/

✖ Check that no duplicate dependencies are installed
Your project contains duplicate native module dependencies, which should be de-duplicated.
Native builds may only contain one version of any given native module, and having multiple versions of a single Native module installed may lead to unexpected build errors.
Found duplicates for expo-constants:
  ├─ expo-constants@55.0.14 (at: node_modules/expo-constants)
  ├─ expo-constants@55.0.14 (at: node_modules/expo/node_modules/expo-constants)
  └─ expo-constants@55.0.14 (at: node_modules/expo-asset/node_modules/expo-constants)
Found duplicates for expo-font:
  ├─ expo-font@55.0.6 (at: node_modules/expo-font)
  └─ expo-font@55.0.6 (at: node_modules/expo/node_modules/expo-font)
Advice:
Your node_modules folder may be corrupted. Multiple copies of the same version exist for: expo-constants, expo-font.
- Try deleting your node_modules folders and reinstall your dependencies after.
- If this error persists, delete your node_modules as well as your lockfile and reinstall.
Resolve your dependency issues and deduplicate your dependencies. Learn more: https://expo.fyi/resolving-dependency-issues

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, splash, ios, android, plugins. 


✖ Check that packages match versions required by installed Expo SDK

🔧 Patch version mismatches
package                expected  found    
expo                   ~55.0.17  55.0.15  
expo-constants         ~55.0.15  55.0.14  
expo-linking           ~55.0.14  55.0.13  
expo-router            ~55.0.13  55.0.12  
expo-splash-screen     ~55.0.19  55.0.18  
react-native           0.83.6    0.83.4   
react-native-worklets  0.7.4     0.7.2    

Changelogs:
- expo-constants → https://github.com/expo/expo/blob/sdk-55/packages/expo-constants/CHANGELOG.md
- expo-linking → https://github.com/expo/expo/blob/sdk-55/packages/expo-linking/CHANGELOG.md
- expo-router → https://github.com/expo/expo/blob/sdk-55/packages/expo-router/CHANGELOG.md
- expo-splash-screen → https://github.com/expo/expo/blob/sdk-55/packages/expo-splash-screen/CHANGELOG.md

7 packages out of date.
Advice:
Use 'npx expo install --check' to review and upgrade your dependencies.
To ignore specific packages, add them to "expo.install.exclude" in package.json. Learn more: https://expo.fyi/dependency-validation
```

### PR DESCRIPTION
**Pull request by jakex7**
# Why

Widgets always requires clean prebuild.
Fixes #45090

# How

Add many ifs.

# Test Plan

Run prebuild without `--clean` and check changes.

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-widgets/plugin/src/withInfoPlistValues.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import plist from '@expo/plist';
+import { ConfigPlugin, withDangerousMod } from 'expo/config-plugins';
+import * as fs from 'fs';
+import * as path from 'path';
+
+const withInfoPlistValues: ConfigPlugin<Record<string, any>> = (config, values) =>
```
Comment (lukmccall) [inline packages/expo-widgets/plugin/src/withInfoPlistValues.ts]: remove it

**Review by lukmccall — APPROVED** [review]
