### PR TITLE
fix: [iOS][ExpoWebBrowser] don't crash with invalid url 

### LINKED ISSUE #22986: expo-web-browser doesn't throw error when attempting to open an invalid URL, instead causes crash
### Minimal reproducible example

https://snack.expo.dev/gsmhKTR6W

### Summary

When using expo-web-browser's `openBrowserAsync`, an improper URL passed to the browser may cause a crash instead of properly handling and throwing an error. In the example, a link with `%5B` in front of `https://` causes a crash.

Expected result would be to receive an error stating that the link was invalid or could not be opened.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.7 => 0.18.12 
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by hirbod**
# Why

An exception is thrown by the SFSafariViewController class when it receives a URL with a scheme other than HTTP or HTTPS which leads into a crash.

Unlike the Android implementation, which throws (as expected) an error of type `NoMatchingActivityException`. 

Fixes #22986 

# How

I've added a simple check to ensure that URLs start with http or https. While this is not 100% bulletproof, it should prevent crashes caused by mistakes with malformed URLs like `%5Bhttps://lemmy.ml/c/instance` or any other malicious input, which SFSafariViewController can't handle anyway. This is more aligned with the Android implementation.

# Test Plan

Simulator and real device, running iOS 16.4 and 16.5, testing a bunch of different strings and URLs

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-web-browser/ios/WebBrowserModule.swift [hunk 1]
```diff
@@ -1,24 +1,40 @@
...
-import ExpoModulesCore
 import AuthenticationServices
+import ExpoModulesCore
+import SafariServices
 
 final public class WebBrowserModule: Module {
   private var currentWebBrowserSession: WebBrowserSession?
   private var currentAuthSession: WebAuthSession?
 
+  private func isValidUrl(urlString: String?) -> Bool {
```
Comment (alanjhughes) [inline packages/expo-web-browser/ios/WebBrowserModule.swift:11]:
```suggestion
  private func isValid(url: URL) -> Bool {
    return url.scheme == "http" || url.scheme == "https"
  }
```
We can just take the URL directly here and skip the guard

**Review by alanjhughes — CHANGES_REQUESTED** [review]
Looks good. Just one minor change

File: packages/expo-web-browser/ios/WebBrowserModule.swift (hunk 1 above)
Comment (hirbod) [reply packages/expo-web-browser/ios/WebBrowserModule.swift]: Makes sense. Done

**Review by alanjhughes — APPROVED** [review]
👍

File: packages/expo-web-browser/ios/WebBrowserModule.swift [hunk 2]
```diff
@@ -8,17 +8,27 @@ final public class WebBrowserModule: Module {
   private var currentWebBrowserSession: WebBrowserSession?
   private var currentAuthSession: WebAuthSession?
 
+  private func isValid(url: URL) -> Bool {
+    return url.scheme == "http" || url.scheme == "https"
+  }
```
Comment (tsapeta) [inline packages/expo-web-browser/ios/WebBrowserModule.swift:13]: Next time, put functions like this outside of the class – it is not depending on the class instance in any way 😉

Comment (hirbod) [reply packages/expo-web-browser/ios/WebBrowserModule.swift:13]: 🥶

Should I create a WebBrowserUtils.swift and move it into its own file?

Comment (hirbod) [reply packages/expo-web-browser/ios/WebBrowserModule.swift:13]: I mean the check is even so simple I could just inline it

Comment (tsapeta) [reply packages/expo-web-browser/ios/WebBrowserModule.swift:13]: Inlining would be fine too, but it can be in the same file as it doesn't need to be accessible from other files 😉 In utils files you usually want them to be exposed (`public` or `internal`).

Comment (hirbod) [reply packages/expo-web-browser/ios/WebBrowserModule.swift:13]: Make sense.
