### PR TITLE
[expo-av] Fix fullscreen events not emitted on iOS

### LINKED ISSUE #8393: Expo video onFullScreenUpdate is not triggered as expected using the native controls in ios
### Environment

Expo CLI 3.20.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\Users\yahya\AppData\Local\watchman\windows\bin\watchman.EXE
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
### Steps to Reproduce

```
expo init
expo install expo-av
```
Adding the video component and use the native controls to open and close the full screen in IOS device.
```
<Video
          ref={e=>this.video = e}
          source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
          rate={1.0}
          volume={1.0}
          isMuted={false}
          resizeMode="cover"
          useNativeControls
          style={{ width: 300, height: 300 }}
          onFullscreenUpdate={(e)=>console.log(e.fullscreenUpdate)}
        />
```

### Expected Behavior

onFullScreenUpdate should be triggered when opening the full screen 2 times and on closing the full screen two times using the native control button.

### Actual Behavior
IOS only
The onFullScreenUpdate is triggered 4 times after closing the full screen and it is not triggered on opening the full screen.

### Reproducible Demo
https://snack.expo.io/@yahiabadr/f3e4cd

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Fixes #8393. When using the native full-screen controls on iOS, the full-screen events are not (always) emitted.

# How

As of iOS 12, full-screen detection can be achieved using the `AVPlayerViewControllerDelegate` delegate.

- Added `AVPlayerViewControllerDelegate` methods for detecting the full-screen mode change
- Kept legacy view-bounds detection code as a fallback for iOS 11 or earlier
- Extended NCL to log full-screen events to console

# Test Plan

- Verified that it worked locally
- Verified that it does not emit events twice when using `presentFullScreen..`

fullscreen-events

### CODE REVIEW

File: apps/native-component-list/src/screens/AV/VideoPlayer.tsx [hunk 1]
```diff
@@ -52,7 +52,9 @@ export default class VideoPlayer extends React.Component<
 
   _handleVideoMount = (ref: Video) => (this._video = ref);
 
-  _updateStateToStatus = (status: any) => this.setState(status);
+  _handlePlaybackStatusUpdate = (status: any) => this.setState(status);
```
Comment (bbarthec) [inline apps/native-component-list/src/screens/AV/VideoPlayer.tsx:55]:
```suggestion
  _handlePlaybackStatusUpdate = (status: SomeMeaningfulType) => this.setState(status);
```
Maybe it would help understanding what state parameters are actually changing? 🤔

**Review by bbarthec — APPROVED** [review]
LGTM 👍 Definitely it's better to base on some actual callbacks than some by-hand-calculation when it comes to fullscreen detection 😉

File: apps/native-component-list/src/screens/AV/VideoPlayer.tsx (hunk 1 above)
Comment (IjzerenHein) [reply apps/native-component-list/src/screens/AV/VideoPlayer.tsx:55]: Yeah I agree. I'll have at improving the example in a separate PR 👍

Comment (IjzerenHein) [reply apps/native-component-list/src/screens/AV/VideoPlayer.tsx:55]: NLC update PR #9335
