### PR TITLE
[cli] fix getting UDID for network connected iOS devices

### LINKED ISSUE #19191: When using "npx expo run:ios -d" with a plugged-in device which is also available on Wifi; shows up twice and has an error
### Summary

Hi,

I setup my device in Devices & Simulators in Xcode to be available over the network

Now, when running `npx expo run:ios -d` two scenarii:
1) if the device is plugged in, it shows twice the same device : and one of them I guess the wireless one gives an error `Cannot read properties of undefined (reading 'udid')`
2) if the device is not plugged in, I can successfully see the device and it also builds correctly but nothing gets installed on the device

The solutions for now is either disable the "Connect via network" or keep using the first row when seeing duplicates for the same device!

Thanks again for all this work Expo puts in the community, what you are accomplishing is game-changing for sure
  

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2022.08.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Minimal reproducible example

Setup an iOS 16 device for development
Enable "Connect via network"
Plug your iPhone to your computer through USB
Run `npx expo run:ios -d` and see the duplicate row

### PR DESCRIPTION
**Pull request by Simek**
# Why

Fixes ENG-6617
Fixes ENG-6650
Fixes #19191
Superseeds #20188

# How

This PR ensures that network connect iOS devices have the correct UDID set, while fetching them via `UsbmuxdClient`.

# Test Plan

The fix has been tested locally with a fresh app. I was able to select the network device and run the app just like it through the USB cord.

I have also added a simple test for the promt list and ensured that all test are still passing.

# Preview

Screenshot 2022-12-01 at 12 38 02

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/run/ios/appleDevice/client/UsbmuxdClient.ts [hunk 1]
```diff
@@ -18,21 +18,26 @@ const debug = Debug('expo:apple-device:client:usbmuxd');
...
-  LocationID: number;
+  LocationID?: number;
   /** 4776 */
-  ProductID: number;
+  ProductID?: number;
   /** '00008101-001964A22629003A' */
   SerialNumber: string;
   /** '00008101-001964A22629003A' */
-  UDID: string;
+  UDID?: string;
```
Comment (EvanBacon) [inline packages/@expo/cli/src/run/ios/appleDevice/client/UsbmuxdClient.ts:33]: Should document when the ID is not defined since we basically use it for everything related to identifying the device.

**Review by EvanBacon — APPROVED** [review]
Would be neat if there were more tests, otherwise looks fine.
