### PR TITLE
[expo-image][android] fix resuming animation

### LINKED ISSUE #37327: [expo-image] startAnimating on android reset the GIF animation.
### Minimal reproducible example

https://snack.expo.dev/@otavio_stasiak/expo-image-test

### Steps to reproduce

I was creating a feature to play and pause my GIFs, here a simple example of implementation:

```
import React, {useRef, useState} from 'react';
import {  SafeAreaView, StyleSheet, TouchableOpacity } from 'react-native';
import { Image } from 'expo-image';

export default function App() {
  const [isPlaying, setIsPlaying] = useState(false);
  const expoImageRef = useRef(null);

const handleGifPlayback = async () => {
		if (isPlaying) {
			setIsPlaying(false);
			await expoImageRef.current?.stopAnimating();
			return;
		}
		setIsPlaying(true);
		await expoImageRef.current?.startAnimating();
	};

  return (
    <SafeAreaView style={styles.container}>
    <TouchableOpacity onPress={handleGifPlayback}>
          <Image ref={expoImageRef} style={{width:300, height: 300}} source={{uri: "https://64.media.tumblr.com/d3cf539271c9e64ea819fcc2c9d8fd8f/5406446a1fe480d2-bc/s540x810/26c9183eeba4a7cc829deb7c1eb7c9042321a8f4.gif"}} autoplay={false} />
    </TouchableOpacity>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  }
});


```
On iOS, it works as expected — after calling .stopAnimating, if I click and run .startAnimating, the GIF resumes from the point where it was paused.

However, on Android, it doesn't work the same way. When I run .startAnimating after .stopAnimating, the GIF resets and starts from the beginning (frame 0) instead of resuming like it does on iOS.

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/otavio.stasiak/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
    IDEs:
      Android Studio: 2024.3 AI-243.25659.59.2432.13423653
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^12.0.11 => 12.0.11 
      expo: 52 => 52.0.39 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.77.2 => 0.77.2 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✖ Check for issues with Metro config
It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more: https://docs.expo.dev/guides/customizing-metro/
Advice:
Update your metro.config.js to extend @expo/metro-config.

✖ Check that native modules use compatible support package versions for installed Expo SDK
Expected package metro@^0.81.0
Found invalid:
  metro@0.80.6
  (for more info, run: npm why metro)
Expected package metro-resolver@^0.81.0
Found invalid:
  metro-resolver@0.80.6
  (for more info, run: npm why metro-resolver)
Expected package metro-config@^0.81.0
Found invalid:
  metro-config@0.80.6
  metro-config@0.80.6
  (for more info, run: npm why metro-config)
Advice:
Upgrade dependencies that are using the invalid package versions.

✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  Untested on New Architecture: @nozbe/watermelondb, react-native-background-timer, react-native-file-viewer, react-native-navigation-bar-color, react-native-notifications, react-native-restart
  Unmaintained: @react-native-cookies/cookies, react-native-background-timer, react-native-easy-grid, react-native-easy-toast, react-native-file-viewer, react-native-image-progress, react-native-navigation-bar-color, react-native-platform-touchable, react-native-prompt-android, react-native-skeleton-placeholder, react-native-slowlog
  No metadata available: @codler/react-native-keyboard-aware-scroll-view, @discord/bottom-sheet, @rocket.chat/message-parser, @rocket.chat/sdk, @rocket.chat/ui-kit, bytebuffer, color2k, dequal, ejson, hoist-non-react-statics, js-base64, js-sha256, jsrsasign, lint-staged, lodash, moment, pretty-bytes, prop-types, react-native-config-reader, react-native-katex, react-native-math-view, react-native-mime-types, react-native-simple-crypto, react-native-vector-icons, reanimated-tab-view, redux-immutable-state-invariant, redux-saga, remove-markdown, rn-root-view, transliteration, typed-redux-saga, ua-parser-js, uri-js, url-parse, use-deep-compare-effect, xregexp
Advice:
Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

✖ Check that packages match versions required by installed Expo SDK
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.22.3 - expected version: 1.23.1
  @react-native-community/datetimepicker@8.3.0 - expected version: 8.2.0
  @react-native-community/netinfo@11.3.1 - expected version: 11.4.1
  @react-native-community/slider@4.5.0 - expected version: 4.5.5
  @react-native-masked-view/masked-view@0.3.1 - expected version: 0.3.2
  @react-native-picker/picker@2.11.0 - expected version: 2.9.0
  expo@52.0.39 - expected version: ~52.0.46
  expo-apple-authentication@7.0.1 - expected version: ~7.1.3
  expo-document-picker@13.0.1 - expected version: ~13.0.3
  expo-file-system@18.0.1 - expected version: ~18.0.12
  expo-image@2.0.6 - expected version: ~2.0.7
  react-native@0.77.2 - expected version: 0.76.9
  react-native-gesture-handler@2.24.0 - expected version: ~2.20.2
  react-native-reanimated@3.17.1 - expected version: ~3.16.1
  react-native-safe-area-context@5.3.0 - expected version: 4.12.0
  react-native-screens@4.9.2 - expected version: ~4.4.0
  react-native-svg@15.11.2 - expected version: 15.8.0
  react-native-webview@11.26.1 - expected version: 13.12.5
  @types/react@18.2.73 - expected version: ~18.3.12
  react-dom@18.2.0 - expected version: 18.3.1
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice:
Use 'npx expo install --check' to review and upgrade your dependencies.

4 checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by Wenszel**
# Why

fixes [37327](https://github.com/expo/expo/issues/37327)

# How

The start() method in Animatable restarts animation, so I added checking if the resource can be cast to GifDrawable, because it has resume and pause methods.

# Test Plan

Added "Animation resuming" screen.  

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: apps/native-component-list/src/screens/Image/ImageAnimationResuming.tsx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+  const handleGifPlayback = async () => {
+    if (isPlaying) {
+      setIsPlaying(false);
+      await expoImageRef.current?.stopAnimating();
+      return;
+    }
+    setIsPlaying(true);
+    await expoImageRef.current?.startAnimating();
+  };
```
Comment (lukmccall) [inline apps/native-component-list/src/screens/Image/ImageAnimationResuming.tsx]:
```suggestion
  const handleGifPlayback = React.useCallback(async () => {
    if (isPlaying) {
      setIsPlaying(false);
      await expoImageRef.current?.stopAnimating();
      return;
    }
    setIsPlaying(true);
    await expoImageRef.current?.startAnimating();
  }, [isPlaying]);
```

File: packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt [hunk 2]
```diff
@@ -170,13 +171,32 @@ class ExpoImageViewWrapper(context: Context, appContext: AppContext) : ExpoView(
 
   fun setIsAnimating(setAnimating: Boolean) {
     val resource = activeView.drawable
+    /* Animatable animations always start from the beginning when resumed.
+    So we check first if the resource is a GifDrawable, because it can continue
+    from where it was paused. */
```
Comment (lukmccall) [inline packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt]:
```suggestion
    // Animatable animations always start from the beginning when resumed.
    // So we check first if the resource is a GifDrawable, because it can continue
    // from where it was paused.
```

File: packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt [hunk 3]
```diff
@@ -170,13 +171,32 @@ class ExpoImageViewWrapper(context: Context, appContext: AppContext) : ExpoView(
...
+    when (resource) {
+      is GifDrawable -> toggleGifDrawableAnimation(resource, setAnimating)
+      is Animatable -> toggleAnimatableAnimation(resource, setAnimating)
+    }
+  }
 
-    if (resource is Animatable) {
-      if (setAnimating) {
-        resource.start()
+  private fun toggleGifDrawableAnimation(resource: GifDrawable, setAnimating: Boolean) {
```
Comment (lukmccall) [inline packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt]:
```suggestion
  private fun setIsAnimating(resource: GifDrawable, setAnimating: Boolean) {
```
It is not toggling anything when you're passing `setAnimating` as an option.
Also, we should be able to use function overloading rather than creating a separate function for each type.

File: packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt [hunk 4]
```diff
@@ -170,13 +171,32 @@ class ExpoImageViewWrapper(context: Context, appContext: AppContext) : ExpoView(
...
       } else {
-        resource.stop()
+        resource.start()
       }
+    } else {
+      resource.pause()
+    }
+  }
+
+  private fun toggleAnimatableAnimation(resource: Animatable, setAnimating: Boolean) {
```
Comment (lukmccall) [inline packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt]:
```suggestion
  private fun setIsAnimating(resource: Animatable, setAnimating: Boolean) {
```

File: packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt [hunk 5]
```diff
@@ -170,13 +171,32 @@ class ExpoImageViewWrapper(context: Context, appContext: AppContext) : ExpoView(
 
   fun setIsAnimating(setAnimating: Boolean) {
     val resource = activeView.drawable
+    /* Animatable animations always start from the beginning when resumed.
+    So we check first if the resource is a GifDrawable, because it can continue
+    from where it was paused. */
+    when (resource) {
+      is GifDrawable -> toggleGifDrawableAnimation(resource, setAnimating)
+      is Animatable -> toggleAnimatableAnimation(resource, setAnimating)
```
Comment (lukmccall) [inline packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageViewWrapper.kt]:
```suggestion
      is GifDrawable -> setIsAnimating(resource, setAnimating)
      is Animatable -> setIsAnimating(resource, setAnimating)
```

**Review by lukmccall — COMMENTED** [review]
image
NCL (native-component-list) is still failing. Otherwise, it looks good.

File: packages/expo-image/CHANGELOG.md [hunk 6]
```diff
@@ -24,6 +26,20 @@
...
+- [iOS] `useAppleWebpCodec` has been moved from the source object to the component's prop to make it usable with the local assets. ([#37300](https://github.com/expo/expo/pull/37300) by [@tsapeta](https://github.com/tsapeta))
+
+### 🐛 Bug fixes
+
+- [iOS] Fix blurry images when using `tintColor` by scaling `imageThumbnailPixelSize` with screen density. ([#37235](https://github.com/expo/expo/pull/37235) by [@hirbod](https://github.com/hirbod))
+
+## 2.2.1 - 2025-06-10
+
+_This version does not introduce any user-facing changes._
+
```
Comment (lukmccall) [inline packages/expo-image/CHANGELOG.md]: Those lines shouldn’t be part of this PR. Something probably went wrong during rebasing. 😅

**Review by lukmccall — APPROVED** [review]
Please fix the changelog, and then you can merge your first PR ;)

**Comment by Wenszel** [comment]
> Please fix the changelog, and then you can merge your first PR ;)

@lukmccall  I don't have merge permissions
Zrzut ekranu 2025-06-12 o 22 23 38
