### PR TITLE
[audio][android]  Fix zero-byte audio recordings

### LINKED ISSUE #39646: [SDK 54] [Android] [expo-audio] Audio recorder returns URI for zero-byte audio file instead of actual recording
### Minimal reproducible example

https://github.com/leojalfred/expo-audio-android-issue-example

### Steps to reproduce

1. Clone and `cd` into the linked example repository
2. `bun install`
3. `bun android`
4. Tap the "Start Recording" button, record for as long as you'd like, tap the "Stop Recording" button
5. Open Android Studio, then from the toolbar click View -> Tool Windows -> Device Explorer
6. Go to the `data/data/com.example.audio/cache/Audio` folder and notice that two recording files have been made, one that's zero bytes in size that matches up with the logged URI and another one that contains the actual recording info

Image

I've tested this both on an emulator and on a real Pixel 9a and got the same result on both. I didn't have this issue before I upgraded from Expo 53 to 54. I have a workaround in my real project to get the actual recording URI that relies on `expo-file-system` as follows:

```ts
async function getActualRecordingUri(createdAt: Date): Promise<string | null> {
  try {
    const files = new Directory(Paths.cache, 'Audio').list()
    if (!files.length) return null

    const fileInfos = files.map((file) => file.info())
    const validFiles = fileInfos.filter((f) => f.size && f.size > 0)
    if (validFiles.length === 0) return null

    const targetTime = createdAt.getTime()
    let closest: DirectoryInfo | FileInfo | null = null
    let minDiff = Infinity

    for (const file of validFiles) {
      if (!file.creationTime || !file.uri) continue
      const diff = Math.abs(file.creationTime - targetTime)
      if (diff < minDiff) {
        closest = file
        minDiff = diff
      }
    }

    return closest?.uri?.slice(0, -1) ?? null
  } catch (e) {
    console.error(e)
    return null
  }
}
```

This fixes the issue for me for the time being, but I'd prefer not to have to rely on this for long.

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 15.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.18.0 - ~/.local/state/fnm_multishells/49981_1757805769084/bin/node
      npm: 10.9.3 - ~/.local/state/fnm_multishells/49981_1757805769084/bin/npm
      Watchman: 2025.08.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
      Android SDK:
        API Levels: 35, 36
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 34.0.0, 35.0.0, 36.0.0
        System Images: android-36 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2513.14007798
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.7 => 54.0.7 
      expo-router: ~6.0.4 => 6.0.4 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
      react-native-web: ~0.21.0 => 0.21.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by hirbod**
# Why

The audio recorder returns a URI pointing to a zero-byte file instead of the actual recording on Android. This was caused by auto-preparation in stopRecording() which immediately created a new empty file after each recording, causing the uri property to point to the wrong file.

This was a regression introduced in #38612 because I tried to auto-prepare the next recording to align more with iOS and Web. Since our docs also state that you need to call `prepareToRecordAsync()` before each recording, we can safely revert this.

Fixes #39646

# How

- Removed auto-preparation call from stopRecording() method
- Preserved filePath after recording stops so uri property continues to work as documented

# Test Plan

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: apps/native-component-list/src/screens/Audio/expo-audio/RecordingScreen.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default function RecordingScreen() {
     return uri ? (
       <>
         <HeadingText>Last recording</HeadingText>
-        <AudioPlayer source={{ uri }} />
+        <AudioPlayer key={uri} source={{ uri }} />
```
Comment (hirbod) [inline apps/native-component-list/src/screens/Audio/expo-audio/RecordingScreen.tsx:18]: The player would often not update in the Emulator when I made quick recordings back to back, but adding a key fixed that issue.

**Review by alanjhughes — APPROVED** [review]
