### PR TITLE
fix(expo-contacts): do not reject `requestPermissionsAsync` promise on iOS

### LINKED ISSUE #29528: [expo-contacts] requestPermissionsAsync throws on iOS when access denied
### Minimal reproducible example

https://github.com/jp1987/expo-contacts-permissions

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When calling `Contacts.requestPermissionsAsync` and denying access, the promise should resolve with the correct `PermissionStatus`. Instead, it throws:

```javascript
{
    "code": "E_CONTACTS_ERROR_UNKNOWN"
}
```

See video.

https://github.com/expo/expo/assets/1288101/c5d43142-4863-4430-a256-8f6a7b5a3a87

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/jesperpaardekooper/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 26, 30, 31, 34
        Build Tools: 26.0.3, 34.0.0
        System Images: android-26 | Google APIs Intel x86_64 Atom, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.11 => 51.0.11 
      expo-router: ~3.5.15 => 3.5.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by jp1987**
# Why

Closes [#29528](https://github.com/expo/expo/issues/29528)

# How

`CNContactStore.requestAccess` may return a boolean and error, but the [documentation](https://developer.apple.com/documentation/contacts/cncontactstore/requestaccess(for:completionhandler:)) is pretty vague as to when `error` is set. As demonstrated in the video of [#29528](https://github.com/expo/expo/issues/29528), `error` is set when denying access. This change makes sure the promise always resolves, which I believe is fine in this case.

# Test Plan

Manually tested in `bare-expo`.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-contacts/ios/ContactsRequester.swift [hunk 1]
```diff
@@ -30,10 +30,6 @@ class ContactsPermissionRequester: NSObject, EXPermissionsRequester {
       guard let self else {
         return
       }
-      if let error {
-        reject("E_CONTACTS_ERROR_UNKNOWN", error.localizedDescription, error)
-        return
-      }
```
Comment (alanjhughes) [inline packages/expo-contacts/ios/ContactsRequester.swift:36]: If the error is not necessary, we can omit the parameter otherwise there will be a warning. The warnings from Xcode don't work correctly in bare expo.

**Review by alanjhughes — CHANGES_REQUESTED** [review]

File: packages/expo-contacts/ios/ContactsRequester.swift (hunk 1 above)
Comment (jp1987) [reply packages/expo-contacts/ios/ContactsRequester.swift:36]: > If the error is not necessary, we can omit the parameter otherwise there will be a warning. The warnings from Xcode don't work correctly in bare expo.

Right, no Swift expert here admittedly, pushed a new commit that replaces `error` for `_`

Comment (alanjhughes) [reply packages/expo-contacts/ios/ContactsRequester.swift:36]: No problem 👍

**Review by alanjhughes — APPROVED** [review]
