### PR TITLE
[core][ios] Re-Dispatch `View` `AsyncFunction` calls when the `View` is not registered

### LINKED ISSUE #33582: expo-video EnterFullScreen - Cannot open video full screen
### Minimal reproducible example

https://github.com/deelo55/expo-video-fullscreen-example

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When trying to run expo-video full screen and using expo router  I  cannot get the video player to enter full screen programmatically.

When I run the same code without expo router, I do not get any issue.

```
import { VideoView, useVideoPlayer } from 'expo-video';
import React, { useEffect, useRef } from 'react';
import { StyleSheet, View } from 'react-native';

export type VideoPlayerProps = {
  videoUrl: string;
  onStop: () => void;
  shouldPlay: boolean;
};

export default function VideoPlayer({
  videoUrl,
  onStop,
  shouldPlay,
  setDurationText,
}: VideoPlayerProps & { setDurationText: (duration: string) => void }) {
  const player = useVideoPlayer({ uri: videoUrl }, (playerInstance) => {});

  const playerRef = useRef<VideoView>(null);
  useEffect(() => {
    if (playerRef.current) {
      if (shouldPlay) {
        player.play();
        playerRef.current.enterFullscreen();
      } else {
        player.pause();
      }
    }
  }, [shouldPlay, playerRef.current]);
  return (
    <View style={styles.videoContainer}>
      <VideoView
        ref={playerRef}
        style={styles.video}
        player={player}
        allowsFullscreen
        contentFit={'contain'}
        nativeControls
        onFullscreenExit={() => onStop()}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  videoContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
    width: '100%',
    height: '50%',
    paddingTop: 20,
  },
  video: {
    width: '100%',
    height: '50%',
  },
});


```

When I try the same code in my app I get the following error message (but not in the minimum reproducible)

```
Error: Calling the 'enterFullscreen' function has failed
→ Caused by: The 1st argument cannot be cast to type View<VideoView>
→ Caused by: Unable to find the 'VideoView' view with tag '1412'
Error: Calling the 'enterFullscreen' function has failed
→ Caused by: The 1st argument cannot be cast to type View<VideoView>
→ Caused by: Unable to find the 'VideoView' view with tag '1412'
    at construct (native)
    at apply (native)
    at _construct (http://10.0.0.208:11000/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:3860:67)
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - /opt/homebrew/opt/node@22/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/opt/node@22/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.17 => 52.0.17 
      expo-router: ~4.0.11 => 4.0.12 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
    npmGlobalPackages:
      eas-cli: 13.4.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, scheme, splash, ios, android, plugins. 


The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-video
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/33582
Similar to https://github.com/expo/expo/commit/bfe63e33cef041d1b3a1004fed0abefd54504bda

In iOS on new Architecture when a view function is called from the initial render 
```
useEffect({ viewRef.current.someAsyncFunction() },[])
```
it will be called before the view is added to the viewRegistry, which means that the argument conversion will fail (the first argument of the function is the view)

# How

We check for the conditions in which this situation occurs and re-dispatch the function up to three times waiting for the viewManager to get the information about the view. This is sub-optimal, but we don't have access to the scheduler, which would allow us to do this properly.

# Test Plan

Tested in BareExpo on iOS

### CODE REVIEW

File: packages/expo-modules-core/ios/Core/Functions/AsyncFunctionDefinition.swift [hunk 1]
```diff
@@ -115,6 +115,43 @@ public final class AsyncFunctionDefinition<Args, FirstArgType, ReturnType>: AnyA
...
+
+    queue.async {
+#if RCT_NEW_ARCH_ENABLED
+      // Checks if this is a view function unregistered in the view registry. The check can be performed from the main thread only.
+      if retryCount < maxRetryCount,
+      let viewTag = arguments.first as? Int,
+      let uiManager = appContext.reactBridge?.uiManager,
+      self.dynamicArgumentTypes.first is DynamicViewType,
+      Thread.isMainThread, // swiftlint:disable:next legacy_objc_type
+      uiManager.view(forReactTag: NSNumber(value: viewTag)) == nil {
```
Comment (lukmccall) [inline packages/expo-modules-core/ios/Core/Functions/AsyncFunctionDefinition.swift:142]:
```suggestion
        let viewTag = arguments.first as? Int,
        let uiManager = appContext.reactBridge?.uiManager,
        self.dynamicArgumentTypes.first is DynamicViewType,
        Thread.isMainThread, // swiftlint:disable:next legacy_objc_type
        uiManager.view(forReactTag: NSNumber(value: viewTag)) == nil {
```

File: packages/expo-modules-core/ios/Core/Functions/AsyncFunctionDefinition.swift [hunk 2]
```diff
@@ -115,6 +115,43 @@ public final class AsyncFunctionDefinition<Args, FirstArgType, ReturnType>: AnyA
...
+        // Schedule the block on the original queue through UI manager if view is missing in the registry.
+        DispatchQueue.main.async {
+          self.dispatchOnQueueUntilViewRegisters(appContext: appContext, arguments: arguments, queue: queue, retryCount: retryCount + 1, block)
+        }
```
Comment (lukmccall) [inline packages/expo-modules-core/ios/Core/Functions/AsyncFunctionDefinition.swift:146]:
```suggestion
        self.dispatchOnQueueUntilViewRegisters(appContext: appContext, arguments: arguments, queue: queue, retryCount: retryCount + 1, block)
```

**Review by lukmccall — APPROVED** [review]
