### PR TITLE
[Android][Notifications] Fix Data-only FCM Notifications appearing in Notification Drawer

### LINKED ISSUE #16261: [expo-notifications][android] Data-only FCM notification shows an empty item in the tray
### Summary

Data messages in android https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages are notifications that are handled by the app. In expo-notifications, it seems that all notifications are handled by the library (all notifications are data notifications). 

When these don't contain a body or title the expected behavior is to not show the notification in the tray (foreground or background). Note that when in the foreground the behavior can be set via `setNotificationHandler` but this doesn't apply to background.

The bug is that these are shown as a blank notification in the tray and drawer.

Screenshot_20220210-205622
Screenshot_20220210-205617

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.8.0 - ~/.volta/tools/image/node/16.8.0/bin/node
      Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
      npm: 7.21.0 - ~/.volta/tools/image/node/16.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        Android NDK: 22.0.6917172-beta1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

1. Create expo app (`expo init repro-app`), choose typescript (though shouldn't matter, just using ts for repro code)
2. Follow the setup steps for `expo-notifications` on Android: https://docs.expo.dev/versions/latest/sdk/notifications/ 
3. Put the following in App.ts

```typescript
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Platform } from 'react-native';
import { Notification } from 'expo-notifications';
import { Image } from 'react-native';
import { Subscription } from 'expo-modules-core';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: false,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState<string | undefined>('');
  const [devicePushToken, setDevicePushToken] = useState<string | undefined>('');
  const [notification, setNotification] = useState<Notification | undefined>();
  const notificationListener = useRef<Subscription>();
  const responseListener = useRef<Subscription>();

  useEffect(() => {
    registerForPushNotificationsAsync().then(([token, deviceToken]) => {
      setExpoPushToken(token);
      setDevicePushToken(deviceToken);
    });

    // This listener is fired whenever a notification is received while the app is foregrounded
    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      console.log(notification);
      setNotification(notification);
    });

    // This listener is fired whenever a user taps on or interacts with a notification (works when app is foregrounded, backgrounded, or killed)
    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      if (notificationListener.current) {
        Notifications.removeNotificationSubscription(notificationListener.current);
      }
      if (responseListener.current) {
        Notifications.removeNotificationSubscription(responseListener.current);
      }
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push tokend: {expoPushToken}</Text>
      <Image source={require('./assets/icon.png')} style={{width: 100, height: 100}} />
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
    </View>
  );
}

async function registerForPushNotificationsAsync(): Promise<[string | undefined, string | undefined]> {
  let token;
  let deviceToken;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return [undefined, undefined];
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    deviceToken = await (await Notifications.getDevicePushTokenAsync()).data;
    console.log(token);
    console.log(deviceToken);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return [token, deviceToken];
}
```

3. Plug in development device (I'm using recent pixel but it shouldn't matter)
4. `expo run:android`
5. Copy the expo push token from the console log.
6. Send push notification via expo push notification api: https://docs.expo.dev/push-notifications/sending-notifications/

```
{
	"to": "ExponentPushToken[...]",
	"data": {"hello": "world"}
}
```
7. See that it is shown in the tray
8. Copy the device token from the console log.
9. Send push notification via FCM directly: https://docs.expo.dev/push-notifications/sending-notifications-custom/

```
{"to":"...","priority":"normal","data":{"experienceId":"@wschurman/brex-repro","scopeKey":"@wschurman/brex-repro","hello":"world"}}
```
10. See that it is also shown in the tray.

### PR DESCRIPTION
**Pull request by sausti**
# Why
Fixes #16261. Prior to this change "data only" or "silent" Push Notifications would appear in the Android Notification Drawer, despite not having a title or message. This is an odd user experience, which makes it difficult for developers to leverage "silent" notifications to update app data (e.g. the badge count).

# How
This already functions correctly on iOS, but for Android a native change was required to check for the existence of the Notification title and message. If both are not present, we should not attempt to show this notification in the Notification Drawer.

# Test Plan
Unit testing added for native Android changes. To test end-to-end, see  #16261 for sample app code and detailed instructions on setting up a Firebase project.

Running `apps/bare-expo`'s Expo Test Suite's "Notifications" end-to-end should also verify that there are no regressions.

# Checklist
- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-notifications/android/src/test/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegateTest.kt [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+import io.mockk.spyk
+import io.mockk.verify
+import org.json.JSONObject
+import org.junit.Before
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.RobolectricTestRunner
+
+@RunWith(RobolectricTestRunner::class)
+class ExpoHandlingDelegateTest {
```
Comment (sausti) [inline packages/expo-notifications/android/src/test/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegateTest.kt:23]: I would prefer to use fakes over mocking here, but I found this rather challenging without refactoring out static method calls and non-injected dependencies from `ExpoHandlingDelegate`. We also have to use `Robolectric` here given the `Context` dependency.

The use of spies and mocks here allows me to limit the changes required

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt [hunk 2]
```diff
@@ -56,12 +56,24 @@ class ExpoHandlingDelegate(protected val context: Context) : HandlingDelegate {
...
     if (isAppInForeground()) {
       getListeners().forEach {
         it.onNotificationReceived(notification)
       }
-    } else {
+    } else if (!(
+      notification.notificationRequest.content.title.isNullOrEmpty() &&
+        notification.notificationRequest.content.text.isNullOrEmpty()
+      )
+    ) {
```
Comment (Kudo) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt:76]:
```suggestion
    } else if (shouldPresentNotification(notification)) {
```

we could try to refactor these logic into separated method and the code would also be clear.

```kotlin
/**
 * If the app is backgrounded, a notification is only presented if
 * the title and text are both non-empty. Otherwise, this is a "data-only" or "silent"
 * notification that should not be presented to the user.
 */
private fun shouldPresentNotification(notification: Notification) {
  val content = notification.notificationRequest.content
  if (content.title.isNullOrEmpty() || content.text.isNullOrEmpty()) {
    return false
  }
  return true
}
```

**Review by Kudo — COMMENTED** [review]
thanks for the nice pr. there's one thing we would need your help. could you help us to add an entry in the [changelog](https://github.com/expo/expo/blob/main/packages/expo-notifications/CHANGELOG.md), so that people can know what's new when we publish a new version. the log entry can be placed under the _unpublished > new features_ section.

File: packages/expo-notifications/android/src/test/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegateTest.kt (hunk 1 above)
Comment (barthap) [reply packages/expo-notifications/android/src/test/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegateTest.kt:23]: Using spies and mocks is ok. We use them extensively in other packages' tests. `RobolectricTestRunner` is also a good choice 👍

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt [hunk 3]
```diff
@@ -99,11 +99,20 @@ class ExpoHandlingDelegate(protected val context: Context) : HandlingDelegate {
...
     }
   }
 
+  /**
+   * If the app is backgrounded, a notification is only presented if
+   * the title and text are both non-empty. Otherwise, this is a "data-only" or "silent"
+   * notification that should not be presented to the user.
+   */
+  private fun Notification.shouldPresent(): Boolean {
+    return !(notificationRequest.content.title.isNullOrEmpty() && notificationRequest.content.text.isNullOrEmpty())
```
Comment (Kudo) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt:113]: i was wondering for the logic here. if title is empty but text is not empty, do we present the notification? from the implementation and test code i think the answer is yes, but from the comment above, i think it's no.

> a notification is only presented if the title and text are both non-empty.

could you help me to clarify that?

File: packages/expo-notifications/android/build.gradle [hunk 4]
```diff
@@ -95,4 +95,9 @@ dependencies {
   api 'com.google.firebase:firebase-messaging:21.1.0'
 
   api 'me.leolin:ShortcutBadger:1.1.22@aar'
+
+  testImplementation "androidx.test:core:1.4.0"
+  testImplementation "junit:junit:4.13.2"
+  testImplementation "org.robolectric:robolectric:4.7.3"
+  testImplementation "io.mockk:mockk:1.12.3"
```
Comment (barthap) [inline packages/expo-notifications/android/build.gradle:102]: The `expo-modules-test-core` includes all of the above dependencies + some utilities. This helps keep test dependency versions consistent across all packages 😉 
```suggestion
  if (project.findProject(':expo-modules-test-core')) {
    testImplementation project(':expo-modules-test-core')
  }
```

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt (hunk 3 above)
Comment (sausti) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt:113]: Good catch! This comment was in error. If there is a title only or text only, notifications should still be displayed. If both are missing then this is a "silent notification".

I've updated the comment to reflect this 😄.

**Comment by sausti** [comment]
Bad rebase, resolving 😄.

**Comment by sausti** [comment]
@EvanBacon @byCedric apologies for adding you! A bad rebase (now resolved) pulled in unrelated changes with you two as code owners on the files.

**Review by Kudo — APPROVED** [review]
awesome work from the solid code and test 🔥 thanks for improving the notifications library.
