### PR TITLE
[updates] Fix autolayout broken in ipad rotation

### LINKED ISSUE #14967: Auto-layout/Orientation/split-screen does not work for iOS in expo 43 production builds
### Summary

We recently updated out app to expo 43 from expo 42. In dev everything looked good, so we did a build and submitted to Apple. Once the build was approved we found that the iPad app no longer resized correctly when rotating the iPad (the app seemed to keep the same dimensions and a gray area was added to the empty area. We found this to be turn when using split screen and when having our app float to the side. We're not sure how to debug because the issue does not preset at all in dev on device or in the simulator. It also isn't reproducible in a snack as far as we can tell.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS (both iPhone and iPad)

### SDK Version (managed workflow only)

43

### Environment

production app on iOS

### Reproducible demo or steps to reproduce from a blank project

Just create a blank project and submit to TestFlight or the App Store. Here is what I used:

https://github.com/tiltshift/expo43ipad

### PR DESCRIPTION
**Pull request by Kudo**
# Why

the ipad simulator rotation is breaking after #14519, (not triggered from the true device rotation cmd-left key, but the  bottom right rotate button). 
Screen Shot 2021-11-09 at 12 53 22 AM

the thing is like autolayout broken because we cannot reuse rootViewController for new view, otherwise view's frame or bounds will not update.

fixed #14967 

# How

so far i didn't find a better solution and back to create a new `rootViewController`. to be compatible with expo-screen-orientation, i use the its selector/property. maybe we should do it in expo-module-core interfaces ? 

# Test Plan

expo init sdk43 + this patch to expo-updates
test ipad simulator rotation
test cmd-left device rotation
test `expo publish` and make sure update works
test `SplashScreen.preventAutoHideAsync()` and make sure splash screen keeps there.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
i am hesitant to propose this workaround dedicated for sdk-43. i'll try to find a proper fix for next sdk.
please help to early review to see if the change makes sense. or let me know if it's recommended to integrate the fix into expo-modules-core interfaces for expo-updates <-> expo-screen-orientation integration.

**Review by esamelson — APPROVED** [review]
For the longer term it does seem more correct to delegate creation of the root view controller to expo-splash-screen (probably through expo-modules-core), but I think this is fine as a short-term fix for SDK 43.

File: packages/expo-updates/ios/EXUpdates/EXUpdatesAppController.m [hunk 1]
```diff
@@ -146,27 +146,30 @@ - (void)start
 
 - (void)startAndShowLaunchScreen:(UIWindow *)window
 {
-  UIView *view = nil;
+  UIViewController* rootViewController = [EXUpdatesUtils createRootViewController:window];
```
Comment (tsapeta) [inline packages/expo-updates/ios/EXUpdates/EXUpdatesAppController.m:149]:
```suggestion
  UIViewController *rootViewController = [EXUpdatesUtils createRootViewController:window];
```

File: packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m [hunk 2]
```diff
@@ -118,6 +118,27 @@ + (NSString *)pathForBundledAsset:(EXUpdatesAsset *)asset
     : [[NSBundle mainBundle] pathForResource:asset.mainBundleFilename ofType:asset.type];
 }
 
+// Recreate a UIViewController from old `window.rootViewController`
++ (UIViewController *)createRootViewController:(UIWindow *)window
+{
+  UIViewController* result;
```
Comment (tsapeta) [inline packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:124]:
```suggestion
  UIViewController *result;
```

File: packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m [hunk 3]
```diff
@@ -118,6 +118,27 @@ + (NSString *)pathForBundledAsset:(EXUpdatesAsset *)asset
...
+  UIViewController* oldRootViewController = window.rootViewController;
```
Comment (tsapeta) [inline packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:125]:
```suggestion
  UIViewController *oldRootViewController = window.rootViewController;
```

File: packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m [hunk 4]
```diff
@@ -118,6 +118,27 @@ + (NSString *)pathForBundledAsset:(EXUpdatesAsset *)asset
...
+
+  SEL screenOrientationSelector = NSSelectorFromString(@"initWithDefaultScreenOrientationMask:");
+  // Support expo-screen-orientation's designated initializer
+  if ([oldRootViewController respondsToSelector:screenOrientationSelector]) {
+    NSNumber *maskValue = (NSNumber *) [oldRootViewController valueForKey:@"defaultOrientationMask"];
```
Comment (tsapeta) [inline packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:130]:
```suggestion
    NSNumber *maskValue = (NSNumber *)[oldRootViewController valueForKey:@"defaultOrientationMask"];
```

File: packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m [hunk 5]
```diff
@@ -118,6 +118,27 @@ + (NSString *)pathForBundledAsset:(EXUpdatesAsset *)asset
...
+    UIInterfaceOrientationMask mask = (UIInterfaceOrientationMask) [maskValue intValue];
+    id instance = [oldRootViewController.class alloc];
+    IMP imp = [instance methodForSelector:screenOrientationSelector];
+    result = ((id (*)(id, SEL, UIInterfaceOrientationMask))imp)(instance, screenOrientationSelector, mask);
```
Comment (tsapeta) [inline packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: Can't we just make a separate protocol with this initializer, check if the instance conforms to the protocol and call it in a standard way? 😅

**Comment by Kudo** [comment]
> For the longer term it does seem more correct to delegate creation of the root view controller to expo-splash-screen (probably through expo-modules-core), but I think this is fine as a short-term fix for SDK 43.

thanks @esamelson. i agree that is totally not an ideal solution. so far coming in my mind is somehow a `createRootViewController` like this:

https://github.com/facebook/react-native/blob/daf37a1fce43403e6320e1e3023e86fd1b970bdf/ReactAndroid/src/main/java/com/facebook/react/ReactDelegate.java#L111-L113

i'm working on the enhanced modularization for RCTBridge. this situation would definitely be better for next sdk.

File: packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m (hunk 5 above)
Comment (Kudo) [reply packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: > Can't we just make a separate protocol with this initializer, check if the instance conforms to the protocol and call it in a standard way? 😅

yes, that is what i mean for the "interfaces of expo-modules-core". the protocol should be placed in expo-modules-core because it's crossing expo-updates and expo-screen-orientation. if that make sense to you, i can update the pr with the change.

Comment (tsapeta) [reply packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: Yeah, that's good idea but you can also make it just in expo-updates if you don't want to clutter modules core. In ObjC, the screen orientation class doesn't have to explicitly inherit from that protocol, if you use define the protocol in updates and check `conformsToProtocol` on the object, it will work.

Comment (Kudo) [reply packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: @tsapeta looks like it doesn't work. or if i misunderstood something.

```objc
@interface ClassA : NSObject

- (instancetype)initCommon;

@end

@implementation ClassA

- (instancetype)initCommon
{
  return (self = [super init]);
}

@end

@protocol CommonProtocol

- (instancetype)initCommon;

@end

@interface ClassB : NSObject

- (instancetype)initCommon;

@end

@implementation ClassB

- (instancetype)initCommon
{
  return (self = [super init]);
}

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  ClassB *instance = [[ClassB alloc] init];
  if ([instance conformsToProtocol:@protocol(CommonProtocol)]) {
    NSLog(@"conformsToProtocol: YES");
  } else {
    NSLog(@"conformsToProtocol: NO");
  }
  // Override point for customization after application launch.
  return YES;
}
```

the output is : `conformsToProtocol: NO`

if `@interface ClassB : NSObject<CommonProtocol>` then the output is `conformsToProtocol: YES`

Comment (tsapeta) [reply packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: Yeah, but what if you declare the conformance by the category? Like
```objc
@interface ClassA (CommonCategory) <CommonProtocol>
@end
```

Comment (tsapeta) [reply packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: Ah, I see — it would have to be for `UIViewController` 🤔 so maybe let's leave it as you did 😉

Comment (Kudo) [reply packages/expo-updates/ios/EXUpdates/EXUpdatesUtils.m:134]: yep, i think so either. adding both @interface and @protocol inside expo-updates for expo-screen-orientation sounds to increase much complexity. let's go with my original approach. thank you, @tsapeta.

**Review by tsapeta — APPROVED** [review]
