### PR TITLE
[blur][iOS] Fix issues with blur not blurring text content properly

### LINKED ISSUE #12871: BlurView not blurring text properly
### Summary

Text behind a `BlurView` looks like this:

117595488-97d26400-b106-11eb-9436-761d4677676a

It should look more like this:

Screen Shot 2021-05-09 at 9 12 34 PM

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

  ```
  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Using @MrLoh's MCVE from #12870: https://github.com/MrLoh/expo-blur-bug you can see that the text is indeed not blurred.

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves [ENG-1418](https://linear.app/expo/issue/ENG-1418/fix-outstanding-issues-with-expo-blur-on-ios)
Resolves https://github.com/expo/expo/issues/12871

# How

- [x] I've got rid of the previous blur mechanism that was basing on `alpha` manipulation, because this is [directly discouraged by Apple](https://developer.apple.com/documentation/uikit/uivisualeffectview) and it was not working very well 😞 
- [x] I've tested many available solutions
  - [x] [**react-native-blur**](https://github.com/Kureev/react-native-blur) is using [some undocumented (possibly `private` API](https://github.com/Kureev/react-native-blur/blob/master/ios/BlurEffectWithAmount.m#L43-L62)) and that discouraged me to use it (even though it is actually working)
  - [x] [**bluuur** native library](https://github.com/ML-Works/Bluuur) is using even [more private API](https://github.com/ML-Works/Bluuur/blob/master/Bluuur/Classes/MLWBluuurView.m#L68) and it's stopped working since **iOS 14**
  - [x] [**`UIViewPropertyAnimator`-based Gist**](https://gist.github.com/darrarski/29a2a4515508e385c90b3ffe6f975df7) is a clever way to take advantage of setting it's `fractionComplete` property and that's a solution I've adapted
- [x] I've rewritten almost all native iOS codebase to adapt `UIViewPropertyAnimator`-based approach to achieve blur intensity manipulation
- [x] I've enriched `BlurViewScreen` available in the `ncl` project with more text, fancy random images (fetched from https://source.unsplash.com/) and manual control over intensity value.

# Test Plan

- [x] I've manually tested backgrounding and foregrounding the app as this was mentioned it might cause problems, but it's working flawlessly
- [x] The solution I've proposed seems to be very resource-expensive as it recreates the animator and blur effect upon every render, but I've seen no framedrops in the inspector

## Recording of old behaviour

https://user-images.githubusercontent.com/16623003/139324716-f00d2491-087d-4aed-b6a9-52a868e1477f.mp4

## Recordings of new behaviour

| **iOS@13.7** (simulator) | **iOS@14.8** (actual device) | **iOS@15.0** (simulator) |
|---|---|---|
| <video src="https://user-images.githubusercontent.com/16623003/139319452-0ce82747-b9ca-4a33-96f7-9c9c30c1189e.mp4" /> | <video src="https://user-images.githubusercontent.com/16623003/139318654-2f19e895-5369-44f9-bb63-60ab7b065d97.mp4" /> | <video src="https://user-images.githubusercontent.com/16623003/139319506-131daf97-c560-4ad0-a11b-9d0b244c0fcd.mp4" /> |

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Cool that you also migrated code to Swift 👍

One nitpick: in Swift we don't need to prefix filenames nor symbols with `EX`. The only situation where it is needed is when you use them from Objective-C, but in that case I'd prefer
```swift
@objc(EXBlurView)
public class BlurView: UIView {
```

which exposes `BlurView` class as `EXBlurView` when used in Objective-C.

File: packages/expo-blur/src/BlurView.tsx [hunk 1]
```diff
@@ -1,41 +1,24 @@
-import { NativeModulesProxy, requireNativeViewManager } from 'expo-modules-core';
+import { requireNativeViewManager } from 'expo-modules-core';
 import * as React from 'react';
-import { findNodeHandle, View, StyleSheet } from 'react-native';
+import { View, StyleSheet } from 'react-native';
 
-import { BlurProps, BlurTint, ComponentOrHandle } from './BlurView.types';
+import { BlurProps } from './BlurView.types';
 
 export default class BlurView extends React.Component<BlurProps> {
```
Comment (Simek) [inline packages/expo-blur/src/BlurView.tsx:7]: Since most of the class related code has been removed, can we refactor this component to the functional one?

File: packages/expo-blur/ios/EXBlur/EXBlurViewManager.m [hunk 2]
```diff
@@ -31,39 +31,11 @@ - (NSString *)viewName
...
-  [view didSetProps:@[@"tint"]];
 }
 
 EX_VIEW_PROPERTY(intensity, NSNumber *, EXBlurView)
 {
-  [view setIntensity:value];
-  [view didSetProps:@[@"intensity"]];
-}
-
-EX_EXPORT_METHOD_AS(updateProps,
```
[the remark this answers is not in the document]
Comment (bbarthec) [reply packages/expo-blur/ios/EXBlur/EXBlurViewManager.m:43]: Yeah, I've found out the undocumented usage. I've restored the mechanism and even fixed it to work more properly 😅

File: packages/expo-blur/src/BlurView.tsx (hunk 1 above)
Comment (bbarthec) [reply packages/expo-blur/src/BlurView.tsx]: See the current implementation. I've researched the topic and there's no other way to achieve what's I was trying to do (ability to pass `ref={useRef}` prop and properly separate view-based props and blur-based props) 🤷

File: packages/expo-blur/src/index.ts [hunk 3]
```diff
@@ -1,2 +1,2 @@
 export { default as BlurView } from './BlurView';
-export { BlurTint, BlurProps } from './BlurView.types';
+export { BlurTint, BlurViewProps } from './BlurView.types';
```
Comment (tsapeta) [inline packages/expo-blur/src/index.ts:2]: Isn't it a breaking change if someone imported this type? 🤔

**Review by tsapeta — APPROVED** [review]

File: packages/expo-blur/src/index.ts (hunk 3 above)
Comment (bbarthec) [reply packages/expo-blur/src/index.ts:2]: Thank you for catching this! I intended to add this change to the CHANGELOG, but forgot about this later on 😅
