### PR TITLE
[expo-contacts] Fix presentFormAsync pre-filling 

### LINKED ISSUE #6401: Contacts - firstName, lastName, addresses and image not working
### Environment

  Expo CLI 3.9.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

App targets: iOS, Android

### Steps to Reproduce

Using **Contacts.presentFormAsync** to present the native "Create contact" view filled with firstName, lastName...etc.

```javascript
Contacts.presentFormAsync(null, {
  [Contacts.Fields.FirstName]: "John", // not working
  [Contacts.Fields.LastName]: "Doe", // not working
  [Contacts.Fields.Company]: 'Doe inc' // works
})
```

### Expected Behavior

firstName, lastName, addresses, image pre-filled in the presented view.

### Actual Behavior

Only certain fields are populated (e.g.: company, jobTitle)

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/6401.

# How

See [the original PR](https://github.com/expo/expo/pull/6444). Some of the issues were fixed in SDK 35. However, we still need to fix some of them. 

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/expo-contacts---fix-presentformasync- ✅

### CODE REVIEW

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.java [hunk 1]
```diff
@@ -183,6 +186,21 @@ public String getLastName() {
         return lastName;
     }
 
+    @Nullable
+    public String getDisplayName() {
+      if (displayName == null) {
+        if (firstName != null) {
+          if (lastName != null) {
```
Comment (tsapeta) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.java]: Too many `if`s 😅 Maybe we can make it simpler? Also, what if `firstName == null`? Shouldn't we return `lastName` then?

**Review by tsapeta — APPROVED** [review]

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.java (hunk 1 above)
Comment (lukmccall) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.java]: I made it simpler ;) 

We shouldn't return only `lastName`, cause then Android will interpret this value as a first name.
