### PR TITLE
[core][ios] Fix URI with encoded `#` getting cut off

### LINKED ISSUE #21321: [expo-image][ios] Image source URI with encoded `#` gets cut off
### Minimal reproducible example

https://github.com/trafficon/expo-image-search-params-bug

### Summary

If a `expo-image` `source.uri` contains an encoded `#` (which is `%23`) everything afterwards in that URI is getting cut off on iOS. This is how the `Image` component is beeing used:

```tsx
<Image
  source={{
    uri: 'http://localhost:3000?platform=' + Platform.OS + '&color=%230000ff&otherParam=willBeCutOff',
    width: 32,
    height: 32,
  }}
/>
```

This requests a SVG from this express server:
```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
    console.log("Requested URL:", req.originalUrl);

    const color = req.query.color;
    res.send(`<svg viewbox="0 0 32 32"><rect width="32" height="32" fill="${color}" /></svg>`)
})

app.listen(port, () => {
    console.log(`Server running on http://localhost:${port}`)
});
```
Which returns a colored SVG based on the `color` search param. This works on Anroid, but no on iOS:

| Android | iOS |
| ---- | --- |
| Screenshot_20230221_115854_expo-image-search-params-bug |  Simulator Screen Shot - iPhone 14 Pro - 2023-02-21 at 11 58 36 |

Both platforms should show a blue rectangle. The rectangle is black on iOS because the actually requested URI through `expo-image` on iOS is as follows from the express server log:

```
Android:
Requested URL: /?platform=android&color=%230000ff&otherParam=willBeCutOff

iOS:
Requested URL: /?platform=ios&color=
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: 0.18.12 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.6.0
      expo-cli: 6.3.1
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes https://github.com/expo/expo/issues/21321.

# How

In the previous implementation encoded `#` was mistakenly converted to the anchor separator. 

# Test Plan

- unit tests ✅
- https://github.com/trafficon/expo-image-search-params-bug ✅

### CODE REVIEW

File: packages/expo-modules-core/ios/Swift/Utilities.swift [hunk 1]
```diff
@@ -32,15 +32,29 @@ internal func toNSError(_ error: Error) -> NSError {
  Note that it encodes only characters that are not allowed in the url query and '#' that indicates the fragment part.
  */
 internal func percentEncodeUrlString(_ url: String) -> String? {
+  // URL contains '#' so it has a fragment part.
+  // We know that because that is the only allowed use case of the undecoded '#' symbol inside of the URL.
+  if (url.contains("#")) {
+    let urlParts = url.split(separator: "#")
+    
+    // Encodes the url without the fragment part. It'll leave the fragment part untounched.
+    guard let parsed = percentEncodeUrlStringWithoutFragmnet(String(urlParts[0])) else {
```
Comment (fobos531) [inline packages/expo-modules-core/ios/Swift/Utilities.swift:41]:
```suggestion
    guard let parsed = percentEncodeUrlStringWithoutFragment(String(urlParts[0])) else {
```

File: packages/expo-modules-core/ios/Swift/Utilities.swift [hunk 2]
```diff
@@ -32,15 +32,29 @@ internal func toNSError(_ error: Error) -> NSError {
...
+      return nil
+    }
+    
+    // Concatenate encoded path with fragment.
+    return parsed + "#" + urlParts[1]
+  }
+  
+  return percentEncodeUrlStringWithoutFragmnet(url)
```
Comment (fobos531) [inline packages/expo-modules-core/ios/Swift/Utilities.swift:49]:
```suggestion
  return percentEncodeUrlStringWithoutFragment(url)
```

File: packages/expo-modules-core/ios/Swift/Utilities.swift [hunk 3]
```diff
@@ -32,15 +32,29 @@ internal func toNSError(_ error: Error) -> NSError {
...
+}
+
+private func percentEncodeUrlStringWithoutFragmnet(_ url: String) -> String? {
```
Comment (fobos531) [inline packages/expo-modules-core/ios/Swift/Utilities.swift:52]:
```suggestion
private func percentEncodeUrlStringWithoutFragment(_ url: String) -> String? {
```

**Review by fobos531 — CHANGES_REQUESTED** [review]

**Review by tsapeta — APPROVED** [review]
