### PR TITLE
[android][image] Add `CookieJar` to image request client

### LINKED ISSUE #43229: [expo-image] [android] expo-image doesn't pass regular headers / cookies from the common react-native http stack
### Minimal reproducible example

https://github.com/alessbelli/test-expo-image-cookies

### Steps to reproduce

open the app ( `npm run android` )

This shows two requests to the same origin (cloudflare-worker code included in the repo).
The /json endpoint is shown in the text element at the bottom of the screen, while the /image.svg is shown at the top of the screen.
Both echo the request headers including the cookies. Both requests set a cookie in the response.

Note that the first request, there are no request cookies (that's expected)
When refreshing the app / opening it anew, note that the native fetch request shows the cookies set the first time around, whereas the expo-image request still shows no cookies.

This is a big problem if images on a given origin require authentication: they will never load.
To a lesser extent, it's very difficult to track usage coming from a specific mobile device since the two requests have a different user-agent.

I expect that by default, requests using expo-image use the same http layer as the base react-native stack that the rest of my app runs on. short of that, I expect to be able to easily swap this out for a predictable http layer.

This works correctly on iOS. requests from expo-image and fetch both come from the same user-agent (Expo/54.0.6 CFNetwork...) and result in requests to either endpoint having the cookies set during both.
android:
Image

ios:

Image

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 26.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.15.1 - ~/.nvm/versions/node/v22.15.1/bin/node
      npm: 10.9.2 - ~/.nvm/versions/node/v22.15.1/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/lib/ruby/gems/3.4.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.1, iOS 26.1, macOS 26.1, tvOS 26.1, visionOS 26.1, watchOS 26.1
    IDEs:
      Android Studio: 2025.2 AI-252.25557.131.2521.14432022
      Xcode: 26.1.1/17B100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.33 => 54.0.33
      react: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #43229
Currently, cookies sent through fetch are not shared with image requests made by expo image. This is because we create our own client but don't configure it to use the global CookieManager. 

# How
Implement `CookieJar`, read and write cookies to the shared manager and add it to the `OkHttpClient` builder.

# Test Plan
Tested in the provided repro

### CODE REVIEW

File: packages/expo-image/android/src/main/java/expo/modules/image/okhttp/ExpoImageOkHttpClientGlideModule.kt [hunk 1]
```diff
@@ -68,10 +72,35 @@ data class GlideUrlWrapper(val glideUrl: GlideUrl) {
...
+    val cookieString = cookieManager.getCookie(url.toString()) ?: return emptyList()
+    return cookieString.split(";").mapNotNull { Cookie.parse(url, it.trim()) }
+  }
+
+  private fun getCookieManager(): CookieManager? = try {
+    CookieManager.getInstance()
+  } catch (e: Exception) {
+    null
+  }
+}
```
Comment (lukmccall) [inline packages/expo-image/android/src/main/java/expo/modules/image/okhttp/ExpoImageOkHttpClientGlideModule.kt]:
```suggestion
  private fun getCookieManager(): CookieManager? = runCatching {
    CookieManager.getInstance() }.getOrNull()
  }
```

**Review by lukmccall — APPROVED** [review]

**Comment by teamclouday** [comment]
Hi, this change seems to be reverted in #44431. I'm using expo-image@56.0.12 and it fails to use cookie from the cookie store on android. The cookie was set from expo/fetch request.

Edit: I was using the wrong image URL. Can verify it works on android with 56.0.12.
