### PR TITLE
[expo] fix fetch abort error for streaming requests

### LINKED ISSUE #33553: Fetch doesn't cancel the stream
### Minimal reproducible example

https://github.com/hollanderbart/BusinessCards-Connect

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

When I've created a server fetch stream and I want to cancel the stream using an AbortController, the stream isn't cancelled. The stream still continues after calling the abort() function. I expect the current stream to be cancelled.

In my reproduction repo the stream is started but keeps returning messages, although abortController.abort() is called after the first message.

```
(NOBRIDGE) LOG  LOG: Response: {"redirected": false, "status": 200, "statusText": "no error", "url": "https://httpbin.org/drip?numbytes=10&duration=10&delay=1&code=200"}
 (NOBRIDGE) LOG  LOG: Reader: {"_closedPromise": {"_h": 0, "_i": 0, "_j": null, "_k": null}, "_closedPromise_reject": [Function anonymous], "_closedPromise_resolve": [Function anonymous], "_ownerReadableStream": {"_disturbed": false, "_readableStreamController": {"_cancelAlgorithm": [Function anonymous], "_closeRequested": false, "_controlledReadableStream": [Circular], "_pullAgain": false, "_pullAlgorithm": [Function anonymous], "_pulling": false, "_queue": [e], "_queueTotalSize": 0, "_started": false, "_strategyHWM": 1, "_strategySizeAlgorithm": [Function anonymous]}, "_reader": [Circular], "_state": "readable", "_storedError": undefined}, "_readRequests": {"_back": {"_elements": [Array], "_next": undefined}, "_cursor": 0, "_front": {"_elements": [Array], "_next": undefined}, "_size": 0}}
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Received chunk: *
 (NOBRIDGE) LOG  Trying to abort the stream
 (NOBRIDGE) LOG  Stream complete
```

@Kudo Can you please review what I'm doing wrong / verify this is an issue with the implementation? Thanks!

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.11.0/bin/npm
      Watchman: 2024.11.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 30.0.3, 33.0.3, 34.0.0, 35.0.0
        System Images: android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.17 => 52.0.17 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.4 => 0.76.4 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Validate packages against React Native Directory package metadata
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions

The following packages should be updated for best compatibility with the installed expo version:
  react-native@0.76.4 - expected version: 0.76.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
```

### PR DESCRIPTION
**Pull request by Kudo**
# Why

i unregistered the abort event listener earlier before the request finished.
fixes #33553

# How

unregister the abort event listener when native request is finished. i introduced a new `readyForJSFinalization` event that emits from both streaming and non-streaming requests.

# Test Plan

added a new test case for this in fetch test-suite

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: apps/test-suite/tests/Fetch.ts [hunk 1]
```diff
@@ -159,6 +159,32 @@ export function test({ describe, expect, it, ...t }) {
       }
       expect(error).not.toBeNull();
     });
+
+    it('should abort streaming request', async () => {
+      const controller = new AbortController();
+      setTimeout(() => controller.abort(), 500);
+      let error: Error | null = null;
+      try {
+        const resp = await fetch('https://httpbin.org/drip?numbytes=512&duration=2', {
```
Comment (hollanderbart) [inline apps/test-suite/tests/Fetch.ts:168]: How do you know that this backend service will behave the same during each test? I expect some flaky-ness will happen. 
It could happen that the service is offline or is slow, so the abort function in the timeout will be called too soon.

Comment (Kudo) [reply apps/test-suite/tests/Fetch.ts]: good call. i have the other pr #33558 to use a different server. should also update this pr. thanks!

Comment (hollanderbart) [reply apps/test-suite/tests/Fetch.ts]: Okay, I hope that is sufficient. One other solution to consider is to mock the backend call and response, so the response will always work, no matter the internet connection. MSW is a standard nowadays.

File: apps/test-suite/tests/Fetch.ts [hunk 2]
```diff
@@ -159,6 +159,32 @@ export function test({ describe, expect, it, ...t }) {
...
+          if (done) {
+            break;
+          }
+        }
+      } catch (e: unknown) {
+        if (e instanceof Error) {
+          error = e;
+        }
+      }
+      expect(error).not.toBeNull();
```
Comment (lukmccall) [inline apps/test-suite/tests/Fetch.ts:186]:
```suggestion
      let error: unknown | null = null;
      try {
        const resp = await fetch('https://httpbin.test.k6.io/drip?numbytes=512&duration=2', {
          signal: controller.signal,
          headers: {
            Accept: 'text/event-stream',
          },
        });
        const reader = resp.body.getReader();
        while (true) {
          const { done } = await reader.read();
          if (done) {
            break;
          }
        }
      } catch (e: unknown) {
        error = e;
      }
      expect(error).not.toBeNull();
      expect(error).toBeInstanceOf(Error);
```
What do you think?

**Review by lukmccall — APPROVED** [review]

File: apps/test-suite/tests/Fetch.ts (hunk 1 above)
Comment (Kudo) [reply apps/test-suite/tests/Fetch.ts]: > One other solution to consider is to mock the backend call and response, so the response will always work, no matter the internet connection. MSW is a standard nowadays.

i was looking for a proper mock, which would still receive and reply network requests. i feel that setup mocks in either js or native side is like not real. a mock server is much better, and MSW looks decent. thanks for sharing this. if the new server is not stable still, i would go MSW for a try.

Comment (hollanderbart) [reply apps/test-suite/tests/Fetch.ts]: Happy to have helped! 👍

File: apps/test-suite/tests/Fetch.ts (hunk 2 above)
Comment (Kudo) [reply apps/test-suite/tests/Fetch.ts:186]: reverted because our old jasmine does not support `toBeInstanceOf` 🙈

**Comment by Kudo** [comment]
rebase to see if it resolve the ios-test error

**Comment by Kudo** [comment]
i'm glad i added fetch to ci testing. that helps to catch the other issue when aborting after streaming started. that's fixed in https://github.com/expo/expo/pull/33577/commits/c2d67f77e13635467bd19c01b0c121369c27a3bd and finally get ci passed.
let's ship it.

**Comment by hollanderbart** [comment]
In which expo version will this be included? @Kudo

**Comment by Kudo** [comment]
i'm cherry-picking this to sdk-52 branch. i think we will publish the fix this week.
