### PR TITLE
[ios][location][permissions] fix ios permission flow

### LINKED ISSUE #33911: [SDK-52] [expo-location] Background location permission not working
### Minimal reproducible example

https://snack.expo.dev/@brodanoel/background-location-broken

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

The problem, as far as I see, is quite similar to this: https://github.com/expo/expo/issues/25873

Basically, I have to call 2 times `await Location.requestBackgroundPermissionsAsync();` in order to get the permissions.

Note: I'm using SDK 52 with DISABLED NEW ARCH

# Steps to Reproduce

* Open https://snack.expo.dev/@brodanoel/background-location-broken
* Tap on "Yes!" blue button
* It will ask you for foreground permissions first. Answer with: "Allow while using app"
* It will ask you for background permissions then. Answer with "Change to Always Allow"
* It will show you an error like if you canceled the permissions.
* Tap again on "Yes!" blue button
* It will show you the information as you would have grated the permissions before

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 12.7.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.04.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.23 => 52.0.23
      react: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

### PR DESCRIPTION
**Pull request by chrfalch**
# Why 

The iOS permission flow is a bit flawed as described in #33911 where asking for background permission in the same session as where you asked for foreground permissions results in the promise resolving too early with a permission denied result.

This was caused by the semi-complex way that iOS location permissions work from iOS 13+.

Closes #33911

# How

This PR proposes a fix that refactors how location permissions are requested on iOS:

- Refactored permission flow to include handling multiple permutations of the flow.
  - Removed deprecated delegate method `- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status`
  - Simplified handling the first delegate callback that we're not interested in (see http://stackoverflow.com/questions/30106341/swift-locationmanager-didchangeauthorizationstatus-always-called/30107511#30107511) by storing the initial state when starting a flow and comparing against this value instead of a static value that wasn't correct for some of the flows.
  - Added special handling for temporary foreground permissions by using active/inactive lifecycle events to detect wether a permission dialog was displayed or not.

# Test Plan

Test the following scenarios in BareExpo -> APIs -> Location

(before each test, make sure to clear any location permissions and restart the app)
    
  _rfp_ = requestForegroundPermissionsAsync, fp: Expected foreground permission
  _rbp_ = requestBackgroundPermissionsAsync, bg: Expected background permission
    
 - _rfp_ -> "Allow once", then _rbp_ -> no dialog = (fp: granted (temporary), bg: denied after 1.5 seconds)
 - _rfp_ -> "Allow while using App", then _rbp_ -> "Keep only while using" = (fp: granted, bg: denied)
 - _rfp_ -> "Allow while using App", then _rbp_ -> "Change to always allow" = (fp: granted, bg: granted)
 - _rfp_ -> "Don't allow", then _rbp_ -> no dialog = (fp: denied, bg: denied)
 - _rbp_ -> "Allow once", no more dialog = (fp: granted (temporary), bg: denied)
 - _rbp_ -> "Allow while using App", no more dialog = (fp: granted, bg: granted (provisional))
 - _rbp_ -> "Don't allow" = (fp: denied, bg: denied)

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-location/ios/Requesters/EXBaseLocationRequester.m [hunk 1]
```diff
@@ -73,25 +72,47 @@ - (void)requestPermissionsWithResolver:(EXPromiseResolveBlock)resolve rejecter:(
...
+    // you have started using the newly aquired permission before showing the permission dialog.
+    //
+    // Test the following scenarios in BareExpo -> APIs -> Location
+    // ------------------------------------------------------------
+    // (before tests, make sure to clear any location permissions and restart the app)
+    //
+    //   rfp = requestForegroundPermissionsAsync, fp: Actual foreground permission given
+    //   rbp = requestBackgroundPermissionsAsync, bg: Actual background permission given
+    //
+    // - rfp -> "Allow once", then rbp -> no dialog                             = (fp: granted (temporary), bg: denied after 1.5 seconds)
```
Comment (behenate) [inline packages/expo-location/ios/Requesters/EXBaseLocationRequester.m:106]: Does this mean that granting "Allow once" and then asking for background permissions will result in no dialog being shown and the permission being denied straight away?

Comment (chrfalch) [reply packages/expo-location/ios/Requesters/EXBaseLocationRequester.m:106]: Yes, that's the result. "Allow once" is a temporary permission that makes the system behave a bit strange - ie. the background request will not show at all.

Comment (behenate) [reply packages/expo-location/ios/Requesters/EXBaseLocationRequester.m:106]: Maybe we should add a note to the docs that explains it (and make it very visible 😆)? I think for most people this behaviour will be weird. 
Also I have an idea, have you tried requesting foreground permissions first every time the background permissions are requested? This should show the foreground popup first if the permissions are different than allow when using. If the user selects `allowOnce` again in that popup we can return `denied` for background permissions without having users complaining about getting the permissions denied without the app asking for them.

Comment (chrfalch) [reply packages/expo-location/ios/Requesters/EXBaseLocationRequester.m:106]: I already made a PR that was merged last week updating the docs :) 

Thanks for the suggestion - Not sure if I understood it correctly? Requesting background permissions (Always) without requesting foreground (When in use) is treated as requesting foreground permission anyway, so it shouldn't make any difference. There is no way unfortunately to see if the current foreground permission is a temporary one - this is documented as basically "your app should be able to function independently of wether the user selects Always or When in use location". 

What I do now (in this implementation) is to setup a simple timeout using the `UIApplicationWillResignActiveNotification` notification to see if a permission dialog is displayed when requesting background permission (Always) - if not, we can assume that the current permission (When in use) is temporary since the system ignores our background permission request.

**Review by alanjhughes — APPROVED** [review]

**Comment by hamannjames** [comment]
@chrfalch thanks for revisiting the ticket and getting this fix merged!
