### PR TITLE
[IAP][android] Upgrade Google Play Billing dependency

### LINKED ISSUE #12193: Upgrade version of Google Play Billing library to 3 (InAppPurchases)
### Summary

I have installed and used `expo-in-app-purchases`. But now when I publish an app on google play store I get a warning.

```
We've detected that this app is using an old version of Google Play Billing.
 By November 1, 2021, all app updates must use Billing Library version 3 or newer. Update to Billing Library 3 before this date.
 Learn More about Billing Library 3.
```

How do I upgrade it to version 3? this should automatically be updated when I installed the latest version of `expo-in-app-purchases` right?

Should we just wait or is there already a support for it in expo and I just do not know about it?

`AndroidManafist.xml`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.***">
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
	<uses-permission android:name="com.android.vending.BILLING" />
	<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme" android:requestLegacyExternalStorage="true">
		<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@***/***" />
		<meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="40.0.0" />
		<meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="***" />
		<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
		<activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.DOWNLOAD_COMPLETE" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
	</application>
</manifest>

```

I want it to be installed so I could be prepared before google block my app suddenly.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.0 

### Environment

  Expo CLI 4.1.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 15.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: ~16.13.1 => 16.13.1
      react-native: ^0.63.4 => 0.63.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Install and `expo-in-app-purchases` and publish it on google play console. 
And then you will get a warning.

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/12193

this upgrade is required by Nov 1st 

# How

looked at [the changlelog](https://developer.android.com/google/play/billing/release-notes), made those changes

# Test Plan

Tested these changes manually using `bare-expo`. Currently this requires you to change the package name to com.expo.payments, so we'll need to create a new Play Store app for `dev.expo.payments`

### CODE REVIEW

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 1]
```diff
@@ -253,27 +258,39 @@ public int getBillingClientResponseCode() {
...
+          public void onQueryPurchasesResponse(@NonNull BillingResult billingResult, @NonNull List<Purchase> inAppPurchases) {
+            inAppBillingResult = billingResult;
+            if (billingResult.getResponseCode() == BillingResponseCode.OK) {
+              purchases.addAll(inAppPurchases);
+            }
 
-          if (subscriptionResult != null && subscriptionResult.getResponseCode() == BillingResponseCode.OK) {
-            purchasesResult.getPurchasesList().addAll(
-              subscriptionResult.getPurchasesList());
+            if(areSubscriptionsSupported()) {
```
Comment (cruzach) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:279]:
```suggestion
            if (areSubscriptionsSupported()) {
```

File: apps/native-component-list/src/screens/InAppPurchases/InAppPurchases.tsx [hunk 2]
```diff
@@ -69,7 +69,7 @@ export default class InAppPurchases extends React.Component<any, any> {
         for (const purchase of results!) {
           console.log(`Successfully purchased ${purchase.productId}`);
           if (!purchase.acknowledged) {
-            finishTransactionAsync(purchase, true);
+            finishTransactionAsync(purchase, purchase.productId === 'gas');
```
Comment (cruzach) [inline apps/native-component-list/src/screens/InAppPurchases/InAppPurchases.tsx:72]: `gas` is the only consumable product

File: apps/native-component-list/src/screens/InAppPurchases/InAppPurchases.tsx [hunk 3]
```diff
@@ -87,7 +87,7 @@ export default class InAppPurchases extends React.Component<any, any> {
   }
 
   async queryPurchaseHistory() {
-    const { responseCode, results } = await getPurchaseHistoryAsync(true);
+    const { responseCode, results } = await getPurchaseHistoryAsync(false);
```
Comment (cruzach) [inline apps/native-component-list/src/screens/InAppPurchases/InAppPurchases.tsx:90]:
```suggestion
    const { responseCode, results } = await getPurchaseHistoryAsync(true);
```

**Comment by xdajay** [comment]
@ide @cruzach PlayStore isn't allowing publishing apps with an older version of billing, this also applies to old apps. Their definition of new apps is "when you integrated IAP, regardless of first publishing date.

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 4]
```diff
@@ -143,9 +145,14 @@ public void run() {
...
-        BillingFlowParams purchaseParams = BillingFlowParams.newBuilder()
-          .setSkuDetails(skuDetails).setOldSku(oldSku).build();
-        mBillingClient.launchBillingFlow(mActivity, purchaseParams);
+        BillingFlowParams.Builder purchaseParams = BillingFlowParams.newBuilder()
+          .setSkuDetails(skuDetails);
+        if (oldSku != null) {
+          purchaseParams.setSubscriptionUpdateParams(
+            BillingFlowParams.SubscriptionUpdateParams.newBuilder().setOldSkuPurchaseToken(oldSku).build()
+          );
+        }
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:154]: Have you tested this? Specifically, old SKU and old SKU purchase token look like two separate things.

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 5]
```diff
@@ -253,27 +259,39 @@ public int getBillingClientResponseCode() {
...
   /**
-   * Query purchases across various use cases and deliver the result in a formalized way through
-   * a listener
+   * Query both in app purchases and subscriptions and deliver the result in a formalized way 
+   * through a listener
    */
   public void queryPurchases(final Promise promise) {
     Runnable queryToExecute = new Runnable() {
+      BillingResult inAppBillingResult;
+      List<Purchase> purchases = new ArrayList<>();
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:268]: Move these declarations inside of `run()`. They might need to be marked `final`.

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 6]
```diff
@@ -253,27 +259,39 @@ public int getBillingClientResponseCode() {
...
+            inAppBillingResult = billingResult;
+            if (billingResult.getResponseCode() == BillingResponseCode.OK) {
+              purchases.addAll(inAppPurchases);
+            }
 
-          if (subscriptionResult != null && subscriptionResult.getResponseCode() == BillingResponseCode.OK) {
-            purchasesResult.getPurchasesList().addAll(
-              subscriptionResult.getPurchasesList());
+            if (areSubscriptionsSupported()) {
+              mBillingClient.queryPurchasesAsync(SkuType.SUBS, new PurchasesResponseListener() {
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:281]: Instead of nesting the async calls it would be better to run the two queryPurchasesAsync calls in parallel.

**Review by ide — CHANGES_REQUESTED** [review]

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java (hunk 4 above)
Comment (cruzach) [reply packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java]: Fixed here- https://github.com/expo/expo/pull/13884/commits/d8c71b1206b4e68ef235f611597e55c81e1019f3 (and tested manually)

However, this now requires you to run `getPurchaseHistoryAsync` before you run `purchaseItemAsync`. Most likely people are already doing this, but it is technically a breaking change. 
If we're making a breaking change, it might be a better idea to change `purchaseItemAsync` to accept the purchaseToken as the second argument directly, instead of the old SKU. The user would get this purchase token the same way we do- by querying their purchase history.

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java (hunk 6 above)
Comment (cruzach) [reply packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java]: Yeah had that originally, but we need to keep track of which listener finishes last, to call `onQueryPurchasesFinished`. Anyways, the extra lines of code are probably worth parallelizing

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 7]
```diff
@@ -253,27 +275,44 @@ public int getBillingClientResponseCode() {
...
-
-        // If there are subscriptions supported, we add subscription rows as well
-        if (purchasesResult != null && areSubscriptionsSupported()) {
-          PurchasesResult subscriptionResult
-            = mBillingClient.queryPurchases(SkuType.SUBS);
-
-          if (subscriptionResult != null && subscriptionResult.getResponseCode() == BillingResponseCode.OK) {
-            purchasesResult.getPurchasesList().addAll(
-              subscriptionResult.getPurchasesList());
+        final List<String> ALL_QUERIES = Arrays.asList(SkuType.INAPP, SkuType.SUBS);
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:285]: Use a Set for the queries

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 8]
```diff
@@ -253,27 +275,44 @@ public int getBillingClientResponseCode() {
...
+        List<Purchase> purchases = new ArrayList<>();
+        List<String> completedQueries = new ArrayList<>();
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:287]: Set

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 9]
```diff
@@ -253,27 +275,44 @@ public int getBillingClientResponseCode() {
...
+
+        mBillingClient.queryPurchasesAsync(SkuType.INAPP, new PurchasesResponseListener() {
+          @Override
+          public void onQueryPurchasesResponse(@NonNull BillingResult billingResult, @NonNull List<Purchase> inAppPurchases) {
+            if (billingResult.getResponseCode() == BillingResponseCode.OK) {
+              purchases.addAll(inAppPurchases);
+            }
+            completedQueries.add(SkuType.INAPP);
+            if (completedQueries.containsAll(ALL_QUERIES) || !areSubscriptionsSupported()) {
+              onQueryPurchasesFinished(billingResult, purchases, promise);
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:297]: The onQueryPurchasesFinished calls look potentially buggy since they pass in the BillingResult for one query but not both.

1. Is passing in the last BillingResult correct? Or do we want to aggregate data from the 1-2 BillingResults?
2. Is the old code buggy?

**Review by ide — CHANGES_REQUESTED** [review]

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java (hunk 9 above)
Comment (cruzach) [reply packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:297]: The only part of BillingResult we're ever interested in is the response code. Although this is _most likely_ equivalent for both queries (INAPP and SUBS), it's potentially buggy since maybe we could get a `SERVICE_DISCONNECTED` or `SERVICE_TIMEOUT` in one query and not the other. Unlikely, but possible, and if that were to happen the current code would return the purchases it _did_ get, and ignore the error (or vice versa- ignore the good purchases, and return an error).

So, yes the old code could have hidden response codes we should've surfaced, and we should probably make it respond consistently in all cases, so maybe the best thing to do is aggregate from the BillingResults:

- If all are OK, pass any one of them (doesn't matter which, all we're after is responseCode)
- If one is NOT OK, pass that one
- if both are NOT OK, pass either one

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java (hunk 4 above)
Comment (ide) [reply packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java]: APIs that require you to call method A before method B while letting you write B(); A(); are usually bad, to put it simply. Lifecycles are some of the worst parts of APIs.

Your proposal to accept the purchase token instead of the SKU structurally fixes this by making B() take the result of A(), forcing the programmer to write code in that order.

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java (hunk 9 above)
Comment (ide) [reply packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java]: I think we should expose partial failures, not hide them. Exactly what you proposed.

File: packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java [hunk 10]
```diff
@@ -253,27 +277,57 @@ public int getBillingClientResponseCode() {
...
     Runnable queryToExecute = new Runnable() {
+      @NonNull
+      private BillingResult aggregateBillingResults(@NonNull Set<BillingResult> billingResults) {
+        for (BillingResult result: billingResults) {
+          if (result.getResponseCode() != BillingResponseCode.OK) {
+            return result;
+          }
+        }
+        return billingResults.iterator().next();
+      }
```
Comment (ide) [inline packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java:293]: Move this out to be a private method of the BillingManager since the method doesn't need to close over any variables. When we convert this code to Kotlin it will make the Runnable nicer to write (Kotlin has special syntactic sugar for classes with only one method so they can be written more like JS callbacks).

**Review by ide — COMMENTED** [review]
Looks good, just the change to requiring the purchase token instead of the old SKU.

If we don't want the JS API to break, we could implement a backwards compatible API that gets the purchase token in our JS code and passes it in. So we'd break the JS–native interface but not the public API.

**Comment by cruzach** [comment]
> If we don't want the JS API to break, we could implement a backwards compatible API that gets the purchase token in our JS code and passes it in. So we'd break the JS–native interface but not the public API.

Probably going to make other breaking changes to the API for this release*, so I don't think making the backwards-compatible API is worth it, and just changed the API to accept `purchaseToken` directly

*- like changing the parameter for `getPurchaseHistoryAsync` to an object so we don't have `getPurchaseHistoryAsync(false)`. The term 'refresh' also doesn't accurately communicate what the difference in behavior will be. `true` will return your most recent purchase history, whereas `false` will only return your currently owned items or subscriptions

**Review by ide — APPROVED** [review]

**Comment by rikkster** [comment]
Hello! I using expo-in-app-purchases v11.0.1 but google console says me: “This app uses an unsupported version of Play Billing. To publish it, update the Payments library to version 3 or later”. I’m confused…How can I get billing to work? P.S.: sorry for my bad eng

**Comment by vladtihonovskiy** [comment]
@rikkster Did you find a solution?

**Comment by darrylyoung** [comment]
Hi, @cruzach. I'm a little confused here — the [CHANGELOG](https://github.com/expo/expo/blob/sdk-42/packages/expo-in-app-purchases/CHANGELOG.md) for `expo-in-app-purchases` mentions changes to `purchaseItemAsync` and how it no longer accepts the old SKU as an optional second argument but the [docs](https://docs.expo.dev/versions/latest/sdk/in-app-purchases/) page still shows the old API (with `oldItem` as an optional second argument). Which is correct? Looking at my code, after upgrading to `11.0.1` I see `purchaseItemAsync(itemId: string, oldPurchaseToken?: string | undefined)` shown when I hover `purchaseItemAsync` so I'm guessing it's just the docs page that's outdated, right?

I'm currently running `expo-in-app-purchases` version `10.2.0` and very close to releasing a product but I'm not sure if I should update to `11.0.1` first, with the difference in the documentation mentioned above — I'd like to be 100% sure as I've already thoroughly tested IAP and would prefer not to rock the boat so close to release. Any suggestions? It'd be great if there were upgrade guides when packages get major version bumps with breaking changes. I understand that this takes time, though.

Thanks!

**Comment by cruzach** [comment]
@darrylyoung yeah, this is a limitation of docs for libraries that aren't included in the SDK: docs page doesn't refer to a specific version of `expo-in-app-purchases`. But, it does seem like the one for the most recent SDK should reflect the documentation for the most recent version of `expo-in-app-purchases`, so I'll update it. You are correct in assuming the docs are out of date, and you should rely on the changelog and TS doc blocks instead :) 

You will not be able to release on Google Play if you use v10.2.0, so imo yes you should update

**Comment by darrylyoung** [comment]
Great. Thanks for that, @cruzach. I'll update now.

**Comment by devGuerra** [comment]
i receive this error in sdk 43 with expo-purchases 12.0.0 :/

**Comment by JB-CHAUVIN** [comment]
Same goes for me, how can we update ?

**Comment by wyeo** [comment]
Hi @cruzach, 
Do you have a recommendation related to the two last comments ?

Thanks

**Comment by cruzach** [comment]
If by "this error" you mean Google Play is telling you you must upgrade to V3, then I think you should reach out to Google support. You can inspect the sourcecode after this change- it uses `com.android.billingclient:billing:4.0.0`. Maybe you have another binary in a different track in your Google Dev Console that still uses an older version?

**Comment by willmac997** [comment]
Removing `<uses-permission android:name="com.android.vending.BILLING" />` from AndroidManifest.xml solved the 'update to version 3 or later' issue for me

According to [https://developer.android.com/google/play/billing/migrate#remove](https://developer.android.com/google/play/billing/migrate#remove
)> The Google Play Billing Library embeds the com.android.vending.BILLING permission inside its manifest. It is no longer necessary to explicitly add this permission inside your app's manifest.
