### PR TITLE
[modules][Android] Fix `JSCRuntime destroyed with a dangling API object`

### LINKED ISSUE #19221: Expo bare-workflow app is crashing when expo-localization is imported
### Summary

My app was crashing all the time, when i was reloading the app. And sometimes it also crashed randomly. I looked into the deivce log with flipper to get more information and there was this error everytime i reload the app:

> /root/react-native/ReactCommon/jsi/JSCRuntime.cpp:395: virtual facebook::jsc::JSCRuntime::~JSCRuntime(): assertion "objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object"" failed

I tryed everything to get the reason for this error and after a month i found it. I was importing `expo-localization`, because i used it before i switched to react-native-localize. I imported it like this:
`import * as Localization from "expo-localization"`

And this line, is making these crashed. I created a new Expo bare-worklfow project with SDK 46, added expo-localization to it and i imported the package at the top of app.js again like `import * as Localization from "expo-localization"`. After i run npm run android, everything worked fine, as before, but when i reload the app, for example through the console, the app is crashing evertime.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.12.0 - F:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.1 - F:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: bare

"dependencies": {
    "expo": "~46.0.9",
    "expo-localization": "^13.1.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.5",
    "react-native-web": "~0.18.7"
  }

### Minimal reproducible example

Run > `npx create-expo-app --template` > choose "Blank (Bare)"
Go into project folder and run `npm i expo-localization`
Import expo-localization like this `import * as Localization from "expo-localization"` in App.js
Run `npm run android`. After the app loaded, reload the app 1 or 2 times.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes https://github.com/expo/expo/issues/19221.

# How

In the current memory modal, all of our JSI references are cleared when GC runs through java unused objects. It turns out that is not the best flow, because JSC has an assertion that checks if all references were cleared. So we have to remove dangling references before the JSC runtime fully deallocates. 

# Test Plan

- bare-expo with JSC and Heremes ✅

### CODE REVIEW

File: packages/expo-modules-core/android/src/main/cpp/ExpoModulesHostObject.h [hunk 1]
```diff
@@ -20,6 +20,8 @@ class ExpoModulesHostObject : public jsi::HostObject {
 public:
   ExpoModulesHostObject(JSIInteropModuleRegistry *installer);
 
+  virtual ~ExpoModulesHostObject();
```
Comment (Kudo) [inline packages/expo-modules-core/android/src/main/cpp/ExpoModulesHostObject.h:23]:
```suggestion
  ~ExpoModulesHostObject() override;
```
nit 😅

File: packages/expo-modules-core/android/src/main/cpp/JavaScriptModuleObject.h [hunk 2]
```diff
@@ -104,6 +104,8 @@ class JavaScriptModuleObject : public jni::HybridClass<JavaScriptModuleObject> {
   public:
     HostObject(JavaScriptModuleObject *);
 
+    virtual ~HostObject();
```
Comment (Kudo) [inline packages/expo-modules-core/android/src/main/cpp/JavaScriptModuleObject.h:107]:
```suggestion
  ~HostObject() override;
```
nit 😅

**Review by Kudo — APPROVED** [review]
🔥 nice fix 🔥

**Review by tsapeta — APPROVED** [review]

**Comment by Kudo** [comment]
@gasolin the `expo@46.0.16` should have this fix.
