### PR TITLE
[secure-store] prevent losing data after ejecting

### LINKED ISSUE #11272: SecureStore variables not accessible after ejecting
### Summary of Issue 
When ejecting an app, retrieving saved variables from the SecureStore are all undefined. The app is using the same developer credentials, certificates, app ids etc. 

```
const item = await SecureStore.getItemAsync("stored_value_from_before_eject");
// item === undefined
```

**Use case**: Store refresh token and authentication token in secure store. User authenticates with app. Ejected version of the app is uploaded. User is logged out.

### Environment

Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18
      expo-secure-store: ~9.2.0
    npmGlobalPackages:
      expo-cli: 4.0.8
    Expo Workflow: bare

### Reproducible Demo

```javascript
import React, { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as SecureStore from "expo-secure-store";

const App = () => {
  const [value, setValue] = useState<string | null>();

  useEffect(() => {
    const init = async () => {
      const item = await SecureStore.getItemAsync("stored_value");
      setValue(item);
    };
    init();
  }, []);

  const storeItem = async () => {
    setValue("Stored value");
    await SecureStore.setItemAsync("stored_value", "Stored value");
  };

  return (
    <View style={{ margin: 80 }}>
      <Pressable onPress={storeItem}>
        <Text>Store item</Text>
      </Pressable>
      <Text>{value ? `Received value: ${value}` : "No value found"}</Text>
    </View>
  );
};
 
export default App;
```
### Steps to Reproduce
I am not sure if there is a way of replicating this on your local machine. 
1. Upload an app using expo manned workflow (using the above code for main app file).
2. Using the app store a value in the secure store.
3. Eject the app and upload a new version of the app.
4. Observe the value is now undefined when starting the updated app.

### Expected Behavior vs Actual Behavior
Value is undefined, it should be "Stored value". 

### Comment
I am wondering if there is some configuration needed by secure store that becomes undefined by the eject process. For example in expo-notification I need to provide the experienceId when getting token, while in managed workflow it gets the experienceId from the manifest file. Is there maybe something similar happening here, where it sets something similar to the  experienceId in SecureStore, which is undefined in the bare workflow, so I don't get access to my secure store (or not the same container at least). For example if changing the "owner" field in the app.json in the managed workflow, you get the same problem. Is there anything you could pass as part of the options of SecureStore.getItemAsync to fix this?

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/11272 and https://github.com/expo/expo/issues/2089

`expo-secure-store` data would be gone after ejecting, because we had scoped this data by experience in standalone apps. The method for fixing this is different on Android and iOS (unfortunately).

# How

## Android
Previously there was no "Scoped" securestore module on Android, but it used a scoped version of SharedPreferences under the hood, which meant once you ejected and used an unscoped SharedPreferences file, it was empty! 

Now, we pass the base context to `SecureStoreModule` **in standalone apps only**, and migrate the old (scoped) SecureStore SharedPreferences file over key-by-key on app launch. Otherwise, the android implementation behaves the same way it did before.

## iOS
Previously, SecureStore on iOS would scope data by prefixing the user-provided key with `@username/slug-` by overriding the `validatedKey` method. Since there isn't a great option in KeychainServices for migrating all those keys to new ones _without_ the prefix, I opted to:

- only add the scope prefix in `validatedKey` override when running in the expo client (so now all get/set/delete key operations for SecureStore in standalone apps are not "Scoped")
- to support previously set values, override the `_getValueWithKey` method so that it:
  - looks for key
    - if it finds it, return associated value
  - look for legacy key by prefixing provided key with `@username/slug-`
    - if it finds it, save it under the **unscoped** key
    - if we successfully migrated the key, delete the legacy key/value from keychain storage
    - return associated value
  - if no values exist for the scoped and unscoped keys, return the search error response from the original query (for the **unscoped** key)

We should be able to remove this code after a while, once there's very little chance anyone would upgrade directly from SDK 39 or lower to the newest SDK (so maybe 45 or 46?)

# Test Plan

Tested manually with android shell app, existing data is carried over when installing a bare version of an app over a managed version. 

iOS I tested this primarily in the Expo client ([disabled this check to do so](https://github.com/expo/expo/pull/11309/files#diff-13e44cde5f8302acbcf3f00c14ca5da26bc06f67ce373baf47a2918b89aa6f51R58)) by going from a versioned experience to an unversioned (using this new code in the unversioned experience) and making sure the old values were gettable. Was running into problems building a local iOS shell app but will continue to investigate

### CODE REVIEW

File: android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ScopedSecureStoreModule.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+          Log.e("E_SECURESTORE_WRITE_ERROR", "Could not transfer SecureStore data to new storage.");
+        }
+      }
+    }
+  }
+
+  protected SharedPreferences getScopedSharedPreferences() {
+    return mScopedContext.getSharedPreferences(SHARED_PREFERENCES_NAME, Context.MODE_PRIVATE);
+  }
+}
```
Comment (bbarthec) [inline android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ScopedSecureStoreModule.java:52]:
```suggestion
}

```

File: ios/Exponent/Versioned/Core/UniversalModules/EXScopedSecureStore.m [hunk 2]
```diff
@@ -30,7 +39,70 @@ - (NSString *)validatedKey:(NSString *)key {
     return nil;
   }
 
-  return [NSString stringWithFormat:@"%@-%@", _experienceId, key];
+  return _isStandaloneApp ? key : [NSString stringWithFormat:@"%@-%@", _experienceId, key];
+}
+
+// We must override this method so that items saved in standalone apps on SDK 39 and under,
```
Comment (bbarthec) [inline ios/Exponent/Versioned/Core/UniversalModules/EXScopedSecureStore.m:45]:
```suggestion
// We must override this method so that items saved in standalone apps on SDK 39 and below,
```

File: ios/Exponent/Versioned/Core/UniversalModules/EXScopedSecureStore.m [hunk 3]
```diff
@@ -30,7 +39,70 @@ - (NSString *)validatedKey:(NSString *)key {
...
+                                        error:&searchError];
+  if (data) {
+    NSString *value = [[NSString alloc] initWithData:data
+                                            encoding:NSUTF8StringEncoding];
+    return value;
+  }
+  return nil;
+}
+
+- (void)migrateValue:(NSString *)value fromScopedKey:(NSString *)scopedKey toNewKey:(NSString *)newKey withOptions:(NSDictionary *)options
```
Comment (bbarthec) [inline ios/Exponent/Versioned/Core/UniversalModules/EXScopedSecureStore.m:91]:
```suggestion
- (void)migrateValue:(NSString *)value
       fromScopedKey:(NSString *)scopedKey
            toNewKey:(NSString *)newKey
         withOptions:(NSDictionary *)options
```

**Review by bbarthec — APPROVED** [review]
Looks ok 👍 
We need a `CHANGELOG` entry though 😉

**Comment by mrtnrst** [comment]
Out of curiosity, what is the limitation to needing to update to ExpoSDK 40 _before_ ejecting in order to not lose the keys? And could this work be back ported to other versions? Thanks!

**Comment by cruzach** [comment]
@mrtnrst there's a lot of other changes being made in SDK 41 to make the process of going from a managed app to a bare app much smoother (so backporting this one particular change would be just a small piece of the puzzle). 

The later of an SDK you eject on, the better your experience will be with ejecting (and upgrading your SDK should be almost _too_ easy at this point, so that's our reccomendation)

**Comment by cruzach** [comment]
@Zakrevskijj please read the comments above- this fix will be included in SDK 41 (not SDK 40)

**Comment by agoqui** [comment]
Hello @cruzach , i have an Bare Workflow react-native app, i migrate  my app from sdk37 to sdk41 but unfortunately , the migration don't work. I don't find your code on the project (ios or android files)

I have installed the react-native-unimodules and make the good configurations but when i launch the app,  i loose my old expo-secure-store key (_enperiencdID-user-token ) . 

Have you an idea how i can integrate this code? please 🙏 
thanks

**Comment by cruzach** [comment]
This is only relevant if you're moving from managed to bare, so if your app was always bare then it doesn't matter

If this code isn't in your project, then you likely don't have the correct version of `expo-secure-store` installed

**Comment by agoqui** [comment]
Thank you

**Comment by agoqui** [comment]
Just for information, for my bare project, to migrate from sdk37, i fix the lost of expo-secure-store (ios) on patch the `ios/EXSecureStore/EXSecureStore.m`

With patch-package lib, i make the migration with the code make here.
Thks for your answer.

**Comment by robsonbbs** [comment]
> We should be able to remove this code after a while, once there's very little chance anyone would upgrade directly from SDK 39 or lower to the newest SDK (so maybe 45 or 46?)

@cruzach This code was removed? I updated my app recently from expo 40 to expo 42, then I ran `expo run:android`, build it using `eas build -p android --profile production`, and release it on Play Store. Now users are complaining about login because apparently credentials were lost.

**Comment by DB1703** [comment]
Hi @cruzach, I hope to donpt disturb, but i have a similar issue, when testing an app with TestFlight with SDK 51 installed on top of the App Store app with SDK 41, all data is wiped out. On the changelog it says: "On iOS, keys and their associated data will be migrated whenever you call `getItemAsync` on that key. This means that any keys you don't `get` while on SDK 41 will **not** be migrated."
So i would have to implement this [fix](https://github.com/expo/expo/pull/11309#issue-761468108) ? I have a bare managed workflow, i'm not completely sure how to implement it also.
