### PR TITLE
[docs] Fix Rotation Behavior of Inner Accordion on Expand/Collapse

### LINKED ISSUE #31218: [docs] The inner accordion icon does not change when it is expanded or closed
### Summary

https://docs.expo.dev/workflow/overview/#key-concepts

For example, the accordions shown in the first level are working fine. When the first-level accordions are expanded or closed, the icons change accordingly, but the second-level accordions nested inside the first-level accordions don't display this behavior, i.e., the icons don't change according to the state (whether it is open or closed) of the accordion.

Ideally, both types of accordions should display the same behavior.

### Link to the related docs page

https://docs.expo.dev/workflow/overview/

### Anything else?

I am happy to take up this issue.

### PR DESCRIPTION
**Pull request by sharmayatendra**
This PR addresses an issue with the inner accordion where the rotation indicator (Triangle Icon) fails to update its state when the accordion is expanded or collapsed. The fix ensures that the rotation correctly reflects the open or closed state of the accordion, improving the overall user experience and visual consistency.

# Why

I observed the issue on https://docs.expo.dev/workflow/overview/ which doesn't look good and gives the inner intuition to the user that accordion is already expanded.
Relevant issue link: [issue-31218](https://github.com/expo/expo/issues/31218)

# How

Running the project locally first and following the steps whatever was mentioned in the contributing guideline.I fixed this by adding the css for rotation to happen based upon closest details element. 

# Test Plan

Before: Even if inner accordion is not open its triangular icon seems representing its open which is bit confusing.
---
image

After: Triangular icon in correct state and representing its not open & opened respectively.
---
image
image

## Miscellaneous

- Also improves the setter function name used in the component

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: docs/ui/components/Collapsible/index.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ const Collapsible: ComponentType<CollapsibleProps> = withHeadingManager(
     open = false,
   }: CollapsibleProps & HeadingManagerProps) => {
     // track open state so we can collapse header if it is set to open by the URL hash
-    const [isOpen, setOpen] = useState<boolean>(open);
+    const [isOpen, setIsOpen] = useState<boolean>(open);
```
Comment (Simek) [inline docs/ui/components/Collapsible/index.tsx:43]: What was the intent with the rename? This seems unrelated to the issue.

**Review by Simek — APPROVED** [review]
Thanks for the correction! 👍 

Fixes #31218

File: docs/ui/components/Collapsible/index.tsx (hunk 1 above)
Comment (sharmayatendra) [reply docs/ui/components/Collapsible/index.tsx:43]: Mostly the destructured value we see in codebase in form of `[value, setValue]` so thought of improving it here itself since it lies in the same component. If still seems unrelatable I can revert it. Please advise.

Thanks

Comment (Simek) [reply docs/ui/components/Collapsible/index.tsx:43]: Thanks for the context! We can leave it as-is, since we have no strict patterns defined on naming the state methods.
