### PR TITLE
[UM] Fix BOOL handling in ViewManager

### LINKED ISSUE #5049: [UM] Incorrect `Bool` var handling
The same situation as with #4862.

https://github.com/expo/expo/blob/f6a81280ceb974de1cffdf13227752018f6aa303/packages/%40unimodules/core/ios/UMCore/UMViewManager.m#L103 - we don't handle the situation when `BOOL` variables are stored as a `signed char`

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #5049

### CODE REVIEW

File: packages/@unimodules/core/ios/UMCore/UMViewManager.m [hunk 1]
```diff
@@ -100,12 +100,22 @@ - (void)updateProp:(NSString *)propName withValue:(id)value onView:(UIView *)vie
...
+    // getArgumentTypeAtIndex can return _C_BOOL (when `bool`) or _C_CHR (when `signed char`)
+#if OBJC_BOOL_IS_BOOL
     if ([methodSignature getArgumentTypeAtIndex:2][0] == _C_BOOL) {
       // We need this intermediary variable, see
       // https://stackoverflow.com/questions/11061166/pointer-to-bool-in-objective-c
       BOOL retainedValue = [value boolValue];
       [invocation setArgument:&retainedValue atIndex:2];
     }
+#else // BOOL is represented by `signed char`
+    if ([methodSignature getArgumentTypeAtIndex:2][0] == _C_CHR){
```
Comment (ide) [inline packages/@unimodules/core/ios/UMCore/UMViewManager.m]:
```suggestion
    if ([methodSignature getArgumentTypeAtIndex:2][0] == _C_CHR) {
```

**Review by ide — APPROVED** [review]

**Review by sjchmiela — APPROVED** [review]
see James's comment, apart from that 👍
