### PR TITLE
[image-picker] bump Android-Image-Cropper dependency

### LINKED ISSUE #43396: Android-Image-Cropper that is being used by expo-image-picker still has the CropImageActivity vulnerability
### Minimal reproducible example

build the app

### Steps to reproduce

build the app then check: /android/app/build/intermediates/merged_manifest/debug/processDebugMainManifest/AndroidManifest.xml

android-image-picker needs to be bumped to 4.7.0 that adds validation

https://github.com/CanHub/Android-Image-Cropper/releases/tag/4.7.0

### Environment

```text
just need expo-image-picker
```

### Expo Doctor Diagnostics

```text
not an issue with expo but expo-image-picker deps
```

### PR DESCRIPTION
**Pull request by vonovak**
# Why

This PR updates the Android-Image-Cropper dependency to the latest version to close #43396

# How

Updated the `com.vanniktech:android-image-cropper` dependency from version 4.6.0 to 4.7.0

# Test Plan

- bare expo

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by vonovak** [comment]
* **#43433** <a href="https://app.graphite.com/github/pr/expo/expo/43433?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/43433?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt [hunk 1]
```diff
@@ -61,12 +61,19 @@ private fun getTypeFromFileUrl(url: String): String? {
...
+  return FileProvider.getUriForFile(context, context.packageName + ".ImagePickerFileProvider", this)
+}
+
 /**
  * Convert this [File] to [Uri] that might be accessed by 3rd party Activities, eg. by camera application
  */
 internal fun File.toContentUri(context: Context): Uri {
   return try {
-    FileProvider.getUriForFile(context, context.packageName + ".ImagePickerFileProvider", this)
+    this.toContentUri(context)
```
Comment (intergalacticspacehighway) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt]: should it be `this.getContentUri` here?

**Review by intergalacticspacehighway — APPROVED** [review]
