### PR TITLE
[android] Fix scopedContext unavailable in Sweet API modules

### LINKED ISSUE #18760: Android Failing to read uri of photo from imagepicker (newly taken or from photos)
### Summary

Suddenly, possibly after upgrading to SDK 46, I am not sure because immediately after upgrading I was mostly working with iOS, my app has been unable to read the uri of new images added via expo-image-picker. I get an error like the following:

```error
Location 'file:///data/user/0/host.exp.exponent/cache/ImagePicker/89003e23-afbb-4b5e-a63e-d263854d739f.jpeg' isn't readable.
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:21:23 in moduleName.methodInfo.name
at node_modules/expo-file-system/build/FileSystem.js:75:17 in copyAsync
at http://192.168.0.15:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in copyAsync
```

### What platform(s) does this occur on?

Android

### Environment

   System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 20210102.202219.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@lastof/android-imagepicker-uri-unreadable

### PR DESCRIPTION
**Pull request by aleqsio**
Fixes: https://github.com/expo/expo/issues/18760

# Why

Trying to access image from ImagePicker via FileSystem results in Location 'file:///…' isn't readable. error.

Appears to be an issue with the scoping of cache files in Expo Go only).

File name looks like this in SDK 45: `file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540keith-kurak%252Fandroid-imagepicker-uri-unreadable/ImagePicker/4151a827-6c11-4d2d-ab5e-2a4015e8a29c.jpg`

Looks like this in 46: `file:///data/user/0/host.exp.exponent/cache/ImagePicker/48faff81-88bd-4578-86c0-b885f1364c3a.jpeg`

This URI is inaccessible to expo-file-system due to logic defined in `ScopedContext.kt `

This logic prevents activites to access each other's cache as an internal permissions mechanism for virtual, separate experiences in one android app in Expo go.

---
The same `context.cacheDir` is used in 3 modules written in the new API:
- Clipboard
- ImageView
- ImagePicker

However, calendar only uses it as internal cache and cannot save to scoped cache due to the dir being allowlisted in a static xml file. As such it was not changed.

# How

With @lukmccall we attempted to come up with a fix by first passing scoped context to the new style modules. Hard to do, as we would need to make `ScopedContext` inherit from `ReactApplicationContext`, which would be doable if we moved `ScopedContext` only to versioned code (large refactor).

We could make the modules use the ScopedContext directly, but this breaks module contract (they should not rely on the fact they they are scoped (from what I understand).

Instead, we add a new filesystem internal module `ScopedDirectoriesModule` that is instantiated by the old API and is providing scoped paths to modules with new API.

```
  private val scopedDirectories: ScopedDirectories
    get() = appContext.scopedDirectories?.scopedDirectories ?: throw ModuleNotFoundException("ScopedDirectories")
```

This is a stopgap fix until we can come up with a clean way to handle scope in new style modules in the future.

# Test Plan

We can't add tests to BareExpo as it does not contain the Scoping logic. @lukmccall any ideas?
[x] Test manually if the original issue is fixed in Expo Go android for imagepicker. (tested using expo-go built locally and a custom project, simillar to https://snack.expo.dev/@aleqsio/expo-directories-internal-module-test) On main it fails to find experience name in cache dir, on this branch it works as expected.
[x] Test manually if the original issue is fixed in Expo Go android for all 2 modules.
[] Test manually if IOS is unaffected.
[x] Test manually if android standalone/bare is unaffected for all 2 modules.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md). - should not require doc changes
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-modules-core/android/src/main/java/expo/modules/interfaces/filesystem/ScopedDirectories.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+        return Objects.hash(cacheDir, filesDir);
+    }
+
+    @Override
+    public String toString() {
+        return "ScopedDirectories[" +
+                "cacheDir=" + cacheDir + ", " +
+                "filesDir=" + filesDir + ']';
+    }
+}
```
Comment (lukmccall) [inline packages/expo-modules-core/android/src/main/java/expo/modules/interfaces/filesystem/ScopedDirectories.java:43]:
```suggestion
data class ScopedDirectories(val cacheDir: File, val filesDir: File)
```
By using Kotlin here, we get the same functionality in just one line of code.

**Review by lukmccall — APPROVED** [review]
Everything looks great. I think that we should avoid using the "scoped" word here. For outside developers, it doesn't make sense. That word is only used internally. So the public interface `ScopedDirectoriesModuleInterface` should be called `DirectoriesModuleInterface` or even `DirectoriesInterface`. Other occurrences of the "scoped" word also have to be removed.

**Review by lukmccall — CHANGES_REQUESTED** [review]
Sorry, I didn't mean to approve that

File: packages/expo-modules-core/android/src/main/java/expo/modules/interfaces/filesystem/ScopedDirectories.java (hunk 1 above)
Comment (aleqsio) [reply packages/expo-modules-core/android/src/main/java/expo/modules/interfaces/filesystem/ScopedDirectories.java:43]: Sorry, still forgetting that I can mix and match kotlin and java and just followed the lang used in the template module I was using. This is actually codegen from Java record classes that is not yet in this Java version (i think), but kotlin data classes work great!

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt [hunk 2]
```diff
@@ -132,6 +133,13 @@ class AppContext(
   val filePermission: FilePermissionModuleInterface?
     get() = legacyModule()
 
+  /**
+   * Provides access to the scoped directories from the legacy module registry.
+   */
+  val directories: DirectoriesModuleInterface?
+    get() = legacyModule()
+
+
```
Comment (lukmccall) [inline packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt:142]:
```suggestion
```

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt [hunk 3]
```diff
@@ -65,8 +69,9 @@ internal class MediaHandler(
 
   private suspend fun handleVideo(
     sourceUri: Uri,
-  ): ImagePickerResponse.Single.Video {
-    val outputFile = createOutputFile(context.cacheDir, ".mp4")
+  ): ImagePickerResponse.Single.Video
+  {
```
Comment (lukmccall) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt:73]:
```suggestion
  ): ImagePickerResponse.Single.Video {
```

**Review by lukmccall — APPROVED** [review]

File: packages/expo-modules-core/CHANGELOG.md [hunk 4]
```diff
@@ -33,6 +33,7 @@
 - Add the `RegisterActivityContracts` component to register all of activity result contracts on Android. ([#19180](https://github.com/expo/expo/pull/19180) by [@lukmccall](https://github.com/lukmccall))
 - Improves JSI/JNI type conversion to support complex function arguments on Android. ([#19120](https://github.com/expo/expo/pull/19120) & [#19094](https://github.com/expo/expo/pull/19094) by [@lukmccall](https://github.com/lukmccall))
 - Using JSI instead of the bridge to call native methods also on legacy modules on iOS. ([#19209](https://github.com/expo/expo/pull/19209) by [@lukmccall](https://github.com/lukmccall))
+- Added a `DirectoriesModule` to android as a temporary solution to fix cache directories being incorrect in new Sweet API modules.
```
Comment (tsapeta) [inline packages/expo-modules-core/CHANGELOG.md]:
```suggestion
- Added a `DirectoriesModule` to Android as a temporary solution to fix cache directories being incorrect in new Sweet API modules. ([#19205](https://github.com/expo/expo/pull/19205) by [@aleqsio](https://github.com/aleqsio))
```

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt [hunk 5]
```diff
@@ -151,6 +152,12 @@ class AppContext(
   val filePermission: FilePermissionModuleInterface?
     get() = legacyModule()
 
+  /**
+   * Provides access to the scoped directories from the legacy module registry.
+   */
+  val directories: DirectoriesModuleInterface?
```
Comment (tsapeta) [inline packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt:158]: Since the directories module has only one thing, maybe it's better to get these directories right away from here instead of then referring to it as `directories.directories` 😅 
I would also think about changing the name to "app directories"; "directories" is too vague.

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/DirectoriesModule.kt [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+
+/*
+New Sweet API modules don't have an easy way to access scoped context. We can't initialize them with scoped context as they need a ReactApplicationContext instead.
+We can't make ScopedContext inherit from ReactApplicationContext as that would require moving ScopedContext to versioned and a large refactor.
+
+This module is a stopgap solution to provide modules with a way to access ScopedContext directories using the filesystem module, only for our internal modules.
+ */
+
+// The class needs to be 'open', because it's inherited in expoview
+open class DirectoriesModule(private val context: Context) : DirectoriesModuleInterface, InternalModule {
```
Comment (tsapeta) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/DirectoriesModule.kt:16]: I'd also change the module name to `AppDirectoriesModule`

File: packages/expo-file-system/CHANGELOG.md [hunk 7]
```diff
@@ -8,6 +8,8 @@
 
 ### 🎉 New features
 
+- Added `DirectoriesModule` to expo-file-system on android as a temporary solution to fix cache directories being incorrect in new Sweet API modules. ([#19205](https://github.com/expo/expo/pull/19205) by [@aleqsio](https://github.com/aleqsio))
```
Comment (tsapeta) [inline packages/expo-file-system/CHANGELOG.md:11]:
```suggestion
- Added `DirectoriesModule` to expo-file-system on Android as a temporary solution to fix cache directories being incorrect in new Sweet API modules. ([#19205](https://github.com/expo/expo/pull/19205) by [@aleqsio](https://github.com/aleqsio))
```

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt (hunk 5 above)
Comment (tsapeta) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt:158]: Yeah, `appContext.cacheDirectory` and `appContext.documentDirectory` would be great 😉 (for consistency let's use the same names as FileSystem module)

File: packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt [hunk 8]
```diff
@@ -151,6 +154,24 @@ class AppContext(
   val filePermission: FilePermissionModuleInterface?
     get() = legacyModule()
 
+  /**
+   * Provides access to the scoped directories from the legacy module registry.
+   */
+  private val appDirectories: AppDirectoriesModuleInterface?
```
Comment (aleqsio) [inline packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt:160]: Not sure if this should be private (as this currently can be used for nothing else then the properties surfaced below)

Comment (lukmccall) [reply packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/AppContext.kt:160]: Let's leave it private for now ;)

**Review by tsapeta — APPROVED** [review]
