### PR TITLE
[expo-camera][Android] Fix adding/removing children from CameraPreview

### LINKED ISSUE #3495: Camera component stops working on Android after a view is rendered on top of it. ANDROID- Expo 32
### Environment

  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.0 - ~/.nvm/versions/node/v9.10.0/bin/node
      Yarn: 1.9.4 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.10.0/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.10.1

### Steps to Reproduce

1. Open a screen with a Camera component from Expo.
2. Click a button to show a View on Top of the camera.
3. The Camera stops working.

### Expected Behavior

If I render a view on top of the Camera component (actually as its child), the camera should keep working.

### Actual Behavior

On Android, if I have the camera component on a screen, and then I render a view on top of it, the camera stops working. It just shows a black screen. Even if I close the View, the camera stays broken. It only comes back to life if I unmount the screen and mount again (using the goBack function with react navigation in my case).

**NOTE THAT THIS HAPPENS ONLY ON ANDROID**

on iOS, it works flawless.
(Write what happened. Add screenshots!)

### Reproducible Demo

https://snack.expo.io/@otaviogaiao/camera-error-expo

Obviously you need an Android phone to reproduce the issue.

I used a Xiaomi redmi note 3, with Android 6.

EDIT: just tried on a Samsung Galaxy S9+ with Android 9 and the same problem occurred.

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves #3495

# How

Previously upon react child added to camera component, preview (Android TextureView) was re-added as a first child to container, but that was causing texture destruction or something similar and newly added preview was not showing actual preview anymore.
Solution is not to remove preview view but to rearrange all children order in camera container.
Side thought: IMO camera should be leaf component and not container.

# Test Plan

You can dynamically add/remove children from `CameraPreview`.
https://snack.expo.io/@barthec/LWdpdG

### CODE REVIEW

**Comment by sjchmiela** [comment]
Have you considered removing ability to add native children to `CameraView` in favor of doing in JS:
```jsx
  render() {
    return (
      <View style={[styles.container, this.props.style]}>
        <ExpoCameraView style={StyleSheet.absoluteFill} />
        {this.props.children}
      </View>
    );
  }
```

**Review by mczernek — APPROVED** [review]

**Comment by bbarthec** [comment]
@sjchmiela please see this PR description. I wish that camera becomes leaf component, but that would cause breaking change and I would rather do that in #3612 .

File: packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java [hunk 1]
```diff
@@ -162,11 +164,34 @@ public void requestLayout() {
...
+      if (i == 0 && childView == this.getView()) {
+        // preview is already first in children list - do not reorder anything
+        return;
+      }
+      if (childView != this.getView()) {
+        childrenToBeReordered.add(childView);
+      }
+    }
+
+    for (View childView: childrenToBeReordered) {
```
Comment (tsapeta) [inline packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java]:
```suggestion
    for (View childView : childrenToBeReordered) {
```

File: packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java [hunk 2]
```diff
@@ -162,11 +164,34 @@ public void requestLayout() {
...
+      this.bringChildToFront(childView);
```
Comment (tsapeta) [inline packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java]:
```suggestion
      bringChildToFront(childView);
```

File: packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java [hunk 3]
```diff
@@ -8,6 +8,7 @@
 import android.net.Uri;
 import android.os.Build;
 import android.os.Bundle;
+import android.view.TextureView;
```
Comment (tsapeta) [inline packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java]:
```suggestion
```

**Review by tsapeta — CHANGES_REQUESTED** [review]

**Comment by sjchmiela** [comment]
Why would it be a breaking change? Is there a noticable difference between putting children inside and next to `<ExpoCameraView />`?

**Comment by bbarthec** [comment]
@sjchmiela it's matter of discussion whether stopping supporting this (examples and community goes this way now):
```javascript
(
  <ExpoCameraView style={[styles.container, this.props.style]}>
    {this.props.children}
  </ExpoCameraView>
);
```
in favour of this:
```javascript
(
  <View style={[styles.container, this.props.style]}>
    <ExpoCameraView style={StyleSheet.absoluteFill}/>
    {this.props.children}
  </View>
);
```
is a breaking change, but for now I will leave it as is.
