### PR TITLE
[video][ios] Fix a race condition causing crashes when deallocating the player

### LINKED ISSUE #29950: [expo-video] Component crashing on unmount
### Minimal reproducible example

Cannot provide min repo as expo video seems to crash the snack as shown in
https://snack.expo.dev/@kimik/765825

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm looking to swap out the existing expo-av video component with the new `expo-video` one, and everything seems to be fine, however my app crashes whenever I unmount the video player.

The issue seems to appear to be with the `release()` functionality, which is called on unmount. I initially thought I should try to release before unmounting as well, but that actually triggered the same issue.

This is code from expo
``` 
/// useReleasingSharedObject()
    useEffect(() => {
        isFastRefresh.current = false;
        return () => {
            // This will be called on every fast refresh and on unmount, but we only want to release the object on unmount.
            if (!isFastRefresh.current && objectRef.current) {
                objectRef.current?.release(); // <--- commenting this out makes it work fine!
            }
        };
    }, []);
    return object;
    ```

The error encoutered is quite non-descriptive, but consistent.

Error: Exception in HostFunction: failed to define internal native state property

```


```
So from what I was able to gather, the` release()` seems to be causing trouble.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - /opt/homebrew/bin/npm
      Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/mihailapuste/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.0.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✖ Check package.json for common issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✖ Check for issues with metro config
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.9.1
  (for more info, run: npm why @expo/config-plugins)
Expected package metro@~0.80.8
Found invalid:
  metro@0.80.5
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.5
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.5
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

Error: Problem validating fields in /Users/mihailapuste/fit52/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

The following scripts in package.json conflict with the contents of node_modules/.bin: lint-staged, tsc.

It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more: https://docs.expo.dev/guides/customizing-metro/
Advice: Update your custom metro.config.js to extend @expo/metro-config.

(node:46223) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@7.6.4 - expected version: 8.0.1
  @react-native-community/netinfo@11.2.1 - expected version: 11.3.1
  @react-native-picker/picker@2.6.1 - expected version: 2.7.5
  expo-notifications@0.27.7 - expected version: ~0.28.9
  react-native-gesture-handler@2.14.1 - expected version: ~2.16.1
  react-native-get-random-values@1.10.0 - expected version: ~1.11.0
  react-native-pager-view@6.2.3 - expected version: 6.3.0
  react-native-reanimated@3.6.2 - expected version: ~3.10.1
  react-native-safe-area-context@4.8.2 - expected version: 4.10.1
  react-native-screens@3.29.0 - expected version: 3.31.1
  react-native-svg@14.1.0 - expected version: 15.2.0
  @babel/core@7.23.9 - expected version: ^7.24.0
  @types/react@18.2.48 - expected version: ~18.2.79
  typescript@5.0.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

### PR DESCRIPTION
**Pull request by behenate**
# Why

We were setting the player item to nil during the deallocation on a thread different than main, this caused KVO related race conditions, which lead to crashes.

Fixes https://github.com/expo/expo/issues/29950

# How

Wrapped the line into `DispatchQueue.main.async` to run on the main queue, did some updates to the code changed in https://github.com/expo/expo/pull/29428 as it's not necessary to create a different queue now.

# Test Plan

Tested in BareExpo and custom test apps in iOS simulator and physical device.

### CODE REVIEW

File: packages/expo-video/ios/NowPlayingManager.swift [hunk 1]
```diff
@@ -182,9 +182,7 @@ class NowPlayingManager: VideoPlayerObserverDelegate {
     }
 
     return await withCheckedContinuation { continuation in
-      fetchMetadataQueue.async {
-        continuation.resume(returning: mediaItem.asset.metadata)
-      }
+      return continuation.resume(returning: mediaItem.asset.metadata)
```
Comment (tsapeta) [inline packages/expo-video/ios/NowPlayingManager.swift:185]: You no longer need to use a continuation, returning `mediaItem.asset.metadata` should just work

File: packages/expo-video/ios/VideoPlayer.swift [hunk 2]
```diff
@@ -86,7 +86,10 @@ internal final class VideoPlayer: SharedRef<AVPlayer>, Hashable, VideoPlayerObse
     observer.cleanup()
     NowPlayingManager.shared.unregisterPlayer(self)
     VideoManager.shared.unregister(videoPlayer: self)
-    pointer.replaceCurrentItem(with: nil)
+
+    DispatchQueue.main.async { [pointer] in
```
Comment (tsapeta) [inline packages/expo-video/ios/VideoPlayer.swift:90]: Add a comment why it's necessary to switch to the main thread, i.e. describe the crash and maybe how to reproduce it

**Review by aleqsio — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by mihailapuste** [comment]
Not certain this addresses the issue found in #29950, as it is still occuring in `expo-video: 1.2.3` https://github.com/expo/expo/issues/29950#issuecomment-2229130654
