### PR TITLE
[media-library] Fix `getAlbumsAsync()` crashing on Android 10

### LINKED ISSUE #9635: [expo-media-library] Invalid column COUNT(*) exception on Android 10.
### Summary of Issue 

I am trying to implement a custom gallery on my app. I am using expo-media-library to get albums. App crashes when `getAlbumsAsync()` called, only in Android 10.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Bare react native project
"expo-av": "^8.4.0",
"expo-media-library": "^8.4.0",
"expo-video-thumbnails": "^4.2.1",
"react-native-unimodules": "^0.10.1",

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

Also i am requesting legacyExternalStorage on my AndroidManifest.xml file.
```
<application  
...
android:requestLegacyExternalStorage="true" 
>
...
</application>
```
Tested devices;
Emulator: Google Pixel 3XL Android 10
Device: Samsung galaxy M31 Android 10

### Reproducible Demo
Just call `getAlbumsAsync()` on android 10 device or emulator. This is how i am getting albums on other api versions.
```
getAlbums = async () => {
    const res = await MediaLibrary.requestPermissionsAsync()
    if (res.granted) {
      MediaLibrary.getAlbumsAsync()
                     .then((albums) => console.log(albums))
                     .catch((err) => console.warn(err)) // not catching any error app directly crashes
    }
  }
``` 

### Steps to Reproduce

Just call `getAlbumsAsync()` on android 10 device or emulator.

### Expected Behavior vs Actual Behavior
Expected: Get albums from that function call.
Actual: App crashes.

I also got the log dump from `adb logcat` you can see from this [link](https://gist.github.com/ahmetbicer/b1b5905503c1bc085fe8f5fdd0e0eea2). You can see in the first lines i requested permissions. java.lang.IllegalArgumentException: Invalid column COUNT(*) in line 11.

Thanks!

### PR DESCRIPTION
**Pull request by barthap**
# Why

Fixes #9635 

Android 10 seems not to support SQL functions (`COUNT(*)`, `GROUP BY` etc.) in `ContentResolver` queries. [[source]](https://stackoverflow.com/questions/60623594/replacement-for-group-by-in-contentresolver-query-in-android-q-android-10-a)

Also, `MediaLibrary.getAlbumsAsync()` did not work properly on Android.

# How

Rewrite some `expo-media-library` methods, which used those statements.

- [x] Fixed `getAlbumsAsync()`. Rewritten method in Kotlin.
- [x] Fixed `getAlbum()`.
- [x] Fixed `MediaLibrary` listener `onChange()` event.
- [x] Other minor fixes.
- [x] Cleanup.

# Test Plan

- [x] Native unit tests
- [x] Test suite
- [x] NCL
- [x] Demo app ran on API level 29+.
- [x] Demo app ran on API level < 29

### CODE REVIEW

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+  private class Album(private val id: String, private val title: String, var count: Int = 0) {
+    fun toBundle(): Bundle {
+      val album = Bundle()
+      album.putString("id", id)
+      album.putString("title", title)
+      album.putParcelable("type", null)
+      album.putInt("assetCount", count)
+      return album
+    }
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt:71]: I think it looks nicer 😅

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+            val album = albums[id] ?: let {
+              val newAlbum = Album(
+                id = id,
+                title = asset.getString(bucketDisplayNameIndex)
+              )
+              albums[id] = newAlbum
+
+              newAlbum
+            }
```
Comment (lukmccall) [inline packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt:47]:
```suggestion
            val album = albums[id] ?: Album(
              id = id, 
              title = asset.getString(bucketDisplayNameIndex)
             ).also {
            	 albums[id] = it
             }
```
I'm not sure how the correct formatting should look like here 😅

Comment (barthap) [reply packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt:47]: It can be even nicer ;) Formatting looks ok, possibly _also_ block could be inlined.

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt (hunk 1 above)
[the remark this answers is not in the document]
Comment (barthap) [reply packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt:71]: Much nicer ;) I'm just stuck with thinking the Java way.

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java [hunk 3]
```diff
@@ -409,6 +408,9 @@ static void deleteAssets(Context context, String selection, String[] selectionAr
     } catch (SecurityException e) {
       promise.reject(ERROR_UNABLE_TO_SAVE_PERMISSION,
         "Could not delete asset: need WRITE_EXTERNAL_STORAGE permission.", e);
+    } catch (IllegalArgumentException e) {
+      e.printStackTrace();
+      promise.reject(ERROR_UNABLE_TO_DELETE, "Could not delete file.", e);
```
Comment (tsapeta) [inline packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java:413]: We're trying to stick to `ERR` prefix for error names in the new code 😉 
```suggestion
      promise.reject(ERR_UNABLE_TO_DELETE, "Could not delete file.", e);
```

**Review by tsapeta — APPROVED** [review]

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java (hunk 3 above)
Comment (barthap) [reply packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java:413]: I've just used the constant that already existed, but I can rename it for whole module 😉

**Review by lukmccall — APPROVED** [review]
