### PR TITLE
[expo-router][ios] fix tint color on VectorIcon

### LINKED ISSUE #43561: [SDK 55] VectorIcon in NativeTabs are not tinted
### Minimal reproducible example

https://github.com/BakkerTom/expo-vector-tabbar-repro

### Steps to reproduce

Using `VectorIcons` within `NativeTabs` results in white icons. I expect them to be tinted using `tintColor` and `iconColor`. 

The tinting does work for SF symbols (`sf` prop) and image assets (with a `require()` import). In my testing `renderingMode='template'` made no difference.

## Example code
```tsx
import { NativeTabs } from "expo-router/unstable-native-tabs";
import { Ionicons } from "@expo/vector-icons";

export default function TabsLayout() {
  return (
    <NativeTabs>
      <NativeTabs.Trigger name="index">
        <NativeTabs.Trigger.Icon
          src={<NativeTabs.Trigger.VectorIcon family={Ionicons} name="home" />}
        />
        <NativeTabs.Trigger.Label>Home</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="settings">
        <NativeTabs.Trigger.Icon
          src={
            <NativeTabs.Trigger.VectorIcon family={Ionicons} name="settings" />
          }
        />
        <NativeTabs.Trigger.Label>Settings</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
```
## Screenshots
|Image|Image|
|---|---|
|Example using VectorIcon (Ionicons)|SF Symbols|

### Environment

```text
expo-env-info 2.0.11 environment info:
    System:
      OS: macOS 15.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 24.11.0 - ~/.local/share/mise/installs/node/24.11.0/bin/node
      npm: 11.6.1 - ~/.local/share/mise/installs/node/24.11.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/tom/.local/share/mise/installs/ruby/3.4.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.1, iOS 26.1, macOS 26.1, tvOS 26.1, visionOS 26.1, watchOS 26.1
    IDEs:
      Android Studio: 2025.1 AI-251.25410.109.2511.13752376
      Xcode: 26.1.1/17B100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~55.0.4 => 55.0.4
      expo-router: ~55.0.3 => 55.0.3
      react: 19.2.0 => 19.2.0
      react-native: 0.83.2 => 0.83.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by Ubax**
# Why

Fixes https://github.com/expo/expo/issues/43561

# How

Pass `renderingMode` when using `AwaitedIcon`

# Test Plan

1. Unit test
2. Manual testing

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by Ubax** [comment]
* **#43904** <a href="https://app.graphite.com/github/pr/expo/expo/43904?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/43904?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/expo-router/src/native-tabs/utils/icon.ts [hunk 1]
```diff
@@ -115,14 +122,22 @@ export function convertOptionsIconToAndroidPropsIcon(
...
-    return { src: src.props.loader() };
+    result = { src: src.props.loader() };
   } else {
     console.warn('Only VectorIcon is supported as a React element in Icon.src');
+    return undefined;
   }
-  return undefined;
+  if (renderingMode) {
+    return { ...result, renderingMode };
+  }
```
Comment (hassankhan) [inline packages/expo-router/src/native-tabs/utils/icon.ts:141]: Minor, but perhaps instead of multiple returns, we could just assign to `result` and return once at the end of the function?

**Review by hassankhan — APPROVED** [review]
