### PR TITLE
[expo-router] fix linking in two places and state restoration after activity recreation

### LINKED ISSUE #42500: [SDK 55][Android]  Unexpected app restart and linking error after wallpaper update
### Minimal reproducible example

https://github.com/androidanimation/Expo-app-restarts-after-wallpaper-change

### Steps to reproduce

After changing the system wallpaper and returning to the app, the app restarts and reports a linking configuration issue.

Steps to reproduce
1  Run bun create expo-app --template default@next
2  Build with eas build --profile development --platform android
3  Open app on Android 13
4  Change wallpaper
5  Switch back to the app

Expected behavior
The app should resume normally.

Actual behavior
The app restarts and shows a linking error.

https://github.com/user-attachments/assets/9f3af129-7728-4088-a0e0-183e7306b6a5

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 24.13.0 - /run/user/1000/fnm_multishells/5644_1769265571743/bin/node
      npm: 11.6.2 - /run/user/1000/fnm_multishells/5644_1769265571743/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0
    npmPackages:
      expo: ~55.0.0-preview.4 => 55.0.0-preview.5 
      expo-router: ~55.0.0-beta.1 => 55.0.0-beta.2 
      react: 19.2.0 => 19.2.0 
      react-dom: 19.2.0 => 19.2.0 
      react-native: 0.83.1 => 0.83.1 
      react-native-web: ~0.21.0 => 0.21.2 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by Ubax**
# Why

Fixes: https://github.com/expo/expo/issues/42500

**After**

There is still a small bug when recreating the state with stack nested inside native tabs. But it it not related to this PR and is a bug in react-native-screens

# How

# Test Plan

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

## Summary by CodeRabbit

* **Bug Fixes**
  * Refined the runtime warning for conflicting linking configurations—now it only warns when multiple linking handlers are present and not on Android, reducing noisy/irrelevant warnings.
  * Improved Android state restoration so prior navigation state is reused across remounts when the app context matches, preserving user navigation after activity recreation.

### CODE REVIEW

**Comment by Ubax** [comment]
* **#42644** <a href="https://app.graphite.com/github/pr/expo/expo/42644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/42644?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by EvanBacon — APPROVED** [review]
thank god

File: packages/expo-router/src/global-state/router-store.tsx [hunk 1]
```diff
@@ -208,6 +208,10 @@ export function useStore(
     rootComponent = Fragment;
   }
 
+  if (storeRef.current.state) {
```
Comment (EvanBacon) [inline packages/expo-router/src/global-state/router-store.tsx]: Maybe add an android-only check here too
