### PR TITLE
[expo-updates] update scopeKey in database if there's a mismatch

### LINKED ISSUE #10305: [ios][android] Error "No launchable updates found in database" occasionally when trying to open a snack
## 🐛 Bug Report

Occasionally in the 2.17.x store versions of the iOS/Android development clients, when opening a snack you have opened before you will run into the error "No launchable updates found in database".

This is a regression with the current client versions and will be fixed ASAP in an update. In the meantime, you can work around this by renaming and saving the snack.

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Addresses the underlying issue in https://github.com/expo/expo/issues/10305 and https://github.com/expo/expo/pull/10308. Currently expo-updates assumes that update IDs will be unique across all apps/scopes.

When an update is downloaded, only the ID is checked to determine if it's already loaded. This means that if an update is downloaded with the same ID but a different scopeKey as one that already exists in the database, the update will not be downloaded (since one with a matching ID is found) but then when expo-updates tries to launch the update later on, it will not be able to find one with the required scopeKey, resulting in the error message from #10305.

This problematic situation is really a server error, but we should handle it more gracefully on the client if we can.

# How

- when checking to see if an update already exists on disk, also check the scope key of the existing update.
- if it does not match the one we already have downloaded, we can't just insert a new row because the ID field is the primary key across the whole table. Instead, we can assume that the update is likely the same one and just update the scopeKey field.

# Test Plan

Same as https://github.com/expo/expo/pull/10308. This fixes #10305 separately from that PR (but we should land both fixes).

### CODE REVIEW

File: packages/expo-updates/android/src/main/java/expo/modules/updates/loader/RemoteLoader.java [hunk 1]
```diff
@@ -130,6 +130,14 @@ private void processManifest(Manifest manifest) {
 
     UpdateEntity newUpdateEntity = manifest.getUpdateEntity();
     UpdateEntity existingUpdateEntity = mDatabase.updateDao().loadUpdateWithId(newUpdateEntity.id);
+
+    // if something has gone wrong on the server and we have two updates with the same id
+    // but different scope keys, we should try to launch something rather than show a cryptic
+    // error to the user.
+    if (existingUpdateEntity != null && !existingUpdateEntity.scopeKey.equals(newUpdateEntity.scopeKey)) {
+      mDatabase.updateDao().setUpdateScopeKey(existingUpdateEntity, newUpdateEntity.scopeKey);
```
Comment (ide) [inline packages/expo-updates/android/src/main/java/expo/modules/updates/loader/RemoteLoader.java:138]: Do you think it's worth logging in the event someone needs to diagnose issues on a device?

**Review by ide — APPROVED** [review]
