### PR TITLE
[Permission] Rework

### LINKED ISSUE #4289: [Android][expo-permissions]  No ability to distinguish when a user has denied access with "Don't ask again" check
### Expected Behavior
I can get a specific status when user press deny with 'don't ask again', like `react-native` Permissions API:
```js
import { PermissionsAndroid, Platform } from 'react-native';

PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN;
```

### Actual Behavior
When user press `"DENY"`, no matter the checkbox `"Don't ask again"` was set to the truth

We get the same result:
```js
{
   expires:"never"
   status:"denied"
}
```
### Reproducible Demo
```js
// @flow
import {
  CAMERA,
  askAsync,
} from 'expo-permissions';

askAsync(CAMERA).then(result => {
	// ...
})
```

### LINKED ISSUE #4618: Permissions.getAsync() results inconsistent with iOS settings after upgrade to ExpoKit 33
### Environment
```
  Expo CLI 2.19.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.2 => 16.8.7 
      @types/react-native: ^0.57.35 => 0.57.38 
      @types/react-navigation: ^3.0.2 => 3.0.4 
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.1
```

We are running an iOS ExpoKit app, distributed through TestFlight.

### Steps to Reproduce

You can repro this issue on [this snack](https://snack.expo.io/@curalate/expo-33-permissions-bug-repro-) provided that Expo is set to v33. You will **not** repro if you set Expo to v32.

Repro steps on this snack:
- Trigger the iOS permissions modal via the `Ask for Perms` button (which calls `Permissions.askAsync(Permissions.CAMERA_ROLL)`)
- Select `Don't Allow` to deny the permission
- Verify that the current permission status as determined by `Permissions.getAsync(Permissions.CAMERA_ROLL)` is `denied` by hitting the `Check Perms` button.
- Go to the settings app within the snack iOS simulator, navigate to Expo -->  Photos, and give the Expo app camera roll read/write permissions
- Navigate back to the Expo app, hit the `Check Perms` button again, and observe that the camera roll permission is still reported as denied.

### Expected Behavior

The status returned by `Permissions.getAsync()` should reflect the permissions found in the iOS settings app. 

### Actual Behavior

Under certain conditions the status from `Permissions.getAsync()` is always returned as `denied`, and cannot be changed even if you manually adjust permissions via iOS settings.

We discovered this issue primarily because the status is returned as `denied` when we upgrade directly from our older non-Expo app where we have already granted permissions to our new TestFlight build running ExpoKit 33. This is causing a bunch of issues for our testers, so we'd love a better workaround than having all of our testers delete our app and re-request perms from scratch!

### LINKED ISSUE #4972: [Permissions] Major rework
I will try to make permissions rework.

Here I post some information about what and how I want to change. 
It would be nice if you provide me some feedback, then we figure out how new permissions will look like. 

Firstly I want to focused on iOS implementation.

Here is our current flow graph for permission asking:

PermissionsFlow

So my suggestions:
- move more logic from `ScopePermission` (SP) to `expo-permission` (P). Now, the decision on how to check given permission came from `ScopePermission` (SP). This solution forced a lot of jumps between SP and P. If we move decision logic to P we could treat SP like iOS extension, which provides API for permissions per experience. 
- treat "particle permission" as a full-fledged permission type (`Location in the foreground` will be a subtype of `LocationPemission`).
We could make a permission family, for example:
LocationPermission will be divided into `foreground` and `background` permission, so the user will be able to ask for all 3 permissions (LocationPermission will still be available to the user).  
  - If he asked for the main permission, this will be treated as asking for all children permissions. 
  - In a situation when he asked for child permission and the current platform doesn't support the required type of permission, the system will ask for the main permission. 

For now, I will try to refactor the current permissions code to make it more readable.

### LINKED ISSUE #5831: react-native-webview - File download without granted storage permission crashes app on Android
### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.1.2

App target: Standalone Android and Android Expo Client.

### Steps to Reproduce

Create a new expo project.
Make sure storage permission is **NOT** accepted for the app (Expo client if you don't build a standalone app).
Try to download a file from a website in a webview (react-native-webview).

If you try to reproduce this bug in a standalone app you will need to add permissions `"READ_EXTERNAL_STORAGE"` and `"WRITE_EXTERNAL_STORAGE"` to `app.json`.

### Expected Behavior

When clicking download it should ask for permission for storage. If the user accepts the permission it should download the file. If the user denies nothing should happen.

### Actual Behavior

The app crashes.
Crash

### Reproducible Demo

https://snack.expo.io/r1bjtCZuH

Download button is in the top right.

## Other
There is also a similar issue with the camera in a webview. If you click on an `<input type="file" accept="image/*">` the webview will ask if you want to take a photo or select an existing photo. If you choose "take photo" nothing will happen if the camera permission isn't already accepted.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolves #4972.
Resolves #5831.
Resolves #4289.
Resolves #4618.

# How

- iOS
  - [x] general clean up. 
  - [x] move logic responsible for asking/getting more than one permission to js side.
  - [x] extract base class for requesters.
  - [x] move each requester to separate podspec.  
  - [x] remove `EXPermissionsModule protocol.
  - [x] make requesters registrable. 
  - [x] add `[_constantsBinding.appOwnership isEqualToString:@"expo"]` to `EXScopedPermissions`. ([see](https://github.com/expo/expo/commit/7b5cc3cff209c57f01e4ede1518fea946d949f36))
  - [x] modules, which need permissions should have own native method to handle own permission.
    - [x] move requesters to modules 
- Android
  - [x] rewrite to kotlin.
  - [x] general clean up.
  - [x] move logic responsible for `scoped permission ask` to activity.
  - [x] remove `PermissionsManager`.
  - [x] remove `PermissionsServiceBinding`. 
  - [x] clean `PermissionsModule` class.
  - [x] do something with `systemBrightness`.
  - [x] cache `mPermissionsAskedFor`. 
  - [x] modules, which need permissions should have own native method to handle own permission.
    - [x] move logic from `PermissionsModule` to `PermissionsService` 
    - [x] rewrite native api for permissions - make it similar to iOS 
    - [x] use List<String> insted of String[] in native interface
    - [x] move requsters to modules
  - [x] resolve #5831.
- Both
  - [x] resolve #4289.
  - [x] resolve #4618 (not fixed in expo client).

# Flowgraph

- iOS
iOS_flow_graph

- Android
android_flow_graph

# Test Plan

- test-suite passed.
- I tested it with a simple [demo](https://snack.expo.io/@lukaszkosmaty/permissions-refactoring) (run on several experiences to be able to test scoped permissions).

## Test cases:
| Test | Android | iOS |
|-----|:---:|:---:|
| Permissions are properly set in settings. | 🆗 | 🆗 |
| Permissions are properly scoped (switching between two apps). | 🆗 | 🆗 |
| Global combined status is correct. | 🆗 | 🆗 |
| Scoped status is correct (the previous test but enforce using scoped permission). | 🆗| 🆗|
| Check if `canAskAgain` and `granted` fields have the correct value. | 🆗| 🆗|
| Test added module methods (getting/asking using, for example, the `Camera` module). | 🆗| 🆗|
| Test backward compatibility. | 🆗 | 🆗|
| Changing permissions in system settings. | 🆗| 🆗| 
| Bare workflow. | 🆗 | 🆗 |

### CODE REVIEW

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt [hunk 1]
```diff
@@ -0,0 +1,406 @@
...
+      throw IllegalStateException("No Permissions module present.")
+    }
+  }
+
+  /**
+   * Checks whether all given permissions are granted or not.
+   * Throws IllegalStateException there's no Permissions module present.
+   */
+  private fun arePermissionsGranted(permissions: Array<String>): Boolean {
+    if (mPermissions != null) {
```
Comment (lukmccall) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt]: Here should be `mPermissions == null`. I will fix it later.

File: android/expoview/src/main/java/host/exp/exponent/utils/PermissionsHelper.java [hunk 2]
```diff
@@ -56,7 +56,7 @@ public boolean requestPermissions(Exponent.PermissionsListener listener, String[
     List<String> permissionsToExplain = new ArrayList<>();
     for (String permission : permissions) {
       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
-          ContextCompat.checkSelfPermission(activity, permission) != PackageManager.PERMISSION_GRANTED) {
+          /* ask for global permission */ activity.checkSelfPermission(permission) != PackageManager.PERMISSION_GRANTED) {
```
Comment (bbarthec) [inline android/expoview/src/main/java/host/exp/exponent/utils/PermissionsHelper.java]:
```suggestion
          /* check for global permission */ activity.checkSelfPermission(permission) != PackageManager.PERMISSION_GRANTED) {
```

File: android/expoview/src/main/java/host/exp/exponent/experience/DetachedModuleRegistryAdapter.java [hunk 3]
```diff
@@ -42,7 +42,7 @@ public DetachedModuleRegistryAdapter(ReactModuleRegistryProvider moduleRegistryP
     }
 
     // Overriding ScopedUIManagerModuleWrapper from ReactAdapterPackage
-    moduleRegistry.registerInternalModule(new ScopedUIManagerModuleWrapper(reactContext, experienceId, manifest.optString(ExponentManifest.MANIFEST_NAME_KEY)));
+    moduleRegistry.registerInternalModule(new ScopedUIManagerModuleWrapper(reactContext, experienceId, manifest.optString(ExponentManifest.MANIFEST_NAME_KEY))); // todo: I think I can delete this line but I'm not sure :\
```
Comment (bbarthec) [inline android/expoview/src/main/java/host/exp/exponent/experience/DetachedModuleRegistryAdapter.java]: Find out then 😜 cc @tsapeta @sjchmiela

File: android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java [hunk 4]
```diff
@@ -263,8 +284,55 @@ protected void registerForNotifications() {
...
+  }
+
+  @Override
+  public void onRequestPermissionsResult(final int requestCode, final String permissions[], final int[] grantResults) {
+    if (permissions.length > 0 && grantResults.length > 0 && mPermissionsHelper != null) {
+      mPermissionsHelper.onRequestPermissionsResult(requestCode, permissions, grantResults);
+      mPermissionsHelper = null;
+    }
+  }
+
```
Comment (bbarthec) [inline android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java]:
```suggestion
```

File: ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m [hunk 5]
```diff
@@ -40,190 +33,125 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
...
+  return permission;
 }
 
 - (BOOL)hasGrantedScopedPermission:(NSString *)permissionType
 {
   if (!_permissionsService) {
     return YES;
   }
-
+
```
Comment (bbarthec) [inline ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m]:
```suggestion

```

File: ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m [hunk 6]
```diff
@@ -40,190 +33,125 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
...
 + (NSString *)textForPermissionType:(NSString *)type
 {
   if ([type isEqualToString:@"audioRecording"]) {
     return @"recording audio";
   } else if ([type isEqualToString:@"cameraRoll"]) {
     return @"photos";
   }
-
+
```
Comment (bbarthec) [inline ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m]:
```suggestion

```

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/CalendarRequester.kt [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+            putString(STATUS_KEY, UNDETERMINED_VALUE)
+          }
+        }
+      } catch (e: IllegalStateException) {
+        putString(STATUS_KEY, DENIED_VALUE)
+      }
+      putString(EXPIRES_KEY, PERMISSION_EXPIRES_NEVER)
+    }
+  }
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/CalendarRequester.kt]: newline needed

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/CameraRollRequester.kt [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+            putString(STATUS_KEY, UNDETERMINED_VALUE)
+          }
+        }
+      } catch (e: IllegalStateException) {
+        putString(STATUS_KEY, UNDETERMINED_VALUE)
+      }
+      putString(EXPIRES_KEY, PERMISSION_EXPIRES_NEVER)
+    }
+  }
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/CameraRollRequester.kt]: newline needed

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/LocationRequester.kt [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+        }
+      } catch (e: IllegalStateException) {
+        putString(STATUS_KEY, UNDETERMINED_VALUE)
+      }
+
+      putString(EXPIRES_KEY, PERMISSION_EXPIRES_NEVER)
+      putBundle("android", Bundle().apply { putString("scope", scope) })
+    }
+  }
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/LocationRequester.kt]: newline needed

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/NotificationRequester.kt [hunk 10]
```diff
@@ -0,0 +1,22 @@
...
+  override fun getPermissionToAsk(): Array<String> = emptyArray()
+
+  override fun getPermission(): Bundle {
+    return Bundle().apply {
+      val areEnabled = NotificationManagerCompat.from(context).areNotificationsEnabled()
+      putString(STATUS_KEY, if (areEnabled) GRANTED_VALUE else DENIED_VALUE)
+      putString(EXPIRES_KEY, PERMISSION_EXPIRES_NEVER)
+    }
+  }
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/NotificationRequester.kt]: newline needed

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/PermissionRequester.kt [hunk 11]
```diff
@@ -0,0 +1,60 @@
...
+
+        putString(EXPIRES_KEY, PERMISSION_EXPIRES_NEVER)
+      }
+    }
+  }
+
+  fun getPermission(): Bundle
+
+  fun getPermissionToAsk(): Array<String>
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/PermissionRequester.kt]: newline needed

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/PermissionRequester.kt [hunk 12]
```diff
@@ -0,0 +1,60 @@
...
+        try {
+          when {
+            isPermissionGranted(permission) -> {
+              putString(STATUS_KEY, GRANTED_VALUE)
+            }
+            PermissionsModule.didAsk(permission) -> {
+              putString(STATUS_KEY, GRANTED_VALUE)
+            }
+            else -> {
+              putString(STATUS_KEY, UNDETERMINED_VALUE)
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/PermissionRequester.kt]: lift up `putString`

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/RemindersRequester.kt [hunk 13]
```diff
@@ -0,0 +1,19 @@
...
+  override fun getPermissionToAsk(): Array<String> = emptyArray()
+
+
+  override fun getPermission(): Bundle {
+    return Bundle().apply {
+      putString(STATUS_KEY, GRANTED_VALUE)
+      putString(EXPIRES_KEY, PERMISSION_EXPIRES_NEVER)
+    }
+  }
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/RemindersRequester.kt]: newline

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/SimpleRequester.kt [hunk 14]
```diff
@@ -0,0 +1,16 @@
...
+ * Used for representing CAMERA, CONTACTS, AUDIORECORDING, SMS
+ *
+ */
+class SimpleRequester(val permission: String) : PermissionRequester {
+  override fun getPermissionToAsk(): Array<String> = arrayOf(permission)
+
+  override fun getPermission(): Bundle {
+    return PermissionRequester.getSimplePermission(permission)
+  }
+}
```
Comment (bbarthec) [inline packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/SimpleRequester.kt]: newline

File: packages/expo-permissions/ios/EXPermissions/EXPermissionBaseRequester.m [hunk 15]
```diff
@@ -0,0 +1,16 @@
+// Copyright 2016-present 650 Industries. All rights reserved.
+
+#import <EXPermissions/EXPermissionBaseRequester.h>
+
+@implementation EXPermissionBaseRequester
+
+- (void)requestPermissionsWithResolver:(UMPromiseResolveBlock)resolve rejecter:(UMPromiseRejectBlock)reject {
+  // todo: change it to something better
```
Comment (bbarthec) [inline packages/expo-permissions/ios/EXPermissions/EXPermissionBaseRequester.m]: ping

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 16]
```diff
@@ -71,109 +125,51 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
...
+                    askAsyncForPermission:(NSString *)permissionType
                     resolver:(UMPromiseResolveBlock)resolve
                     rejecter:(UMPromiseRejectBlock)reject)
 {
-  [self askForPermissionsWithTypes:permissionsTypes
-                       withResults:resolve
-                      withRejecter:reject];
+  [self askForPermissionWithType:permissionType
+                     withResults:resolve 
+                     withRejecter:reject];
```
Comment (bbarthec) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]:
```suggestion
                    withRejecter:reject];
```

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 17]
```diff
@@ -182,83 +178,64 @@ - (BOOL)hasGrantedPermission:(NSString *)permissionType
...
-  void (^globalPermissionResolver)(NSDictionary *) = ^(NSDictionary *globalPermissions) {
-    [permissions addEntriesFromDictionary:globalPermissions];
-    onResults([NSDictionary dictionaryWithDictionary:permissions]);
-  };
-
-  [self askForGlobalPermissions:globalPermissionsToBeAsked
-                   withResolver:globalPermissionResolver
+ 
+  [self askForGlobalPermission:permissionType
+                   withResolver:onResults
```
Comment (bbarthec) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]:
```suggestion
                  withResolver:onResults
```

File: packages/expo-permissions/src/Permissions.ts [hunk 18]
```diff
@@ -51,4 +88,4 @@ async function _handlePermissionsRequestAsync(
     expires: coalesceExpirations(permissions),
     permissions,
   };
-}
+}
```
Comment (bbarthec) [inline packages/expo-permissions/src/Permissions.ts]: newline

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 19]
```diff
@@ -28,266 +29,256 @@ @implementation EXPermissions
...
+    return false;
+  }
+  
+  return [permissions[@"status"] isEqualToString:@"granted"];
 }
 
-- (void)askForPermissions:(NSArray<NSString *> *)permissionsTypes
-              withResults:(void (^)(NSArray<NSDictionary *> *))onResults
-             withRejecter:(UMPromiseRejectBlock)reject
+- (void)askForPermissionUsingRequesterClass:(Class)requesterClass
```
Comment (bbarthec) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]: This method will handle requesting permission once requesters would be moved to separate modules, right?

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 20]
```diff
@@ -28,266 +29,256 @@ @implementation EXPermissions
...
-                              }
-                             withRejecter:reject];
+  NSMutableDictionary *permission = [[self getPermissionUsingRequesterClass:requesterClass] mutableCopy];
+  
+  // permission type not found - reject immediately
+  if (permission == nil) {
+    return reject(@"E_PERMISSIONS_UNKNOWN", [NSString stringWithFormat:@"Unrecognized requester: %@", NSStringFromClass(requesterClass)], nil);
+  }
+  
+  BOOL isGranted = [EXPermissions statusForPermission:permission] == UMPermissionStatusGranted;
```
Comment (bbarthec) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]: What about permissions returning composite results that not necessarily are explicitly granted?
E.g. `NOTIFICATIONS` right now comes with this scenario.

File: packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsInterface.h [hunk 21]
```diff
@@ -1,18 +1,43 @@
...
+@end
 
 @protocol UMPermissionsInterface
 
 - (NSDictionary *)getPermissionsForResource:(NSString *)resource;
+
 - (BOOL)hasGrantedPermission:(NSString *)permissionType;
 
 - (void)askForPermission:(NSString *)permissionType
               withResult:(void (^)(NSDictionary *))onResult
```
Comment (bbarthec) [inline packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsInterface.h]: I wonder whether this actually cannot be
```suggestion
              withResult:(UMPromiseResolveBlock)onResult
```
❓

File: packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsInterface.h [hunk 22]
```diff
@@ -1,18 +1,43 @@
...
-              withResults:(void (^)(NSArray<NSDictionary *> *))onResults
-             withRejecter:(UMPromiseRejectBlock)reject;
+- (void)registerRequesters:(NSArray<id<UMPermissionsRequester>> *)newRequesters;
+
+- (NSDictionary *)getPermissionUsingRequesterClass:(Class)requesterClass;
+
+- (BOOL)hasGrantedPermissionUsingRequesterClass:(Class)requesterClass;
+
+- (void)askForPermissionUsingRequesterClass:(Class)requesterClass
+              withResult:(void (^)(NSDictionary *))onResult
```
Comment (bbarthec) [inline packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsInterface.h]: Same here:
```suggestion
              withResult:(UMPromiseResolveBlock)onResult
```
❓ 

If so, please adjust all the occurrences 😉

**Review by bbarthec — COMMENTED** [review]
LGTM 💯 Amazing work 👍
One suggestion:
Maybe these's some clever way to rewrite
```obj-c
%{
	@"status": sth,
	@"expires": sth
}
```

into some POJO-style or NSDictionary-based?

There are many places where this construction is used and it's always typed by hand, but maybe we can somehow enforce more class-based behaviours instead of JSON-like behaviour.

**Review by bbarthec — COMMENTED** [review]
Great job! 💯 Let's merge it once everything is resolved and proceed to testing 😉 
One global comment: think more about variables/methods/functions names to provide as much information as possible 👍 
One request: maybe it's possible to draw some diagram showing what and how is happening during PermissionRequester registration and asking for/getting permission starting from JS side 🤔 🙇 🙏 (If I was to ask I would do sth like [this](https://developer.android.com/guide/components/activities/activity-lifecycle#alc) using draw.io) 😉

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.h [hunk 23]
```diff
@@ -6,38 +6,16 @@
...
-- (dispatch_queue_t)methodQueue;
-
-@end
-
-@interface EXPermissions : UMExportedModule <EXPermissionRequesterDelegate, UMPermissionsInterface, UMModuleRegistryConsumer, EXPermissionsModule>
-
-- (NSDictionary *)getPermissionsForResource:(NSString *)resource;
-
-+ (NSString *)permissionStringForStatus:(EXPermissionStatus)status;
+- (void)askForGlobalPermissionUsingRequesterClass:(Class)requesterClass
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-permissions/ios/EXPermissions/EXPermissions.h]: Yes that's true

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsService.kt [hunk 24]
```diff
@@ -0,0 +1,260 @@
...
+  }
+
+  override fun getExportedInterfaces(): List<Class<out Any>> = listOf(Permissions::class.java)
+
+  @Throws(IllegalStateException::class)
+  override fun onCreate(moduleRegistry: ModuleRegistry) {
+    mActivityProvider = moduleRegistry.getModule(ActivityProvider::class.java)
+        ?: throw IllegalStateException("Couldn't find implementation for ActivityProvider.")
+    moduleRegistry.getModule(UIManager::class.java).registerLifecycleEventListener(this)
+    mPermissionsAskedStorage = context.applicationContext.getSharedPreferences(PREFERENCE_FILENAME, Context.MODE_PRIVATE)
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsService.kt]: I've renamed it.

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsService.kt [hunk 25]
```diff
@@ -0,0 +1,260 @@
...
+
+private const val PERMISSIONS_REQUEST: Int = 13
+private const val PREFERENCE_FILENAME = "expo.modules.permissions.asked"
+
+internal const val ERROR_TAG = "E_PERMISSIONS"
+
+typealias PermissionsListener = (result: IntArray) -> Unit
+
+class PermissionsService(val context: Context) : InternalModule, Permissions, LifecycleEventListener {
+  private var mActivityProvider: ActivityProvider? = null
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsService.kt]: Location module in OnHostResume calls `getPermissions` method, before Activity Provider is available. So, that's why I've decided to remove lateinit.

File: packages/expo-permissions/src/Permissions.ts [hunk 26]
```diff
@@ -1,5 +1,7 @@
-import { coalesceExpirations, coalesceStatuses } from './CoalescedPermissions';
+import { coalesceExpirations, coalesceStatuses, coalesceCanAskAgin } from './CoalescedPermissions';
```
Comment (bbarthec) [inline packages/expo-permissions/src/Permissions.ts]:
```suggestion
import { coalesceExpirations, coalesceStatuses, coalesceCanAskAgain } from './CoalescedPermissions';
```

**Review by bbarthec — APPROVED** [review]
I've found one small typo 😛 
Fix, merge master resolving conflicts, ensure CI builds correctly and merge 💯 
Let's ship it! 😄

**Review by bbarthec — APPROVED** [review]
From what I can see:
- `packages/react-native-unimodule` shouldn't probably be updated -> it's submodule, so please `git submodule update` after rebasing on/merging master
- `yaga` pod shouldn't be deleted 🤔 Please revert this (`et ios-generate-dynamic-macros` after rebasing)

Please fix and merge 🎉

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 27]
```diff
@@ -18,6 +18,30 @@ import SnackEmbed from '~/components/plugins/SnackEmbed';
...
+
+### `ImagePicker.requestCameraRollPermissionsAsync()`
+
+Asks the user to grant permissions for accessing user's photo. Alias for `Permissions.askAsync(Permissions.CAMERA_ROLL)`.
+
+#### Returns
+
+A promise that resolves to an object of type [PermissionsResponse](#permissionsresponse).
+
+### `ImagePicker.getCamerPermissionsAsync()`
```
Comment (brentvatne) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]:
```suggestion
### `ImagePicker.getCameraPermissionsAsync()`
```

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 28]
```diff
@@ -18,6 +18,30 @@ import SnackEmbed from '~/components/plugins/SnackEmbed';
...
+
+Checks user's permissions for accessing camera. Alias for `Permissions.getAsync(Permissions.CAMERA)`.
+
+### `ImagePicker.getCamerRollPermissionsAsync()`
```
Comment (brentvatne) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]:
```suggestion
### `ImagePicker.getCameraRollPermissionsAsync()`
```

**Review by brentvatne — CHANGES_REQUESTED** [review]

**Review by brentvatne — COMMENTED** [review]
a couple questions re: documentation

1. how will we need to update the [react-native-unimodules readme](https://github.com/unimodules/react-native-unimodules)?
2. how will we need to update the installation / configuration instructions in the READMEs for each related module? eg: https://github.com/expo/expo/blob/master/packages/expo-calendar/README.md

File: ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.h [hunk 29]
```diff
@@ -9,7 +9,9 @@ NS_ASSUME_NONNULL_BEGIN
 
 @protocol EXPermissionsScopedModuleDelegate
 
-- (EXPermissionStatus)getPermission:(NSString *)permissionType forExperience:(NSString *)experienceId;
+- (UMPermissionStatus)getPermission:(NSString *)permissionType forExperience:(NSString *)experienceId;
+// TODO: Remove once SDK32 is phased out
+- (BOOL)hasGrantedPermission:(NSString *)permission forExperience:(NSString *)experienceId; // used in SDKs 29–32
```
Comment (tsapeta) [inline ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.h]: Can we remove it? 🤔

File: ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m [hunk 30]
```diff
@@ -40,185 +32,123 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
...
 {
-  // nothing to ask for - return immediately
-  if (permissionsTypes.count == 0) {
-    return resolver(@{});
-  }
-  
-  // not in Expo Client - invoke allow action for each permission type
-  if (![_constantsBinding.appOwnership isEqualToString:@"expo"]) {
-    NSMutableDictionary *results = [NSMutableDictionary new];
+  NSDictionary* globalPermissions = [super getPermissionUsingRequesterClass:requesterClass];
```
Comment (tsapeta) [inline ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m]:
```suggestion
  NSDictionary *globalPermissions = [super getPermissionUsingRequesterClass:requesterClass];
```

File: ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m [hunk 31]
```diff
@@ -40,185 +32,123 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
...
+  NSString* permissionType = [requesterClass permissionType];
```
Comment (tsapeta) [inline ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m]:
```suggestion
  NSString *permissionType = [requesterClass permissionType];
```

File: packages/expo-brightness/ios/EXBrightness/EXSystemBrightnessRequester.m [hunk 32]
```diff
@@ -0,0 +1,23 @@
+// Copyright 2016-present 650 Industries. All rights reserved.
+
+#import <EXBrightness/EXSystemBrightnessRequester.h>
+
+@implementation EXSystemBrightnessRequester
```
Comment (tsapeta) [inline packages/expo-brightness/ios/EXBrightness/EXSystemBrightnessRequester.m]: I think we should call these requesters as permission requesters, so let's change it to `EXSystemBrightnessPermissionRequester`

File: packages/expo-brightness/src/Brightness.ts [hunk 33]
```diff
@@ -8,6 +8,19 @@ export enum BrightnessMode {
...
+  DENIED: 'denied',
+} as const;
+
+export type PermissionsResponse = {
+  status: typeof PermissionsStatus[keyof typeof PermissionsStatus];
+  expires: 'never' | number;
+  granted: boolean;
+  canAskAgain: boolean;
+};
+
```
Comment (tsapeta) [inline packages/expo-brightness/src/Brightness.ts]: It might be better to have these types defined in `unimodules-permissions-interface` and re-export them in modules using them.

File: packages/expo-calendar/ios/EXCalendar/EXCalendarRequester.h [hunk 34]
```diff
@@ -0,0 +1,7 @@
+// Copyright 2016-present 650 Industries. All rights reserved.
+
+#import <UMPermissionsInterface/UMPermissionsInterface.h>
+
+@interface EXCalendarRequester : NSObject<UMPermissionsRequester>
```
Comment (tsapeta) [inline packages/expo-calendar/ios/EXCalendar/EXCalendarRequester.h]:
```suggestion
@interface EXCalendarPermissionRequester : NSObject<UMPermissionsRequester>
```

File: packages/expo-calendar/ios/EXCalendar/EXCalendarRequester.m [hunk 35]
```diff
@@ -1,18 +1,17 @@
-#import <EXPermissions/EXCalendarRequester.h>
+#import <EXCalendar/EXCalendarRequester.h>
```
Comment (tsapeta) [inline packages/expo-calendar/ios/EXCalendar/EXCalendarRequester.m]:
```suggestion
#import <EXCalendar/EXCalendarPermissionRequester.h>
```

File: packages/expo-calendar/ios/EXCalendar/EXRemindersRequester.h [hunk 36]
```diff
@@ -0,0 +1,7 @@
+// Copyright 2016-present 650 Industries. All rights reserved.
+
+#import <UMPermissionsInterface/UMPermissionsInterface.h>
+
+@interface EXRemindersRequester : NSObject<UMPermissionsRequester>
```
Comment (tsapeta) [inline packages/expo-calendar/ios/EXCalendar/EXRemindersRequester.h]:
```suggestion
@interface EXRemindersPermissionRequester : NSObject<UMPermissionsRequester>
```

File: packages/expo-calendar/ios/EXCalendar/EXRemindersRequester.m [hunk 37]
```diff
@@ -1,17 +1,17 @@
-#import <EXPermissions/EXRemindersRequester.h>
+#import <EXCalendar/EXRemindersRequester.h>
```
Comment (tsapeta) [inline packages/expo-calendar/ios/EXCalendar/EXRemindersRequester.m]:
```suggestion
#import <EXCalendar/EXRemindersPermissionRequester.h>
```

File: packages/expo-camera/ios/EXCamera/EXCamera.m [hunk 38]
```diff
@@ -4,6 +4,7 @@
 #import <EXCamera/EXCamera.h>
 #import <EXCamera/EXCameraUtils.h>
 #import <EXCamera/EXCameraManager.h>
+#import <EXCamera/EXCameraRequester.h>
```
Comment (tsapeta) [inline packages/expo-camera/ios/EXCamera/EXCamera.m]:
```suggestion
#import <EXCamera/EXCameraPermissionRequester.h>
```

File: packages/expo-camera/ios/EXCamera/EXCamera.m [hunk 39]
```diff
@@ -578,8 +579,7 @@ - (void)startSession
 #if TARGET_IPHONE_SIMULATOR
   return;
 #endif
-  NSDictionary *cameraPermissions = [_permissionsManager getPermissionsForResource:@"camera"];
-  if (![cameraPermissions[@"status"] isEqualToString:@"granted"]) {
+  if (![_permissionsManager hasGrantedPermissionUsingRequesterClass:[EXCameraRequester class]]) {
```
Comment (tsapeta) [inline packages/expo-camera/ios/EXCamera/EXCamera.m]:
```suggestion
  if (![_permissionsManager hasGrantedPermissionUsingRequesterClass:[EXCameraPermissionRequester class]]) {
```

File: packages/expo-camera/ios/EXCamera/EXCameraManager.m [hunk 40]
```diff
@@ -1,16 +1,19 @@
 #import <EXCamera/EXCamera.h>
 #import <EXCamera/EXCameraManager.h>
 #import <EXCamera/EXCameraUtils.h>
+#import <EXCamera/EXCameraRequester.h>
```
Comment (tsapeta) [inline packages/expo-camera/ios/EXCamera/EXCameraManager.m]:
```suggestion
#import <EXCamera/EXCameraPermissionRequester.h>
```

File: docs/pages/versions/unversioned/sdk/audio.md [hunk 41]
```diff
@@ -18,6 +18,24 @@ For [managed](../../introduction/managed-vs-bare/#managed-workflow) apps, you'll
...
 
+## Request recording permissions
+
+### `Audio.requestPermissionsAsync()`
+
+Asks the user to grant permissions for audio recording. Alias for `Permissions.askAsync(Permissions.AUDIO_RECORDING)`.
+
+#### Returns
+
+A promise that resolves to an object of type [PermissionsResponse](#permissionsresponse).
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/audio.md]: I'm wondering if it isn't better to document `PermissionsResponse` type in Permissions docs and just link to that page here 🤔

File: packages/expo-av/ios/EXAV/EXAV.m [hunk 42]
```diff
@@ -7,10 +7,12 @@
 #import <UMCore/UMAppLifecycleService.h>
 #import <UMFileSystemInterface/UMFileSystemInterface.h>
 #import <UMPermissionsInterface/UMPermissionsInterface.h>
+#import <UMPermissionsInterface/UMPermissionsMethodsDelegate.h>
 
 #import <EXAV/EXAV.h>
 #import <EXAV/EXAVPlayerData.h>
 #import <EXAV/EXVideoView.h>
+#import <EXAV/EXAudioRecordingRequester.h>
```
Comment (tsapeta) [inline packages/expo-av/ios/EXAV/EXAV.m]:
```suggestion
#import <EXAV/EXAudioRecordingPermissionRequester.h>
```

**Review by tsapeta — CHANGES_REQUESTED** [review]
Generally looks good, but I'd make a few (but wide) changes:
- Rename `*Requester` classes to `*PermissionRequester` - it sounds better and is more descriptive about what the requester actually does.
- Move `PermissionsStatus` and `PermissionsResponse` types to `unimodules-permissions-interface` and their docs to Permissions docs page. Having them defined in every unimodule is not a good idea because we will have to maintain one, the same type, in several places.
These types cannot be in ze `expo-permissions` because we don't want other unimodules to depend on it. Interface seems to be a good alternative and it's going to be a dependency of all unimodules with permission requesters. (Also make sure the interface is actually a dependency of them).

**Comment by bbarthec** [comment]
Just to link this rework with web changes: https://github.com/expo/expo/pull/6115

File: packages/expo-barcode-scanner/build/BarCodeScanner.d.ts [hunk 43]
```diff
@@ -10,6 +10,16 @@ export declare type BarCodeEventCallbackArguments = {
...
 export declare type BarCodeScannedCallback = (params: BarCodeEvent) => void;
+export declare const PermissionsStatus: {
+    readonly GRANTED: "granted";
+    readonly UNDETERMINED: "undetermined";
+    readonly DENIED: "denied";
+};
+export declare type PermissionsResponse = {
+    status: typeof PermissionsStatus[keyof typeof PermissionsStatus];
+    expires: 'never' | number;
+    granted: boolean;
```
Comment (lukmccall) [inline packages/expo-barcode-scanner/build/BarCodeScanner.d.ts]: Add canAskAgain

File: packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java [hunk 44]
```diff
@@ -748,6 +743,35 @@ private void stopWatching() {
...
+    if (accessFineLocation.getStatus() == PermissionsStatus.GRANTED) {
+      scope = "fine";
+      status = PermissionsStatus.GRANTED.getStatus();
+    } else if (accessCoarseLocation.getStatus() == PermissionsStatus.GRANTED) {
+      scope = "coarse";
+      status = PermissionsStatus.GRANTED.getStatus();
+    } else if (accessFineLocation.getStatus() == PermissionsStatus.DENIED && accessCoarseLocation.getStatus() == PermissionsStatus.DENIED) {
+      status = PermissionsStatus.DENIED.getStatus();
+    }
+
```
Comment (lukmccall) [inline packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java]: Add granted key.

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 45]
```diff
@@ -28,266 +27,209 @@ @implementation EXPermissions
...
 
 # pragma mark - permission requsters / getters
 
-- (void)askForGlobalPermissions:(NSArray<NSString *> *)permissionsTypes
-                   withResolver:(void (^)(NSDictionary *))resolver
-                   withRejecter:(UMPromiseRejectBlock)reject
+
+- (void)getPermissionUsingRequesterClass:(Class)requesterClass
+                              withResult:(UMPromiseResolveBlock)onResult
+                            withRejecter:(UMPromiseRejectBlock)reject
```
Comment (esamelson) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]:
```suggestion
                              resolver:(UMPromiseResolveBlock)resolve
                           rejecter:(UMPromiseRejectBlock)reject
```
these are the conventions in the rest of the expo modules, not sure why they were different in this one but let's stick with the common conventions.

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 46]
```diff
@@ -28,266 +27,209 @@ @implementation EXPermissions
...
-  return [permissions[@"status"] isEqualToString:@"granted"];
+  return [permissions[EXStatusKey] isEqualToString:@"granted"];
 }
 
-- (void)askForPermission:(NSString *)permissionType
-              withResult:(void (^)(NSDictionary *))onResult
-            withRejecter:(UMPromiseRejectBlock)reject
+- (void)askForPermissionUsingRequesterClass:(Class)requesterClass
+                                 withResult:(UMPromiseResolveBlock)onResult
+                               withRejecter:(UMPromiseRejectBlock)reject
```
Comment (esamelson) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]: same comment here as above -- should be resolver:resolve and rejecter:reject

File: packages/expo-permissions/ios/EXPermissions/EXPermissions.m [hunk 47]
```diff
@@ -28,266 +27,209 @@ @implementation EXPermissions
...
+  [self askForGlobalPermissionUsingRequester:requester withResolver:onResult withRejecter:reject];
 }
-
-- (void)askForPermissions:(NSArray<NSString *> *)permissionsTypes
-              withResults:(void (^)(NSArray<NSDictionary *> *))onResults
-             withRejecter:(UMPromiseRejectBlock)reject
+   
+- (void)askForGlobalPermissionUsingRequesterClass:(Class)requesterClass
+                                     withResolver:(UMPromiseResolveBlock)resolver
+                                     withRejecter:(UMPromiseRejectBlock)reject
```
Comment (esamelson) [inline packages/expo-permissions/ios/EXPermissions/EXPermissions.m]: same comment here, and in the rest of the methods added to this module -- should be resolver:resolve and rejecter:reject

File: packages/expo-permissions/src/Permissions.ts [hunk 48]
```diff
@@ -30,13 +32,47 @@ export const REMINDERS = 'reminders';
...
+  types: PermissionType[],
+  handlePermission: (type: PermissionType) => Promise<PermissionInfo>
+): Promise<PermissionResponse> {
+  if (!types.length) {
+    throw new Error('At least one permission type must be specified');
+  }
+
+  let permissions = {};
+  for (let type of types) {
+    permissions[type] = await _handleSinglePermissionRequestIOSAsync(type, handlePermission);
```
Comment (esamelson) [inline packages/expo-permissions/src/Permissions.ts]: what is the reason for moving the multi-permissions requests on iOS to the JS side? this is less efficient because it requires asynchronous calls over the bridge for each permission in the request rather than just one for the entire request.

File: packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsInterface.h [hunk 49]
```diff
@@ -1,18 +1,37 @@
...
+
+@end
 
 @protocol UMPermissionsInterface
 
-- (NSDictionary *)getPermissionsForResource:(NSString *)resource;
-- (BOOL)hasGrantedPermission:(NSString *)permissionType;
+- (void)registerRequesters:(NSArray<id<UMPermissionsRequester>> *)newRequesters;
+
+- (void)getPermissionUsingRequesterClass:(Class)requesterClass
```
Comment (esamelson) [inline packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsInterface.h]: same comment as above for **both** methods added here -- should be resolver:resolve and rejecter:reject

File: packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsMethodsDelegate.h [hunk 50]
```diff
@@ -0,0 +1,22 @@
+// Copyright 2018-present 650 Industries. All rights reserved.
+
+#import <Foundation/Foundation.h>
+#import <UMPermissionsInterface/UMPermissionsInterface.h>
+
+@interface UMPermissionsMethodsDelegate : NSObject
+
++ (void)getPermissionWithPermissionsManager:(id<UMPermissionsInterface>)permissionsManager
+                              withRequester:(Class)requesterClass
+                                 withResult:(UMPromiseResolveBlock)resolve
```
Comment (esamelson) [inline packages/unimodules-permissions-interface/ios/UMPermissionsInterface/UMPermissionsMethodsDelegate.h]: same comment for both of these as well -- use `resolver:resolve` and `rejecter:reject`

**Review by esamelson — CHANGES_REQUESTED** [review]
Hi there! Thanks for taking on this job 🙂 It looks quite good overall! I've left a number of comments -- many are small style/spelling nits, but there are some important logic-related comments too.

In a big PR like this, having a thorough test plan is really important. Here are a few things I think need to be tested before we can land this:
- For standalone iOS and Android apps -- upgrading a current SDK 35 standalone app to a new build with this PR's changes, and making sure the previously granted permissions are still granted and do not need to be requested again. Since we're modifying the scoped permissions implementation and don't want this to break in people's production apps, this is critical to test.
- Same as above, but in the iOS and Android Expo clients. This is less critical than in production standalone apps, but still important for developer trust.
- Also, should test for the expected behavior when permissions are granted or denied from the initial request, then the status is subsequently changed in OS settings manually. This is difficult to write test-suite tests for but an important part of the API.

^If you've already tested any of those, awesome, just wanted to be sure! 😄 

One aside -- in the future please split giant PRs like this into smaller components (e.g. one PR for each unimodule). This makes it much more ergonomic and efficient to review.

File: android/expoview/src/main/java/host/exp/exponent/utils/PermissionsHelper.java [hunk 51]
```diff
@@ -1,10 +1,14 @@
 package host.exp.exponent.utils;
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply android/expoview/src/main/java/host/exp/exponent/utils/PermissionsHelper.java]: It's for ensuring back compatibility. We'll remove it later.

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/SimpleRequester.kt [hunk 52]
```diff
@@ -0,0 +1,36 @@
...
+  override fun parseAndroidPermissions(permissionsResponse: Map<String, PermissionsResponse>): Bundle {
+    return Bundle().apply {
+      // combined status is equal:
+      // granted when all needed permissions have been granted
+      // denied when all needed permissions have been denied
+      // undetermined if exist permission with undetermined status
+      val permissionsStatus = when {
+        getAndroidPermissions().all { permissionsResponse.getValue(it).status == PermissionsStatus.GRANTED } -> PermissionsStatus.GRANTED
+        getAndroidPermissions().all { permissionsResponse.getValue(it).status == PermissionsStatus.DENIED } -> PermissionsStatus.DENIED
+        else -> PermissionsStatus.UNDETERMINED
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/SimpleRequester.kt]: It isn't combined status. We add combined values in js before returning them to the user.

File: packages/expo-permissions/src/Permissions.ts (hunk 48 above)
Comment (lukmccall) [reply packages/expo-permissions/src/Permissions.ts]: I moved it to JS side because I thought, it'll be easier to maintain this in the future. Native iOS API wasn't created to request for multiple permissions at once. That's why our code was a little bit messy and difficult to read. 
Moreover, asking/getting `permissions` isn't something that user doing very often. Mostly, it's happed once per `permission`. So I think, it wouldn't affect performance a lot.

**Comment by lukmccall** [comment]
> In a big PR like this, having a thorough test plan is really important. Here are a few things I think need to be tested before we can land this:
> 
> * For standalone iOS and Android apps -- upgrading a current SDK 35 standalone app to a new build with this PR's changes, and making sure the previously granted permissions are still granted and do not need to be requested again. Since we're modifying the scoped permissions implementation and don't want this to break in people's production apps, this is critical to test.
> * Same as above, but in the iOS and Android Expo clients. This is less critical than in production standalone apps, but still important for developer trust.
> * Also, should test for the expected behaviour when permissions are granted or denied from the initial request, then the status is subsequently changed in OS settings manually. This is difficult to write test-suite tests for but an important part of the API.

I've done some testing. Also, I've tied to include all edge cases like changing permissions in setting manually (in expo-client it's inconsistent with settings. However, in the future we could add something like permissions screen to the client, which will display all applications with their permissions and possibility to change them) or changing between apps with different SDK versions.

Moreover, I'm going to test iOS again on Monday. To make sure that everything works fine.

File: packages/expo-permissions/src/Permissions.ts (hunk 48 above)
Comment (esamelson) [reply packages/expo-permissions/src/Permissions.ts]: OK, that makes sense. Thanks for explaining.

File: android/expoview/src/main/java/host/exp/exponent/utils/PermissionsHelper.java (hunk 51 above)
[the remark this answers is not in the document]
Comment (esamelson) [reply android/expoview/src/main/java/host/exp/exponent/utils/PermissionsHelper.java]: OK. Could we add a big comment to this file explaining that, as well as any places it's imported & used?

File: packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/SimpleRequester.kt (hunk 52 above)
[the remark this answers is not in the document]
Comment (esamelson) [reply packages/expo-permissions/android/src/main/java/expo/modules/permissions/requesters/SimpleRequester.kt]: Ah okay, I see. Thanks for the explanation. I still wonder whether this is the correct behavior, or if we should return `denied` if the user has denied any of the individual permissions.

Either way, we should document this -- would be great to have our docs be at this level of detail.

**Comment by esamelson** [comment]
Cool, sounds good. It would be awesome if you could be explicit about what cases you've tested -- for example I really like the checklist you made in the issue description detailing the steps, would be great to have something like that for test cases. That makes it easier for us to determine if anything got missed, or know if you're super thorough and have covered everything and beyond!

One question -- what exactly do you mean by 
> in expo-client it's inconsistent with settings
?

File: CHANGELOG.md [hunk 53]
```diff
@@ -29,10 +31,16 @@ This is the log of notable changes to the Expo client that are developer-facing.
 - Fixed `Calendar.getCalendarsAsync` rejecting on iOS 13, when `source.name` is null. ([#5994](https://github.com/expo/expo/pull/5994) by [@lukmccall](https://github.com/lukmccall))
 - Fixed handling URI with no scheme in `ExpoFileSystem`. ([#5904](https://github.com/expo/expo/pull/5904) by [@bbarthec](https://github.com/bbarthec))
 - Fixed `FileSystem#deleteAsync` in older Android SDKs. ([#5923](https://github.com/expo/expo/pull/5923) by [@bbarthec](https://github.com/bbarthec))
+  <<<<<<< HEAD
```
Comment (bbarthec) [inline CHANGELOG.md]: It's not right 😉

File: CHANGELOG.md [hunk 54]
```diff
@@ -29,10 +31,16 @@ This is the log of notable changes to the Expo client that are developer-facing.
...
 - Fixed image cropping on Android in `expo-image-manipulator`. ([#5828](https://github.com/expo/expo/pull/5828) by [@matiasmelendi](https://github.com/matiasmelendi))
 - Fixed type problem with `EXiOSOperatingSystemVersion` struct in `expo-gl-cpp`. ([#6063](https://github.com/expo/expo/pull/6063) by [@crubier](https://github.com/crubier))
 - Fixed blinking `Camera.Constants.FlashMode.torch` on iOS in `Camera`. ([#6128](https://github.com/expo/expo/pull/6128) by [@bbarthec](https://github.com/bbarthec))
 - Fixed race condition in `GoogleSignIn` on iOS. ([#5872](https://github.com/expo/expo/pull/5872) by [@vonovak](https://github.com/vonovak)])
+  ||||||| merged common ancestors
+  =======
+- Fixed crashes when the user tries to download a file through `react-native-webview` without granted storage permission on Android. ([#5061](https://github.com/expo/expo/pull/5061) by [@lukmccall](https://github.com/lukmccall))
+- Fixed `Permissions.getAsync` result, which was inconsistent with iOS settings. ([#5061](https://github.com/expo/expo/pull/5061) by [@lukmccall](https://github.com/lukmccall))
+  > > > > > > > [Permissions] Add requested changes
```
Comment (bbarthec) [inline CHANGELOG.md]: Please take care of it 🙏

File: ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m [hunk 55]
```diff
@@ -40,185 +32,123 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
...
+  UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Experience needs permissions"
+                                                                 message:message
+                                                          preferredStyle:UIAlertControllerStyleAlert];
+  [alert addAction:deny];
+  [alert addAction:allow];
+
+  UM_WEAKIFY(self);
+  [UMUtilities performSynchronouslyOnMainThread:^{
+    UM_ENSURE_STRONGIFY(self);
+    // TODO: below line is sometimes failing with: "Presenting view controllers on detached view controllers is discourage"
```
[the remark this answers is not in the document]
Comment (bbarthec) [reply ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m]: AFAIK this comment line is dangling here for a while, but I believe changes that are made quite a long time ago already fixed it 🤔

[the remark this answers is not in the document]
Comment (lukmccall) [reply ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m]: Unfortunately, I couldn't reproduce this behaviour and I've never encountered this error.

File: android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java [hunk 56]
```diff
@@ -82,6 +114,14 @@ protected void onCreate(Bundle savedInstanceState) {
     mReactRootView = new RNObject("com.facebook.react.ReactRootView");
 
     NativeModuleDepsProvider.getInstance().inject(BaseExperienceActivity.class, this);
+
+    if (mManifest == null) {
```
[the remark this answers is not in the document]
Comment (lukmccall) [reply android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java]: I've added this here because `HomeActivity` couldn't set this properly. Unforynelty, I'm not sure how can I set it in a suitable place.

**Comment by lukmccall** [comment]
An important note here. We need to publish a new home after merge. Without this, iOS will not work (it needs a new js code to work properly).

**Comment by sjchmiela** [comment]
Re: https://github.com/expo/expo/pull/5061#issuecomment-549575829 : you can publish home right now without breaking anything!

When building Expo client from `master` it fetches the app from [`dev-home-config.json`](https://github.com/expo/expo/blob/master/dev-home-config.json), which is a file you can modify and the change will only have an effect on your branch.

To publish dev home, use `et publish-dev-expo-home`. It should relogin to `@expo-home-dev` user, publish `home` and save its experience URL to `dev-home-config`. We will all get this change once the PR with this change is merged. 🙂

File: android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java (hunk 56 above)
[the remark this answers is not in the document]
Comment (esamelson) [reply android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java]: This should definitely be set in `HomeActivity`. Is the problem that you aren't able to get the manifest from that activity? If so, does this comment help? https://github.com/expo/expo/pull/6162#discussion_r343451589 😄

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java [hunk 57]
```diff
@@ -76,18 +76,46 @@ public void onCreate(ModuleRegistry moduleRegistry) {
...
+  }
+
+  @ExpoMethod
+  public void getPermissionsAsync(final Promise promise) {
+    Permissions permissionsManager = mModuleRegistry.getModule(Permissions.class);
+    if (permissionsManager == null) {
+      promise.reject("E_NO_PERMISSIONS", "Permissions module is null. Are you sure all the installed Expo modules are properly linked?");
+      return;
+    }
+    if (permissionsManager.isPermissionPresentInManifest(Manifest.permission.WRITE_CALENDAR)) {
```
[the remark this answers is not in the document]
Comment (esamelson) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java]: it looks like this still needs to be fixed? unless github is showing me the wrong thing

**Review by esamelson — COMMENTED** [review]
a few followups to previous comments but this otherwise looks good 👍 awesome work!!

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java (hunk 57 above)
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java]: Thanks for notice this. I fixed it.

**Review by esamelson — APPROVED** [review]
