### PR TITLE
[ios] remove legacy naming and fix manifest caching in Expo client

### LINKED ISSUE #2424: [ios] after downloading new build from App Store, app occasionally reverts to using old JS bundle
We've had a few reports of apps reverting to an older version of the JS bundle after updating to a new build through the App Store. It seems like this is an occasional issue when the app has been installed on the user's device for a long time. My guess is that this is an issue with the legacy naming of embedded bundles, meaning it won't affect new apps installed now for the first time, but may affect devices that have had the app installed since before May.

https://forums.expo.io/t/expo-uses-old-code-even-though-new-code-has-been-deployed/14764

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Fixes #2424 . Also fixes an issue I found while testing where OTA updates do not cache properly in the expo client 😱 (not totally sure when this started)

# How

Standalone apps are single-version now, so we can remove all of the legacy stuff. This means there is no chance of getting into a weird code path which ends up loading a really old bundle with a legacy filename.

Also noticed that the `[EXManifestResource _chooseManifest:]` selector was sometimes returning an `NSError` object, but this was not handled in the calling method, which would probably cause a native crash. I changed this selector to receive an error pointer and handled it in the calling method.

Finally, manifests were not getting cached properly in the Expo client because we were failing to properly escape the filename. I've fixed this by passing `resourceName` through the superclass, which does escape the string.

# Test Plan

- [x] need to test standalone apps to make sure OTA updates still work
- [x] test installing a new standalone app build over an old build
- [x] OTA updates in expo client cache properly again

### CODE REVIEW

File: ios/Exponent/Kernel/AppLoader/CachedResource/EXCachedResource.h [hunk 1]
```diff
@@ -8,16 +8,14 @@ NS_ASSUME_NONNULL_BEGIN
 
 @interface EXCachedResource : NSObject <EXResourceLoader>
 
+@property (nonatomic, readonly) NSString *resourceName;
```
Comment (quinlanj) [inline ios/Exponent/Kernel/AppLoader/CachedResource/EXCachedResource.h]: how come we are moving this field from EXManifestResouce?

**Review by quinlanj — APPROVED** [review]
lgtm, few minor comments

File: ios/Exponent/Kernel/AppLoader/CachedResource/EXCachedResource.h (hunk 1 above)
Comment (esamelson) [reply ios/Exponent/Kernel/AppLoader/CachedResource/EXCachedResource.h]: it already exists on `EXCachedResource` and in there we run in through `[EXUtil escapedResourceName:]` https://github.com/expo/expo/blob/c5a18838f760ccb06b4c4c799bcb85d5b9ce005c/ios/Exponent/Kernel/AppLoader/CachedResource/EXCachedResource.m#L31 so this allows `EXManifestResource` to access that property.

We could instead keep the property on `EXManifestResource` and also run it through that selector, but I thought this way was cleaner (the other way, the subclass has a property with the same name as the super but the property is actually different). Let me know if you think that's okay.
