### PR TITLE
[symbols] Fix import error on web

### LINKED ISSUE #30233: [expo-symbols] The method or property expo-modules-core.requireNativeViewManager is not available on web
### Minimal reproducible example

https://snack.expo.dev/@nfrmn/expo-symbols-web-crash

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

Yes

### Summary

The `expo-symbols` library is iOS-only and provides access to Apple's SF Symbols icon pack.

For unsupported platforms there is a `fallback` prop that renders an alternative icon. This works correctly on Android.

However due to the implementation of the library, the absence of `requireNativeViewManager` on web causes a runtime crash.

For cross-platform Expo projects that target web in addition to iOS/Android, this means that `expo-symbols` is unusable.

I understand `expo-symbols` is in beta, but personally we are required to have it in the project due to Apple's requirements to use their specific icon on a gated feature.

For this reason I humbly request a quick fix to this library - would be extremely grateful. If you guys are not prioritising development of `expo-symbols` right now, I would also be happy to try undertaking this fix myself, which I would probably approach by making a `.web.tsx` environment specific file. Just give me direction/approval for me to fix it myself.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/freeman/.rvm/gems/ruby-3.0.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.17 => 51.0.17 
      expo-router: ~3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #30233
Fixes error when using `requireNativeViewManager` on web

# How
Only call `requireNativeViewManager` when not on web. Add `web` to the fallback check so it can be used on web too.

# Test Plan
NCL on web. Symbol screen now renders correctly

### CODE REVIEW

**Review by amandeepmittal — APPROVED** [review]

File: packages/expo-symbols/src/SymbolView.tsx [hunk 1]
```diff
@@ -2,11 +2,13 @@ import { Platform, requireNativeViewManager } from 'expo-modules-core';
 
 import { NativeSymbolViewProps, SymbolViewProps } from './SymbolModule.types';
 
-const NativeView: React.ComponentType<NativeSymbolViewProps> =
-  requireNativeViewManager('SymbolModule');
+let NativeView: React.ComponentType<NativeSymbolViewProps>;
+if (Platform.OS !== 'web') {
+  NativeView = requireNativeViewManager('SymbolModule');
+}
```
Comment (tsapeta) [inline packages/expo-symbols/src/SymbolView.tsx:8]: Wouldn't it be more clear if moved to a `*.web.tsx` file?

Comment (alanjhughes) [reply packages/expo-symbols/src/SymbolView.tsx:8]: Maybe. There's not really any consistency to how we do this across the packages. A web file would just be 
```typescript
export function SymbolView(props: SymbolViewProps) {
    return props.fallback  
}
```

Comment (alanjhughes) [reply packages/expo-symbols/src/SymbolView.tsx]: Updated it

**Review by tsapeta — APPROVED** [review]
