### PR TITLE
[image-picker][Android] Allow picking very large files (e.g. video 700MB)

### LINKED ISSUE #3953: ImagePickerModule: java.lang.OutOfMemoryError
## 🐛 Bug Report

OutOfMemory with file size 700MiB
```
04-09 16:59:32.611 14789 14814 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 704165528 byte allocation with 6609432 free bytes and 505MB until OOM, max allowed footprint 13218864, growth limit 536870912
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at abi32_0_0.host.exp.exponent.modules.api.ImagePickerModule.writeVideo(ImagePickerModule.java:486)
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at abi32_0_0.host.exp.exponent.modules.api.ImagePickerModule.access$1700(ImagePickerModule.java:59)
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at abi32_0_0.host.exp.exponent.modules.api.ImagePickerModule$1.run(ImagePickerModule.java:345)
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-09 16:59:32.611 14789 14814 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:764)
```
### Environment

Expo SDKv32

### Steps to Reproduce

Select a video 700MiB

### Expected Behavior

Select file success and return the Url

### Actual Behavior

App Crashed with error OutOfMemory

https://github.com/expo/expo/blob/eff89d3614fe4fe9b5dfb0e2d6ef89b36c2acb41/android/versioned-abis/expoview-abi32_0_0/src/main/java/abi32_0_0/host/exp/exponent/modules/api/ImagePickerModule.java#L484-L491

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves #3953

# How

Android now reads and writes file in chunks.

# Test Plan

Fetch your Android device with large video file.
Open this [**snack**](https://snack.expo.io/@barthec/YW5kcm) and select your large file.

### CODE REVIEW

**Comment by giautm** [comment]
Hi, please include this in SDKv33 release.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java [hunk 1]
```diff
@@ -663,12 +663,13 @@ private String writeVideo(Uri uri) {
...
       if (in != null) {
-        byte[] buffer = new byte[in.available()];
-        in.read(buffer);
-
         path = ExpFileUtils.generateOutputPath(mContext.getCacheDir(), "ImagePicker", ".mp4");
         out = new FileOutputStream(path);
-        out.write(buffer);
+        byte[] buffer = new byte[4096];
+        int bytesRead;
+        while ((bytesRead = in.read(buffer)) > 0) {
```
Comment (illume) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java]: This condition seems wrong.
"the total number of bytes read into the buffer, or -1 if there is no more data because the end of the file has been reached."

Should it be? `while ((bytesRead = in.read(buffer)) != -1) {`

Comment (bbarthec) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java]: Apparently there is built-in-java-sdk function `Files.copy` (http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/be30cb2a3088/src/share/classes/java/nio/file/Files.java#l2902) that performs copying exactly the same way 😄 
But thank you for pointing that out, because I will replace my implementation with using already-provided one 🙇

**Review by mczernek — APPROVED** [review]

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java (hunk 1 above)
Comment (bbarthec) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java]: It turned out that using `Files.copy` would be harder than just invoking that method, because it requires some specific arguments that are not easily obtainable - therefore I leave the code as is.

**Comment by illume** [comment]
Seems like there's still a bug in this which leads to corrupt files.

**Comment by bbarthec** [comment]
@illume would you mind providing some more information upon bug you're mentioning? I've successfully picked 700MB< video with this fix.
