### PR TITLE
[iOS][expo-speech] Add method which returns list of all available voices

### LINKED ISSUE #3186: voiceIOS option for Expo.Speech doesn't work
### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19 (Tara)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/bin/node
      npm: 6.5.0 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @types/react: ^16.3.10 => 16.7.18
      @types/react-native: ^0.55.2 => 0.55.28
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.3 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

1. Download the iOS Voice in Settings -> General -> Accessibility -> Speech -> Voice, and download the voice you want to use (For this example, Aurelie voice in French) 
2. Call this function in your app : 

`Expo.Speech.speak("Bonjour le monde", {language: 'fr', voiceIOS: 'Aurelie'});`

3. As you hear it doesn't use the voice you choose, it uses the default voice, but IF you select Aurelie as default speech voice in your iOS settings, it speaks with this voice.

The 'voiceIOS' option is ignored.

### Expected Behavior

Expected to speak with the voice defined in the 'voiceIOS option'

### Actual Behavior

Speaks with the selected voice in iOS settings.

### Reproducible Demo

Sorry, no time to make this, but it's pretty easy to make.

Thank you very much !

### PR DESCRIPTION
**Pull request by Szymon20000**
# Why

closes : https://github.com/expo/expo/issues/3186

# How

# Test Plan

run NCL-textToSpeech.

### CODE REVIEW

File: apps/native-component-list/screens/TextToSpeechScreen.js [hunk 1]
```diff
@@ -126,6 +146,11 @@ export default class TextToSpeechScreen extends React.Component {
     });
   };
 
+  _showAllVoices = async () => {
+    let availableVoices = await Speech.getAvailableVoicesAsync();
```
Comment (tsapeta) [inline apps/native-component-list/screens/TextToSpeechScreen.js]:
```suggestion
    const availableVoices = await Speech.getAvailableVoicesAsync();
```

File: apps/native-component-list/screens/TextToSpeechScreen.js [hunk 2]
```diff
@@ -126,6 +146,11 @@ export default class TextToSpeechScreen extends React.Component {
...
+    console.log('availableVoices ', JSON.stringify(availableVoices));
```
Comment (tsapeta) [inline apps/native-component-list/screens/TextToSpeechScreen.js]: NCL is not only used in debug mode, we need to show this to the user 😉 
```suggestion
   alert('Available voices: ' + availableVoices);
```

File: docs/pages/versions/unversioned/sdk/speech.md [hunk 3]
```diff
@@ -18,7 +18,7 @@ Speak out loud the `text` given `options`. Calling this when another text is bei
 -   **options : `object`** --
 
       A map of options:
-
+    -   **voiceIOS : `string`** -- Voice identifier (iOS only)
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/speech.md]: Since this parameter was not documented, can we remove `IOS` suffix?
```suggestion
    -   **voice : `string`** -- Voice identifier (**iOS only**)
```

File: packages/expo-speech/src/Speech/Speech.ts [hunk 4]
```diff
@@ -61,6 +61,10 @@ export function speak(text: string, options: SpeechOptions = {}) {
   ExponentSpeech.speak(String(id), text, options);
 }
 
+export async function getAvailableVoicesAsync() {
+  return ExponentSpeech.getVoices();
```
Comment (tsapeta) [inline packages/expo-speech/src/Speech/Speech.ts]: We might need to check whether `ExponentSpeech.getVoices` exists and throw `UnavailabilityError` if not.

File: docs/pages/versions/unversioned/sdk/speech.md [hunk 5]
```diff
@@ -46,3 +46,20 @@ Determine whether the Text-to-speech utility is currently speaking. Will return
...
+
+List of `Voice` objects.
+
+##### `Voice`
+
+|    Field   |               Type               |
+|:----------:|:--------------------------------:|
+| identifier |              string              |
+|    name    |              string              |
+|   quality  | string ("Default" or "Enhanced") |
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/speech.md]: What do you think about enum `Speech.VoiceQuality`? I'd prefer that our users use enums instead of plain strings as there is higher probability they do a typo in a plain string (IDE suggests enums) and also we wouldn't be able to change such values in the future, without a breaking change.

```typescript
enum VoiceQuality {
  Default = "default",
  Enhanced = "enhanced",
}
```

File: apps/native-component-list/screens/TextToSpeechScreen.js [hunk 6]
```diff
@@ -107,6 +118,14 @@ export default class TextToSpeechScreen extends React.Component {
     );
   }
 
+  _getRandomVoice = () => {
+    if (Math.random() > 0.5) {
```
Comment (tsapeta) [inline apps/native-component-list/screens/TextToSpeechScreen.js]: Maybe we could take a random voice from the list of available voices? 🤔 Just thinking out loud 😄

**Review by tsapeta — CHANGES_REQUESTED** [review]
Looks great 💪 just a few minor comments 😉

File: packages/expo-speech/src/Speech/Speech.ts [hunk 7]
```diff
@@ -61,6 +66,13 @@ export function speak(text: string, options: SpeechOptions = {}) {
   ExponentSpeech.speak(String(id), text, options);
 }
 
+export async function getAvailableVoicesAsync(): Promise<any> {
```
Comment (tsapeta) [inline packages/expo-speech/src/Speech/Speech.ts]: could you add an interface for `Voice` objects and change the return type to `Promise<Voice[]>`?

**Review by tsapeta — APPROVED** [review]

File: CHANGELOG.md [hunk 8]
```diff
@@ -6,11 +6,13 @@ This is the log of notable changes to the Expo client that are developer-facing.
 
 ### 🛠 Breaking changes
 
+- `Expo.Speech.speak` changed option name from `voiceIOS` to `voice`. [@Szymon20000](https://github.com/Szymon20000) ([#3423](https://github.com/expo/expo/pull/3423))
```
Comment (tsapeta) [inline CHANGELOG.md]:
```suggestion
- `Speech.speak` changed option name from `voiceIOS` to `voice`. [@Szymon20000](https://github.com/Szymon20000) ([#3423](https://github.com/expo/expo/pull/3423))
```

File: CHANGELOG.md [hunk 9]
```diff
@@ -6,11 +6,13 @@ This is the log of notable changes to the Expo client that are developer-facing.
...
 - `ImageManipulator.manipulateAsync` is now accepting `ImageManipulator.FlipType.{Vertical, Horizontal}` as flipping action parameter and `ImageManipulator.SaveFormat.{JPEG, PNG}` as saving option [@bbarthec](https://github.com/bbarthec) ([#3245](https://github.com/expo/expo/pull/3245))
 - removed `devKernel` and `prodKernel` build flavors from Android ExpoKit projects (all Gradle commands become simply `[verb](Debug|Release)`, e.g. `installDebug` or `assembleRelease`) by [@esamelson](https://github.com/esamelson) ([#3386](https://github.com/expo/expo/pull/3386))
 
 ### 🎉 New features
 
+- added method `Expo.Speech.getAvailableVoicesAsync()` [@Szymon20000](https://github.com/Szymon20000) ([#3423](https://github.com/expo/expo/pull/3423))
```
Comment (tsapeta) [inline CHANGELOG.md]:
```suggestion
- added method `Speech.getAvailableVoicesAsync()` [@Szymon20000](https://github.com/Szymon20000) ([#3423](https://github.com/expo/expo/pull/3423))
```

**Review by tsapeta — APPROVED** [review]
