### PR TITLE
[expo-gl-cpp] enable stencil buffer on Android

### LINKED ISSUE #3893: [GLView] 2D context doesn't work on Android because it requests 0 bits for stencil buffer
Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.14

For Android/iOS

### Steps to Reproduce

Attempt to run the example from 
https://blog.expo.io/introducing-the-canvas-2d-context-api-for-expo-8ba6106ed8e5

Or this cutdown example which screenshots are of:
https://snack.expo.io/@innershed/expo2d-android

### Expected Behavior

To draw a purple line, like this (iOS):
image

### Actual Behavior

Entire canvas area is filled with purple, adjusting `moveTo` and `lineTo` parameters has no effect.
image
A warning is given in the console: `WARNING: Was given 0 stencil bits - strokes and clipping will be broken`

### Reproducible Demo
https://snack.expo.io/@innershed/expo2d-android

### PR DESCRIPTION
**Pull request by wkozyra95**
# Why

Fixes #3893

# How

Request EGL context with stencil buffer

# Test Plan

Added ncl example

### CODE REVIEW

File: apps/native-component-list/src/screens/GL/GLScreens.tsx [hunk 1]
```diff
@@ -3,6 +3,7 @@ import './BeforePIXI';
 import * as React from 'react';
 import { Platform } from '@unimodules/core';
 import { Asset } from 'expo-asset';
+import Expo2DContext from 'expo-2d-context';
```
Comment (bbarthec) [inline apps/native-component-list/src/screens/GL/GLScreens.tsx:6]:
```suggestion
import Expo2DContext from 'expo-2d-context';
```
Do we really want to add this lib here? What's it's purpose here? 🤔

**Review by bbarthec — COMMENTED** [review]
I'm not sure why are you adding this `expo-2d-context` lib? Cannot we use some `three.js`/`pixi.js` api as we do in other examples?

File: apps/native-component-list/src/screens/GL/GLScreens.tsx (hunk 1 above)
Comment (wkozyra95) [reply apps/native-component-list/src/screens/GL/GLScreens.tsx:6]: this is canvas implementation, neither three js nor pixi does not implement it. Bug mentioned in the linked issue was  showing up when using this library, so decided to use it.
