### PR TITLE
@tommy/docs header css bugs

### LINKED ISSUE #9284: [docs] Search bar overlaps menu on wide screens
new

Happens on Chrome (MacOS), using a 4K screen and QHD ultrawide.

### PR DESCRIPTION
**Pull request by tommybru**
# Why

Closes #9284  

As well as fixes small design updates after testing

# Search Bar Updates

- Following [expo.io](expo.io), switches to use a default font for search bar input for vertical text-centering given our font's off-center nature
- Auto-focuses now on mobile for a better experience
- Removes default mobile webkit appearance

### Input
Screen Shot 2020-07-17 at 8 14 43 PM

### Mobile
Jul-17-2020 20-19-49

### Input
Screen Shot 2020-07-17 at 8 15 51 PM

### Mobile
Jul-17-2020 20-32-38

# Max-width bug
- Adds a max-width property on the search bar to prevent it from taking up too much space on ultra wide screens, re: @byCedric 

# Expo logo and tabs

- Replaces logo as one svg to be an SDK svg + "Expo" text in order to be more flexible
- Shifts down tabs text to vertically center them

## Before
Screen Shot 2020-07-17 at 8 45 55 PM

## After
Screen Shot 2020-07-17 at 8 44 57 PM

### CODE REVIEW

File: docs/components/plugins/AlgoliaSearch.js [hunk 1]
```diff
@@ -181,6 +176,11 @@ class AlgoliaSearch extends React.Component {
         },
       ],
     });
+
+    //auto-focuses on mobile
+    if (!this.props.hiddenOnMobile) {
+      document.getElementById('algolia-search-box-mobile').focus();
```
Comment (jonsamp) [inline docs/components/plugins/AlgoliaSearch.js:182]: A 'more react' way to do this is to use react's `createRef` hook, put a `ref` on the `<input />` element, then call `ref.current.focus()`. The main benefit of using react to call `.focus()` on a `ref` would be if there's ever a case where there are two things with the same id on the same page. I don't think that's a danger here, but something to consider to make this code more maintainable in the future. --im also happy to explain how to do this next week!

File: docs/static/libs/algolia/algolia-mobile.css [hunk 2]
```diff
@@ -45,14 +46,13 @@
   }
 }
 
-/* !important tags, box-shadow are needed for desktop, but make overwritting difficult, so moved out of algolia.min.css */
+/* !important tags are needed for desktop but are difficult to overwrite, so moved out of algolia.min.css */
```
Comment (jonsamp) [inline docs/static/libs/algolia/algolia-mobile.css:49]: I don't think this comment is needed, especially with the one that's at the top of this file. Also, does this actually move something out of **algolia.min.css**? Doesn't it override it instead?

**Review by jonsamp — APPROVED** [review]
these before/after shots are great. thanks for being detail oriented and fixing these!

File: docs/static/libs/algolia/algolia-mobile.css (hunk 2 above)
Comment (tommybru) [reply docs/static/libs/algolia/algolia-mobile.css:49]: Yes I moved some position styling out of **algolia.min.css** because it uses **!important** (and needs to in order to work on desktop). 

My mobile media queries didn't seem to override it (even when they themselves had **!important**). So I moved those **!important** position styles here under a desktop media query -- happy to talk next week about ways to work on this!!

Comment (jonsamp) [reply docs/static/libs/algolia/algolia-mobile.css:49]: This sounds tricky! I wonder how we created algolia.min.css. If someone were to generate it/upgrade it to a new algolia version, would it break these changes? If it might, we should search for another approach. Let's talk next week!!

**Comment by brentvatne** [comment]
i think we can shift the text in the buttons down just a bit more still. sometimes vertically cantering doesn’t feel quite right and you need to bias it a bit more towards the bottom, in this case i think an additional 2px or so of top padding on the text would look better

**Comment by tommybru** [comment]
> i think we can shift the text in the buttons down just a bit more still. sometimes vertically cantering doesn’t feel quite right and you need to bias it a bit more towards the bottom, in this case i think an additional 2px or so of top padding on the text would look better

Sg! I think a total of 2px (so just an additional 1px) looks best, but open to feedback:

## 2px total
Screen Shot 2020-07-20 at 11 19 59 AM

## 3px total

Screen Shot 2020-07-20 at 10 57 31 AM

File: docs/components/DocumentationHeader.js [hunk 3]
```diff
@@ -7,6 +7,7 @@ import AlgoliaSearch from '~/components/plugins/AlgoliaSearch';
 
 const STYLES_LOGO = css`
   display: flex;
+  cursor: pointer;
```
Comment (jonsamp) [inline docs/components/DocumentationHeader.js:10]: ❤️

File: docs/static/libs/algolia/algolia.min.css [hunk 4]
```diff
@@ -1,467 +1,2 @@
-.searchbox {
```
Comment (jonsamp) [inline docs/static/libs/algolia/algolia.min.css:1]: Im assuming that this diff makes this file identical to `master`? (Did you run `git co master static/libs/algolia/algolia.min.css`, then commit that?)

File: docs/static/libs/algolia/algolia-mobile.css [hunk 5]
```diff
@@ -7,25 +7,26 @@
     margin-bottom: 0px;
   }
 
-  .algolia-autocomplete.algolia-autocomplete-left {
-    left: 0px !important;
+  .algolia-autocomplete.algolia-autocomplete-right .ds-dropdown-menu {
+    left: -16px !important;
```
Comment (jonsamp) [inline docs/static/libs/algolia/algolia-mobile.css:11]: Are these `!important` flags still necessary? (they might be, I'm just unsure why)

**Review by jonsamp — APPROVED** [review]
Nice fixes. I haven't run this locally but the code is looking good. Left a couple comments but nothing that should block this from shipping.

File: docs/static/libs/algolia/algolia.min.css (hunk 4 above)
Comment (tommybru) [reply docs/static/libs/algolia/algolia.min.css:1]: yes, kinda! master currently has an edited version of mine of algolia.min.css -- so I git checkout-ed (haha) from the [last commit](https://github.com/expo/expo/commit/2a30c4fb4f65da6d9303f68936d30496c5e5c645#diff-c5ef6e0d71e5aa5afd0d72a862e27f3a) before mine

File: docs/static/libs/algolia/algolia-mobile.css (hunk 5 above)
Comment (tommybru) [reply docs/static/libs/algolia/algolia-mobile.css:11]: Just double-checked and they are necessary -- the `algolia.min.css` was pretty difficult to override:

Screen Shot 2020-07-20 at 9 05 32 PM

This might be how `!important` works or how overridding works and I'd love to learn more --- but if I don't have _both_ of these lines, inspectElement would show my media queries crossed out (and `algolia.min.css` taking precedence)

Comment (tommybru) [reply docs/static/libs/algolia/algolia-mobile.css:11]: For reference (or `ref`, haha), `algolia.min.css` has this property that I had to override:

Screen Shot 2020-07-20 at 9 14 47 PM

Comment (jonsamp) [reply docs/static/libs/algolia/algolia-mobile.css:11]: Ah interesting, it looks like we are a bit behind on our algolia styling because we copy/pasted it from the source and are now running our own version. (The CSS version we should be using is [here](https://cdn.jsdelivr.net/npm/docsearch.js@2.5.2/dist/cdn/docsearch.min.css)). --This is another ticket/task (to add these new styles and edit our overrides).

Also, since the source we are using uses `!important`, it forces us to as well. 

Thanks for digging into this!
