### PR TITLE
[web-browser][plugin] Fix multiple runs of prebuild without clean

### LINKED ISSUE #39698: Expo WebBrowser - experimentalLauncherActivity - Prebuild issue
### Minimal reproducible example

npx expo run prebuild

### Steps to reproduce

- Simply install the expo web browser
- Turn on experimentalLauncherActivity in the app.json
- run a prebuild than run it again.

The MainApplication.kt  will contain multiple duplicated content. If you run it again than it will be there for the 3th time

Image

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.3 - ~/.nvm/versions/node/v20.18.3/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.18.3/bin/yarn
      npm: 11.4.1 - ~/.nvm/versions/node/v20.18.3/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: 53.0.22 => 53.0.22 
      expo-router: ~5.1.5 => 5.1.5 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.6 => 0.79.6 
      react-native-web: ^0.20.0 => 0.20.0 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
14/17 checks passed. 3 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar. 


✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  Untested on New Architecture: react-native-bouncy-checkbox
  No metadata available: @turf/turf
Advice:
Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

✖ Check that packages match versions required by installed Expo SDK
The following packages should be updated for best compatibility with the installed expo version:
  expo-router@5.1.5 - expected version: ~5.1.6
  react-native@0.79.6 - expected version: 0.79.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice:
Use 'npx expo install --check' to review and upgrade your dependencies.
To ignore specific packages, add them to "expo.install.exclude" in package.json. Learn more: https://expo.fyi/dependency-validation

3 checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #39698

# How
With the `expo-web-browser` plugin, multiple runs of prebuild will make the code modifications multiple times resulting in error. Added some checks so it is safe to run multiple times without `--clean`

# Test Plan
Sandbox ✅

### CODE REVIEW

File: packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts [hunk 1]
```diff
@@ -7,6 +7,7 @@ import {
   withDangerousMod,
   withMainApplication,
 } from 'expo/config-plugins';
+import { existsSync } from 'fs';
```
Comment (Kudo) [inline packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts]:
```suggestion
import fs from 'fs';
```

File: packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts [hunk 2]
```diff
@@ -62,6 +63,16 @@ function addLauncherClassToProject(config: ExpoConfig) {
     'android',
     async (config) => {
       const fileName = 'BrowserLauncherActivity.kt';
+      const dir = path.dirname(
+        AndroidConfig.Paths.getProjectFilePath(config.modRequest.projectRoot, 'MainApplication')
+      );
+
+      const fullPath = path.join(dir, fileName);
+
+      if (existsSync(fullPath)) {
```
Comment (Kudo) [inline packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts]:
```suggestion
      if (fs.existsSync(fullPath)) {
```

File: packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts [hunk 3]
```diff
@@ -102,11 +108,14 @@ function modifyMainApplication(config: ExpoConfig) {
       false
```
Comment (Kudo) [inline packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts:107]: <p class='graphite__hidden'><i>[Re: line +105]</i></p>
rename this as `let contents = addImports(`
<p class='graphite__hidden'>See this comment inline on <a href="https://app.graphite.dev/github/pr/expo/expo/39702?utm_source=unchanged-line-comment">Graphite</a>.</p>

File: packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts [hunk 4]
```diff
@@ -102,11 +108,14 @@ function modifyMainApplication(config: ExpoConfig) {
...
+    let onCreateMod = importsMod;
+    if (!importsMod.includes('registerActivityLifecycleCallbacks(lifecycleCallbacks)')) {
+      onCreateMod = appendContentsInsideDeclarationBlock(
+        importsMod,
+        'onCreate',
+        '  registerActivityLifecycleCallbacks(lifecycleCallbacks)'
+      );
+    }
 
     const result = addMainApplicationMod(onCreateMod);
```
Comment (Kudo) [inline packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts]:
```suggestion
    if (!importsMod.includes('registerActivityLifecycleCallbacks(lifecycleCallbacks)')) {
      contents = appendContentsInsideDeclarationBlock(
        contents,
        'onCreate',
        '  registerActivityLifecycleCallbacks(lifecycleCallbacks)'
      );
    }

    const result = addMainApplicationMod(contents);
```

**Review by Kudo — CHANGES_REQUESTED** [review]
good to add unit tests for the re-entrance case

File: packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts]: I'll need to name it something else. We already have an fs from `fs/promises`

Comment (Kudo) [reply packages/expo-web-browser/plugin/src/withWebBrowserAndroid.ts]: there's just one existing callsite, that's `fs.writeFile`, you can replace it with
```
import fs from 'fs';

await fs.promises.writeFile(...)
```

**Review by Kudo — APPROVED** [review]
thanks for following up my comments
