### PR TITLE
[contacts] Added contacts image remote uri validation

### LINKED ISSUE #38855: [expo-contacts] Android presentFormAsync android `image` fails with: "No content provider"
### Minimal reproducible example

https://github.com/ginoraviola/ec-contacts-avatar

### Steps to reproduce

 1. Clone and setup the project:
  git clone [repository-url]
  cd contacts-avatar-android
  npm install
  2. Start the Expo development server:
  npm run android
  3. Test the issue:
    - Open the app on Android device
    - Grant contacts permission when prompted
    - Tap "Present Contact Form (with image)" button

  Expected behavior: Contact form should open with the avatar image displayed properly

  Actual behavior: The contact form fails to present or crashes when trying to display the contact with an avatar image (App.tsx:34-36 defines the image URI)

presentFormAsync error: [Error: Call to function 'ExpoContacts.presentFormAsync' has been rejected.
→ Caused by: java.io.FileNotFoundException: No content provider: /150x150/007ACC/FFFFFF]

Image

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
      Watchman: 2025.04.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/ginoraviola/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2025.1 AI-251.25410.109.2511.13752376
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.20 => 53.0.20 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.5 => 0.79.5 
    npmGlobalPackages:
      eas-cli: 16.3.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by hryhoriiK97**
# Why
Based on this [issue](https://github.com/expo/expo/issues/38855), I think it would be helpful to have a validation of the remote image URI for contacts when using presentFormAsync.

Simulator Screenshot - iPhone 16 Pro - 2025-09-14 at 21 34 27

Fixes: #38855

# How

# Test Plan

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt [hunk 1]
```diff
@@ -367,7 +367,12 @@ class ContactsModule : Module() {
     if (data.containsKey("image")) {
       val image = data["image"]
       if (image is Map<*, *> && image.containsKey("uri")) {
-        contact.photoUri = image["uri"] as String?
+        val uri = image["uri"] as String?
+        // Check if this is a remote URI (http/https)
+        if (uri != null && (uri.startsWith("http://") || uri.startsWith("https://"))) {
```
Comment (vonovak) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt]: If I understand correctly, this feature requires file:// uris.

In that case we should check that this is a file uri, rather than checking what it's not.

File: packages/expo-contacts/ios/ContactsModule.swift [hunk 2]
```diff
@@ -553,6 +553,11 @@ public class ContactsModule: Module, OnContactPickingResultHandler {
       throw FilePermissionException(uri)
     }
 
+    // Check if this is a remote URI (http/https)
+    guard url.scheme != "http" && url.scheme != "https" else {
```
Comment (vonovak) [inline packages/expo-contacts/ios/ContactsModule.swift]: The original issue report was for android; does ios suffer from the same issue?

**Review by vonovak — CHANGES_REQUESTED** [review]
Thanks for the PR, left some suggestions and a question.

File: packages/expo-contacts/ios/ContactsExceptions.swift [hunk 3]
```diff
@@ -113,3 +113,9 @@ internal final class AccessPickerAlreadyPresentedException: Exception {
     "Contact access picker is already presented"
   }
 }
+
+internal final class RemoteImageUriException: Exception {
+  override var reason: String {
+    "Remote image URIs are not supported. Please download the image first using File.downloadFileAsync from expo-file-system and provide a local URI."
```
Comment (vonovak) [inline packages/expo-contacts/ios/ContactsExceptions.swift]: The exception could contain the URL which user provided for better traceability.

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt (hunk 1 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt]: Thanks for the comment - I've updated it. [2dcde31](https://github.com/expo/expo/pull/39658/commits/2dcde31f08f390a2290ad2a21bd5791eb75a2413)

File: packages/expo-contacts/ios/ContactsModule.swift (hunk 2 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/ios/ContactsModule.swift]: Yes, I've checked, and iOS also doesn't support remote URIs. We didn't get any exception, but the images weren't displayed.

File: packages/expo-contacts/ios/ContactsExceptions.swift (hunk 3 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/ios/ContactsExceptions.swift]: Done - [2dcde31](https://github.com/expo/expo/pull/39658/commits/2dcde31f08f390a2290ad2a21bd5791eb75a2413)

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt [hunk 4]
```diff
@@ -553,7 +554,7 @@ class Contact(var contactId: String, var appContext: AppContext) {
 
   private fun getThumbnailBitmap(photoUri: String?): Bitmap {
     val context = appContext.reactContext ?: throw Exceptions.ReactContextLost()
-    val uri = Uri.parse(photoUri)
+    val uri = Uri.fromFile(File(photoUri))
```
Comment (hryhoriiK97) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: @vonovak I found another issue while testing on Android. Uri.parse doesn't work for local file paths - it looks like it should be handled by Uri.fromFile 🤔

Screenshot_1757880014

Comment (vonovak) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: maybe this place should be updated to just pass `photoUri` string https://github.com/expo/expo/blob/main/packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt#L528-L528

it's a bit awkward to convert `val x = Uri.parse(photoUri).path` -> `Uri.fromFile(File(x))`

in `val uri = Uri.fromFile(File(photoUri))` the `photoUri` can be null but `File` constructor doesn't expect to receive `null`

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt [hunk 5]
```diff
@@ -367,7 +367,12 @@ class ContactsModule : Module() {
     if (data.containsKey("image")) {
       val image = data["image"]
       if (image is Map<*, *> && image.containsKey("uri")) {
-        contact.photoUri = image["uri"] as String?
+        val uri = image["uri"] as String?
+        // Check if this is a file URI (required for local images)
```
Comment (vonovak) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt]:
```suggestion
```

the code is self-evident in this case

File: packages/expo-contacts/ios/ContactsModule.swift [hunk 6]
```diff
@@ -553,6 +553,11 @@ public class ContactsModule: Module, OnContactPickingResultHandler {
       throw FilePermissionException(uri)
     }
 
+    // Check if this is a file URI (required for local images)
```
Comment (vonovak) [inline packages/expo-contacts/ios/ContactsModule.swift]:
```suggestion
    // Check if this is a file URI (required for local images)
```

File: packages/expo-contacts/ios/ContactsExceptions.swift [hunk 7]
```diff
@@ -113,3 +113,16 @@ internal final class AccessPickerAlreadyPresentedException: Exception {
...
+internal final class RemoteImageUriException: Exception {
+  private let providedUri: String
+
+  init(_ uri: String) {
+    self.providedUri = uri
+    super.init()
+  }
+
+  override var reason: String {
+    "Only file:// URIs are supported for contact images. Provided URI: '\(providedUri)'. Please download the image first using File.downloadFileAsync from expo-file-system and provide a local file URI."
```
Comment (vonovak) [inline packages/expo-contacts/ios/ContactsExceptions.swift]:
```suggestion
    "Only file:// URIs are supported for contact images. Provided URI: '\(providedUri)'. Download the image first using File.downloadFileAsync from expo-file-system and provide a local file URI."
```

in our error messages, we usually don't say please; we just tell what to do to resolve the error

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsExceptions.kt [hunk 8]
```diff
@@ -19,3 +19,5 @@ class ContactNotFoundException : CodedException("Couldn't find contact")
 class ContactUpdateException : CodedException("Given contact couldn't be updated")
 
 class LookupKeyNotFoundException : CodedException("Couldn't find lookup key for contact")
+
+class RemoteImageUriException(uri: String) : CodedException("Only file:// URIs are supported for contact images. Provided URI: '$uri'. Please download the image first using File.downloadFileAsync from expo-file-system and provide a local file URI.")
```
Comment (vonovak) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsExceptions.kt]:
```suggestion
class RemoteImageUriException(uri: String) : CodedException("Only file:// URIs are supported for contact images. Provided URI: '$uri'. Download the image first using File.downloadFileAsync from expo-file-system and provide a local file URI.")
```

**Review by vonovak — CHANGES_REQUESTED** [review]
A few more comments; actually, could you add back the example of creating contact with an image? I'll be useful for testing. 
Thanks

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt (hunk 5 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.kt]: Done - [0653c08](https://github.com/expo/expo/pull/39658/commits/0653c088846ce307cd6f69cd106f708d1a5ad712)

File: packages/expo-contacts/ios/ContactsModule.swift (hunk 6 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/ios/ContactsModule.swift]: [0653c08](https://github.com/expo/expo/pull/39658/commits/0653c088846ce307cd6f69cd106f708d1a5ad712)

File: packages/expo-contacts/ios/ContactsExceptions.swift (hunk 7 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/ios/ContactsExceptions.swift]: Done - [c799e67](https://github.com/expo/expo/pull/39658/commits/c799e672cc927a4049da827882d32c0e64b0bfa2)

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsExceptions.kt (hunk 8 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsExceptions.kt]: [c799e67](https://github.com/expo/expo/pull/39658/commits/c799e672cc927a4049da827882d32c0e64b0bfa2)

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt (hunk 4 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: @vonovak yes, simply passing the photoUri string resolves the problem. Thank you for your comment! [8baed92](https://github.com/expo/expo/pull/39658/commits/8baed924e2c15f1961cb81de365128b477d2c3a4)

**Comment by hryhoriiK97** [comment]
> A few more comments; actually, could you add back the example of creating contact with an image? I'll be useful for testing. Thanks

@vonovak thank you! I've addressed all of your comments. I've also reverted the example of creating a contact with an image. [40198cc](https://github.com/expo/expo/pull/39658/commits/40198cce33d686565ebceb243febf9591469dc2f)
 
[android_test.webm](https://github.com/user-attachments/assets/838c9f94-8f27-40a9-b954-e3dab93206d7)

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt [hunk 9]
```diff
@@ -524,7 +525,7 @@ class Contact(var contactId: String, var appContext: AppContext) {
       contactData.add(notes)
 
       if (!photoUri.isNullOrBlank()) {
-        val photo = getThumbnailBitmap(Uri.parse(photoUri).path)
+        val photo = getThumbnailBitmap(photoUri)
```
Comment (vonovak) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: one last thing:

`getThumbnailBitmap` is `private fun getThumbnailBitmap(photoUri: String?): Bitmap` (at accepts null)

but it calls `Uri.parse` which throws on `null` input, which probably causes other problems as a consequence. It probably doesn't happen with the current code but we can't tell for sure because the compiler doesn't guard against it: https://developer.android.com/reference/android/net/Uri#parse(java.lang.String) 

can you instead change it to `private fun getThumbnailBitmap(photoUri: String): Bitmap`?


the Kotlin compiler is not gonna like it but you can make it understand [here](https://github.com/expo/expo/blob/main/packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt#L275) and in other places by following this pattern:

```
    val maybePhoto = rawPhotoUri ?: photoUri
    if (!maybePhoto.isNullOrBlank()) {
      val photo = getThumbnailBitmap(maybePhoto)
```

(use `isNullOrBlank` instead of `TextUtils.isEmpty`)

**Review by vonovak — COMMENTED** [review]
Thanks for your patience :)

can you make one more change pls?

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt (hunk 9 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: Yeah, thank you for catching that! 🚀 I've added the changes - [b247750](https://github.com/expo/expo/pull/39658/commits/b24775052b0fe46ec1dbaeea555f5e06815178d7)

**Comment by hryhoriiK97** [comment]
> Thanks for your patience :)
> 
> can you make one more change pls?

@vonovak no problem at all! Thank you for the comprehensive review 🚀 I've applied the change.

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt (hunk 9 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: @vonovak actually, couldn't we use `val uri = photoUri.toUri()` instead of `val uri = Uri.parse(photoUri)`? Wouldn't that be better?

Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: I checked how it works with toUri(), and it looks like it behaves as expected. I also found that toUri is commonly used in other modules as well. I've made the change - [4cdcd00](https://github.com/expo/expo/pull/39658/commits/4cdcd00cc90cc710ea19045651daa1fcb8bd4b68)

Please let me know if you're okay with this. I can revert it if any issues come up 👍

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt [hunk 10]
```diff
@@ -229,14 +229,17 @@ class Contact(var contactId: String, var appContext: AppContext) {
     ops.add(op.build())
     op.withYieldAllowed(true)
     if (!TextUtils.isEmpty(photoUri) || !TextUtils.isEmpty(rawPhotoUri)) {
```
Comment (vonovak) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]:
```suggestion
```

no need for this condition

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt [hunk 11]
```diff
@@ -273,19 +276,22 @@ class Contact(var contactId: String, var appContext: AppContext) {
...
```
Comment (vonovak) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]:
```suggestion
```

no need for this condition

File: packages/expo-contacts/CHANGELOG.md [hunk 12]
```diff
@@ -10,6 +10,8 @@
 
 ### 💡 Others
 
+- Added contacts image remote uri validation. ([#39658](https://github.com/expo/expo/pull/39658) by [@hryhoriiK97](https://github.com/hryhoriiK97))
```
Comment (vonovak) [inline packages/expo-contacts/CHANGELOG.md]:
```suggestion
- Added contact image uri validation. ([#39658](https://github.com/expo/expo/pull/39658) by [@hryhoriiK97](https://github.com/hryhoriiK97))
```

**Review by vonovak — CHANGES_REQUESTED** [review]

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt (hunk 10 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: @vonovak yes, sorry, I've fixed this - [9d7b582](https://github.com/expo/expo/pull/39658/commits/9d7b582817ed031ecf54b66e86d738cffc1c6db7)

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt (hunk 11 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt]: Done - [9d7b582](https://github.com/expo/expo/pull/39658/commits/9d7b582817ed031ecf54b66e86d738cffc1c6db7)

File: packages/expo-contacts/CHANGELOG.md (hunk 12 above)
Comment (hryhoriiK97) [reply packages/expo-contacts/CHANGELOG.md]: [9d7b582](https://github.com/expo/expo/pull/39658/commits/9d7b582817ed031ecf54b66e86d738cffc1c6db7)

**Review by vonovak — APPROVED** [review]
Thank you!

Strictly speaking, this is a breaking change on iOS where previously remote images were simply ignored, now it'll throw. Need to see when to merge this.

**Comment by hryhoriiK97** [comment]
> Thank you!
> 
> Strictly speaking, this is a breaking change on iOS where previously remote images were simply ignored, now it'll throw. Need to see when to merge this.

Thank you for the review!

I'll wait for the info from you  🙂
