### PR TITLE
[jest-expo] fix jest-preset mutating react-native preset

### LINKED ISSUE #9050: [jest-expo] expo's jest-preset is called twice, leading to warnings in console and a corrupted jest-preset
### Summary of Issue (just a few sentences)

Since upgraded to Expo SDK 38, I noticed some warnings in console when executing jest. The jest-preset.js file in jest-expo is called twice, it is due to a change since jest@25.

The preset is built by mutating the react-native preset, leading to warnings on the second pass and a corrupted output. The preset should be built in a immutable way.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.16.1 - D:\Programs\nodejs\node.EXE
      Yarn: 1.22.4 - D:\Programs\Yarn\bin\yarn.CMD
      npm: 6.13.4 - D:\Programs\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
```

### Reproducible Demo

1. `expo init -t tabs jest-demo`
2. `cd jest-demo`
3. `yarn test`

Warnings showing in console:
```
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
```

### Workaround

1. `yarn add jest@^24.0.0`
2. Launch tests using this command: `node ./node_modules/jest/bin.jest.js`

### PR DESCRIPTION
**Pull request by alex-fournier**
# Why

Fixes https://github.com/expo/expo/issues/9050

Due to a change in jest-config since v25.0.0, the jest-preset.js file is called twice.
The current implement of expo's jest-preset is based on mutating react-native's jest-preset.
The problem is that now, this file is called twice so the mutation is applied twice, leading to warnings in console and a corrupted jest-preset in output.

# How

With a `cloneDeep`, the origin preset is no longer mutated and the output is now deterministic.

### CODE REVIEW

**Review by renanmav — APPROVED** [review]

File: packages/jest-expo/jest-preset.js [hunk 1]
```diff
@@ -1,8 +1,10 @@
 'use strict';
 
+const cloneDeep = require('lodash/cloneDeep');
 const isEqual = require('lodash/isEqual');
 // Derive the Expo Jest preset from the React Native one
-const jestPreset = require('react-native/jest-preset');
+const jestPresetOrigin = require('react-native/jest-preset');
```
Comment (brentvatne) [inline packages/jest-expo/jest-preset.js:6]:
```suggestion
const jestPreset = cloneDeep(require('react-native/jest-preset'));
```

File: packages/jest-expo/jest-preset.js [hunk 2]
```diff
@@ -1,8 +1,10 @@
...
+const jestPreset = cloneDeep(jestPresetOrigin);
```
Comment (brentvatne) [inline packages/jest-expo/jest-preset.js:7]:
```suggestion
```

**Review by brentvatne — APPROVED** [review]
if ci passes this lgtm

**Comment by renanmav** [comment]
Shall we merge?

**Comment by hesyifei** [comment]
Any update on this?

**Comment by renanmav** [comment]
cc @brentvatne

**Comment by renanmav** [comment]
Any news?

**Comment by brentvatne** [comment]
thanks, this will go out with sdk-40
