### PR TITLE
[ios][file-system] Fix copy async

### LINKED ISSUE #27021: [expo-file-system] copyAsync not working
### Minimal reproducible example

https://snack.expo.dev/@fpena/blissful-green-candies?platform=ios

### Summary

Using the latest Expo version (50.0.0) copying an asset doesn't work with expo-file-system package. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/opt/node@12/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #27021
When an image is selected from the photo library it will have a url like `ph://***`. Our `URL` conversion will accept this but when we access `url.path` it will be blank, causing the copy to fail.

# How
Check if we are dealing with a photo library asset and handle the copy using the `PHAssetResourceManager` instead of the `FileManager`.

# Test Plan
All tests still passing in bare-expo
Tested using the provided repro.

### CODE REVIEW

File: packages/expo-file-system/ios/FileSystemHelpers.swift [hunk 1]
```diff
@@ -1,6 +1,10 @@
 // Copyright 2023-present 650 Industries. All rights reserved.
 
 import ExpoModulesCore
+import Photos
+
+private let assetIdentifier = "ph://"
+private let resourceManager = PHAssetResourceManager()
```
Comment (Kudo) [inline packages/expo-file-system/ios/FileSystemHelpers.swift:7]: nit: could we lazy initiate ths instance or even just using local variable in the usage?
```swift
PHAssetResourceManager().writeData(...)
```

**Review by Kudo — APPROVED** [review]

File: packages/expo-file-system/ios/FileSystemHelpers.swift (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-file-system/ios/FileSystemHelpers.swift:7]: Good catch, we should make it lazy. We still need to keep it outside of the function because it has to live long enough for the callback to get executed.

**Comment by protetore** [comment]
Thanks for fixing this @alanjhughes !
I see it's been marked as published, but I don't see any new version out there. Do you have any idea of the release schedule for this fix?

**Comment by protetore** [comment]
@alanjhughes I gave it a try, but I'm facing another problem now: the files gets copied, but the promise never resolves. 

Tried a simple test case of selecting a photo from camera roll and copying it to the documents path. The promise never resolves, but when a got to the directory and check if the file is there, it is.

```
await FileSystem.copyAsync({
  from: selectedPhoto,
  to: `${fullPath}/${pictureId}`,
});
```

**Comment by alanjhughes** [comment]
Hi @protetore - This will be fixed by #27381. Apologies for the inconvenience. I shouldn't have missed that
