### PR TITLE
[expo-mail-composer] Extract mail composer from Expo SDK

### LINKED ISSUE #3237: MailComposer does not support attachments lacking an extension
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 11.6.0
  Yarn: 1.12.3
  npm: 6.5.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^32.0.0 => 32.0.1
  react: 16.5.0 => 16.5.0
  react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1

### Steps to Reproduce
Calling MailComposer.composeAsync with an URI which filename has no extension.

### Expected Behavior
The mailer should open with the attached file.

### Actual Behavior
This crashes the application (see attached screen capture)
screen-capture

### Reproducible Demo
I have developed a small project reproducing the problem:
https://github.com/PierFio/MailComposerFails
(Tested on an iOS device with version 12.1.2)

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

b365e29 fixes https://github.com/expo/expo/issues/3237

# How

Nothing special.

# Test Plan

MailComposer screen in NCL works ok on both platforms.

### CODE REVIEW

File: packages/expo-mail-composer/android/src/main/java/expo/modules/mailcomposer/MailComposerModule.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+  private ModuleRegistry mModuleRegistry;
+  private Promise mPromise;
+
+  public MailComposerModule(Context context) {
+    super(context);
+  }
+
+  @Override
+  public String getName() {
+    return "ExponentMailComposer";
```
Comment (tsapeta) [inline packages/expo-mail-composer/android/src/main/java/expo/modules/mailcomposer/MailComposerModule.java]:
```suggestion
    return "ExpoMailComposer";
```

File: packages/expo-mail-composer/ios/EXMailComposer/EXMailComposer.m [hunk 2]
```diff
@@ -6,79 +6,78 @@
...
+@property (nonatomic, strong) EXPromiseRejectBlock reject;
 
 @end
 
 @implementation EXMailComposer
 
-RCT_EXPORT_MODULE(ExponentMailComposer);
-
-@synthesize bridge = _bridge;
+EX_EXPORT_MODULE(ExponentMailComposer);
```
Comment (tsapeta) [inline packages/expo-mail-composer/ios/EXMailComposer/EXMailComposer.m]:
```suggestion
EX_EXPORT_MODULE(ExpoMailComposer);
```

File: packages/expo-mail-composer/ios/EXMailComposer/EXMailComposer.h [hunk 3]
```diff
@@ -0,0 +1,15 @@
+//
+//  EXMailComposer.h
+//  Exponent
+//
+//  Created by Alicja Warchał on 20.12.2017.
+//  Copyright © 2017 650 Industries. All rights reserved.
+//
```
Comment (tsapeta) [inline packages/expo-mail-composer/ios/EXMailComposer/EXMailComposer.h]: I'm sorry Alicja, you have to be removed from here 🤷‍♂️

File: packages/expo-mail-composer/android/build.gradle [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+  }
+}
+
+android {
+  compileSdkVersion 26
+
+  defaultConfig {
+    minSdkVersion 21
+    targetSdkVersion 26
+    versionCode 7
```
Comment (tsapeta) [inline packages/expo-mail-composer/android/build.gradle]:
```suggestion
    versionCode 1
```

File: packages/expo-mail-composer/android/build.gradle [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+    versionName "1.1.0"
```
Comment (tsapeta) [inline packages/expo-mail-composer/android/build.gradle]:
```suggestion
    versionName "1.0.0"
```

File: packages/expo-mail-composer/android/build.gradle [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+  dependencies {
+    classpath 'com.android.tools.build:gradle:3.1.3'
+  }
+}
+
+apply plugin: 'com.android.library'
+apply plugin: 'maven'
+
+group = 'host.exp.exponent'
+version = '1.1.0'
```
Comment (tsapeta) [inline packages/expo-mail-composer/android/build.gradle]:
```suggestion
version = '1.0.0'
```

**Review by tsapeta — CHANGES_REQUESTED** [review]
