### PR TITLE
[android][ios][home][jest-expo] persist session info in one location on clients

### LINKED ISSUE #2653: Home build broken, missing mocks
[Example failing build](https://circleci.com/gh/expo/expo/4206).  The errors are `TypeError: ExponentKernel.{remove,set}SessionSecret is not a function`.

As I understand it, jest needs mock definitions for these functions, and we haven't added them to jest-expo in the past because they aren't exposed to regular apps.

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Follow up to @ide 's comments on #2503 

Also fixes #2653 

# How

Stop storing session data in `AsyncStorage` and instead store it in only one place on each client -- `SharedPreferences` on Android and the keychain on iOS.

# Test Plan

On both platforms, tested that an old sessionSecret was properly retrieved from `AsyncStorage` and then sent as a header along with manifest requests. Then tested that logging out cleared the session and logging back in caused new sessionSecret to be sent with manifest requests.

### CODE REVIEW

File: home/storage/LocalStorage.js [hunk 1]
```diff
@@ -49,7 +49,14 @@ async function updateSettingsAsync(updatedSettings) {
 }
 
 async function getSessionAsync() {
-  let results = await AsyncStorage.getItem(Keys.Session);
+  let results = await ExponentKernel.getSessionAsync();
+  if (!results) {
+    // try querying legacy location
```
Comment (ide) [inline home/storage/LocalStorage.js]: consider including today's date in the comment so that a yearish from now we can delete this without interrupting active developers

File: home/storage/LocalStorage.js [hunk 2]
```diff
@@ -49,7 +49,14 @@ async function updateSettingsAsync(updatedSettings) {
...
+    results = await AsyncStorage.getItem(Keys.Session);
+    if (results) {
+      await AsyncStorage.removeItem(Keys.Session);
```
Comment (ide) [inline home/storage/LocalStorage.js]: We need to also write the value to the new session store

File: android/expoview/src/main/java/host/exp/exponent/modules/ExponentKernelModule.java [hunk 3]
```diff
@@ -112,13 +113,31 @@ public void consumeEventQueue() {
...
+    String sessionSecret = mExponentSharedPreferences.getString(ExponentSharedPreferences.EXPO_AUTH_SESSION);
+    promise.resolve(sessionSecret);
   }
 
   @ReactMethod
-  public void removeSessionSecret() {
-    ExponentUrls.setSessionSecret(null);
+  public void setSessionAsync(String sessionSecret, Promise promise) {
+    try {
+      mExponentSharedPreferences.setString(ExponentSharedPreferences.EXPO_AUTH_SESSION, sessionSecret);
```
Comment (ide) [inline android/expoview/src/main/java/host/exp/exponent/modules/ExponentKernelModule.java]: Won't this be the session JSON string as opposed to the secret token alone? In the iOS implementation there's all that JSON parsing that's missing here.

**Review by ide — CHANGES_REQUESTED** [review]
This looks much better than what we had before and looks like it won't inadvertently break.

One thing that stood out to me as a bit complex is that the ExpoKernel.set/getSessionAsync interface takes/returns a string, which looks like any opaque string value. But then the native iOS code expects that string to be valid JSON with a "sessionSecret" property -> this means we need to keep the JS and native code in sync with regard to how the session string is encoded.

I think we could do two mutually exclusive things to make this better:

- Rename the methods to set/getSessionJsonAsync (or set/getSessionJSONAsync -- we haven't talked about capitalization as part of the audit yet). This communicates that the native layer wants valid JSON vs. an opaque string the way AsyncStorage did.
- Have set/getSessionAsync take/return a JS object, and have the JSON encoding/decoding be an implementation detail of the native storage mechanism. I think this is a better API since the JS code used JSON only because AsyncStorage wanted it but that constraint is now gone.

File: home/storage/LocalStorage.js (hunk 2 above)
Comment (esamelson) [reply home/storage/LocalStorage.js]: this isn't necessary in the current form of the code because the only place where `getSessionAsync` is called also calls `saveSessionAsync` immediately afterwards. But this is a good idea, I've added it for future proofing.

**Comment by esamelson** [comment]
I agree that having the methods take/return objects is clearer -- makes sense that they were stringified because of AsyncStorage, thanks for that clarification. I've implemented this in the latest commit.

The one wrinkle is that AFAIK there is currently no method for converting a java `JSONObject` to `WritableMap`. Will work on adding that in a bit. (for now just passing a stringified form back from `getSessionAsync` and the JS calls `JSON.parse`.)

File: ios/Exponent/Kernel/DevSupport/EXSession.h [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+#import <Foundation/Foundation.h>
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface EXSession : NSObject
+
++ (instancetype)sharedInstance;
+
+- (NSDictionary * _Nullable)getSession;
```
Comment (ide) [inline ios/Exponent/Kernel/DevSupport/EXSession.h]:
```suggestion
- (NSDictionary * _Nullable)session;
```

Obj-C / Swift convention is to use noun phrases for non-mutating getters (whereas in JS / Java, methods => verb phrases)

File: ios/Exponent/Kernel/DevSupport/EXSession.h [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+- (NSString * _Nullable)getSessionSecret;
```
Comment (ide) [inline ios/Exponent/Kernel/DevSupport/EXSession.h]:
```suggestion
- (NSString * _Nullable)sessionSecret;
```

File: ios/Exponent/Kernel/DevSupport/EXSession.m [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+
+- (BOOL)saveSessionToKeychain:(NSDictionary *)session error:(NSError **)error
+{
+  NSError *jsonError;
+  NSData *encodedData = [NSJSONSerialization dataWithJSONObject:session
+                                                        options:kNilOptions
+                                                          error:&jsonError];
+  if (jsonError) {
+    if (error) {
+      * error = [NSError errorWithDomain:EX_UNVERSIONED(@"EXKernelErrorDomain")
```
Comment (ide) [inline ios/Exponent/Kernel/DevSupport/EXSession.m]:
```suggestion
      *error = [NSError errorWithDomain:EX_UNVERSIONED(@"EXKernelErrorDomain")
```

Remove extra space

File: android/expoview/src/main/java/host/exp/exponent/modules/ExponentKernelModule.java [hunk 7]
```diff
@@ -112,13 +115,34 @@ public void consumeEventQueue() {
   }
 
   @ReactMethod
-  public void setSessionSecret(String sessionSecret) {
-    ExponentUrls.setSessionSecret(sessionSecret);
+  public void getSessionAsync(Promise promise) {
+    // there is not a great way in Java to convert a JSONObject into a ReadableMap
```
Comment (ide) [inline android/expoview/src/main/java/host/exp/exponent/modules/ExponentKernelModule.java]: WriteableMap

**Review by ide — APPROVED** [review]
Looks much better (esp when the Java-only edge case is smoothed away), thanks.
