### PR TITLE
fix(cli): use correct `script src` path when exporting web development build

### LINKED ISSUE #27803: Wrong script src on export -p web --dev
### Summary

**what the expected behavior is**

When running `yarn expo export --platform web --dev`, it should generate `dist/index.html` with the correct App entry path.

**what is actually happening**

`dist/index.html` is generated with `<script src="//Users/**/index-src/node_modules/expo/AppEntry.js" defer></script>`

The path has one more `/` in the beginning.

* `**` is the location of the `index-src`.

### What platform(s) does this occur on?

Web

### SDK Version

50

### Environment

```
  expo-env-info 1.2.0 environment info:
   System:
     OS: macOS 14.4
     Shell: 5.9 - /bin/zsh
   Binaries:
     Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
     Yarn: 4.0.1 - ~/.nvm/versions/node/v20.11.1/bin/yarn
     npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
   SDKs:
     iOS SDK:
       Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
   IDEs:
     Android Studio: 2023.1 AI-231.9392.1.2311.11330709
     Xcode: 15.1/15C65 - /usr/bin/xcodebuild
   npmPackages:
     babel-preset-expo: ^10.0.0 => 10.0.1 
     expo: ~50.0.11 => 50.0.11 
     react: 18.2.0 => 18.2.0 
     react-dom: 18.2.0 => 18.2.0 
     react-native: 0.73.4 => 0.73.4 
     react-native-web: ^0.19.10 => 0.19.10 
   Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/jparksecurity/index-src

Run `yarn export --platform web --dev`, then check `script` tag in `dist/index.html`.

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #27803

# How

When exporting a development version of the (web) app, it seems we are using the absolute paths of modules. This doesn't work well with our `baseUrl` handling, and accidentally adds multiple starting slashes (as mentioned in #27803).

# Test Plan

- Added method to filter empty segments when creating URL pathnames
- Added tests to ensure no regression

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/start/server/metro/serializeHtml.ts [hunk 1]
```diff
@@ -91,10 +102,10 @@ function htmlFromSerialAssets(
               return '';
             }
             // Mark async chunks as defer so they don't block the page load.
-            // return `<script src="${baseUrl}/${filename}" defer></script>`;
+            // return `<script src="/${combineUrlPath(baseUrl, filename)" defer></script>`;
           }
 
-          return `<script src="${baseUrl}/${filename}" defer></script>`;
+          return `<script src="/${combineUrlPath(baseUrl, filename)}" defer></script>`;
```
Comment (byCedric) [inline packages/@expo/cli/src/start/server/metro/serializeHtml.ts:108]: Adding the root `/` seems incorrect to me, as this would break `baseUrl`'s like `https://cdn.example.app/` base URLs. Unfortunately, the **e2e/__tests__/export/base-path.test.ts** breaks without it.

@EvanBacon do you know the exact behavior we should follow here? E.g. keep the forced-starting `/`, or correct the e2e test and add another test for `https://cdn.example.app/` base urls.
