### PR TITLE
[expo-asset] Load local expo-updates manifest assets

### LINKED ISSUE #4081: Manifest type "expo-updates" does not show images in development
### Summary

When running a project with `expo start --force-manifest-type=expo-updates`, `<Image />`s are not shown during development.

Screenshots:
Screen Shot 2021-12-18 at 2 55 15 PM
Left: started a project with `expo start --force-manifest-type=classic`, and the image displays (expected). 
Right: started a project with `expo start --force-manifest-type=expo-updates`, and the image does not display. The expectation is that it should display.

Repo demonstrating the issue: https://github.com/jonsamp/test-12-14-sdk44

Replication steps:
1. Clone the repo
2. Install dependencies
3. Run `yarn start`. This runs `expo start`, and it also includes the `--force-manifest-type=expo-updates` flag since in **app.json**, there's an `updates.url` property with `https://u.expo.dev/...`.
4. Notice that the image does not show up (right screenshot above). The expectation is that the image displays.
5. Restart the server with `yarn start --force-manifest-type=classic`, and restart the app. Notice that the image now shows up.

### Environment

```
  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.volta/tools/image/node/16.13.0/bin/node
      Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
      npm: 8.1.0 - ~/.volta/tools/image/node/16.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-30 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0-beta.1 => 44.0.0-beta.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

iOS Simulator, iPhone 13, iOS 15.2, Expo Go (client version 2.23.2.101)

### Error output

There is not error output

### Reproducible demo or steps to reproduce from a blank project

https://github.com/jonsamp/test-12-14-sdk44

### PR DESCRIPTION
**Pull request by jonsamp**
# Why

Fixes [4081](https://github.com/expo/expo-cli/issues/4081)

Closes ENG-2748, ENG-2288

As described in the issues above, there was one issue that was causing problems: 
- The expo-asset library could not load local assets when using an `expo-updates` manifest
- Using React Native `<Image />`'s `defaultSource` prop would cause an app to error.

This PR exposes the `manifest2.extra.expoGo.debuggerHost` to the `selectAssetSources` function, which returns the correct local asset URLs. This makes it possible to run `expo start --force-manifest-type=expo-updates` and to load assets.

#  How 

For expo-asset to know the correct local URL, we must pass it the URL of the currently running local session. For classic manifests, we pass in the `manifest.bundleUrl` (example: `http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false`). The expo-asset library code then takes the pathname (`http://127.0.0.1:19000`) and uses that to construct the asset URL. 

In similar fashion, I decided to take the `manifest2.extra.expoGo.debuggerHost` property (example: `127.0.0.1:19000`) for `expo-updates` manifests. If this property is likely to change, we should pass another prop when running Expo CLI that is more specific, but using this one since I think it is likely stable.

# Test Plan

1. Run unit tests inside expo-asset.
2. In apps/sandbox, add the following **App.js** file and some images named image-one.png and image-two.png:
    ```jsx
    import ImageOne from './image-one.png';
    import ImageTwo from './image-two.png';
    
    // ...
    <Image defaultSource={ImageOne} source={ImageTwo} style={{ height: 200, width: 300 }} />
    ```
3. Install dependencies with `yarn`, then run the server with `expo start --force-manifest-type=expo-updates` and open the app in Expo Go in a simulator. You should see an image appear. You can also write `console.log(Image.resolveAssetSource(ImageOne))`, and make sure that the URL starts with a URL like "https://127.0.0.1:19000/...". 
4. Then, try running the server with `expo start --force-manifest-type=classic`, to make sure that classic updates are unaffected.

### CODE REVIEW

File: packages/expo-asset/src/AssetSources.ts [hunk 1]
```diff
@@ -74,6 +74,19 @@ export function selectAssetSource(meta: AssetMetadata): AssetSource {
     return { uri, hash };
   }
 
+  // For assets during development using manifest2, we use the development server's URL origin
+  const manifest2 = getManifest2();
+
+  if (manifest2?.extra?.expoGo) {
```
Comment (esamelson) [inline packages/expo-asset/src/AssetSources.ts:80]:
```suggestion
  if (manifest2?.extra?.expoGo?.developer) {
```

**Review by esamelson — APPROVED** [review]
Looks good to me (aside from the one detail) -- thanks so much for fixing this, @jonsamp!! And for the comprehensive test plan 🙏 🙏 

It looks like we should probably take a pass over the rest of the `getManifest()` calls in this file as well, to make them compatible with `manifest2` (could also consider removing the hardcoded cloudfront URL altogether, although it has useful to have a last resort fallback at times) -- but this seems great as a hotfix for the current issue.

**Review by tsapeta — APPROVED** [review]
