### PR TITLE
[templates][bare] add metro.config.js with hashAssetFiles plugin

### LINKED ISSUE #8266: Eject Expo SDK 37 - iOS won't build Bundle React Native code and images phase
### Environment

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.20.3

### Steps to Reproduce

Run `expo eject` and try running `yarn ios` or go to iOS folder and build the `.xcworkspace`

### Expected Behavior

Expect the iOS project to build without error

### Actual Behavior

Receive error: 

```
+ DEST=/Users/croossin/Library/Developer/Xcode/DerivedData/Spot-dacyrpbiwrmdvabvpmkrcdgtuwuz/Build/Products/Debug-iphonesimulator/ios.app
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0
```

### Remedies

If I remove the line `../node_modules/expo-updates/scripts/create-manifest-ios.sh` in the `Bundle React Native code and images` build phase, it will build without error.  So it is something with the expo updates create manifest.

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Fixes https://github.com/expo/expo/issues/8266

# How

Add metro.config.js to template projects and to upgrade instructions for expo-updates.

Also add a better error message to the createManifest script in case this plugin is missing.

# Test Plan

`expo init` -> bare template -> add asset to App.js -> `pod install` -> Xcode build Debug -> success

### CODE REVIEW

File: packages/expo-updates/scripts/createManifest.js [hunk 1]
```diff
@@ -44,6 +44,11 @@ const destinationDir = process.argv[4];
   };
 
   assets.forEach(function(asset) {
+    if (!asset.fileHashes) {
+      throw new Error(
+        'It looks like the hashAssetFiles Metro plugin is not configured in your project. You need to add a metro.config.js that configures Metro to use this plugin.'
```
Comment (brentvatne) [inline packages/expo-updates/scripts/createManifest.js:49]: maybe we can link to expo.fyi page that has a minimal metro.config.js that includes this?

Comment (brentvatne) [reply packages/expo-updates/scripts/createManifest.js:49]: or even readme link is fine actually now that it includes this

**Review by brentvatne — APPROVED** [review]
