### PR TITLE
[android][core] Use `RuntimeSchedulerCallInvoker`

### LINKED ISSUE #43474: No re-render on state change within an expo module callback
### Minimal reproducible example

https://github.com/sander48k/expo-issue-module-state

### Steps to reproduce

When a JavaScript callback function, containing a state change statement, that is passed to an Expo Native Module is invoked from that native module, it does not result in a screen update.

The provided minimal reproducible example contains a simple module (MyModule) that provides a method called `startCounter`. This method accepts a callback function with signature `(number)=>void` as its sole argument. The method starts a timer on a background thread and on every tick, the callback function is invoked on the JavaScript thread (using `runtime.schedule`). On the JavaScript side, in App.tsx, a button is present that, on press, invokes the `startCounter` method providing a function that sets the `count` state variable.

The following is observed: on both iOS and Android, on every tick, the callback function is correctly called on the JavaScript side. However, on iOS this results in a screen update (i.e. the screen reflects the change of the count state variable), while on Android the screen is not updated.

The minimal reproducible example was created using `npx create-expo-app@latest --template blank-typescript` and `npx create-expo-module@latest --local`.

### Environment

```text
expo-env-info 2.0.11 environment info:
    System:
      OS: macOS 26.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
      Yarn: 3.3.1 - ~/.nvm/versions/node/v22.14.0/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/sander/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
      Android SDK:
        API Levels: 28, 29, 31, 32, 33, 34, 35, 36
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 36.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-35 | Pre-Release 16 KB Page Size Google Play ARM 64 v8a, android-36 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.27812.49.2514.14217341
      Xcode: 26.2/17C52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~55.0.2 => 55.0.2 
      react: 19.2.0 => 19.2.0 
      react-native: 0.83.2 => 0.83.2 
    npmGlobalPackages:
      eas-cli: 16.28.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #43474
Follow up of #40473. 
We are currently still using `runOnJSQueueThread` on android which posts work directly to the JS thread, bypassing the scheduler. The causes the problem mentioned in the issue where react never flushes state updates because it is unaware of them. We should use `RuntimeSchedulerCallInvoker` instead of `BridgelessJSCallInvoker` to match the iOS behaviour. 

# How
- Add an new native method `scheduleOnJSThread`
- Expose `Runnable` to c++ 
- Create an instance of `RuntimeSchedulerCallInvoker` in `install` and pass that to the `jsiContext`
- Use it in the `MainRuntime`s `schedule` method

# Test Plan
Bare expo behaves as normal
Tested in the provided repro.

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good to me, but wait for Łukasz to review it 😉

File: packages/expo-modules-core/android/src/main/cpp/installers/MainRuntimeInstaller.cpp [hunk 1]
```diff
@@ -54,11 +56,23 @@ jni::local_ref<JSIContext::javaobject> MainRuntimeInstaller::install(
...
+  auto *runtime = reinterpret_cast<jsi::Runtime *>(jsRuntimePointer);
+
+  std::shared_ptr<react::CallInvoker> callInvoker;
+  std::shared_ptr<react::RuntimeScheduler> runtimeScheduler;
+
+  if (auto binding = react::RuntimeSchedulerBinding::getBinding(*runtime)) {
+    runtimeScheduler = binding->getRuntimeScheduler();
+    callInvoker = std::make_shared<react::RuntimeSchedulerCallInvoker>(runtimeScheduler);
+  } else {
+    callInvoker = std::make_shared<BridgelessJSCallInvoker>(runtimeExecutor->cthis()->get());
```
Comment (lukmccall) [inline packages/expo-modules-core/android/src/main/cpp/installers/MainRuntimeInstaller.cpp:68]: I think we don't need this anymore, and throwing an error here would be a better approach. I can change it in the following PR, so you can merge it as is.

**Review by lukmccall — APPROVED** [review]
