### PR TITLE
[ios] fix screen orientation portrait bug

### LINKED ISSUE #4646: After lock orientation view doesn't get rotated
## 🐛 Bug Report

```
  Expo CLI 2.18.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.20 => 16.8.20 
      @types/react-native: ^0.57.63 => 0.57.63 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.18.4
```

iOS 11, latest Expo client

When locking orientation to a different orientation than currently locked, screen doesn't get rotated.

For example, when locked to landscape orientation I do 
```
componentDidMount() {
  ScreenOrientation.lockAsync(OrientationLock.PORTRAIT);
}
``` 

My app is not get rotated. To see the app in the portrait mode, I need to rotate the phone to landscape and then back.

### PR DESCRIPTION
**Pull request by quinlanj**
# Why
- Screen orientation doesn't lock properly with the `ScreenOrientation.OrientationLock.PORTRAIT` lock
Fixes https://github.com/expo/expo/issues/4646

# some background
- The phone can be in one of four positions: {portrait up, portrait down, landscape left, landscape left}
- `ScreenOrientation.OrientationLock.PORTRAIT` allows {portrait up, portrait down}. 
- We express this with the mask `UIInterfaceOrientationMaskPortrait | UIInterfaceOrientationMaskPortraitUpsideDown`

# How
- there was previously no case to account for the `UIInterfaceOrientationMaskPortrait | UIInterfaceOrientationMaskPortraitUpsideDown` mask in the app view controller
-  `UIInterfaceOrientationMaskPortrait` refers to just to {portrait up}  whereas the `UIDeviceOrientationIsPortrait` function checks if phone is in position {portrait up, portrait down}, NOT just {portrait up}.

# Test Plan

- [x] fixes the problem snack in the referenced issue
- [x] make sure this passes on test suite

### CODE REVIEW

File: ios/Exponent/Kernel/Views/EXAppViewController.m [hunk 1]
```diff
@@ -343,11 +343,14 @@ - (void)_enforceDesiredDeviceOrientation
   UIDeviceOrientation currentOrientation = [[UIDevice currentDevice] orientation];
   UIInterfaceOrientation newOrientation = UIInterfaceOrientationUnknown;
   switch (mask) {
-    case UIInterfaceOrientationMaskPortrait:
-      if (!UIDeviceOrientationIsPortrait(currentOrientation)) {
+    case UIInterfaceOrientationMaskPortrait | UIInterfaceOrientationMaskPortraitUpsideDown:
+      if(!UIDeviceOrientationIsPortrait(currentOrientation)){
```
Comment (tsapeta) [inline ios/Exponent/Kernel/Views/EXAppViewController.m]: formatting was fine 😉 
```suggestion
      if (!UIDeviceOrientationIsPortrait(currentOrientation)) {
```

**Review by tsapeta — APPROVED** [review]
