### PR TITLE
[expo-image-picker] Fix incorrect file URI on Android

### LINKED ISSUE #11214: [expo-image-picker] [Android] Incorrect file:/ url
### Summary of Issue

`ImagePicker.launchImageLibraryAsync` returns a file url that starts with `file:/`, not `file:///`. That's not only in contrast with what the documentation says but it also causes problems when trying to use the file url further, e.g. in VideoThumbnail. (Though, when used directly, the picked image/video seems to display correctly.)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

This seems to affect Android, both in Expo and standalone (bare).

<details>
  <summary>Environment info</summary>

```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.6.0/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/petrbela/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.40 => 0.12.40 
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```

</details>

### Reproducible Demo

I'm able to reproduce it with the example Snack at https://docs.expo.io/versions/latest/sdk/imagepicker/
 
### Steps to Reproduce

Choose any image or video (on Android). The resulting `uri` looks like this:

```js
{
  cancelled:false,
  width:1440,
  type:"image",
  uri:"file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540snack%252Fsdk.39.0.0-cmP99I8ELy/ImagePicker/3060429b-a71c-42cf-9595-d3f39d044422.png",
  height:1080
}
```

### Expected Behavior vs Actual Behavior

The file url should start with `file:///` instead of `file:/`.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/11214.

# How

For some reason, `toURI` returns a different path than `toURL`. The first one returns `file:/...` and the second one `file://...`. 

# Test Plan

- Snack at docs.expo.io/versions/latest/sdk/imagepicker ✅

# Changelog

- Fixed incorrect file URI on Android

### CODE REVIEW

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.kt [hunk 1]
```diff
@@ -25,7 +25,7 @@ class VideoResultTask(private val promise: Promise,
       val outputFile = fileProvider.generateFile()
       saveVideo(outputFile)
       val response = Bundle().apply {
-        putString("uri", outputFile.toURI().toString())
+        putString("uri", outputFile.toURL().toString())
```
Comment (bbarthec) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.kt:28]: This method is deprecated 😞 
https://docs.oracle.com/javase/7/docs/api/java/io/File.html#toURL()
What about using the suggestion from the deprecation message? 🤔 
```suggestion
        putString("uri", outputFile.toURI().toURL().toString())
```

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt [hunk 2]
```diff
@@ -31,7 +31,7 @@ open class ImageResultTask(private val promise: Promise,
       val imageExporterHandler = object : Listener {
         override fun onResult(out: ByteArrayOutputStream?, width: Int, height: Int) {
           val response = Bundle().apply {
-            putString("uri", outputFile.toURI().toString())
+            putString("uri", outputFile.toURL().toString())
```
Comment (bbarthec) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt:34]:
```suggestion
            putString("uri", outputFile.toURI().toURL().toString())
```
See the other comment 😉

**Review by bbarthec — CHANGES_REQUESTED** [review]
I believe we need to create some test coverage for this scenario.

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.kt (hunk 1 above)
Comment (lukmccall) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.kt]: `outputFile.toURI().toURL()` also returns incorrect path. 
I believe that Android changed how URIs are parsed and now we should use "file:/" instead of "file:///". But we can't migrate right now. We rely on "file:///" in many places. So, I've added a method that will replace "file:/" with "file:///".

Comment (bbarthec) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.kt]: Ok, so you're saying that:
- Android changed it's internal behaviour (it would be nice to have some reference)
- we are using some other approach that the default one

I'm ok with the change, but we need to investigate this and unify across all codebase, ideally to follow native Android behaviour 😉 I'll create an issue for that.

**Review by bbarthec — APPROVED** [review]
