### PR TITLE
[audio][android][ios][web] Fix recordForDuration status updates and add new record() options API

### LINKED ISSUE #38565: [docs] [expo-audio] usage of recordForDuration is unclear
### Summary

> Stops the recording once the specified time has elapsed.

The docs don't say much about `recordForDuration` or have an example. What's the expected usage? Is it a replacement for `.record()` or should be called after it?

It doesn't seem to work in either of the scenarios. Is it a 🐛 or wrong usage? 
- Just calling `recordForDuration(5)` - recording state stays at `isRecording: false`
- Calling `record() + recordForDuration(5)` - recorder never stops

```tsx
// "expo-audio": "0.4.8"

import { useEffect } from "react";
import { View, StyleSheet, Button, Alert } from "react-native";
import {
  useAudioRecorder,
  AudioModule,
  RecordingPresets,
  setAudioModeAsync,
  useAudioRecorderState,
  RecordingOptions,
} from "expo-audio";

const recordingOptions = {
  ...RecordingPresets.HIGH_QUALITY,
  isMeteringEnabled: true,
} satisfies RecordingOptions;

export default function App() {
  const audioRecorder = useAudioRecorder(recordingOptions);
  const recorderState = useAudioRecorderState(audioRecorder);

  const record = async () => {
    await audioRecorder.prepareToRecordAsync(recordingOptions);
    audioRecorder.recordForDuration(5);
  };

  const stopRecording = async () => {
    // The recording will be available on `audioRecorder.uri`.
    await audioRecorder.stop();
  };

  useEffect(() => {
    (async () => {
      const status = await AudioModule.requestRecordingPermissionsAsync();
      if (!status.granted) {
        Alert.alert("Permission to access microphone was denied");
      }

      setAudioModeAsync({
        playsInSilentMode: true,
        allowsRecording: true,
      });
    })();
  }, []);

  console.log("recorderState", JSON.stringify(recorderState, null, 2));

  return (
    <View style={styles.container}>
      <Button
        title={recorderState.isRecording ? "Stop Recording" : "Start Recording"}
        onPress={recorderState.isRecording ? stopRecording : record}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    padding: 10,
  },
});
```

### Link to the related documentation page

https://docs.expo.dev/versions/latest/sdk/audio/#recordfordurationseconds

### PR DESCRIPTION
**Pull request by hirbod**
# Why

  - recordForDuration() and startRecordingAtTime() methods had inconsistent behavior across platforms
  - No unified API for recording options - required separate method calls
  - iOS atTime parameter was incorrectly treated as relative delay instead of absolute device time
  - Android and Web didn't emit completion events, causing demo UI to not show "last recording"
  - Android required manual re-preparation between recordings, unlike iOS/Web
  - Manual recording stops on Android didn't emit events on correct thread context

Fixes #38565

# How

  New API:
  - Added record(options?: RecordingStartOptions) with atTime and forDuration properties
  - Deprecated recordForDuration() and startRecordingAtTime() methods (maintained for backward compatibility)
  - Added TypeScript types RecordingStartOptions with platform-specific documentation

  iOS:
  - Fixed atTime to use absolute device time (deviceCurrentTime + atTime) instead of relative delay
  - Added state synchronization for native AVAudioRecorder calls
  - Full support for both atTime and forDuration options

  Android:
  - Added completion event emission in stopRecording() with proper thread context (mainQueue)
  - Implemented auto-preparation after recording stops to match iOS/Web behavior
  - Made atTime a no-op (iOS-only feature) with clear documentation and comments
  - Maintained forDuration support with coroutine timers

  Web:
  - Made atTime a no-op (iOS-only feature) with clean conditional removal
  - Maintained forDuration support with setTimeout

  Demo:
  - Added toggle switches for testing new record({ atTime: 3, forDuration: 5 }) API
  - Added automatic completion detection for forDuration recordings
  - Updated UI to show platform-specific behavior ("iOS only" labels)

# Test Plan

bare-expo on Android, iOS and Web

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt [hunk 1]
```diff
@@ -465,10 +465,12 @@ class AudioModule : Module() {
         recorder.prepareRecording(options)
       }
 
-      Function("record") { recorder: AudioRecorder ->
+      Function("record") { recorder: AudioRecorder, options: Map<String, Any>? ->
```
Comment (alanjhughes) [inline packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt]:
```suggestion
      Function("record") { recorder: AudioRecorder, options: RecordOptions? ->
```

```swift
struct RecordOptions: Record {
  @Field var forDuration: Double?
  @Field var atTime: Double?
}
```
Let's create a record for this

File: packages/expo-audio/ios/AudioModule.swift [hunk 2]
```diff
@@ -234,8 +234,30 @@ public class AudioModule: Module {
         try recorder.prepare(options: options, sessionOptions: sessionOptions)
       }
 
-      Function("record") { (recorder: AudioRecorder) -> [String: Any] in
+      Function("record") { (recorder: AudioRecorder, options: [String: Any]?) in
```
Comment (alanjhughes) [inline packages/expo-audio/ios/AudioModule.swift]:
```suggestion
      Function("record") { (recorder: AudioRecorder, options: RecordOptions?) in
```

File: packages/expo-audio/ios/AudioModule.swift [hunk 3]
```diff
@@ -234,8 +234,30 @@ public class AudioModule: Module {
...
+          let absoluteTime = recorder.ref.deviceCurrentTime + TimeInterval(atTime)
+          recorder.ref.record(atTime: absoluteTime)
+          recorder.updateStateForDirectRecording()
+          return recorder.getRecordingStatus()
+        }
+        if let forDuration = forDuration {
+          recorder.ref.record(forDuration: TimeInterval(forDuration))
+          recorder.updateStateForDirectRecording()
+          return recorder.getRecordingStatus()
+        }
```
Comment (alanjhughes) [inline packages/expo-audio/ios/AudioModule.swift]:
```suggestion
       switch (options?.atTime, options?.forDuration) {
        case let (atTime?, forDuration?):
           // Convert relative delay to absolute device time
          let absoluteTime = recorder.ref.deviceCurrentTime + TimeInterval(atTime)
          recorder.ref.record(atTime: absoluteTime, forDuration: TimeInterval(forDuration))
          recorder.updateStateForDirectRecording()
          return recorder.getRecordingStatus()
        case let (atTime?, nil):
           let absoluteTime = recorder.ref.deviceCurrentTime + TimeInterval(atTime)
          recorder.ref.record(atTime: absoluteTime)
          recorder.updateStateForDirectRecording()
          return recorder.getRecordingStatus()
        case let (nil, forDuration?):
           recorder.ref.record(forDuration: TimeInterval(forDuration))
          recorder.updateStateForDirectRecording()
          return recorder.getRecordingStatus()
        default:
            recorder.startRecording()
        }
```

File: packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt [hunk 4]
```diff
@@ -465,10 +465,12 @@ class AudioModule : Module() {
...
         checkRecordingPermission()
         if (recorder.isPrepared) {
-          recorder.record()
+          val atTime = options?.get("atTime") as? Double
+          val forDuration = options?.get("forDuration") as? Double
+          recorder.recordWithOptions(atTime, forDuration)
```
Comment (alanjhughes) [inline packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt]:
```suggestion
          recorder.recordWithOptions(options.atTime, options.forDuration)
```

File: packages/expo-audio/android/src/main/java/expo/modules/audio/AudioRecorder.kt [hunk 5]
```diff
@@ -81,21 +81,34 @@ class AudioRecorder(
...
+    if (forDurationSeconds != null) {
+      record()
+      recordingTimerJob = appContext?.mainQueue?.launch {
+        delay((forDurationSeconds * 1000).toLong())
+        if (isRecording || isPaused) {
+          stopRecording()
+        }
       }
+    } else {
+      record()
```
Comment (alanjhughes) [inline packages/expo-audio/android/src/main/java/expo/modules/audio/AudioRecorder.kt]:
```suggestion
    forDurationSeconds?.let {
      record()
      recordingTimerJob = appContext?.mainQueue?.launch {
        delay((it * 1000).toLong())
        if (isRecording || isPaused) {
          stopRecording()
        }
      }
    } ?: record()
```

File: packages/expo-audio/ios/AudioRecorder.swift [hunk 6]
```diff
@@ -112,12 +112,22 @@ class AudioRecorder: SharedRef<AVAudioRecorder>, RecordingResultHandler {
       resetDurationTracking()
     }
 
-    ref.record()
+    _ = ref.record()
```
Comment (alanjhughes) [inline packages/expo-audio/ios/AudioRecorder.swift]: Is there a warning without this?

**Review by alanjhughes — CHANGES_REQUESTED** [review]
Looks good! Just left some comments

File: packages/expo-audio/ios/AudioRecorder.swift (hunk 6 above)
Comment (hirbod) [reply packages/expo-audio/ios/AudioRecorder.swift]: The build was failing for me without this, but happy to try it again.

Comment (hirbod) [reply packages/expo-audio/ios/AudioRecorder.swift]: false alarm

**Review by alanjhughes — APPROVED** [review]

File: packages/expo-audio/src/Audio.types.ts [hunk 7]
```diff
@@ -275,6 +275,36 @@ export enum AudioQuality {
...
+   * The time in seconds to wait before starting the recording.
+   * If not provided, recording starts immediately.
+   *
+   * **Platform behavior:**
+   * - iOS: Uses native AVAudioRecorder.record(atTime:) for precise timing.
+   *   ⚠️ **Important**: The recording process starts immediately (you'll see status updates),
+   *   but actual audio capture begins after the specified delay. This is not a countdown -
+   *   the recorder is active but silent during the delay period.
+   * - Android: Ignored, recording starts immediately
+   * - Web: Ignored, recording starts immediately
```
Comment (amandeepmittal) [inline packages/expo-audio/src/Audio.types.ts]:
```suggestion
   * **Platform behavior:**
   * - Android: Ignored, recording starts immediately
   * - iOS: Uses native AVAudioRecorder.record(atTime:) for precise timing.
   * - Web: Ignored, recording starts immediately
   *
   * > **warning** On iOS, the recording process starts immediately (you'll see status updates),
   * but actual audio capture begins after the specified delay. This is not a countdown, since
   * the recorder is active but silent during the delay period.
```

Let's use the platform order as per the writing style guide: https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#platform-order-when-referencing-android-ios-and-web-or-multiple-platforms

I'd avoid the emoji pattern you are using to call out the warning. Let's use the standard callout pattern after the platform behavior section and use `> **warning**` instead of important (we use important for experimental feature indication mostly). If this warning is only related to iOS, in the callout, let's mention the platform name.

Comment (amandeepmittal) [reply packages/expo-audio/src/Audio.types.ts]: Also, since this marked as platform iOS only, I think Android and Web info might not be required.

**Review by amandeepmittal — CHANGES_REQUESTED** [review]

**Review by amandeepmittal — APPROVED** [review]
