### PR TITLE
[linking] don't add extra slash to expoPrefix

### LINKED ISSUE #6555: SDK36: paths between Linking.makeUrl and Linking.parse do not match
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.6 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1

iOS & Android

### Steps to Reproduce

Place the following code in any component  (in the render function):
```
const link = Linking.makeUrl("MagicLink", {to: 'Home'});
console.log("Link: ", link);
const parsedLink = Linking.parse(link);
console.log("Parsed Link: ", parsedLink);
```

### Expected Behavior

Prior, on SDK35 I get the following logs:
```
Link:  exp://127.0.0.1:19000/--/MagicLink?to=Home
Parsed Link:  Object {
  "path": "MagicLink",
  "queryParams": Object {
    "to": "Home",
  },
}
```

Notice that the path passed in ('MagicLink') is the same parsed

### Actual Behavior

After upgrading to SDK36 I get the following logs:
```
Link:  exp://127.0.0.1:19000/--/MagicLink?to=Home
Parsed Link:  Object {
  "hostname": "127.0.0.1",
  "path": "--/MagicLink",
  "queryParams": Object {
    "to": "Home",
  },
  "scheme": "exp",
}
```
The parsed path is "--/MagicLink" when the passed in path is "MagicLink".  I would expect the parse function to return the same path that is initially passed into makeUrl

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/6555

# How

expoPrefix was adding an extra '/' to the string, which meant `path.startsWith(expoPrefix))` would return false
https://github.com/expo/expo/blob/master/packages/expo/src/Linking/Linking.ts#L132

### CODE REVIEW

**Comment by ide** [comment]
Add a regression test and also fix the failing unit tests.

File: packages/expo/src/Linking/Linking.ts [hunk 1]
```diff
@@ -129,12 +129,14 @@ function parse(url: string): ParsedURL {
...
-      expoPrefix = `${parts.slice(1).join('/')}/--/`;
+      expoPrefix = `${parts
+        .slice(1)
+        .concat(['--/'])
+        .join('/')}`;
     }
 
     if (IS_EXPO_HOSTED && !USES_CUSTOM_SCHEME && expoPrefix && path.startsWith(expoPrefix)) {
       path = path.substring(expoPrefix.length);
-      hostname = null;
```
Comment (ide) [inline packages/expo/src/Linking/Linking.ts]: This might have been there intentionally so we keep the hostname for Expo-hosted assets abstract for now. (In the future we want to treat all hostnames the same but that’s a bigger change).

**Review by ide — CHANGES_REQUESTED** [review]

File: packages/expo/src/Linking/Linking.ts (hunk 1 above)
Comment (cruzach) [reply packages/expo/src/Linking/Linking.ts]: yeah good point, adding it back in.

This API is a little confusing right now, since it does quite a bit of manipulation of the url if it's in the Expo client. Seems like it might be better to just treat it as a regular url, and provide the full path, host, etc? But I'm assuming it's like this `hostname = null` case, where it was done intentionally for a good reason and I'm just failing to see it 😄

File: packages/expo/src/Linking/Linking.ts [hunk 2]
```diff
@@ -129,7 +129,10 @@ function parse(url: string): ParsedURL {
     let expoPrefix: string | null = null;
     if (hostUriStripped) {
       const parts = hostUriStripped.split('/');
-      expoPrefix = `${parts.slice(1).join('/')}/--/`;
+      expoPrefix = `${parts
```
Comment (ide) [inline packages/expo/src/Linking/Linking.ts]: don't need string interpolation anymore
```suggestion
      expoPrefix = parts
```

**Review by ide — APPROVED** [review]
