### PR TITLE
[android][web-browser] Fix browser closing after app backgrounds

### LINKED ISSUE #8072: [expo-web-browser] Browser closes when switching to a different app temporarily (Android)
### Environment
```
  Expo CLI 3.19.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.7 => 37.0.7
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

Targeting Android and iOS using the managed workflow. Experiencing this problem on Android in both the client and standalone.

### Steps to Reproduce

Start your login flow using `AuthSession.startAsync` and then continue it when it resolves successfully. If it's not successful then give the user an option to retry.

After starting the login flow the browser should open. Switch to another app and then switch back to the login screen.

### Expected Behavior

The browser should stay open when returning to the app.

### Actual Behavior

The browser closes and the user must restart their login process. This is a major issue for anything using two factor authentication because they will need to switch apps after entering their email and password, copy a code, and then paste it on the login page to continue.

### Reproducible Demo

https://snack.expo.io/7wvmAi3cf

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #8072 
The short explanation of the issue is, because the main activity in react native apps is set to `singleTask` for easier handling of deeplinks etc. there is a knock on effect where some things don't behave correctly. In this case, opening the browser. With singleTask the browser instance is killed when the app is backgrounded. This is inconvenient and a poor UX for login flows where the user may need to leave the app to get a password. 

# How
I found some issues in how the `CustomTabsIntent` was being used leading to incorrect behaviour. This mostly solves the original problem except in one case. When the is backgrounded and launched from the app icon the browser instance is destroyed. It works fine when using the app switcher. 

Other libraries have experienced similar issues. Most notably [Stripe](https://github.com/stripe/stripe-react-native/issues/355). They have added a [workaround](https://github.com/stripe/stripe-react-native/blob/master/docs/android-chrome-tab-closes-on-background.md) to their README. To make the same changes in a expo project, I'm adding a config plugin to `expo-web-browser`. For now, I've named the parameter it accepts `experimentalLauncherActivity`. As more people use it and we're sure it has no hidden effects on other modules we can make it the default.

I've also adjusted bare expo with the necessary changes.

# Test Plan
Bare-expo. Everything appears to work normally.

Sandbox app. The plugin correctly makes the necessary changes.

### CODE REVIEW

**Comment by fobos531** [comment]
@alanjhughes In regards to your last comment with stripe workaround, I learned that RevenueCat also strongly recommends modifying the launch mode. Does this mean that the changes in this PR (the plugin and all) would benefit that case as well?

**Comment by alanjhughes** [comment]
@fobos531 yes, it should also handle that case. It's experimental until it used enough that we are confident it doesn't cause some unintended side effects

**Comment by fobos531** [comment]
> @fobos531 yes, it should also handle that case. It's experimental until it used enough that we are confident it doesn't cause some unintended side effects

This is awesome, eager to try it out!

File: apps/bare-expo/android/app/src/main/java/dev/expo/payments/BrowserLauncherActivity.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+    val application = application as MainApplication
+    if (!application.isActivityInBackStack(MainActivity::class.java)) {
+      val intent = Intent(this, MainActivity::class.java)
+      startActivity(intent)
+    }
+    finish()
+  }
+}
```
Comment (lukmccall) [inline apps/bare-expo/android/app/src/main/java/dev/expo/payments/BrowserLauncherActivity.kt:17]:
```suggestion
}

```

File: apps/bare-expo/android/app/src/main/java/dev/expo/payments/MainApplication.kt [hunk 2]
```diff
@@ -53,4 +54,18 @@ class MainApplication : Application(), ReactApplication {
...
+    }
+  }
+
+  fun removeActivityFromStack(cls: Class<*>?) {
+    cls?.let {
+      if (runningActivities.contains(cls)) runningActivities.remove(it)
+    }
+  }
+
+  fun isActivityInBackStack(cls: Class<*>?) = runningActivities.contains(cls)
```
Comment (lukmccall) [inline apps/bare-expo/android/app/src/main/java/dev/expo/payments/MainApplication.kt:70]: Can we use [`ActivityLifecycleCallbaks`](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks) instead? It can be registered on the `Application` object using `registerActivityLifecycleCallbacks` and it seems to contain all function that we need. I'm uncertain about when those callbacks will be executed, but it shouldn't be much different than `onCreate` or `onDestroy`. 

If possible, it would be wonderful—less abstraction on our end and a simpler configuration plugin.

Comment (alanjhughes) [reply apps/bare-expo/android/app/src/main/java/dev/expo/payments/MainApplication.kt:70]: Possibly, I'll look into it 👍

**Comment by arieloO** [comment]
Hi @alanjhughes, first of all thank you for addressing these issues.

I have tried to port these fixes to my app, also ran this branch locally (launching the _apps/bare-expo_ app), the plugin & mods are working as expected but the browser still closes when backgrounded.
Plus I'm always having this issue at launch (in _bare-expo_ and in my project) :
the app is backgrounded before the app is fully loaded (while still on splash screen). It does not crash though, as I'm able to re-open it from "recents" and it ends up loading correctly.

https://github.com/user-attachments/assets/9cbcefa3-127d-4e5a-9950-155399bfbefb

Do you have an idea of why that might happen ? (I am not familiar to native android dev, so I can't help much, sorry)

thx

**Comment by jmargolis-percipio** [comment]
Hey there! Our application is currently experiencing this poor UX for login behavior. I wanted to check in to see if work in this PR is on going or if there is anything we can do to try to help move it along?

**Comment by arieloO** [comment]
@jmargolis-percipio 
> Hey there! Our application is currently experiencing this poor UX for login behavior. I wanted to check in to see if work in this PR is on going or if there is anything we can do to try to help move it along?

I finally found kind of a "workaround", adding `createTask: false` in params

```ts
      WebBrowser.openAuthSessionAsync(originUrl, baseRedirectUri, {
        /*
          Setting `createTask` to false makes the auth session open "within" the app task,
          and prevents session being dismissed when app is backgrounded for 2FA
          follow https://github.com/expo/expo/pull/34160 for updates
        */
        createTask: false,
      })
```

**Comment by jmargolis-percipio** [comment]
@arieloO ah that's cool thanks for sharing! I'm not sure this is exactly going to work for our case. Without getting into too much detail, we are using the built in universal login from auth0 so we don't actually make a call to `WebBrowser`. We might be able to hack around it but that's kinda operating outside of auth0's suggested flow

**Review by chrfalch — APPROVED** [review]
Tested on Android with/without branch applied. Seems to fix the issue with reactivating the app through the icon nicely.

**Comment by chukwumaokere** [comment]
This uses the new plugin.id syntax with the `expo-module-gradle-plugin` plugin which doesnt seem to work with my Expo SDK 52.0.44 android builds. Which i see exists in SDK 53.0-preview branches.

Is there any way to make this backwards compatible with SDK 52? I need this for my build

**Comment by JuliAnyday** [comment]
> This uses the new plugin.id syntax with the `expo-module-gradle-plugin` plugin which doesnt seem to work with my Expo SDK 52.0.44 android builds. Which i see exists in SDK 53.0-preview branches.
> 
> Is there any way to make this backwards compatible with SDK 52? I need this for my build

We also need this fix urgently.
[alanjhughes](https://github.com/alanjhughes) is there a workaround or a version we can downgrade to, to fix it?

**Comment by alanjhughes** [comment]
@JuliAnyday This issue was present for years so there is no version to downgrade to. It would have been an issue since `expo-web-browser` was created. The problem is caused by react native setting the `launchMode` in the android manifest to `singleTask` by default . This fix is experimental and not something we would be looking to backport as it is an evasive change. We need to get feedback on it's stability first.

**Comment by JuliAnyday** [comment]
@alanjhughes Thanks for getting back about this immediately. 
Okay then. Well previously it was working in our old app before migrating to expo managed workflow.
We had launchMode=singleTask in that with expo-web-browser 10.1.0.

But since it was bare workflow, we might have fixed it somehow, but that was before I got hands on the project.

>  This fix is experimental and not something we would be looking to backport as it is an evasive change. We need to get feedback on it's stability first.

I fully understand that.

Do you think it is even possible to fix / find a workaround for this when using Expo Managed and CNG?

**Comment by alanjhughes** [comment]
@JuliAnyday if you had been using the bare workflow, it's possible someone modified something to fix this problem. They would have had to. This error was present in any react native app using `expo-web-browser`. Is there a reason you can't use the latest SDK version? If you can't for whatever reason, then you can create you can create your own plugin and copy the changes from the `/plugin` folder in this PR

**Comment by JuliAnyday** [comment]
@alanjhughes Does the latest SDK support React Native 0.76 or only 0.79?
We will have to make some huge changes to be able to update the React Native version.

I think we will have to try creating a plugin based on this PR. Anything specific I should be aware of when doing this?
Again, thanks for the fast and thorough responses.

**Comment by JuliAnyday** [comment]
@alanjhughes Sounds good, I hope that is they way for now then.

>I'm curious what changes your app would need you use 0.79? React 19 issues?

Well from 0.76 to 0.79 it is a lot of changes in general. So it's more how that affects our non-expo package dependencies like react-navigation (we are not using expo-router yet), Hermes vs JSC, debugging tools and so on.

That and we don't have time to re-test all of our functionality, since we have an important deadline coming up.

**Comment by alanjhughes** [comment]
@JuliAnyday - I understand. In our testing React navigation, Hermes etc. will all work fine but I appreciate you still need to do your own testing and that takes time. I would set a side some time to try it after your deadline. If you are using CNG, upgrading should be a pretty quick process usually. You can verify the scope of the problems you will run into (or have no problems) and can quickly revert. It's better not to fall too far behind if you can because it could be much more painful making a large jump

**Comment by JuliAnyday** [comment]
@alanjhughes Not falling too far behind is definitely what I'm aiming for. Being 8 major expo versions and 9 minor react-native versions behind and having to do that update... I wouldn't wish it on my worst enemy.

So I'll see if I get time to try it out with version 53 soon.

Keep doing what you guys are doing. You're doing a bang-up job!

**Comment by alanjhughes** [comment]
@JuliAnyday - Good, let us know if you run into issues with any expo libraries. 
> Keep doing what you guys are doing. You're doing a bang-up job!

Thanks! Appreciate that 👍
