### PR TITLE
[media-library] Add saveToAssetsAsync method

### LINKED ISSUE #5089: [MediaLibrary] [IOS] Exaggerated Permissions for createAssetAsync
## TLDR
iOS 11+ added a write only permission to the camera roll. `MediaLibrary` needlessly enforces read+write permissions on methods that perform write only operations, leading to exaggerated permissions being requested.

### Environment
- Targeting iOS (10.3+) & Android (API 21+)
- Not using the Expo SDK (Unimodules setup)

```
react-native-unimodules@0.5.0
expo-media-library@6.0.0
```

### Steps to Reproduce

1. Add `NSPhotoLibraryAddUsageDescription` (**without adding** `NSPhotoLibraryUsageDescription`) to `Info.plist`
1. Download an image to the local filesystem (`localUri`)
1. Call `MediaLibrary.createAssetAsync(localUri)`

### Expected Behavior

Asset creation should succeed on iOS 11+.

### Actual Behavior
An error stating `CAMERA_ROLL permission is required to do this operation` will be thrown from [this line.](https://github.com/expo/expo/blob/40387ef9d42f8fc8df808dc28335e515056b1684/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L868)

### The Cause
I apologise for not supplying a demo, instead I'll describe what's causing this issue and how to fix it.

iOS 11.0 added a new permission key called `NSPhotoLibraryAddUsageDescription`, which provides **write only** access to the user's photos. This allows apps to save photos to the device, without being able to read the user's photos.

However, [this line](https://github.com/expo/expo/blob/master/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L868), originally called from [here](https://github.com/expo/expo/blob/40387ef9d42f8fc8df808dc28335e515056b1684/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L84) checks for the `CAMERA_ROLL` permission, which Expo defines as **both read & write**.

This check causes the **read** permission to be needlessly enforced for **write** operations on devices running iOS 11+ (to date, over 90% of the iOS devices in the world)

### Fixing this issue
- It's possible to split `_checkPermissions` to `_checkReadPermissions` and `_checkWritePermissions` and call these as required by the MediaLibrary methods. On devices running iOS < 11.0 (<10%), checkReadPermissions can fall back to enforce the `NSPhotoLibraryUsageDescription` key.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #5089.

# How

Adding a new method, which needs `write only` access to users's gallery.

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/80162f

### CODE REVIEW

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2015-present 650 Industries. All rights reserved.
+
+#import <Foundation/Foundation.h>
+#import <UMCore/UMUtilities.h>
+#import <EXMediaLibrary/EXMediaLibrary.h>
+
+typedef void(^EXAssetsSaveCallback)(id asset, NSError *error);
+
+@interface EXAssetsSaveDelegate : NSObject
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h]:
```suggestion
@interface EXSaveToLibraryDelegate : NSObject
```
?

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2015-present 650 Industries. All rights reserved.
+
+#import <Foundation/Foundation.h>
+#import <UMCore/UMUtilities.h>
+#import <EXMediaLibrary/EXMediaLibrary.h>
+
+typedef void(^EXAssetsSaveCallback)(id asset, NSError *error);
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h]:
```suggestion
typedef void(^EXSaveToLibraryCallback)(id asset, NSError *error);
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m [hunk 3]
```diff
@@ -25,13 +26,22 @@ @interface EXMediaLibrary ()
 @property (nonatomic, weak) id<UMPermissionsInterface> permissionsManager;
 @property (nonatomic, weak) id<UMFileSystemInterface> fileSystem;
 @property (nonatomic, weak) id<UMEventEmitterService> eventEmitter;
+@property (nonatomic, strong) NSMutableSet *assetsSaveDelegates;
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m]:
```suggestion
@property (nonatomic, strong) NSMutableSet *saveToLibraryDelegates;
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m [hunk 4]
```diff
@@ -25,13 +26,22 @@ @interface EXMediaLibrary ()
...
 @end
 
 @implementation EXMediaLibrary
 
 UM_EXPORT_MODULE(ExponentMediaLibrary);
 
+- (instancetype) init
+{
+  if (self = [super init]) {
+    _assetsSaveDelegates = [NSMutableSet new];
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m]:
```suggestion
    _saveToLibraryDelegates = [NSMutableSet new];
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m [hunk 5]
```diff
@@ -143,6 +153,44 @@ - (NSDictionary *)constantsToExport
...
+                    reject:(UMPromiseRejectBlock)reject)
+{
+  if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSPhotoLibraryAddUsageDescription"] == nil) {
+    return reject(@"E_NO_PERMISSIONS", @"This app is missing NSPhotoLibraryAddUsageDescription. Add this entry to your bundle's Info.plist.", nil);
+  }
+  PHAssetMediaType assetType = [EXMediaLibrary _assetTypeForUri:localUri];
+  NSURL *assetUrl = [self.class _normalizeAssetURLFromUri:localUri];
+  UM_WEAKIFY(self)
+  __block EXAssetsSaveDelegate *delegate = [EXAssetsSaveDelegate new];
+  [_assetsSaveDelegates addObject:delegate];
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m]:
```suggestion
  [_saveToLibraryDelegates addObject:delegate];
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m [hunk 6]
```diff
@@ -143,6 +153,44 @@ - (NSDictionary *)constantsToExport
...
+                    resolve:(UMPromiseResolveBlock)resolve
+                    reject:(UMPromiseRejectBlock)reject)
+{
+  if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSPhotoLibraryAddUsageDescription"] == nil) {
+    return reject(@"E_NO_PERMISSIONS", @"This app is missing NSPhotoLibraryAddUsageDescription. Add this entry to your bundle's Info.plist.", nil);
+  }
+  PHAssetMediaType assetType = [EXMediaLibrary _assetTypeForUri:localUri];
+  NSURL *assetUrl = [self.class _normalizeAssetURLFromUri:localUri];
+  UM_WEAKIFY(self)
+  __block EXAssetsSaveDelegate *delegate = [EXAssetsSaveDelegate new];
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m]:
```suggestion
  __block EXSaveToLibraryDelegate *delegate = [EXSaveToLibraryDelegate new];
```

File: packages/expo-media-library/src/MediaLibrary.ts [hunk 7]
```diff
@@ -198,6 +198,13 @@ export async function createAssetAsync(localUri: string): Promise<Asset> {
   return asset;
 }
 
+export async function saveToAssetsAsync(localUri: string): Promise<void> {
```
Comment (tsapeta) [inline packages/expo-media-library/src/MediaLibrary.ts]:
```suggestion
export async function saveToLibraryAsync(localUri: string): Promise<void> {
```

File: packages/expo-media-library/src/MediaLibrary.ts [hunk 8]
```diff
@@ -198,6 +198,13 @@ export async function createAssetAsync(localUri: string): Promise<Asset> {
...
+  if (!MediaLibrary.saveToAssetsAsync) {
```
Comment (tsapeta) [inline packages/expo-media-library/src/MediaLibrary.ts]:
```suggestion
  if (!MediaLibrary.saveToLibraryAsync) {
```

File: packages/expo-media-library/src/MediaLibrary.ts [hunk 9]
```diff
@@ -198,6 +198,13 @@ export async function createAssetAsync(localUri: string): Promise<Asset> {
...
+    throw new UnavailabilityError('MediaLibrary', 'saveToAssetsAsync');
```
Comment (tsapeta) [inline packages/expo-media-library/src/MediaLibrary.ts]:
```suggestion
    throw new UnavailabilityError('MediaLibrary', 'saveToLibraryAsync');
```

File: packages/expo-media-library/src/MediaLibrary.ts [hunk 10]
```diff
@@ -198,6 +198,13 @@ export async function createAssetAsync(localUri: string): Promise<Asset> {
...
+  }
+  return await MediaLibrary.saveToAssetsAsync(localUri);
```
Comment (tsapeta) [inline packages/expo-media-library/src/MediaLibrary.ts]:
```suggestion
  return await MediaLibrary.saveToLibraryAsync(localUri);
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m [hunk 11]
```diff
@@ -143,6 +153,44 @@ - (NSDictionary *)constantsToExport
   }];
 }
 
+UM_EXPORT_METHOD_AS(saveToAssetsAsync,
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m]:
```suggestion
UM_EXPORT_METHOD_AS(saveToLibraryAsync,
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m [hunk 12]
```diff
@@ -143,6 +153,44 @@ - (NSDictionary *)constantsToExport
...
+                    saveToAssetsAsync:(nonnull NSString *)localUri
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m]:
```suggestion
                    saveToLibraryAsync:(nonnull NSString *)localUri
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.m [hunk 13]
```diff
@@ -0,0 +1,53 @@
...
+
+@interface EXAssetsSaveDelegate ()
+
+@property (nonatomic, strong) EXAssetsSaveCallback callback;
+
+@end
+
+@implementation EXAssetsSaveDelegate : NSObject
+
+- (void)writeImage:(UIImage *)image withCallback:(EXAssetsSaveCallback)callback
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.m]:
```suggestion
- (void)writeImage:(UIImage *)image withCallback:(EXSaveToLibraryCallback)callback
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.m [hunk 14]
```diff
@@ -0,0 +1,53 @@
...
+{
+  _callback = callback;
+  UIImageWriteToSavedPhotosAlbum(image,
+                                 self,
+                                 @selector(image:didFinishSavingWithError:contextInfo:),
+                                 nil);
+}
+
+- (void)writeVideo:(NSString *)movieUrl withCallback:(EXAssetsSaveCallback) callback
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.m]:
```suggestion
- (void)writeVideo:(NSString *)movieUrl withCallback:(EXSaveToLibraryCallback) callback
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h [hunk 15]
```diff
@@ -0,0 +1,15 @@
...
+
+@interface EXAssetsSaveDelegate : NSObject
+
+- (void)writeImage:(UIImage *)image withCallback:(EXAssetsSaveCallback)callback;
+
+- (void)writeVideo:(NSString *)movieUrl withCallback:(EXAssetsSaveCallback) callback;
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h]:
```suggestion
- (void)writeVideo:(NSString *)movieUrl withCallback:(EXSaveToLibraryCallback) callback;
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h [hunk 16]
```diff
@@ -0,0 +1,15 @@
...
+
+#import <Foundation/Foundation.h>
+#import <UMCore/UMUtilities.h>
+#import <EXMediaLibrary/EXMediaLibrary.h>
+
+typedef void(^EXAssetsSaveCallback)(id asset, NSError *error);
+
+@interface EXAssetsSaveDelegate : NSObject
+
+- (void)writeImage:(UIImage *)image withCallback:(EXAssetsSaveCallback)callback;
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h]:
```suggestion
- (void)writeImage:(UIImage *)image withCallback:(EXSaveToLibraryCallback)callback;
```

File: packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h [hunk 17]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2015-present 650 Industries. All rights reserved.
+
+#import <Foundation/Foundation.h>
+#import <UMCore/UMUtilities.h>
+#import <EXMediaLibrary/EXMediaLibrary.h>
```
Comment (tsapeta) [inline packages/expo-media-library/ios/EXMediaLibrary/EXAssetsSaveDelegate.h]: Do we need to import `EXMediaLibrary.h` and `UMUtilities.h` here?

**Review by tsapeta — CHANGES_REQUESTED** [review]
Looks good except the method name 😄 Thanks for fixing this!

**Comment by tsapeta** [comment]
Some CI jobs are failing here 😱

**Review by tsapeta — APPROVED** [review]
