### PR TITLE
fix(uri-scheme): escape special characters in the URL search parameters before opening on device

### LINKED ISSUE #35192: uri-scheme: pipe characters in passed URL are not escaped for the shell
### Summary

I wanted to test a deep link just now. Following [the documentation over at reactnavigation.org](https://reactnavigation.org/docs/deep-linking/#testing-with-npx-uri-scheme) I used a command like `npx uri-scheme open "mychat://chat/jane" --android`, only my URL has query parameters, some of which have values containing the pipe character.

This command

```
npx uri-scheme open "mychat://chat/jane?test=a|b|c" --android
```

Has this output:

```
› Android: Opening URI "mychat://chat/jane?test=a|b|c" in emulator

/system/bin/sh: b: inaccessible or not found
/system/bin/sh: c: inaccessible or not found
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=mychat://chat/... flg=0x10000000 }
```

I find the fact that it tried to execute binaries called `b` and `c` alarming.

### What platform(s) does this occur on?

Android

### SDK Version

uri-scheme 1.3.3

### Environment

```text
Linux
Node 20.10.0
```

### Minimal reproducible example

```
npx uri-scheme open "mychat://chat/jane?test=a|b|c" --android
```

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #35192, #34105 

# How

This adds automatic special characters escaping when running `npx uri-scheme open ..`. Unfortunately, the URI provided is technically not a URL, usually the host is missing - so we can't use `new URL` parsing. And both Android and iOS are behaving slightly different when it comes to these escaping rules.

Because there isn't a lot of documentation out there that indicates exactly what character needs to be escaped and how, I also added a new `--raw` flag to disable URI escaping fully. That way, users can still run as-is through an opt-in.

# Test Plan

- `bun create expo ./test-urischeme`
- Set the **app.json** `scheme` to `testuri`
- Modify the **app/(tabs)/explore.tsx** file to render the search parameters
  ```tsx
  export default function TabTwoScreen() {
    const params = useLocalSearchParams();

    return (
      <SafeAreaView>
        <View style={{ margin: 16 }}>
          {Object.entries(params).map(([key, value]) => (
            <View key={key}>
              <ThemedText type="defaultSemiBold">{key}</ThemedText>
              <ThemedText>{value}</ThemedText>
            </View>
          ))}
        </View>
      </SafeAreaView>
    );
  }
  ```
- Create production builds for both Android and iOS
  - `bun expo run android --variant release`
  - `bun expo run ios --configuration Release`
- Test URLs through:
  - `npx uri-scheme open "testuri://explore"`
  - `npx uri-scheme open "testuri://(tabs)/explore"`
  - `npx uri-scheme open "testuri://explore?test=a|b|c"`
  - `npx uri-scheme open "testuri://(tabs)/explore?test=a|b|c&other=@1"`
  - _All of these URLs should open the correct screen + show the right data on both Android & iOS_

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/uri-scheme/src/Android.ts [hunk 1]
```diff
@@ -186,3 +186,32 @@ async function readConfigAsync(path: string): Promise<any> {
...
+ * @example
+ *   - `myapp://(tabs)/explore` -> `myapp://\(tabs\)/explore`
+ *   - `myapp://(tabs)/explore?test=a|b|c` -> `myapp://\(tabs\)/explore?test=a%257Cb%257Cc`
+ */
+export function escapeUri(uri: string) {
+  // Split the URI into protocol, path, and params - each have different escaping rules
+  const [protocol, uriWithoutProtocol] = uri.split('://', 2);
+  const [uriPath, uriParams] = uriWithoutProtocol.split('?', 2);
+
+  // Escape non-escaped URI path special characters
```
Comment (byCedric) [inline packages/uri-scheme/src/Android.ts:202]:
```suggestion
  // Escape special characters in the URI path using a single backslash
```

File: packages/uri-scheme/src/Android.ts [hunk 2]
```diff
@@ -186,3 +186,32 @@ async function readConfigAsync(path: string): Promise<any> {
...
+  // See: https://datatracker.ietf.org/doc/html/rfc1738#section-2.2
+  const escapedUriPath = uriPath.replace(/(^|[^\\])([$\-_.+!*'(),])/g, '$1\\$2');
+
+  if (uriParams?.length) {
+    // Escape every individual search paramter's value
+    const escapedUriParams = new URLSearchParams(uriParams);
```
Comment (byCedric) [inline packages/uri-scheme/src/Android.ts:208]:
```suggestion
  if (uriParams?.length) {
    const escapedUriParams = new URLSearchParams(uriParams);
```

File: packages/uri-scheme/src/Android.ts [hunk 3]
```diff
@@ -186,3 +186,32 @@ async function readConfigAsync(path: string): Promise<any> {
...
+/**
+ * ADB expects special characters in both the URI path and search parameters to be escaped.
+ *
+ * @example
+ *   - `myapp://(tabs)/explore` -> `myapp://\(tabs\)/explore`
+ *   - `myapp://(tabs)/explore?test=a|b|c` -> `myapp://\(tabs\)/explore?test=a%257Cb%257Cc`
+ */
+export function escapeUri(uri: string) {
+  // Split the URI into protocol, path, and params - each have different escaping rules
+  const [protocol, uriWithoutProtocol] = uri.split('://', 2);
```
Comment (byCedric) [inline packages/uri-scheme/src/Android.ts:199]:
```suggestion
export function escapeUri(uri: string) {
  const [protocol, uriWithoutProtocol] = uri.split('://', 2);
```
