### PR TITLE
[camera][android] Fix rendering order

### LINKED ISSUE #30720: [Android] Images inside of CameraView appear on top of its children
### Minimal reproducible example

https://snack.expo.dev/@dpelkey-tillys/thankful-red-macaroni-and-cheese

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Check the snack. On android the red square is hidden underneath the background image whereas on iOS it displays properly. This only occurs while it is wrapped in CameraView. This also occurs with any image inside of cameraview. I tried using an absolute positioned image with the same result.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.7.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/opt/ruby/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.22 => 51.0.22
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

Not fixing the listed packages as irrelevant

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.22 - expected version: ~51.0.23
  expo-dev-client@4.0.20 - expected version: ~4.0.21
  expo-notifications@0.28.11 - expected version: ~0.28.13
  typescript@5.5.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #30720
Views such as `ImageBackground` were not rendering their child views in the correct order. This is because we manually handled when child views were added and it appears the order was not consistent on each render. Ideally, we would not support children in this component as it is not a container and should not be treated as one.

I may just use a suggestion @aleqsio made and render children as siblings but a common use case seems to be rendering the camera inside of modals so I'll need to test that.

# How
~~Because we don't target below android 21, we can drop `onViewAdded` and set the elevation on the `PreviewView` directly. This ensures it will always appear behind everything else without directly changing the order.~~

Edit 1: 
Second attempt
We explicitly bring all children to the front as well as moving the PreviewView to the back. I'm still not completely happy with the results here. We should recommend against using children with this component. My feeling is the functionality should be deprecated. If there is no opposition, I will do that cc @brentvatne @tsapeta @lukmccall  The desired effects can be achieved with absolute positioning.

# Test Plan
Bare expo using the provided repro code. Child views now render in the correct order.

### CODE REVIEW

File: packages/expo-image/src/utils.ts [hunk 1]
```diff
@@ -114,5 +114,5 @@ export function resolveTransition(
  * Checks whether the given value is an instance of the ImageRef class.
  */
 export function isImageRef(value: any): value is ImageRef {
-  return value instanceof ImageModule.Image;
+  return !!ImageModule.Image && value instanceof ImageModule.Image;
```
Comment (alanjhughes) [inline packages/expo-image/src/utils.ts:117]: Temporary workaround for android

**Review by tsapeta — APPROVED** [review]
I'm also not a fan of `ImageBackground`, but there seemed to be a high demand from our users as they used it with the RN Image.
In my opinion, if we want to deprecate or remove it, we should make a guide on how to migrate from other image components to `expo-image` (we should probably do this anyway 😅)
