### PR TITLE
fix(cli): Fix incorrect `--device` input for `run:ios`'s `launchApp` call and strenghten types

### LINKED ISSUE #42611: Can't run on multiple iOS simulators from different worktrees
### Minimal reproducible example

Happens on any repo.

### Steps to reproduce

I have two git worktrees of the same repo. Both are on different folders of course.

I then run the following commands, one on each worktree:
- pnpm expo run:ios --port 8081 --device "iPhone 16e"
- pnpm expo run:ios --port 8082 --device "iPhone 16 Pro Max"

The first one launches fine and connects to iPhone 16e.

The second one builds fine, but never launches, and for some reason changes the device its targeting right at the end, as shown in the next image with the yellow arrows. It gets stuck in this state permanently (actually sometimes it steals the simulator from the other expo server and actually runs)

Image

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: macOS 15.3.1
      Shell: 5.3.3 - /opt/homebrew/bin/bash
    Binaries:
      Node: 24.11.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 11.6.1 - /usr/local/bin/npm
      Watchman: 2025.09.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2513.14007798
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
16/17 checks passed. 1 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check that packages match versions required by installed Expo SDK
npm warn Unknown env config "dangerously-allow-all-builds". This will stop working in the next major version of npm.
npm warn Unknown project config "dangerously-allow-all-builds". This will stop working in the next major version of npm.
Advice:
Use 'npx expo install --check' to review and upgrade your dependencies.
To ignore specific packages, add them to "expo.install.exclude" in package.json. Learn more: https://expo.fyi/dependency-validation
```

I'm using expo 54.

### LINKED ISSUE #43144: [expo run:ios] --device flag ignored when opening dev-client deep link — launches on wrong simulator
## Summary

`expo run:ios --device <UDID>` correctly builds and installs the app on the specified simulator, but then opens the dev-client deep link on the **wrong** simulator (the "best booted" one from `getBestBootedSimulatorAsync`), ignoring the `--device` flag entirely.

## Root Cause

In [`packages/@expo/cli/src/run/ios/launchApp.ts`](https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/run/ios/launchApp.ts), the `launchAppAsync` function passes the wrong object to `openCustomRuntimeAsync`:

```ts
// line ~105–119 (compiled JS, line ~66 in TS source)
const device = await AppleDeviceManager.resolveAsync({
    device: props.device
});
await device.installAppAsync(binaryPath);

// BUG: `device` here is an AppleDeviceManager instance, NOT a raw Device.
// AppleDeviceManager has no top-level `udid` property.
await manager.getDefaultDevServer().openCustomRuntimeAsync('simulator', {
    applicationId: appId
}, {
    device   // <-- passes AppleDeviceManager, not Device
});
```

`openCustomRuntimeAsync` eventually calls `ensureSimulatorOpenAsync`, which checks `device?.udid`. Since `AppleDeviceManager` doesn't have a `udid` property at its top level (the raw `Device` is at `device.device`), the check fails and falls back to `getBestBootedSimulatorAsync()`, which picks the first booted simulator regardless of the `--device` flag.

## Downstream effects

1. The deep link is sent to a different simulator than the one the app was just installed on.
2. If the app happens to be installed on that other sim, it launches there — confusing the developer.
3. If the app is NOT installed there, `expo` hangs indefinitely waiting for a response that never comes.
4. In a multi-simulator workflow (e.g. git worktrees with dedicated simulators), this makes `--device` effectively unusable.

## Fix

Change `{ device }` to `{ device: device.device }` so the raw `Device` object (which has `.udid`) is forwarded:

```diff
 await manager.getDefaultDevServer().openCustomRuntimeAsync('simulator', {
     applicationId: appId
 }, {
-    device
+    device: device.device
 });
```

Here is the unified patch for the compiled JS (`build/src/run/ios/launchApp.js`):

```diff
@@ -115,7 +115,7 @@
     await manager.getDefaultDevServer().openCustomRuntimeAsync('simulator', {
         applicationId: appId
     }, {
-        device
+        device: device.device
     });
 }
```

## Environment

- `@expo/cli`: 55.0.6, 55.0.7 (both affected)
- `expo`: 55.0.0-preview.7 → 55.0.0-preview.10
- macOS 15.x, Xcode 16.x
- Multiple booted iOS simulators

## Reproduction

1. Boot two iOS simulators (e.g. "iPhone 17 Pro" and a custom sim).
2. Run `npx expo run:ios --device <UDID-of-custom-sim>`.
3. Observe the "Opening on..." log — it targets the custom sim correctly.
4. But the deep link (`exp+<scheme>://expo-development-client/...`) is sent to the **other** (default/first-booted) simulator.

## Workaround

Apply this patch to `node_modules/@expo/cli/build/src/run/ios/launchApp.js` in your postinstall:

```diff
-        device
+        device: device.device
```

### PR DESCRIPTION
**Pull request by kitten**
# Why

Resolves #43144
Resolves #42611
Supersedes #35570

The types of the `BundlerDevServer`'s `PlatformManager` calls were very loosely typed, which cause us to miss that we passed the device manager (`device`) itself rather than the device (`device.device`). A few utility types can strengthen this and prevent this from happening again.

# How

- Determine strict `Platform`-dependent device, device manager, and launch props types
- Update `launchApp` to use `device.device`

# Test Plan

- Types themselves document the correctness of this change
- For reproduction steps of the issue itself, check the resolved issue (#43144)

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/@expo/cli/src/run/android/runAndroidAsync.ts [hunk 1]
```diff
@@ -104,10 +104,10 @@ export async function runAndroidAsync(projectRoot: string, { install, ...options
     await installAppAsync(androidProjectRoot, props);
   }
 
-  await manager.getDefaultDevServer().openCustomRuntimeAsync<AndroidOpenInCustomProps>(
+  await manager.getDefaultDevServer().openCustomRuntimeAsync(
     'emulator',
     {
-      applicationId: props.packageName,
+      applicationId: props.packageName + 'test',
```
Comment (kitten) [inline packages/@expo/cli/src/run/android/runAndroidAsync.ts]:
```suggestion
      applicationId: props.packageName,
```

File: packages/@expo/cli/src/start/server/BundlerDevServer.ts [hunk 2]
```diff
@@ -519,13 +535,25 @@ export abstract class BundlerDevServer {
...
       debug(`Creating platform manager (platform: ${platform}, port: ${port})`);
-      this.platformManagers[platform] = new Manager(this.projectRoot, port, {
+      const managerParams = {
         getCustomRuntimeUrl: this.urlCreator.constructDevClientUrl.bind(this.urlCreator),
         getExpoGoUrl: this.getExpoGoUrl.bind(this),
         getRedirectUrl: this.getRedirectUrl.bind(this, platform),
         getDevServerUrl: this.getDevServerUrl.bind(this, { hostType: 'localhost' }),
-      });
+      };
+      switch (platform) {
```
Comment (kitten) [inline packages/@expo/cli/src/start/server/BundlerDevServer.ts:544]: Note: this is just for type-narrowing, but we can technically also add one more cast to make this work

**Review by EvanBacon — APPROVED** [review]
