### PR TITLE
[tracking-transparency][iOS] Run methods on the main thread

### LINKED ISSUE #20271: iOS crash TrackingTransparencyPermissionRequester doing work on background thread
### Summary

Looks like `requestTrackingAuthorizationWithCompletionHandler` eventually calls `-[UIApplication applicationState]` which is expected to only be called on the main thread.
```
4  UIKitCore                      0x18d3d4 -[UIApplication applicationState] + 56
5  AppTrackingTransparency        0x2be4 +[ATTrackingManager applicationStateActive] + 56
6  AppTrackingTransparency        0x2f00 +[ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:] + 440
```

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 3.2.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/colton.schlosser/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.15 => 46.0.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.69.7 => 0.69.7
      react-native-web: 0.18.9 => 0.18.9
    Expo Workflow: bare
```

### Minimal reproducible example

```
Crashed: com.apple.root.default-qos
0  libobjc.A.dylib                0x3120 objc_retain + 16
1  UIKitCore                      0x3d0a28 -[_UIWindowSceneFBSSceneLifecycleMonitor currentActivationState] + 144
2  UIKitCore                      0x1746bc -[UIScene activationState] + 108
3  UIKitCore                      0x4c676c -[_UISceneLifecycleMultiplexer applicationState] + 200
4  UIKitCore                      0x18d3d4 -[UIApplication applicationState] + 56
5  AppTrackingTransparency        0x2be4 +[ATTrackingManager applicationStateActive] + 56
6  AppTrackingTransparency        0x2f00 +[ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:] + 440
7  <App>                          0x2bd1f0 specialized TrackingTransparencyPermissionRequester.requestPermissions(resolver:rejecter:) + 4302344688 (<compiler-generated>:4302344688)
8  <App>                          0x2bcd9c @objc TrackingTransparencyPermissionRequester.requestPermissions(resolver:rejecter:) + 4302343580 (<compiler-generated>:4302343580)
9  <App>                          0x272c4c -[EXPermissionsService askForGlobalPermissionUsingRequesterClass:withResolver:withRejecter:] + 132 (EXPermissionsService.m:132)
10 <App>                          0x272b74 -[EXPermissionsService askForPermissionUsingRequesterClass:resolve:reject:] + 116 (EXPermissionsService.m:116)
11 <App>                          0x2bca98 closure #2 in TrackingTransparencyModule.definition() + 4302342808
12 <App>                          0x2bcb00 partial apply for closure #3 in TrackingTransparencyModule.definition() + 4302342912 (<compiler-generated>:4302342912)
13 <App>                          0x283524 specialized closure #3 in AsyncFunctionComponent.call(by:withArguments:callback:) + 96 (AsyncFunctionComponent.swift:96)
14 <App>                          0x2861c8 partial apply for specialized closure #3 in AsyncFunctionComponent.call(by:withArguments:callback:) + 4302119368 (<compiler-generated>:4302119368)
15 <App>                          0x3b860 thunk for @escaping @callee_guaranteed () -> () + 4299716704 (<compiler-generated>:4299716704)
16 libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
18 libdispatch.dylib              0x6858 _dispatch_queue_override_invoke + 720
19 libdispatch.dylib              0x13b94 _dispatch_root_queue_drain + 340
20 libdispatch.dylib              0x1439c _dispatch_worker_thread2 + 172
21 libsystem_pthread.dylib        0x1dd4 _pthread_wqthread + 224
22 libsystem_pthread.dylib        0x193c start_wqthread + 8
```

### PR DESCRIPTION
**Pull request by cltnschlosser**
# Why

Fixes https://github.com/expo/expo/issues/20271

# How

Added `.runOnQueue(.main)` for expo-tracking-transparency module.

# Test Plan

`yarn ios` in `apps/bare-expo`
Simulator Screen Shot - iPhone 14 - 2022-11-30 at 10 01 04

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-tracking-transparency/ios/TrackingTransparencyModule.swift [hunk 1]
```diff
@@ -16,6 +16,7 @@ public class TrackingTransparencyModule: Module {
         reject: promise.legacyRejecter
       )
     }
+    .runOnQueue(.main)
```
Comment (tsapeta) [inline packages/expo-tracking-transparency/ios/TrackingTransparencyModule.swift:19]: The crash that you provided is coming from `requestPermissionsAsync`, is it also the case in `getPermissionsAsync`? If not, I think it would be better not to run it on the main thread.

**Review by tsapeta — APPROVED** [review]
Cool, thanks for your contribution! I'm almost sure it worked in previous iOS versions. I wish Apple takes care of switching to the main thread when it's necessary or at least document whether the function requires it or not 😅 
I left one comment below

File: packages/expo-tracking-transparency/ios/TrackingTransparencyModule.swift (hunk 1 above)
Comment (cltnschlosser) [reply packages/expo-tracking-transparency/ios/TrackingTransparencyModule.swift:19]: I'm not sure. I've only seen this crash twice (9 days apart - different users), so it seems to be somewhat rare. Whether `getPermissionsAsync` is safe to call off the main thread is up to apple's implementation. My guess is that it's not required to call on the main thread, but this seemed safer. I'll let you make that decision though.
I'm guessing it's only `requestPermissionsAsync` that's required to be on the main thread, because it shows UI, whereas `getPermissionsAsync` won't result in UI showing, but I can't know for sure (without reverse engineering apple's implementation. Or them updating the documentation.)

**Comment by Norfeldt** [comment]
@tsapeta 

sdk46: xcode 14.0.1 works with reload for me (but xcode 14.1 or 14.2 crash the app) but it is giving me this warning when I do the refresh:

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'requestPermissionsAsync' of undefined
TypeError: Cannot read property 'requestPermissionsAsync' of undefined
    at ?anon_0_ (http://192.168.147.248:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:361925:45)
    at next (native)
    at asyncGeneratorStep (http://192.168.147.248:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25086:26)
    at _next (http://192.168.147.248:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25108:29)
    at anonymous (http://192.168.147.248:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25115:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
...
```

Do you think this PR would fix that?

**Comment by cltnschlosser** [comment]
@Norfeldt 
> Do you think this PR would fix that or should I report the issue?

That looks unrelated. Looks like these functions are entirely missing in the JS at runtime.

**Comment by Norfeldt** [comment]
> @Norfeldt
> 
> > Do you think this PR would fix that or should I report the issue?
> 
> That looks unrelated. Looks like these functions are entirely missing in the JS at runtime.

@cltnschlosser I sorry to side-tracking this PR a little, but do you by any chance have an advice for me. I have done

```
❯ rg -c "requestPermissionsAsync" node_modules
node_modules/jest-expo/src/preset/expoModules.js:13
node_modules/expo-modules-core/build/PermissionsInterface.js.map:1
node_modules/expo-modules-core/build/PermissionsInterface.d.ts:1
node_modules/expo-modules-core/src/PermissionsInterface.ts:1
node_modules/expo-notifications/CHANGELOG.md:2
node_modules/expo-notifications/src/NotificationPermissionsModule.types.ts:1
node_modules/expo-notifications/src/NotificationPermissionsModule.ts:1
node_modules/expo-notifications/src/NotificationPermissions.ts:6
node_modules/expo-notifications/build/NotificationPermissions.js:6
node_modules/expo-notifications/build/NotificationPermissions.js.map:1
node_modules/expo-notifications/build/NotificationPermissionsModule.js.map:1
node_modules/expo-notifications/build/NotificationPermissionsModule.types.d.ts:1
node_modules/expo-notifications/build/NotificationPermissions.d.ts:2
node_modules/expo-notifications/build/NotificationPermissionsModule.js:1
node_modules/expo-notifications/build/NotificationPermissionsModule.types.js.map:1
node_modules/expo-notifications/README.md:4
node_modules/expo-notifications/ios/EXNotifications/Permissions/EXNotificationPermissionsModule.m:2
node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/permissions/NotificationPermissionsModule.java:1
node_modules/expo-tracking-transparency/src/TrackingTransparency.ts:3
node_modules/expo-tracking-transparency/build/TrackingTransparency.js:3
node_modules/expo-tracking-transparency/ios/TrackingTransparencyModule.swift:1
node_modules/expo-tracking-transparency/build/TrackingTransparency.js.map:1
```

I can only figure out to pin it down to that it's either `expo-modules-core`, `expo-notifications` or `expo-tracking-transparency` that is causing the issue. But now I have no clue on what to do? 🤷‍♂️

**Comment by cltnschlosser** [comment]
@tsapeta When you have a chance, I rebased this and added a changelog.
