### PR TITLE
[expo-notifications] Fix notification icon in standalone app & add large icon support on the android

### LINKED ISSUE #9062: [expo-notifications] Android notification icon when using useNextNotificationsApi
### Steps to Reproduce

1. Setup a bare Expo project
2. Add the PN example from the Expo docs
3. Switch to the new `useNextNotificationsApi` code.
4. Send a PN on your Android device

_I cannot create a snack as it doesn't seem to allow for modifying the `app.json`._

Repository: https://github.com/1337LutZ/android-pn-icon-bug

### Expected Behavior vs Actual Behavior
It used to work as intended:
- Transparency shows as transparant
- Anything white will be opaque in the bar / notification list. (white or chosen icon color)

Actual behavior:
- Transparency inside an icon now no longer gets "cut out". The icon will show only as a white/black square/circle depending on your OS settings.

Screenshots:
Screenshot_20200702-092217
Screenshot_20200702-092227

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/9062

# How

- Added `ScopedExpoNotificationBuilder` and injected it in the `ScopedExpoNotificationsService`
- Added `loadIconBitmapSync` method to `ExponentManifest` 
- In the builder overwrite  `getIcon` method 
- Added `getLargeIcon` method

# Test Plan

- send notifications via https://expo.io/notifications and confirm that the icon has changed

# Changelog

- [feature] Added support for custom large icon on the Android.

### CODE REVIEW

File: android/expoview/src/main/java/host/exp/exponent/notifications/ScopedExpoNotificationBuilder.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+        e.printStackTrace();
+      }
+    }
+
+    return this;
+  }
+
+  @Override
+  protected int getIcon() {
+    return Constants.isStandaloneApp() ? R.drawable.shell_notification_icon : R.drawable.notification_icon;
```
Comment (mczernek) [inline android/expoview/src/main/java/host/exp/exponent/notifications/ScopedExpoNotificationBuilder.java:58]: Why do we need this distinction?

**Review by mczernek — APPROVED** [review]
LGTM

File: android/expoview/src/main/java/host/exp/exponent/notifications/ScopedExpoNotificationBuilder.java (hunk 1 above)
Comment (lukmccall) [reply android/expoview/src/main/java/host/exp/exponent/notifications/ScopedExpoNotificationBuilder.java:58]: To be honest, I'm not sure. In the previous implementation, it looked like this. I assume that `R.drawable.shell_notification_icon` will be replaced with an image from the manifest.
