### PR TITLE
[android][audio] Update player on main thread when focus changes

### LINKED ISSUE #36948: [expo-audio][expo-video] Player is accessed on the wrong thread.
### Minimal reproducible example

https://github.com/anasvemmully/expo-audio-video-crash

### Steps to reproduce

1. Navigate to /audio
2. click buttons to play sound
3. Back and navigate to /video
4. play the video
5. then, App Exits after crash

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.12.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
      Watchman: 2025.02.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
      Android SDK:
        API Levels: 31, 32, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-26 | ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-33 | Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23726.103.2422.12816248
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^53.0.9 => 53.0.9 
      expo-router: ~5.0.3 => 5.0.7 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.2 => 0.79.2 
      react-native-web: ^0.20.0 => 0.20.0 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #36948

# How
Player updates need to run on the main thread. Updated the calls in the `audioFocusChangeListener` 

# Test Plan
Bare-expo

### CODE REVIEW

File: packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt [hunk 1]
```diff
@@ -63,15 +63,19 @@ class AudioModule : Module() {
...
         focusAcquired = false
         if (interruptionMode == InterruptionMode.DUCK_OTHERS) {
           players.values.forEach {
-            it.player.volume /= 2f
+            runOnMain {
+              it.player.volume /= 2f
+            }
           }
         }
       }
```
Comment (behenate) [inline packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt:81]: when `interruptionMode == InterruptionMode.DO_NOT_MIX` or others shouldn't we pause the player? Or is it paused somewhere else?

**Review by behenate — APPROVED** [review]

File: packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt:81]: That's handled in `requestAudioFocus`. We don't prevent mixing in your own app. Interruption mode is only relevant when we are interrupted by another app.

Comment (behenate) [reply packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt:81]: Makes sense, thanks!

**Comment by WillyReyno** [comment]
@alanjhughes Hello, I just wanted to let you know this PR is listed in the [changelog](https://github.com/expo/expo/blob/main/packages/expo-audio/CHANGELOG.md) under version 0.4.5, but it has actually not been released in it. Is this a mistake?

**Comment by anirudhsama** [comment]
@WillyReyno Yes, it wasn't released in 0.4.5. It is included in 0.4.6.

@alanjhughes btw this is causing massive ANRs. Around 18% of all sessions of our app version with this is having an ANR. Getting a stack trace like this:

```
          main (timed waiting):tid=1 systid=12192 
       at sun.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:98)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
       at kotlinx.coroutines.BuildersKt.runBlocking(unavailable:1)
       at expo.modules.audio.AudioModule.runOnMain(AudioModule.kt:526)
       at expo.modules.audio.AudioModule.audioFocusChangeListener$lambda$5(AudioModule.kt:66)
       at expo.modules.audio.AudioModule.$r8$lambda$FOMeMJryr7m5vP94yj6g3vUJOng(AudioModule.kt)
       at expo.modules.audio.AudioModule$$ExternalSyntheticLambda0.onAudioFocusChange(D8$$SyntheticClass)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:3817)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8103)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     ```
