### PR TITLE
[localization] Fix  two specific platform issues for Android and Web

### LINKED ISSUE #21414: [expo-localization] Exception: Unsupported ISO 3166 country: es_419
### Minimal reproducible example

https://gist.github.com/andresribeiro/569e4d70afe1778e8f2541e301433017

### Summary

The following error appears on Play Console pre-launch report:

```
Exception com.facebook.react.common.JavascriptException: Error: Call to function 'ExpoLocalization.getLocales' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: es_419, js engine: hermes, stack:
_construct@1:105491
Wrapper@1:105136
_createSuperInternal@1:645189
CodedError@1:645474
findBestAvailableLanguage@1:703297
getBestAvailableLanguage@1:703599
setBestAvailableDayJsLocale@1:692514
anonymous@1:692458
loadModuleImplementation@1:73062
guardedLoadModule@1:72611
metroRequire@1:72239
anonymous@1:690154
loadModuleImplementation@1:73062
guardedLoadModule@1:72611
metroRequire@1:72239
anonymous@1:79390
loadModuleImplementation@1:73062
guardedLoadModule@1:72568
metroRequire@1:72239
global@1:71823
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:72)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop (Looper.java:223)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:228)
  at java.lang.Thread.run (Thread.java:923)
```

It might be related to these 2 issues from `react-native-localize`:

https://github.com/zoontek/react-native-localize/issues/31
https://github.com/zoontek/react-native-localize/issues/36

### Environment

System:
  OS: Linux 5.4 Linux Mint 20.3 (Una)
  Shell: 5.8 - /usr/bin/zsh
Binaries:
  Node: 19.7.0 - /usr/bin/node
  Yarn: 1.22.19 - /usr/bin/yarn
  npm: 9.5.0 - /usr/bin/npm
  Watchman: 20220605.192726.0 - /usr/local/bin/watchman
npmPackages:
  expo: ~48.0.4 => 48.0.4 
  react: 18.2.0 => 18.2.0 
  react-native: 0.71.3 => 0.71.3 
npmGlobalPackages:
  eas-cli: 3.7.2
  expo-cli: 6.3.2
Expo Workflow: managed

### LINKED ISSUE #22009: Localization.getCalendars() gets an incorrect timezone on web
### Minimal reproducible example

https://snack.expo.dev/MlFZ4YUTbA

### Summary

Affected platforms: web

**Note**: I'm in the `America/Vancouver` timezone, so the output may be different for people in different timezones. To repro this reliably, you must be in the `America/Vancouver` timezone.

In the above snack, the correct timezone (`America/Vancouver`) is calculated with [getLocalizationAsync](https://docs.expo.dev/versions/latest/sdk/localization/#localizationgetlocalizationasync) and `Intl.DateTimeFormat().resolvedOptions().timeZone`. When using `Localization.getCalendars()`, I get `America/Adak`, which is 2 hours behind my current timezone.

### Environment

``` 
❯ npx expo-env-info
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.3 
      expo: ~48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      expo-cli: 6.2.1
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Closes: https://github.com/expo/expo/issues/21414

I'm unable to replicate it since it can't really happen in production – Android doesn't let you set a locale without a country.
This should fix the pre-launch report.

Closes: https://github.com/expo/expo/issues/22009
On web we now use `resolvedOptions` instead of `navigator.languages` for calendars.

# How

# Test Plan

Tested in bare expo if it doesn't break for some weird reason.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
A few nitpicks:
- CI jobs are failing
- Missing changelog entry
- Can we log when the exception occurred?

File: packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.kt [hunk 1]
```diff
@@ -131,26 +131,30 @@ class LocalizationModule : Module() {
...
+            "measurementSystem" to getMeasurementSystem(locale),
+            "currencyCode" to decimalFormat.currency.currencyCode,
+
+            // currency symbol can be localized to display locale (1st on the list) or to the locale for the currency (as done here).
+            "currencySymbol" to Currency.getInstance(locale).getSymbol(locale),
+          )
         )
-      )
+      } catch (Exception e) {
+        // we don't append the problematic locale to the list
```
Comment (Simek) [inline packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.kt:156]: Can we output some kind information for the users when this happens, so they can address the issues or remove the problematic locale?

**Review by tsapeta — APPROVED** [review]
