### PR TITLE
[sqlite][docs] Fix typo in `withTransactionAsync(task)` example

### LINKED ISSUE #29085: [docs] expo-sqlite getAsync function reference
### Summary

In the withTransactionAsync example there is a function "getAsync" which is only referenced in that part of documentation.

The function executed should probably be **getAllAsync**" or **getFirstAsync**. 

When i try to use getAsync in latest version of the expo-sqlite I get that the function doesn't exist. 

This is probably a typo

Image for reference:
image

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/sqlite/

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

Fix #29085

# How

Fix the typo in the  `withTransactionAsync(task)` example and update it to use `getFirstAsync()` method.

# Test Plan

Changes applied to `unversioned` by running `et gdad -p expo-sqlite`.

Changes applied to SDK 51 API reference by generating source using `et` command from SDK 51 branch, stashing those changes, and then bringing the data generated file (expo-sqlite.json) to this branch.

## Preview of updated example

CleanShot 2024-06-07 at 17 10 32@2x

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-sqlite/src/SQLiteDatabase.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export class SQLiteDatabase {
    *   // The following UPDATE query out of transaction may be executed here and break the expectation.
    *   //
    *
-   *   const result = await db.getAsync<{ name: string }>('SELECT name FROM Users');
+   *   const result = await db.getAllAsync<{ name: string }>('SELECT name FROM Users');
```
Comment (Kudo) [inline packages/expo-sqlite/src/SQLiteDatabase.ts:84]:
```suggestion
   *   const result = await db.getFirstAsync<{ name: string }>('SELECT name FROM Users');
```

since we have `result?.name`, it should be getFirstAsync() for single entitle.

**Review by Kudo — APPROVED** [review]
thanks for helping this!

File: packages/expo-sqlite/src/SQLiteDatabase.ts (hunk 1 above)
Comment (amandeepmittal) [reply packages/expo-sqlite/src/SQLiteDatabase.ts:84]: Thanks for correcting that! Let me update this!

**Review by alanjhughes — APPROVED** [review]

File: packages/expo-sqlite/src/SQLiteDatabase.ts (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-sqlite/src/SQLiteDatabase.ts:84]: Looks like a couple of the tests are broken @Kudo. Unrelated to this change. They are already failing on main

Comment (amandeepmittal) [reply packages/expo-sqlite/src/SQLiteDatabase.ts]: > since we have result?.name, it should be getFirstAsync() for single entitle.

Done.

**Review by Simek — APPROVED** [review]

**Comment by Kudo** [comment]
weird. the expo-sqlite unit test looks broken for unknown reason. i'll fix in a seperate pr.

**Comment by Kudo** [comment]
> weird. the expo-sqlite unit test looks broken for unknown reason. i'll fix in a seperate pr.

fix in this pr https://github.com/expo/expo/pull/29540
