### PR TITLE
[config-plugins] Improve error handling in plugin resolver

### LINKED ISSUE #37917: Unknown file type error in node_modules/expo-modules-core after installing expo-crypto
### Minimal reproducible example

https://github.com/NajmKHoda/expo-crypto-issue

### Steps to reproduce

1. `cd` to the project folder.
2. Run `npm install` to fetch all dependencies.
3. Attempt to run *any* Expo-related command:
  - `npx expo start`
  - `npx expo run:ios`
  - `npx expo run:android`
  - `npx expo prebuild`

When any of the above commands are run, the following error will occur:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /.../node_modules/expo-modules-core/src/index.ts
```

This is quite strange since `expo-modules-core` seems to work normally in a project without `expo-crypto`, but upon installing `expo-crypto` (which is its own dependency), `expo-modules-core` breaks.

I don't see any changes to the `package-lock.json` entry of `expo-modules-core` either. This can be confirmed by running `git diff HEAD~1 HEAD package-lock.json`.

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 11.2.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
    IDEs:
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.17 => 53.0.19 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.5 => 0.79.5 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
npx expo-doctor@latest cannot be run due to the issue at hand.
```

### PR DESCRIPTION
**Pull request by hirbod**
# Why

This PR tackles an interesting bug where AI-generated configurations were referencing config plugins that don't actually exist (like expo-crypto, expo-clipboard, expo-print, expo-share). This was leading to some unexpected errors.

The core of the issue arises when a package is added to Expo's config plugin array, but that package *doesn't* actually ship a config plugin. If that package's main entry point isn't a JavaScript file or the main entry point imports types or `UnavailabilityError` from `expo-module-core`, which has `src/index.ts` as `main` field, it could cause a ".ts UNKNOWN_FILE_EXTENSION" error. 

# How
Since we only handled a very specific case (`error instanceof SyntaxError`) and threw the error for every other issue, it was very cryptic and users did not easily understand what was going on. I've updated the error handling logic in `resolveConfigPluginFunctionWithInfo` to include more detailed messages about the underlying errors and potential issues with the plugin reference. I also added a link to the documentation for further assistance. The most helpful piece is likely that we now print the `pluginReference` that caused the issue.

I also removed the redundant`SyntaxError` check and just returning the generic Error message. I think it contains enough information to be generally useful, and it makes that function cleaner and a bit more lightweight and universal.

Fixes #37917

Closes ENG-16728

# Test Plan

Before | After
-- | --
Screenshot 2025-07-25 at 14 40 49 | Screenshot 2025-08-02 at 10 35 18

Text:
```bash
PluginError: Unable to resolve a valid config plugin for expo-crypto.
• No "app.plugin.js" file found in expo-crypto: config plugins are typically exported from an "app.plugin.js" file in the package root.
• main export of expo-crypto does not appear to be a config plugin: the following error was thrown when importing /Users/hirbod/Expo/repros/StickerSmash/node_modules/expo-crypto/build/Crypto.js: Unknown file extension ".ts" for /Users/hirbod/Expo/repros/StickerSmash/node_modules/expo-modules-core/src/index.ts ERR_UNKNOWN_FILE_EXTENSION
Verify that expo-crypto includes a config plugin. If it does not, then remove the entry from plugins in your app config file. Learn more: https://docs.expo.dev/guides/config-plugins/
```

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by hirbod** [comment]
@byCedric let me know if I should remove the `SyntaxError` check. I think the generic one should be enough

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts [hunk 1]
```diff
@@ -115,19 +115,36 @@ export function resolveConfigPluginFunctionWithInfo(projectRoot: string, pluginR
...
+      stack = errorWithCode.stack;
+    } else {
+      underlyingError = String(error);
     }
-    throw error;
+
+    let errorMessage =
+      `Could not find a valid config plugin for "${pluginReference}".\n` +
+      `We found "${pluginFile}" but an error was thrown while requiring it.\n` +
+      `Make sure that the package actually ships a config plugin.\n\n`;
```
Comment (vonovak) [inline packages/@expo/config-plugins/src/utils/plugin-resolver.ts]:
```suggestion
      `Make sure that ${pluginReference} actually ships a config plugin. If not, remove the entry from the app config file.\n\n`;
```

**Review by vonovak — APPROVED** [review]
one tiny suggestion

Definitely feels more informative :100:

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts (hunk 1 above)
Comment (hirbod) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts]: Thx for the suggestion and tinkering with me, added!

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts [hunk 2]
```diff
@@ -115,19 +115,36 @@ export function resolveConfigPluginFunctionWithInfo(projectRoot: string, pluginR
...
+      underlyingError = `${errorWithCode.message} ${errorWithCode.code ?? ''}`;
+      stack = errorWithCode.stack;
+    } else {
+      underlyingError = String(error);
     }
-    throw error;
+
+    let errorMessage =
+      `Could not find a valid config plugin for "${pluginReference}".\n` +
+      `We found "${pluginFile}" but an error was thrown while requiring it.\n` +
```
Comment (brentvatne) [inline packages/@expo/config-plugins/src/utils/plugin-resolver.ts]:
```suggestion
      `Found "${pluginFile}", but an error was thrown while importing it.\n` +
```

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts [hunk 3]
```diff
@@ -115,19 +115,36 @@ export function resolveConfigPluginFunctionWithInfo(projectRoot: string, pluginR
...
-      // If the plugin reference is a node module, and that node module has a syntax error, then it probably doesn't have an official config plugin.
-      if (!isPluginFile && !moduleNameIsDirectFileReference(pluginReference)) {
-        const pluginError = new PluginError(
-          `Package "${pluginReference}" does not contain a valid config plugin.\n${learnMoreLink}\n\n${error.message}`,
-          'INVALID_PLUGIN_IMPORT'
-        );
-        pluginError.stack = error.stack;
-        throw pluginError;
-      }
+    const learnMoreLink = `Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin`;
```
Comment (brentvatne) [inline packages/@expo/config-plugins/src/utils/plugin-resolver.ts]:
```suggestion
    const learnMoreLink = `Learn more: https://docs.expo.dev/guides/config-plugins/`;
```

let's avoid using an anchor since that is easy to change and go out of date

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts [hunk 4]
```diff
@@ -115,19 +115,36 @@ export function resolveConfigPluginFunctionWithInfo(projectRoot: string, pluginR
...
+      const errorWithCode = error as Error & { code?: string };
+      underlyingError = `${errorWithCode.message} ${errorWithCode.code ?? ''}`;
+      stack = errorWithCode.stack;
+    } else {
+      underlyingError = String(error);
     }
-    throw error;
+
+    let errorMessage =
+      `Could not find a valid config plugin for "${pluginReference}".\n` +
```
Comment (brentvatne) [inline packages/@expo/config-plugins/src/utils/plugin-resolver.ts]:
```suggestion
      `Unable to resolve a valid config plugin for "${pluginReference}".\n` +
```

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts (hunk 2 above)
Comment (brentvatne) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts]: I would move the "Config plugins are typically exported from .." (note: i'd avoid "usually" and use "typically" instead as i did here, which sounds less loose and casual) to immediately after "Unable to resolve a valid .."

so:

> PluginError: Unable to resolve a valid config plugin for "expo-crypto". Config plugins are typically exported from an "app.plugin.js" file in the package root, and "expo-crypto" does not have this file.

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts [hunk 5]
```diff
@@ -115,19 +115,36 @@ export function resolveConfigPluginFunctionWithInfo(projectRoot: string, pluginR
...
+      `We found "${pluginFile}" but an error was thrown while requiring it.\n` +
+      `Make sure that ${pluginReference} actually ships a config plugin. If not, remove the entry from the app config file.\n\n`;
```
Comment (brentvatne) [inline packages/@expo/config-plugins/src/utils/plugin-resolver.ts]: "Make sure" -> "Ensure" typically. but also saying "actually ships" is also too conversational and casual for a tool like this. i would remove that sentence.

i'd also reword it a bit more extensively and instead say

> Verify that ${pluginReference} includes a config plugin. If it does not, then remove the entry from `plugins` in your app config file.

i prefer verify here because that is a more of a verification task.

<details><summary>chatgpt comparison of verify and ensure</summary>


🔍 Verify
Means: Check if something is true or correct.
Used after something has happened or been set.

You're checking.

It's reactive.

You're confirming facts or outcomes.

Examples:

"Verify that the file was uploaded correctly."

"We need to verify his identity before granting access."

✅ Ensure
Means: Make sure something will happen or is done correctly.
Used before or during an action to guarantee a result.

You're making it happen.

It's proactive.

You're taking responsibility for success.

Examples:

"Ensure the package is delivered by Friday."

"Please ensure you lock the door when you leave."

</details>

**Review by brentvatne — CHANGES_REQUESTED** [review]

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts (hunk 5 above)
Comment (hirbod) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts]: Addressed!

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts (hunk 4 above)
Comment (hirbod) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts]: Addressed!

File: packages/@expo/config-plugins/src/utils/plugin-resolver.ts (hunk 2 above)
Comment (hirbod) [reply packages/@expo/config-plugins/src/utils/plugin-resolver.ts]: Done

**Review by brentvatne — APPROVED** [review]

**Review by EvanBacon — COMMENTED** [review]
Why does this PR update react-native?

**Comment by hirbod** [comment]
It should not. I removed the submodule update a few times (I honestly don't know why this keeps happening), and it looks like on the final rebase, it slipped in front of my eyes.

**Comment by hirbod** [comment]
@EvanBacon thanks for the catch, just prepared a PR to fix it with Alan! I need to figure out why the submodule updates for me over and over again.
