### PR TITLE
[image-manipulator] Fix handling urls from the photo library

### LINKED ISSUE #28772: [expo-media-library][iOS] No suitable URL request handler found Expo 51
### Minimal reproducible example

https://github.com/iM-GeeKy/image-bug

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Starting in Expo 51 and on iOS only (Expo Go and Development Builds), it appears `MediaLibrary.getAssetsAsync` returns assets with a `uri` that contain `ph://` which conflicts with the documentation that says `URI that points to the asset. assets://* (iOS), file://* (Android)` and causes downstream issues as demonstrated in the sample repository provided, where it gets the first asset from your photos and tries to call `ImageManipulator.manipulateAsync` resulting in a the attached error (see below). 

Previously in Expo 50 this code worked as expected which is what should be expected in Expo 51. There appears to be an [old related issue](https://github.com/expo/expo/issues/15664), but considering this has worked for me up until Expo 51, it seems to be an issue.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #28772
`PHAsset.fetchAssets(withALAssetURLs:, options:)` has been deprecated since iOS 11 so we need to retrieve the image differently when it is selected from the user's photo library. 

# How
Use a different function on `PHAsset` to handle these URLs.

# Test Plan
Bare expo and the provided repro. The image is selected and resized correctly.

### CODE REVIEW

File: packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    return image.jpegData(compressionQuality: compression)
+  case .png:
+    return image.pngData()
+  case .webp:
+    return SDImageWebPCoder.shared.encodedData(with: image, format: .webP, options: [.encodeCompressionQuality: compression])
+  }
+}
+
+/**
+ Checks is we are dealing with a ph asset URL and uses the correct method to fetch it.
```
Comment (lukmccall) [inline packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift:19]:
```suggestion
 Checks if we are dealing with a ph asset URL and uses the correct method to fetch it.
```

File: packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ */
+func retreiveAsset(from url: URL) -> PHAsset? {
+  if url.scheme == "ph" {
+    let identifier = String(url.absoluteString.dropFirst(5))
```
Comment (lukmccall) [inline packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift:23]:
```suggestion
    let identifier = String(url.absoluteString.dropFirst(5)) // removes ph://
```

**Review by lukmccall — APPROVED** [review]

File: packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+    return image.pngData()
+  case .webp:
+    return SDImageWebPCoder.shared.encodedData(with: image, format: .webP, options: [.encodeCompressionQuality: compression])
+  }
+}
+
+/**
+ Checks if we are dealing with a ph asset URL and uses the correct method to fetch it.
+ */
+func retreiveAsset(from url: URL) -> PHAsset? {
```
Comment (tsapeta) [inline packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift:21]: `retreiveAsset` -> `retrieveAsset`
That's how not waiting for my spellchecking review ends up 😂

Comment (alanjhughes) [reply packages/expo-image-manipulator/ios/ImageManipulatorUtils.swift:21]: 😅 Damn it

**Comment by Dalvii** [comment]
Hello, How can I use this fixed version of Expo please ? Thank you
