### PR TITLE
[file-system][ios] Fix downloadAsync for local files

### LINKED ISSUE #26502: expo sqlite / expo-file-system unsupported url 1002 on ios bundle
### Minimal reproducible example

https://github.com/Sznapsollo/expo_ios_bundle_unsupportedurl_1002

### Summary

Case: copy sqlite db3 database from app assets to documentDirectory.

While it works perfectly on android expo, android simulator bundle, android prod bundle, ios expo
It does not work on ios bundle (simulator or production) returning error below. It happens when i build locally and also when app is build using expo services.

Exception is Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" (also attached screen from catch lot on ios)

It happens when performing the following code:
```
       await FileSystem.downloadAsync(
          Asset.fromModule(require('./assets/test_database.db3')).uri,
          FileSystem.documentDirectory + 'SQLite/test_database.db3'
        );
```
db3 extensions are added and also configured in metro.config.js in assetExts

I have browsed many docs about this but nothing works so far.
I have found similar bug report - https://github.com/expo/expo/issues/23455
This report contains info how to handle this by @alanjhughes but comment is what turns out I am actually using and the result is still 1002

image

Thank you kindly for your help

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 6.0.0
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Currently `FileSystem.downloadAsync` does not support "downloading" local files.  In most cases, users should just use `FileSystem.copyAsync`  instead, but the problem is that if you're using `Asset.fromModule(require("")).url` in dev mode you will get a remote URL (pointing to the bundler) and in prod that same call resolver to a local file path, causing this method to work differently in prod vs debug

Closes https://github.com/expo/expo/issues/26502

# How

Update `downloadAsync` method to check if source URL is a local file and then copy it to the destination instead of trying to download it with URLSession.downloadTask

# Test Plan

Run NCL through BareExpo on dev and release and ensure `downloadAsync` works as expected 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: apps/native-component-list/src/screens/FileSystemScreen.tsx [hunk 1]
```diff
@@ -334,6 +346,7 @@ export default class FileSystemScreen extends React.Component<object, State> {
         <ListButton onPress={this._getInfoAsset} title="Get Info Asset" />
         <ListButton onPress={this._copyAndReadAsset} title="Copy and Read Asset" />
         <ListButton onPress={this._alertFreeSpace} title="Alert free space" />
+        <ListButton onPress={this._downloadAndReadLocalAsset} title="Download & local asset" />
```
Comment (tsapeta) [inline apps/native-component-list/src/screens/FileSystemScreen.tsx:349]:
```suggestion
        <ListButton onPress={this._downloadAndReadLocalAsset} title="Download and read local asset" />
```

File: packages/expo-file-system/ios/FileSystemModule.swift [hunk 2]
```diff
@@ -134,18 +134,23 @@ public final class FileSystemModule: Module {
...
+        let taskDelegate = EXSessionDownloadTaskDelegate(
+          resolve: promise.resolver,
+          reject: promise.legacyRejecter,
+          localUrl: localUrl,
+          shouldCalculateMd5: options.md5
+        )
+
+        sessionTaskDispatcher.register(taskDelegate, for: downloadTask)
+        downloadTask.resume()
+      }
```
Comment (tsapeta) [inline packages/expo-file-system/ios/FileSystemModule.swift:153]: Let's avoid using `if/else` when there could be one `if` with a `return`. Then the rest of the code doesn't need an indent

```suggestion
      if sourceUrl.isFileURL {
        try ensurePathPermission(appContext, path: sourceUrl.path, flag: .read)
        EXFileSystemLocalFileHandler.copy(from: sourceUrl, to: localUrl, resolver: promise.resolver, rejecter: promise.legacyRejecter)
        return
      }
      let session = options.sessionType == .background ? backgroundSession : foregroundSession
      let request = createUrlRequest(url: sourceUrl, headers: options.headers)
      let downloadTask = session.downloadTask(with: request)
      let taskDelegate = EXSessionDownloadTaskDelegate(
        resolve: promise.resolver,
        reject: promise.legacyRejecter,
        localUrl: localUrl,
        shouldCalculateMd5: options.md5
      )

      sessionTaskDispatcher.register(taskDelegate, for: downloadTask)
      downloadTask.resume()
```

**Review by tsapeta — APPROVED** [review]

**Review by Kudo — APPROVED** [review]
