### PR TITLE
[expo-print][android] Fix file loading

### LINKED ISSUE #13560: [expo-print] _printDocumentPickerPDFAsync not loading file
### Summary

After picking document to print, document is loading and nothing happens. I also noticed that variable pageCount in object PrintDocumentInfo is set to -1, so problem can be connected with PrintDocumentInfo object.
You can run it by clicking "Print PDF (document picker)" in native-component-list.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

_No response_

### Environment

 Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
        Android NDK: 21.0.6113669
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0-alpha.0 => 42.0.0-alpha.0 
      react-native: 0.63.2 => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://github.com/expo/expo/blob/f78248927f701443a40c9713b5c2df5d67288504/packages/expo-print/android/src/main/java/expo/modules/print/PrintModule.java#L141

### PR DESCRIPTION
**Pull request by mstach60161**
# Why

Fixes #13560.

# How

- Fixed copying to output stream bug.
- Added promise resolving.

# Test Plan

- Native component list.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

### CODE REVIEW

File: packages/expo-print/android/src/main/java/expo/modules/print/FileUtils.kt [hunk 1]
```diff
@@ -27,4 +36,37 @@ object FileUtils {
...
+    FileOutputStream(destination.fileDescriptor).use {
+      val buf = ByteArray(1024)
+      var bytesRead = input.read(buf)
+      while (bytesRead > 0) {
+        it.write(buf, 0, bytesRead)
+        bytesRead = input.read(buf)
+      }
+      callback.onWriteFinished(arrayOf(PageRange.ALL_PAGES))
+    }
+  }
```
Comment (lukmccall) [inline packages/expo-print/android/src/main/java/expo/modules/print/FileUtils.kt:51]: I think you can simplify this function using https://stackoverflow.com/a/35529070/13361748.

**Review by lukmccall — APPROVED** [review]
LGTM 💪 
You can apply one more improvement 😉

**Comment by lukmccall** [comment]
Please run `./gradlew :expo-print:spotlessApply`
