### PR TITLE
fix(cli): filter ADB trace logs from the device list

### LINKED ISSUE #27421: Unable to find attached android devices when ADB_TRACE=adb is set
### Summary

Short story - `getAttachedDevicesAsync` from `node_modules/@expo/cli/build/src/start/platforms/android/adb.js` is using `adb devices -l` to find the devices, but when `ADB_TRACE=adb` is set, it is unable to extract properly due to presence of debug log lines.

The `const type = line.includes("emulator") ? "emulator" : "device";` is not sufficient to detect if a line is an `emulator` or `device` when logs are present. Example log here under has lines that don't include `emulator` and clearly are not not device.

```
adb devices
03-04 12:29:44.557 16415 16415 D adb     : adb_trace.cpp:187 Android Debug Bridge version 1.0.41
03-04 12:29:44.557 16415 16415 D adb     : adb_trace.cpp:187 Version 35.0.0-11411520
03-04 12:29:44.557 16415 16415 D adb     : adb_trace.cpp:187 Installed as /home/user/SDKs/Android/platform-tools/adb
03-04 12:29:44.557 16415 16415 D adb     : adb_trace.cpp:187 Running on Linux 5.15.133.1-microsoft-standard-WSL2 (x86_64)
03-04 12:29:44.557 16415 16415 D adb     : adb_trace.cpp:187
03-04 12:29:44.557 16415 16415 D adb     : commandline.cpp:1646 Using server socket: tcp:172.27.192.1:5037
03-04 12:29:44.557 16415 16415 D adb     : adb_client.cpp:160 _adb_connect: host:version
03-04 12:29:44.558 16415 16415 D adb     : adb_client.cpp:194 _adb_connect: return fd 3
List of devices attached
03-04 12:29:44.558 16415 16415 D adb     : adb_client.cpp:400 adb_query: host:devices
03-04 12:29:44.558 16415 16415 D adb     : adb_client.cpp:358 adb_connect: service: host:devices
03-04 12:29:44.558 16415 16415 D adb     : adb_client.cpp:160 _adb_connect: host:devices
03-04 12:29:44.558 16415 16415 D adb     : adb_client.cpp:194 _adb_connect: return fd 3
03-04 12:29:44.558 16415 16415 D adb     : adb_client.cpp:376 adb_connect: return fd 3
emulator-5554   device
```

### What platform(s) does this occur on?

Android

### SDK Version

50.0.8

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.21 - /mnt/c/Users/istoica/AppData/Roaming/npm/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ^50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
      react-native-web: ~0.19.10 => 0.19.10 
    Expo Workflow: bare

### Minimal reproducible example

The issue can be reproduced by setting `ADB_TRACE=adb` globally on any OS

On Windows we cannot build native modules for expo so we normally go to WSL. WSL needs some dance:

```
export WSL_HOST_IP="$(tail -1 /etc/resolv.conf | cut -d' ' -f2)"
export ADB_SERVER_SOCKET=tcp:$WSL_HOST_IP:5037
export ADB_TRACE=adb
export EXPO_DEBUG=1
export ANDROID_SERIAL=emulator-5554
export REACT_NATIVE_PACKAGER_HOSTNAME=$(ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
```

Example

1. Start emulator avd `emulator -avd Pixel_3a_API_34_extension_level_7_x86_64`
2. Start adb server `adb kill-server && adb -a -P 5037 nodaemon server start`
3. Start socat for `5037` `socat -d -d TCP-LISTEN:5037,reuseaddr,fork TCP:$(cat /etc/resolv.conf | tail -n1 | cut -d " " -f 2):5037`
4. Start socat for `5554` `socat -d -d TCP-LISTEN:5554,reuseaddr,fork TCP:$(cat /etc/resolv.conf | tail -n1 | cut -d " " -f 2):5554`
5. Attempt launching android `yarn android`

Note - Android Studio works with all these settings, it is able to detect what device is really there probably without relying on the CLI or avoiding/unsetting `ADB_TRACE=adb` when `adb devices -l` is issued

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #27421

# How

Filter logs based on mentions of `adb_trace.cpp:<line>`, `adb_client.cpp:<line>`, or `commandline.cpp:<line>`.

# Test Plan

See issue #27421

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/start/platforms/android/adb.ts [hunk 1]
```diff
@@ -229,7 +229,16 @@ export function adbArgs(pid: Device['pid'], ...options: string[]): string[] {
 export async function getAttachedDevicesAsync(): Promise<Device[]> {
   const output = await getServer().runAsync(['devices', '-l']);
 
-  const splitItems = output.trim().replace(/\n$/, '').split(os.EOL);
+  const splitItems = output
+    .trim()
+    .replace(/\n$/, '')
```
Comment (byCedric) [inline packages/@expo/cli/src/start/platforms/android/adb.ts:234]:
```suggestion
    .replace(/\n(\r)?$/, '')
```

Comment (byCedric) [reply packages/@expo/cli/src/start/platforms/android/adb.ts:234]: Or use EOL

**Review by EvanBacon — APPROVED** [review]
