### PR TITLE
[expo-permissions] Fix multiple permissions request crash on Android

### LINKED ISSUE #12248: Android app crashes when user denies permissions
### Summary

My application requires 'ACCESS_FINE_LOCATION' and 'CAMERA', permissions. When the user denies the location permissions the Android app crashes.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/ShaneMcNamara/android-permissions-crash

When a user denies both location and camera perms, the app crashes. iOS handles this case correctly. Both permissions are in my `app.config.js` 

Through testing, it appears that when the user denies location permissions, the app is not able to present camera permissions and crashes. Here's some test cases I've run and the results:

1. Open app and accept both permissions. App works fine.
2. Open app and accept location permissions. App will show camera permissions request. Deny camera permissions. App works fine.
3. Open app and deny location permissions. App crashes. 
4. Go into the Android app settings and manually enable Camera permissions. Open app and deny location permissions. App works fine.

This also happens in the Expo Go app.

After further testing, I believe this is caused by [requesting permissions at the same time](https://github.com/expo/expo/issues/1848).

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes ENG-650.
Fixes https://github.com/expo/expo/issues/12248

# How

React Native doesn't allow asking for multiple permissions in separate calls before receiving responses. So we need to queue permission calls.

# Test Plan

- Expo Go and bare-expo
  - https://snack.expo.io/@brents/carefree-candy
  -  NCL 
 
# Changelog 

- Fixed multiple permissions request crash on Android

### CODE REVIEW

File: packages/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt [hunk 1]
```diff
@@ -230,20 +234,50 @@ open class PermissionsService(val context: Context) : InternalModule, Permission
...
+          mCurrentPermissionListener = listener
+          currentActivity.requestPermissions(permissions, PERMISSIONS_REQUEST, createPermissionRequester())
+        }
+      }
+    } else {
+      listener.onResult(parseNativeResult(permissions, IntArray(permissions.size) { PackageManager.PERMISSION_DENIED }))
+    }
+  }
+
+  private fun createPermissionRequester(): PermissionListener {
```
Comment (esamelson) [inline packages/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt:252]:
```suggestion
  private fun createListenerWithPendingPermissionsRequest(): PermissionListener {
```

File: packages/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt [hunk 2]
```diff
@@ -230,20 +234,50 @@ open class PermissionsService(val context: Context) : InternalModule, Permission
...
-            listener.onResult(parseNativeResult(receivePermissions, IntArray(receivePermissions.size) { PackageManager.PERMISSION_DENIED }))
-            false
+    val currentActivity = mActivityProvider?.currentActivity
+    if (currentActivity is PermissionAwareActivity) {
+      synchronized(this@PermissionsService) {
+        if (mCurrentPermissionListener != null) {
+          mPendingPermissionCalls.add(permissions to listener)
+        } else {
+          mCurrentPermissionListener = listener
+          currentActivity.requestPermissions(permissions, PERMISSIONS_REQUEST, createPermissionRequester())
```
Comment (esamelson) [inline packages/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt:244]:
```suggestion
          currentActivity.requestPermissions(permissions, PERMISSIONS_REQUEST, createListenerWithPendingPermissionsRequest())
```

File: packages/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt [hunk 3]
```diff
@@ -230,20 +234,50 @@ open class PermissionsService(val context: Context) : InternalModule, Permission
...
+              pendingCall.second.onResult(parseNativeResult(pendingCall.first, IntArray(pendingCall.first.size) { PackageManager.PERMISSION_DENIED }))
+              mPendingPermissionCalls.forEach {
+                it.second.onResult(parseNativeResult(it.first, IntArray(it.first.size) { PackageManager.PERMISSION_DENIED }))
+              }
+              mPendingPermissionCalls.clear()
+              return@let
+            }
+
+            mCurrentPermissionListener = pendingCall.second
+            activity.requestPermissions(pendingCall.first, PERMISSIONS_REQUEST, createPermissionRequester())
```
Comment (esamelson) [inline packages/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt:273]:
```suggestion
            activity.requestPermissions(pendingCall.first, PERMISSIONS_REQUEST, createListenerWithPendingPermissionsRequest())
```

**Review by esamelson — APPROVED** [review]
