### PR TITLE
[image-manipulator] Handle url with no scheme by prepending file:// scheme

### LINKED ISSUE #4806: "File isn't readable" when using `ImageManipulator.manipulateAsync` with Expo SDK 33 on iOS
## 🐛 Bug Report
"File isn't readable" when using `ImageManipulator.manipulateAsync` with Expo SDK 33 on iOS.

### Environment

`Expo client iOS:  2.11.1.106175`

```
Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.3.2 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2
```
Issue appears in iPhone and iOS simulator only. It works with Android.

### Steps to Reproduce
When using `ImageManipulator.manipulateAsync` getting `File isn't readable` permission error. Snapshot is captured and stored in the file system. However, the issue is not able to read the file.

### Expected Behavior

Should read image successfully.

### Actual Behavior
`[Unhandled promise rejection: Error: File '/private/var/mobile/Containers/Data/Application/BF2874F8-9EAF-484B-A3C7-04CF9A1401DF/tmp/ReactABI33_0_0Native/5378EF2C-5DEC-4BE0-A609-69F2CF195CFC.png' isn't readable.]`

### Reproducible Demo

Please check the Snack URL below:

https://snack.expo.io/@hussain-t/imagemanipulator

Check the console logs on Snack.

### PR DESCRIPTION
**Pull request by bbarthec**
Resolves #4806

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

File: packages/expo-image-manipulator/ios/EXImageManipulator/EXImageManipulatorModule.m [hunk 1]
```diff
@@ -41,6 +41,10 @@ - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
                     reject:(UMPromiseRejectBlock)reject)
 {
   NSURL *url = [NSURL URLWithString:uri];
+  // no scheme provided in uri, handle as a local path by adding 'file://' scheme
+  if (!url.scheme) {
+      url = [NSURL fileURLWithPath:uri isDirectory:false];
```
Comment (ide) [inline packages/expo-image-manipulator/ios/EXImageManipulator/EXImageManipulatorModule.m]:
```suggestion
    url = [NSURL fileURLWithPath:uri isDirectory:false];
```

**Review by ide — APPROVED** [review]

**Review by sjchmiela — APPROVED** [review]
Thanks for taking care of this! You could also add a CHANGELOG entry for this fix. 🙂
