### PR TITLE
[expo-file-system] Unscope paths in standalone/ejected scenarios

### LINKED ISSUE #3096: [uni] Make expo-file-system work in an app with bare RN
FS is a dependency of Asset and Print, and Asset is a dependency of Font so we first need FS to work. There are several issues we need to fix with expo-file-system:

1. Methods like `writeAsStringAsync` fail because the FS permissions module (EXFilePermissionModule) is not registered with RN outside of the Expo Client / ExpoKit. Proposed changed: if there is no FS permissions module, don't enforce any permissions. And to ensure we don't accidentally forget to register the FS permissions module for the Expo Client / ExpoKit, we assert that the permissions module is defined each time before we call a method on it in those environments.

2. EXFileSystem adds "ExponentExperienceData" to file paths. We want to provide direct access to the file system where possible so that other libraries that interact with the file system work with paths returned by expo-file-system, without "ExponentExperienceData" added to the path. In standalone apps, ExpoKit apps, and apps with bare RN, we shouldn't add "ExponentExperienceData" to file paths nor scope file paths. (Scoping is needed only in the Expo Client.)

### PR DESCRIPTION
**Pull request by Szymon20000**
# Why

closes https://github.com/expo/expo/issues/3096

# How

WIP

# Test Plan

WIP

### CODE REVIEW

File: android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java [hunk 1]
```diff
@@ -60,6 +60,22 @@ public ScopedContext(final Context context, final String scope) {
 
     mFilesDir = new File(mContext.getFilesDir() + "/ExperienceData/" + scope);
     mCacheDir = new File(mContext.getCacheDir() + "/ExperienceData/" + scope);
+
+    try {
+      ApplicationInfo app = context.getPackageManager().getApplicationInfo(context.getPackageName(),PackageManager.GET_META_DATA);
+      Bundle bundle = app.metaData;
+
+      Boolean inExpoClient = bundle.getBoolean("host.exp.exponent.InExpoClient");
```
Comment (sjchmiela) [inline android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java]: For `if expoClient` you could use `Constants.isStandaloneApp()`

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 2]
```diff
@@ -812,5 +801,20 @@ + (NSString *)escapedResourceName:(NSString *)name
   return [name stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacters];
 }
 
++ (NSString *)documentDirectoryForExperienceId:(NSString *)experienceId
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: How about moving those methods to instance methods of `EXFileSystemService` so we can just override them in `EXFileSystemBinding` and not override `EXFileSystem` at all? 🤔

File: template-files/android/AndroidManifest.xml [hunk 3]
```diff
@@ -367,6 +367,8 @@
     <!-- The Facebook SDK runs FacebookInitProvider on startup and crashes if there isn't an ID here -->
     <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="fb0"/>
 
+    <meta-data android:name="host.exp.exponent.InExpoClient" android:value="true"/>
```
Comment (sjchmiela) [inline template-files/android/AndroidManifest.xml]: This file defines both Expo Client manifest and apps built in Turtle, so this value would always be `true`

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h [hunk 4]
```diff
@@ -1,15 +1,19 @@
 // Copyright 2016-present 650 Industries. All rights reserved.
 
 #import <Foundation/Foundation.h>
-#import <EXCore/EXExportedModule.h>
+#import <EXCore/EXInternalModule.h>
 #import <EXCore/EXModuleRegistryConsumer.h>
 #import <EXCore/EXEventEmitter.h>
+#import <EXCore/EXExportedModule.h>
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h]: Unnecessary import changes

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h [hunk 5]
```diff
@@ -1,15 +1,19 @@
...
 #import <EXFileSystemInterface/EXFileSystemInterface.h>
 
-@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface>
+@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface> {
+  EXModuleRegistry *_moduleRegistry;
+}
 
 @property (nonatomic, readonly) NSString *documentDirectory;
 @property (nonatomic, readonly) NSString *cachesDirectory;
+@property (nonatomic, retain) EXModuleRegistry *moduleRegistry;
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h]:
```suggestion
@property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
```

File: android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java [hunk 6]
```diff
@@ -3,6 +3,6 @@
 // This file is auto-generated. Please don't rename!
 public class DetachBuildConstants {
 
-  public static final String DEVELOPMENT_URL = "";
+  public static final String DEVELOPMENT_URL = "exp://192.168.1.29:80";
```
Comment (sjchmiela) [inline android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java]: Revert this change

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h [hunk 7]
```diff
@@ -1,15 +1,19 @@
...
-#import <EXCore/EXExportedModule.h>
+#import <EXCore/EXInternalModule.h>
 #import <EXCore/EXModuleRegistryConsumer.h>
 #import <EXCore/EXEventEmitter.h>
+#import <EXCore/EXExportedModule.h>
 #import <EXFileSystemInterface/EXFileSystemInterface.h>
 
-@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface>
+@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface> {
+  EXModuleRegistry *_moduleRegistry;
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h]: Why define this property like this? If it's defined in the public header isn't it accessible and inheritable already? 🤔

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 8]
```diff
@@ -70,6 +69,8 @@ - (NSString *)md5String
 
 @implementation EXFileSystem
 
+@synthesize moduleRegistry = _moduleRegistry;
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: Why do you synthesize this property?

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 9]
```diff
@@ -768,28 +769,16 @@ + (BOOL)ensureDirExistsWithPath:(NSString *)path
...
-  return [EXFileSystem documentDirectoryForExperienceId:experienceId];
-}
-
-+ (NSString *)documentDirectoryForExperienceId:(NSString *)experienceId
-{
-  NSString *subdir = [self escapedResourceName:experienceId];
-  return [[[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES).firstObject
-            stringByAppendingPathComponent:@"ExponentExperienceData"]
-           stringByAppendingPathComponent:subdir] stringByStandardizingPath];
+  NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: Always annotate collection types with `<type>`

**Review by sjchmiela — COMMENTED** [review]
How about:…

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h [hunk 10]
```diff
@@ -1,12 +1,12 @@
...
 
 #import <Foundation/Foundation.h>
-#import <EXCore/EXExportedModule.h>
 #import <EXCore/EXModuleRegistryConsumer.h>
 #import <EXCore/EXEventEmitter.h>
+#import <EXCore/EXExportedModule.h>
 #import <EXFileSystemInterface/EXFileSystemInterface.h>
 
-@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface>
+@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface>
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h]: Unnecessary change

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 11]
```diff
@@ -47,9 +47,9 @@ - (instancetype)initWithId:(NSString *)uuid
 @interface EXFileSystem ()
 
 @property (nonatomic, strong) NSMutableDictionary<NSString *, EXDownloadResumable*> *downloadObjects;
-@property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
 @property (nonatomic, weak) id<EXEventEmitterService> eventEmitter;
 @property (nonatomic, weak) id<EXFileSystemManager> fileSystemManager;
+@property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
```
Comment (sjchmiela) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: Unnecessary change

File: ios/Exponent/Versioned/Core/UniversalModules/EXScopedFileSystemModule.m [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+}
+
++ (NSString *)escapedResourceName:(NSString *)name
+{
+  NSString *charactersToEscape = @"!*'();:@&=+$,/?%#[]";
+  NSCharacterSet *allowedCharacters = [[NSCharacterSet characterSetWithCharactersInString:charactersToEscape] invertedSet];
+  return [name stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacters];
+}
+
++ (NSString *)documentDirectoryForExperienceId:(NSString *)experienceId isDetached:(BOOL)isDetached {
```
Comment (sjchmiela) [inline ios/Exponent/Versioned/Core/UniversalModules/EXScopedFileSystemModule.m]: This method doesn't need to have this argument, it can just always use `[EXEnvironment sharedEnvironment].isDetached`

File: ios/Exponent/Versioned/Core/UniversalModules/EXScopedFileSystemModule.m [hunk 13]
```diff
@@ -0,0 +1,63 @@
...
+}
+
+- (NSString *)cachesDirectoryForExperienceId:(NSString *)experienceId
+{
+  return [EXScopedFileSystemModule cachesDirectoryForExperienceId:experienceId isDetached:![self isItExpoClient]];
+}
+
+- (bool)isItExpoClient
+{
+  return [_appOwnership isEqualToString:@"expo"];
```
Comment (sjchmiela) [inline ios/Exponent/Versioned/Core/UniversalModules/EXScopedFileSystemModule.m]: In `ExpoKit` we can use `EXEnvironment` to know whether the app is detached or not

File: android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java [hunk 14]
```diff
@@ -60,6 +61,11 @@ public ScopedContext(final Context context, final String scope) {
 
     mFilesDir = new File(mContext.getFilesDir() + "/ExperienceData/" + scope);
     mCacheDir = new File(mContext.getCacheDir() + "/ExperienceData/" + scope);
+
+    if (Constants.isStandaloneApp()) {
```
[the remark this answers is not in the document]
Comment (sjchmiela) [reply android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java]: bump

**Review by sjchmiela — CHANGES_REQUESTED** [review]

**Review by sjchmiela — APPROVED** [review]
Thanks! 💯

**Comment by sjchmiela** [comment]
Hey, @ide, I've added you as a reviewer to start a discussion about data migration—how do you think we should approach it? On one hand the only safe way of handling this would be to synchronously move all the files from `/ExponentExperienceData/${experienceId}` to `/` when the app starts, on the other hand this increases startup time by a call to the file system… On the other hand it's _only one FS call_… Maybe it is something we can live with and remove when we phase SDK32 out? Maybe we should save information about migration in some faster storage, like `NSUserDefaults`?

**Comment by ide** [comment]
Synchronously moving everything on the first launch seems like the best approach:

- It's simple and likely to have the fewest bugs as long as we run the migration as an atomic operation. Correctness is more important than performance here (though I think we can achieve excellent performance too).
- I like the idea of migrating all files at once instead of on-demand so that file paths are more consistent and operations like listing all of the files in the directory are simpler to implement.
- We aren't copying any file contents. Regardless of file size, we're just creating new inodes. We should benchmark it, but I expect moving even 1000 files to run in a few milliseconds. This seems like an acceptable one-time cost.
- I don't think it's necessary to store migration information in NSUserDefaults. Let the file system be the source of truth unless we find the performance to be too slow (for example, > 1 millisecond to check if the migration has happened).
- Sometimes people stay on an old SDK even after the Expo client has dropped it. We could keep this auto-migration logic even after the client no longer includes SDK 32, but perhaps make it be opt-in (ex: `Filesystem.runMigrationAsync()`) so that most apps don't run it at all.
