### PR TITLE
[camera] fix barcode types

### LINKED ISSUE #28100: How to remove the leading zero when scanning an UPC-A barcode scanner
### Minimal reproducible example

https://gist.github.com/dhavalbhuva/05d8b6bbbff1bf747c57699536d81d6e

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

So far all the items Im scanning, the scanner is adding an extra 0 in front of the barcode.. so seems like this is a European barcode scanner (EAN) instead of UPC

I am using expo-camera/next

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/orafox/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 23, 29, 30, 31, 32, 33, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0, 34.0.0, 35.0.0
        System Images: android-19 | Google APIs ARM EABI v7a, android-21 | Google APIs ARM 64 v8a, android-23 | ARM 64 v8a, android-24 | ARM 64 v8a, android-24 | Google APIs ARM 64 v8a, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs ARM 64 v8a, android-27 | ARM 64 v8a, android-27 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.14 
      react: ^18.2.0 => 18.2.0 
      react-native: ^0.73.6 => 0.73.6 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #28100
This did not actually repro on `android` and on `iOS` `upc_a` codes were never supported. I did notice that some of the types in swift were not cased correctly though which would cause casting them to fail. I also added a workaround to allow `iOS` to scan `upc_a` correctly. 

# How
`iOS` will convert these `upc_a` barcodes to `ean13` and append a leading `0`. We can check if we are dealing with an `ean13` and remove it. 

Fixed the casing issue in the barcode record.

# Test Plan
Bare-expo scanning a `upc_a` barcode.

### CODE REVIEW

File: packages/expo-camera/ios/Current/BarcodeScannerUtils.swift [hunk 1]
```diff
@@ -30,7 +32,16 @@ class BarcodeScannerUtils {
   static func avMetadataCodeObjectToDictionary(_ barcodeScannerResult: AVMetadataMachineReadableCodeObject) -> [String: Any] {
     var result = [String: Any]()
     result["type"] = barcodeScannerResult.type
-    result["data"] = barcodeScannerResult.stringValue
+
+    // iOS converts upc_a to ean13 an appends a leading 0
```
Comment (Kudo) [inline packages/expo-camera/ios/Current/BarcodeScannerUtils.swift:36]:
```suggestion
    // iOS converts upc_a to ean13 and appends a leading 0
```
typo "and"?

File: packages/expo-camera/ios/Current/BarcodeScannerUtils.swift [hunk 2]
```diff
@@ -60,6 +71,16 @@ class BarcodeScannerUtils {
     result["type"] = item.observation.symbology.rawValue
     result["data"] = item.payloadStringValue
 
+    // iOS converts upc_a to ean13 an appends a leading 0
```
Comment (Kudo) [inline packages/expo-camera/ios/Current/BarcodeScannerUtils.swift:74]:
```suggestion
    // iOS converts upc_a to ean13 and appends a leading 0
```

typo "and"?

**Review by Kudo — APPROVED** [review]
