### PR TITLE
[media-library][android] Fix requesting optional location permission

### LINKED ISSUE #15273: [expo-media-library] get/request permission always returns undetermined / denied
### Summary

MediaLibrary.getPermissionsAsync() always returns status:undetermined when granted(denied when denied), 
and when canAskAgain:true, requestPermissionsAsync() always returns granted:false immediately without asking.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.3

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 2.4.2 - /usr/local/bin/yarn
      npm: 8.1.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.3 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

install bare workflow project, 
add dependencies expo 43.0.3, expo-media-library 

> let permission = await MediaLibrary.getPermissionsAsync();
>       if (!permission.granted) {
>         if (permission.canAskAgain || permission.status === "undetermined") {
>           permission = await MediaLibrary.requestPermissionsAsync(false);
>           if (!permission.granted) {
>             //denied
>             return;
>           }
>         } else {
>           //denied
>           return;
>         }
>       }

### PR DESCRIPTION
**Pull request by barthap**
# Why

In #14413 the optional `ACCESS_MEDIA_LOCATION` permission was introduced. Generally it's optional, required only if requesting `latitude` and `longitude` from asset EXIF tags.
It can be added to `AndroidManifest.xml` [by a config plugin](https://github.com/expo/expo/issues/15273#issuecomment-1005440392) in managed, or manually in bare workflow.

But `MediaLibrary.requestPermissionsAsync()` asked for it even if it's not present in the manifest, which caused issues. 

Resolves #15273 
Resolves ENG-3968

More context: https://github.com/expo/expo/issues/15273#issuecomment-1005440392

# How

Check if the permission is present in `AndroidManifest.xml` and ask for it only if present there.

# Test Plan

- Added the `<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />` to `AndroidManifest.xml`, then ensured that `MediaLibrary.requestPermissionsAsync()` asks for media location permission.
- Removed the line from manifest, ensured that `MediaLibrary.requestPermissionsAsync()` no longer asks for it.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by ajsmth — APPROVED** [review]
thank you very much!

File: packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt [hunk 1]
```diff
@@ -234,4 +236,27 @@ object MediaLibraryUtils {
...
+      packageInfo.requestedPermissions?.toSet() ?: emptySet()
+    } catch (e: PackageManager.NameNotFoundException) {
+      Log.e("expo-media-library", "Failed to list AndroidManifest.xml permissions")
+      e.printStackTrace()
+      emptySet()
+    }
+  }
+
+  /**
+   * Checks, whenever an appplication represented by [context] contains specific [permission]
```
Comment (tsapeta) [inline packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt:253]:
```suggestion
   * Checks, whenever an application represented by [context] contains specific [permission]
```

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]
