### PR TITLE
[expo] Mark the exp prop as optional, this is only used in Expo Go

### LINKED ISSUE #3596: Sentry.wrap types don't play nicely with Expo's registerRootComponent
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Prerequisites:
- Use TypeScript
- Use React Native

1. Set up Sentry SDK as per https://docs.sentry.io/platforms/react-native/manual-setup/expo/
2. In `index.tsx` use `registerRootComponent(App);`, (worked fine before introducing Sentry), because:

> // registerRootComponent calls AppRegistry.registerComponent('main', () => App);
> // It also ensures that whether you load the app in Expo Go or in a native build,
> // the environment is set up appropriately

### Expected Result

Happy TypeScript

### Actual Result

```
Argument of type 'ComponentType<Record<string, unknown>>' is not assignable to parameter of type 'ComponentType<InitialProps>'.
  Type 'ComponentClass<Record<string, unknown>, any>' is not assignable to type 'ComponentType<InitialProps>'.
    Type 'ComponentClass<Record<string, unknown>, any>' is not assignable to type 'ComponentClass<InitialProps, any>'.
      Construct signature return types 'Component<Record<string, unknown>, any, any>' and 'Component<InitialProps, any, any>' are incompatible.
        The types of 'props' are incompatible between these types.
          Property 'exp' is missing in type 'Readonly<Record<string, unknown>>' but required in type 'Readonly<InitialProps>'.ts(2345)
registerRootComponent.d.ts(4, 5): 'exp' is declared here.
```

### Product Area

Unknown

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

Fixes https://github.com/getsentry/sentry-react-native/issues/3596

# How

Spoke with @tsapeta and @krystofwoldrich about this and decided on making `exp` optional, since it's only used in Expo Go.

# Test Plan

Let CI run

### CODE REVIEW

File: packages/expo/src/launch/registerRootComponent.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ import * as React from 'react';
 import { AppRegistry, Platform } from 'react-native';
 
 type InitialProps = {
-  exp: {
```
Comment (ide) [inline packages/expo/src/launch/registerRootComponent.tsx:7]: Suggestion to add a docblock explaining this is defined only in Expo Go

**Review by tsapeta — APPROVED** [review]
