### PR TITLE
[expo-video][android] Fix wrong event being sent when the volume is changed

### LINKED ISSUE #30734: [expo-video] Event `playingChange` emit wrong value when muted
### Minimal reproducible example

https://github.com/Dominic-Preap/expo-video-test

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

When we handled event `playingChange`, we saw that we received value from that event when we set player mute. And the value we received is an object instead of boolean. 

It shouldn't emit any value on that event when set muted.

```tsx
  const player = useVideoPlayer('some source');

  function onMuted(muted: boolean) {
    player.muted = muted;
  }

  function onPlayPause() {
    if (state.isPlaying) {
      player.pause();
    } else {
      player.play();
    }
  }

  useEffect(() => {
    const playingChange = player.addListener('playingChange', isPlaying => {
       // when set muted to true, emit this value = {"isMuted": true, "volume": 0} 
       // when set play or pause emit Boolean = true  
       cosole.log(isPlaying);
    });

    return () => {
      playingChange.remove();
    };
  }, [player]);


```

### Environment

expo-env-info 1.2.0 environment info:
  - System:
      - OS: Windows 10 10.0.19045
  - Binaries:
      - Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      - Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      - npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  - npmPackages:
      - expo: ~51.0.24 => 51.0.24
      - expo-router: ~3.5.20 => 3.5.20
      - react: 18.2.0 => 18.2.0
      - react-dom: 18.2.0 => 18.2.0
      - react-native: 0.74.3 => 0.74.3
      - react-native-web: ~0.19.10 => 0.19.12
  - Expo Workflow: bare

### Expo Doctor Diagnostics

Dependencies are up to date

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/30734

# How

During a recent refactor the wrong name has been set for the `VolumeChange` event, also noticed some bugs with behavior, which I fixed in this PR.

# Test Plan

Tested in BareExpo on Android and iOS

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

File: packages/expo-video/android/src/main/java/expo/modules/video/VideoPlayer.kt [hunk 1]
```diff
@@ -113,7 +114,9 @@ class VideoPlayer(val context: Context, appContext: AppContext, source: VideoSou
     }
 
     override fun onVolumeChanged(volume: Float) {
-      this@VideoPlayer.volume = volume
+      if (!muted) {
```
Comment (rolfb) [inline packages/expo-video/android/src/main/java/expo/modules/video/VideoPlayer.kt:117]: Is this the correct behavior? My expection would be that mute gets disabled when volume is changed.
