### PR TITLE
[sqlite] fix reentrant issue for statement.executeAsync

### LINKED ISSUE #36307: [expo-sqlite] 15.2 breaks resolving statement.executeAsync promises with Promise.all
### Minimal reproducible example

https://github.com/GiyoMoon/expo-sqlite-promise-resolve-bug

Reproduction is here: https://github.com/GiyoMoon/expo-sqlite-promise-resolve-bug/blob/main/app/(tabs)/index.tsx#L12

### What platform(s) does this occur on?

iOS, Android

### Where did you reproduce the issue?

in a development build

### Summary

After updating to the expo v53 beta which uses `expo-sqlite@15.2`, I started to notice issues when resolving promises from `statement.executeAsync` with `Promise.all`.
```ts
      // Dummy data
      const data = new Array(100).fill(0).map((_, i) => ({
        key: i,
        value: `Item ${i}`,
      }));

      const statement = await db.prepareAsync(
        'INSERT INTO key_value (key, value) VALUES ($key, $value)',
      );
      const promises = []
      for (const item of data) {
        // HERE: If we add await to the statement.executeAsync, it will work
        // const promise = await statement.executeAsync({

        const promise = statement.executeAsync({
          $key: item.key,
          $value: item.value,
        });
        promises.push(promise);
      }
      // debug to see errors
      promises.map((p) => p.catch((e) => console.log(e)));
      // This worked before in expo-sqlite 15.1 and broke in expo-sqlite 15.2
      await Promise.all(promises);
      await statement.finalizeAsync();
```
This code snippet produces errors like `UNIQUE constraint failed: key_value.key` which shouldn't happen because the data we're using doesn't have duplicate keys.

When adding `await` to the `statement.executeAsync` line to run them in order, it works again. Grouping promises like this gives a significant performance boost on Android when inserting a lot of data, that's why I'd like to continue using this method.
It worked before in `15.1` and broke when I upgraded. I'm suspecting that it's related to this PR: https://github.com/expo/expo/pull/35896

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3.2
      Shell: 4.0.1 - /Users/jasi/.nix-profile/bin/fish
    Binaries:
      Node: 22.14.0 - ~/.nix-profile/bin/node
      Yarn: 1.22.22 - ~/.nix-profile/bin/yarn
      npm: 10.9.2 - ~/.nix-profile/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/jasi/.nix-profile/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-35 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: 53.0.0-preview.9 => 53.0.0-preview.9 
      expo-router: 5.0.2-preview.4 => 5.0.2-preview.4 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.1 => 0.79.1 
      react-native-web: ~0.20.0 => 0.20.0 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #36307

# How

since #35896, the async tasks would be exeucted in parallel. however, the `statement.executeAsync` is stateful because it store parameter bindings. we have to pretect the relevant code with a lock

# Test Plan

tested repro from https://github.com/GiyoMoon/expo-sqlite-promise-resolve-bug

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by Kudo** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/36674?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#36674** <a href="https://app.graphite.dev/github/pr/expo/expo/36674?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/expo/expo/36674?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#36670** <a href="https://app.graphite.dev/github/pr/expo/expo/36670?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#36669** <a href="https://app.graphite.dev/github/pr/expo/expo/36669?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/expo-sqlite/ios/NativeStatement.swift [hunk 1]
```diff
@@ -6,6 +6,7 @@ final class NativeStatement: SharedObject, Equatable {
   var pointer: OpaquePointer?
   var isFinalized = false
   var extraPointer: OpaquePointer?
+  internal let lock = NSLock()
```
Comment (alanjhughes) [inline packages/expo-sqlite/ios/NativeStatement.swift:9]:
```suggestion
  internal let lock = DispatchSemaphore(value: 1)
```

File: packages/expo-sqlite/ios/SQLiteModule.swift [hunk 2]
```diff
@@ -371,6 +371,11 @@ public final class SQLiteModule: Module {
     try maybeThrowForClosedDatabase(database)
     try maybeThrowForFinalizedStatement(statement)
 
+    // The statement with parameter bindings is stateful,
+    // we have to guard with a critical section for thread safety.
+    statement.lock.lock()
+    defer { statement.lock.unlock() }
+
```
Comment (alanjhughes) [inline packages/expo-sqlite/ios/SQLiteModule.swift:378]:
```suggestion
 statement.semaphore.wait()
  defer { 
      statement.semaphore.signal() 
  }
```
There can be issues with thread safety with `NSLock` but it's up to you.

**Review by alanjhughes — APPROVED** [review]

**Comment by Kudo** [comment]
### Merge activity

* **May 7, 12:54 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/36674).
