### PR TITLE
[ios][core] Fix view managers not deallocating

### LINKED ISSUE #33655: [Expo Module] lifecycle method onDestroy is never invoked on iOS
### Minimal reproducible example

https://github.com/DarvilCZE/expo-monorepo-sandbox

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

## Issue Description

We are implementing an expo module that integrates a 3rd party iOS module that connects via Bluetooth to hardware. We need to disconnect from the hardware whenever the JS thread is terminated. In the bare react native module, we would use the `invalidate` method to do such a cleanup. Based on the [documentation](https://docs.expo.dev/modules/module-api/#ondestroy) we believe the `onDestroy` callback in the module definition should be used for such a thing.

On Android, everything works fine. When we run the app we can see the callback `onCreate` is invoked based on the log that we have inside. Also, when we reload the JS we can see that `onDestroy` is called as well. The problem is on iOS, we can see `onCreate` being called, but we **never** see the `onDestroy` being invoked when we reload the JS. We would expect to see our log `TestPackageModule destroyed` when `onDestroy` is called also on iOS when we reload the JS.

The behavior is the same for the new and old architecture.

## Reproducible Example

It is a simple monorepo with one app (`apps/example`), which was created with command `npx create-expo-app`, and one package (`packages/test-package`), which was created with the command `npx create-expo-module`. We only bumped the versions and added the lifecycle callbacks to the module definition.

To see that the `test-package` is properly linked open `package` tab in the example app, press the buttons and check debugger to see JS logs.

### Environment

```text
expo-env-info 1.2.1 environment info:
  System:
    OS: macOS 15.1.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /Users/davidlang/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    Android SDK:
      API Levels: 29, 30, 31, 32, 33, 34, 35
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0, 35.0.0
      System Images: android-28 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-34 | Google TV ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
  IDEs:
    Android Studio: 2024.1 AI-241.18034.62.2412.12266719
    Xcode: 16.1/16B40 - /usr/bin/xcodebuild
  npmGlobalPackages:
    eas-cli: 13.4.2
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #33655

# How
Attempts to fix two memory leaks
- The `MainValueConverter` holds a strong reference to the `AppContext` causing it not to deallocate
- The `ModuleHolder` will not deallocate when the definition exports a view because the `ViewModuleWrapper` strongly references it.

# Test Plan
Bare-expo. The lifecycle methods `OnDestroy`, and `OnAppContextDestroys` are called correctly when the app is reloaded.

### CODE REVIEW

File: packages/expo-modules-core/ios/Core/Views/ViewModuleWrapper.swift [hunk 1]
```diff
@@ -20,7 +20,7 @@ public final class ViewModuleWrapper: RCTViewManager, DynamicModuleWrapperProtoc
    A reference to the module holder that stores the module definition.
    Enforced unwrapping is required since it can be set right after the object is initialized.
```
Comment (Kudo) [inline packages/expo-modules-core/ios/Core/Views/ViewModuleWrapper.swift:21]:
```suggestion
```

also the variable called `wrappedModuleHolder` doesn't sound precise afterall. maybe we could refactor as `moduleHolder` as now it can be nil.

File: packages/expo-modules-core/ios/Core/Views/ViewModuleWrapper.swift [hunk 2]
```diff
@@ -57,7 +57,8 @@ public final class ViewModuleWrapper: RCTViewManager, DynamicModuleWrapperProtoc
    */
   @objc
   public func name() -> String {
-    return wrappedModuleHolder.name
+    // swiftlint:disable:next force_unwrapping
+    return wrappedModuleHolder!.name
```
Comment (Kudo) [inline packages/expo-modules-core/ios/Core/Views/ViewModuleWrapper.swift:61]:
```suggestion
    guard let moduleHolder = wrappedModuleHolder else {
      fatalError("ModuleHolder is lost")
    }
    return moduleHolder.name
```

maybe we should better remove the force unwrap. feel free to fine tune the error message

**Review by Kudo — APPROVED** [review]
question: should we update the code to handle nil wrappedModuleHolder case?

https://github.com/expo/expo/blob/d494a8500d9cab8baca24ddc5a428155bcf1a701/packages/expo-modules-core/ios/Core/Views/ComponentData.swift#L21

**Review by tsapeta — APPROVED** [review]

**Comment by alanjhughes** [comment]
> question: should we update the code to handle nil wrappedModuleHolder case?
> 
> https://github.com/expo/expo/blob/d494a8500d9cab8baca24ddc5a428155bcf1a701/packages/expo-modules-core/ios/Core/Views/ComponentData.swift#L21

I don't think so. `ComponentData` takes a reference to an optional `ModuleHolder` so that's fine.

File: packages/expo-modules-core/ios/Core/Views/ViewModuleWrapper.swift (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-modules-core/ios/Core/Views/ViewModuleWrapper.swift:21]: Yes, renaming it makes sense. In practice, it was never nil before so it should never be nil now. We're just changing how it's stored so arc won't increase the reference count.

**Review by Kudo — APPROVED** [review]
