### PR TITLE
[expo-notifications] Register emitter as center delegate's delegate only once JS subscribes to it

### LINKED ISSUE #9866: [unimodules][android][notifications] Event listener can miss `emit()` calls made soon after app launch
### Summary of Issue 

If you call `Notifications.addResponseReceivedListener` in `useEffect` for example, the listener will not be triggered when opening an app from a completely killed state via a notification. This can also be demonstrated by adding a timeout to `componentDidMount` [as shown here](https://github.com/expo/expo/issues/7787#issuecomment-612072912). Without 1 second timeout- events come through; with 1 second timeout- event's do not come through.

I should note that [the emit method](https://github.com/expo/expo/blob/master/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/emitting/NotificationsEmitter.java#L72) **is** getting called in this case.

### Reproducible Demo

https://snack.expo.io/@charliecruzan/push-notifications  
 
### Steps to Reproduce

Need to run the app as a published experience or standalone app (or bare debug build) to see the behavior. Press "show notification" and kill the app, tap the notification, observe that response listener isn't triggered.

### Workaround

The workaround (and possibly long-term solution) is to add the listener outside of any component, then it works as expected (presumably bc of how much sooner it's getting called?). I changed the docs to suggest this so fewer people run into this issue

### LINKED ISSUE #11343: addNotificationResponseReceivedListener and useLastNotificationResponse not triggered for killed iOS apps SDK 40
🐛 Bug Report

After updating to SDK 40 expo-notifications does not trigger addNotificationResponseReceivedListener after app was killed on iOS. This last upgrade did fix the issue on Android, but now I am having that same problem on iOS.

SDK 40
Standalone App (I built a new bundle after updating to SDK 40)
Only on iOS.

Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      npm: 6.14.9 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

Reproducible Demo

```
class HandlePushNotifications extends Component {
    componentDidMount() {
        this.onResponseReceivedListener = Notifications.addNotificationResponseReceivedListener(
            this.handlePush <-- This is never triggered when the app was killed on iOS.
        );
    }
}
```

Steps to Reproduce
Kill the app, Send a push notification, tap on that push (it opens the app)

Expected Behavior vs Actual Behavior
Expected Behavior: Notifications.addNotificationResponseReceivedListener triggers since the user interacted with the push.
Actual Behavior: The triggering of Notifications.addNotificationResponseReceivedListener never occurs.

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes a bug introduced in https://github.com/expo/expo/pull/10883 which causes initial notification responses to get lost in standalone iOS apps.

Along with #11378 I believe it fixes #11343 and may also finally fix #9866.

# How

Using native breakpoints I've noticed `EXNotificationCenterDelegate`'s `addDelegate:` is called more times than I would expect it to.

It turned out before `EXScopedNotificationsEmitter` was subscribing to `EXNotificationCenterDelegate` (it would then receive pending notification response) an unscoped `EXNotificationsEmitter` was subscribing and consuming pending responses. Since unscoped emitter wasn't being used and exposed to the app later, it consumed the response into the void.

Most probably unimodules have a bug where instances of overridden modules are still kept in memory (since `setModuleRegistry:` is called on them). Fixing this bug is out of the scope of this pull request.

These changes are based on how it was implemented before https://github.com/expo/expo/pull/10883/commits/dfda625f3e7c51fa6c766b60c26dbf09c2987523. I can't see any reason why `EXNotificationsEmitter` would need to register for notifications as soon as module registry is ready, so let's roll back to what we know worked well.

# Test Plan

I have verified in an ExpoKit workspace that when the app is opened from a notification, the notification response is delivered to `useLastNotificationResponse`:

https://www.loom.com/share/586a906c538f47f0940b2cc83582fb29

### CODE REVIEW

File: packages/expo-notifications/ios/EXNotifications/Notifications/Emitter/EXNotificationsEmitter.m [hunk 1]
```diff
@@ -33,9 +34,7 @@ @implementation EXNotificationsEmitter
 - (void)setModuleRegistry:(UMModuleRegistry *)moduleRegistry
 {
   _eventEmitter = [moduleRegistry getModuleImplementingProtocol:@protocol(UMEventEmitterService)];
-
   _notificationCenterDelegate = [moduleRegistry getSingletonModuleForName:@"NotificationCenterDelegate"];
-  [_notificationCenterDelegate addDelegate:self];
```
Comment (cruzach) [inline packages/expo-notifications/ios/EXNotifications/Notifications/Emitter/EXNotificationsEmitter.m:38]: Only reason I can think of needing this is if responses could somehow get swallowed between now and when we add a listener...but that is what `EXNotificationCenterDelegate`'s `_pendingNotificationResponses` is for! 

so yeah, I can't think of any reason we would need this either 👍

**Review by cruzach — APPROVED** [review]
thanks for the video 🙏 this lgtm!

I don't believe there would be any difference if the notification _comes in_ while the app is closed, but it might be worth double-checking? I.e. you schedule a notification for 5 seconds from now, kill the app, notification arrives, tap on it to launch app, do we still get the response? Again, I don't think it will make a difference but just me being extra-cautious

Approved but we should backport to sdk 40 versioned code as well
