### PR TITLE
[av][android] Fix events not working

### LINKED ISSUE #28698: [expo-av] SDK 51: Sound.setOnPlaybackStatusUpdate() callback not called at regular inteval
### Minimal reproducible example

https://github.com/cyanChill/expo-av-setOnPlaybackStatusUpdate

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

In SDK 51 with Android, the callback passed to `Sound.setOnPlaybackStatusUpdate()` is never called at a regular interval or when the track finishes playing, unlike with SDK 50. It's only called when we manually call a function on the playback object. The same behavior was seen with Expo Go and in a Development Build for the SDK 51 version.
- Doc Reference: https://docs.expo.dev/versions/latest/sdk/audio/#setonplaybackstatusupdateonplaybackstatusupdate

I made snacks for both [SDK 50](https://snack.expo.dev/@missingcore/setonplaybackstatusupdate-sdk_50?platform=android) & [SDK 51](https://snack.expo.dev/@missingcore/setonplaybackstatusupdate-sdk_51?platform=android). In our example, once the track is loaded, when we click "Play Track", we expect the time next to "Current Position" to increment. The time doesn't change unless we hit the "Pause Track" button.
- Weirdly enough, for SDK 51 on "Web", the callback is called in a regular interval, which is the expected behavior.

~~This might be similar to an old issue seen with iOS: https://github.com/expo/expo/issues/19022.~~
- Seems to work on iOS via the Snack link.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.0 => 51.0.0
      expo-router: ~3.5.10 => 3.5.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.11 => 0.19.11
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

### PR DESCRIPTION
**Pull request by behenate**
# Why

This PR fixes a regression introduced in SDK 51, caused by the fact that events sent using the wrong event emitter are not accepted.

Fixes https://github.com/expo/expo/issues/28698

# How

Used a solution similar to `ExpoBattery`, where the `sendEvent` function from the module is passed to the calling class instance. In this case I used additional wrapper interface, because `AVModule` is written in kotlin and `AVManager` is in java.

# Test Plan

Tested in BareExpo in Android 14 emulator.

### CODE REVIEW

File: packages/expo-av/android/src/main/java/expo/modules/av/AVManagerInterface.java [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 import android.content.Context;
+import android.os.Bundle;
 
 import expo.modules.core.ModuleRegistry;
 import expo.modules.core.Promise;
 import expo.modules.core.arguments.ReadableArguments;
 import expo.modules.av.video.VideoView;
 import expo.modules.interfaces.permissions.PermissionsResponseListener;
 
+interface EmitEventWrapper {
```
Comment (lukmccall) [inline packages/expo-av/android/src/main/java/expo/modules/av/AVManagerInterface.java:12]:
```suggestion
@FunctionalInterface
interface EmitEventWrapper {
```

**Review by lukmccall — APPROVED** [review]
