### PR TITLE
[linking] prevent crash in bare workflow

### LINKED ISSUE #10095: In Bare, Linking crashes with null is not an object (evaluating 'manifest.hostUri')
### Summary of Issue

In Bare (sdk38), Linking crashes with `null is not an object (evaluating 'manifest.hostUri')`

IMG_65A1588D585A-1

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.26.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 3.10.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.9 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.26.2
```

### Reproducible Demo

Not easy as it's a bare project.
Similar issue #7807
 
### Steps to Reproduce

Open the link, the app is launched, linking is handled by getInitialURL or addEventListener then parsing crashes

```
import * as Linking from 'expo-linking';
/../
let { path, queryParams } = Linking.parse(url);
```
_url is correct : scheme://join?memberId=xxx_

### Expected Behavior vs Actual Behavior

Previous version with sdk35 did not crash.
As mentioned in expo-notification README, 
`"Defaults to [`Constants.manifest.id`](https://docs.expo.io/versions/latest/sdk/constants/#constantsmanifest) exposed by `expo-constants`. You may need to define it in bare workflow, where `expo-constants` doesn't expose the manifest."`

https://github.com/expo/expo/blob/master/packages/expo-linking/src/Linking.ts imports expo-constants

```
import Constants from 'expo-constants';
/.../
const { manifest } = Constants;
/.../
function getHostUri(): string {
  if (!manifest.hostUri && !usesCustomScheme()) {                                  <<<<<<<<<<<<<< CRASH HERE
    // we're probably not using up-to-date xdl, so just fake it for now
    // we have to remove the /--/ on the end since this will be inserted again later
    return removeScheme(Constants.linkingUri).replace(/\/--($|\/.*$)/, '');
  }
  return manifest.hostUri;
}
```
So that's why it is broken in bare workflow ....

How can we urgently solve this ?

### Quickfix until solved

I just need path and queryParams, so I replaced Linking.parse(url) with

```
export function fixLinkingParse(url) {
  // url is this kind for me : scheme://path?queryParams
  const parsed = URL(url, /* parseQueryString */ true);
  for (const param in parsed.query) {
    parsed.query[param] = decodeURIComponent(parsed.query[param]);
  }
  const queryParams = parsed.query;
  const path = parsed.host || null;
  return {
    path,
    queryParams
  };
}
```

### PR DESCRIPTION
**Pull request by cruzach**
# Why

fixes https://github.com/expo/expo/issues/10095 and https://github.com/expo/expo/issues/8973 

Relying on keys inside of `Constants.manifest` will crash in the bare workflow. (I looked at the other cases [listed here](https://github.com/expo/expo/issues/7721#issuecomment-619624914) and didn't see any that would cause crashes)

# How

fallback to `Updates.manifest`, which is `{}` if it's a bare build that hasn't received an OTA update yet, but that still won't crash

### CODE REVIEW

**Review by brentvatne — CHANGES_REQUESTED** [review]
i'm not sure we want to require users to have expo-updates installed in order to use this package. we have some questions we need to answer about expo-constants, expo-updates, and the manifest object. for example, manifest isn't available in bare apps using expo-updates on the first build, it's only available once an update has been downloaded. should we change that? probably. this behavior would not work well in a world where a managed app uses the same build process as a bare app, as folks depend on accessing the manifest in managed workflow fairly often.

so, i think what we should do here for now is make sure that it doesn't crash. so, something like:

```js
const manifest = Constants.manifest ?? {};
```

then verify that every time we access a property on manifest in expo-linking that we handle the case where it is undefined

File: packages/expo-linking/src/Linking.ts [hunk 1]
```diff
@@ -24,6 +23,10 @@ function usesCustomScheme(): boolean {
 
 function getHostUri(): string {
   if (!manifest.hostUri && !usesCustomScheme()) {
+    if (!Constants.linkingUri) {
+      // this is a bare workflow app
+      return '';
```
Comment (brentvatne) [inline packages/expo-linking/src/Linking.ts:28]: i would change the `getHostUri` function to look like this, for clarity:

```js
function getHostUri(): string | null {
  if (manifest.hostUri) {
    return manifest.hostUri;
  } else if (!manifest.hostUri && !usesCustomScheme()) {
    // we're probably not using up-to-date xdl, so just fake it for now
    // we have to remove the /--/ on the end since this will be inserted again later
    return removeScheme(Constants.linkingUri).replace(/\/--($|\/.*$)/, '');
  } else {
    return null;
  }
}
```

it looks like the rest of the code already expects `getHostUri()` to return `string | null` anyhow, eg: in `parse`:

```
const hostUri = getHostUri() || '';
```

**Comment by Ciberusps** [comment]
merge?

**Review by brentvatne — APPROVED** [review]
