### PR TITLE
[video][android] turn off auto-PiP on video unmount

### LINKED ISSUE #30937: [expo-video] [android] startsPictureInPictureAutomatically keeps Picture-in-picture after videoview is unmounted
### Minimal reproducible example

https://github.com/erixtekila/expovideo/

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Hi,

On android supported versions, PiP automatic feature misbehave.
If a `VideoView` has been used, then unmounted, the whole app will be displayed in PiP later, since there is no more video stream attached.

Steps to reproduce the problem :
1. Go to the so-called `video` page.
2. Play content
3. Put the app in background. The video is displayed correctly in PiP.
4. Put the app back in forground.
5. Navigate back to the `index` page.
6. Put the app once again in background. The `index` page appears incorrectly in PiP

Here is the result…

Capture d’écran 2024-08-10 à 16 37 24

 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0
        System Images: android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.26 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 10.2.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by fobos531**
# Why

Fixes https://github.com/expo/expo/issues/30937

# How

In `unregisterVideoView`, if the `videoViews` is empty after unregistering the videoView, we can assume that the user left the screen containing the video (video was unmounted). Therefore, we need to explicitly set autoEnterPiP to false to prevent the activity going into PiP when the user tries to background it.

# Test Plan

Test case from the linked issue:

https://github.com/user-attachments/assets/61a810a5-5644-4944-a433-b18d7704f297

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-video/android/src/main/java/expo/modules/video/VideoManager.kt [hunk 1]
```diff
@@ -82,4 +103,25 @@ object VideoManager {
       }
     }
   }
+
+  // We can't check if AndroidManifest.xml is configured properly, so we have to handle the exceptions ourselves to prevent crashes
+  fun runWithPiPMisconfigurationSoftHandling(shouldThrow: Boolean = false, ignore: Boolean = false, block: () -> Any?) {
```
Comment (fobos531) [inline packages/expo-video/android/src/main/java/expo/modules/video/VideoManager.kt:108]: moved these two functions from the `VideoView` so that they are accessible there and because of DRY - let me know if this is not a good choice.

**Review by behenate — COMMENTED** [review]
Thanks for the contribution! I somehow missed that issue. I'd suggest a slightly different approach. 

Lets create a helper function and put it somewhere near the bottom just above the `companion object` in `VideoView.kt`:
```kotlin
  private fun applyAutoEnterPiP(autoEnterPiP: Boolean) {
    if (Build.VERSION.SDK_INT >= 31 && isPictureInPictureSupported(currentActivity)) {
      runWithPiPMisconfigurationSoftHandling {
        currentActivity.setPictureInPictureParams(PictureInPictureParams.Builder().setAutoEnterEnabled(autoEnterPiP).build())
      }
    }
  }
```

Then we can replace
https://github.com/expo/expo/blob/38ac96ffe39ce83b39cc5421009c4990baa90274/packages/expo-video/android/src/main/java/expo/modules/video/VideoView.kt#L88-L97

with

```kotlin
  var autoEnterPiP: Boolean by IgnoreSameSet(false) {new, _ ->
    applyAutoEnterPiP(new)
  }
```

Now in the `onAttachedToWindow` and `onDetachedFromWindow` we can use it to prevent auto entering PiP when unnecessary:
```kotlin
override fun onAttachedToWindow() {
  super.onAttachedToWindow()
  (currentActivity as? FragmentActivity)?.let {
    val fragment = PictureInPictureHelperFragment(this)
    pictureInPictureHelperTag = fragment.id
    it.supportFragmentManager.beginTransaction()
      .add(fragment, fragment.id)
      .commitAllowingStateLoss()
  }
  applyAutoEnterPiP(autoEnterPiP);
}

override fun onDetachedFromWindow() {
  super.onDetachedFromWindow()
  (currentActivity as? FragmentActivity)?.let {
    val fragment = it.supportFragmentManager.findFragmentByTag(pictureInPictureHelperTag ?: "")
      ?: return
    it.supportFragmentManager.beginTransaction()
      .remove(fragment)
      .commitAllowingStateLoss()
  }
  applyAutoEnterPiP(false);
}
 ```
 
 Seems to fix it in `bare-expo`with a lot less changes. Let me know if you can think of any situation in which it would break PiP

**Comment by fobos531** [comment]
Hey @behenate 

Yup, that does indeed work great with a lot less code! I have nothing else to add on my end.

> Let me know if you can think of any situation in which it would break PiP

For this specific PR, I don't think so, but there is a related issue https://github.com/expo/expo/issues/31870

As I understand it, to fix it, we need to be able to properly distinguish between when user backgrounded the app vs. when they just entered PiP. For that, we need support for `OnUserLeaveHint` in `expo-modules-core`. I found that your related PR was merged into `react-native` core. Is it now possible to integrate this into e-m-c?

**Comment by behenate** [comment]
@fobos531 I'm planning to do some work with the `onUserLeaveHint` PR this week to add support for auto PiP in lower versions of Android. I'll try to fix related issues then (such as video pausing when it auto enters PiP)

**Review by behenate — APPROVED** [review]

**Comment by behenate** [comment]
@fobos531 A little update for `onUserLeaveHint` turns out it won't work for this, even though I really thought it would. It turns out that `onUserLeaveHint` isn't called when `PictureInPictureParams.Builder().setAutoEnterEnabled(true).build()` is used, which we have to use for smooth transitions.

It will still allow us to have `startsPictureInPictureAutomatically` on older Android SDKs.
