### PR TITLE
[expo-av] Fix instability issues when changing source and useNativeControls

### LINKED ISSUE #7137: [expo-av] EXVideoView - Modifications to the layout engine must not be performed from a background thread
## 🐛 Bug Report

We are getting crash reports that are related to the `EXVideoView`. It seems to happen to users running iOS 13.3 and 13.3.1.

**Error**
```
-[EXVideoView _updateNativeResizeMode]
EXVideoView.m, line 552
SIGABRT: Modifications to the layout engine must not be performed from
a background thread after it has been accessed from the main thread.
```

**Backtrace**
image

**Packages**
"react-native": "0.61.5"
"expo-av": "8.0.0",

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Fixes #7137. Code that changes the UI is not always executed in the main UI thread, causing immediate or delayed crashes in the EXVideoView. This was reproducible by changing the source icw setting `useNativeControls` to true, however it is not limited to this situation and may occur on other scenarios as well.

# How

- Update ViewController & Layer code to always be executed in main UI thread
- Fix external call to `setUseNativeControls` not checking whether player-load is complete
- Add test-suite tests  to verify stability when changing sources & useNativeControls
- Add 'Change source` button to NCL to test & verify changing source ability

*Change source button in NCL*

image

# Test Plan

- Validated behavior and debugged using NCL changes
- Newly added test-suite tests succeed (they will fail with the exact same error as described in #7137 without the fixes)
- All existing tests succeed 

image

### CODE REVIEW

File: packages/expo-av/ios/EXAV/Video/EXVideoView.m [hunk 1]
```diff
@@ -129,15 +139,19 @@ - (void)_removePlayer
...
-    [_data setStatusUpdateCallback:nil];
-    [_exAV demoteAudioSessionIfPossible];
-    [self _removeFullscreenPlayerViewController];
-    [self _removePlayerLayer];
-    [self _removePlayerViewController];
-    _data = nil;
-  }
+  // Any ViewController/layer updates need to be
+  // executed on the main UI thread.
+  __weak EXVideoView *weakSelf = self;
```
Comment (bbarthec) [inline packages/expo-av/ios/EXAV/Video/EXVideoView.m:144]: FYI, we have macros for handling those nasty `__weak self` references.
Instead of `__weak VariableType *var = variable` use `UM_WEAKIFY(variable)`
and instead of `__strong ...` use `UM_STRONGIFY` or even `UM_ENSURE_STRONGIFY` (the latter comes with auto-checking for nullability).

File: packages/expo-av/ios/EXAV/Video/EXVideoView.m [hunk 2]
```diff
@@ -129,15 +139,19 @@ - (void)_removePlayer
...
+  void (^block)(void) = ^ {
+    __strong EXVideoView *strongSelf = weakSelf;
+    if (strongSelf) {
+      [strongSelf _removeFullscreenPlayerViewController];
+      [strongSelf _removePlayerLayer];
+      [strongSelf _removePlayerViewController];
+    }
+  };
```
Comment (bbarthec) [inline packages/expo-av/ios/EXAV/Video/EXVideoView.m:152]:
```suggestion
  UM_WEAKIFY(self);
  void (^block)(void) = ^ {
    UM_ENSURE_STRONGIFY(self);
    [self _removeFullscreenPlayerViewController];
    [self _removePlayerLayer];
    [self _removePlayerViewController];
  };
```

Comment (IjzerenHein) [reply packages/expo-av/ios/EXAV/Video/EXVideoView.m:152]: Good one, thanks for the reminder! I'll create a PR to update this globally for expo-av 👍

Comment (IjzerenHein) [reply packages/expo-av/ios/EXAV/Video/EXVideoView.m:152]: Created a PR for this 👍 
https://github.com/expo/expo/pull/9437
