### PR TITLE
[android][contacts] fixed saving contacts with photos

### LINKED ISSUE #34313: [Contacts] updateContactAsync is failing with "Caused by: java.lang.NullPointerException: decodeFile(...) must not be null"
### Minimal reproducible example

https://github.com/NorseGaud/expo-testing

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I'm doing the following:

```
        console.log('[updateDeviceContact::contact]', contact)
        await ExpoContacts.updateContactAsync({
          id: contact.id,
          [ExpoContacts.Fields.Name]: contact.name,
          [ExpoContacts.Fields.ContactType]: contact.contactType,
        })
```

This throws the following:

```
 LOG  [updateDeviceContact::contact] {"birthday": {"day": 25, "format": "gregorian", "month": 5, "year": 1956}, "contactType": "person", "firstName": "Dan", "id": "10", "image": {"uri": "content://com.android.contacts/contacts/10/photo"}, "imageAvailable": true, "lastName": "Park", "lookupKey": "340i10905b0a99d0af", "name": "Dan Park", "phoneNumbers": [{"id": "69", "isPrimary": 0, "label": "mobile", "number": "1 (234) 121-2313", "type": "2"}], "rawDates": [{"type": "birthday", "value": "1956-06-25"}]}
 ERROR  error updating contact:  Call to function 'ExpoContacts.updateContactAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: decodeFile(...) must not be null
```

### Environment

```text
❯ npx expo-env-info

  expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v21.7.3/bin/npm
      Watchman: 2024.11.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/opt/ruby/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 32, 33, 34, 35
        Build Tools: 26.0.3, 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-26 | Google APIs Intel x86_64 Atom, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.27 => 52.0.27 
      expo-router: ~4.0.17 => 4.0.17 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.6 => 0.76.6 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
❯ npx expo-doctor@latest                        
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by chrfalch**
# Why

On Android, when saving a contact that has a photo attached to it, the method will fail because we're not resolving the path to the photo correctly (not using a content resolver).

Note: This was previously solved in #32097 by [freeboub](https://github.com/freeboub) - thanks!

# How

- Added using contentResolver to get the correct inputstream to the photo in the Contact class
- Passed appContext from Contacts module to be able to use the contentResolver
- Added support for testing saving an image (ie. changing picture) on Android in BareExpo

Closes #ENG-14832

# Test Plan

Test in BareExpo:
- Open Contacts test screen
- Click contact image and select a new image (this will save the contact)
- Verify that the contact was successfully saved.

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by freeboub** [comment]
I pushed more or less the same fix here: https://github.com/expo/expo/pull/32097/files

**Comment by NorseGaud** [comment]
I can't get this to work. While it does get rid of the error, this doesn't actually impact the contacts on the device and make any changes

```
await ExpoContacts.updateContactAsync({
          id: contact.id,
          [ExpoContacts.Fields.Name]: contact.name,
          [ExpoContacts.Fields.ContactType]: contact.contactType,
          . . . changes here . . .
})
```

I then query using `getContactsAsync` and the contact still has the old settings.

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt [hunk 1]
```diff
@@ -521,7 +523,10 @@ class Contact(var contactId: String) {
     }
 
   private fun getThumbnailBitmap(photoUri: String?): Bitmap {
-    val path = Uri.parse(photoUri).path
-    return BitmapFactory.decodeFile(path)
+    val context = appContext.reactContext ?: throw Exceptions.AppContextLost()
```
Comment (lukmccall) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt:526]:
```suggestion
    val context = appContext.reactContext ?: throw Exceptions.ReactContextLost()
```

**Review by lukmccall — APPROVED** [review]
