### PR TITLE
fix(cli): avoid creating dev client urls containing `_` in protocol

### LINKED ISSUE #23440: expo run:android throw CommandError when starting android app with underscore in package name
### Summary

If the package name for android in app.config.js has underscore like this `com.example.with_underscore`
During expo run:android, it throws `CommandError: Couldn't open Android app with activity`

Probably caused by this, nodejs URL does not allow protocol with underscore
https://github.com/expo/expo/blob/3920dd813e62395a64a307ee8e16a0db615b32f1/packages/%40expo/cli/src/utils/url.ts#L38-L50

### What platform(s) does this occur on?

Android

### SDK Version

49

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 18.13.0 - /usr/bin/node
      npm: 9.2.0 - /usr/bin/npm
    npmPackages:
      expo: ^49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    Expo Workflow: bare

### Minimal reproducible example

Expo project with underscore android package name 
`com.example.with_underscore`

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #23440

Unfortunately, due to Node's limitation in URL, we can't use `_` in protocols. Even when we do fix it, we run into URL parsing issues in Expo Router (that's also using Node's URL). Instead, this change makes protocols containing `_` fully invalid as any dev client URL.

# How

- Prohibited dev client URLs with `_` characters in the protocol
- This will trigger the [`_resolveAlternativeLaunchUrl`](https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/start/platforms/android/AndroidPlatformManager.ts#L48-L53) on Android and create `com.example.some_package/.MainActivity` instead

# Test Plan

- `$ yarn create expo ./fix-23440 --template tabs@49`
- `$ cd ./fix-23440`
- Update `app.json` with `expo.android.package = "com.example.protocol_underscore"`
- `$ yarn expo run:android`
- Should fall back to `com.example.protocol_underscore/.MainActivity` URL and open the app properly

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/start/server/__tests__/UrlCreator-test.ts [hunk 1]
```diff
@@ -47,6 +47,11 @@ describe('constructDevClientUrl', () => {
     expect(createDefaultCreator().constructDevClientUrl({ scheme: 'http' })).toEqual(null);
     expect(createDefaultCreator().constructDevClientUrl({ scheme: 'https' })).toEqual(null);
   });
+  it(`returns null when protocol contains "_" characters`, () => {
+    expect(
+      createDefaultCreator().constructDevClientUrl({ scheme: 'dev.expo.invalid_node_protocol' })
```
Comment (EvanBacon) [inline packages/@expo/cli/src/start/server/__tests__/UrlCreator-test.ts:52]: Can we confirm that the error message the user will get will **not** look something like "no scheme is defined"?

Comment (byCedric) [reply packages/@expo/cli/src/start/server/__tests__/UrlCreator-test.ts:52]: The user won't get an error message when using `_`, it will instead just fallback to the Android "alternative" URL, which is `<identifier>/.MainActivity`

**Review by EvanBacon — APPROVED** [review]
