### PR TITLE
[network] fix: ip address not retrieved if using cellular data

### LINKED ISSUE #7351: [expo-network] Unknown Host Exception thrown on Android on Cellular Data
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.22.1 - /usr/local/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.9.16
      @types/react-native: ^0.57.60 => 0.57.65
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.13.1

I am targeting iOS and Android as a Standalone App.

### Steps to Reproduce

1. Use an Android Device with cellular data not wifi
2. do `const ip = await Network.getIpAddressAsync();`

### Expected Behavior

I get the current IP Address of the device and the code continues executing.

### Actual Behavior

My Application gets an `Error: Unknown Host Exception`. This only happens when the User of the App is on Cellular Data and not on Wifi. 

### Reproducible Demo

https://expo.io/@saifadin/host-exception

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/7351

# How

If we aren't connected to wifi, the IP address returned on iOS is currently 0.0.0.0, and on android we would throw an error. At first I changed this to just return 0.0.0.0 so that the behavior would be consistent across both, but it makes sense to catch that case and fallback to getting the IP address from ipifiy.org (which is what we do in the web implementation already).

Related question- do we just want to rely on ipify for IP address on android & ios in the first place?

# Test Plan

Tested manually on android, IP address is returned both on data and wifi

### CODE REVIEW

**Review by ide — CHANGES_REQUESTED** [review]
This doesn't look like the correct fix. `InetAddress.getByAddress(new byte[] {0, 0, 0, 0})` runs fine. The issue seems to be that `BigInteger.valueOf(0).toByteArray()` produces an array that does not have four elements exactly.

**Comment by cruzach** [comment]
`getByAddress` will throw if the input isn't an array of length 4 or 16, so I changed it to just catch that error. Also removed the `ipify` fallback from native (it's still used on web)

File: packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.java [hunk 1]
```diff
@@ -120,6 +120,19 @@ private NetworkStateType getNetworkCapabilities(NetworkCapabilities nc) {
...
 
+  private String rawIpToString(Integer ip) {
+    // Convert little-endian to big-endian if needed
+    if (ByteOrder.nativeOrder().equals(ByteOrder.LITTLE_ENDIAN)) {
+      ip = Integer.reverseBytes(ip);
+    }
+    byte[] ipByteArray = BigInteger.valueOf(ip).toByteArray();
+    try {
+      return InetAddress.getByAddress(ipByteArray).getHostAddress();
+    } catch (UnknownHostException e) {
```
Comment (ide) [inline packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.java:131]: This exception is thrown if the byte array is of the wrong length. While I think it's good to have this `catch` clause if we document this behavior in our API contract, this also means that IP addresses that start with a zero but aren't "0.0.0.0" (uncommon but valid within a network) will all get forced into this code path.

The byte array needs to be front-padded with zero bytes so that it always is four bytes long.

Comment (cruzach) [reply packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.java:131]: hm, I don't understand- why would an ip address that just starts with zero result in an array of the wrong length? 

I tried triggered the error by providing the `rawIpToString` method with the integer `16885760`, and got back `0.168.1.1` (as expected).

Comment (ide) [reply packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.java:131]: If it starts with a zero the integer will be too small to produce a four byte array. Try it.

Comment (cruzach) [reply packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.java:131]: ahh I see now, thanks for pointing that out

**Review by ide — APPROVED** [review]
Make sure to test this with `0` (and maybe `1`) to make sure the padding logic works and that we don't take the try-catch code path.
