### PR TITLE
[expo-localization][android] fix convert BCP-47 locales to Android resource qualifiers

### LINKED ISSUE #40205: [expo-localization] Unable to use locale 'en-US' on Android
### Minimal reproducible example

https://github.com/AndreasJJ/expo-localization-repro

### Steps to reproduce

1. Clone repo
2. Run `expo run:android`

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.11.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.2 - /opt/homebrew/bin/npm
      Watchman: 2025.04.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2024.3 AI-243.22562.218.2431.13114758
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.12 => 54.0.12 
      expo-router: ~6.0.10 => 6.0.10 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
      react-native-web: ~0.21.0 => 0.21.1 
    npmGlobalPackages:
      eas-cli: 16.1.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by kosmydel**
# Why

Fixes https://github.com/expo/expo/issues/40205

# How

- Added `convertBcp47ToAndroidLocale()` helper to convert BCP-47 locales (e.g., `"en-US"`) to Android format (e.g., `"en-rUS"`)
- Updated `withAppBuildGradle` to apply conversion before writing to `resourceConfigurations`
- https://developer.android.com/guide/topics/resources/app-languages
- https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources

# Test Plan

1. Added unit tests in `plugin/__tests__/withExpoLocalization-test.ts`.
2. Manual testing:
- Create an app with `supportedLocales: ["en-US", "nb-NO", "fr"]`
- Run `npx expo prebuild -p android`
- Verify `android/app/build.gradle` contains `resourceConfigurations += ["en-rUS", "nb-rNO", "fr"]`
- Run Android build to confirm no "invalid config" errors

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-localization/plugin/__tests__/withExpoLocalization-test.ts [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    expect(convertBcp47ToAndroidLocale('pt-rBR')).toBe('pt-rBR');
+    expect(convertBcp47ToAndroidLocale('zh-rCN')).toBe('zh-rCN');
+  });
+
+  it('should handle numeric region codes (UN M.49)', () => {
+    expect(convertBcp47ToAndroidLocale('es-419')).toBe('es-r419');
+  });
+
+  it('should handle edge cases with only script codes (no region)', () => {
+    // When there's only a script code and no region, should return just the language
```
Comment (cambecc) [inline packages/expo-localization/plugin/__tests__/withExpoLocalization-test.ts]: The script cannot be dropped because it can be used to differentiate between locale resources. `zh-Hans` vs `zh-Hant` to select between Simplified and Traditional Chinese strings is a prominent example.

File: packages/expo-localization/plugin/src/withExpoLocalization.ts [hunk 2]
```diff
@@ -23,6 +23,49 @@ type ConfigPluginProps = {
       };
 };
 
+/**
+ * Converts BCP-47 locale strings (e.g., "en-US") to Android resource qualifiers (e.g., "en-rUS").
+ * This prevents "invalid config" errors during :processDebugResources.
+ */
+export function convertBcp47ToAndroidLocale(locale: string): string {
```
Comment (cambecc) [inline packages/expo-localization/plugin/src/withExpoLocalization.ts]: Why not follow the [official guidance](https://developer.android.com/guide/topics/resources/providing-resources) for formatting locale qualifiers?

> Android 7.0 (API level 24) introduced support for [BCP 47 language tags](https://tools.ietf.org/html/bcp47), which you can use to qualify language- and region-specific resources. A language tag is composed from a sequence of one or more subtags, each of which refines or narrows the range of language identified by the overall tag. For more information about language tags, see [Tags for Identifying Languages](https://tools.ietf.org/html/rfc5646).
>
> To use a BCP 47 language tag, concatenate b+ and a two-letter [ISO 639-1](http://www.loc.gov/standards/iso639-2/php/code_list.php) language code, optionally followed by additional subtags separated by +.

Couldn't this function just be the following?:
```javascript
// If already in Android format (contains '-r'), return as-is
if (locale.includes('-r')) {
  return locale;
}
return `b+${locale.replace("-", "+")}`;
```

Comment (kosmydel) [reply packages/expo-localization/plugin/src/withExpoLocalization.ts]: You are right. Thanks for the feedback!

File: packages/expo-localization/plugin/__tests__/withExpoLocalization-test.ts [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+
+  it('should convert language-region codes to BCP-47 format', () => {
+    expect(convertLocaleToBcp47('en-US')).toBe('b+en+US');
+    expect(convertLocaleToBcp47('en-GB')).toBe('b+en+GB');
+    expect(convertLocaleToBcp47('zh-Hans')).toBe('b+zh+Hans');
+    expect(convertLocaleToBcp47('zh-Hant')).toBe('b+zh+Hant');
+    expect(convertLocaleToBcp47('es-419')).toBe('b+es+419');
+    expect(convertLocaleToBcp47('zh-Hant-TW')).toBe('b+zh+Hant+TW');
+  });
+});
```
Comment (cambecc) [inline packages/expo-localization/plugin/__tests__/withExpoLocalization-test.ts:21]: minor point: might be good to have a few tests for the "-r" case, like `en-rUS` and `fr-rFR`.

Comment (kosmydel) [reply packages/expo-localization/plugin/__tests__/withExpoLocalization-test.ts:21]: Thank you, I've added it

File: packages/expo-localization/plugin/src/withExpoLocalization.ts [hunk 4]
```diff
@@ -106,10 +117,11 @@ function withExpoLocalizationAndroid(config: ExpoConfig, data: ConfigPluginProps
     });
     config = withAppBuildGradle(config, (config) => {
       if (config.modResults.language === 'groovy') {
+        const bcp47Locales = supportedLocales.map((locale) => convertLocaleToBcp47(locale));
         config.modResults.contents = AndroidConfig.CodeMod.appendContentsInsideDeclarationBlock(
           config.modResults.contents,
           'defaultConfig',
-          `    resourceConfigurations += [${supportedLocales.map((lang) => `"${lang}"`).join(', ')}]\n    `
+          `    resourceConfigurations += [${bcp47Locales.map((lang) => `"${lang}"`).join(', ')}]\n    `
```
Comment (cambecc) [inline packages/expo-localization/plugin/src/withExpoLocalization.ts]: Minor point on naming:the `resourceConfigurations` field is an array of resource qualifiers

File: packages/expo-localization/plugin/src/withExpoLocalization.ts [hunk 5]
```diff
@@ -23,6 +23,17 @@ type ConfigPluginProps = {
       };
 };
 
+/**
+ * Converts locale strings to BCP-47 format.
+ */
+export function convertLocaleToBcp47(locale: string): string {
```
Comment (cambecc) [inline packages/expo-localization/plugin/src/withExpoLocalization.ts]: Perhaps a better name for `convertLocaleToBcp47` would be `convertBcp47ToResourceQualifier` because this function converts BCP 47 tags to that special "b+..." resource qualifier format.

File: packages/expo-localization/plugin/src/withExpoLocalization.ts [hunk 6]
```diff
@@ -23,6 +23,17 @@ type ConfigPluginProps = {
...
+  // If already in Android format (contains '-r'), return as-is
+  if (locale.includes('-r')) {
```
Comment (cambecc) [inline packages/expo-localization/plugin/src/withExpoLocalization.ts]: By the way, I'm not sure the "-r" format will ever work, so maybe this check is not needed after all? The resource qualifier needs to match the resource directory name. But the directory names only ever use the "b+" format:
https://github.com/expo/expo/blob/2c7e51f18784d251026a7ef0cada55d5ccc0a6a4/packages/%40expo/config-plugins/src/android/Locales.ts#L39

Comment (cambecc) [reply packages/expo-localization/plugin/src/withExpoLocalization.ts]: Also, the docs suggest the locale values can only ever be BCP 47 tags: https://docs.expo.dev/guides/localization/#translating-app-metadata

Comment (kosmydel) [reply packages/expo-localization/plugin/src/withExpoLocalization.ts]: You are right. We don't accept the '-r' format in the configuration.

**Review by cambecc — COMMENTED** [review]
Looks good to me. Thanks for addressing this issue!

**Comment by cambecc** [comment]
What's needed to get this merged?

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]
