### PR TITLE
[android][screen-capture] Register Screen Capture callback earlier on Android 14

### LINKED ISSUE #31678: [expo-screen-capture] Can't detect screenshots on Android 14+
### Minimal reproducible example

https://github.com/david98/expo-screen-capture-bug

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Trying to detect a screenshot being taken by using code found in the documentation (https://docs.expo.dev/versions/latest/sdk/screen-capture/#example-functions):

```jsx
const hasPermissions = async () => {
    const { status } = await ScreenCapture.requestPermissionsAsync();
    return status === 'granted';
  };

  useEffect(() => {
    let subscription;

    const addListenerAsync = async () => {
      if (await hasPermissions()) {
        subscription = ScreenCapture.addScreenshotListener(() => {
          alert('Thanks for screenshotting my beautiful app 😊');
        });
      } else {
        console.error('Permissions needed to subscribe to screenshot events are missing!');
      }
    };
    addListenerAsync();

    return () => {
      subscription?.remove();
    };
  }, []);
```

works just fine on iOS and Android versions 13 and below. When running on Android 14+, it looks like the screenshot listener is never called. 

Also, I don't really know whether this is related or not, but we're getting a lot of unhandled exceptions for this module on Firebase:

```
 Fatal Exception: expo.modules.kotlin.exception.Exceptions$MissingActivity: The current activity is no longer available
       at expo.modules.screencapture.ScreenCaptureModule.getCurrentActivity(ScreenCaptureModule.kt:21)
       at expo.modules.screencapture.ScreenCaptureModule.access$getCurrentActivity(ScreenCaptureModule.kt:17)
       at expo.modules.screencapture.ScreenCaptureModule$definition$lambda$9$$inlined$OnDestroy$1.invoke(ModuleDefinitionBuilder.kt:147)
       at expo.modules.screencapture.ScreenCaptureModule$definition$lambda$9$$inlined$OnDestroy$1.invoke(ModuleDefinitionBuilder.kt:89)
       at expo.modules.kotlin.events.BasicEventListener.call(EventListener.kt:13)
       at expo.modules.kotlin.ModuleHolder.post(ModuleHolder.kt:98)
       at expo.modules.kotlin.ModuleRegistry.post(ModuleRegistry.kt:92)
       at expo.modules.kotlin.AppContext.onDestroy$expo_modules_core_release(AppContext.kt:333)
       at expo.modules.kotlin.KotlinInteropModuleRegistry.onDestroy(KotlinInteropModuleRegistry.kt:91)
       at expo.modules.adapters.react.NativeModulesProxy.invalidate(NativeModulesProxy.java:171)
       at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:109)
       at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:86)
       at com.facebook.react.bridge.CatalystInstanceImpl.lambda$destroy$2(CatalystInstanceImpl.java:366)
       at com.facebook.react.bridge.CatalystInstanceImpl.$r8$lambda$Oa3wfVCkSpv9UbaDKR-owki1vUU()
       at com.facebook.react.bridge.CatalystInstanceImpl$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:1012)
```

This seems to be happening only on Android 14:

Screenshot 2024-09-25 at 10 25 02

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 22.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.8.3 - /opt/homebrew/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 30, 31, 33, 33, 34, 34, 35
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google APIs ARM 64 v8a, android-35 | Google APIs Intel x86_64 Atom
    IDEs:
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.34 => 51.0.34
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by chrfalch**
# Why

On Android 14 we're using a new ScreenCapture detection API which requries an extra step in our module to register the callback. Due to a bug in bridgeless mode the activity wasn't ready when the module was created leading to a crash if we tried to register the callback here.

A fix was made in #28244 where the registration code was moved into the API methods for preventing/allowing screen capture. This was fine in the example in our tests since we use these methods in our test code - however in #31678 the example (from documentation) used did not automatically call the required API methods and so the callback was not registered and screen capture notifications was not sent on Android 14.

closes #31678

# How

This PR fixes this by trying to register in the `onCreate` method (testing for null) in addition to also registering in `onActivityEntersForeground` as a fallback.

Registering will no longer be done in the `allowScreenCapture` and `preventScreenCapture` API methods. Registration also has an extra null check.

Related PRs: #28244 which was waiting on #28200 - both merged.

# Test Plan

Tested on BareExpo in both old arch/bridgeless mode without crashing when opening the ScreenCapture test screen.

### CODE REVIEW

File: packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt [hunk 1]
```diff
@@ -91,8 +93,10 @@ class ScreenCaptureModule : Module() {
       return
     }
     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
-      currentActivity.registerScreenCaptureCallback(currentActivity.mainExecutor, screenCaptureCallback!!)
-      isRegistered = true
+      if (safeCurrentActivity != null) {
+        safeCurrentActivity!!.registerScreenCaptureCallback(currentActivity.mainExecutor, screenCaptureCallback!!)
+        isRegistered = true
+      }
```
Comment (alanjhughes) [inline packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt:99]: We should be able to avoid the explicit null check with
```suggestion
    safeCurrentActivity?.registerScreenCaptureCallback(currentActivity.mainExecutor, screenCaptureCallback!!)
```

**Review by alanjhughes — APPROVED** [review]
Looks good @chrfalch. Just one nit.

File: packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt (hunk 1 above)
Comment (chrfalch) [reply packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt:99]: Yeah, but then we'd set `isRegistered` to true even though the registration didn't go through?

Comment (alanjhughes) [reply packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt:99]: Sorry, I thought of that and updated the comment. See the new version. It's not a big deal. Feel free to merge if you want to leave as is 👍

Comment (chrfalch) [reply packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt]: Good point using the Elvis-operator there - changed this.
