### PR TITLE
[sqlite] add experimental promise support

### LINKED ISSUE #13357: Implementing SQLite to use promises does not work on the second step in a transaction
### Summary

I am trying to use promises to reduce the code depth for the SQLite callbacks.  However, it appears that the way expo-sqlite is implemented, using `immediate` it when it starts and completes the first SQL in a transaction, it marks the transaction as "complete" and executing a second SQL in the same transaction hangs.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android
iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.18.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      npm: 6.14.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ^0.16.3 => 0.16.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@trajano/sqlite-async

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #13357
close ENG-8685

# How

- originally, the callbacks for websql doesn't support Promise. when people using either 'async/async` or '.then` inside the callback, the statement will be executed after the "transaction end" statement.
- we should we low level control without websql at all.
- introduce low-level `execAsync`
- introduce `transactionAsync`
  usage
  ```tsx
  const db = SQLite.openDatabase('dbName', version);

  const readOnly = true;
  await db.transactionAsync(async tx => {
    const result = await tx.executeSqlAsync('SELECT COUNT(*) FROM USERS', []);
    console.log('Count:', result.rows[0]['COUNT(*)']);
  }, readOnly);
  ```
  note that the result is the [`ResultSet` type](https://github.com/expo/expo/blob/065419647694cf9341261bc7ac614d05e4bac27d/packages/expo-sqlite/src/SQLite.types.ts#L167-L177) but not the [`SQLResultSet` type](https://github.com/expo/expo/blob/065419647694cf9341261bc7ac614d05e4bac27d/packages/expo-sqlite/src/SQLite.types.ts#L93C18-L121). people can access the result items by `rows[0]` rather than `rows.item(0)`. i was thinking to deprecate websql somehow and it doesn't make sense to wrap the result by the [`WebSQLResultSet` again](https://github.com/nolanlawson/node-websql/blob/b3e48284572108feff1cd019dc7f13c1d8aa34b2/lib/websql/WebSQLTransaction.js#L12-L36)

# Test Plan

add some SQLite Async unit tests and test suite ci should be passed

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-sqlite/src/SQLite.ts [hunk 1]
```diff
@@ -54,6 +93,26 @@ class SQLiteDatabase {
...
+   * @param asyncCallback A `SQLTransactionAsyncCallback` function that can perform SQL statements in a transaction.
+   * @param readOnly true if all the SQL statements in the callback are read only.
+   */
+  async transactionAsync(
+    asyncCallback: SQLTransactionAsyncCallback,
+    readOnly: boolean = false
+  ): Promise<void> {
+    await this.execAsync([{ sql: 'BEGIN;', args: [] }], false);
+    try {
+      const transaction = new ExpoSQLTransactionAsync(this, readOnly);
```
Comment (brentvatne) [inline packages/expo-sqlite/src/SQLite.ts:108]: out of curiosity - how did you decide on wrapping this in an `ExpoSQLTransaction` class rather than inlining the `execAsync` here?

Comment (Kudo) [reply packages/expo-sqlite/src/SQLite.ts:108]: the idea is to make `transactionAsync` like `transaction` but only for async mode. for `transaction`, it gives you [a transaction interface](https://github.com/expo/expo/blob/fb5dc6036cf10c1d288388690d482a8330b9be6d/packages/expo-sqlite/src/SQLite.types.ts#L63-L84) and that is actually a wrapped `WebSQLTransaction` as well.

i'm open to the design, feel free to comment if there's any thought.

Comment (brentvatne) [reply packages/expo-sqlite/src/SQLite.ts:108]: sounds reasonable, thanks for clarifying!

**Comment by Kudo** [comment]
landing this pr because it doesn't have other concerns and it's experimental.

**Comment by sean-fletching** [comment]
Hello,

Thanks for this change! I discovered the transactional problem in my code today (trying to wrap promises around it) and then discovered this thread and the new expo-sqlite 11.3.1.

I've integrated this and I noticed a few things I'd like to share; hopefully this is an OK place:

- My app now throws an error at startup 
> Cannot find native module 'ExpoSQLite'
and I assumed that this could be fixed by building an expo-dev-client, which it did. I didn't see this in the documentation but 11.3.1 isn't an approved SDK 48.0.0 package, so I'd assume that also means it doesn't get built into Expo Go either, at least not yet?

**Comment by Kudo** [comment]
hi there! this feature is available in sdk 49 and it's now public beta.

**Comment by mphill** [comment]
> Hello,
> 
> Thanks for this change! I discovered the transactional problem in my code today (trying to wrap promises around it) and then discovered this thread and the new expo-sqlite 11.3.1.
> 
> I've integrated this and I noticed a few things I'd like to share; hopefully this is an OK place:
> 
> * My app now throws an error at startup
> 
> > Cannot find native module 'ExpoSQLite'
> 
> and I assumed that this could be fixed by building an expo-dev-client, which it did. I didn't see this in the documentation but 11.3.1 isn't an approved SDK 48.0.0 package, so I'd assume that also means it doesn't get built into Expo Go either, at least not yet?

This is an interesting situation I saw too.  

Make sure you install this using `npx expo install expo-sqlite` and not `yarn add expo-sqlite`.  This new version of expo-sqlite will fail on expo 48.

**Comment by sean-fletching** [comment]
> hi there! this feature is available in sdk 49 and it's now public beta.

Thanks! Hey I believe I found a typing error in the code here: 
https://github.com/expo/expo/blob/main/packages/expo-sqlite/src/SQLite.ts#L57

This will cause errors to go unnoticed, at least for me, until I checked that the property `error` was on the result object and throw that result to kill a transaction. I don't want to keep your PR here running though - can I help file a bug on that or a PR?

**Comment by tanoc** [comment]
Am I wrong thinking that there should be some sort of locks (or a queue like in `@expo/websql`) for `transactionAsync`? It looks if you are running 2 concurrent transactions it could result in something like this with unexpected results:

```
...
BEGIN
INSERT ...
BEGIN
INSERT ...
END
ROLLBACK
...
```

In `@expo/websql` the `_createTransaction` function is actually [appending the transaction to a queue](https://github.com/expo/node-websql/blob/fa169c167f75347cb2768a99b122f8ac40eb735c/lib/websql/WebSQLDatabase.js#L90), making every transaction independent, waiting one to finish before starting the next one.
