### PR TITLE
[expo-contacts] resolve presentFormAsync when form closes

### LINKED ISSUE #8840: Not able to determine when form is closed after calling Contacts.presentFormAsync on iOS
### Summary of Issue
After calling Contacts.presentFormAsync, there is no way of knowing that the user is now back on the App, if something changed, or the editing was canceled. The promise returned from presentFormAsync resolves when opening the modal.

### Environment
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.5

Target: IOS Simulator

### Steps to Reproduce
1. Call Contacts.presentFormAsync
2. Edit the Contact or Cancel

### Expected Behavior vs Actual Behavior
I'd expect some way of knowing that the user has finished editing the contact, or if they hit cancel on the modal. Ideally that promise is resolving after one of those two things happens. I can't rely on AppState, or even useFocusEffect from React Navigation for this as neither of them trigger when the modal closes.

This issue had already been reported here:
https://github.com/expo/expo/issues/3696

It seems that arnaudambro tried to commit a fix for it, but it didn't make it to the new SDK version.

### PR DESCRIPTION
**Pull request by dsokal**
# Why

Fixes https://github.com/expo/expo/issues/8840 (and https://github.com/expo/expo/issues/3696)

Currently, `Contacts.presentFromAsync` resolves immediately after the modal/activity has appeared. This seems to be undesirable as apps usually depend on the state of the edited contact. 

# How

- I changed the iOS implementation so that the promise is resolved after the modal disappears.
- Even though the original issue was about iOS, I also updated the Android implementation so it behaves the same.
- I added a new button to the Contact screen in NCL so it's possible to test the `Contacts.presentFromAsync` there.

# Test Plan

Tested with NCL.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java [hunk 1]
```diff
@@ -48,7 +51,11 @@
 import static expo.modules.contacts.models.BaseModel.decodeList;
 
 public class ContactsModule extends ExportedModule {
+  public static final int RC_EDIT_CONTACT = 2138;
```
Comment (tsapeta) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java:54]:
```suggestion
  public static final int RC_EDIT_CONTACT = 2137;
```

**Review by tsapeta — CHANGES_REQUESTED** [review]

**Review by tsapeta — APPROVED** [review]
