### PR TITLE
[expo-updates] filter assets in manifest to match those embedded in build

### LINKED ISSUE #1859: New eject bare workflow unable to load bundled assets on Release configuration and crashes
## Expected Behavior

After Expo Eject (new bare workflow),
expo publish
react-native run-ios --configuration Release 
application should run on device/simulator

## Observed Behavior

react-native run-ios --configuration Release 
crash with

```
2020-04-10 18:05:17.460983+0300 collect[8448:2356523] *** Terminating app due to uncaught exception ‘NSInvalidArgumentException’, reason: '* -[NSFileManager copyItemAtPath:toPath:options:error:]: source path is nil’**
```
Checked the urls, and see 
/var/mobile/Containers/Data/Application/C72454CA-B3C2-4E13-9DA1-EA4B70E8FA4C/Library/Application Support/.expo-internal/43b6c00fa250b3b2925695018d6fb84e0799a288213499970aa9dc2ab615aadf.ttf

The fonts are not being published to .expo-internal/ 

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

  Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.17.21

## Reproducible Demo

Create Expo Project
Add Fonts
```
  async UNSAFE_componentWillMount() {
    await Font.loadAsync({
      //   Fonts
      // Maax
      Maax: require('../src/assets/font/Maax/Maax.otf'),
      Maax_Bold: require('../src/assets/font/Maax/Maax-Bold.otf'),
      Maax_BoldItalic: require('../src/assets/font/Maax/Maax-BoldItalic.otf'),
```

Eject
Publish
Build
Run on Release Configuration

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Fixes https://github.com/expo/expo-cli/issues/1859

# How

- It turns out that RN CLI filters the assets when embedding into a build, and only embeds those scales that are supported by the platform. Since we didn't do this in `createManifest.js`, expo-updates sometimes expected more assets to be embedded than actually were.
- We now filter using the same function imported from RN CLI, so the lists should always match now.
- Additionally, added the `dev=false` parameter which was missing before (and caused dev-only assets to be erroneously included in the manifest).
- Finally, added a better error message to iOS when expo-updates thinks it's missing embedded assets. This should help make debugging easier/clearer in the future.

# Test Plan

The repro case in [this comment](https://github.com/expo/expo-cli/issues/1859#issuecomment-629270242) works now.

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

File: packages/expo-updates/scripts/createManifest.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
+const filterPlatformAssetScales = require('@react-native-community/cli/build/commands/bundle/filterPlatformAssetScales')
```
Comment (brentvatne) [inline packages/expo-updates/scripts/createManifest.js:1]: yikes, i could see this breaking easily. we should maybe follow up with an upstream pr to pull this into a separate package or a public api

**Comment by ide** [comment]
>  This should help make debugging easier/clearer in the future.

Nice!

File: packages/expo-updates/scripts/createManifest.js (hunk 1 above)
Comment (ide) [inline packages/expo-updates/scripts/createManifest.js:1]: I agree with Brent that this coupling is fragile. Looking at https://github.com/react-native-community/cli/blob/66f5a51dccc66a12a4ba9ff9901c468a99148ab1/packages/cli/src/commands/bundle/filterPlatformAssetScales.ts it'd be easy to vendor, but that would likely increase the coupling; our vendored logic would need to stay in sync with whatever RN CLI's logic is, and there'd be even less of an indication that the two pieces of code need to be synced. The real answer I think is to make this part of RN CLI's public API eventually.

**Review by ide — APPROVED** [review]

**Comment by esamelson** [comment]
makes sense, thanks for the feedback, both of you. Will work on a more sustainable solution next week but land and release this for now to unblock people.

File: packages/expo-updates/scripts/createManifest.js (hunk 1 above)
Comment (chrmod) [reply packages/expo-updates/scripts/createManifest.js:1]: It seems it breaks `expo eject`

```
Error: Cannot find module '@react-native-community/cli/build/commands/bundle/filterPlatformAssetScales'
Require stack:
- /Users/chrmod/Projects/game/node_modules/expo-updates/scripts/createManifest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/chrmod/Projects/game/node_modules/expo-updates/scripts/createManifest.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/chrmod/Projects/game/node_modules/expo-updates/scripts/createManifest.js'
  ]
}
Command PhaseScriptExecution failed with a nonzero exit code
```
