### PR TITLE
[image] fix stopAnimating broken on downscaled images

### LINKED ISSUE #31176: expo-image stopAnimating() with AVIF does not work on iOS
### Minimal reproducible example

https://snack.expo.dev/-nigAhGm4zHjdMK3opUrW

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

I believe this is an upstream bug in SDWebImage. I'll open an issue there too.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 4.4.0 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.17 => 51.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.74.2 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

irrelevant

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #31176
close ENG-13297

# How

see #31176 for details, basically the case happens when the image is downscaled. it looks like an issue from UIKit. this pr tried to add a SDWebImage coder that we can leverage SDWebImage loading pipeline to resize the animated image.
> `Co-authored-by: DreamPiggy <lizhuoli1126@126.com>`

# Test Plan

- test repro
```js
import { Text, SafeAreaView, StyleSheet } from 'react-native';
import React, { useRef, useEffect, useState } from 'react';

import {Image} from 'expo-image'

export default function App() {
  const ref = useRef(null);
  const ref2 = useRef(null);

  const [isAnimating, setIsAnimating] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsAnimating(false);
      console.log('stop animating');
      ref.current.stopAnimating();
      ref2.current.stopAnimating();
    }, 1000)
  }, [ref])
  
  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.paragraph}>
        Animating: { isAnimating.toString() }
      </Text>
      <Text style={styles.paragraph}>
        AVIF:
      </Text>
      <Image ref={ref} source={{ uri: "https://colinbendell.github.io/webperf/animated-gif-decode/4.avif" }} style={{ height: 100, width: "100%"}} />

      <Text style={styles.paragraph}>
        WEBP:
      </Text>
      <Image ref={ref2} source={{ uri: "https://mathiasbynens.be/demo/animated-webp-supported.webp" }} style={{ height: 100, width: "100%"}} />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
```
- test static image downscaling

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

File: packages/expo-image/ios/ImageUtils.swift [hunk 1]
```diff
@@ -102,23 +102,16 @@ func shouldDownscale(image: UIImage, toSize size: CGSize, scale: Double) -> Bool
...
-  }
-
-  // Resize all animated image frames.
-  let resizedImages = await concurrentMap(images) { image in
-    return resize(image: image, toSize: size, scale: scale)
+func resize(animatedImage image: UIImage, toSize size: CGSize, scale: Double) -> UIImage {
+  if image.sd_isAnimated,
+    let animatedImage = image as? AnimatedImage {
+    let animatedCoder = ResizedAnimatedCoder(image: animatedImage, size: size, scale: scale)
+    if let result = AnimatedImage(animatedCoder: animatedCoder, scale: scale) {
```
Comment (dreampiggy) [inline packages/expo-image/ios/ImageUtils.swift:109]: It's a clever idea to use custom image class (which will receive `animatedImageFrameAtIndex` call to get frame) with post-process transform

File: packages/expo-image/ios/ResizedAnimatedCoder.swift [hunk 2]
```diff
@@ -0,0 +1,49 @@
+// Copyright 2024-present 650 Industries. All rights reserved.
+
+import SDWebImage
+
+/**
+ An animated image resizer that adjusts an already loaded `SDAnimatedImage`.
+ This is not a formal SDWebImage coder; it's used solely to leverage the SDWebImage loading pipeline.
+ */
+internal final class ResizedAnimatedCoder: SDImageIOAnimatedCoder {
```
Comment (dreampiggy) [inline packages/expo-image/ios/ResizedAnimatedCoder.swift:9]: Seems inherit from `SDImageIOAnimatedCoder` will not use the custom AVIF/WebP coder, this only supports Apple's System ImageIO format like JPEG/HEIC/WebP(from iOS 14+)

File: packages/expo-image/ios/ResizedAnimatedCoder.swift [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+  private let image: SDAnimatedImage
```
Comment (dreampiggy) [inline packages/expo-image/ios/ResizedAnimatedCoder.swift:10]: The coder should not retain the `SDAnimatedImage`. Because this cause retain cycle.

SDAnimatedImage will retain the `animatedCoder` you passed into the initializer.

File: packages/expo-image/ios/ResizedAnimatedCoder.swift [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+  init(image: SDAnimatedImage, size: CGSize, scale: Double) {
+    self.image = image
+    self.size = size
+    self.scale = scale
+    super.init()
+  }
+
+  override func animatedImageFrame(at index: UInt) -> UIImage? {
+    guard let frame = image.animatedImageFrame(at: index) else {
```
Comment (dreampiggy) [inline packages/expo-image/ios/ResizedAnimatedCoder.swift:32]: Change this into `super.animatedImageFrame(at: index)`, no need any `SDAnimatedImage` instance

File: packages/expo-image/ios/ResizedAnimatedCoder.swift (hunk 2 above)
Comment (Kudo) [reply packages/expo-image/ios/ResizedAnimatedCoder.swift:9]: the tricky part of the current solution is that even the `ResizedAnimatedCoder` inherits SDImageIOAnimatedCoder, it does not do any encode/decode. only do post-transform in `animatedImageFrameAtIndex`.

we used existing SDWebImage (which is decoded already), so it supports AVIF.

i was thinking your idea to store the `actualCoder`. i got blocked from the [eight protocols](https://github.com/SDWebImage/SDWebImage/blob/0b10fcb54484b618a53386670bff38176a203290/SDWebImage/Core/SDImageIOAnimatedCoder.h#L24-L56) are class static. it's difficult to pass from instance `actualCoder`.

File: packages/expo-image/ios/ResizedAnimatedCoder.swift (hunk 3 above)
Comment (Kudo) [reply packages/expo-image/ios/ResizedAnimatedCoder.swift:10]: as mentioned above, we didn't go through decode in this coder. the `initWithAnimatedImageData:options:` has not being called, so data from `super` is not available.

current approach doesn't have retain cycle. it's like
`resized SDWebImage` -> `ResizedAnimatedCoder` -> `ResizedAnimatedCoder.image (original image)` -> `original animatedCoder (for example, SDImageAVIFCoder)`
if not don't retain the image here, the original image will be deallocated.

File: packages/expo-image/ios/ResizedAnimatedCoder.swift (hunk 4 above)
Comment (Kudo) [reply packages/expo-image/ios/ResizedAnimatedCoder.swift:32]: same as above the `super` is unavailable because we didn't decode

**Review by Kudo — COMMENTED** [review]
thanks for all the nice comments. the current solution is tricky because we didn't call `initWithAnimatedImageData:options:`. hopes my explanation is clear to you. if there's any questions, feel free to let me know.

File: packages/expo-image/ios/ResizedAnimatedCoder.swift (hunk 2 above)
Comment (dreampiggy) [reply packages/expo-image/ios/ResizedAnimatedCoder.swift:9]: > i got blocked from the [eight protocols](https://github.com/SDWebImage/SDWebImage/blob/0b10fcb54484b618a53386670bff38176a203290/SDWebImage/Core/SDImageIOAnimatedCoder.h#L24-L56) are class static

No, The coder protocol APIs are all instance method.

Your link pointed to another ImageIO based coder implementation details, it's different thing and you don't need them at all. 

https://sdwebimage.github.io/documentation/sdwebimage/sdimagecoder

**Comment by dreampiggy** [comment]
Again, don use inherit. Just use proxy (which means, you retain the actual coder and proxy API to that)

This code should works, ignore what my original post says

```
internal final class ResizedAnimatedCoder: NSObject, SDAnimatedImageCoder {
    var actualCoder: SDAnimatedImageCoder
    var size: CGSize
    var scale: CGFloat
    // All other APIs just proxy to `actualCoder`
    func animatedImageCount -> {
        return actualCoder.animatedImageCount
    }
    // proxy and do customization
    func animatedImageFrame(at: index: UInt) -> {
        let image = actualCoder.animatedImageFrame(at: index)
        // do what you want
    }
}
```

File: packages/expo-image/ios/ResizedAnimatedCoder.swift (hunk 2 above)
Comment (Kudo) [reply packages/expo-image/ios/ResizedAnimatedCoder.swift:9]: oh interesting! let me try for SDImageCoder. thanks for the hint!

**Comment by Kudo** [comment]
> Again, don use inherit. Just use proxy (which means, you retain the actual coder and proxy API to that).

the approach works like a charm! much appreciated ❤️

**Comment by dreampiggy** [comment]
Looks OK for now.


But, I've decided to provide a better and easy-to-use API for this common case. Like `scaled animated image` or `tinted color animated image`. Which applies to individual image view (Note: not for image level, for image view, rendering level)

### I'll call this Animated Image frame processor

Sample API:

```objective-c
SDAniamtedImageView *imageView;
 [imageView addFrameProcessor:[SDAnimatedImageFrameProcessor processorWithBlock:^(id<SDAnimatedImage> contextImage, UIImage *frame) {
     UIImage *finalFrame = [frame imageWithTintColor:UIColor.greenColor];
     finalFrame = [finalFrame imageFlippedForRightToLeftLayoutDirection];
     finalFrame = [finalFrame resizedImageWithSize:CGSizeMake(100,200)];
     finalFrame = [finalFrame resizedImageWithSize:CGSizeMake(100,200)];
 }];
```

**Review by tsapeta — APPROVED** [review]

**Comment by Kudo** [comment]
much appreciated @dreampiggy ❤️ the frame processor api looks decent. i'm going to merge this pr first and would give the frame process a try when it's ready.

**Comment by dreampiggy** [comment]
> much appreciated @dreampiggy ❤️ the frame processor api looks decent. i'm going to merge this pr first and would give the frame process a try when it's ready.

After some prototype I change my mind. I re-use the `Transformer` naming, but on animated image.

See https://github.com/SDWebImage/SDWebImage/pull/3761
