### PR TITLE
[ios][sdk-54][precompile] added support for USE_FRAMEWORKS with Expo modules

### LINKED ISSUE #39080: [SDK 54] Build fails on iOS when using `useFrameworks: 'static'` due to import of missing headers from RNScreens
### Minimal reproducible example

https://github.com/MrFunctor/expo-sdk-54-react-native-screens-missing-headers

### Steps to reproduce

When setting `useFrameworks: 'static'` in `expo-build-properties` (required for React Native Firebase), the iOS build fails because `expo-router/ios/LinkPreview/LinkPreviewNativeNavigation.h` tries to import apparently non exposed RNScreens headers:

```
> 3 | #import <RNScreens/RNSDismissibleModalProtocol.h>
    |         ^ 'RNScreens/RNSDismissibleModalProtocol.h' file not found
  4 | #import <RNScreens/RNSTabBarController.h>
    |         ^ 'RNScreens/RNSTabBarController.h' file not found

```

To reproduce, clone the repro repo and run:

```sh
yarn
yarn expo prebuild --clean
yarn ios
```

Note: In the repro, I had to build React Native from source to avoid [this issue](https://github.com/software-mansion/react-native-screens/issues/3140), and I had to apply [this patch](https://github.com/reactwg/react-native-releases/issues/1093) to React Native that has yet to be released in 0.81.1.

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.17.1 - ~/.nvm/versions/node/v22.17.1/bin/node
      Yarn: 4.9.3 - ~/.nvm/versions/node/v22.17.1/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.17.1/bin/npm
      Watchman: 2024.10.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.0-preview.5 => 54.0.0-preview.6
      expo-router: ~6.0.0-beta.5 => 6.0.0-beta.5
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: patch:react-native@npm%3A0.81.0#~/.yarn/patches/react-native-npm-0.81.0-612367b09d.patch => 0.81.0
      react-native-web: ~0.21.0 => 0.21.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by chrfalch**
# Why

Some Expo modules are including React Native Core header files to override base RN classes in their public headers. This causes the swift interop generation to fail, since the RN headers are not fully modular - some include c++ code which fails when generating the module interface for these modules.

This isn't a problem for the module itself - but for the modules or targets that are using them. XCode will try to generate a public and modular interface for the module using the Objective-c headers - but when these contains c++ the process fails.

**NOTE:** Until we get a truly modular set of headers for React Native using USE_FRAMEWORKS will fail with React Native precompiled binaries. Building from source or building without USE_FRAMEWORKS does not fail since header files are detected through search paths only - without any checks for public/modularity.

This PR contains a workaround and not a final fix that we can implement when the above is finished (it is in the works!).

Closes #39080

# How

This commit fixes this by disabling frameworks (forcing static linking) of the targets that uses RN headers in their own public headers (Expo, ExpoModulesCore, ReactAppDependencyProvider, expo-dev-menu).

To fix this I added an installer.rb class to expo-modules-autolinking that overrides the Podfile and Installer and patches the necessary modules. Also added `additionalFrameworkModulesToPatch` parameter to use_expo_modules to be able to add additional framework modules to patch when using USE_FRAMEWORKS. Not sure if this is needed, but it will be very nice to have if someone needs it one day!

edit: for clarification, this makes sure a few of our own core modules (listed above) are being statically linked, while leaving all others as frameworks - it does not switch to build from source.

# Test Plan

Tested with new Expo app using SDK-54 and the changes from this commit:

✅ Build without precompiled RN, no USE_FRAMEWORKS
✅ Build without precompiled RN, USE_FRAMEWORKS=static 
✅ Build without precompiled RN, USE_FRAMEWORKS=dynamic 
✅ Build with precompiled RN, no USE_FRAMEWORKS
✅ Build with precompiled RN, USE_FRAMEWORKS=static
✅ Build with precompiled RN, USE_FRAMEWORKS=dynamic

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: apps/bare-expo/ios/Podfile [hunk 1]
```diff
@@ -24,6 +24,10 @@ abstract_target 'BareExpoMain' do
     includeTests: true,
   )
 
+  pre_install do |installer|
+    expo_pre_install!(installer)
+  end
```
Comment (Kudo) [inline apps/bare-expo/ios/Podfile]: requiring the template change is not ideal, especially that's a temporary workflow. we had a cocoapods monkey patching code in https://github.com/expo/expo/tree/main/packages/expo-modules-autolinking/scripts/ios/cocoapods
any change to do the pre_install hook in the hook?

**Review by Kudo — CHANGES_REQUESTED** [review]

File: apps/bare-expo/ios/Podfile (hunk 1 above)
Comment (chrfalch) [reply apps/bare-expo/ios/Podfile]: I've now implemented the logic in a class called `installer.rb` as you suggested - this seems to work fine so I've remove the changes to our pod files and templates! Great suggestion!

File: packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+      return false if ENV['RCT_USE_PREBUILT_RNCORE'] != '1'
+      return false if props['ios.buildReactNativeFromSource'] == 'true'
+      return true if get_linkage?() != nil
+      false
+    end
+
+    # Returns the linkage type if USE_FRAMEWORKS is set, otherwise returns nil
+    def get_linkage?()
+      props = JSON.parse(File.read(File.join(installer.project_root, 'Podfile.properties.json'))) rescue {}
+      linkage_str = (ENV["USE_FRAMEWORKS"] || props['ios.useFrameworks'] || nil)
```
Comment (Kudo) [inline packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb]: ditto to remove `ios.useFrameworks` check. react-native also set the env from https://github.com/facebook/react-native/blob/226d2ba1607fe34f8dc16616e7ee7182a2d7a309/packages/react-native/scripts/cocoapods/utils.rb#L245-L261

if the env from react-native is too late to set, we can try to use `target_definition.build_type.to_s` to get the linkage type from cocoapods

File: packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+  class Podfile
+    public
+
+    def framework_modules_to_patch
+      @framework_modules_to_patch ||= ['ExpoModulesCore', 'Expo', 'ReactAppDependencyProvider', 'expo-dev-menu']
+    end
+
+    def expo_add_modules_to_patch(modules)
+      framework_modules_to_patch.concat(modules)
+      Pod::UI.puts "[Expo] ".blue + "Added extra framework modules to patch: #{modules.join(', ')}"
```
Comment (Kudo) [inline packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb]:
```suggestion
```

the following log will show all `framework_modules_to_patch` which is good enough

File: packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+    def get_linkage?()
+      props = JSON.parse(File.read(File.join(installer.project_root, 'Podfile.properties.json'))) rescue {}
+      linkage_str = (ENV["USE_FRAMEWORKS"] || props['ios.useFrameworks'] || nil)
+      return nil if linkage_str == nil
+      return :dynamic if linkage_str.downcase == 'dynamic'
+      return :static if linkage_str.downcase == 'static'
+      nil
+    end
+  end
+end
```
Comment (Kudo) [inline packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb]: add empty line at EOF

**Review by Kudo — CHANGES_REQUESTED** [review]

File: packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb (hunk 2 above)
Comment (chrfalch) [reply packages/expo-modules-autolinking/scripts/ios/cocoapods/installer.rb]: Removed pod file props from `should_disable_use_frameworks_for_core_expo_pods?` as well, these are not needed since all of the required env variables were already set in the pre_install step. Nice catch as always, @Kudo!

**Review by Kudo — APPROVED** [review]

**Comment by nubpro** [comment]
Hi, is this update released to the public?
if so, how do we update?
if not, any etas?

Thanks!
