### PR TITLE
[android] Rephrase comment around "Couldn't get GCM token"

### LINKED ISSUE #7653: SDK37 Android Expo Client: Couldn't get GCM token on device
## 🐛 Bug Report
While running the guide from https://docs.expo.io/versions/v37.0.0/guides/push-notifications,
I'm getting the error `Couldn't get GCM token on device.`

Please run the following project in local expo client to reproduce it
https://github.com/yortyrh/pushnandroidissue

### Environment
```
  Expo CLI 3.17.15 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.0.0 - D:\Soft\nodejs\node.EXE
      Yarn: 1.19.1 - D:\Soft\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\Soft\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.4
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

This happens in Android using the expo client

### Steps to Reproduce
1) Execute the following steps in windows CMD.
```
git clone git@github.com:yortyrh/pushnandroidissue.git
cd pushnandroidissue
yarn install
yarn start
```
2) Once the application starts, it shows the alert: "Error: Couldn't get GCM token on device"

### Expected Behavior
It should show **Token**: <the push notification token> and no alert 

### Actual Behavior
It shows **Token**: <empty> and the Alert: "Error: Couldn't get GCM token on device"

### Reproducible Demo
https://github.com/yortyrh/pushnandroidissue

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/expo/expo/issues/7653.

# How

On clean install, when only running an SDK37 experience, `getOrCreateUUID` is never called on `ExponentSharedPreferences` before we can call `getExponentPushTokenAsync`, so `getUUID` may return `null` and we should not fail in this scenario.

`getOrCreateUUID` may be called in two places in the project:
- in `ExponentNotificationIntentService#onHandleIntent` — when we receive a new token (which we may not receive!),
- in `ConstantsBinding#getConstants` — it is called in versioned code for SDKs below 37.
  For SDK37 it has been removed ([#6906](https://github.com/expo/expo/pull/6906/files#diff-df59c97cff05c0505acbbc763cbbe0b0)) in favor of `getOrCreateInstallationId` in `expo-constants/ConstantsService` which in general works the same, but it doesn't share the `SharedPreferences` instance, as the `Context` used in the module is a `ScopedContext`. Thus, even though we use the same `PREFERENCES_FILE_NAME` and `UUID_KEY`, the preferences will get scoped, rendering two different values `mExponentSharedPreferences.getUUID() != ConstantsService#getOrCreateInstallationId()`

```java
// This should have been set by ExponentNotificationIntentService when Activity was created/resumed.
```
is an outdated comment, we no longer explicitly start any of the subclasses of `ExponentNotificationIntentService` if Firebase Cloud Messaging is enabled, which it is in Expo client, we depend on the FCM `onNewToken` mechanism.

# Test Plan

I have confirmed with changes in https://github.com/expo/expo/pull/7688 that `getOrCreateUUID` is called _before everything else_ if the Firebase configuration is valid.

### CODE REVIEW

**Comment by sjchmiela** [comment]
At first I wanted this PR to [change `getUUID` to `getOrCreateUUID`](https://github.com/expo/expo/commit/36f42d6d3370ad315aa4e4b76cbeda2ec5695c3d) so that we never depend solely on the FCM calling the `onNewToken` and always try to `registerAndFetch`, but after more debugging I found it doesn't make sense — hence change of the purpose of this PR.

File: android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/notifications/NotificationsModule.java [hunk 1]
```diff
@@ -150,8 +150,12 @@ public void getDevicePushTokenAsync(final ReadableMap config, final Promise prom
...
     String uuid = mExponentSharedPreferences.getUUID();
     if (uuid == null) {
-      // This should have been set by ExponentNotificationIntentService when Activity was created/resumed.
-      promise.reject("Couldn't get GCM token on device.");
+      // This should have been set by ExponentNotificationIntentService via
+      // ExpoFcmMessagingService#onNewToken -> FcmRegistrationIntentService.registerForeground -> ExponentNotificationIntentService#onHandleIntent
+      // (#onNewToken is supposed to be called when a token is generated after app install, see
+      // https://developers.google.com/android/reference/com/google/firebase/messaging/FirebaseMessagingService#onNewToken(java.lang.String)).
+      // If it hasn't been set, the app probably couldn't register at FCM (invalid configuration?).
+      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token on device.");
```
Comment (esamelson) [inline android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/notifications/NotificationsModule.java:158]:
```suggestion
      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token on device. Check that your FCM configuration is valid.");
```

File: android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/notifications/NotificationsModule.java [hunk 2]
```diff
@@ -165,12 +169,11 @@ public void onSuccess(String token) {
 
         @Override
         public void onFailure(Exception e) {
-          promise.reject("E_GET_GCM_TOKEN_FAILED", "Couldn't get GCM token for device", e);
+          promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device", e);
```
Comment (esamelson) [inline android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/notifications/NotificationsModule.java:172]:
```suggestion
          promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device. Check that your FCM configuration is valid.", e);
```

File: android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/notifications/NotificationsModule.java [hunk 3]
```diff
@@ -165,12 +169,11 @@ public void onSuccess(String token) {
...
         }
       });
     } catch (JSONException e) {
-      promise.reject("E_GET_GCM_TOKEN_FAILED", "Couldn't get GCM token for device", e);
-      return;
+      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device", e);
```
Comment (esamelson) [inline android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/notifications/NotificationsModule.java:176]:
```suggestion
      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device. Check that your FCM configuration is valid.", e);
```

File: android/versioned-abis/expoview-abi37_0_0/src/main/java/abi37_0_0/host/exp/exponent/modules/api/notifications/NotificationsModule.java [hunk 4]
```diff
@@ -150,8 +150,12 @@ public void getDevicePushTokenAsync(final ReadableMap config, final Promise prom
...
     String uuid = mExponentSharedPreferences.getUUID();
     if (uuid == null) {
-      // This should have been set by ExponentNotificationIntentService when Activity was created/resumed.
-      promise.reject("Couldn't get GCM token on device.");
+      // This should have been set by ExponentNotificationIntentService via
+      // ExpoFcmMessagingService#onNewToken -> FcmRegistrationIntentService.registerForeground -> ExponentNotificationIntentService#onHandleIntent
+      // (#onNewToken is supposed to be called when a token is generated after app install, see
+      // https://developers.google.com/android/reference/com/google/firebase/messaging/FirebaseMessagingService#onNewToken(java.lang.String)).
+      // If it hasn't been set, the app probably couldn't register at FCM (invalid configuration?).
+      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token on device.");
```
Comment (esamelson) [inline android/versioned-abis/expoview-abi37_0_0/src/main/java/abi37_0_0/host/exp/exponent/modules/api/notifications/NotificationsModule.java:158]:
```suggestion
      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token on device. Check that your FCM configuration is valid.");
```

File: android/versioned-abis/expoview-abi37_0_0/src/main/java/abi37_0_0/host/exp/exponent/modules/api/notifications/NotificationsModule.java [hunk 5]
```diff
@@ -165,12 +169,11 @@ public void onSuccess(String token) {
 
         @Override
         public void onFailure(Exception e) {
-          promise.reject("E_GET_GCM_TOKEN_FAILED", "Couldn't get GCM token for device", e);
+          promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device", e);
```
Comment (esamelson) [inline android/versioned-abis/expoview-abi37_0_0/src/main/java/abi37_0_0/host/exp/exponent/modules/api/notifications/NotificationsModule.java:172]:
```suggestion
          promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device. Check that your FCM configuration is valid.", e);
```

File: android/versioned-abis/expoview-abi37_0_0/src/main/java/abi37_0_0/host/exp/exponent/modules/api/notifications/NotificationsModule.java [hunk 6]
```diff
@@ -165,12 +169,11 @@ public void onSuccess(String token) {
...
         }
       });
     } catch (JSONException e) {
-      promise.reject("E_GET_GCM_TOKEN_FAILED", "Couldn't get GCM token for device", e);
-      return;
+      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device", e);
```
Comment (esamelson) [inline android/versioned-abis/expoview-abi37_0_0/src/main/java/abi37_0_0/host/exp/exponent/modules/api/notifications/NotificationsModule.java:176]:
```suggestion
      promise.reject("E_GET_PUSH_TOKEN_FAILED", "Couldn't get push token for device. Check that your FCM configuration is valid.", e);
```

**Review by esamelson — APPROVED** [review]
Looks good, thanks for digging into this! Just one suggestion to make these error messages somewhat more helpful.
