### PR TITLE
[cli] Implement getApplicationIdFromBundle fixing iOS app launch issue with SDK 46

### LINKED ISSUE #1853: Android Calendar Crashes java.lang.NumberFormatException
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.2.0
  Yarn: 0.22.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

I've already created a topic in the forums and got the response to report this as an issue.
https://forums.expo.io/t/android-calendar-crashes-java-lang-numberformatexception/10466

------
### The Issue/Bug

Hello, Ive been using the Calendar API for some time now. But recently I noticed some crashes in my app. I'm not sure if this is suppose to happen but I get promted 2 times about permissons. After that 
 the app crashes.

This is my import `import {Calendar as NativeCalendar, Permissions} from "expo";`

And this is what i use to make sure I have permissions before i try to get the calendars
```
    askForCalendarPermissions = async () => {
        const calendarPermissions = await Permissions.askAsync(Permissions.CALENDAR);

        return calendarPermissions.status === 'granted';
    };
```

The crash occurs when i call:
```
const eventCalendars = await NativeCalendar.getCalendarsAsync(NativeCalendar.EntityTypes.EVENT);
```

I get no bug report from XDE but in Google Play Console I get this error (on multiple devices)
It has occurred on Android 8.0 and Android 7.0
```
java.lang.NumberFormatException: 
  at java.lang.Integer.parseInt (Integer.java:597)
  at java.lang.Integer.parseInt (Integer.java:643)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.calendarAllowedAttendeeTypesFromDBString (CalendarModule.java:1147)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendar (CalendarModule.java:1353)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendars (CalendarModule.java:1332)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.findCalendars (CalendarModule.java:318)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.access$000 (CalendarModule.java:41)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule$1.run (CalendarModule.java:70)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```

Here's a snack https://snack.expo.io/S1Vt9RPxQ that produces the error on my phone.

I'm using a One Plus 3T with android 8.0,
Other devices I've seen this issue for is:
Samsung Galaxy Note8 (Android 8.0)
Samsung Galaxy S8 (Android 7.0)
Samsung Galaxy A3 (Android 7.0)

I should add that this issue does not effect all android devices, and I have been able to use the calendar functionality before (On my One Plus 3T). But somehow something has happened since then and now I get the crash.

### PR DESCRIPTION
**Pull request by sync**
# Why

When running `expo run:ios` the app does get installed but not launched inside my current iOS simulator.

Fix:  https://github.com/expo/expo/issues/1853

# How

The method wasn't really implemented.

# Test Plan

Followed reproduction from here: https://github.com/expo/expo/issues/18536

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/@expo/cli/src/start/platforms/ios/AppleDeviceManager.ts [hunk 1]
```diff
@@ -141,8 +143,9 @@ export class AppleDeviceManager extends DeviceManager<SimControl.Device> {
   }
 
   private async getApplicationIdFromBundle(filePath: string): Promise<string> {
-    // TODO: Implement...
-    return EXPO_GO_BUNDLE_IDENTIFIER;
+    const builtInfoPlistPath = path.join(filePath, 'Info.plist');
+    const { CFBundleIdentifier } = await parsePlistAsync(builtInfoPlistPath);
```
Comment (EvanBacon) [inline packages/@expo/cli/src/start/platforms/ios/AppleDeviceManager.ts:147]: Can you do a fs.exists check and `Log.warn` if the file cannot be found, then fallback on the Expo Go bundle id, I can do the rest (testing, debug logging) after merged if you'd like. Otherwise, you can add with a line like:
```js
const debug = require('debug')('expo:start:platforms:ios:AppleDeviceManager') as typeof console.log;
```
at the top and a `debug('getApplicationIdFromBundle:', filePath);` makes it a bit easier for users to find out what's going on.

**Comment by brentvatne** [comment]
thanks for this pr! happy to land this and ship it as soon as @EvanBacon's is addressed

**Comment by brentvatne** [comment]
thanks for this! deployed in expo@46.0.7, which includes @expo/cli@0.2.9
