### PR TITLE
[ios][expo] Add `createRootViewController` to the factory

### LINKED ISSUE #36772: [expo-screen-orientation] Not detecting orientation change on iOS
### Minimal reproducible example

https://github.com/vr7bd/expo-screen-orientation-issue

### Steps to reproduce

- Clone the repo
- Run the command `pnpm i && pnpm expo prebuild --clean -p ios && pnpm expo run:ios` or the equivalent command from your package manager. Make sure to run in on an iPad (haven't tested it on iPhone)
- Change the orientation of the device. You will not see logs that are supposed to get printed when the orientation changes

This issue started occurring after upgrading to Expo SDK 53 and wasn't happening on SDK 52. It doesn't happen on Android. It hasn't been tested on iPhone.

## Expected behavior
To fire events after the orientation has been changed. 

## Actual behavior
No events are getting fired when the orientation changes 

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.15.0 - ~/Library/pnpm/node
      npm: 10.9.2 - ~/Library/pnpm/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2024.3 AI-243.25659.59.2432.13423653
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.9 => 53.0.9
      react: 19.0.0 => 19.0.0
      react-native: 0.79.2 => 0.79.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #36772
`createRootViewController` needs to be added to the `ExpoReactNativeFactoryDelegate`

# How
Override the method in `ExpoReactNativeFactoryDelegate` and call the handlers. We only use this for `expo-screen-orientation`

# Test Plan
`expo-screen-orientation` is setup correctly and works as expected

### CODE REVIEW

File: packages/expo-modules-core/ios/ReactDelegates/ExpoReactDelegateHandler.swift [hunk 1]
```diff
@@ -35,7 +35,7 @@ open class ExpoReactDelegateHandler: NSObject {
    Otherwise return nil.
    */
   @objc
-  open func createRootViewController(reactDelegate: ExpoReactDelegate) -> UIViewController? {
+  open func createRootViewController() -> UIViewController? {
```
Comment (Kudo) [inline packages/expo-modules-core/ios/ReactDelegates/ExpoReactDelegateHandler.swift:38]: fwiw, the original design to pass ExpoReactDelegate for each handlers is for callsite to get correct setup. e.g. in updates when we recreate the root view, we have to use ExpoReactDelegate to get correct root view controller from expo-splash-screen: https://github.com/expo/expo/blob/c3a83979d5e1103d3d259ea537823a3ec3972fa6/packages/expo-updates/ios/EXUpdates/ReactDelegateHandler/ExpoUpdatesReactDelegateHandler.swift#L89.

though the case is not being used here for the `createRootViewController` handler. just share the insight and open to you for making the decision.

**Review by Kudo — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]

**Comment by jacobgreenberg** [comment]
How you update to/install this patch?
