### PR TITLE
[ios][android] Update @react-native-community/datetimepicker@7.6.3

### LINKED ISSUE #27743: Expo Install Check recommends incompatible version of @react-native-community/datetimepicker
### Summary

Expo Install Check expects version: 7.6.1  of @react-native-community/datetimepicker, however while building on iOS with that version the following error causes the build to fail:

```
❌  (node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m:8:41)

   6 | {
   7 |   if (self = [super init]) {
>  8 |     YGNodeSetMeasureFunc(self.yogaNode, RNDateTimePickerShadowViewMeasure);
     |                                         ^ incompatible function pointer types passing 'YGSize ' (aka 'struct YGSize (struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') [-Wincompatible-function-pointer-types]
   9 |   }
  10 |   return self;
  11 | }
```

To resolve, please change the expected version of @react-native-community/datetimepicker to 7.6.3

### What platform(s) does this occur on?

iOS

### SDK Version

_No response_

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.0 - /opt/homebrew/bin/npm
      Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/dannelson/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.13 => 50.0.13 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/dnelsonlivecurrence/my-app-cli-bug

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #27743

# How
`et uvm -m @react-native-community/datetimepicker -c v7.6.3`

# Test Plan
~~Could only test in bare-expo as expo go is not currently building~~

Android bare-expo + NCL ✅
iOS bare-expo + NCL ✅
Android expo go + NCL ✅
iOS expo go  + NCL ✅

### CODE REVIEW

File: apps/expo-go/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/components/datetimepicker/RNTimePickerDialogFragment.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ static TimePickerDialog getDialog(
     if (display == RNTimePickerDisplay.SPINNER) {
         return new RNDismissableTimePickerDialog(
                 activityContext,
-                host.exp.expoview.R.style.SpinnerTimePickerDialog,
+								host.exp.expoview.R.style.SpinnerTimePickerDialog,
```
Comment (tsapeta) [inline apps/expo-go/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/components/datetimepicker/RNTimePickerDialogFragment.java:76]: 😮

**Review by tsapeta — APPROVED** [review]

**Comment by obayit** [comment]
How can I apply this to my project? I have the issue, but I don't know how to apply this fix to my project.
I tried `npm install expo@50` then `pod install` but the version of the RNDateTimePicker is still 7.6.1

**Comment by obayit** [comment]
In the description:
`et uvm -m @react-native-community/datetimepicker -c v7.6.3`
What is `et uvm` ???
