### PR TITLE
[with-node] Add quotes for arguments

### LINKED ISSUE #18490: [SDK46][expo-constants] build failing on getAppConfig.js
### Summary

After upgrading a bare workflow to SDK 46, I get the following error:

```
Node found at: /Users/robrechtme/.asdf/shims/node
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/robrechtme/Library/Developer/Xcode/DerivedData/MyApp-azpdixtdlkszolgclavvwztubvel/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/app.config'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at Object.<anonymous> (/Users/robrechtme/code/my-app/node_modules/expo-constants/scripts/getAppConfig.js:22:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/robrechtme/Library/Developer/Xcode/DerivedData/MyApp-azpdixtdlkszolgclavvwztubvel/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/app.config'
}
Command PhaseScriptExecution failed with a nonzero exit code
```

The error seems to be coming from [`expo-constants/scripts/getAppConfig.js#L22`](https://github.com/expo/expo/blob/main/packages/expo-constants/scripts/getAppConfig.js#L22). When I comment out that line, the build succeeds.

The error only occurs when archiving the app. During development builds it is ok.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
      Yarn: 1.22.18 - ~/.asdf/shims/yarn
      npm: 8.6.0 - ~/.asdf/installs/nodejs/16.13.1/.npm/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/robrechtme/.asdf/shims/pod
    SDKs:
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: 46.0.2 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo

No demo sorry

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fix #18490

# How

keep quotes for the arguments.
~reference the solution from https://unix.stackexchange.com/a/472593~
reference the solution from https://stackoverflow.com/a/1669548

# Test Plan

```
$ yarn create expo-app -t blank@sdk-46 sdk46
$ npx expo prebuild
$ open ios/sdk46.xcworkspace
# change the scheme name to "sdk46 (test)"
# "Archive" the project
```

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-constants/scripts/with-node.sh [hunk 1]
```diff
@@ -40,5 +40,6 @@ fi
 
 # Execute argument, if present
 if [[ "$#" -gt 0 ]]; then
-  "$NODE_BINARY" $@
+  args=( "$@" )
+  "$NODE_BINARY" "${args[@]}"
```
Comment (ide) [inline packages/expo-constants/scripts/with-node.sh:44]: Typically `"$@"` is used to pass through all of the arguments. Does that work here?
```suggestion
  "$NODE_BINARY" "$@"
```

**Review by ide — APPROVED** [review]
Approving but I suggested `"$@"` if it works, since it's more common to see and simpler.

File: packages/expo-constants/scripts/with-node.sh (hunk 1 above)
Comment (Kudo) [reply packages/expo-constants/scripts/with-node.sh]: cool it works! good to know this trick, thanks James!
