### PR TITLE
[android][screen-orientation] Fix: add event to module definition

### LINKED ISSUE #23392: `new NativeEventEmitter()` was called with a non-null argument without the required `addListener`, `removeListeners` method.
### Minimal reproducible example

https://github.com/ThejXM/Expo-Debug.git

### Summary

This occurs on Android Expo Go, not on iOS, after upgrading to SDK 49.

I'm not using `new NativeEventEmitter()` directly in my code, but check useOrientation.js for possible indirect usage.

My own code looks fine, and it used to work fine before upgrade, and it still doesn't trigger this particular issue on iOS Expo Go.

SSA_003

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.4.0 - C:\0\A\NODE\20.4.0\x64\node.EXE
      npm: 9.8.0 - C:\0\A\NODE\20.4.0\x64\npm.CMD
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #23392

# How
Add the event to module definition on `Android` to prevent the native event emitter warning. The event is supported on both platforms but doesn't use the emitter from native on `Android`.

# Test Plan
bare-expo. Warning is cleared

### CODE REVIEW

File: packages/expo-screen-orientation/android/src/main/java/expo/modules/screenorientation/ScreenOrientationModule.kt [hunk 1]
```diff
@@ -32,6 +32,8 @@ class ScreenOrientationModule : Module(), LifecycleEventListener {
   override fun definition() = ModuleDefinition {
     Name("ExpoScreenOrientation")
 
+    Events("expoDidUpdateDimensions")
```
Comment (tsapeta) [inline packages/expo-screen-orientation/android/src/main/java/expo/modules/screenorientation/ScreenOrientationModule.kt:35]: Might be worth adding a comment that this event is actually not used from native, but suppresses warnings from NativeEventEmitter. I hope we'll soon make event emitters built-in for module objects and then we could remove it from the definition.

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]
