### PR TITLE
[audio] Fix AudioSource type

### LINKED ISSUE #33665: [expo-audio] Unable to play bundled assets
### Minimal reproducible example

https://github.com/mihailapuste/ExpoAudioAssetTest

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

I'm looking to fully replace our usage of the current `expo-av` module, however I have not been able to play bundled assets. Streaming and playing files saved to local storage is fine, however files that are bundled with my project cannot be played. 

I get the following error when attempting to use `.replace(source)` on the audio player, as demonstrated in my minimal repro:
```bash
Error: FunctionCallException: Calling the 'replace' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
→ Caused by: ArgumentCastException: The 1st argument cannot be cast to type AudioSource (at ExpoModulesCore/MainValueConverter.swift:40)
→ Caused by: ConvertingException<AudioSource>: Cannot convert 'Optional(Optional(2))' to AudioSource (at ExpoModulesCore/Record.swift:40)
```

Locally bundled files have a `number` as their identifier, and it seems the `replace()` method's type `AudioSource` doesn't allow for such
```tyepscript
export type AudioSource =
  | string
  | {
      uri?: string;
      headers?: Record<string, string>;
    }
  | null
```

I ran into a similar issue once before on expo sdk 50 https://github.com/expo/expo/issues/26474.

Hope this helps, and can be addressed relatively easily.

Thank you expo team for all your hard work! 🚀

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.5.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mihailapuste/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.18 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Multiple lock files detected (yarn.lock, package-lock.json). This may result in unexpected behavior in CI environments, such as EAS Build, which infer the package manager from the lock file.

Error: Problem validating fields in /Users/mihailapuste/ExpoAudioAssetTest/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more: https://docs.expo.dev/guides/customizing-metro/
Advice: Update your metro.config.js to extend @expo/metro-config.

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-audio
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  typescript@5.0.4 - expected version: ^5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #33665

# How
Fix the `AudioSource` type to accept a number for loading local assets.

# Test Plan
Bare-expo

### CODE REVIEW

File: packages/expo-audio/src/resolveAssetSource.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
```
Comment (tsapeta) [inline packages/expo-audio/src/resolveAssetSource.ts:1]: Are you sure this works? So far in the other modules on Web we had to use `@react-native/assets-registry/registry` directly – `react-native-web` itself didn't have `resolveAssetSource` file.

**Review by tsapeta — APPROVED** [review]

**Comment by mihailapuste** [comment]
@alanjhughes 

Just re-tested with the latest changes, however the issue still persists.
https://github.com/expo/expo/issues/33665#issuecomment-2546860426


Please let me know if theres any other information i can provide or help with.

Thanks!
