### PR TITLE
[android][brightness] Fix: add event to module definition

### LINKED ISSUE #23392: `new NativeEventEmitter()` was called with a non-null argument without the required `addListener`, `removeListeners` method.
### Minimal reproducible example

https://github.com/ThejXM/Expo-Debug.git

### Summary

This occurs on Android Expo Go, not on iOS, after upgrading to SDK 49.

I'm not using `new NativeEventEmitter()` directly in my code, but check useOrientation.js for possible indirect usage.

My own code looks fine, and it used to work fine before upgrade, and it still doesn't trigger this particular issue on iOS Expo Go.

SSA_003

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.4.0 - C:\0\A\NODE\20.4.0\x64\node.EXE
      npm: 9.8.0 - C:\0\A\NODE\20.4.0\x64\npm.CMD
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Same as #24943

# How
This module has an event that is only supported on `iOS` but it still needs to be added to the module definition on`Android` to prevent a warning.

# Test Plan
bare-expo. The warning is cleared

### CODE REVIEW

File: packages/expo-brightness/android/src/main/java/expo/modules/brightness/BrightnessModule.kt [hunk 1]
```diff
@@ -12,13 +12,17 @@ import expo.modules.kotlin.modules.Module
...
+const val brightnessChangeEvent = "Expo.brightnessDidChange"
+
 class BrightnessModule : Module() {
   private val currentActivity
     get() = appContext.currentActivity ?: throw Exceptions.MissingActivity()
 
   override fun definition() = ModuleDefinition {
     Name("ExpoBrightness")
 
+    Events(brightnessChangeEvent)
```
Comment (tsapeta) [inline packages/expo-brightness/android/src/main/java/expo/modules/brightness/BrightnessModule.kt:24]: Same as https://github.com/expo/expo/pull/24943#discussion_r1365168587

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]
