### PR TITLE
fix(cli): allow fast resolver to resolve nested `node_modules` packages in monorepos

### LINKED ISSUE #37734: [Expo 53] Package resolution incorrect in monorepo setups
### Minimal reproducible example

https://github.com/ExodusMovement/expo-monorepo-resolution

### Steps to reproduce

Using Expo 53, React 19.1, React Native 0.79.4. We have the same issue using React 19.0 as well.

1. run `pnpm install`
2. add a `console.log('new version esm')` to `node_modules/lru-cache/dist/esm/index.js` and a `console.log('old version')` to  `node_modules/@exodus/asset-lib/node_modules/lru-cache/index.js`
3. start the app `cd apps/native && pnpm expo start`
4. run the app in `Expo Go`
5. we expect `'old version'` to log, since we import `@exodus/asset-lib` in the root
6. actual behaviour is that `'new version esm'` logs

This was not a problem using Expo 52, React 18.3, React Native 0.76.9.
This is also not a problem if not using a monorepo structure with all the rest of the setup being the same.

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 24.1.0 - ~/.nvm/versions/node/v24.1.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v24.1.0/bin/yarn
      npm: 11.3.0 - ~/.nvm/versions/node/v24.1.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/exodus/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
      Android SDK:
        API Levels: 26, 28, 29, 30, 31, 32, 33, 34, 35
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0, 35.0.0
        System Images: android-24 | ARM 64 v8a, android-27 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-36 | Google Play ARM 64 v8a, android-UpsideDownCake | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
14/15 checks passed. 1 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  No metadata available: lru-cache
Advice:
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

1 check failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by byCedric**
Blocked by #37770

# Why

Fixes #37734

Looking at the bug described in #37734, it turns out that we didn't configure `resolve` (used by our fast resolver) properly when using monorepos.

TL;DR;
- Fast resolver is now enabled when using React canaries
- When using monorepos, we explicitly configure [`nodeModulesPaths`](https://metrobundler.dev/docs/configuration/#nodemodulespaths)
- The `nodeModulesPaths` is then passed to the `resolve` package as `moduleDirectory`
- The `moduleDirectory` property is not identical to Metro
  - Instead, this is the folder name (or names) that should be searched recursively when resolving from specific directories.
- Because the `moduleDirectory` was set incorrectly, nested resolutions started misbehaving (see #37734)

I used the repro from #37734, and looked how the Node module resolution paths were generated:

Before | After
--- | ---
image | image

# How

Looking at the documentation for `resolve`, there is a property called [`paths`](https://github.com/browserify/resolve/tree/06bfa9190190760511720cf74efb7f00a1a40a9d?tab=readme-ov-file#resolveid-opts-cb), which actually resembles the functionality Metro provides through `nodeModulesPaths`.

image

image

> [!IMPORTANT]
> Notice how both features explains this as:
> - **resolve**:  .. _if nothing is found_ on the normal `node_modules` recursive walk ..
> - **Metro**: .. _After_ after looking through all `node_modules` directories. ..

# Test Plan

See added unit test and #37734

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by kitten — APPROVED** [review]

File: packages/@expo/cli/src/start/server/metro/createExpoMetroResolver.ts [hunk 1]
```diff
@@ -146,9 +146,7 @@ export function createFastResolver({
         blockList,
         enablePackageExports: context.unstable_enablePackageExports,
         basedir: path.dirname(context.originModulePath),
-        moduleDirectory: context.nodeModulesPaths.length
```
Comment (EvanBacon) [inline packages/@expo/cli/src/start/server/metro/createExpoMetroResolver.ts:149]: I think I intentionally changed this to support react canary

Comment (byCedric) [reply packages/@expo/cli/src/start/server/metro/createExpoMetroResolver.ts:149]: Yeah, which causes the broken behavior we are seeing with normal resolutions. That's why I created #37770 to fix the React Canary resolution.

Specifically, this behavior - which unintentionally changes package versions, possibly causing JS bundle API breakage without clear error descriptions: https://github.com/expo/expo/issues/37734#issuecomment-3019772145
