### PR TITLE
[splash-screen] Fix reading splash image from the android.splash config

### LINKED ISSUE #10382: android.splash key not being used in standalone app builds on SDK 39
### Summary of Issue

Android splash screen images failing to load... on the splash screen.

### Environment

```
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 22, 28
        Build Tools: 21.1.2, 29.0.1
        System Images: android-22 | ARM EABI v7a, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: 39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed
```

### Steps to Reproduce

This one, in `app.json` works just fine:

```
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#FFFFFF",
      "image": "./assets/splash/splash.png"
    },
```

However, when configuring the `splash` attribute for Android specifically, it fails to load the appropriate images both - on Android simulator and on a real device.

It correctly renders only the `backgroundColor` configured.

```
  "android": {
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#FFFFFF",
      "mdpi": "./assets/splash/test.png",
      "hdpi": "./assets/splash/test.png",
      "xhdpi": "./assets/splash/test.png",
      "xxhdpi": "./assets/splash/test.png",
      "xxxhdpi": "./assets/splash/test.png"
    },
 ```

### Expected Behavior vs Actual Behavior

Android splash screen images to actually load.

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Partially resolves https://github.com/expo/expo/issues/10382 - only ExpoClient flow.
This PR resolves reading `android.splash.*dpi` images as splash image.

# How

After integrating `expo-splash-screen` `*dpi` keys form the config were no longer read by the Android.
It restores previous behaviour.
Splash image is now searched for under following keys (and the first hit is used):
- `android.splash.*dpi` (from `xxxhdpi` down to `mdpi`)
- `android.splash.image` (this one is not working yet, needs schema update to transform `image` into `imageUrl`, to be delivered soon)
- `splash.image`

# Test Plan

- create an app with the config:
```json
{
  "splash": {} // intentionally empty,
  "android": {
    "splash": {
      "xxxhdpi": "<relativePathToTheSplashImage>"
    }
  }
}
```
- start the app and see the splash image is presented

### CODE REVIEW

File: android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt [hunk 1]
```diff
@@ -69,8 +70,30 @@ class ManagedAppSplashScreenConfiguration private constructor() {
...
+     * - android-scoped splash imageUrl
+     * - generic splash imageUrl
+     */
     private fun parseImageUrl(manifest: JSONObject): String? {
-      return getStringFromManifest(
+      val androidSplash = manifest
+        .optJSONObject(ExponentManifest.MANIFEST_ANDROID_INFO_KEY)
+        ?.optJSONObject(ExponentManifest.MANIFEST_SPLASH_INFO_KEY)
+      if (androidSplash != null) {
+        val dpiRelatedImageUrl = getStringFromJSONObject(
```
Comment (sjchmiela) [inline android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt:84]: So… would this return the first non-empty value for any of the keys defined in `*arrayOf("xxxhdpi"…)`? Wouldn't we want to use a lower-resolution image on a lower-resolution device?

File: android/expoview/src/main/java/host/exp/exponent/experience/ExperienceActivity.java [hunk 2]
```diff
@@ -400,8 +400,8 @@ protected void showOrReconfigureManagedAppSplashScreen(final JSONObject manifest
     }
 
     this.hideLoadingView();
-    ManagedAppSplashScreenConfiguration config = ManagedAppSplashScreenConfiguration.parseManifest(manifest);
     if (mManagedAppSplashScreenViewProvider == null) {
+      ManagedAppSplashScreenConfiguration config = ManagedAppSplashScreenConfiguration.parseManifest(manifest);
```
Comment (brentvatne) [inline android/expoview/src/main/java/host/exp/exponent/experience/ExperienceActivity.java:404]: what wsa the motivation for moving this?

File: android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt (hunk 1 above)
Comment (bbarthec) [reply android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt:84]: We've been always doing this that way (code from the `sdk-38` branch): https://github.com/expo/expo/blob/9db4ea6dcb8431faac64047f7580cdaa1c8d6df0/android/expoview/src/main/java/host/exp/exponent/LoadingView.java#L271-L295

The image is fetched into `ImageView`, so we rather prefer to always have the best resolution here.
These `*dpi` are only usable in standalone's builds.

File: android/expoview/src/main/java/host/exp/exponent/experience/ExperienceActivity.java (hunk 2 above)
Comment (bbarthec) [reply android/expoview/src/main/java/host/exp/exponent/experience/ExperienceActivity.java:404]: This `config` variable is only used in the `if` block, os it was just natural for me to scope it into `if` block as well 🤷

File: android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt (hunk 1 above)
Comment (sjchmiela) [reply android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt:84]: Ah so this won't be used in standalone apps, sorry. 👍

File: android/expoview/src/main/java/host/exp/exponent/experience/ExperienceActivity.java (hunk 2 above)
Comment (brentvatne) [reply android/expoview/src/main/java/host/exp/exponent/experience/ExperienceActivity.java:404]: ah, ok. i just wasn't sure if it was somehow intended to be related to the fix

File: android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt (hunk 1 above)
Comment (brentvatne) [reply android/expoview/src/main/java/host/exp/exponent/experience/splashscreen/ManagedAppSplashScreenConfiguration.kt:84]: if it's the way we've always done it then let's stick with that. we can follow up with improvements over status quo if needed in another pr

**Review by brentvatne — APPROVED** [review]
