### PR TITLE
[expo-random] Add sync equivalents for expo-random methods

### LINKED ISSUE #7209: Compatibility with uuid 7.x, nanoid, and others
### Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.13.1
```

### Steps to Reproduce

There are a lot of libraries that requires synchronous random values. Many of those libraries are moving away from `Math.random()` because of the numerous issues with them.

The new standard web platforms api is the `crypto.getRandomValues` API, and this is what e.g. uuid and nanoid uses. This is an excellent API that gives you secure random values. The newly released version 7.x of uuid does no longer work without this API.

I've previously tried to [add `crypto.getRandomValues` into React Native itself](https://github.com/facebook/react-native/pull/20686), but unfortunately that never came to fruition. I still think that that would be the absolut best approach.

The next best approach for vanilla React Native is a polyfill! So that's why I wrote: [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values).

Unfortunately this polyfill doesn't work in Expo since it requires native code.

My proposal is to add the package to Expo as with other native packages, but also go one step further and adding the `require` of the polyfill to Expo itself, so that `crypto.getRandomValues()` will just work out of the box for everyone!

-----

We've already heard from a few users that are having problem with uuid in React Native/Expo, see some previous discussions: https://github.com/uuidjs/uuid/issues/375 https://github.com/uuidjs/uuid/pull/385

What we did for now was add instructions to React Native users to use the polyfill, but unfortunately we cannot offer a solution to Expo users right now 😱 

-----

As always I'm willing to submit PRs for this 👍

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

Provide building blocks to fix #7209

# How

Added a sync version of the expo-random `getRandomBytes` method.

To do this I had to convert expo-random away from a unimodule, because we don't support sync methods yet. This was a bit awkward to do on the build/dependency configuration side because we lean on autolinking unimodules in our packages directory, so I'd appreciate feedback on whether I've configured that properly in the appropriate gradle files.

# Test Plan

Open the "Random" example in NCL

### CODE REVIEW

File: packages/expo-updates/ios/EXUpdates/AppLoader/EXUpdatesFileDownloader.m [hunk 1]
```diff
@@ -202,7 +202,7 @@ - (nullable NSDictionary *)_extractManifest:(id)parsedJson error:(NSError **)err
   }
 
   if (error) {
-    *error = [NSError errorWithDomain:kEXUpdatesFileDownloaderErrorDomain code:1009 userInfo:@{NSLocalizedDescriptionKey: [NSString stringWithFormat:@"No compatible update found at %@. Only %@ are supported.", _config.updateUrl.absoluteString, _config.sdkVersion]}];
+    *error = [NSError errorWithDomain:EXUpdatesFileDownloaderErrorDomain code:1009 userInfo:@{NSLocalizedDescriptionKey: [NSString stringWithFormat:@"No compatible update found at %@. Only %@ are supported.", _config.updateUrl.absoluteString, _config.sdkVersion]}];
```
Comment (brentvatne) [inline packages/expo-updates/ios/EXUpdates/AppLoader/EXUpdatesFileDownloader.m:205]: this was broken on master at the time of creating this branch, this change will go away on rebase once it's resolved there

File: packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java [hunk 2]
```diff
@@ -1,39 +1,40 @@
...
-  }
-
   @Override
   public String getName() {
     return "ExpoRandom";
   }
 
-  @ExpoMethod
-  public void getRandomBase64StringAsync(int randomByteCount, final Promise promise) {
+  private String _getRandomBase64String(int randomByteCount) throws NoSuchAlgorithmException {
```
Comment (ide) [inline packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java:23]: Leave off the underscore for private Java methods

File: packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java [hunk 3]
```diff
@@ -1,39 +1,40 @@
...
-import org.unimodules.core.interfaces.ExpoMethod;
-import org.unimodules.core.Promise;
+import com.facebook.react.bridge.Promise;
+import com.facebook.react.bridge.ReactApplicationContext;
+import com.facebook.react.bridge.ReactContextBaseJavaModule;
+import com.facebook.react.bridge.ReactMethod;
 
-public class RandomModule extends ExportedModule {
-
-  SecureRandom mRandom;
```
Comment (ide) [inline packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java:15]: Keep the member variable since the SecureRandom constructor has to loop through security providers.

File: packages/expo-random/ios/EXRandom/EXRandom.m [hunk 4]
```diff
@@ -4,23 +4,34 @@
...
+#pragma mark - Internal methods
+
+- (NSString *)_getRandomBase64String:(NSUInteger)length {
+    NSMutableData *bytes = [NSMutableData dataWithLength:length];
+
+    OSStatus result = SecRandomCopyBytes(kSecRandomDefault, length, [bytes mutableBytes]);
+    if (result == errSecSuccess) {
+      return [bytes base64EncodedStringWithOptions:0];
+    } else {
+      @throw([NSException exceptionWithName:@"expo-random" reason:@"Failed to create secure random string" userInfo:nil]);
```
Comment (ide) [inline packages/expo-random/ios/EXRandom/EXRandom.m:33]: Instead of throwing, accept an optimal NSError double pointer and set its value.

File: packages/expo-random/src/Random.ts [hunk 5]
```diff
@@ -3,21 +3,34 @@ import { toByteArray } from 'base64-js';
...
-      `expo-random: getRandomBytesAsync(${value}) expected a valid number from range 0...1024`
+      `expo-random: ${methodName}(${value}) expected a valid number from range 0...1024`
     );
   }
 }
 
+export function getRandomBytes(byteCount: number): Uint8Array {
+  assertByteCount(byteCount, 'getRandomBytes');
+  const validByteCount = Math.floor(byteCount);
+  if (ExpoRandom.getRandomBytesAsync) {
```
Comment (ide) [inline packages/expo-random/src/Random.ts:22]: getRandomBytes

File: packages/react-native.config.js [hunk 6]
```diff
@@ -0,0 +1 @@
+{}
```
Comment (ide) [inline packages/react-native.config.js:1]: Remove?

File: packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java [hunk 7]
```diff
@@ -1,39 +1,40 @@
...
-    mRandom.nextBytes(output);
-    promise.resolve(Base64.encodeToString(output, Base64.NO_WRAP));
+    SecureRandom random = new SecureRandom();
+    random.nextBytes(output);
+
+    return Base64.encodeToString(output, Base64.NO_WRAP);
+  }
+
+  @ReactMethod
+  public void getRandomBase64StringAsync(int randomByteCount, Promise promise) throws NoSuchAlgorithmException {
```
Comment (ide) [inline packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java:32]: Should be able to remove the NoSuchAlgorithmException declarations throughout this file since we just use the default RNG algorithm.

**Review by ide — CHANGES_REQUESTED** [review]

File: android/settings.gradle [hunk 8]
```diff
@@ -37,3 +37,7 @@ includeUnimodulesProjects(
     ]
 // WHEN_DISTRIBUTING_REMOVE_TO_HERE
 )
+
+// Include Expo modules that are not unimodules
+include(":expo-random")
+project(":expo-random").projectDir = new File("../packages/expo-random/android")
```
Comment (sjchmiela) [inline android/settings.gradle:43]:
```suggestion
project(":expo-random").projectDir = new File("../packages/expo-random/android")

```

Comment (sjchmiela) [inline android/settings.gradle:43]: Would you please move it to nearer `include ':unimodules-test-core'` etc.? This should be wrapped with `// WHEN_DISTRIBUTING_REMOVE_{FROM,TO}_HERE`, otherwise it'll end up in Android shell app (Turtle shouldn't try to use this project, instead, `expokit` prebuilt AARs are available there).

File: docs/pages/versions/unversioned/sdk/random.md [hunk 9]
```diff
@@ -41,10 +41,10 @@ import * as Random from 'expo-random';
 
 ## Methods
 
-### `Random.getRandomBytesAsync(byteCount)`
+### `getRandomBytes(byteCount)`
```
Comment (sjchmiela) [inline docs/pages/versions/unversioned/sdk/random.md:44]: Docs aren't that consistent in how we write out method description, but I think it's more common there to prefix methods with `ModuleName.` and recommend `import * as ModuleName`. Was this change intentional?

File: packages/expo-random/CHANGELOG.md [hunk 10]
```diff
@@ -6,6 +6,8 @@
 
 ### 🎉 New features
 
+- Add a synchronous version of `getRandomBytesAsync` called `getRandomBytes`
```
Comment (sjchmiela) [inline packages/expo-random/CHANGELOG.md:9]:
```suggestion
- Add a synchronous version of `getRandomBytesAsync` called `getRandomBytes`. ([#9750](https://github.com/expo/expo/pull/9750) by [@brentvatne](https://github.com/brentvatne))
```

File: packages/expo-random/android/build.gradle [hunk 11]
```diff
@@ -48,14 +48,6 @@ android {
...
-  apply from: project(":unimodules-core").file("../unimodules-core.gradle")
-} else {
-  throw new GradleException(
-      "'unimodules-core.gradle' was not found in the usual Flutter or React Native dependency locations. " +
-          "This package can only be used in such projects. Are you sure you've installed the dependencies properly?")
-}
-
 dependencies {
-  unimodule "unimodules-core"
+  implementation project(path: ':ReactAndroid')
```
Comment (sjchmiela) [inline packages/expo-random/android/build.gradle:52]:
```suggestion
  //noinspection GradleDynamicVersion
  implementation 'com.facebook.react:react-native:+'
```
We should depend on a compiled dependency of RN, otherwise people installing this module in their projects would need to have `:ReactAndroid` linked too. 

https://github.com/expo/expo/blob/5d1121fee4fc6522d9ee4cfabc25457bd5718c85/packages/expo-splash-screen/android/build.gradle#L73-L74

When developing Expo SDK a `resolutionStrategy` makes sure that libraries end up depending on `:ReactAndroid` instead of `…:react-native`

https://github.com/expo/expo/blob/2770008129aef794dcdf5fcdaa35ef5056b6ff29/android/app/build.gradle#L90-L92

File: packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java (hunk 7 above)
Comment (sjchmiela) [inline packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java:32]: Wouldn't we want to catch the `NoSuchAlgorithmException` and reject the `Promise` with a developer-readable error? I don't remember how this would behave if we just threw an exception. (The same question applies to sync equivalent.)

File: packages/expo-random/package.json [hunk 12]
```diff
@@ -27,8 +27,7 @@
   "repository": {
     "type": "git",
     "url": "https://github.com/expo/expo.git",
-    "directory": "packages/expo-random"
-  },
+    "directory": "packages/expo-random" },
```
Comment (sjchmiela) [inline packages/expo-random/package.json:30]:
```suggestion
    "directory": "packages/expo-random"
  },
```

File: packages/expo-random/src/ExpoRandom.web.ts [hunk 13]
```diff
@@ -2,6 +2,10 @@ export default {
   get name(): string {
     return 'ExpoRandom';
   },
+  getRandomBytes(length: number): Uint8Array {
+    const array = new Uint8Array(length);
+    return window.crypto.getRandomValues(array);
```
Comment (sjchmiela) [inline packages/expo-random/src/ExpoRandom.web.ts:7]:
```suggestion
    return (window.crypto ?? window.msCrypto).getRandomValues(array);
```
? https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto#Syntax

File: packages/react-native.config.js (hunk 6 above)
Comment (sjchmiela) [reply packages/react-native.config.js:1]: 👍 Should this have ended up inside `packages/expo-random` to add RN autolinking capabilities?

**Review by sjchmiela — DISMISSED** [review]
Good job! Happy to see integration with newest `uuid`! 👍

File: packages/react-native.config.js (hunk 6 above)
Comment (brentvatne) [reply packages/react-native.config.js:1]: ah yes

File: docs/pages/versions/unversioned/sdk/random.md (hunk 9 above)
Comment (brentvatne) [reply docs/pages/versions/unversioned/sdk/random.md:44]: good catch

File: packages/expo-random/android/build.gradle (hunk 11 above)
Comment (brentvatne) [reply packages/expo-random/android/build.gradle:52]: ah thank you for pointing this out!

File: packages/expo-random/src/ExpoRandom.web.ts [hunk 14]
```diff
@@ -2,6 +2,10 @@ export default {
...
+  },
   async getRandomBytesAsync(length: number): Promise<Uint8Array> {
     const array = new Uint8Array(length);
     return window.crypto.getRandomValues(array);
```
Comment (brentvatne) [inline packages/expo-random/src/ExpoRandom.web.ts:11]:
```suggestion
    return (window.crypto ?? window.msCrypto).getRandomValues(array)
```

File: packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java (hunk 7 above)
Comment (brentvatne) [reply packages/expo-random/android/src/main/java/expo/modules/random/RandomModule.java:32]: @ide mentioned:

> Should be able to remove the NoSuchAlgorithmException declarations throughout this file since we just use the default RNG algorithm.

so i went ahead and did this

File: packages/expo-random/src/ExpoRandom.web.ts [hunk 15]
```diff
@@ -2,8 +2,14 @@ export default {
...
+  getRandomBytes(length: number): Uint8Array {
+    const array = new Uint8Array(length);
+    // @ts-ignore
+    return (window.crypto ?? window.msCrypto).getRandomValues(array);
+  },
   async getRandomBytesAsync(length: number): Promise<Uint8Array> {
     const array = new Uint8Array(length);
-    return window.crypto.getRandomValues(array);
+    // @ts-ignore
+    return (window.crypto ?? window.msCrypto).getRandomValues(array)
```
Comment (ide) [inline packages/expo-random/src/ExpoRandom.web.ts:13]:
```suggestion
    return (window.crypto ?? window.msCrypto).getRandomValues(array);
```

**Review by ide — APPROVED** [review]

**Comment by martinheidegger** [comment]
:wave: Hi! Just wanted to let you know that there [is a conversation](https://github.com/LinusU/react-native-get-random-values/issues/11) in `react-native-get-random-values` about the performance passing the binary data between the threads.

Related  to the performance issue, I was wondering if it wouldn't be possible to change from a string to an array of numbers. This way the `new Uint8Array(dataFromNative)` could be used without the base64 conversion on both sides. More data would need to sent, but maybe it is still faster than the string array?

**Comment by ide** [comment]
How much does it matter or is this mostly a developer-driven desire rather than a UX-driven one? Either way in the future we should be able to build something faster than strings and numbers, we're just looking for something reasonable that can make UUIDs which are tiny regardless.

**Comment by martinheidegger** [comment]
The get-random-values is used in crypto libraries like [sodium-javascript](https://github.com/sodium-friends/sodium-javascript/blob/a546f3e51d4496b18f4d565339bd06c0ccbc0527/randombytes.js#L9) which tend to process quite a bit of data which can get really slow (stopped, stuttering UI)

**Comment by brentvatne** [comment]
@martinheidegger - i'm open to a pr to improve perf here, i don't have time to work on it myself though. the main objective of this pr was to unblock people who need crypto.getRandomValues polyfill for usage with uuid and so on
