### PR TITLE
[core][splash-screen] fix splash screen missing from delay loading

### LINKED ISSUE #23363: [SDK49] expo-updates makes SplashScreen image not Render on APK
### Minimal reproducible example

https://github.com/islamouzou/expo-updates-demo

### Summary

As the title says , when i create a project using the latest SDK 49 , even the default expo template without any change to the code , when i generate an apk using (npx eas build -p android --profile preview --local ) even on the cloud , while expo-updates is installed on my project (no need to use anything from the package , just install it ) the splash screen image disappears . i tried uninstalling expo-updates then rebuilding i got my splash screen back upon the app launch .

this behaviour is only in production release ( APK) , it doesn't happen in dev client .

i tried this with expo-updates@0.18.8 and 0.18.7 , 0.17.0 i got the same behaviour .

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 11.7.6
Shell: 5.8 - /bin/zsh
Binaries:
Node: 18.16.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.5.1 - /usr/local/bin/npm
Watchman: 2023.05.22.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.12.1 - /usr/local/bin/pod
SDKs:
Android SDK:
API Levels: 19, 27, 28, 31, 32, 33, 34
Build Tools: 27.0.0, 27.0.3, 28.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
Android NDK: 22.1.7171670
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.10121639
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
expo: ~49.0.0 => 49.0.0
react: 18.2.0 => 18.2.0
react-native: 0.72.1 => 0.72.1
npmGlobalPackages:
eas-cli: 3.15.0
expo-cli: 6.3.9
Expo Workflow: bare

### PR DESCRIPTION
**Pull request by Kudo**
# Why

close ENG-9269
fixes #23363

# How

splash screen is missing because of different call flows from delay loading #20273.

the original flow sequences are:
  - `ReactActivityDelegateWrapper.onCreate()`
  - `ReactActivityDelegate.loadApp()`
  - `Activity.setContentView()`
  - `SplashScreenViewController.showSplashScreen()`
  - `contentView.addView()` for splash view

the delay loading will change the sequences to:
  - `ReactActivityDelegateWrapper.onCreate()`
  - `SplashScreenViewController.showSplashScreen()`
  - `contentView.addView()` for splash view
  - `ReactActivityDelegate.loadApp()`
  - `Activity.setContentView()`

the splash screen will dismiss because the whole content view is replaced.

this pr tries to introduce a new `onContentChanged` lifecycle for expo-splash-screen to show splash screen at correct point.

# Test Plan

patch to https://github.com/islamouzou/expo-updates-demo provided from #23363 to see if the splash screen will not dismiss. 

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
LGTM ✅

**Review by tsapeta — APPROVED** [review]

File: packages/expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt [hunk 1]
```diff
@@ -92,15 +96,22 @@ class ReactActivityDelegateWrapper(
       .firstOrNull()
```
Comment (douglowder) [inline packages/expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt:96]: In future, if modules other than `expo-updates` need to delay app launch, you may need to change this so that all the modules that implement the interface have called their `whenReady()` method before you invoke "loadApp".

**Review by douglowder — APPROVED** [review]
Looks good! One inline comment

File: packages/expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt (hunk 1 above)
Comment (Kudo) [reply packages/expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt:96]: good catch! i've always been confused to get the app delegate subscribers doing right. in this case maybe we should loop all subscribers and wait for all `whenReady()` to be completed. will address this in a separated pr. thanks!
