### PR TITLE
[expo-notifications][Android] Get notification responses when app in background or not running

### LINKED ISSUE #14078: NotificationResponseReceivedListener not called when app is killed
### Summary

I ran into problems while developing an app that has to respond to push notifications. I based this app on the expo notification snack that is found in [the documentation](https://docs.expo.dev/versions/latest/sdk/notifications/). 

When trying out my app, the expo notification service works fine when an app is in the foreground or background, but does not trigger when the app is killed. I use the [addnotificationresponsereceivedlistenerlistener](https://docs.expo.dev/versions/latest/sdk/notifications/#addnotificationresponsereceivedlistenerlistener-event-notificationresponse--void-void) method to handle notifications when the app is killed.

I found a lot  of issues about this problem that have already been closed. Unfortunately, the solutions/pull request in these issues don't solve the problem on my system. I therefore think this might be a bug that was introduced in version 42 of the expo SDK.

#### Related issues

- https://forums.expo.dev/t/push-notification-doesnt-open-specific-screen-when-app-is-killed-works-only-in-foreground-and-background/53890/5
- https://github.com/expo/expo/issues/13333
- https://github.com/expo/expo/issues/12954
- https://github.com/expo/expo/issues/12228
- https://github.com/expo/expo/issues/11933
- https://github.com/expo/expo/issues/11470
- https://github.com/expo/expo/issues/11340
- https://github.com/expo/expo/issues/10621
- https://github.com/expo/expo/issues/9968
- https://github.com/expo/expo/issues/6943

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.1

### Environment

```bash 
Expo CLI 4.10.0 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
    IDEs:
      Android Studio: AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

**Development mode**
1. Clone the [example project](https://github.com/rickstaa/killed_app_notification_bug_example-/blob/main/README.md) or create a new expo project using the [push notification snack](https://snack.expo.dev/) in the [expo-notifications documentation](https://docs.expo.dev/versions/latest/sdk/notifications/).
2. Install the NPM dependencies.
3. Run the app on an android emulator or a  real android device.
3. Kill the app while keeping the expo go app open and send a push notification using the [push notification tool](https://expo.dev/notifications).
4. Click the notification.
5. See that the alert is not triggered.

**Production mode**
1. Clone the [example project](https://github.com/rickstaa/killed_app_notification_bug_example-/blob/main/README.md) or create a new expo project using the [push notification snack](https://snack.expo.dev/) in the [expo-notifications documentation](https://docs.expo.dev/versions/latest/sdk/notifications/).
2. Setup your google FCM credentials (see [the expo documentation](https://docs.expo.dev/push-notifications/using-fcm/)).
3. Build the project `.apk` using the `eas build -p android --profile preview` command.
4. Install the app on your device using the `adb` tool.
5. Open the app.
6. Close the app.
7. Send a notification using the [push notification tool](https://expo.dev/notifications).
8. Click the notification.
9. See that the alert is not triggered.

### PR DESCRIPTION
**Pull request by douglowder**
# Why

After the Android notifications change to FCMv1, the app is not able to get notification response listeners to fire when the app is in background or not running, and opened in response to a notification.

# How

This change leverages the Expo module Android lifecycle listeners to get the notification data from the lifecycle methods, and pass them to the notification emitter that emits notifications and responses to JS.

This change also includes support for the `useLastNotificationResponse()` hook. This is especially important if the app is not running and is opened in response to a notification, since response listeners may not become active early enough in initial render.

Fixes #14078 .

# Test Plan

- CI should pass
- Testing with release builds of an Android app on real devices

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by christopherwalter — APPROVED** [review]

**Review by alanjhughes — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

File: packages/expo-notifications/src/NotificationsEmitter.ts [hunk 1]
```diff
@@ -86,7 +86,22 @@ export function addNotificationResponseReceivedListener(
...
+        notification: { request: { content: { dataString?: string } } };
+      } = { ...response };
+      try {
+        const dataString = mappedResponse?.notification?.request?.content['dataString'];
+        if (typeof dataString === 'string') {
+          mappedResponse.notification.request.content.data = JSON.parse(dataString);
+          delete mappedResponse.notification.request.content.dataString;
+        }
+      } catch (e: any) {
+        console.log(`Error in response: ${e}`);
```
Comment (BrodaNoel) [inline packages/expo-notifications/src/NotificationsEmitter.ts:100]: Are these `console.log` ok?
