### PR TITLE
[notifications][android] fix: allow data message to control notification appearance

### LINKED ISSUE #32152: Android notifications for data-only messages not displaying after upgrading SDK 50 -> SDK 51
### Minimal reproducible example

https://gitlab.holi.team/danbim/expo-notifications-bug-demo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

(We're still working on the minimal reproducible example, but have already verified it within our app, stay tuned for an update).

We have an app that receives push notifications via 2 different services (http://novu.co and Matrix Sygnal Push Gateway). The upgrade from Expo SDK 50 to SDK 51 seems to have broken how notifications are displayed in our app:

* App not running
  * SDK 50: notification is displayed to user, press opens app
  * SDK 51: notification is NOT displayed to user
* App is in background
  * SDK 50: notification is displayed to user, press opens app, background handler receives notification
  * SDK 51: notification is NOT displayed to user, background handler receive notification
* App is in foreground
  * SDK 50: notification is displayed to user, press opens app, background handler receives notification
  * SDK 51: notification is NOT displayed to user, background handler receive notification

This can be verified using the example project by sending a notification via FCM V1 API, using:

```
curl -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
     -H "Content-Type: application/json" \
     -d '{
           "message": {
             "token": YOUR_DEVICE_TOKEN,
             "data": {"title":"test title", "message":"test message"}
           }
         }' \
     https://fcm.googleapis.com/v1/projects/$FCM_PROJECT_ID/messages:send
```

Here, the payload conforms to what's documented in https://docs.expo.dev/versions/latest/sdk/notifications/#android-push-notification-payload-specification.

## Suspected change

We suspect `RemoteNotificationContent.kt` in [this change](https://github.com/expo/expo/commit/2b5752e899db1e88293825b0fa65d61fe5c41492) to be the root cause of the changed behavior.

* The [old code](https://github.com/expo/expo/commit/2b5752e899db1e88293825b0fa65d61fe5c41492#diff-cdd761897eb667fa84e18870f73fed872f1efb7c6596f71bd451afc35c4ffe78L108) parses message/title/... from `remoteMessage.data`
* The [new code](https://github.com/expo/expo/commit/2b5752e899db1e88293825b0fa65d61fe5c41492#diff-0499ba0c855fce1d45093fe78ebab33651d0999db4682245ef1a543d6b3a3819R33) parses them from `remoteMeessage.notification`.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nodenv/versions/20.11.0/bin/node
      npm: 10.2.4 - ~/.nodenv/versions/20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 31, 32, 33
        Build Tools: 29.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0, 35.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.5.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by vonovak**
# Why

fixes #32152

# How

bring back some of the fallbacks that used to be present in `JSONNotificationContentBuilder.java`

# Test Plan

added some unit tests, fix confirmed working in https://github.com/expo/expo/issues/32152#issuecomment-2424979285

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by vonovak** [comment]
* **#32162** <a href="https://app.graphite.dev/github/pr/expo/expo/32162?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @vonovak and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/NotificationData.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+  val sticky: Boolean
+    get() = data["sticky"]?.toBoolean() ?: false
+
+  val subText: String?
+    get() = data["subtitle"]
+
+  val badge: Int?
+    get() = data["badge"]?.toIntOrNull()
+}
```
Comment (danbim) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/NotificationData.kt:64]: The old `JSONNotificationContentBuilder` and [documentation](https://docs.expo.dev/versions/latest/sdk/notifications/#android-push-notification-payload-specification) also implement the following properties for `data`:

* priority
* color

For full backward compatibility I think they should also be used as fallback from `data`.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/RemoteNotificationContent.kt [hunk 2]
```diff
@@ -65,21 +59,17 @@ class RemoteNotificationContent(private val remoteMessage: RemoteMessage) : INot
...
-    get() = remoteMessage.data["categoryId"]
+  override val categoryId = notificationData.categoryId
 
-  override val isSticky: Boolean
-    get() = remoteMessage.data["sticky"]?.toBoolean() ?: false
+  override val isSticky = notificationData.isSticky
 
-  override val subText: String?
-    get() = remoteMessage.data["subtitle"]
+  override val subText = notificationData.subText
```
Comment (danbim) [inline packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/RemoteNotificationContent.kt:70]: Typo here and in `NotificationData.kt`, should be `subtitle` instead of `subText`, otherwise build breaks as it doesn't override `subtitle` from `INotificationContent` then.

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/NotificationData.kt (hunk 1 above)
Comment (vonovak) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/NotificationData.kt]: Hello, thanks for flagging that. I added support for `color` but won't be adding support for `priority` in this PR because AFAICT, it should not be set in the `data` part of the notification but rather on the top-level object.

https://github.com/expo/expo-server-sdk-node/blob/7d620a833fd99a3071d69394b73b7182b6147397/src/ExpoClient.ts#L362

File: packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/RemoteNotificationContent.kt (hunk 2 above)
Comment (vonovak) [reply packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/RemoteNotificationContent.kt:70]: `subtitle` was renamed to `subText` internally in the android package on the main branch (not a change that would influence consumers) so this is correct.

**Review by tsapeta — APPROVED** [review]

**Comment by vonovak** [comment]
For those using expo push service, this will require a fix on our push backend. I'll comment here when that's deployed.
