### PR TITLE
[ios][localization] Fix useCalendars not re-rendering when timezone changed

### LINKED ISSUE #32736: [docs] useCalendars should not that it won't change the value even if the user changes timezone
### Summary

In https://docs.expo.dev/versions/latest/sdk/localization/#usecalendars the hook should note that it doesn't get updated when the OS changes its state for the timezone which on iOS does not trigger a restart.  

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/localization/#usecalendars

### Anything else?

It may be a code bug. It may do it on Android I haven't verified, but the statement

> If the OS settings change, the hook will rerender with a new list of calendars. 

Does not seem to match the behaviour I am seeing on iOS.

### PR DESCRIPTION
**Pull request by ouwargui**
# Why

This change addresses an issue on iOS where `useLocales` or `useCalendars` didn't re-render when the device's timezone changes.

Closes #32736 

# How

To fix this issue I added a new observer to watch for the `significantTimeChangeNotification` event and fire an event back to JS.

More info on `significantTimeChangeNotification` [here](https://developer.apple.com/documentation/uikit/uiapplication/significanttimechangenotification).

I also tried subscribing to `UIApplicationDelegate.applicationSignificantTimeChange`, but this method was never called.

https://github.com/user-attachments/assets/7aef1ccd-def3-4bcb-9cf9-89d0b2b19451

# Test Plan

I created new unit and e2e tests to cover the `getLocales` and `getCalendars` methods, but I'm not sure how to test the hooks. Let me know how can I do it and I'll update this PR :)

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: apps/test-suite/tests/Localization.js [hunk 1]
```diff
@@ -165,12 +165,25 @@ export function test(t) {
   });
 
   t.describe(`Localization works with i18n-js`, () => {
```
Comment (aleqsio) [inline apps/test-suite/tests/Localization.js:167]: Let's split unrelated changes from this PR into a separate PR.

File: bin/expotools [hunk 2]
```diff
@@ -6,5 +6,4 @@ script_dir=$(dirname "$0")
 repository_root="${script_dir}/.."
 expotools_dir="`cd ${repository_root}/tools;pwd;`"
 NODE_BINARY=${NODE_BINARY:-node}
-
```
Comment (aleqsio) [inline bin/expotools:9]: let's not change this

**Review by aleqsio — CHANGES_REQUESTED** [review]
The actual changes to listeners look good, but let's move the test changes to a separate PR! 

Thanks for submitting your PR!

File: apps/test-suite/tests/Localization.js (hunk 1 above)
Comment (ouwargui) [reply apps/test-suite/tests/Localization.js]: @aleqsio i'd like to add tests for these hooks but i'm not sure how to do it - i appreciate if you could point me to a direction

File: bin/expotools (hunk 2 above)
Comment (ouwargui) [reply bin/expotools]: removed, but it would be nice to have a separate PR for this - it fixes an issue where the build fails if your node binary path has spaces, e.g.:

`/path/to my node/binary`

**Review by aleqsio — APPROVED** [review]
