### PR TITLE
[ios][audio] Support native preloading

### LINKED ISSUE #42900: [expo-audio] Critical architecture design flaw in terms of preloading sound
### Minimal reproducible example

https://github.com/search?q=repo%3Aexpo%2Fexpo+path%3A%2F%5Epackages%5C%2Fexpo-audio%5C%2F%2F+preload&type=code

### Steps to reproduce

As we can see by link:

https://github.com/search?q=repo%3Aexpo%2Fexpo+path%3A%2F%5Epackages%5C%2Fexpo-audio%5C%2F%2F+preload&type=code

`expo-audio` **doesnt have real prealoding (buffering)** audio data before playing, that means buffering is starting right after calling `play` which causes a long init time for preparation and results in large latency.

This means `expo-audio` doesnt fits for **sound effects** or UI sound interaction like clicks or other short sound audio which must be played with **low latency** so user can feel it naturally.

In these situation `expo-audio` fits only for long playing audio like background music, audio player, but not for UI sfx and games.

This is very sad situation as developers can think it is universal whereas it is not.

Also disorienting property `downloadFirst` which have description:

> This can improve playback performance and reduce buffering, especially for users managing multiple audio players simultaneously.

which is not related to buffering **AT ALL**! Because of it **only** downloads file via `downloadAsync` to temp folder in case if this is `Asset`, it doesnt do anything related to improve buffering.

Situation
---

`expo-audio` did large work to be not universal. I think the proper way to **improve latency and make real buffering** is to implement underlying `exoplayer`'s **preloading** described here:

https://developer.android.com/media/media3/exoplayer/preloading-media/preloadmanager

This will make huge improvement into this library.

### Environment

```text
SDK 54
```

### Expo Doctor Diagnostics

```text
All ok
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
closes #42900
Adds support for native preloading

# How
Adds a `preload` function and cache that allows users to create a player instance and start loading the buffer ahead of when `useAudioPlayer` is used in the component. When a url is used that exist's in the cache, we return the preloaded `AVPlayer` instance.

# Test Plan
Bare expo

### CODE REVIEW

**Comment by alanjhughes** [comment]
* **#43063** <a href="https://app.graphite.com/github/pr/expo/expo/43063?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#43062** <a href="https://app.graphite.com/github/pr/expo/expo/43062?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#43061** <a href="https://app.graphite.com/github/pr/expo/expo/43061?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/expo/expo/43061?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by psnet** [comment]
@alanjhughes thanks for working on this!

I want to mention that audio has prop `isLoaded`:

https://docs.expo.dev/versions/latest/sdk/audio/#isloaded

which is kinda useless (it doesnt really show audio is ready to play)

and there is `isBuffering`:

https://docs.expo.dev/versions/latest/sdk/audio/#isbuffering

which works in way you cannot rely on it.

---

So maybe add another **status** prop like `isBufferedToPlay` to indicate that _player_ will play asap with minimum latency (some or all data is really buffered).

Because of this, neither `isLoaded` nor `isBuffering` are currently not suitable for case "_when?_" you can play audio.

**Comment by alanjhughes** [comment]
@psnet 
> So maybe add another status prop like isBufferedToPlay to indicate that player will play asap with minimum latency (some or all data is really buffered).

What values outside of what we are already using are provided by the native SDKs would be used to determine that?

**Comment by psnet** [comment]
@alanjhughes 

> What values outside of what we are already using are provided by the native SDKs would be used to determine that?

Right now I dont know, I just want to mention that current **statuses** `isLoaded`  and `isBuffering` are not really helpful. And asked maybe you have ideas how to improve this case?

**Comment by alanjhughes** [comment]
@psnet - Ok, I will try out some things and see if this can be improved

**Comment by alanjhughes** [comment]
@psnet - you can also check the `playbackState` for `readyToPlay`

**Comment by psnet** [comment]
@alanjhughes 

> @psnet - you can also check the `playbackState` for `readyToPlay`

on web it is unimplemented (always empty):

https://github.com/expo/expo/blob/main/packages/expo-audio/src/AudioModule.web.ts#L89

on android:

it is the same as `isBuffering`:

https://github.com/expo/expo/blob/d1ac7269f57ce55e174ae51e16d0524a44b62b14/packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt#L301-L305

and as `isLoaded`:

https://github.com/expo/expo/blob/d1ac7269f57ce55e174ae51e16d0524a44b62b14/packages/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt#L331-L335

File: apps/native-component-list/src/screens/Audio/AudioPreloadScreen.tsx [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+  );
+}
+
+function SoundEffectButtons() {
+  const player1 = useAudioPlayer(sfx1, { keepAudioSessionActive: true });
+  const player2 = useAudioPlayer(sfx2, { keepAudioSessionActive: true });
+  const status1 = useAudioPlayerStatus(player1);
+  const status2 = useAudioPlayerStatus(player2);
+
+  const playSfx = (player: typeof player1, status: typeof status1) => {
```
Comment (lukmccall) [inline apps/native-component-list/src/screens/Audio/AudioPreloadScreen.tsx]:
```suggestion
  const playSfx = (player: AudioPlayer, status: AudioStatus) => {
```

File: packages/expo-audio/ios/AudioModule.swift [hunk 2]
```diff
@@ -60,7 +60,37 @@ public class AudioModule: Module {
...
+      _ = self.registry.removePreloadedPlayer(forKey: key)
+    }
+
+    Function("clearAllPreloadedSources") {
+      self.registry.removeAllPreloadedPlayers()
+    }
+
+    Function("getPreloadedSources") {
+      self.registry.preloadedPlayerKeys()
+    }
```
Comment (lukmccall) [inline packages/expo-audio/ios/AudioModule.swift]: I think those methods should be async. What do you think?

Comment (alanjhughes) [reply packages/expo-audio/ios/AudioModule.swift]: The idea is that they could be called in module scope without needing `await`. Essentially, what I'm trying to do is, when `useAudioPlayer` is called, we'll get a cached instance that already has some of the buffer loaded. Might need to think about it again 🤔

Comment (lukmccall) [reply packages/expo-audio/ios/AudioModule.swift]: I mean, calling an async function without `await` isn't a problem. Currently, users can't wait for the preload asset to complete or receive any notification when the function is completed. By making these functions async, we provide more information to users without limiting any use cases.

Comment (alanjhughes) [reply packages/expo-audio/ios/AudioModule.swift]: Ok, that makes sense. Won't they get a warning for using it without `await`? Maybe not. I'll change it 👍

**Review by lukmccall — APPROVED** [review]

**Comment by alanjhughes** [comment]
### Merge activity

* **Feb 19, 11:54 AM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/expo/expo/43061).
* **Feb 19, 11:54 AM UTC**: @alanjhughes merged this pull request with [Graphite](https://app.graphite.com/github/pr/expo/expo/43061).
