### PR TITLE
[ios][camera] Fix build issue with after switch to Swift concurrency

### LINKED ISSUE #32378: [SDK52] [expo-camera] Unable to build project due to swift concurrency error
### Minimal reproducible example

https://github.com/Eingin/expo-camera-build-reproduction

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

While trying to upgrade an existing project to SDK52 i ran into this build issue on iOS inside `expo-camera`

```
❌  (node_modules/expo-camera/ios/Current/CameraView.swift:795:13)

  793 |   private func createBarcodeScanner() -> BarcodeScanner {
  794 |     let scanner = BarcodeScanner(session: session, sessionQueue: sessionQueue)
> 795 |     scanner.setPreviewLayer(layer: previewLayer)
      |             ^ call to actor-isolated instance method 'setPreviewLayer' in a synchronous main actor-isolated context
  796 |     scanner.onBarcodeScanned = { [weak self] body in
  797 |       guard let self else {
  798 |         return


❌  (node_modules/expo-camera/ios/Current/CameraView.swift:796:13)

  794 |     let scanner = BarcodeScanner(session: session, sessionQueue: sessionQueue)
  795 |     scanner.setPreviewLayer(layer: previewLayer)
> 796 |     scanner.onBarcodeScanned = { [weak self] body in
      |             ^ actor-isolated property 'onBarcodeScanned' can not be mutated from the main actor
  797 |       guard let self else {
  798 |         return
  799 |       }
```

This looks due to the recent change within the `expo-camera` module to use swift concurrency #31900

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.5 => 52.0.0-preview.5
      expo-router: ~4.0.0-preview.3 => 4.0.0-preview.3
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.0 => 0.76.0
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  expo-dev-client@5.0.0-preview.2 - expected version: ~5.0.0-preview.2
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

### PR DESCRIPTION
**Pull request by Eingin**
# Why
`expo-camera` does not currently compile for iOS because of a bug that was missed after the change to use Swift concurrency.

Closes #32378

# How
Wrapped the code within the `createBarcodeScanner` where the invalid code is in a `Task`. Also an created a setter for `onBarcodeScanned` to satisfy the Swift compiler.

# Test Plan
Was able to build the `bare-expo` app after applying theses changes.

### CODE REVIEW

**Comment by alanjhughes** [comment]
Sorry, my mistake, this change has been published. The changes look fine, they will remove the warnings but I would still like to reproduce the build error. @Eingin what version of xcode are you using?

File: packages/expo-camera/ios/Current/BarcodeScanner.swift [hunk 1]
```diff
@@ -76,6 +76,10 @@ actor BarcodeScanner: NSObject, BarcodeScanningResponseHandler {
     }
   }
 
+  func setOnBarcodeScanned(_ onBarcodeScanned: @escaping ([String: Any]?) -> Void) {
+    self.onBarcodeScanned = onBarcodeScanned
+  }
+
```
Comment (alanjhughes) [inline packages/expo-camera/ios/Current/BarcodeScanner.swift:82]: Let's make the `onBarcodeScanned` property private now that it's not accessed directly outside of the class

File: packages/expo-camera/ios/Current/CameraView.swift [hunk 2]
```diff
@@ -791,14 +791,21 @@ public class CameraView: ExpoView, EXAppLifecycleListener,
...
-      if let body {
-        self.onBarcodeScanned(body)
+    let scanner = BarcodeScanner(
+      session: session,
+      sessionQueue: sessionQueue
+    )
+    Task {
+      await scanner.setPreviewLayer(
+        layer: previewLayer
+      )
```
Comment (alanjhughes) [inline packages/expo-camera/ios/Current/CameraView.swift:801]:
```suggestion
      await scanner.setPreviewLayer(layer: previewLayer)
```

File: packages/expo-camera/ios/Current/CameraView.swift [hunk 3]
```diff
@@ -791,14 +791,21 @@ public class CameraView: ExpoView, EXAppLifecycleListener,
...
-    scanner.onBarcodeScanned = { [weak self] body in
-      guard let self else {
-        return
-      }
-      if let body {
-        self.onBarcodeScanned(body)
+    let scanner = BarcodeScanner(
+      session: session,
+      sessionQueue: sessionQueue
+    )
```
Comment (alanjhughes) [inline packages/expo-camera/ios/Current/CameraView.swift:797]:
```suggestion
    let scanner = BarcodeScanner(session: session, sessionQueue: sessionQueue)
```

**Review by alanjhughes — CHANGES_REQUESTED** [review]

**Review by alanjhughes — APPROVED** [review]
Looks good 🔥 Thank you for the fix @Eingin!

**Comment by Eingin** [comment]
@alanjhughes im on Xcode 15.3 MacOS 14.6.1
As i mention on the issue `macos-sonoma-14.4-xcode-15.3` image on EAS causes the issue on my repoduction
