### PR TITLE
[localization] Gracefully handle unsupported locales

### LINKED ISSUE #25694: getLocales crashes due to unsupported locales
### Minimal reproducible example

https://snack.expo.dev/3e1UB5xwZ

### Summary

Call to function 'ExpoLocalization.getLocales' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: pl_SP

Also saw the same issue with following country code es_419

Snack can't reproduce the issue due to not able to change locales of device

### Environment

Environment
expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.2.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 20.9.0 - ~/Library/Caches/fnm_multishells/90040_1701414843416/bin/node
Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/90040_1701414843416/bin/yarn
npm: 10.2.4 - ~/Library/Caches/fnm_multishells/90040_1701414843416/bin/npm
Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
Android Studio: 2022.3 AI-223.8836.35.2231.11090377
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
npmPackages:
expo: ~48.0.21 => 48.0.21
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.71.14 => 0.71.14
react-native-web: ~0.18.12 => 0.18.12
npmGlobalPackages:
eas-cli: 5.9.1
Expo Workflow: bare

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

This is a PR by @mary-ext, just linted and rebuilt.
https://github.com/expo/expo/pull/27403

Closes https://github.com/expo/expo/issues/25694

I'm unable to push changes to that fork, so made a new PR

# How

# Test Plan

Tested that this doesn't break working locales on web.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by behenate — APPROVED** [review]

File: packages/expo-localization/src/ExpoLocalization.ts [hunk 1]
```diff
@@ -129,18 +129,33 @@ export default {
...
+
+      let locale = {} as ExtendedLocale;
 
       // Properties added only for compatibility with native, use `toLocaleString` instead.
-      const digitGroupingSeparator =
-        Array.from((10000).toLocaleString(languageTag)).filter((c) => c > '9' || c < '0')[0] ||
-        null; // using 1e5 instead of 1e4 since for some locales (like pl-PL) 1e4 does not use digit grouping
-      const decimalSeparator = (1.1).toLocaleString(languageTag).substring(1, 2);
-      const temperatureUnit = region ? regionToTemperatureUnit(region) : null;
+      let digitGroupingSeparator: string | null = null;
```
Comment (tsapeta) [inline packages/expo-localization/src/ExpoLocalization.ts:136]: I'm not a big fan of using `let`/`var` and reassignments, but ok 🤷‍♂️

**Review by tsapeta — APPROVED** [review]
