### PR TITLE
[ios][audio] Improve looping support

### LINKED ISSUE #42880: [expo-audio] not looping seamlessly on iOS
### Minimal reproducible example

https://github.com/robrechtme-itp/expo-audio-bug

### Steps to reproduce

1. Clone the repo:
   ```bash
   git clone https://github.com/robrechtme-itp/expo-audio-bug.git
   cd expo-audio-bug
   ```

2. Install dependencies:
   ```bash
   npm install
   ```

3. Run on iOS (and cover your ears!):
   ```bash
   npx expo run:ios
   ```

4. Wait for the 5-second audio to loop

5. Observe console output at loop point:
   ```
   [expo-audio status] {"playing": true, "currentTime": 4.98, ...}
   [expo-audio status] {"playing": false, "currentTime": 0, ...}  ← unexpected
   [expo-audio status] {"playing": true, "currentTime": 0, ...}
   ```
   The `playing: false` status causes UI bound to `status.playing` to briefly flicker.
    Also observe that the audio doesn't loop seamlessly.

On Android this issue does not occur: the audio loops seamlessly and there is no `playing: false` state emitted.

### Environment

```text
expo-env-info 2.0.8 environment info:
  System:
    OS: macOS 26.2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - ~/.asdf/installs/nodejs/22.20.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 10.9.3 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2026.01.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.16.2 - /Users/robrecht.meersman/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 25.1, iOS 26.1, macOS 26.1, tvOS 26.1, visionOS 26.1, watchOS 26.1
    Android SDK:
      API Levels: 28, 29, 31, 33, 34, 35, 36
      Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 36.0.0
      System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-36 | Google Play ARM 64 v8a
  IDEs:
    Android Studio: 2025.2 AI-252.27397.103.2522.14514259
    Xcode: 26.1.1/17B100 - /usr/bin/xcodebuild
  npmPackages:
    expo: 55.0.0-preview.9 => 55.0.0-preview.9 
    react: 19.2.0 => 19.2.0 
    react-native: 0.83.1 => 0.83.1 
  npmGlobalPackages:
    eas-cli: 16.28.0
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #42880
When the player is set to `loop` it is not seamless. When the current item ends, we seek to the beginning and start again. This causes an event where `playing` is false briefly before starting again.

# How
`AVPlayer` does not have built-in support for gapless looping. For that ideally we would use `AVPlayerLooper` but that means switching out the entire player. If the user enables looping during playback, it will restart from the beginning. This is inconsistent with androids behaviour. Instead, because `AVQueuePlayer` is a subclass of `AVPlayer` we can use that, treat it like a `AVPlayer` in the rest of the module so nothing else needs to change but handle looping correctly. 

It's a bit of a hack but when looping is enabled, we enqueue a copy of the same item so playback can continue seamlessly. It means management of sampling, notifications etc is a bit more complicated but it's the only way I could match android behaviour.  

# Test Plan
Bare expo

### CODE REVIEW

File: packages/expo-audio/ios/AudioModule.swift [hunk 1]
```diff
@@ -705,7 +705,7 @@ public class AudioModule: Module {
   private func resumeAllPlayers() {
     registry.allPlayers.values.forEach { player in
       if player.wasPlaying {
-        player.ref.play()
+        player.play(at: player.currentRate > 0 ? player.currentRate : 1.0)
```
Comment (lukmccall) [inline packages/expo-audio/ios/AudioModule.swift:708]: Let's make 1.0 the default value instead of 0, and add a guard against cases where users pass a negative value.

**Review by lukmccall — APPROVED** [review]

**Comment by 227Faddi** [comment]
is this fix available on sdk 54 or only for 55?
