### PR TITLE
[firebase-analytics] Add support for logging the `items` array to `logEvent`

### LINKED ISSUE #13954: [firebase-analytics] view_item event will be error in Android
### Summary

I've tried to send `view_item` (described in [this page](https://firebase.google.com/docs/analytics/measure-ecommerce?hl=en#web-v8) ) event to Firebase.

In iOS, `expo-firebase-analytics` works great and events were successfully sent to my Firebase server.

But in Android, sent events were error events. Firebase says `items` are wrong format.

I fond this messages from Android logcat. I hope this info help to solve the problem!

```
2021-08-06 17:30:59.715 14609-1062/com.example.app W/FA: All ArrayList elements must be of type Bundle. Value type, name: class java.util.HashMap, items
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - ~/.anyenv/envs/nodenv/versions/14.15.3/bin/node
      Yarn: 1.22.10 - ~/.anyenv/envs/nodenv/versions/14.15.3/bin/yarn
      npm: 7.11.1 - ~/.anyenv/envs/nodenv/versions/14.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
  useEffect(() => {
    if (id && name) {
      Analytics.logEvent("view_item", {
        items: [{ item_id: id, item_name: name }],
      });
    }
  }, [id, name]);
```

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Firebase Analytics allows for passing a `items` array to the `logEvent` function. This is a special case field, which can support multiple items and requires special encoding in the pure JS implementation. As well causes a crash on Android when attempting to pass an array containing objects to `items`.

Fixes #13954 and #13086

Updated docs:

image

# How

- Explicitly convert arrays to bundles on Android (non object values inside arrays are not supported)
- Add test-case to `test-suite`
- Support converting the special `items` array in `logEvent` on the pure JS client (Expo Go)
- Add unit test to verify the `items` array conversion
- Updated changelog and build files
- Updated docs (`et gdad -p expo-firebase-analytics`)

# Test Plan

- New test in test-suite succeeds
- New unit-test in `packages/expo-firebase-analytics` succeeds
- All tests pass

### CODE REVIEW

**Comment by IjzerenHein** [comment]
> #13086

This appears to be about the custom JS implementation used with the Expo Go client. Will investigate this 👍

File: packages/expo-firebase-analytics/android/src/main/java/expo/modules/firebase/analytics/FirebaseAnalyticsModule.java [hunk 1]
```diff
@@ -80,13 +82,48 @@ private FirebaseAnalytics getFirebaseAnalyticsOrReject(final Promise promise) {
     return analytics;
   }
 
+  private static Bundle convertToBundle(final MapArguments mapArguments) {
```
Comment (EvanBacon) [inline packages/expo-firebase-analytics/android/src/main/java/expo/modules/firebase/analytics/FirebaseAnalyticsModule.java:85]: I wonder if this has any overlap with https://github.com/expo/expo/pull/1422 -- @wschurman

Comment (wschurman) [reply packages/expo-firebase-analytics/android/src/main/java/expo/modules/firebase/analytics/FirebaseAnalyticsModule.java:85]: @EvanBacon - I think you may have put the incorrect number? I can tell it's missing the last number since my recent PRs are all 1422_

Comment (wschurman) [reply packages/expo-firebase-analytics/android/src/main/java/expo/modules/firebase/analytics/FirebaseAnalyticsModule.java:85]: Nice find. It definitely may. Especailly if we think we're being bitten by this in other places in the client. If so it would be a good argument for calling the new library I created in that PR something other than `expo-json-utils`; maybe something like `expo-native-utils` instead.

I do see that `MapArguments` is actually our code though, so maybe the right fix would be to make this change at that layer if we think this is the general right behavior of arrays containing object. I see we put it in the `unimodules.core` though, so maybe instead that's where the new JSON stuff should live?

**Review by Simek — COMMENTED** [review]
`FirebaseAnalytics` package has been recently converted to be compatible with API data extraction feature. To regenerate the API docs file you need to run `et gdad -p expo-firebase-analytics` and then verify if the desired changes are visible on the docs page under `unversioned` version tag.

Unfortunately, the attachment of API generation process to the current workflow is stale, I'm not sure how to proceed with this, since there are different views on the topic, so it's required to regenerate those files manually:
* https://github.com/expo/expo/pull/13666

**Comment by IjzerenHein** [comment]
Alight thanks for explaining that @Simek !
I've updated the docs accordingly and added a screenshot to the description of this PR

File: packages/expo-firebase-analytics/CHANGELOG.md [hunk 2]
```diff
@@ -6,11 +6,15 @@
 
 ### 🎉 New features
 
+- Add support for logging the `items` array to `logEvent` ([#14189](https://github.com/expo/expo/pull/14189) by [@IjzerenHein](https://github.com/IjzerenHein))
 - Update JS code to read manifest2 when manifest is not available. ([#13602](https://github.com/expo/expo/pull/13602) by [@wschurman](https://github.com/wschurman))
 - Update TS typings to allow null user property values. ([#14105](https://github.com/expo/expo/pull/14105) by [@kylerjensen](https://github.com/kylerjensen))
 
 ### 🐛 Bug fixes
 
+- Fix logEvent exception on Android when using arrays. ([#14189](https://github.com/expo/expo/pull/14189) by [@IjzerenHein](https://github.com/IjzerenHein))
```
Comment (Simek) [inline packages/expo-firebase-analytics/CHANGELOG.md:15]:
```suggestion
- Fix `logEvent` exception on Android when using arrays. ([#14189](https://github.com/expo/expo/pull/14189) by [@IjzerenHein](https://github.com/IjzerenHein))
```

**Review by Simek — APPROVED** [review]
It looks like you will need to regenerate the JSON file once more after the latest changes to the types, but besides that the rest of the changes LGTM! 👍
