### PR TITLE
Guess the device language on iOS rather than using the app-specific lang

### LINKED ISSUE #12737: [Expo 41] isRTL returns false on right-to-left languages on iOS
### Summary

My team work on app with Hebrew support and after updating to SDK41 `isRTL` returns `false` when language set to Hebrew on iOS.

I think last commit to expo-localization package broke this:

SDK40: https://github.com/expo/expo/blob/sdk-40/packages/expo-localization/ios/EXLocalization/EXLocalization.m
SDK41: https://github.com/expo/expo/blob/sdk-41/packages/expo-localization/ios/EXLocalization/EXLocalization.m

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD   
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: ^17.0.2 => 17.0.2
      react-dom: ^17.0.2 => 17.0.2
      react-native: ^0.63.4 => 0.63.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@chybisov/isrtl

1) Set language to Hebrew in iOS Language & Region settings.
2) Run snack.
3) Switch to SDK41 to see wrong behavior.
image

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- fix https://github.com/expo/expo/issues/12737

I thought about maybe adding a "device" locale and "app" locale system but given that web and Android don't appear to have this distinction, it didn't seem very important.

Further, we may want to add something like `isLayoutRTL` in the future, and expose a native function like `isLocaleRTL(locale: string): Promise<boolean>`:
```swift
var isLayoutRTL = false
EXUtilities.performSynchronously {
  isLayoutRTL = UIApplication.shared.userInterfaceLayoutDirection == UIUserInterfaceLayoutDirection.rightToLeft
}
```

# How

- https://stackoverflow.com/a/48138683/4047926

# Test Plan

- In a project, change the Simulator language to "Hebrew" in the device settings, then print out:
```js
import { isRTL, getLocalizationAsync } from "expo-localization";
import { StyleSheet, Text, I18nManager, View } from "react-native";

export default function App() {
  getLocalizationAsync().then(console.log);
  return (
    <View style={styles.container}>
      <Text style={styles.paragraph}>isRTL: {isRTL ? "true" : "false"}</Text>
      <Text style={styles.paragraph}>
        RN isRTL: {I18nManager.isRTL ? "true" : "false"}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
});

```

- The expo RTL should be true, the RN one can sometimes be true and sometimes be false.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-localization/ios/LocalizationModule.swift [hunk 1]
```diff
@@ -15,16 +15,28 @@ public class LocalizationModule: Module {
...
-    let locale = Locale.current
+    let locale = getPreferredLocale()
     let languageCode = locale.languageCode ?? "en"
     var languageIds = Locale.preferredLanguages
 
     if languageIds.isEmpty {
       languageIds.append("en-US")
     }
-
+
```
Comment (tsapeta) [inline packages/expo-localization/ios/LocalizationModule.swift:39]:
```suggestion

```

I recommend turning on this option in Xcode 👇 

Screen Shot 2022-01-06 at 14 27 21

**Review by tsapeta — APPROVED** [review]
