### PR TITLE
[core] fix ts-jest type errors

### LINKED ISSUE #32884: ts-jest is no longer working using the default template and expo 52
### Minimal reproducible example

https://github.com/sync/TypeNotTs-

### What platform(s) does this occur on?

Android, iOS, Web

### Where did you reproduce the issue?

in a development build

### Summary

I am now getting a bunch of typing errors when using ts-jest: 

```
 FAIL  components/__tests__/ThemedText-test.tsx
  ● Test suite failed to run

    node_modules/expo-modules-core/src/web/index.web.ts:5:18 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

    5   if (globalThis.expo) return;
                       ~~~~
    node_modules/expo-modules-core/src/web/index.web.ts:6:14 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

    6   globalThis.expo = {
                   ~~~~
    node_modules/expo-modules-core/src/web/index.web.ts:11:25 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

    11     modules: globalThis.ExpoDomWebView?.expoModulesProxy ?? {},
                               ~~~~~~~~~~~~~~

Test Suites: 1 failed, 1 total
```

If using expo 51 i don't get any of those typing errors:

see https://github.com/sync/TypeNotTs-/tree/expo-51 

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.local/state/fnm_multishells/22733_1731540758420/bin/node
      Yarn: 1.22.22 - ~/.local/state/fnm_multishells/22733_1731540758420/bin/yarn
      npm: 10.2.4 - ~/.local/state/fnm_multishells/22733_1731540758420/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/anthonymittaz/.gem/ruby/2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.3 => 52.0.5 
      expo-router: ~4.0.2 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.3.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  react-native-screens@~4.0.0 - expected version: ^4.0.0
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixes #32884

# How

we had some type errors specifically from jest setup call paths: https://github.com/expo/expo/blob/c1ab8d0551cf2f1b0604316a18daa563fd24c495/packages/jest-expo/src/preset/setup.js#L293-L297

- [expo-modules-core] exports and executes global types from `expo-modules-core/src/web/index.web.ts`
- [expo-modules-core] add `globalThis.ExpoDomWebView` type declaration
- [expo] ignore `FormData` type error
- [expo] ignore `react-native/Libraries/Utilities/PolyfillFunctions` type error
- [expo] also removed duplicated `process` type definition that also specified in [expo-modules-core](https://github.com/expo/expo/blob/c1ab8d0551cf2f1b0604316a18daa563fd24c495/packages/expo-modules-core/src/ts-declarations/global.ts#L63-L93). that would fix the expo package unit test error
  ```
  stderr >     ../expo-modules-core/src/ts-declarations/global.ts:93:7 - error TS2451: Cannot redeclare block-scoped variable 'process'.
  stderr > 
  stderr >     93   var process: ExpoProcess;
  stderr >              ~~~~~~~
  stderr > 
  stderr >       src/ts-declarations/process.d.ts:1:15
  stderr >         1 declare const process: {
  stderr >                         ~~~~~~~
  stderr >         'process' was also declared here.
  ```

# Test Plan

- ci passed
- test on https://github.com/sync/TypeNotTs-

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-modules-core/src/ts-declarations/global.ts [hunk 1]
```diff
@@ -91,4 +91,9 @@ declare global {
   var expo: ExpoGlobal;
 
   var process: ExpoProcess;
+
+  /**
+   * ExpoDomWebView is alived in `@expo/dom-webview` runtime.
```
Comment (tsapeta) [inline packages/expo-modules-core/src/ts-declarations/global.ts:96]:
```suggestion
   * ExpoDomWebView is defined in `@expo/dom-webview` runtime.
```

**Review by tsapeta — APPROVED** [review]
