### PR TITLE
[ios][camera] Fix initial orientation

### LINKED ISSUE #27218: Initial camera orientation is portrait even when device's orientation is landscape
### Summary

After upgrading from SDK 49 to SDK 50, Camera doesn't seem to respect the device's orientation at first. Basically, when device's orientation is landscape and Camera component is rendered, camera's orientation is portrait.

When changing the device's orientation, the camera's changes correctly, so this can be fixed if the device's orientation is manually changed to Portrait and then to Landscape, but there seems to be some issue that prevents the Camera component from detecting the device's initial orientation (seems to always detect it as Portrait).

I was able to reproduce this issue using both Expo Go app and debug/production builds in an iPad 8th Gen. I wasn't able to reproduce it in my Android phone.

### What platform(s) does this occur on?

iOS

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.1 - C:\Extras\NodeJS\node.EXE     
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.1 - C:\Extras\NodeJS\npm.CMD        
    npmPackages:
      babel-preset-expo: ^10.0.0 => 10.0.1
      expo: ^50.0.0 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/ManuelBahamonde/Expo-Camera-Orientation-Issue

Steps to reproduce are in README.md

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #27218
In both versions of the package we were checking for the initial orientation too early. At a time when the video buffers were not yet connected. 

# How
Moved the call to correct the orientation after we have connected the inputs. Also fixed a number of other small warnings and removed dead code. I've backported the fix to old camera.

# Test Plan
Bare-expo and provided repro.

### CODE REVIEW

File: packages/expo-camera/ios/Next/CameraViewNext.swift [hunk 1]
```diff
@@ -636,13 +631,12 @@ public class CameraViewNext: ExpoView, EXCameraInterface, EXAppLifecycleListener
...
     super.removeFromSuperview()
+    UIDevice.current.endGeneratingDeviceOrientationNotifications()
     NotificationCenter.default.removeObserver(self, name: UIDevice.orientationDidChangeNotification, object: nil)
   }
 
   func ensureSessionConfiguration() {
-    sessionQueue.async {
-      self.updateSessionAudioIsMuted()
-    }
+    self.updateSessionAudioIsMuted()
```
Comment (tsapeta) [inline packages/expo-camera/ios/Next/CameraViewNext.swift:639]: Are you sure that it's safe not to run on the session queue?

**Review by tsapeta — APPROVED** [review]

File: packages/expo-camera/ios/Next/CameraViewNext.swift (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-camera/ios/Next/CameraViewNext.swift:639]: Anywhere it's called is already putting it on the sessionQueue so I didn't think it was necessary to do it explicitly here too. I'm trying to keep as much of the configuration as sequential as possible. Moving too much onto the queue makes it very unpredictable when it's safe to start the session.

Comment (tsapeta) [reply packages/expo-camera/ios/Next/CameraViewNext.swift:639]: Hmm, ok, makes sense. In this case I recommend to add doc comments for functions that must be run on the session queue, i.e. running on the proper queue must be enforced externally.

Comment (alanjhughes) [reply packages/expo-camera/ios/Next/CameraViewNext.swift:639]: Looking again, I can remove this function entirely.
