### PR TITLE
[expo-av] Fix exception on Android when loading invalid Video source

### LINKED ISSUE #9185: [expo-av] NullPointerException at VideoView.java
### Summary of Issue 
I have an app that uses expo-av to show videos from users gallery. I am getting crash reports from play console.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I am using expo-av on bare react native project.

react-native : 0.62.2
expo-av: 8.2.1
expo-image-picker: 8.3.0
react-native-unimodules: 0.10.1

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

### Reproducible Demo
I don't have a reproducible demo because i don't know what causes this issue.

 
### Steps to Reproduce
I don't have steps to reproduce the error because i don't know what causes this issue.

### Expected Behavior vs Actual Behavior
Expected behavior is that the application does not crash.
Actual behavior is app crashing.

### Stack Trace

```
java.lang.NullPointerException: 
  at expo.modules.av.video.VideoView$5.a (VideoView.java:111)
  at expo.modules.av.player.SimpleExoPlayerData.a (SimpleExoPlayerData.java:14)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners (ExoPlayerImpl.java:169)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:63)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:79)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:93)
  at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:2)
  at android.os.Handler.dispatchMessage (Handler.java:112)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

### My Code 

```
<Video
    source={{ uri: this.state.videoPath }}
    ref={ (ref) => this.player = ref }
    shouldPlay={this.state.pauseVideo}
    isLooping
    useNativeControls={true}
    style={{ width: Dimensions.get("window").width, height: "100%" }}
    resizeMode={Video.RESIZE_MODE_CONTAIN}
/>
```

VideoView.java:111 points to [this](https://github.com/expo/expo/blob/1df8bf885540e4780e17e9c451b08bcea7c543ae/packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java#L106) which is a function that throws an error and this function called in [this](https://github.com/expo/expo/blob/1df8bf885540e4780e17e9c451b08bcea7c543ae/packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java#L303) and [this](https://github.com/expo/expo/blob/1df8bf885540e4780e17e9c451b08bcea7c543ae/packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java#L385) function. 

The first one is `setSource` and other one is `onLoadError` so my guess is when loading the video something happens. Maybe unsupported video format? How can i solve or debug this problem? Thank you so much.

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Fix invalid state when loading a source fails. This leads to an exception when loading a new source.
Fixes #9185

# How

When an error occurred, the MediaController was cleaned up. Upon loading a new source after that, an exception occurred because the `mMediaController` variable was null.

- Test for existence of media-controller in all places
- Re-create the Media Controller upon loading a new source

# Test Plan

- Verified that the problem no longer occurred using [test app](https://github.com/IjzerenHein/expo-av-9596-repro)
- All test-suite tests pass

Steps to reproduce:

- Start Expo client on android Emulator (Android 5.1)
- Put an mp4 file on the emulator (e.g. https://github.com/IjzerenHein/expo-av-9596-repro/blob/master/assets/video.mp4)
- Load this test app: https://github.com/IjzerenHein/expo-av-9596-repro
- Press the button to load the errornous video
- Press the button again to cause the crash

### CODE REVIEW

File: packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java [hunk 1]
```diff
@@ -396,6 +400,10 @@ public void onLoadSuccess(final Bundle status) {
         }
 
         mPlayerData.setStatusUpdateListener(mStatusUpdateListener);
+
+        if (mMediaController == null) {
+          mMediaController = new MediaController(VideoView.this.getContext());
+        }
```
Comment (Bug-Generator) [inline packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java:406]: Run linter to parry this, update changeLog and this should be good to go

**Review by Bug-Generator — APPROVED** [review]
Almost there but looks good to me

File: packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java (hunk 1 above)
Comment (IjzerenHein) [reply packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java:406]: Thanks for taking a look! Updated the changelog 👍 

> Run linter to parry this

Please elaborate

**Review by bbarthec — APPROVED** [review]
LGTM 👍
