### PR TITLE
[file-system][ios] Add UTF-8 URI support

### LINKED ISSUE #10476: [expo-file-system][iOS] lack of utf-8 uri support on iOS
### Summary of Issue 

on iOS, `expo-file-system` cannot properly handle uri that contains utf-8 strings.

It seems these lines of code that create URL from strings are responsible. They all return `nil` for any utf-8 file uri.

```objc
NSURL *uri = [NSURL URLWithString:uriString];
```

I believe we should use `NSURL fileURLWithPath` or `stringByAddingPercentEncodingWithAllowedCharacters` to properly handle this.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    Expo Workflow: bare
```

### Steps to Reproduce

```js
import * as fs from 'expo-file-system';
await fs.makeDirectoryAsync(fs.documentDirectory + "中文");
```

throws an error: `[Error: Directory '(null)' could not be created because the location isn't writable.]`.

### Expected Behavior vs Actual Behavior

Uri should work with utf-8 strings.

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Closes https://github.com/expo/expo/issues/10476

# How
This PR updates all iOS local uri instances (NSURL) to parse them using percent-encoded characters when necessary, that way we're able to support paths like `fs.documentDirectory + "中文"`. 

The main difference from https://github.com/expo/expo/pull/21098 is that this PR uses a similar approach to https://github.com/expo/expo/pull/21139, where we first decode the input URI to ensure we don't double-encode it. It also uses `stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLPathAllowedCharacterSet]` instead of `fileURLWithPath` and keeps the original scheme in place.
 
# Test Plan

Added unit test support to the EXFileSystem module, just testing `percentEncodeURIStringAfterScheme` for now, and updated `apps/test-suite/tests/FileSystem.js` to include a `Create UTF-8 uri` test.

https://user-images.githubusercontent.com/11707729/217058407-3ff04176-2b72-43f9-803c-6a097f0a79ee.mov

 

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 1]
```diff
@@ -1012,6 +1012,26 @@ - (BOOL)checkIfFileDirExists:(NSString *)path
   return [self _checkIfFileExists:dir];
 }
 
+- (NSURL *)percentEncodeURIStringAfterScheme:(NSString *)uri
+{
+  // Removing percent encoding to prevent double encoding
+  NSString *uriWitoutPercentEncoding = [uri stringByRemovingPercentEncoding];
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:1018]:
```suggestion
  NSString *uriWithoutPercentEncoding = [uri stringByRemovingPercentEncoding];
```

File: apps/native-component-list/src/screens/FileSystemScreen.tsx [hunk 2]
```diff
@@ -233,6 +233,23 @@ export default class FileSystemScreen extends React.Component<object, State> {
     }
   };
 
+  _createUTF8Uri = async () => {
```
Comment (ide) [inline apps/native-component-list/src/screens/FileSystemScreen.tsx:236]: Add a separate test case for a path like: `/hello%2Fworld.txt`. I believe it should not create `/hello/world.txt` (specifically, no directory named "hello").

**Review by ide — CHANGES_REQUESTED** [review]
My intuition is that we should not percent-encode the whole string after the URL scheme. We should only encode characters that are outside of the set of allowed characters defined by [RFC3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.2):
```
      reserved    = gen-delims / sub-delims
      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```
If a character is neither reserved nor unreserved, it should be percent-encoded.

There's also the WHATWG URL spec that describes [what characters to escape in a URL path](https://url.spec.whatwg.org/#path-percent-encode-set).

Also, look at Node's behavior:
```
> new URL('file:///document/directory/%40%2F中文').href
'file:///document/directory/%40%2F%E4%B8%AD%E6%96%87'
```

Chrome:
```
new URL('file:///document/directory/%40%2F中文').href
'file:///document/directory/%40%2F%E4%B8%AD%E6%96%87'
```

I'm not saying it's necessarily correct to follow the URL API provided by Node and Chrome, but their behavior looks closer to what we want.

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m (hunk 1 above)
Comment (gabrieldonadel) [reply packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: thanks for catching this, fixed

File: apps/native-component-list/src/screens/FileSystemScreen.tsx (hunk 2 above)
Comment (gabrieldonadel) [reply apps/native-component-list/src/screens/FileSystemScreen.tsx:236]: Added a couple more cases to the units tests covering this

**Comment by gabrieldonadel** [comment]
@ide I have updated the code to only encode characters that are outside of the set of allowed characters defined by RFC3986 and added more tests

File: apps/native-component-list/src/screens/FileSystemScreen.tsx [hunk 3]
```diff
@@ -335,6 +352,7 @@ export default class FileSystemScreen extends React.Component<object, State> {
         <ListButton onPress={this._readAsset} title="Read Asset" />
         <ListButton onPress={this._getInfoAsset} title="Get Info Asset" />
         <ListButton onPress={this._copyAndReadAsset} title="Copy and Read Asset" />
+        <ListButton onPress={this._createUTF8Uri} title="Create UTF-8 uri" />
```
Comment (Kudo) [inline apps/native-component-list/src/screens/FileSystemScreen.tsx:355]: would recommend adding the test case in **apps/test-suite/tests/FileSystem.js** rather than NCL if feasible. that would save a little attention cost when doing QA.

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 4]
```diff
@@ -1012,6 +1012,15 @@ - (BOOL)checkIfFileDirExists:(NSString *)path
   return [self _checkIfFileExists:dir];
 }
 
+- (NSURL *)percentEncodeURIString:(NSString *)uri
+{
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:1016]: This method needs documentation, including a reference to the RFC. "Percent-encoding" a string could mean many different things. Our use case is non-obvious.

Additionally, iOS methods that are mostly for producing a value should be named using noun phrases like `URLFromPercentEncodedURIString:`

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m [hunk 5]
```diff
@@ -1012,6 +1012,15 @@ - (BOOL)checkIfFileDirExists:(NSString *)path
...
+  NSMutableCharacterSet *allowedCharacterSet = [NSMutableCharacterSet alphanumericCharacterSet];
+  [allowedCharacterSet addCharactersInString:@"-._~:/?#[]@!$&'()*+,;="];
+  NSString *encodedUriString = [uri stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacterSet];
+
+  return [NSURL URLWithString: [encodedUriString stringByReplacingOccurrencesOfString:@"%25" withString:@"%"]];
```
Comment (ide) [inline packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m:1021]:
```suggestion
  return [NSURL URLWithString:[encodedUriString stringByReplacingOccurrencesOfString:@"%25" withString:@"%"]];
```

**Review by ide — COMMENTED** [review]
One question I have is: what do the file names look like when using NSFileManager (or another API without URLs) to browse the file system? Assuming the NSFileManager API us Unicode-aware, I would like to make sure its representation of file names are not percent-encoded when not using URL-based APIs.

File: apps/native-component-list/src/screens/FileSystemScreen.tsx (hunk 3 above)
Comment (gabrieldonadel) [reply apps/native-component-list/src/screens/FileSystemScreen.tsx]: Sure, I've just moved it to apps/test-suite/tests/FileSystem.js

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m (hunk 5 above)
Comment (gabrieldonadel) [reply packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: fixed

File: packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m (hunk 4 above)
Comment (gabrieldonadel) [reply packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m]: That makes sense, I added doc comments, `nullable` and `nonnull` annotations and renamed the function to `percentEncodedURLFromURIString`

**Comment by gabrieldonadel** [comment]
@ide file names look fine when using NSFileManager, they only include percentages in cases where we explicitly add it, e.g.  `hello%2Fworld.txt`

image

<details>
  <summary>NSFileManager snippet</summary>
  
```
 NSFileManager *fileManager = [NSFileManager defaultManager];
  NSString *directoryPath = @"/Users/gabriel/Library/Developer/CoreSimulator/Devices/F3899241-7036-404B-9A92-899851C0A3F1/data/Containers/Data/Application/C28197A8-793D-41F2-9B82-1BEB3EC555C7/Documents";
  NSArray *files = [fileManager contentsOfDirectoryAtPath:_documentDirectory error:nil];
  for (NSString *fileName in files) {
      NSLog(@"File name: %@", fileName);
  }
```
</details>

**Comment by Kudo** [comment]
@brentvatne once mentioned whether the new encoding design would break existing apps. e.g. a file originally not encoding correctly could be inaccessible after this. could this happen by chance? in this case, could we have some fallback especially at the getters like `getInfoAsync`?

**Comment by ide** [comment]
> @ide file names look fine when using NSFileManager, they only include percentages in cases where we explicitly add it, e.g.  `hello%2Fworld.txt`

It's good to see the characters outside of the ASCII character set are rendering correctly. I am surprised that %2F isn't decoded by the iOS file system APIs, though. Perhaps it's because slashes in file names are problematic and perhaps disallowed.

I have two related follow-up questions: are slashes (%2F) the only character that doesn't get decoded -- if we construct a URI with a path component that contains %20%21%22...%7C%7D%7E, are all the characters other than the slash properly decoded?

And how about this string?

X%E6%BC%A2%E5%AD%97X%F0%9F%A5%B3X%F0%9F%91%A9%F0%9F%8F%BB%E2%80%8D%F0%9F%A4%9D%E2%80%8D%F0%9F%91%A8%F0%9F%8F%BEX

This string decodes to: X漢字X🥳X👩🏻‍🤝‍👨🏾X (X acts as a delimiter that's easy to see).

As for the point Kudo brings up, what strings would be encoded differently because of this PR? I'm not sure I can think of any, except strings that were already failing.

**Comment by gabrieldonadel** [comment]
> @brentvatne once mentioned whether the new encoding design would break existing apps. e.g. a file originally not encoding correctly could be inaccessible after this. could this happen by chance? in this case, could we have some fallback especially at the getters like `getInfoAsync`?

Users were not able to download/create folders using UTF-8 characters like `中文` before this change so this should not affect any existing files.

**Comment by gabrieldonadel** [comment]
> Are slashes (%2F) the only character that doesn't get decoded -- if we construct a URI with a path component that contains %20%21%22...%7C%7D%7E, are all the characters other than the slash properly decoded?

Yes @ide, from my testing all characters other than the slash are decoded.


image

> And how about this string?
X%E6%BC%A2%E5%AD%97X%F0%9F%A5%B3X%F0%9F%91%A9%F0%9F%8F%BB%E2%80%8D%F0%9F%A4%9D%E2%80%8D%F0%9F%91%A8%F0%9F%8F%BEX
> 
> This string decodes to: X漢字X🥳X👩🏻‍🤝‍👨🏾X (X acts as a delimiter that's easy to see).

Creating a file with `FileSystem.documentDirectory + 'X%E6%BC%A2%E5%AD%97X%F0%9F%A5%B3X%F0%9F%91%A9%F0%9F%8F%BB%E2%80%8D%F0%9F%A4%9D%E2%80%8D%F0%9F%91%A8%F0%9F%8F%BEX.zip'` indeed results in `X漢字X🥳X👩🏻‍🤝‍👨🏾X.zip`

**Review by ide — APPROVED** [review]
Thanks for thoroughly testing this! I'm impressed by how well iOS handles Unicode filenames. I feel comfortable merging this in. I'd like someone else to independently review this and confirm it looks good to them, too, though.

**Comment by Kudo** [comment]
> Users were not able to download/create folders using UTF-8 characters like `中文` before this change so this should not affect any existing files.

thanks for confirming that. last thing in this pr: could you investigate the ios unit test ci error, is it related to this pr or not?

**Review by douglowder — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]
Looks good to me 👍 I'll take care of fixing the package to properly build for testing, so feel free to merge.

**Comment by gabrieldonadel** [comment]
> thanks for confirming that. last thing in this pr: could you investigate the ios unit test ci error, is it related to this pr or not?

Yes, the ios unit test ci error is related to this PR, me and @tsapeta are investigating it
