### PR TITLE
[ios][dev-menu] Fix custom actions not triggering after reload

### LINKED ISSUE #36359: [expo-dev-menu] DevMenu items are not responsive after "Reload" (only for newArchEnabled)
### Summary

On the **New Architecture** and **only for iOS**: custom dev menu items registered via `registerDevMenuItems` stop responding after a reload (e.g., after pressing the "Reload" option in DevMenu or by pressing "R" in terminal).

```
import { registerDevMenuItems } from 'expo-dev-menu';

registerDevMenuItems([
  {
    name: 'Test',
    callback: () => {
      // This log is not present when the item is pressed post-reload
      console.log('Test');
    },
  },
]);
```

It works as expected on Android, and also works on both platform if `newArchEnabled: false`

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo: `52.0.46`
expo-dev-client: `5.0.20`

### Environment

```text
Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 4.3.1 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
Managers:
    CocoaPods: 1.16.2 - /Users/michalziolkowski/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
    iOS SDK:
    Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
IDEs:
    Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
npmPackages:
    expo: ^52.0.46 => 52.0.46 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
    react-native: 0.76.9 => 0.76.9 
npmGlobalPackages:
    eas-cli: 16.3.2
Expo Workflow: managed
```

### Reproducible demo

https://github.com/michalziolkowski/expo-dev-menu-issue

### Stacktrace (if a crash is involved)

```text

```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #36359

# How
After a reload, the RCTInstance is null when we try to `enqueueJSCall` on our bridge reference. Instead of doing it this way, we can take the `RCTEventDispatcher` from the module registry and use it directly.

# Test Plan
Bare-expo on new and old arch. Dev menu events are emitted correctly on custom actions.

### CODE REVIEW

File: packages/expo-modules-core/ios/ReactDelegates/ExpoReactDelegate.swift [hunk 1]
```diff
@@ -17,7 +17,7 @@ public class ExpoReactDelegate: NSObject {
     initialProperties: [AnyHashable: Any]?,
     launchOptions: [UIApplication.LaunchOptionsKey: Any]?
   ) -> UIView {
-    return self.handlers.lazy
+    return self.handlers
```
Comment (alanjhughes) [inline packages/expo-modules-core/ios/ReactDelegates/ExpoReactDelegate.swift:20]: This should not be lazy because even though some modules will not return a view, `DevMenu` for example, it still needs to be called to set up it's bridge reference

**Review by lukmccall — APPROVED** [review]
