### PR TITLE
[task-manager][android] Fix the task manager events not being sent to the JS side

### LINKED ISSUE #28959: Location.startLocationUpdatesAsync task callback does not receive any location updates on Android
### Minimal reproducible example

https://github.com/santibernas/expo-issue-28767

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When using Location.startLocationUpdatesAsync to register a TaskManager task the task is registered successfully (verified by TaskManager.getRegisteredTasksAsync) but the callback does not ever get called with location data or even an error on Android.

Here are some Logcat insights.

Initially:
Registered task with name 'LocationTask' for app with scoping identifier 'test.app'.

Thereafter every second:
Handling intent with task name 'LocationTask' and app scoping identifier 'test.app'.
Handling job with task name 'LocationTask' for app with scoping identifier 'test.app'.

After a few minutes (usually less than 15) the app runs out of memory and restarts.

On IOS everything works fine and in SDK 50 with the respective package versions of expo-task-manager and expo-location everything was working on Android as well.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.6.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11709847
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: bare

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### LINKED ISSUE #29021: Expo background fetch isnt working
### Minimal reproducible example

https://github.com/aymanMFD/Monitoring-System.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

This is my task manager define
```js
TaskManager.defineTask('backgroundTask', async () => {
    const now = Date.now();
  
    console.log(`Got background fetch call at date: ${new Date(now).toISOString()}`);
      return BackgroundFetch.BackgroundFetchResult.NewData;
  });
```
And those for registering and unregistering
```js
const toggleBg = async () => {
        
        await BackgroundFetch.registerTaskAsync('backgroundTask', {
            minimumInterval: 0,
            stopOnTerminate: false,
            startOnBoot: true
        }).then(() => {console.log("Registered task")})
        
    }

    const unregister = async () => {
        await BackgroundFetch.unregisterTaskAsync('backgroundTask');
        console.log("Unregistered task!");
    }
```

And these are basic components for testing
```js
            <TouchableOpacity onPress={toggleBg}>
                <Text>Click me</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={unregister}>
                <Text>unregister</Text>
            </TouchableOpacity>
```

Despite registering and checking if the task was well registered, the task doesn't seem to be able to run,

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by behenate**
# Why

Location updates wouldn't get passed to the JS side. Turns out the TaskManager is still using the old EventEmitter which doesn't work in SDK51 on Android

fixes https://github.com/expo/expo/issues/28959
fixes https://github.com/expo/expo/issues/29021

# How

Used a similar workaround to use the new EventEmitter as in `expo-av` and `expo-battery`

# Test Plan

Tested in BareExpo on Android 14 emulator

### CODE REVIEW

File: packages/expo-task-manager/android/src/main/java/expo/modules/taskManager/TaskManagerModule.kt [hunk 1]
```diff
@@ -30,6 +31,25 @@ class TaskManagerModule : Module() {
...
+    OnCreate {
+      // Slightly hacky way to be able to emit events using the new event emitter from legacy modules.
+      val weakModule = WeakReference(this@TaskManagerModule)
+      val emitEvent = { name: String, body: Bundle ->
+        try {
+          // It may throw, because RN event emitter may not be available
+          // we can just ignore those cases
+          weakModule.get()?.sendEvent(name, body)
+        } catch (_: Throwable) {
+        }
```
Comment (lukmccall) [inline packages/expo-task-manager/android/src/main/java/expo/modules/taskManager/TaskManagerModule.kt:43]: Let's log that error. It may be hard to debug that if we suppress that error.

**Review by lukmccall — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by tkrafael** [comment]
How do I get this package version?

**Comment by behenate** [comment]
@tkrafael You will have to wait until we publish a new version, this should be in a few days

**Comment by tkrafael** [comment]
After messing with npm link (which almost made me give up), I did npm pack for following packages:
- expo-modules-core
- expo-task-manager
- expo-background-fetch (idk if that's necessary)
- expo
installed locally (yarn add ../package-outputs/{package}-{version}.tgz)
and ran my application and it worked as expected:

```
05-27 11:17:47.209 17942 18060 I ReactNativeJS: run task modafoca
05-27 11:18:47.197 17942 18060 I ReactNativeJS: run task modafoca
05-27 11:19:47.197 17942 18060 I ReactNativeJS: run task modafoca
05-27 11:20:47.193 17942 18060 I ReactNativeJS: run task modafoca
 
```
Just like to thank you guys for the fixes and to help maintain this amazing library.
I'll go through issues related with "backgroun task not working" and let them know this will be fixed in next days.

**Comment by Beckmann0o** [comment]
> Después de jugar con el enlace npm (que casi me hace darme por vencido), hice npm pack para los siguientes paquetes:
> 
> * expo-modules-core
> * expo-task-manager
> * expo-background-fetch (idk si es necesario)
> * expo
> * unimodules-app-loader
> * expo-task-manager instalado localmente (yarn add .. /package-outputs/{package}-{version}.tgz) y ejecuté mi aplicación y funcionó como se esperaba:
> 
> ```
> 05-27 11:17:47.209 17942 18060 I ReactNativeJS: run task modafoca
> 05-27 11:18:47.197 17942 18060 I ReactNativeJS: run task modafoca
> 05-27 11:19:47.197 17942 18060 I ReactNativeJS: run task modafoca
> 05-27 11:20:47.193 17942 18060 I ReactNativeJS: run task modafoca
>  
> ```
> 
> Me gustaría agradecerles por las correcciones y por ayudar a mantener esta increíble biblioteca. Revisaré los problemas relacionados con "la tarea de backgroun no funciona" y les haré saber que esto se solucionará en los próximos días.

Could you let us know here when it is solved? Since I don't understand where to see that the problem was corrected.

**Comment by aymanMFD** [comment]
Yea that would be great!

**Comment by tkrafael** [comment]
tested with latest version, working correctly:
``` 
"expo": "51.0.9",
"expo-background-fetch": "12.0.1",
"expo-task-manager": "11.8.2",
"expo-modules-core": "1.12.12",
"unimodules-app-loader": "4.6.0"
```

**Comment by lnguz** [comment]
@tkrafael what environment did you test in? I used the same libraries and it doesn't work on my localhost, the function defined in TaskManager still doesn't trigger

**Comment by tkrafael** [comment]
@lnguz I don't need expo-location, just use task manager to run expensive and slow tasks in background.
I run the tests in android emulator and a real device, both are calling registered tasks.

Can you provide a logcat from running up so I can help?
`adb logcat |grep "NAME_OF_YOUR_DEFINED_TASK"`
Be aware the task will run only when display is turned off or when user opens another app

**Comment by Hosam-hsm** [comment]
@tkrafael  Is it working for you in iOS?

**Comment by tkrafael** [comment]
Don't have iOS to test.
Also i think your code might not work due to the alert function call.
I'm assuming alert needs a UI context, which you don't have when running background tasks.

**Comment by tkrafael** [comment]
In the docs it is explained that background tasks work a bit different on ios. There's a minimal interval, which I think is 15 min

**Comment by Hosam-hsm** [comment]
@tkrafael Thanks for replying. My actual need is to run a function which upload multiple files as chunks to S3. What I understood from your reply is that my function will only run after 15 mins in iOS. Is it possible to run this function in background after triggering it without the delay? I cannot use the background mode provided by the expo-file-system since I'm using chunk upload method which requires to run some other JS functions in background after one upload completes.

**Comment by tkrafael** [comment]
> @tkrafael Thanks for replying. My actual need is to run a function which upload multiple files as chunks to S3. What I understood from your reply is that my function will only run after 15 mins in iOS. Is it possible to run this function in background after triggering it without the delay? I cannot use the background mode provided by the expo-file-system since I'm using chunk upload method which requires to run some other JS functions in background after one upload completes.

I'm not a specialist in frontend dev, but I understood that's a feature/limitation in ios.

You can use a foreground mechanism that runs code outside of app screen, but it will be limited to run only when user is using the app
