### PR TITLE
[ui][iOS] - Make `RNHostView` SwiftUI view

### LINKED ISSUE #43537: [SDK 55] Expo UI menu with glass button + native view freezes app on iOS
### Minimal reproducible example

https://github.com/iankberry/expo-ui-menu-hostview-repro

### Steps to reproduce

1. Checkout the above repo
2. Run `yarn ios`
3. The app will freeze on launch (or if you try switching tabs)

I'll explain the issue in a bit more detail since it requires several conditions to be met.

I'm using the `react-navigation` library (not sure if the issue is present in `expo-router`). I have an Expo UI `Menu` component that lives on each screen. This menu contains a glass style `Button` as its label, which contains a RN native view (because I need to render a custom image). When an `animation` param is specified in the tab navigator, the app will completely freeze when rendering the UI. In my app, it renders the initial screen and freezes when switching tabs while in the demo app it freezes on launch. So it might be timing related.

If you remove the `animation` param OR remove the glass `buttonStyle` from the `Button` component, the issue is no longer present.

### Environment

```text
expo-env-info 2.0.11 environment info:
    System:
      OS: macOS 15.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 24.10.0 - ~/.nvm/versions/node/v24.10.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v24.10.0/bin/yarn
      npm: 11.6.1 - ~/.nvm/versions/node/v24.10.0/bin/npm
      Watchman: 2025.06.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/iberry/.gem/ruby/3.4.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
    IDEs:
      Android Studio: 2025.2 AI-252.27397.103.2522.14514259
      Xcode: 26.3/17C529 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~55.0.4 => 55.0.4
      react: 19.2.0 => 19.2.0
      react-native: 0.83.2 => 0.83.2
    npmGlobalPackages:
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
iberry@Ians-MacBook-Pro-4 expo-ui-repro % npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.18.10
Ok to proceed? (y) y

17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Why

- Simplifies current RNHostView implementation and matches the approach with the Android [version](https://github.com/expo/expo/pull/43495)
- As a side effect, it also fixes https://github.com/expo/expo/issues/43537

# How

Make `RNHostView` SwiftUI view instead of regular Expo View. Use bounds kvo instead of using `layoutSubviews` to get the updated bounds from yoga.

# Test Plan

Tested all the `RNHostView` examples from NCL.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-modules-core/ios/Core/Views/SwiftUI/SwiftUIHostingView.swift [hunk 1]
```diff
@@ -70,7 +70,7 @@ extension ExpoSwiftUI {
      */
     init(viewType: ContentView.Type, props: Props, appContext: AppContext) {
       self.contentView = ContentView(props: props)
-      let rootView = AnyView(contentView.environmentObject(shadowNodeProxy))
+      let rootView = AnyView(contentView)
```
Comment (Kudo) [inline packages/expo-modules-core/ios/Core/Views/SwiftUI/SwiftUIHostingView.swift:73]: [🏗️ **design**] Removing `.environmentObject(shadowNodeProxy)` is a breaking change for any SwiftUI view in the `WithHostingView` path that reads `@EnvironmentObject var shadowNodeProxy: ExpoSwiftUI.ShadowNodeProxy`. The only in-repo consumer (`GeometryChangeModifier` in `HostView.swift`) is migrated to `props.shadowNodeProxy`, but third-party expo modules using this pattern would crash at runtime with a missing environment object error.

Is `ShadowNodeProxy` considered internal/unstable API, or should this be documented as a breaking change with migration guidance (use `props.shadowNodeProxy` instead)?

File: packages/expo-ui/ios/RNHostView.swift [hunk 2]
```diff
@@ -1,21 +1,102 @@
...
+  
+  @ObservedObject var props: RNHostViewProps
+
+  var body: some View {
+    if props.matchContents, let childUIView = firstChildUIView {
+      ApplySizeFromYogaNode(childUIView: childUIView) {
+        Children()
+      }
+      .onAppear {
+        ExpoUITouchHandlerHelper.createAndAttachTouchHandler(for: childUIView)
```
Comment (Kudo) [inline packages/expo-ui/ios/RNHostView.swift:20]: [💡 suggestion] Touch handler attachment moved from `init` (old UIKit code) to `.onAppear`. This means touches won't be handled during the brief window between view creation and appearance. Also, `onAppear` can fire multiple times in SwiftUI (e.g., when a view is reinserted into the hierarchy). `ExpoUITouchHandlerHelper` already guards against duplicate attachment, so the duplicate call is fine, but worth noting the timing shift.

Is there a scenario where the child UIView needs touch handling before the SwiftUI `onAppear` fires?

File: packages/expo-modules-core/ios/Core/Views/SwiftUI/SwiftUIHostingView.swift (hunk 1 above)
Comment (Kudo) [reply packages/expo-modules-core/ios/Core/Views/SwiftUI/SwiftUIHostingView.swift:73]: search from https://github.com/search?type=code&q=%2F%40EnvironmentObject.*shadowNodeProxy%2F and all expo code there. seems fine to ship the breaking change

**Review by Kudo — APPROVED** [review]

File: packages/expo-ui/ios/RNHostView.swift (hunk 2 above)
Comment (intergalacticspacehighway) [reply packages/expo-ui/ios/RNHostView.swift:20]: yeah before it was attaching the handler on `RNViewHost` itself in `init` because it was UIView, but now it attaches on the child which won't be present on init.

> Is there a scenario where the child UIView needs touch handling before the SwiftUI onAppear fires?

i don't think so because any touch interaction would require view to have appeared on screen 🤔.
