### PR TITLE
[eslint-config] bump dependencies and minimum required lint tools versions

### LINKED ISSUE #14124: lint warns of unsupported TypeScript version
### Summary

Running `npm run lint` in any modules complains about a non supported TypeScript version.
Will be due to the update from #14015

It'll need something like the following and the updated yarn.lock but I wasn't sure if anything else needs updating?

```diff
diff --git a/packages/eslint-config-universe/package.json b/packages/eslint-config-universe/package.json
index b998ffc63b..eacdb82f07 100644
--- a/packages/eslint-config-universe/package.json
+++ b/packages/eslint-config-universe/package.json
@@ -43,8 +43,8 @@
   "dependencies": {
     "@babel/eslint-parser": "^7.11.5",
     "@babel/eslint-plugin": "^7.11.5",
-    "@typescript-eslint/eslint-plugin": "^4.12.0",
-    "@typescript-eslint/parser": "^4.12.0",
+    "@typescript-eslint/eslint-plugin": "^4.29.0",
+    "@typescript-eslint/parser": "^4.29.0",
     "eslint-config-prettier": "^6.11.0",
     "eslint-plugin-import": "^2.22.0",
     "eslint-plugin-prettier": "^3.1.4",
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

_No response_

### Environment

  ```
Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 30, 31
        Build Tools: 26.0.3, 29.0.2, 31.0.0
        System Images: android-22 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

```shell
$ npm run lint

> expo-image-manipulator@9.2.0 lint /Users/mnightingale/personal/expo/packages/expo-image-manipulator
> expo-module lint

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.2.0

YOUR TYPESCRIPT VERSION: 4.3.5

Please only submit bug reports when using the officially supported version.

=============
```

### PR DESCRIPTION
**Pull request by Simek**
# Why

It would be nice to keep development dependencies like ESLint or Prettier aligned in the whole workspace. 

It was also a nice opportunity to try bump `eslint-config` dependencies to the latest version.

# How

This PR bumps most of `eslint-config` dependencies and most of (if not all) entires of ESLint or Prettier in workspace or detached packages.

# Test Plan

I have run the `lint` command in few packages and docs, but for some reason the main `yarn lint` command run from workspace root never ends on my machine (so I was not able to fix any formatting issues that might appear after the bumps). I hope that CI will help me to investigate the root command issue.

### CODE REVIEW

**Comment by Simek** [comment]
To fix the Prettier conflicting rules test I had to refactor the code according to the `eslint-config-prettier` readme and legacy note:
* https://github.com/prettier/eslint-config-prettier#cli-helper-tool

I have print the result from the conflict check to be sure that after refactor code is working correctly, there is an output:

```
{
  pid: 33535,
  output: [
    '',
    'No rules that are unnecessary or conflict with Prettier were found.\n'
  ],
  stdout: '',
  stderr: 'No rules that are unnecessary or conflict with Prettier were found.\n',
  status: 0,
  signal: null
}
```

**Comment by Simek** [comment]
I have decided to bump the minimal required version of ESLint because new Prettier plugin requires that (https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-700-2020-12-05). From the users perspective this should not be preserved as rushed, since first stable version of ESLint 7 has been released more than year ago. Same reasoning applies to Prettier requirement bump, the fist stable 2.x version was released Q1 2020.

File: packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js [hunk 1]
```diff
@@ -7,17 +7,7 @@ module.exports = async function checkPrettierRulesAsync(configFile) {
...
-    ['--config', configFile, '--no-eslintrc', '--print-config', configFile],
-    { env }
-  );
-
-  const resultPromise = spawnAsync('eslint-config-prettier-check', [], { env });
-  const { child } = resultPromise;
-  child.stdin.setEncoding('utf8');
-  child.stdin.write(configString);
-  child.stdin.end();
+  const resultPromise = spawnAsync('eslint-config-prettier', [configFile], { env });
```
Comment (ide) [inline packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: This doesn't test `configFile` -- it tests the linter config that would have been applied to `configFile` is correct, which does two undesirable things: it loads `.eslintrc.js` and it computes the config for `configFile` specifically instead of checking the generic config.

One way to test this is to put `rules: { 'no-mixed-operators': 'error' }` inside of `web.js`. The tests should fail. 

Similarly, if `'no-mixed-operators': 'error'` is added to `node.js`, only the node test should fail and the other configurations should succeed.

I am not convinced this is possible with the new `eslint-config-prettier` script and may require more work.

**Review by ide — CHANGES_REQUESTED** [review]

File: packages/eslint-config-universe/shared/prettier.js [hunk 2]
```diff
@@ -1,7 +1,12 @@
...
-  extends: ['prettier', 'prettier/@typescript-eslint', 'prettier/babel', 'prettier/react'],
+  extends: ['prettier'],
   plugins: ['prettier'],
   rules: {
-    'prettier/prettier': ['warn'],
+    'prettier/prettier': [
+      'warn',
+      {
+        arrowParens: 'avoid',
+      },
```
[the remark this answers is not in the document]
Comment (Simek) [reply packages/eslint-config-universe/shared/prettier.js:9]: If you want to remove this setting I can remove this even now, but it would result in ~300 format warnings in the workspace, my goal was to mimic the current setup as much as possible to reduce the number of format changes after migration.

[the remark this answers is not in the document]
Comment (ide) [reply packages/eslint-config-universe/shared/prettier.js:9]: yea another commit

File: packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js (hunk 1 above)
Comment (Simek) [reply packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: Thank you for the hint, I will try to reproduce recommended fails locally and will be back with results. 🙂

Comment (Simek) [reply packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: If I put `'no-mixed-operators': 'error'` in `node.js` all 4 tests are failing:
Screenshot 2021-08-03 at 12 50 29

If I put `rules: { 'no-mixed-operators': 'error' }` in `web.js` all tests are successful.

File: packages/eslint-config-universe/shared/prettier.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (Simek) [reply packages/eslint-config-universe/shared/prettier.js]: I'm not sure if I like the enforcement of parenthesis everywhere, what do you think about that formatting rule after looking at the changes?

Maybe this Prettier option should be retained and placed within other Prettier config entries in `.prettierrc` (https://github.com/expo/expo/blob/master/packages/eslint-config-universe/.prettierrc)?

File: packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js (hunk 1 above)
Comment (ide) [reply packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: The tests were checking that the configs don't include rules that conflict with the ESLint Prettier config's rules.

The result you see above is what we want to avoid. The desired behavior is:
* When you add `'no-mixed-operators': 'error'` to node.js, only the `node.js` test should fail and the rest should succeed.
* When you add `'no-mixed-operators': 'error'` to web.js, only the `web.js` test should fail and the rest should succeed.

File: packages/eslint-config-universe/shared/prettier.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (ide) [reply packages/eslint-config-universe/shared/prettier.js]: We use the parentheses in our other codebases and plan to do so here but because of how much code it changes, a separate commit (and therefore separate PR) will be easier to read.

File: packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js (hunk 1 above)
Comment (Simek) [reply packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: I can understand what should happen, but I'm not understanding why the tests fails in way they does.

I have looked at several resources and the refactor I have made looks like the correct way to update previous `eslint-config-prettier-check` setup:
* https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-700-2020-12-05

However, I can see the same results by running `eslint-config-prettier` directly from terminal on the config files (change to one file, results in error when checking all configs):
```sh
eslint-config-prettier ./node.js
# or even
npx eslint-config-prettier ./node.js
```

According to the changelog, instead of using stout from `eslint --print-config` they are using now new ESLint API to resolve config file, so maybe the way in which ESLint resolves config parts changed or there is a bug/quirk within this API which results in this behaviour. But still that are just the blind shots, because unfortunately I was not able to crack this problem.

Comment (ide) [reply packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: The intent of the old test was to validate each config.

As I understand it, `eslint-config-prettier <file>` now validates the config for `<file>`. We do not want to validate the linter config for `node.js` (that is, the config specified in .eslintrc.js, which is unrelated to this test). We want to validate the linter config exported from `node.js`.

I am not convinced that there is an obvious path forward using the scripts that eslint-config-prettier provides. It may require careful thinking to implement the desired behavior sustainably.

Comment (ide) [reply packages/eslint-config-universe/__tests__/tools/checkPrettierRulesAsync.js:10]: The migration steps to which you linked aren't directly applicable. In the old test code, the key is that we pass in `'--config', configFile`.

**Review by bbarthec — COMMENTED** [review]
@simek, I believe this PR is good idea, but the amount of changes are simply too big to process it smoothly 😅 What would you say about splitting this PR into two separate ones:
- first with config changes, dependencies updates
- second with the effect of running `lint/prettier fix` commands? 🤔

**Comment by Simek** [comment]
@bbarthec Yup, I can see that, that's way in the first iteration I have decided to add `arrowParens` to the Prettier config, to reduce the amount of lint changes to bare minimum, but I was asked in the review later to remove this config option.

Also there is still a problem with config test, which at this point, after refactor of time did not cover the previous cases, which also holds this PR.

I will try to split this PR somehow to smaller chunks and I will try to fix the test issue, however it will be my second attempt to fix this and I cannot guarantee success at this point of time. 😉

File: packages/eslint-config-universe/shared/prettier.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (Simek) [reply packages/eslint-config-universe/shared/prettier.js:9]: To reduce the PR changeset size I have decided to revert PR to the state before `arrowParens` removal. 

The parenthesis reformat and new config option removal will be posted in the separate PR, if I will be able to fix the issues in this PR and got it merged.

**Comment by Simek** [comment]
@ide It looks like I was able to stabilize the PR, reduce the changeset to minimum and get rid of all the CI issues. 

What do you think about merging this PR in like that, and in upcoming two separate PR I will try to address remining tasks:
* research more into the config conflict test and try to mimic the situation you have described in the comments in there (it would be nice if you can add the test, which by design should fail, but it succeeded after the update, this would definitely help me)
* remove `arrowParens` from the config and reformat the whole code base again

What do you think about that?

**Comment by ide** [comment]
Please fix the test first so we don't regress. Working on the test cases is not currently a priority for me so if you actively would like to land this, you or someone else will need to update the tests.

As we discussed, make the change to require the arrowParens but in another PR to keep this one simpler.

**Review by ide — CHANGES_REQUESTED** [review]
The test projects are a good idea. They can be committed to Git in a simpler and compatible way.

**Review by ide — APPROVED** [review]

**Review by EvanBacon — APPROVED** [review]
looks fine
