### PR TITLE
[video][android] Refactor Picture in Picture to support multiple VideoViews

### LINKED ISSUE #40157: [expo-video][android] Crash resuming app from PiP
### Minimal reproducible example

https://snack.expo.dev/@gnarbucks/expo-video-pip-issue

### Steps to reproduce

Here is a [snack](https://snack.expo.dev/@gnarbucks/expo-video-pip-issue) that shows how to reproduce the issue and can be repro'd in that environment there on android.

Steps to repro the crash on android (crash 1):
1. Have more than one `VideoView` mounted, each with their own player instance
2. Minimize/background while one of the videos has `allowsPictureInPicture` and `startsPictureInPictureAutomatically`
3. The PiP will start - if you try to resume the app from the PiP UI it will crash

You can also get a crash to occur if you have unmounted a previous `VideoView` and do steps 2 and 3 above (crash 2).

Here is the stack trace for both of these crashes:

<details>

<summary>Crash 1</summary>

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5256)
    at android.view.ViewGroup.addView(ViewGroup.java:5085)
    at android.view.ViewGroup.addView(ViewGroup.java:5025)
    at android.view.ViewGroup.addView(ViewGroup.java:4997)
    at expo.modules.video.VideoView.layoutForPiPExit(VideoView.kt:254)
    at expo.modules.video.PictureInPictureHelperFragment.onPictureInPictureModeChanged(PictureInPictureHelperFragment.kt:40)
    at androidx.fragment.app.Fragment.performPictureInPictureModeChanged(Fragment.java:3242)
    at androidx.fragment.app.FragmentManager.dispatchPictureInPictureModeChanged(FragmentManager.java:3357)
    at androidx.fragment.app.FragmentManager.lambda$new$3$androidx-fragment-app-FragmentManager(FragmentManager.java:624)
    at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda3.accept(D8$$SyntheticClass:0)
    at androidx.activity.ComponentActivity.onPictureInPictureModeChanged(ComponentActivity.kt:970)
    at android.app.Activity.dispatchPictureInPictureModeChanged(Activity.java:9328)
    at android.app.ActivityThread.handleWindowingModeChangeIfNeeded(ActivityThread.java:6619)
    at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6404)
    at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6379)
    at android.app.ActivityThread.handleActivityConfigurationChangedInner(ActivityThread.java:6830)
    at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6777)
    at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6749)
    at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8705)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

</details>

<details>

<summary>Crash 2</summary>

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
    at java.util.Objects.checkIndex(Objects.java:359)
    at java.util.ArrayList.get(ArrayList.java:434)
    at expo.modules.video.VideoView.layoutForPiPExit(VideoView.kt:248)
    at expo.modules.video.PictureInPictureHelperFragment.onPictureInPictureModeChanged(PictureInPictureHelperFragment.kt:31)
    at androidx.fragment.app.Fragment.performPictureInPictureModeChanged(Fragment.java:3242)
    at androidx.fragment.app.FragmentManager.dispatchPictureInPictureModeChanged(FragmentManager.java:3357)
    at androidx.fragment.app.FragmentManager.lambda$new$3$androidx-fragment-app-FragmentManager(FragmentManager.java:624)
    at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda3.accept(D8$$SyntheticClass:0)
    at androidx.activity.ComponentActivity.onPictureInPictureModeChanged(ComponentActivity.kt:970)
    at android.app.Activity.dispatchPictureInPictureModeChanged(Activity.java:9328)
    at android.app.ActivityThread.handleWindowingModeChangeIfNeeded(ActivityThread.java:6619)
    at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6404)
    at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6379)
    at android.app.ActivityThread.handleActivityConfigurationChangedInner(ActivityThread.java:6830)
    at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6777)
    at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6749)
    at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8705)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

</details>

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 4.5.1 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/rmartin/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2024.3 AI-243.25659.59.2432.13423653
      Xcode: 26.0/17A324 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.17 => 53.0.17 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.4 => 0.79.4 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
N/A
```

### PR DESCRIPTION
**Pull request by behenate**
# Why

Fixes https://github.com/expo/expo/issues/40157

Originally this was supposed to be just a fix for https://github.com/expo/expo/issues/40157, but it turned out that having more than one `VideoView` mounted is tricky and requires a lot more changes.

# How

Support for multiple video views requires knowledge of all view PiP states etc.  I added `PictureInPictureManager` which contains pretty much all of PiP logic. 

The new manager reduces the amount of PiP code inside `VideoView`. Now the `VideoViews` only declare whether they auto enter PiP and emit events when a PiP parameters have changed. 

# Test Plan

Tested in Bare Expo on Android

### CODE REVIEW

**Comment by behenate** [comment]
I feel like this still needs some work, so I marked is as a draft

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoManagerListener.kt [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+import expo.modules.video.VideoView
+
+// TODO: Add more as needed
+interface VideoManagerListener {
+  fun onVideoViewRegistered(videoView: VideoView, allVideoViews: Collection<VideoView>) {}
+  fun onVideoViewUnregistered(videoView: VideoView, allVideoViews: Collection<VideoView>) {}
+  fun onAppBackgrounded() {}
+  fun onAppForegrounded() {}
+}
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoManagerListener.kt]:
```suggestion
}

```

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoManagerListener.kt [hunk 2]
```diff
@@ -0,0 +1,11 @@
+package expo.modules.video.listeners
+
+import expo.modules.video.VideoView
+
+// TODO: Add more as needed
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoManagerListener.kt]:
```suggestion
```

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoPlayerListener.kt [hunk 3]
```diff
@@ -31,4 +32,4 @@ interface VideoPlayerListener {
   fun onVideoSourceLoaded(player: VideoPlayer, videoSource: VideoSource?, duration: Double?, availableVideoTracks: List<VideoTrack>, availableSubtitleTracks: List<SubtitleTrack>, availableAudioTracks: List<AudioTrack>) {}
   fun onTargetViewChanged(player: VideoPlayer, newTargetView: VideoView?, oldTargetView: VideoView?) {}
   fun onRenderedFirstFrame(player: VideoPlayer) {}
-}
+}
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoPlayerListener.kt]:
```suggestion
}

```

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+import expo.modules.video.records.PiPParams
+
+interface VideoViewListener {
+  /**
+   * Called when the ability of the view to autoEnterPip has changed.
+   * Note: This can be called when `autoEnterPiP` doesn't change, but other factors
+   * influence the view's ability to enter PiP.
+   */
+  fun onPiPParamsChanged(videoView: VideoView, oldPiPParams: PiPParams, newPiPParams: PiPParams) {}
+}
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt]:
```suggestion
}

```

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt [hunk 5]
```diff
@@ -0,0 +1,13 @@
+package expo.modules.video.listeners
+
+import expo.modules.video.VideoView
+import expo.modules.video.records.PiPParams
+
+interface VideoViewListener {
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt:6]:
```suggestion
fun interface VideoViewListener {
```

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt [hunk 6]
```diff
@@ -0,0 +1,13 @@
...
+  /**
+   * Called when the ability of the view to autoEnterPip has changed.
+   * Note: This can be called when `autoEnterPiP` doesn't change, but other factors
+   * influence the view's ability to enter PiP.
+   */
+  fun onPiPParamsChanged(videoView: VideoView, oldPiPParams: PiPParams, newPiPParams: PiPParams) {}
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt]:
```suggestion
  fun onPiPParamsChanged(videoView: VideoView, oldPiPParams: PiPParams, newPiPParams: PiPParams) = Unit
```
Do we need the default implementation here?

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt [hunk 7]
```diff
@@ -0,0 +1,329 @@
...
+  private val appContext = WeakReference(appContext)
+  private val mainActivity = WeakReference(appContext.currentActivity)
+
+  var autoEnterPiP = false
+    private set
+
+  var isInPiP = false
+    private set
+
+  var currentPiPViewCandidate: WeakReference<VideoView?> = WeakReference(null)
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]:
```suggestion
  var currentPiPViewCandidate = WeakReference<VideoView>(null)
```

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt [hunk 8]
```diff
@@ -0,0 +1,329 @@
...
+    private set
+
+  private var pipHelperFragment: PictureInPictureHelperFragment? = null
+  private val videoViews = mutableListOf<WeakReference<VideoView>>()
+  private val strongVideoViews
+    get() = videoViews.mapNotNull { it.get() }
+  private val rootViewChildrenOriginalVisibility: MutableMap<Int, Int> = mutableMapOf()
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]:
```suggestion
  private val rootViewChildrenOriginalVisibility = mutableMapOf<Int, Int>()
```

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt [hunk 9]
```diff
@@ -0,0 +1,329 @@
...
+
+    strongVideoViews.forEach {
+      it.onStartPictureInPicture(candidate)
+    }
+
+    isInPiP = true
+  }
+
+  override fun onPictureInPictureStop() {
+    if (mainActivity.get() == null) {
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]: We're checking if we have a reference to the main activity, but should we check the `isInPip` instead?

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt [hunk 10]
```diff
@@ -0,0 +1,329 @@
...
+    val relevanceOrderedViews = listOf(visiblePlayingPipViews, playingPipViews, visiblePiPView, pipViews).flatten()
+
+    return relevanceOrderedViews.firstOrNull()
+  }
+
+  private fun maybeWarnAboutAutoEnterViews() {
+    val pipViews = strongVideoViews.filter { it.autoEnterPiP }
+
+    // Ideally we want users to have only one view with `startsPictureInPictureAutomatically`, if multiple exist we try to elect one that makes the most sense.
+    // We can only do the election **during** picture in picture transition, therefore we can't set the rectHint for the transition. That's why we show the warning.
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]:
```suggestion
    // Ideally, we want users to have only one view with `startsPictureInPictureAutomatically`, if multiple exist, we try to elect one that makes the most sense.
    // We can only do the election **during** picture in picture transition, therefore we can't set the rectHint for the transition. That's why we show the warning.
```

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt [hunk 11]
```diff
@@ -0,0 +1,329 @@
...
+        "expo-video: Detected multiple `VideoViews` with `startsPictureInPictureAutomatically` set to `true`" +
+          "while entering picture in picture. To ensure no visual issues when auto-entering PiP, make sure that there is only " +
+          "one active `VideoView` with that property."
+      )
+    }
+  }
+
+  /**
+   * For optimal picture in picture experience it's best to only have one view. This method
+   * hides all children of the root view and makes the player the only visible child of the rootView.
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]:
```suggestion
   * For an optimal picture in picture experience, it's best to only have one view. This method
   * hides all children of the root view and makes the player the only visible child of the rootView.
```

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt [hunk 12]
```diff
@@ -0,0 +1,329 @@
...
+    }
+
+    videoViews.clear()
+    removePiPHelperFragment()
+    isReleased = true
+  }
+
+  /**
+   * Updates whether the main activity will auto-enter Pictrue in Picture, elects a new PiP candidate
+   * and refreshes PiP parameters such as the rectHint.
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]:
```suggestion
   * Updates whether the main activity will auto-enter Picture in Picture, elects a new PiP candidate
   * and refreshes PiP parameters such as the rectHint.
```

File: packages/expo-video/android/src/main/java/expo/modules/video/utils/ViewVisibilityUtils.kt [hunk 13]
```diff
@@ -0,0 +1,28 @@
+package expo.modules.video.utils
+
+import android.graphics.Rect
+import android.view.View
+
+internal fun View.isVisibleOnScreen(): Boolean {
+  val visibleRect = Rect()
+  val isVisible = this.getGlobalVisibleRect(visibleRect)
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/utils/ViewVisibilityUtils.kt]:
```suggestion
  val isVisible = getGlobalVisibleRect(visibleRect)
```

File: packages/expo-video/android/src/main/java/expo/modules/video/utils/ViewVisibilityUtils.kt [hunk 14]
```diff
@@ -0,0 +1,28 @@
...
+  return isVisible
+}
+
+internal fun View.visiblePercentage(): Float {
+  val visibleRect = Rect()
+  if (!this.getGlobalVisibleRect(visibleRect)) {
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/utils/ViewVisibilityUtils.kt]:
```suggestion
  if (!getGlobalVisibleRect(visibleRect)) {
```

File: packages/expo-video/android/src/main/java/expo/modules/video/utils/ViewVisibilityUtils.kt [hunk 15]
```diff
@@ -0,0 +1,28 @@
...
+    return 0f
+  }
+
+  val visibleArea = visibleRect.height() * visibleRect.width()
+  val totalArea = this.height * this.width
```
Comment (lukmccall) [inline packages/expo-video/android/src/main/java/expo/modules/video/utils/ViewVisibilityUtils.kt]:
```suggestion
  val totalArea = height * width
```

File: packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt (hunk 6 above)
Comment (behenate) [reply packages/expo-video/android/src/main/java/expo/modules/video/listeners/VideoViewListener.kt]: Not really since it's the only method for now, but when we add more we'll need default implementations

File: packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt (hunk 9 above)
Comment (behenate) [reply packages/expo-video/android/src/main/java/expo/modules/video/managers/PictureInPictureManager.kt]: You are right, it's a leftover from development when onPictureInPictureStop contained code from layoutForPiPExit

**Review by lukmccall — APPROVED** [review]
