### PR TITLE
[ui][Android] Fix DateTimePicker crashes on Android

### LINKED ISSUE #39424: Expo UI DateTimePicker Crashes on Android on Expo 54
### Minimal reproducible example

https://github.com/billdybas/expo-ui-date-time-picker-android-crash

### Steps to reproduce

1. `npm install`
1. `npm run android`
1. Open the app on a physical Android device. The component will not render and will error with this message:

```
ERROR  Cannot set prop 'initialDate' on view 'class expo.modules.ui.DateTimePickerView'
→ Caused by: Cannot find type converter for 'java.util.Date?'. Make sure the class implements `expo.modules.kotlin.records.Record` (i.e. `class MyObj : Record`).
```

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.13.0 - ~/.volta/tools/image/node/22.13.0/bin/node
      Yarn: 4.5.2 - ~/.volta/tools/image/yarn/4.5.2/bin/yarn
      npm: 10.9.2 - ~/.volta/tools/image/node/22.13.0/bin/npm
      Watchman: 2025.04.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Android Studio: 2024.3 AI-243.24978.46.2431.13208083
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.0-preview.15 => 54.0.0-preview.15 
      expo-router: ~6.0.0-preview.15 => 6.0.0-preview.15 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.1 => 0.81.1 
      react-native-web: ~0.21.0 => 0.21.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by hryhoriiK97**
# Why

The DateTimePicker component has error on Android because it tried to use java.util.Date? as a prop type, but Expo modules don't have a built-in type converter for Date objects.

Zrzut ekranu 2025-09-16 o 16 24 21

Fixes: #39424

# How

The fix changes the Android implementation to use Long? timestamps instead, with TypeScript converting ISO strings to timestamps automatically. The onDateSelected callback already returns timestamps (Long?) via DatePickerResult, so this approach maintains consistency throughout the component's data flow.

# Test Plan

It would be enough to visit DateTimePickerScreen on Android and check that the error logs disappeared.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by aleqsio — APPROVED** [review]
LGTM

File: packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx [hunk 1]
```diff
@@ -51,15 +51,19 @@ export type DateTimePickerProps = {
   modifiers?: ExpoModifier[];
 };
 
-type NativeDatePickerProps = Omit<DateTimePickerProps, 'variant' | 'onDateSelected'> & {
+type NativeDatePickerProps = Omit<
+  DateTimePickerProps,
+  'variant' | 'onDateSelected' | 'initialDate'
+> & {
   variant?: AndroidVariant;
+  initialDate?: number | null;
```
Comment (intergalacticspacehighway) [inline packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx:59]: nit: wyt of accepting type as Date instead of number as it is named initialDate? 🤔

**Review by intergalacticspacehighway — APPROVED** [review]

File: packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx (hunk 1 above)
Comment (intergalacticspacehighway) [reply packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx:59]: @hryhoriiK97 can we rename it to initialDateTimestamp since it is a number type? we can avoid the conversion again [here](https://github.com/expo/expo/pull/39718/files#diff-afb36f1d9e4dd8ee26190f38e8b97916968d4e818fc08bac6533423ea674e11aR78)

Comment (hryhoriiK97) [reply packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx:59]: @intergalacticspacehighway It looks like [onDateSelected](https://github.com/expo/expo/blob/f7d4a368f5a57c1f8e1e730da5ce14add8d1164a/packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx#L83) returns a Date object in the callback 🤔 That’s why I added this conversion. Shouldn’t we also return a timestamp in the callback for consistency? cc: @aleqsio

Comment (intergalacticspacehighway) [reply packages/expo-ui/src/jetpack-compose/DatePicker/index.tsx:59]: sorry my bad. i didn't know we already had `initialDate` 🤦. Let's keep the API as it is for now!
