### PR TITLE
[cli] Filter architectures to valid values only

### LINKED ISSUE #28541: Android build after Upgrade SDK 50 to 51.0.0-preview.8 fails with [CXX1201] ABIs [armeabi] are not supported for platform
### Minimal reproducible example

https://github.com/killerchip/vanilla-sdk-50

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

- I created an vanilla repo with `npx create-expo-app@latest --template` and chose Basic Typescript template.
- run with `npx expo run:android` to confirm working OK on physical device
- upgraded with `npm install expo@next` and `npx expo install --fix`
- run with `npm run android` (with physical device connected)

Build fails with the following:

```
* Where:
Script '****/vanilla-sdk-50/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 408

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > com.android.builder.errors.EvalIssueException: [CXX1201] ABIs [armeabi] are not supported for platform. Supported ABIs are [arm64-v8a, armeabi-v7a, x86, x86_64].
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 30, 31, 33, 33, 34
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-26 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86_64 Atom, android-34 | Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0-preview.8 => 51.0.0-preview.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.0 => 0.74.0 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #28541

# How
Older android devices may return deprecated architectures causing build errors. We should filter these out. It's fine if the returned string ends up empty as we won't add the architecture argument it in that case.

# Test Plan
I can't repro the issue myself as I don't have an old enough device but the existing behaviour is unaffected. Maybe @jonsamp or @brentvatne can test this?

### CODE REVIEW

File: packages/@expo/cli/src/run/android/resolveGradlePropsAsync.ts [hunk 1]
```diff
@@ -60,5 +62,7 @@ async function getConnectedDeviceABIS(
   }
 
   const abis = await getDeviceABIsAsync(device);
-  return abis.filter((abi, i, arr) => arr.indexOf(abi) === i).join(',');
+
+  const validAbis = abis.filter((abi) => VALID_ARCHITECTURES.includes(abi));
+  return validAbis.filter((abi, i, arr) => arr.indexOf(abi) === i).join(',');
```
Comment (byCedric) [inline packages/@expo/cli/src/run/android/resolveGradlePropsAsync.ts:67]: What happens when there are no valid abis detected, do we still pass the gradle prop to RN?

Comment (alanjhughes) [reply packages/@expo/cli/src/run/android/resolveGradlePropsAsync.ts:67]: No, we have a check if it's falsey  later so we won't add it.

**Review by byCedric — APPROVED** [review]
Added 1 comment, make sure the tests passes before merging 😄

**Review by brentvatne — APPROVED** [review]
this fixed the issue for me.

however i did get a warning that was unrelated to this pr when testing:

```
 Validation Warning:

  Unknown option "server.forwardClientLogs" with value true was found.
  This is probably a typing mistake. Fixing it will remove this message.
```

cc @EvanBacon / @byCedric

**Comment by brentvatne** [comment]
@alanjhughes - looks like check-packages is failing related to this pr

**Comment by alanjhughes** [comment]
@brentvatne yes, just have to fix the tests
