### PR TITLE
fix(router): Ensure url params are decoded consistently across expo-router

### LINKED ISSUE #25323: [IOS][Android] Crash with Deep Links that include `%25` - Malformed decodeURI input
### Minimal reproducible example

https://github.com/MaxKebeDBZ/expo-router-deeplink-bug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Deep links that include an encoded % character `%25` make the app crash both on Android and IOS. I reproduced the issue the easiest using the Android ADB command. Example:

`adb shell am start -W -a android.intent.action.VIEW -d "myapp://products/facet/discountBands/up%20to%2050%25%20discount"`

This returns the following console error:

```
 ERROR  URIError: Malformed decodeURI input

This error is located at:
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

...and this error screen:  
Screenshot 2023-11-10 at 12 22 47

Other characters (at least `%23`, `%26` and `%2B`) don't make the app crash but result in unexpected returns from `useLocalSearchParams()`.

Example repo: https://github.com/MaxKebeDBZ/expo-router-deeplink-bug (see readme for other tests scenarios)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/maxime.kebe/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.7.0
    Expo Workflow: managed

### LINKED ISSUE #25570: Path parameters not URI decoded
### Minimal reproducible example

https://github.com/

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

`useLocalSearchParams()` path parameters are not URI decoded.

This issue primary effects the web, where the browser may encode the url

### Example route
`/[id]`

#### Expected
`site.com/test%3A123` -> `{ id: 'test:123' }`

#### Actual
`site.com/test%3A123` -> `{ id: 'test%3A123' }`

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 3.6.0 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2023.11.13.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by marklawlor**
# Why

`useGlobalSearchParams` and `useLocalSearchParams` treat URL search parameters differently.

Fix #25570
Fix #25323

# How

I'm not 100% happy with this solution, I thought we could do it more in the `getStateFromPath`/`getPathFromState` but I couldn't get it working. Instead we just decode them directly before saving to the global store, or when accessing from the navigation context.

# Test Plan

Unit tests cover multiple scenarios, ensuring the parameters are consistently decoded.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: packages/expo-router/src/hooks.ts [hunk 1]
```diff
@@ -92,10 +92,27 @@ export function useGlobalSearchParams<
...
+          ];
+        }
 
-function useOptionalLocalRoute<T extends RouteProp<ParamListBase>>(): T | undefined {
-  const route = React.useContext(NavigationRouteContext);
-  return route as T | undefined;
+        return [key, decodeURIComponent(value as string)];
+      } catch {
+        return [key, value];
+      }
```
Comment (ide) [inline packages/expo-router/src/hooks.ts:115]: The nested try-catch looks unnecessary. Better to write this as:
```ts
if (isArray) {
  try {} catch {}
} else {
  try {} catch {}
}
```
so that unexpected errors don't get caught

**Review by ide — COMMENTED** [review]
Add a regression test for invalid URL-encoded paths/parameters, such as `/start%end` -- it's useful to define and document the behavior of invalid URLs.

**Review by ide — APPROVED** [review]

**Comment by rileysk3** [comment]
Noob here. Just updated to sdk50 from 49. If I pass a firebase image url through local params  It becomes invalid due to the decoding removing %2f.  Use case is searching a user and then passing the details to profile screen. 

error code is 400, "Bad Request.".

There a way to revert or disable decoding?

**Comment by ide** [comment]
It sounds like the custom parameters might need to be URL-encoded when serializing them. For now you could probably work around the issue by double-encoding your URL.

**Comment by rileysk3** [comment]
Thanks, works for now
