### PR TITLE
[documents-picker][ios][android] add lastModified for native platforms

### LINKED ISSUE #37385: expo-document-picker not returning assed lastModifiedDate
### Minimal reproducible example

https://github.com/Xeitor/expo-document-picker-missing-lastModified-property-bug

### Steps to reproduce

# Versions
```
"expo": "~53.0.11",
"expo-document-picker": "^13.1.5",
"expo-status-bar": "~2.2.3",
"react": "19.0.0",
"react-native": "0.79.3"
```
# Platform
Samsung device (s22+) witth Android 15 and One UI 7.0

# Reproduction steps
pretty simple to reproduce, I created a sample app with the minimal code, just an upload button that calls `DocumentPicker getDocumentAsync`

the problem is, the `DocumentPickerResult` `DocumentPickerAsset` asset comes with an empty `lastModified` property event tough the file actually has a last modified date

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: Linux 6.8 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.14.0/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm
    IDEs:
      Android Studio: AI-243.22562.218.2431.13114758
    npmPackages:
      expo: ~53.0.11 => 53.0.11
      react: 19.0.0 => 19.0.0
      react-native: 0.79.3 => 0.79.3
    npmGlobalPackages:
      eas-cli: 16.6.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
╰─ npx expo-doctor@latest
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by hirbod**
# Why

expo-document-picker returns lastModified only on web. The docs state that this field is optional but its actually never returned on iOS and Android as it's not implemented.

# How

I decided to follow the [Web API specs](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified) for File:

The lastModified read-only property of the File interface provides the last modified date of the file as the number of milliseconds since the Unix epoch (January 1, 1970 at midnight). Files without a known last modified date return the current date.

Added for iOS and Android

Fixes #37385

# Test Plan

Tested on Web, iOS and Android.

~~@amandeepmittal or @Simek  - I am not onboarded with the docs yet.~~
~~lastModified is marked as optional. That needs to be removed. Would appreciate if one of you could pick it up until I figure out how it works.~~

Screenshot 2025-06-14 at 15 08 55

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-document-picker/ios/DocumentPickerResponse.swift [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import ExpoModulesCore
 
+// Disable swiftlint for redundant_optional_initialization. Optional initialization with nil is necessary for the Record constructors to work.
+// swiftlint:disable  redundant_optional_initialization
```
Comment (hirbod) [inline packages/expo-document-picker/ios/DocumentPickerResponse.swift]: I copied this from a different expo module. Shall I ignore it?

File: packages/expo-document-picker/ios/DocumentPickerModule.swift [hunk 2]
```diff
@@ -202,7 +214,8 @@ public class DocumentPickerModule: Module, PickingResultHandler {
     return uti as String
   }
 
-  private func createDocumentPicker(with options: DocumentPickerOptions) -> UIDocumentPickerViewController {
+  private func createDocumentPicker(with options: DocumentPickerOptions)
+    -> UIDocumentPickerViewController {
```
Comment (alanjhughes) [inline packages/expo-document-picker/ios/DocumentPickerModule.swift]:
```suggestion
  private func createDocumentPicker(with options: DocumentPickerOptions) -> UIDocumentPickerViewController {
```

File: packages/expo-document-picker/ios/DocumentPickerModule.swift [hunk 3]
```diff
@@ -148,7 +159,8 @@ public class DocumentPickerModule: Module, PickingResultHandler {
         kUTTagClassFilenameExtension,
         pathExtension as NSString, nil
       )?.takeRetainedValue() {
-        if let mimetype = UTTypeCopyPreferredTagWithClass(uti, kUTTagClassMIMEType)?.takeRetainedValue() {
+        if let mimetype = UTTypeCopyPreferredTagWithClass(uti, kUTTagClassMIMEType)?
+          .takeRetainedValue() {
```
Comment (alanjhughes) [inline packages/expo-document-picker/ios/DocumentPickerModule.swift]:
```suggestion
        if let mimetype = UTTypeCopyPreferredTagWithClass(uti, kUTTagClassMIMEType)
          ?.takeRetainedValue() {
```

File: packages/expo-document-picker/ios/DocumentPickerModule.swift [hunk 4]
```diff
@@ -97,7 +98,8 @@ public class DocumentPickerModule: Module, PickingResultHandler {
       }
     }
 
-    guard let contents = try? FileManager.default.contentsOfDirectory(atPath: path.absoluteString) else {
+    guard let contents = try? FileManager.default.contentsOfDirectory(atPath: path.absoluteString)
+    else {
```
Comment (alanjhughes) [inline packages/expo-document-picker/ios/DocumentPickerModule.swift]:
```suggestion
    guard let contents = try? FileManager.default.contentsOfDirectory(atPath: path.absoluteString) else {
```

File: packages/expo-document-picker/ios/DocumentPickerModule.swift [hunk 5]
```diff
@@ -49,7 +49,8 @@ public class DocumentPickerModule: Module, PickingResultHandler {
 
   func didPickDocumentsAt(urls: [URL]) {
     guard let options = self.pickingContext?.options,
-    let promise = self.pickingContext?.promise else {
+      let promise = self.pickingContext?.promise
+    else {
```
Comment (alanjhughes) [inline packages/expo-document-picker/ios/DocumentPickerModule.swift]:
```suggestion
      let promise = self.pickingContext?.promise else {
```

File: packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentDetailsReader.kt [hunk 6]
```diff
@@ -21,7 +22,30 @@ class DocumentDetailsReader(private val context: Context) {
...
         }
         val mimeType = context.contentResolver.getType(uri)
-        return DocumentInfo(uri, name, mimeType, size)
+
+        // Get last modified date or use current date if not available.
+        // This follows the Web API spec.
+        // https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified
+        val lastModified = try {
+          // First try to get it from the content resolver
+          val lastModifiedColumn = cursor.getColumnIndex("last_modified")
```
Comment (alanjhughes) [inline packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentDetailsReader.kt]:
```suggestion
          val lastModifiedColumn = cursor.getColumnIndex(DocumentsContract.Document.COLUMN_LAST_MODIFIED)
```
We can use the constant here

File: packages/expo-document-picker/ios/DocumentPickerResponse.swift (hunk 1 above)
Comment (alanjhughes) [reply packages/expo-document-picker/ios/DocumentPickerResponse.swift]: Not sure we need it, files like [this](https://github.com/expo/expo/blob/main/packages/expo-camera/ios/Common/PictureOptions.swift) aren't triggering it 🤔

Comment (alanjhughes) [inline packages/expo-document-picker/ios/DocumentPickerResponse.swift]:
```suggestion
// Disable swiftlint for redundant_optional_initialization. Optional initialization with nil is necessary for the Record constructors to work.
// swiftlint:disable redundant_optional_initialization
```

**Review by alanjhughes — APPROVED** [review]
Looks good 👍

File: packages/expo-document-picker/ios/DocumentPickerResponse.swift (hunk 1 above)
Comment (hirbod) [reply packages/expo-document-picker/ios/DocumentPickerResponse.swift]: The swiftlint triggered when I initialized with nil.

File: packages/expo-document-picker/ios/DocumentPickerModule.swift (hunk 5 above)
Comment (hirbod) [reply packages/expo-document-picker/ios/DocumentPickerModule.swift]: How do you fix these formats? I tried 4 different formatters from the VSCode marketplace and even ran swiftlint --fix from the CLI but it's somehow not working as expected

File: packages/expo-document-picker/ios/DocumentPickerResponse.swift (hunk 1 above)
Comment (hirbod) [reply packages/expo-document-picker/ios/DocumentPickerResponse.swift]: The package you referenced does not use nil.
But [expo-print has it](https://github.com/expo/expo/blob/54d745bed821a8054a52237739a7b4571448bf89/packages/expo-print/ios/PrintResponse.swift)

File: packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentDetailsReader.kt (hunk 6 above)
Comment (hirbod) [reply packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentDetailsReader.kt]: Ty, added

File: packages/expo-document-picker/ios/DocumentPickerResponse.swift (hunk 1 above)
Comment (hirbod) [reply packages/expo-document-picker/ios/DocumentPickerResponse.swift]: Instead of disabling it globally, I added it per line now.

File: packages/expo-document-picker/ios/DocumentPickerModule.swift (hunk 3 above)
Comment (hirbod) [reply packages/expo-document-picker/ios/DocumentPickerModule.swift]: This would actually cause an error

**Comment by Simek** [comment]
To update the docs part, run `et gdad -p document-picker` and commit the updated JSON file. 

You can also verify the changes locally by running docs app, and visiting the `unversioned` (Next) page for the package. 

For more detailed guide see:
* https://github.com/expo/expo/tree/main/docs#update-api-reference-docs

**Comment by hirbod** [comment]
@Simek thank you very much. Took me a while, but I finally figured it out (had to upgrade Node). I can see it automatically removed (optional) based on the[ types for next (unversioned)](https://github.com/expo/expo/pull/37429/commits/189f1202542abf41815598d36f8b6be91a5625e3). Does that mean it will be included in SDK 54, or will it automatically be available in SDK 53 if someone publishes?

File: packages/expo-document-picker/ios/DocumentPickerModule.swift (hunk 3 above)
Comment (alanjhughes) [reply packages/expo-document-picker/ios/DocumentPickerModule.swift]: Ok, I'd just leave it on the same line then but it's no a big deal. Trailing `?` just looks weird

File: packages/expo-document-picker/ios/DocumentPickerModule.swift (hunk 5 above)
Comment (alanjhughes) [reply packages/expo-document-picker/ios/DocumentPickerModule.swift]: I just use swiftlint from the cli but it doesn't fix everything. Most of the rules you just get used to and write it that way. If you run `swiftlint --rules` it will tell you which ones it can correct

**Review by alanjhughes — APPROVED** [review]

File: packages/expo-document-picker/ios/DocumentPickerModule.swift (hunk 5 above)
Comment (hirbod) [reply packages/expo-document-picker/ios/DocumentPickerModule.swift]: Ok, addressed. Gotta learn those rules

**Comment by Simek** [comment]
> Does that mean it will be included in SDK 54, or will it automatically be available in SDK 53 if someone publishes?

It depends, currently (by default) the change will only by available starting from the SDK 54, but if we decide to cherry pick this back into `sdk-53` branch, we will need to regenerate the docs data from the SDK branch in a follow up commit, but that's on person from the team doing the picks.
