### PR TITLE
[expo-file-system][next] Fix inconsistent behavior when using special chars in filenames.

### LINKED ISSUE #35619: [expo-file-system/next] Incorrect handling of URI with certain characters
### Minimal reproducible example

https://github.com/cyanChill/expo-file-system-next-uri

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Compared to the regular `expo-file-system` (based off of using `getInfoAsync()`), the `Directory` & `File` classes incorrectly handles URIs containing spaces, a "#", or a "%" (in this case, I mainly see "%20") as they throw an error such as:

```
[Error: Call to function 'FileSystemFile.constructor' has been rejected.
→ Caused by: The 1st argument cannot be cast to type expo.modules.kotlin.types.EmptyKType@dcaa3ea3 (received class java.lang.String)
→ Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 30: /storage/emulated/0/Music/Test File.mp3]
```

A quick comparison table from the different behaviors seen:
|                                  | `getInfoAsync()`                           | `File()`     |
| -------------------------------- | ------------------------------------------ | ------------ |
| Space in URI (`Test File.mp3`)   | Returns File Info                          | Throws Error |
| `#` in URI (`Test#File.mp3`)     | Returns File Info                          | Throws Error |
| `%20` in URI (`Test%20File.mp3`) | Doesn't find file, but doesn't throw error | Throws Error |

> [!NOTE]
> With a `#` in the URI, what's seen by the `Directory` & `File` constructor is everything before the `#` - so it'll look at it like a directory (throwing a permissions error if the file isn't from the app's storage).

This isn't that big of a deal when using the `File` class as we can manually fix the URI on our end, but becomes a problem with `Directory().list()` as it'll throw an error if it tries to get a `File` with one of those characters.

I saw this comment in the PR review for the 1st version of the Next version mentioning a convertor for the URI which I don't know is being used: https://github.com/expo/expo/pull/29995#discussion_r1665330071.

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 31, 34, 35
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 34.0.0, 35.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-35 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ~52.0.40 => 52.0.40
      react: 18.3.1 => 18.3.1
      react-native: 0.76.7 => 0.76.7
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Fixes https://github.com/expo/expo/issues/35619#issue-2937438626

# How

This functionality mostly worked already, but node had no encoding for spaces in the linux code – think we can safely add it.
Some examples from the original issue are working as expected, with the first argument being a file:// uri any #queryparams will get stripped.

# Test Plan

Added more tests to cover this, tested on both iOS and Android.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/expo-file-system/android/src/main/java/expo/modules/filesystem/next/FileSystemDirectory.kt [hunk 1]
```diff
@@ -42,9 +42,10 @@ class FileSystemDirectory(file: File) : FileSystemPath(file) {
     validateType()
     validatePermission(Permission.READ)
     return file.listFiles()?.map {
+      val uriString = Uri.fromFile(it).toString()
       mapOf(
         "isDirectory" to it.isDirectory,
-        "path" to it.path
+        "uri" to if (uriString.endsWith("/")) uriString else "$uriString/"
```
Comment (jakex7) [inline packages/expo-file-system/android/src/main/java/expo/modules/filesystem/next/FileSystemDirectory.kt:48]: I'm not sure about adding a trailing slash to a non directory resources. It might be a bit confusing

Comment (aleqsio) [reply packages/expo-file-system/android/src/main/java/expo/modules/filesystem/next/FileSystemDirectory.kt:48]: Hmm, it's internal only, we clean it up when creating the actual file/directory instances.

**Review by jakex7 — APPROVED** [review]
