### PR TITLE
[expo-contacts][Android] Fix presentFormAsync fields pre fill

### LINKED ISSUE #5519: [Android] Contacts.presentFormAsync does not pre fill name, emails and phone numbers
### Environment

```sh
Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: 34.0.4 => 34.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.1 => 3.11.1 
```

#### Targets

- iOS
- Android

#### Tested On

- Samsung Galaxy Tab S2 - `Android 7.0.0`
- Samsung Galaxy A5 (2017) - `Android 8.0.0`
- Nokia 6.1 - `Android 9.0.0`

### Steps to Reproduce

```js
import * as Contacts from 'expo-contacts';

const contactId = null;
const contact = {
  [Contacts.Fields.Company]: 'Rad Company Name',
  [Contacts.Fields.FirstName]: 'John',
  [Contacts.Fields.Emails]: [
    {
      email: 'john@domain.com',
      label: 'Email',
    },
  ],
  [Contacts.Fields.PhoneNumbers]: [
    {
      number: '+61243123456',
      isPrimary: true,
      label: 'Phone',
    },
  ],
};
const formOptions = {
  isNew: true,
};

await Contacts.presentFormAsync(contactId, contact, formOptions);
```

### Expected Behavior

New contact form should be pre-filled with Company, First Name, Email Address, and Phone Number.

### Actual Behavior

New contact form is only pre-filled with Company.

### Reproducible Demo

https://snack.expo.io/@oneblinkdevelopers/expo-contacts-pre-fill

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #5519.

# How

In `map Value`, we tried to cast `Bool` to `String`. This part threw an cast exception. We caught it but, we didn't parse the rest of the date from js. That's why phone number and email weren't added to the form. 

For some reason, putting the name into `ContactsContract.Intents.Insert.DATA`, not set it in the form.

# Test Plan

- test-suite - passed
- https://snack.expo.io/@oneblinkdevelopers/expo-contacts-pre-fill - worked

### CODE REVIEW

**Comment by bbarthec** [comment]
@mczernek is the one that can shed some light on your solution 😉

File: packages/expo-contacts/android/src/main/java/expo/modules/contacts/models/BaseModel.java [hunk 1]
```diff
@@ -45,8 +45,14 @@ protected void mapValue(Map<String, Object> readableMap, String key) {
     }
 
     protected void mapValue(Map<String, Object> readableMap, String key, String alias) {
-        if (readableMap.containsKey(key))
-            map.putString(alias == null ? key : alias, (String) readableMap.get(key));
+        if (readableMap.containsKey(key)) {
+            Object value = readableMap.get(key);
+            if (value instanceof Boolean ) {
```
Comment (tsapeta) [inline packages/expo-contacts/android/src/main/java/expo/modules/contacts/models/BaseModel.java]:
```suggestion
            if (value instanceof Boolean) {
```

**Review by tsapeta — APPROVED** [review]

**Review by bbarthec — APPROVED** [review]
