### PR TITLE
[barcode-scanner][camera][iOS] update requestPermissionsAsync microphone validation

### LINKED ISSUE #11736: On iOS, Expo Camera requires NSMicrophoneUsageDescription key to use the feature
### Summary of Issue 
Hi, I just started using Expo Camera on my bare RN project and facing some issues.
I followed the installation process [here](https://github.com/expo/expo/tree/master/packages/expo-camera) and according to [Configure for iOS](https://github.com/expo/expo/tree/master/packages/expo-camera#configure-for-ios), I only need to add `NSCameraUsageDescription` key but doing so produces following error:
```
This app is missing either NSCameraUsageDescription or 
NSMicrophoneUsageDescription, so audio/video services will fail. Add one of
these entries to your bundle's Info.plist.
```
But adding `NSMicrophoneUsageDescription` key solves the error.
I simply copied the code from [here](https://docs.expo.io/versions/latest/sdk/camera/#usage) and I believe it shouldn't require permission for mic since I'm not going to use camera to take a video. So it should rather considered optional.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.4.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.0.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare
```
 
### Steps to Reproduce
1. Create bare RN app with unimodules installed.
2. Install Expo Camera following this [page](https://github.com/expo/expo/tree/master/packages/expo-camera)
2. Copy the example from [here](https://docs.expo.io/versions/latest/sdk/camera/#usage)
3. Running it throws this error:
Simulator Screen Shot - iPhone 12 - 2021-01-25 at 17 35 43

### PR DESCRIPTION
**Pull request by ajsmth**
# Why

Closes #11736 

BarcodeScanner requires developers to include a `NSMicrophoneUsageDescription` entry in their apps Info.plist - this isn't necessary as the BarcodeScanner doesn't capture any audio.

Likewise, any developer that uses the `Camera` module will need to specify `NSMicrophoneUsageDescription` even if they are using it just for photos.

There should be a way for developers to have more granular control over what permissions are required based on their use case. 

This PR aims to remove the microphone requirement from BarcodeScanner, and add additional methods to `Camera.requestPermissionsAsync()` to allow developers request only the camera permission if their apps do not need microphone functionality.  

# How

BarcodeScanner: Removed the check for the presence of `NSMicrophoneUsageDescription` in the BarcodeScanner module

Camera: Added additional methods to request permissions by type:
```
Camera.requestCameraPermissionsAsync()
Camera.requestMicrophonePermissionsAsync()
```

# Test Plan

Gist: https://gist.github.com/ajsmth/a28326f0f7c258246c8251f0d8e21406

## BarcodeScanner:

- applications without `NSMicrophoneUsageDescription` entry in Info.plist should no longer crash when `requestPermissionsAsync()` is called

## Camera 

- applications without `NSMicrophoneUsageDescription` entry in Info.plist should no longer crash when `requestPermissionsAsync(Camera.Constants.Permission.videoOnly)` is called

- applications without `NSMicrophoneUsageDescription` entry in Info.plist **should** crash when `requestPermissionsAsync()` or `requestPermissionsAsync(Camera.Constants.Permission.all)`  is called (default behaviour)

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

### CODE REVIEW

**Comment by ajsmth** [comment]
@bbarthec  would like your feedback on this before updating the docs!

File: packages/expo-barcode-scanner/ios/EXBarCodeScanner/EXBarCodeCameraRequester.m [hunk 1]
```diff
@@ -18,9 +18,8 @@ - (NSDictionary *)getPermissions
   AVAuthorizationStatus systemStatus;
   UMPermissionStatus status;
   NSString *cameraUsageDescription = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSCameraUsageDescription"];
-  NSString *microphoneUsageDescription = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSMicrophoneUsageDescription"];
-  if (!(cameraUsageDescription && microphoneUsageDescription)) {
-    UMFatal(UMErrorWithMessage(@"This app is missing either 'NSCameraUsageDescription' or 'NSMicrophoneUsageDescription', so audio/video services will fail. Add both of these entries to your bundle's Info.plist."));
+  if (!(cameraUsageDescription)) {
```
Comment (lukmccall) [inline packages/expo-barcode-scanner/ios/EXBarCodeScanner/EXBarCodeCameraRequester.m:21]:
```suggestion
  if (!cameraUsageDescription) {
```

File: packages/expo-camera/ios/EXCameraVideoPermissionRequester.m [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
++ (NSString *)permissionType {
+  return @"camera";
+}
+
+- (NSDictionary *)getPermissions
+{
+  AVAuthorizationStatus systemStatus;
+  UMPermissionStatus status;
+  NSString *cameraUsageDescription = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSCameraUsageDescription"];
+  if (!(cameraUsageDescription)) {
```
Comment (lukmccall) [inline packages/expo-camera/ios/EXCameraVideoPermissionRequester.m:21]:
```suggestion
  if (!cameraUsageDescription) {
```

File: apps/bare-expo/ios/Podfile.lock [hunk 3]
```diff
@@ -159,9 +159,17 @@ PODS:
     - React
   - expo-dev-menu (0.4.1):
     - expo-dev-menu-interface
+    - expo-dev-menu/Main (= 0.4.1)
```
Comment (bbarthec) [inline apps/bare-expo/ios/Podfile.lock:162]: I believe any change in this file that is not directly connected with the module you're working on right now should be extracted as a separate PR 😉 
```suggestion
```

File: apps/bare-expo/ios/Podfile.lock [hunk 4]
```diff
@@ -159,9 +159,17 @@ PODS:
...
     - React
   - expo-dev-menu-interface (0.2.0):
     - React
+  - expo-dev-menu/Main (0.4.1):
+    - expo-dev-menu-interface
+    - expo-dev-menu/Vendored
+    - React
+  - expo-dev-menu/Vendored (0.4.1):
+    - expo-dev-menu-interface
+    - React
```
Comment (bbarthec) [inline apps/bare-expo/ios/Podfile.lock:172]:
```suggestion
```

File: apps/bare-expo/ios/Podfile.lock [hunk 5]
```diff
@@ -1281,7 +1289,7 @@ SPEC CHECKSUMS:
   EXPermissions: 8f8c1c05580c4e02d4ee2c8dd74bfe173ff6a723
   expo-dev-client: e7b6c924dad57d75ae7e0fd18f7dca2d8fb1118a
   expo-dev-launcher: ba817d68d83bffae03beebb59b14341ac27f1833
-  expo-dev-menu: 9cab52a55688aef281dee77a101af83658c59b48
+  expo-dev-menu: 491591fff3e5578a3f9ac9914c9b5f92e91ae1de
```
Comment (bbarthec) [inline apps/bare-expo/ios/Podfile.lock:1292]:
```suggestion
  expo-dev-menu: 9cab52a55688aef281dee77a101af83658c59b48
```

**Review by bbarthec — CHANGES_REQUESTED** [review]
I dislike the idea of this parameter 🤔 
If the module has multiple permissions requirements (some of these might be optional) we're proposing multiple methods to ask for each of them individually (see for example [`Location#foreground/background`](https://docs.expo.io/versions/v41.0.0/sdk/location/#locationrequestforegroundpermissionsasync) or [Calendar#calendar/reminders](https://docs.expo.io/versions/v41.0.0/sdk/calendar/#calendarrequestcalendarpermissionsasync)).

I guess we want to have something like this:
```
/**
 * Requests both camera & microphone permissions.
 * (Will behave the very same it is right now)
 */
Camera.requestPermissionsAsync()

/**
 * Requests only camera permissions.
 */
Camera.requestCameraPermissionsAsync()

/**
 * Requests microphone permissions.
 */
Camera.requestMicrophonePermissionsAsync()
```

**Comment by bbarthec** [comment]
Summon @byCedric as he was the author of splitting `Location.permissions` into multiple methods 🧙‍♂️

**Comment by byCedric** [comment]
I think we don't have parameters to permission requesters in general. I'm open to that idea though, but just for consistency I would go for the split one.

File: packages/expo-camera/ios/EXCamera/EXCameraManager.m [hunk 6]
```diff
@@ -73,6 +75,10 @@ - (NSDictionary *)constantsToExport
                @"cinematic": @(EXCameraVideoStabilizationModeCinematic),
                @"auto": @(EXCameraAVCaptureVideoStabilizationModeAuto)
                },
+           @"Permission": @{
+               @"all": @(EXCameraPermissionAll),
+               @"videoOnly": @(EXCameraPermissionVideoOnly),
+               },
```
Comment (lukmccall) [inline packages/expo-camera/ios/EXCamera/EXCameraManager.m:81]: We don't have to export those values, do we? Especially that, we don't use them anyway. Or maybe I missed something?  
cc @bbarthec

**Review by bbarthec — CHANGES_REQUESTED** [review]
On `iOS` it looks fine to me 👍, but what about Android & web? 🤔 
I guess calling these methods would fail miserably with `Uncaught TypeError: CameraManager.{request,get}{Camera,Microphone}PermissionsAsync is not a function`

**Comment by ajsmth** [comment]
> On `iOS` it looks fine to me 👍, but what about Android & web? 🤔
> I guess calling these methods would fail miserably with `Uncaught TypeError: CameraManager.{request,get}{Camera,Microphone}PermissionsAsync is not a function`

Yes - I'm going to add these methods to Android and web, just need to test them out a bit more!

**Comment by bbarthec** [comment]
Let's do that as a single PR then 🙂

**Comment by ajsmth** [comment]
Here is a gist for easily testing in Sandbox: https://gist.github.com/ajsmth/a28326f0f7c258246c8251f0d8e21406

File: packages/expo-camera/CHANGELOG.md [hunk 7]
```diff
@@ -7,6 +7,7 @@
 ### 🎉 New features
 
 - On iOS added new `codec` parameter in `recordAsync()` method and new method `getAvailableVideoCodecsAsync()` that queries the device for available video codecs. ([#12772](https://github.com/expo/expo/pull/12772) by [@ajsmth](https://github.com/ajsmth))
+- On iOS added new `requestCameraPermissions()` and `requestMicrophonePermissions()` methods which gives more fine-grained control over requested permissions. ([#12860](https://github.com/expo/expo/pull/12772) by [@ajsmth](https://github.com/ajsmth))
```
Comment (bbarthec) [inline packages/expo-camera/CHANGELOG.md:10]:
```suggestion
- Added new `requestCameraPermissionsAsync()`, `requestMicrophonePermissionsAsync()`, `getCameraPermissionsAsync()` and `getMicrophonePermissionsAsync()` methods which gives more fine-grained control over requested permissions. ([#12860](https://github.com/expo/expo/pull/12772) by [@ajsmth](https://github.com/ajsmth))
```

**Review by bbarthec — APPROVED** [review]
Yeah, now it looks comprehensive 👏 
Impressive work 🥳 
Adjust CHANGELOG and I'm ok with that 👍 
Side note regarding `web`: Does `requestPermissionsAsync()` (methods that should ask for both `camera` & `microphone` is actually doing so? 🤔 
I see that this method on web is asking only for `camera` and I see it was always that way 🤔 ?
We should probably adjust it to match mobiles' behaviour?

File: packages/expo-camera/CHANGELOG.md (hunk 7 above)
Comment (ajsmth) [reply packages/expo-camera/CHANGELOG.md:10]: Good call - although `requestPermissionAsync()` for iOS has the same behaviour - only requests access to camera, the microphone prompt only comes up when audio capture begins (e.g `recordAsync()`) is called

Comment (ajsmth) [reply packages/expo-camera/CHANGELOG.md:10]: also `recordAsync()` is not available on web so this method is just to keep parity (no need for microphone permissions) - although this is commented out as a TODO so maybe I will look into tackling video capture for web at some point!

**Comment by EvanBacon** [comment]
Iirc iOS Safari requires microphone permission but could be wrong.

**Comment by ajsmth** [comment]
> Iirc iOS Safari requires microphone permission but could be wrong.

I just tested and it seems to work with just the camera permissions - needs to be `https` though

File: packages/expo-camera/src/WebCameraUtils.ts [hunk 8]
```diff
@@ -377,7 +377,7 @@ export function setVideoSource(
   video: HTMLVideoElement,
   stream: MediaStream | MediaSource | Blob | null
 ): void {
-  const createObjectURL = window.URL.createObjectURL ?? window.webkitURL.createObjectURL;
+  const createObjectURL = window?.URL.createObjectURL ?? window.webkitURL.createObjectURL;
```
Comment (bbarthec) [inline packages/expo-camera/src/WebCameraUtils.ts:380]:
```suggestion
  const createObjectURL = window?.URL.createObjectURL ?? window?.webkitURL.createObjectURL;
```
If `window` is optional then it should rather be that way 🤔

Comment (ajsmth) [reply packages/expo-camera/src/WebCameraUtils.ts:380]: I will revert as this was not the correct fix, it was caused by something else that has since been updated
