### PR TITLE
[iOS][test-suite][notifications] Disable foreign notif test

### LINKED ISSUE #9882: [iOS][notifications] getPresentedNotificationAsync() does not return foreign notifications info
### Summary of Issue

`getPresentedNotificationAsync()` does not return foreign notifications info and thus test is failing

### Environment

Expo CLI 3.24.2 environment info:
```
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.24.2
```

Device:
```
	iOS version: OS 13.6
	Model: iPhone 11
```

### Reproducible Demo

- on master launch `Expo Client` with `test-suite`
- launch `expo-notifications` tests and observe:
```
+++ :broken_heart: expo-notifications getPresentedNotificationsAsync() includes the foreign persistent notification
toContain: Expected [  ] to contain <jasmine.objectContaining(Object({ request: <jasmine.objectContaining(Object({ identifier: <jasmine.stringMatching(/^expo-notifications:\/\/foreign_notifications/)>, content: <jasmine.objectContaining(Object({ data: <jasmine.objectContaining(Object({ android.contains.customView: true }))> }))> }))> }))>.
```

Screen Shot 2020-08-21 at 13 32 55

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Resolves https://github.com/expo/expo/issues/9882

### CODE REVIEW

File: apps/test-suite/tests/NewNotifications.js [hunk 1]
```diff
@@ -842,13 +842,16 @@ export async function test(t) {
         );
       });
 
-      if (Constants.appOwnership === 'expo') {
+      // TODO: Limited this test as on iOS it never succeeds and @lukmccall
```
Comment (bbarthec) [inline apps/test-suite/tests/NewNotifications.js:845]:
```suggestion
      // TODO: Limited this test to Android platform only as on iOS it never succeeds
```

**Review by sjchmiela — APPROVED** [review]
👍 👍 👍  🍎
