### PR TITLE
[image-picker][android] fix:  Adjust video metadata extraction to account for rotation

### LINKED ISSUE #37657: [image-picker] videos on android have wrong width/height if filmed rotated
Certain videos on android have the width/height swapped. To me this sounds similar to https://github.com/expo/expo/pull/32534, but for videos instead

### Minimal reproducible example

https://github.com/mozzius/aspectratio-repro

### Steps to reproduce

1. Open the repro on Android
2. Pick the vertical video (I've left a sample video in the repo but you can record your own)
3. Observe that the aspect ratio is wrong

https://github.com/user-attachments/assets/c9e7186f-16e1-4dd9-9425-c2ed8f70626a

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.2 - ~/.nvm/versions/node/v20.19.2/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.19.2/bin/npm
      Watchman: 2025.06.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Android Studio: 2024.3 AI-243.26053.27.2432.13536105
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.12 => 53.0.12
      react: 19.0.0 => 19.0.0
      react-native: 0.79.4 => 0.79.4
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by hirbod**
# Why

MediaMetadataRetriever reports the encoded frame size, which is often landscape (e.g. 1920 × 1080) even for portrait clips that are meant to be displayed with a 90°/270° rotation flag.
  - iOS, on the other hand, derives the size from AVAssetTrack.naturalSize.applying(preferredTransform) which already compensates for rotation, so it returns 1080 × 1920 for the same file.
  - Therefore when rotation % 180 ≠ 0 the width/height values must be swapped to be semantically consistent with iOS and with what developers expect to see.

# How

- Updated MediaHandler to extract video width and height while considering the rotation metadata.
- Ensured consistent behavior across platforms by swapping width and height for portrait videos.

Fixes #37657

# Test Plan

bare-expo and 6-7 different video files, and the repro file

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by hirbod** [comment]
@mozzius does expo-media-library suffer from the same issue?

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt [hunk 1]
```diff
@@ -101,16 +101,32 @@ internal class MediaHandler(
...
+      // Android returns the encoded width/height which do not take the display rotation into
+      // account. For videos recorded in portrait mode the encoded dimensions are often landscape
+      // (e.g. 1920x1080) paired with a 90°/270° rotation flag.  iOS adjusts these values before
+      // reporting them, so to keep the behaviour consistent across platforms we swap the width
+      // and height when the rotation indicates the video should be displayed in portrait.
+      if (rotation % 180 != 0) {
+        val tmp = width
+        width = height
+        height = tmp
+      }
```
Comment (alanjhughes) [inline packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt]:
```suggestion
if (rotation % 180 != 0) {
    width = height.also { height = width }
}
```

**Review by alanjhughes — APPROVED** [review]

File: packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt (hunk 1 above)
Comment (hirbod) [reply packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt]: At first I thought it looked terrible, but once you read it, it’s beautiful :D

**Comment by mozzius** [comment]
> @mozzius does expo-media-library suffer from the same issue?

No, doesn't seem so

https://github.com/user-attachments/assets/d89735dd-cd3f-44d7-a87d-ade291933f44
