### PR TITLE
[local-authentication] Use sdk version flags and hardcoded system features

### LINKED ISSUE #8964: [expo-local-authentication][android][bare] Build fails, cannot find symbols FEATURE_FACE or FEATURE_IRIS
### Summary of Issue (just a few sentences)
I have been using expo-local-authentication version 9.0.0 with a bare react native workflow. Upgrading to 9.1.1 gave me the following error when building with Android. 

```
/my-project/node_modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java:93: error: cannot find symbol
    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_FACE)) {
                                                       ^
  symbol:   variable FEATURE_FACE
  location: class PackageManager
/my-project/node_modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java:96: error: cannot find symbol
    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_IRIS)) {
                                                       ^
  symbol:   variable FEATURE_IRIS
  location: class PackageManager
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-local-authentication:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 3.21.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.9

Building on Pixel 3a XL emulator with Android API 29.

### Expected behavior 
Build should not fail.

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #8964

# How

Because we won't be able to use the constants in compile target 28, we need to hardcode them. I also added sdk versioning flags to prevent unnecessary lookups.

# Test Plan

Set `ext.compileSdkVersion` to `28` in `apps/bare-expo/android/build.gradle` and run with `yarn android`

### CODE REVIEW

File: packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java [hunk 1]
```diff
@@ -87,15 +87,23 @@ public void supportedAuthenticationTypesAsync(final Promise promise) {
...
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
+      if (mPackageManager.hasSystemFeature("android.hardware.fingerprint")) {
+        results.add(AUTHENTICATION_TYPE_FINGERPRINT);
+      }
     }
-    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_IRIS)) {
-      results.add(AUTHENTICATION_TYPE_IRIS);
+
+    if (Build.VERSION.SDK_INT >= 29) {
+      if (mPackageManager.hasSystemFeature("android.hardware.biometrics.face")) {
```
Comment (tsapeta) [inline packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java:98]: Can you also put some comments to replace these strings with appropriate PackageManager properties in the future once we drop support for Android SDK 28?

**Review by tsapeta — APPROVED** [review]
